### ISSUE TITLE
[BUG] [Branding] cannot use custom branding feature

### ISSUE THREAD

**Issue by JujuElk** [opensearch-project/OpenSearch-Dashboards#1000]
Hi all, 

I am trying to use OSDashboard custom branding with 1.2.0 version of OSD. But i failed, maybe I missed something ? 

I am adding these lines in my opensearch_dashboards.yml 
 `opensearchDashboards.branding:`
   `   applicationTitle: "Service Analytics Dashboard"`

when I start OSD to get the result i have this following error : 
_Error: [config validation of [opensearch].branding]: definition for this key is missing_

I did not find any documentation for custom branding, so i am following this youtube video : https://www.youtube.com/watch?v=ouEIZbFTPuo&ab_channel=QingyangHu 

Thanks for your help ! 

Best, 
Julien

**Comment by kavilla** [comment]
> Error: [config validation of [opensearch].branding]: definition for this key is missing

Can you share your config? For me the error message is saying you are using `opensearch.Branding` but it should be `opensearchDashboards.branding`

**Comment by JujuElk** [comment]
Hi kavilla, 

I did not have pid.file in my opensearch_dashboards.yml, that caused the problem with my service osdashboard start because of a conflict with another app.pid. Sorry for this false issue. I close it

Thanks

**Comment by kavilla** [comment]
Glad you can get it resolved! Thanks for the update!
