### ISSUE TITLE
[BUG] Opening artifacts.opensearch.org give me access denied

### ISSUE THREAD

**Issue by solar-core** [opensearch-project/OpenSearch-Dashboards#1038]
**Describe the bug**
I am trying to install sql plugin into opensearch, but when i try to install, it show me this link
https://artifacts.opensearch.org/downloads/kibana-plugins/opensearch-sql/opensearch-sql-1.1.0.zip
and write no valid url was found

**To Reproduce**
1. Try to install Sql plugin
2. Try to download plugin from link https://artifacts.opensearch.org/downloads/kibana-plugins/opensearch-sql/opensearch-sql-1.1.0.zip
3. Shows me access denied

**Expected behavior**
Clear install, or at least download this plugin manualy, to install it manualy

**Plugins**
On screenshot

**Screenshots**
![111](https://user-images.githubusercontent.com/57063825/146940459-4f3f12bb-12d7-4184-8856-75418153d71d.png)

**Host/Environment (please complete the following information):**
 - OS: Docker container
 - Version 1.1.0

**Comment by kavilla** [comment]
Hello @solar-core,

A couple of things to un-bundle here.

First off, thanks for opening this! That is definitely a bug the auto-generate URL using `kibana-plugins`. But before that:
* The SQL plugin is an OpenSearch plugin so you would want to install into OpenSearch not OpenSearch Dashboards [[REF]](https://opensearch.org/docs/latest/opensearch/install/plugins/#available-plugins).
* The OpenSearch Dashboards plugin corresponding plugin would be Query Workbench plugin [[REF]](https://opensearch.org/docs/latest/search-plugins/sql/workbench/), which I see you already have installed. I'm assuming you are just using the image from docker hub to which case all the OpenSearch Projects released plugins should be included in OpenSearch and OpenSearch Dashboards [[REF (prefixed with opensearch-)]](https://opensearch.org/docs/latest/opensearch/install/plugins/#available-plugins).  So if you are trying to install anything from OpenSearch then you should be able to run it out-of-the-box.

But if you were just verifying the install method and knew the above points then please ignore.

For the bug, there is a workaround where you can install where you can pass the direct URL: for 1.2 query workbench: 
```
https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/1.2.0/512/linux/x64/builds/plugins/queryWorkbenchDashboards-1.2.0.zip
```
 
So the full URL path would be: 

```
./opensearch-dashboards-plugin install https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/1.2.0/512/linux/x64/builds/plugins/queryWorkbenchDashboards-1.2.0.zip
```

I got this path by downloading https://opensearch.org/downloads.html the distribution and opening up the `manifest.yml` within the distribution and finding the corresponding plugin.

However for fixing this bug, passing by name of the plugin hits code that will auto-generate a URL and it should not include `kibana-plugins`  and we can change it [here](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/cli_plugin/install/settings.js#L42) but we will need a replacement that doesn't require us to know the proper build number. @dblock, @peternied, @peterzhuamazon, is there a `latest` or `version` plugins URL that is available so we can default to when someone passed a plugin name if we want to support this functionality?

**Comment by peternied** [comment]
@solar-core @kavilla I've created a feature request in OpenSearch-Build with a couple of options for supporting `latest`
