### ISSUE TITLE
[BUG] Dev Tools 'Open Documentation' link leads to non-existent page.

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/OpenSearch-Dashboards#1041]
**Describe the bug**

When using the dev tools, clicking on the gear in the IDE and then the "OPen Documentation" link brings you to a page that doesn't exist: https://www.opensearch.org/guide/en/elasticsearch/reference/main/search-search.html

**To Reproduce**

1. Go to 'Management' -> 'Dev Tools'
2. Click on the small blue wrench in the upper right hand corner of the IDE.
3. Click on the link named 'Open Documentation'
4. Arrive at 404: https://www.opensearch.org/guide/en/elasticsearch/reference/main/search-search.html

**Expected behavior**
Link should point to current proper documentation. 

**OpenSearch Version**
1.2.0

**Dashboards Version**
1.2.0

**Screenshots**

![image](https://user-images.githubusercontent.com/96254688/147141297-36057eb1-ad11-4f4d-898c-06a86d97b69c.png)

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser: Chrome Version 96.0.4664.110 (Official Build) (64-bit)

#592

**Comment by kavilla** [comment]
Thanks for opening for tracking purposes. Closing as addressing in 
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/938 which has yet to be released.
