### ISSUE TITLE
OpenSearch Curator

### ISSUE THREAD

**Issue by dawo0od** [opensearch-project/OpenSearch-Dashboards#1046]
**Is your feature request related to a problem? Please describe.**

Can't find curator functionality

**Describe the solution you'd like**

We are planning to move from ElasticSearch to OpenSearch but can't find curator functionality to remove old indices.

**Comment by tmarkley** [comment]
This is relevant to OpenSearch, not OpenSearch Dashboards. There is already an issue open for this topic: https://github.com/opensearch-project/OpenSearch/issues/1352
