### ISSUE TITLE
running ./opensearch-dashboards [error][data][opensearch] [TimeoutError]: Request timed out  

### ISSUE THREAD

**Issue by phi06** [opensearch-project/OpenSearch-Dashboards#1054]
[error][data][opensearch] [TimeoutError]: Request timed out
  log   [08:48:55.442] [warning][savedobjects-service] Unable to connect to OpenSearch. Error: Request timed out

**Comment by tmarkley** [comment]
Hi @phi06, this error occurs when you don't have OpenSearch running or when your ports aren't configure properly. Please follow our [developer guide](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md#getting-started) and/or the [installation docs](https://opensearch.org/docs/latest/dashboards/install/index/) for more information about how to properly configure your environment.
