### ISSUE TITLE
Incorrect License Header

### ISSUE THREAD

**Issue by anders-swanson** [opensearch-project/OpenSearch-Dashboards#1129]
The license header for https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/opensearch_dashboards_react/public/code_editor/.storybook/main.js looks outdated. 

It looks like this file was missed by the license header sweep in #259. The license header should be updated to reflect the correct licensing.

**Comment by anders-swanson** [comment]
Another instance: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/embeddable/.storybook/main.js

**Comment by tmarkley** [comment]
Thanks for creating this issue @anders-swanson, I've added these details to #1130 and will track progress there.
