### ISSUE TITLE
Fold in EUI and Charts

### ISSUE THREAD

**Issue by AMoo-Miki** [opensearch-project/OpenSearch-Dashboards#1136]
Following the discussion on #695, a decision was made to pull in the code for Charts and EUI, and merge them into the packages folder of OpenSearch Dashboards where they will be consumed by the built-in package manager. The upgrade to Node v14 [being on track](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/787#issuecomment-1005017569) for Dashboards v2.0, the last Apache-2.0 releases of EUI and Charts should be used:
* Charts: [87629e23e7](https://github.com/elastic/elastic-charts/tree/87629e23e7cc8aef125a8b6d2b87092085abe2bd), after v31.1.0
* EUI: [cb8deda11d](https://github.com/elastic/eui/tree/cb8deda11d5526775a47e0b99bb475ef5d3fcfb3), after v34.6.0

**Comment by kavilla** [comment]
@atifsyedali left a comment that is worth checking out https://github.com/opensearch-project/OpenSearch-Dashboards/issues/695#issuecomment-1015896757

**Comment by kavilla** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/787#issuecomment-1039495531
