### ISSUE TITLE
[BUG]disableWelcomeScreen settings ignored

### ISSUE THREAD

**Issue by rkbennett** [opensearch-project/OpenSearch-Dashboards#1138]
When setting any of the possible iterations of the disableWelcomeScreen setting, if logging in for the first time, you are still redirected to the welcome screen.

1. Add any of kibana.disableWelcomeScreen, home.disableWelcomeScreen, or opensearchDashboards.disableWelcomeScreen in the opensearch_dashboards.yml config file
2. Deploy opensearch and opensearch-dashboards docker containers
3. Log into opensearch-dashboards via port 5601
4. Select tenant (if necessary)
5. End up on the welcome screen

**Expected behavior**
Welcome screen not loaded

**OpenSearch Version**
1.2.3

**Dashboards Version**
1.2.0

**Plugins**
alertingDashboards,usageCollection,opensearchDashboardsUsageCollection,opensearchDashboardsLegacy,mapsLegacy,share,opensearchUiShared,legacyExport,embeddable,expressions,data,home,console,apmOss,management,indexPatternManagement,advancedSettings,savedObjects,securityDashboards,reportsDashboards,indexManagementDashboards,anomalyDetectionDashboards,dashboard,visualizations,visTypeVega,visTypeTimeline,timeline,visTypeTable,visTypeMarkdown,tileMap,regionMap,inputControlVis,ganttChartDashboards,visualize,queryWorkbenchDashboards,charts,visTypeVislib,visTypeTimeseries,visTypeTagcloud,visTypeMetric,observabilityDashboards,discover,savedObjectsManagement,bfetch

**Host/Environment (please complete the following information):**
 - OS: Talos 1.14
 - Chrome  96.0.4664.110

**Comment by kavilla** [comment]
Hello @rkbennett,

Thanks for opening this issue! Just to reiterate you have tried all of the following:
```
kibana.disableWelcomeScreen: false
home.disableWelcomeScreen: false
opensearchDashboards.disableWelcomeScreen : false
```
And still see the welcome message overlaying the home screen?

Could you provide how you are deploying to Docker containers as well, like are you just pulling the latest Docker images? It will help with seeing how are setting that configuration. Finally, would you be able to provide a screenshot of the welcome screen showing (just to see so I make sure I am looking at the right page while debugging).

Thank you so much!
