### ISSUE TITLE
Make bucket aggregation types configurable

### ISSUE THREAD

**Issue by RoyiSitbon** [opensearch-project/OpenSearch-Dashboards#1195]
**Is your feature request related to a problem? Please describe.**
We don't have an option to remove bucket aggregation types by demand. e.g. we want to disable the option of choosing ‘significant_terms’ bucket aggregation because it can be very heavy when run on large indices.

**Describe the solution you'd like**
We wish to add a configuration in order to disable nonrelevant bucket aggregation types. i.e by setting configuration as so, we will disable the option of choosing significant_terms aggregation:
<img width="1043" alt="significantTerm1" src="https://user-images.githubusercontent.com/12782945/151986919-912d0e98-fb32-4ab8-bee3-789a2127faee.png">

<img width="517" alt="significantTerm2" src="https://user-images.githubusercontent.com/12782945/151987083-d1205e11-babe-4e63-828c-4be972e31bc6.png">

Conversely, if the value will be an empty array, we could choose all options from the list:
<img width="510" alt="significantTerm3" src="https://user-images.githubusercontent.com/12782945/151987163-12f1778e-effa-4d18-8114-3dda75cd71f0.png">

**Comment by kgcreative** [comment]
Hey @RoyiSitbon - Would i be accurate in saying there's a desire to add some configurability and granularity to some of these features? I'm a little hesitant to suggest continuing to add .yaml settings to additional features in perpetuity, and have started thinking about how we might give some more granular controls to admins or even cluster admins in the future. Can you think of some additional use cases for these type of configuration changes?

**Comment by RoyiSitbon** [comment]
> 
Hey @kgcreative, thanks for replying.
We have several ideas for configuration changes. Some of them already opened as other issues/PRs.
e.g. https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1178 was implemented for our needs of limiting bucket split rows. I guess it can be enriched with other agg types etc.
