### ISSUE TITLE
[BUG] Incorrect documentation about connect / createStateContainerReactHelpers

### ISSUE THREAD

**Issue by ginkel** [opensearch-project/OpenSearch-Dashboards#1197]
**Describe the bug**

The developer documentation at https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/opensearch_dashboards_utils/docs/state_containers/react/connect.md provides an example how to invoke `connect` as returned by `createStateContainerReactHelpers`, which takes the state store as an argument, according to the docs. The real `createStateContainerReactHelpers` takes zero arguments, though, c.f.: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/opensearch_dashboards_utils/common/state_containers/create_state_container_react_helpers.ts#L95

**To Reproduce**
n/a

**Expected behavior**
n/a

**OpenSearch Version**
n/a

**Dashboards Version**
1.2.0

**Plugins**

n/a

**Screenshots**
n/a

**Host/Environment (please complete the following information):**
n/a

**Comment by ginkel** [comment]
If that's ok for you, I can submit a PR that changes the docs to include the correct usage.

**Comment by kavilla** [comment]
@ginkel nice catch!

Yeah if you would like to update that, that would be great!
