### ISSUE TITLE
[Git] Do not run full build-test workflow on markdown only changes

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#1214]
**Is your feature request related to a problem? Please describe.**

When creating a PR with only markdown file changes for example `README.md`, it shouldn't be blocked by build and testing.

**Describe the solution you'd like**

Have the linter only run if the PR only contains markdown changes. It looks like `paths-ignore` can be used to wildcard catch `**.md` [[DOCS](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore)]

**Describe alternatives you've considered**

N/A

**Additional context**

I believe it is safe to wildcard `**.md` to only run the lint but we should verify if we need to be more specific.

**Comment by kavilla** [comment]
Example PR that did not need to run the full test suite: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1213

**Comment by abbyhu2000** [comment]
I think it is okay to skip linter test for markdown only changes as well? Since i verified that linter test does not look at markdown files. @kavilla

**Comment by joshuarrrr** [comment]
Yeah, eventually I'd love to actually have markdown linting, but that's a low-priority item for the moment.
