### ISSUE TITLE
Updated at column in saved objects' tables

### ISSUE THREAD

**Issue by RoyiSitbon** [opensearch-project/OpenSearch-Dashboards#1217]
**Is your feature request related to a problem? Please describe.**

Is your feature request related to a problem? Please describe.
We want to see more informative data inside the saved objects' tables,
one important column that answers our needs will be the “updated at” option.
After adding this option we will gain an additional advantage, i.e sort our objects by date.

**Describe the solution you'd like to**
We wish to add an additional “updated at” column to our management, visualizations, and dashboards tables. e.g. for the management table, we will define:
<img width="1230" alt="Screen Shot 2022-02-06 at 20 04 38" src="https://user-images.githubusercontent.com/12782945/152752453-5da0c16f-54a0-4e08-a539-162b454bb67b.png">

and then we will be able to see an additional column, like so:
![Untitled](https://user-images.githubusercontent.com/12782945/152752529-fc954c39-c5f5-4b57-a91d-269fcc548a89.png)

The same solution will be implemented under the visualizations and dashboards tables, besides the fact that we will need to set our updated_at property inside the attributes prop since it uses us as the rendered object info for these tables.

**Comment by ahopp** [comment]
Hey team! Are we thinking 1.3.0 for this? @tmarkley should we associate a version with this?
