### ISSUE TITLE
[CI] Unit tests are failing in GitHub Action for all PRs and Pushes

### ISSUE THREAD

**Issue by tmarkley** [opensearch-project/OpenSearch-Dashboards#1231]
I just noticed that unit tests are not passing in the `Build and Verify` GitHub Action for any current PRs.

Example run for [PR 1229](https://github.com/opensearch-project/OpenSearch-Dashboards/runs/5132841918?check_suite_focus=true) - see `Run echo Unit tests completed unsuccessfully.`

I went back through the [commit history](https://github.com/opensearch-project/OpenSearch-Dashboards/commits/main) and it looks like unit tests have been failing for all commits since https://github.com/opensearch-project/OpenSearch-Dashboards/commit/fc96cc3e685f94285073c919e7fa309fa2e6abb2: [Build and Verify unit tests failing](https://github.com/opensearch-project/OpenSearch-Dashboards/runs/5058947670?check_suite_focus=true)

This might not be the cause, but the unit tests in each of the commits before this passed. The commit before that was https://github.com/opensearch-project/OpenSearch-Dashboards/commit/8777eb3c7068af74de7001d1842138c157a134b5: [Build and Verify unit tests passing](https://github.com/opensearch-project/OpenSearch-Dashboards/runs/4886751966?check_suite_focus=true)

**Comment by kavilla** [comment]
Just re-ran the PR for 1229, seems to be just the inconsistency issue since a new set of tests failed with the echo message being `However, unit tests are inconsistent on the CI so please verify locally with `yarn test:jest``. 

From my understanding, the issue being github being limiting on the resources and then the tests run into the error 
`Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:`.  So not to starve out the resources we limit the runners but it still it's flaky so we allowed it to pass without failing but for PRs I've been checking this step and just validating that any error generally tends to be just the jest timeout.

The snapshot error being an existing inconsistency. For Jenkins we end up updating snapshots every time we is probably not safe.

If the message needs to added to PR then will need give permissions in the org to an action that can add messages if the echo isn't helping.

To solve the flakiness, might just require not using github for PR validation or refactor the unit tests.

**Comment by tmarkley** [comment]
I think we need to re-consider how unit tests are run in GitHub Actions overall since it's taking them more than an hour to run (when successful) which is ridiculous considering they take less than a minute to run locally.

**Comment by tmarkley** [comment]
@kavilla also I don't think this is just flakiness since unit tests were consistently passing before that commit, based on going through commits before that.

All 5 of the commits were passing before that commit was pushed:

https://github.com/opensearch-project/OpenSearch-Dashboards/runs/4809365830?check_suite_focus=true
https://github.com/opensearch-project/OpenSearch-Dashboards/runs/4821234831?check_suite_focus=true
https://github.com/opensearch-project/OpenSearch-Dashboards/runs/4821425328?check_suite_focus=true
https://github.com/opensearch-project/OpenSearch-Dashboards/runs/4856193594?check_suite_focus=true
https://github.com/opensearch-project/OpenSearch-Dashboards/runs/4886751966?check_suite_focus=true

**Comment by tmarkley** [comment]
> 

Ah, nice catch. I must've missed that commit.

**Comment by tmarkley** [comment]
I reduced `maxWorkers` to 2 and unit tests passed in 11 minutes in my forked repo: https://github.com/tmarkley/OpenSearch-Dashboards/runs/5146756602?check_suite_focus=true

Going to try setting it to 1 to see if that improves it further. I've seen a few anecdotes like https://github.com/kulshekhar/ts-jest/issues/1044 that suggest reducing `maxWorkers` to 1 or 2 to improve performance in GitHub actions.

**Comment by tmarkley** [comment]
I keep seeing this error:

```
PASS  src/plugins/data/server/search/routes/msearch.test.ts
(node:3072) UnhandledPromiseRejectionWarning: AbortError: Aborted
(Use `node --trace-warnings ...` to show where the warning was created)
Node.js process-warning detected:
UnhandledPromiseRejectionWarning: AbortError: Aborted
    at emitUnhandledRejectionWarning (internal/process/promises.js:170:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
Terminating process...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

Example: https://github.com/tmarkley/OpenSearch-Dashboards/runs/5160718614?check_suite_focus=true

**Comment by tmarkley** [comment]
Also trying to use `--runInBand`. Reference: https://dev.to/vantanev/make-your-jest-tests-up-to-20-faster-by-changing-a-single-setting-i36

**Comment by kavilla** [comment]
> Also trying to use --runInBand. Reference: https://dev.to/vantanev/make-your-jest-tests-up-to-20-faster-by-changing-a-single-setting-i36

As far as am I aware runInBand would look similar to what maxWorkers=1 would be.

**Comment by kavilla** [comment]
> I reduced maxWorkers to 2 and unit tests passed in 11 minutes in my forked repo: https://github.com/tmarkley/OpenSearch-Dashboards/runs/5146756602?check_suite_focus=true

This is interesting. So reducing the amount of workers that can spawn makes it goes faster? Seems kind of anti-intuitive. I believe I remember trying this before and it took nearly 4 hours. Perhaps there part of the node upgrade relieved some of the issues?

**Comment by kavilla** [comment]
Remove checksum flag check

**Comment by tmarkley** [comment]
> 

@kavilla I tried removing the flag check and it still failed 😞
