### ISSUE TITLE
[BUG] Branding with Opensearch Dashboard on Kubernetes Cluster

### ISSUE THREAD

**Issue by kunal-parsewar** [opensearch-project/OpenSearch-Dashboards#1243]
I am trying to implement the branding for opensearch dashboard and trying to change the logo. But I am unable to do so. I am following the steps from below link .

I am running opensearch dashboard on the AKS Kubernetes Cluster.

Dashboard Version : 1.2.1

Link : https://opensearch.org/docs/latest/dashboards/branding/#sample-configuration

Error I am facing 

/osdash_branding/opensearch-dashboards# k logs -f osbranding-opensearch-dashboards-7f57cdf89c-5jhgt
{“type”:“log”,"@timestamp":“2022-02-08T06:59:34Z”,“tags”:[“info”,“plugins-service”],“pid”:1,“message”:“Plugin “visTypeXy” is disabled.”}
{“type”:“log”,"@timestamp":“2022-02-08T06:59:35Z”,“tags”:[“fatal”,“root”],“pid”:1,“message”:"{ ValidationError: child “opensearchDashboards” fails because [“branding” is not allowed]\n at Object.exports.process (/usr/share/opensearch-dashboards/node_modules/joi/lib/errors.js:196:19)\n at internals.Object._validateWithOptions (/usr/share/opensearch-dashboards/node_modules/joi/lib/types/any/index.js:675:31)\n at module.exports.internals.Any.root.validate (/usr/share/opensearch-dashboards/node_modules/joi/lib/index.js:146:23)\n at Config._commit (/usr/share/opensearch-dashboards/src/legacy/server/config/config.js:146:34)\n at Config.set (/usr/share/opensearch-dashboards/src/legacy/server/config/config.js:117:10)\n at Config.extendSchema (/usr/share/opensearch-dashboards/src/legacy/server/config/config.js:89:10)\n at _lodash.default.each.child (/usr/share/opensearch-dashboards/src/legacy/server/config/config.js:79:14)\n at arrayEach (/usr/share/opensearch-dashboards/node_modules/lodash/lodash.js:530:11)\n at Function.forEach (/usr/share/opensearch-dashboards/node_modules/lodash/lodash.js:9410:14)\n at Config.extendSchema (/usr/share/opensearch-dashboards/src/legacy/server/config/config.js:78:30)\n at new Config (/usr/share/opensearch-dashboards/src/legacy/server/config/config.js:69:10)\n at Function.withDefaultSchema (/usr/share/opensearch-dashboards/src/legacy/server/config/config.js:63:12)\n at LegacyService.setupLegacyConfig (/usr/share/opensearch-dashboards/src/core/server/legacy/legacy_service.js:84:43) name: ‘ValidationError’ }"}

Any one faced this issue earlier?

**Comment by kavilla** [comment]
Hello @kunal-parsewar, thanks for opening this. 

Could you provide details with how you are configuring these values?

There is a current issue https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1164, that will need to be addressed as well that has issues with SSL enabled.

**Comment by kunal-parsewar** [comment]
> Hello @kunal-parsewar, thanks for opening this.
> 
> Could you provide details with how you are configuring these values?
> 
> There is a current issue #1164, that will need to be addressed as well that has issues with SSL enabled. There might be an issue there

Hi,
I have mounted an image inside a container via configmap. Then in the os dashboard configuration i am mentioning the mount path where i have mounted the image.

After doing the changes , I am accessing the dashboard but i dont see the updated image.

Note 2 :

Even I tried placing the branding image in the github and then given the github url in the dashboard configuration.

But both times no luck.

Regards,
Kunal

**Comment by kunal-parsewar** [comment]
Also i cannot disable SSL / remove the SSL plugins because of the compliance issues.

**Comment by kavilla** [comment]
> Also i cannot disable SSL / remove the SSL plugins because of the compliance issues.

Unfortunately, it would seem you are still blocked by https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1164, which we are targeting to have a fix by for `1.3.0`.

I'm going to link this issue in #1164 and close this issue as duplicate.

Apologies for any inconvenience this may have caused you.
