### ISSUE TITLE
[BUG]Loading a saved query with double quotes in Discover removes the quotes (Kibana issue #81575)

### ISSUE THREAD

**Issue by ngamber** [opensearch-project/OpenSearch-Dashboards#1254]
Copying the bug from the upstream kibana issue, which persists in Opensearch 1.1

> **Kibana version:** Opensearch 1.1 (AWS)
> 
> **Describe the bug:** If you save a query in Discover containing double quotes, those quotes will be trimmed upon reloading the saved query, making the response not the expected one. If the saved query contains 2 different strings in quotes (for example when using OR), the trimming won't happen.
> 
> **Steps to reproduce:**
> 
> 1. Load the sample ecommerce data.
> 2. Save the query: `"Men's Clothes"` and then reload it.
> 
> Looking at the saved objects for each respective query it doesn't seem to be a problem with saving the query, but with the loading of it, since the quotes are saved escaped in the query.
> 
> Here's a sample saved query:
> 
> ```
> {"attributes":{"description":"","filters":[],"query":{"language":"kuery","query":"\"Men's Shoes\""},"title":"test"},"id":"test","references":[],"type":"query","updated_at":"2020-10-24T22:36:48.064Z","version":"WzI4ODEwLDFd"}
> {"exportedCount":1,"missingRefCount":0,"missingReferences":[]}
> ```
> 
> And this is one with an OR clause:
> 
> ```
> {"attributes":{"description":"","filters":[],"query":{"language":"kuery","query":"\"Men's Shoes\" OR \"Men's Clothing\""},"title":"tewfascew"},"id":"tewfascew","references":[],"type":"query","updated_at":"2020-10-24T22:40:37.436Z","version":"WzI4ODQwLDFd"}
> {"exportedCount":1,"missingRefCount":0,"missingReferences":[]}
> ```
> 
> Seems like functionality related to the search bar, so I'm tagging the app arch team.

**Comment by kavilla** [comment]
@ngamber,

Thanks for opening! Yes I can see the bug.

**Comment by ananzh** [comment]
This is an issue with JSON.parse

example 1: `"\"Men's Shoes\"" `
```
parsed result:
"\"Men's Shoes\"" 

parsed type: string
```

example 2: `"\"Men's Clothing\" or \"Men's Shoes\""`
```
parsed result:
error: Uncaught SyntaxError: Unexpected token o in JSON at position 17
```

example 3: `'{"x": "y"}'`
```
parsed result:
{
x:"y"
}

parsed type: object
```

For example 1, `"\"Men's Shoes\"" ` is parsed so double quotes are gone. Then osd treat `Men's Shoes` as separate words due to default standard analyzer. While for example, an error is triggered, query is then reset to `"\"Men's Clothing\" or \"Men's Shoes\""`. This time osd treat it as a whole term.
