### ISSUE TITLE
[BUG] --rpm does not actually build RPM artifact

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/OpenSearch-Dashboards#1259]
Using this on branch 1.x does not build .rpm package.
```
yarn build-platform --rpm --release
```
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1.x/src/dev/build/cli.ts

It will build tarball and put it to target folder:

`....../OpenSearch-Dashboards/target/opensearch-dashboards-1.3.0-linux-x64.tar.gz`

Also, there is no option to build arm64 rpm as well.

Thanks.

**Comment by peterzhuamazon** [comment]
cc: @bbarani

**Comment by peterzhuamazon** [comment]
The same applies to `deb`, tho rpm takes higher priority now.
Thanks.

**Comment by ananzh** [comment]
@peterzhuamazon 

Could run `yarn build-platform --all-platforms` to get rpm/deb package. Result is below (using osd 1.2.0):

```
~/work/OpenSearch-Dashboards/target$ ls
opensearch-dashboards-1.2.0-SNAPSHOT-amd64.deb          opensearch-dashboards-1.2.0-SNAPSHOT-linux-arm64.tar.gz  opensearch-dashboards-1.2.0-SNAPSHOT-windows-x64.zip
opensearch-dashboards-1.2.0-SNAPSHOT-darwin-x64.tar.gz  opensearch-dashboards-1.2.0-SNAPSHOT-linux-x64.tar.gz    opensearch-dashboards-1.2.0-SNAPSHOT-x64.rpm
```

Currently, we don't have arm64 rpm. We only have x64 rpm. We don't have a separate cmd for building only deb/rpm package. Need to get them with argument `--all-platforms` .  If want to limit building only rpm package, would do `yarn build-platform --all-platforms --rpm` but `--all-platforms` is required.

**Comment by kavilla** [comment]
@peterzhuamazon, to expand on @ananzh said. 

You can also run the following:
```
yarn build --rpm --skip-archives --release
```

I think this is the command you are looking for, it will build specifically the RPM build. `build-platform` would be supports Linux x64, Linux ARM, and Darwin.

**Comment by peterzhuamazon** [comment]
Thanks @ananzh @kavilla I will try the rpm commands for x64.
How long would it take to add arm64 rpm builds for dashboards?
As that is also crucial for the rpm releases.

Thanks.

**Comment by peterzhuamazon** [comment]
Just talked to the dashboards team member and have these outcomes:
1. @kavilla PR can build both x64 and arm64 #1272 but cannot build only one of them, requires changes in our build.sh to grep the specific ones. Also, need to backport it to 1.x branch if merged.
2. The arm64 package currently still have `aarch64` in the naming:
```
-rw-r--r-- 1  96967083 Feb 22 23:00 opensearch-dashboards-2.0.0-SNAPSHOT-aarch64.rpm
-rw-r--r-- 1        40 Feb 22 23:00 opensearch-dashboards-2.0.0-SNAPSHOT-aarch64.rpm.sha1.txt
-rw-r--r-- 1  97227223 Feb 22 23:00 opensearch-dashboards-2.0.0-SNAPSHOT-x64.rpm
-rw-r--r-- 1        40 Feb 22 23:00 opensearch-dashboards-2.0.0-SNAPSHOT-x64.rpm.sha1.txt
```
3. Like OpenSearch, the Dashboards is bundling nodejs tarball within the rpm, need to make them as dependencies during installation time: 
https://www.softwarecollections.org/en/scls/?search=NodeJS
4. Need someone from @seanneumann / @seraphjiang team to verify that the core dashboards rpm package is able to run on arm64 before Infra Team use it for bundled rpm creation.


Thanks,
Peter
