### ISSUE TITLE
[BUG] Document table expand icon is invisible on Discover Context page

### ISSUE THREAD

**Issue by tmarkley** [opensearch-project/OpenSearch-Dashboards#1281]
**Describe the bug**

The icon for expanding/collapsing the document in the Discover Context page is not visible. You can click it and it works, but you can't see it.

**To Reproduce**
1. Go to Discover
2. Expand a document with the arrow on the left side (this is what should show up on the context page)
3. Click on `View surrounding documents`
4. See that the arrow icons for every document is not visible on the left side of the table. This is the case in the dark and light themes.

**Expected behavior**
The icons should be visible.

**OpenSearch Version**
2.0 snapshot

**Dashboards Version**
2.0 from `main`

**Plugins**

N/A

**Screenshots**

Invisible icon:
<img width="747" alt="Screen Shot 2022-02-24 at 6 25 41 PM" src="https://user-images.githubusercontent.com/5437176/155631428-ddde64ee-2aa5-46b9-9706-f94bf6012d5c.png">

What the icon should look like, from the Discover page:
<img width="1507" alt="Screen Shot 2022-02-24 at 6 32 04 PM" src="https://user-images.githubusercontent.com/5437176/155631489-4ffb1d59-3a46-4430-9253-2a2f63c95b2d.png">

**Host/Environment (please complete the following information):**
 - OS: OpenSearch and OpenSearch Dashboards running on Ubuntu ARM, testing browsers on MacOS 12.2.1
 - Browser and version: Confirmed on Safari 15.3, Firefox 97.0.1, and Chrome 98.0

**Additional context**

N/A

**Comment by tmarkley** [comment]
Didn't get a chance to dive into this quite yet.

**Comment by joshuarrrr** [comment]
This is reproducible in `1.0.0`. It appears that the context page was never de-angularized as far as the discover page was, although they share the same table component. My initial plan is to apply the same de-angularization process as https://github.com/elastic/kibana/pull/75784/ or https://github.com/opensearch-project/OpenSearch-Dashboards/commit/aaccd705034752f1f461b3cc9ec069eddab25f48
