### ISSUE TITLE
Release version 1.3

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/OpenSearch-Dashboards#1282]
This is a component issue for release 1.3.0.<br/>
Coming from [opensearch-build#889](https://github.com/opensearch-project/opensearch-build/issues/889), release version 1.3. Please follow the following checklist.

### Preparation

- [x] Assign this issue to a release owner
- [x] Finalize scope and feature set and update [the Public Roadmap](https://github.com/orgs/opensearch-project/projects/1).
- [x] Create, update, triage and label all features and issues targeted for this release with `v1.3.0`.

### CI/CD

- [x] Increment version on main to `1.3.0`. https://github.com/opensearch-project/OpenSearch-Dashboards/pull/977
- [x] Ensure working and passing CI.
- [x] Re(add) this repo to the (if not exist) [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.0/).

### Pre-Release

- [x] Branch and build from a `1.3` branch. https://github.com/opensearch-project/OpenSearch-Dashboards/tree/1.3
- [x] Update your branch in the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.0).
- [x] Feature complete, pencils down.
- [x] Fix bugs that target this release.

### Release

- [x] Complete [documentation](https://github.com/opensearch-project/documentation-website).
- [x] Gather, review and publish release notes. https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1348
- [x] Verify all [issues labeled for this release](https://github.com/opensearch-project/OpenSearch-Dashboards/issues?q=is%3Aissue+label%3Av1.3.0+) are closed or labelled for the next release.

### Post Release

- [x] Create [a release tag](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#tagging).
- [x] Suggest improvements to [this template](https://github.com/opensearch-project/opensearch-build/blob/main/.github/ISSUE_TEMPLATE/release_template.md).
- [ ] Conduct a postmortem, and publish its results.

**Comment by kavilla** [comment]
Retro
---

* Release notes generation is becoming actual work so I've created an issue here for automation: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1357
* This CVE fix was missed: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1160
* Test wise, it still required a little bit of manual effort but better than before hopefully next release it will completely hands off.
