### ISSUE TITLE
[BWC] Verify impact for `type` and `include_type_name` no longer being supported

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#1290]
We will need to verify if the removal of the `type` here: https://github.com/opensearch-project/OpenSearch/pull/2239 has impact to backwards compatibility for OpenSearch Dashboards.

If it doesn't then we can close this issue. If it does, does it require a migration script on startup?

If we it does require a migration script then we will take note of a migration path and any documents to ensure that OpenSearch Dashboards and the compatible OpenSearch. If it's somewhat compatible then we will have to make sure if a legacy version goes from 6.8 to OpenSearch Dashboards does not fail to start. Or we will need to update documents.

If we discover no BWC issues than the commented out code added here: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1289 can be removed.

**Comment by dreamer-89** [comment]
Here is the meta issue regarding type removal from OpenSearch engine.
https://github.com/opensearch-project/opensearch/issues/1940

A high level changes done as part of type removal
https://gist.github.com/dreamer-89/d76eaf639171e8ab32fa7f8b9d6c93d3

**Comment by kavilla** [comment]
Will also now need verify impact of this as well:

https://github.com/opensearch-project/OpenSearch/pull/2397

Removal of `include_type_name`

**Comment by dblock** [comment]
Assigning to @kavilla since it's labeled 2.0, just so we don't lose it.

**Comment by dreamer-89** [comment]
@kavilla : Is there anything pending here ?
