### ISSUE TITLE
[BUG] Median metric does not work for scripted fields

### ISSUE THREAD

**Issue by evamillan** [opensearch-project/OpenSearch-Dashboards#1296]
**Describe the bug**

The median metric does not return any value for scripted fields.

**To Reproduce**
1. Create a numeric scripted field.
2. Create a visualization, for example a data table.
3. Add a metric with a median agg and the scripted field.
4. No data is displayed on the visualization.

**Expected behavior**
The median data should be shown on the visualization.

**OpenSearch Version**
1.2.0

**Dashboards Version**
1.2.0

**Plugins**

None

**Host/Environment:**
 - OS: Ubuntu
 - Browser and version: Firefox 97.0

**Additional context**
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/8ba11e3382169a8c03de047241163c64e0f3081d/src/plugins/data/common/search/aggs/metrics/median.ts#L64
The `field` param does not work for scripted fields.

**Comment by ananzh** [comment]
Reproduce the issue with a script using sample eCommerce data
```
if (doc.containsKey('base_price') && !doc['base_price'].empty) {
    if (doc['base_price'].value <30) {
    return -10;
}
}
return 10;

```

Median metrics does not work for the above script

<img width="1688" alt="Screen Shot 2022-03-01 at 11 48 44 AM" src="https://user-images.githubusercontent.com/79961084/156238614-10056d43-f7f7-4d69-95fa-138cab036caa.png">
