### ISSUE TITLE
[savedobjects-service] This version of OpenSearch Dashboards (v2.0.0) is incompatible with the following OpenSearch nodes in your cluster[BUG]

### ISSUE THREAD

**Issue by DaCastle** [opensearch-project/OpenSearch-Dashboards#1297]
**Describe the bug**

When trying to launch openSearch Dashboards locally by following the [developer guide](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md#getting-started), ending with running `yarn start` in the dashboards directory, I see the following error displayed:

[info][savedobjects-service] Waiting until all OpenSearch nodes are compatible with OpenSearch Dashboards before starting saved objects migrations...

[error][savedobjects-service] This version of OpenSearch Dashboards (v2.0.0) is incompatible with the following OpenSearch nodes in your cluster: v1.2.4 @ 172.18.0.3:9200 (172.18.0.3), v1.2.4 @ 172.18.0.2:9200 (172.18.0.2)

**To Reproduce**
Follow the developer guide mentioned above from the 'Getting Started' section, ending with running `yarn start` from the 'Run OpenSearch Dashboards' section.

**Expected behavior**
For the openSearch Dashboard instance to be compatible with the openSearch instance that was referenced by the documentation, and in the meantime reference useable compatible versions. 

**OpenSearch Version**
1.2.4

**Dashboards Version**
release 1.2.0,  with 'version' 2.0.0 referenced in package.json

**Plugins**

Only those installed from the developer guide referenced above.

**Screenshots**

**Host/Environment (please complete the following information):**
OS Name	Microsoft Windows 10 Pro, 
Version	10.0.19041 Build 19041

**Additional context**

Running openSearch via Docker (docker-compose)

Extremely likely to be user error.

**Comment by tmarkley** [comment]
Hi @DaCastle, welcome and thanks for submitting this issue! We are aware of this discrepancy in the documentation and are addressing it in #1265. You should be able to run `yarn opensearch snapshot` to run the latest `v2.0.0` snapshot of OpenSearch.
