### ISSUE TITLE
[BUG] Jest test cannot find matches on Windows

### ISSUE THREAD

**Issue by Ironem** [opensearch-project/OpenSearch-Dashboards#1310]
**Describe the bug**

Fail when I tried to run yarn test:jest on a new project without any changes. I was on branch 1.x on the commit of Wed Feb 9 2022. Even on other branch I have the same error. 

**To Reproduce**
1. Check out to 1.x : git checkout origin/1.x
2. Install all dependencies with the right version of node : yarn osd bootstrap
3. Run the test with : yarn test:jest
4. See error on console output

![image](https://user-images.githubusercontent.com/57012015/156540855-db7dd425-e281-431c-8da8-2c513a0aa725.png)

**Expected behavior**
Should run all tests and give the results of tests.

**OpenSearch Version**
n/a

**Dashboards Version**
1.x

**Plugins**

n/a

**Host/Environment (please complete the following information):**
 - node : v10.24.1
 - yarn : 1.22.17

**Comment by kavilla** [comment]
Hello @Ironem,

Potentially related to your OS. Are you running on windows? There is an existing issue there: https://github.com/facebook/jest/issues/7914.

**Comment by kavilla** [comment]
@Ironem, is that your OS? If so, we can rename this issue to `yarn test:jest` for windows. You will also see some issues with integration tests and functional tests since we currently don't have snapshots for Windows (yet).

**Comment by Ironem** [comment]
> @Ironem, is that your OS? If so, we can rename this issue to `yarn test:jest` for windows. You will also see some issues with integration tests and functional tests since we currently don't have snapshots for Windows (yet).

Yeah, sorry for the late response, I am on Windows 10 and all tests doest not work, and I am trying to install node in wsl in order to get it work.

**Comment by kavilla** [comment]
Sounds good, I will update the title of this issue to reflect as such. Thanks!

**Comment by Ironem** [comment]
So with WSL it works fine. You need to install make, python3, gcc and g++ in your WSL and then reinstall the project with `yarn osd bootstrap` and then tests run fine.

**Comment by AMoo-Miki** [comment]
This is fixed with #2601.
