### ISSUE TITLE
onboard to Codecov for code coverage

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/OpenSearch-Dashboards#1339]
**Is your feature request related to a problem? Please describe.**

There is an project initiative for code coverage. See examples
https://github.com/opensearch-project/opensearch-build/blob/main/.codecov.yml
https://github.com/opensearch-project/security-dashboards-plugin/blob/main/codecov.yml

**Describe the solution you'd like**

onboard to Codecov

**Describe alternatives you've considered**

**Additional context**

**Comment by kavilla** [comment]
Linking similar issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1035

**Comment by kavilla** [comment]
I believe @ananzh was looking into this?
