### ISSUE TITLE
Add support for build version qualifiers.

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch-Dashboards#1340]
Coming from https://github.com/opensearch-project/opensearch-build/issues/1632, add support for `-Dbuild.version_qualifier=`. 

The distribution build process now supports passing additional optional qualifiers other than the 3 digit versions, e.g. `2.0.0-alpha1`. Add the ability to pass additional qualifier to build scripts, and generate artifacts with a version that includes the qualifier.

**Comment by kavilla** [comment]
Resolved with: https://github.com/opensearch-project/opensearch-build/pull/1836
