### ISSUE TITLE
[BUG] Inconsistent license headers

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#1382]
The license headers are not consistent for files from OpenSearch contributors is not consistent.

**Comment by AMoo-Miki** [comment]
The headers should follow these rules:

* Newly created files:
  * With copied code: Long with extra modifications text
  * Entirely new: Short 2-liner
* Modified files: Long with extra modifications text
* Unmodified: Long without the modifications text
