### ISSUE TITLE
Distribution neutral packaging of OpenSearch core

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch-Dashboards#1404]
I'm raising this issue to track a longer term refactoring/improvement of the build process for OpenSearch. The immediately impact that motivated #2571 has been mitigated. However, the existing build process involves building distribution-specific opensearch-min artifacts (such as an RPM), which are subsequently extracted, modified, then repackaged for the full distribution. This seems to be a bit of a roundabout mechanism and has led to problems in the past. A better solution might be to have the targets in OpenSearch core to build distribution neutral artifacts that can be used by the downstream steps in the build/packaging process without having to do extra work like extracting an RPM.

**Comment by andrross** [comment]
Sorry, just realized I created this in the wrong repo :( Closing

**Comment by kavilla** [comment]
@andrross no problem! I could have re-routed it to the right repo to avoid extra work for you unless you have already created it? Otherwise let me know!

**Comment by andrross** [comment]
I just closed and recreated. I suppose re-routing would have been easier :)

**Comment by kavilla** [comment]
Sounds good! Sorry about not getting to this earlier.
