### ISSUE TITLE
Option to disable Dev Tools/Console?

### ISSUE THREAD

**Issue by evandam** [opensearch-project/OpenSearch-Dashboards#1406]
**Is your feature request related to a problem? Please describe.**

I would like to run an Opensearch Dashboards instance but without the dev tools/console that allows running queries (effectively only allowing read-only access to OpenSearch through the dashboards). It looks like there's a way to do it with Kibana (https://www.elastic.co/guide/en/kibana/current/console-kibana.html#console-settings), but I can't find the OpenSearch equivalent.

**Describe the solution you'd like**

A configuration flag like `OPENSEARCH_CONSOLE_ENABLED=false` to disable the console.

**Describe alternatives you've considered**

Hoping I'm just missing the doc for this. Alternatives would be jumping through some hoops to block the console endpoint, which I would like to avoid.

**Comment by kavilla** [comment]
Hello @evandam,

Thanks for opening! You can add the following to your `opensearch_dashboards.yml`:
```
console.enabled: false
```
this will remove the console from view. If that satisfies your feature request then yeah I would agree, this an issue with documentation and I will re-route this to the documentation repo. Really sorry about this not being included in the docs site.

However, if your goal was to set an environmental variable then we can keep this as feature request but specify that you would like to set the environment variable.

Let me know! Thanks!

**Comment by ahopp** [comment]
@evandam does @kavilla callout solve your use case? If so, we can close. If not, can you help us understand the incremental gap?

**Comment by kavilla** [comment]
Just verified that the docker image has the config as well: https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint.sh#L22. So this should be supported even running from docker environment. But I do not believe there is current environment variable that allows for this.

With the security plugin installed one can give a user a role that hides a lot of plugins that filters a lot of plugins `kibana_read_only`. But I'm not positive if it supports granular filtering of plugins as indicated by this issue: https://github.com/opensearch-project/security-dashboards-plugin/issues/857.

I will close this issue as I think the best next steps with the current information is what @ahopp mentioned with the lack of docs.

If this doesn't resolve your issue @evandam please re-open and add further details.
