### ISSUE TITLE
Feedback - Controls Visualization

### ISSUE THREAD

**Issue by squiddy61** [opensearch-project/OpenSearch-Dashboards#1423]
Headline - when using the controls visualization / Options List, there's a limit of 10 entries displayed.

To re-create, create a "Controls" visualization, "Options List", "Add", then choose an index/field that has more than 10 distinct values.  Only 10 will be displayed.  

Examining the properties of the control shows a "size" of 5; but changing this value has no effect, 10 seems to be a fixed value.

(As an experimental visualization, I didn't know how to classify this one - but wanted to provide feedback)

**Comment by kavilla** [comment]
Hello @squiddy61,

Thanks for opening!

We have an [issue](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/800) to remove the tag `experimental` so any feedback will be great even if on things that say `experimental`.

Just to make sure, you have ensure you have disabled:

![Screen Shot 2022-04-03 at 1 51 15 PM](https://user-images.githubusercontent.com/12060704/161448120-08b13589-348a-4ea0-94de-1dcb93a8b0d8.png)

This will prevent dynamically determining the size of options while disabling it will give you the ability to control it to the size you would like. 5 is the default value we set in the application but it will default use that value if have disable that the dynamic option.

Let me know!

Thanks again!

**Comment by squiddy61** [comment]
That works - I didn't make the connection that the "Dynamic Options" worked - thanks!

The silent limit of 10 is a bit troubling, but will leave it to smarter people than I to figure out how best to handle :)

Thanks again!
