### ISSUE TITLE
[BUG] 403 error while building osd.

### ISSUE THREAD

**Issue by jk-node** [opensearch-project/OpenSearch-Dashboards#1446]
`403` access denied error while building OSD from source code. 
Source URL throwing error - https://d1v1sj258etie.cloudfront.net/node-re2/1.15.4/linux-arm64-64.gz 

info [ opensearch-dashboards ] Creating platform-specific archive source directories
  │ debg Generic build source copied into linux-x64 specific build directory
  │ debg Generic build source copied into linux-arm64 specific build directory
  │ debg Generic build source copied into darwin-x64 specific build directory
  │ debg Generic build source copied into win32-x64 specific build directory
  │ debg Node.js copied into win32-x64 specific build directory
  │ debg Node.js copied into linux-x64 specific build directory
  │ debg Node.js copied into darwin-x64 specific build directory
  │ debg Node.js copied into linux-arm64 specific build directory
  │ succ ✓ 51 sec
 info [ opensearch-dashboards ] Patching platform-specific native modules
  │ debg Patching re2 binaries from https://github.com/uhop/node-re2/releases/download/1.15.4/linux-x64-64.gz to /home/4px/od/OpenSearch-Dashboards/build/opensearch-dashboards-1.2.0-SNAPSHOT-linux-x64/node_modules/re2/build/Release/re2.node
  │ debg Deleting patterns: [ '/home/4px/od/OpenSearch-Dashboards/build/opensearch-dashboards-1.2.0-SNAPSHOT-linux-x64/node_modules/re2/build/Release/re2.node' ]
  │ debg Patching re2 binaries from https://d1v1sj258etie.cloudfront.net/node-re2/1.15.4/linux-arm64-64.gz to /home/4px/od/OpenSearch-Dashboards/build/opensearch-dashboards-1.2.0-SNAPSHOT-linux-arm64/node_modules/re2/build/Release/re2.node
  │ debg Deleting patterns: [ '/home/4px/od/OpenSearch-Dashboards/build/opensearch-dashboards-1.2.0-SNAPSHOT-linux-arm64/node_modules/re2/build/Release/re2.node' ]
  │ debg Patching re2 binaries from https://github.com/uhop/node-re2/releases/download/1.15.4/darwin-x64-64.gz to /home/4px/od/OpenSearch-Dashboards/build/opensearch-dashboards-1.2.0-SNAPSHOT-darwin-x64/node_modules/re2/build/Release/re2.node
  │ debg Deleting patterns: [ '/home/4px/od/OpenSearch-Dashboards/build/opensearch-dashboards-1.2.0-SNAPSHOT-darwin-x64/node_modules/re2/build/Release/re2.node' ]
  │ debg Patching re2 binaries from https://github.com/uhop/node-re2/releases/download/1.15.4/win32-x64-64.gz to /home/4px/od/OpenSearch-Dashboards/build/opensearch-dashboards-1.2.0-SNAPSHOT-windows-x64/node_modules/re2/build/Release/re2.node
  │ debg Deleting patterns: [ '/home/4px/od/OpenSearch-Dashboards/build/opensearch-dashboards-1.2.0-SNAPSHOT-windows-x64/node_modules/re2/build/Release/re2.node' ]
  │ debg Deleted 1 files/directories
  │ debg Deleted 1 files/directories
  │ debg Deleted 1 files/directories
  │ debg Deleted 1 files/directories
  │ debg Attempting download of https://github.com/uhop/node-re2/releases/download/1.15.4/linux-x64-64.gz e743587bc96314edf10c3e659c03168bc374a5cd9a6623ee99d989251e331f28
  │ debg Attempting download of https://d1v1sj258etie.cloudfront.net/node-re2/1.15.4/linux-arm64-64.gz 19fa97f39d4965276382429bcd932dd696915f711663e7cef9b0a304b3e8e6f7
  │ debg Attempting download of https://github.com/uhop/node-re2/releases/download/1.15.4/darwin-x64-64.gz 595c6653d796493ddb288fc0732a0d1df8560099796f55a1dd242357d96bb8d6
  │ debg Attempting download of https://github.com/uhop/node-re2/releases/download/1.15.4/win32-x64-64.gz b33de62cda24fb02dc80a19fb79977d686468ac746e97cd211059d2d4c75d529
  │ debg Download failed: Request failed with status code 403
  │ debg Deleting downloaded data at /home/4px/od/OpenSearch-Dashboards/.native_modules/re2/linux-arm64-64.gz
  │ debg Retrying - 3 attempt remaining
  │ debg Attempting download of https://d1v1sj258etie.cloudfront.net/node-re2/1.15.4/linux-arm64-64.gz 19fa97f39d4965276382429bcd932dd696915f711663e7cef9b0a304b3e8e6f7
  │ debg Downloaded https://github.com/uhop/node-re2/releases/download/1.15.4/win32-x64-64.gz and verified checksum
  │ debg Downloaded https://github.com/uhop/node-re2/releases/download/1.15.4/darwin-x64-64.gz and verified checksum
  │ debg Downloaded https://github.com/uhop/node-re2/releases/download/1.15.4/linux-x64-64.gz and verified checksum
  │ debg Download failed: Request failed with status code 403
  │ debg Deleting downloaded data at /home/4px/od/OpenSearch-Dashboards/.native_modules/re2/linux-arm64-64.gz
  │ debg Retrying - 2 attempt remaining
  │ debg Attempting download of https://d1v1sj258etie.cloudfront.net/node-re2/1.15.4/linux-arm64-64.gz 19fa97f39d4965276382429bcd932dd696915f711663e7cef9b0a304b3e8e6f7
  │ debg Download failed: Request failed with status code 403
  │ debg Deleting downloaded data at /home/4px/od/OpenSearch-Dashboards/.native_modules/re2/linux-arm64-64.gz
  │ debg Retrying - 1 attempt remaining
  │ debg Attempting download of https://d1v1sj258etie.cloudfront.net/node-re2/1.15.4/linux-arm64-64.gz 19fa97f39d4965276382429bcd932dd696915f711663e7cef9b0a304b3e8e6f7
  │ debg Download failed: Request failed with status code 403
  │ debg Deleting downloaded data at /home/4px/od/OpenSearch-Dashboards/.native_modules/re2/linux-arm64-64.gz
  │ERROR failure 1 sec
  │ERROR Error: Request failed with status code 403
  │     at createError (/home/4px/od/OpenSearch-Dashboards/node_modules/axios/lib/core/createError.js:16:15)
  │     at settle (/home/4px/od/OpenSearch-Dashboards/node_modules/axios/lib/core/settle.js:17:12)
  │     at RedirectableRequest.handleResponse (/home/4px/od/OpenSearch-Dashboards/node_modules/axios/lib/adapters/http.js:238:9)
  │     at RedirectableRequest.emit (events.js:198:13)
  │     at RedirectableRequest._processResponse (/home/4px/od/OpenSearch-Dashboards/node_modules/follow-redirects/index.js:399:10)
  │     at ClientRequest.RedirectableRequest._onNativeResponse (/home/4px/od/OpenSearch-Dashboards/node_modules/follow-redirects/index.js:57:10)
  │     at Object.onceWrapper (events.js:286:20)
  │     at ClientRequest.emit (events.js:198:13)
  │     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
  │     at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
  │     at TLSSocket.socketOnData (_http_client.js:451:20)
  │     at TLSSocket.emit (events.js:198:13)
  │     at addChunk (_stream_readable.js:288:12)
  │     at readableAddChunk (_stream_readable.js:269:11)
  │     at TLSSocket.Readable.push (_stream_readable.js:224:10)
  │     at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 

**OpenSearch Version**
1.2

**Dashboards Version**
1.2

**Plugins**
NA

**Host/Environment (please complete the following information):**
-centOS

**Comment by ananzh** [comment]
@jk-node, we restored re2 and currently still tested it. We will make an update.

**Comment by kavilla** [comment]
Hi @jk-node, thanks for opening this. Let's close this one and track it with this issue https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1436.
