### ISSUE TITLE
[BUG] Typo in icon file for "Replace Panel"

### ISSUE THREAD

**Issue by fioddor** [opensearch-project/OpenSearch-Dashboards#1475]
**Describe the bug**

The icon of the option _'Replace Panel'_ shows as an empty square box.
There seems to be a small typo in the name of the icon.

**To Reproduce**
1. Go to a Dashboard
2. Click on 'Edit'
3. Choose a visualization
4. Click on the gear icon at the top-right corner of the visualization.
5. Select the option '...More' in the floating menu.
6. Look at the 'Replace panel' option of the floating menu.

**Expected behavior**
The previous icon was  something like '<=>'.

**OpenSearch Version**

`GET /` reports 1.2.4. Kibana reports 1.2.0 on the top-right help icon.

**Dashboards Version**

1.3.1, we believe.

**Plugins**

**Screenshots**

![imagen](https://user-images.githubusercontent.com/36269471/163992832-8c95b8d1-5809-4f63-b148-ba036fe00c61.png)

**Host/Environment (please complete the following information):**
 - OS: Linux
 - FireFox 91.8.0esr (64 bit)

**Additional context**

**Comment by kavilla** [comment]
Thank you for opening! It was in my list of paper cuts that I needed to create an issue for but haven't gotten to it so appreciate it!

**Comment by ahopp** [comment]
@joshuarrrr want to take this one?

**Comment by joshuarrrr** [comment]
fixed by #1496
