### ISSUE TITLE
[BUG] Maps license error is misleading

### ISSUE THREAD

**Issue by tmarkley** [opensearch-project/OpenSearch-Dashboards#1479]
**Describe the bug**

Coming from https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1431

![image](https://user-images.githubusercontent.com/5437176/164091093-4279ec7b-26d3-4c1d-819b-1efb9b658299.png)

**Expected behavior**
The error shouldn't reference a license; it should say that the maps service is unavailable.

**OpenSearch Version**
1.x

**Dashboards Version**
1.x

**Plugins**

N/A

**Comment by kavilla** [comment]
Did we want to close the previous issue?

**Comment by tmarkley** [comment]
@kavilla oh I thought that the triage plan was to track the error message separately from that issue. If not then we probably don't need this.

**Comment by ashwin-pc** [comment]
@tmarkley Is this issue just a change in the copy? Or is there anything else that needs to be done?

**Comment by tmarkley** [comment]
> @tmarkley Is this issue just a change in the copy? Or is there anything else that needs to be done?

@ashwin-pc for now I think we just need to change the message.
