### ISSUE TITLE
[Enhancement] Add support for geo_shape fields

### ISSUE THREAD

**Issue by alisazosimova** [opensearch-project/OpenSearch-Dashboards#1481]
**Describe the bug**

Hi guys. I am trying to create a visualisation (coordinate map), that would aggregate geo data by a `geo_shape` field type. 

I build these objects programmatically mostly, but trying to create a map from Dashboards UI gives the same result. 

In my index, I have two fields of `geo_shape` type
<img width="575" alt="geo_shape_index" src="https://user-images.githubusercontent.com/39901047/164278099-6f3e521d-46f2-4007-a64f-e16aaf862062.png">

This field type can be aggregated as Geohash grid aggregation according to Elastic 7.9 documentation
https://www.elastic.co/guide/en/elasticsearch/reference/7.9/search-aggregations-bucket-geohashgrid-aggregation.html#_aggregating_geo_shape_fields

Is some kind of license needed for this now? Does OpenSearch has any capabilities to build maps with  `geo_shape` fields? 

Oh, and this is the error that I see when I try to build a map with that mentioned index from UI:

<img width="494" alt="Screenshot 2022-04-13 at 4 43 47 PM" src="https://user-images.githubusercontent.com/39901047/164278914-28cdcad9-52a8-4d5f-a3e9-33bbaec80fdf.png">
(as you can see, there's no mention of the `geo_shape` field type in the list of compatible field types; only `geo_point`) 

Thanks for you help.

**To Reproduce**

1. Basically, you need  index with some data marked as a `geo_shape` type. 
https://www.elastic.co/guide/en/elasticsearch/reference/7.9/geo-shape.html#geo-linestring
2. Go to create a coordinate map from that index.
3. In the Map UI, leave default agg for metric, choose `Geohash` for `Buckets` agg

**Expected behavior**
Ability to choose GeoObjectGT / GeoObjectDT fields marked as geo_shape` type. 

**OpenSearch Version**
1.1

**Dashboards Version**
1.1

**Plugins**
All available out of the box

**Host/Environment (please complete the following information):**
Local OpenSearch + OpenSearch Dashboards run on docker + the same behaviour on AWS OpenSearch Service.

**Comment by alisazosimova** [comment]
Also, this is the JSON from visState field of the map object, in case this helps.

`{
  "title": "",
  "type": "tile_map",
  "aggs": [
    {
      "id": "1",
      "enabled": true,
      "type": "count",
      "params": {},
      "schema": "metric"
    },
    {
      "id": "2",
      "enabled": true,
      "type": "geohash_grid",
      "params": {
        "field": "GeoObjectDT",
        "autoPrecision": true,
        "precision": 2,
        "useGeocentroid": true,
        "isFilteredByCollar": true
      },
      "schema": "segment"
    }
  ],
  "params": {
    "addTooltip": true,
    "colorSchema": "Yellow to Red",
    "heatClusterSize": 1.5,
    "isDesaturated": true,
    "legendPosition": "bottomright",
    "mapCenter": [
      0,
      0
    ],
    "mapType": "Scaled Circle Markers",
    "mapZoom": 2,
    "wms": {
      "enabled": false,
      "options": {
        "format": "image/png",
        "transparent": true
      },
      "selectedTmsLayer": {
        "attribution": "<a rel=\"noreferrer noopener\" href=\"https://www.openstreetmap.org/copyright\">Map data OpenStreetMap contributors</a>\"",
        "id": "road_map",
        "maxZoom": 10,
        "minZoom": 0,
        "origin": "elastic_maps_service"
      }
    }
  }
}`

**Comment by kavilla** [comment]
Thank you for diving deep on this. Yes I do believe is actually do to a license issue. That `geo_shape` was an x-pack feature and would appear the maps plugin is able to see that and render the error instead. We should still gut it.

I know we have this: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1408 but I'm not positive if it's a 1:1 replacement for your current functionality. I'm not sure if this will easily allow you to migrate from using a x-pack feature to OSS.

Could you check out the above issue and see if that's the case? If it can then we will probably need to consider what is the next steps to help people migrate if we are able to support it.

**Comment by alisazosimova** [comment]
Thanks, @ashwin-pc. Will do.
