### ISSUE TITLE
Upgrade to node@12 to support ARM Mac

### ISSUE THREAD

**Issue by TechAilurus** [opensearch-project/OpenSearch-Dashboards#1484]
**Is your feature request related to a problem? Please describe:**

I'm using `brew install opensearch-dashboards` to install on Mac with M1 chip, but there is dependency on node@10, which not support Mac ARM. I tried to build from source, but not work.

**Describe the solution you'd like:**

I checked node@12 at https://formulae.brew.sh/formula/node@12, which is the min version which support Mac ARM. I think upgrade to node@12 is acceptable since it's published a long time ago.

**Additional context**
This is screen shot of `brew info opensearch-dashboards`, which dependens on node@10:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/20474091/164468439-85e0c407-ce39-4526-89d2-42df39c72796.png">

Screen shot of  `brew install opensearch-dashboards` on Mac with M1 failure:

<img width="944" alt="image" src="https://user-images.githubusercontent.com/20474091/164472302-340850da-f4aa-447e-b872-66d311155976.png">

**Comment by tmarkley** [comment]
Hi @TechAilurus! Thanks for reaching out. We have upgraded OpenSearch Dashboards to Node.js v14 for our upcoming v2.0 release. You can check out #920 for more information about the work involved. You can pull down the code to test ahead of the release over in our 2.0 branch: https://github.com/opensearch-project/OpenSearch-Dashboards/tree/2.0
