### ISSUE TITLE
[BUG] [Help me,Thanks]  run yarn build-platform appear "EINVAL: invalid argument"  errors on windows

### ISSUE THREAD

**Issue by Top1zZ** [opensearch-project/OpenSearch-Dashboards#1492]
**Describe the bug**

in git bash run yarn build-platform appear "EINVAL: invalid argument" error

**To Reproduce**
1. yarn build-platform 
2. See error

**Expected behavior**
build successful

**OpenSearch Version**
v1.2.0

**Dashboards Version**
v1.2.0

**Plugins**
none

**Screenshots**

<img width="469" alt="Snipaste_2022-04-25_16-51-14" src="https://user-images.githubusercontent.com/86825148/165054876-5efcf46b-37d2-4a23-8bb9-f4c99680f7ec.png">

**Host/Environment (please complete the following information):**
 - OS: windows10
 - Browser and version: chrome
 - node.js: v10.24.1
 - 
**Additional context**

I just pulled the code from GitHub, installed the dependency, and then implemented the package without making any code changes. Such an error occurred

I tried to solve it. It's the FS of node For questions about utimes, refer to the link: [https://github.com/nodejs/node/issues/5561](https://github.com/nodejs/node/issues/5561)

**Comment by Top1zZ** [comment]
I'm curious. Hasn't anyone encountered such a problem?

**Comment by Top1zZ** [comment]
> Hello @Top1zZ , if you don't pass any arguments to the `build-platform` it will try to use your OS to try to build image. However, we have not yet started the campaign to support Windows.您好@Top1zZ，如果您不将任何参数传递给构建平台，它将尝试使用您的操作系统来尝试构建映像。但是，我们还没有开始支持 Windows 的活动。
> 
> Here are the list of other issues with Windows:以下是 Windows 的其他问题列表：
> 
> * [[BUG] Jest test cannot find matches on Windows #1310[BUG] Jest 测试在 Windows 上找不到匹配项#1310](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1310)
> * [https://github.com/opensearch-project/opensearch-build/labels/windowshttps://github.com/opensearch-project/opensearch-build/labels/windows](https://github.com/opensearch-project/opensearch-build/labels/windows)
> 
> Would you be able to try:你能试试： `yarn build --skip-os-packages纱线构建--skip-os-packages`
> 
> I'm not positive it will help actually produce a windows artifact but it's worth a try.我不肯定它会帮助实际产生一个 Windows 工件，但值得一试。
> 
> `build-platform` is a relatively new build script that is suppose to target single OS builds and that only support Linux or unix-like systems as of today.build-platform 是一个相对较新的构建脚本，假设针对单一操作系统构建，并且截至目前仅支持 Linux 或类 unix 系统。
> 
> We will need to create a meta issue about developer support on Windows and link it to this issue:我们需要创建一个关于 Windows 上的开发人员支持的元问题并将其链接到此问题： [opensearch-project/opensearch-build#33opensearch-project/opensearch-build#33](https://github.com/opensearch-project/opensearch-build/issues/33)
> 
> Apologies once again about this inconvenience.再次为给您带来的不便表示歉意。

Hi @kavilla,Thank you very much for responding to my question. It answers my doubts, and I will try to package on other platforms

**Comment by ahopp** [comment]
Based on the above information, we'll close this for now as there isn't a bug or Dashboard specific issues. The OpenSearch project is tracking the request for a signed (X64)Windows artifact for OpenSearch / OpenSearch Dashboards [here](https://github.com/opensearch-project/opensearch-build/issues/33).

**Comment by kavilla** [comment]
Will also link this issue for OpenSearch Dashboards side: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/796
