### ISSUE TITLE
Enable column resizing within the DISCOVER table

### ISSUE THREAD

**Issue by gsmith-sas** [opensearch-project/OpenSearch-Dashboards#1500]
**Is your feature request related to a problem? Please describe.**

The columns within the table on the DISCOVER panel cannot be resized.  The same limitation applies to the saved query widget/visualization used when including a query within a dashboard.

**Describe the solution you'd like**

It's 2022, adjustable column widths have been a standard feature of web-based tables for 20+ years.  It would be nice to see this capability come to OpenSearch Dashboards.  Developers should be able to set the column widths when creating/saving queries.  Users of those saved queries should be able to adjust the column widths.

**Describe alternatives you've considered**

The alternative we've been living with is accepting the somewhat random column widths and resulting odd text wrapping of data values the OpenSearch Dashboards currently presents.

**Comment by kavilla** [comment]
Thanks for opening @gsmith-sas,

Tagging @opensearch-project/opensearch-ux

**Comment by kgcreative** [comment]
Thank you @kavilla and @gsmith-sas -- this is high on our priority list as we evolve our UI library

**Comment by kgcreative** [comment]
Nothing short term yet. This has a dependency on refactoring the discover interface from angular to react, and then replacing the old table with either the new data grid, or an updated table component.

**Comment by anubisg1** [comment]
Yes, this is seemgly a small thing but it's incredibly important in the UI in terms of usability. I hope to see this done sooner than later

**Comment by ananzh** [comment]
@anubisg1  thank you and this is a great feedback. I am working on switching table vis from angular to react by using data grid component. I will add resizing column in my current scope.

**Comment by anubisg1** [comment]
> @anubisg1 thank you and this is a great feedback. I am working on switching table vis from angular to react by using data grid component. I will add resizing column in my current scope.

hello @ananzh , i know that this is a huge piece of work but i was wondering .. how is it progressing? do you need help with testing?

**Comment by mobiusmalware** [comment]
I feel like I'm resurrecting a dead thread but @ananzh is there progress on this? I just realized that a year on from the last update, resizing is still not possible.

**Comment by kgcreative** [comment]
@mobiusmalware This is now live in OpenSearch Dashboards 2.10 (New discover experience): https://playground.opensearch.org/app/data-explorer/discover#?_a=(discover:(columns:!(_source),isDirty:!f,sort:!()),metadata:(indexPattern:ff959d40-b880-11e8-a6d9-e546fe2bba5f,view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-30d,to:now))&_q=(filters:!(),query:(language:kuery,query:'')) -- we would love your feedback

**Comment by stevesimpson418** [comment]
> @mobiusmalware This is now live in OpenSearch Dashboards 2.10 (New discover experience): https://playground.opensearch.org/app/data-explorer/discover#?_a=(discover:(columns:!(_source),isDirty:!f,sort:!()),metadata:(indexPattern:ff959d40-b880-11e8-a6d9-e546fe2bba5f,view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-30d,to:now))&_q=(filters:!(),query:(language:kuery,query:'')) -- we would love your feedback

Resizing works for me but truncation settings are no longer respected it would seem. Raised: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5227

**Comment by gsmith-sas** [comment]
@kgcreative The new Discover 2 interface looks good...and it is very nice to (finally!) be able to resize the columns.  Thanks for addressing this long-standing gap/annoyance.  My only quibble with the new interface is that there seems to be a lot of wasted space in the field selection panel along the left-hand side:  there seems like there's a lot of the padding around the individual fields AND the additional padding between each field. While that increases readability, it seems like we could easily show twice as many fields and still be very readable with half as much padding.  

  I just created a Dashboard and added a Saved Search panel to it.  I had expected (hoped) to have the column resize capability in that object as well. But that doesn't appear to be the case; that's a bummer. I had assumed that it re-used the Discover interface components.  We use saved Dashboards (within OpenSearch Dashboards) to provide our users with a curated view of the data for many of their use-cases.

**Comment by kgcreative** [comment]
@gsmith-sas Thanks for this feedback! -- see #4995, which feels related to this issue as well, since it has to do with the data table embeddable for Dashboards

**Comment by ashwin-pc** [comment]
@gsmith-sas Yes the saved search visualization on the Dashboard was updated to use the same data table in 2.11. As Kevin mentioned, in 2.10 since we had to support both the legacy and current version of Discover, that was the compromise we had to make temporarily. 

As for the wasted space, I agree, data density and ease of use can be improved. Can you create a separate issue for that? I'll close this out in the meantime since the feature now exists.
