### ISSUE TITLE
Change blocklist to denylist to make consistency

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#1544]
In [this OpenSearch PR](https://github.com/opensearch-project/OpenSearch/issues/1547):

```
Replace the old usages that having "blacklist/whitelist" in configurations with "denylist/allowlist", then create duplicate usages with the old terminology for backwards compatibility (including fallback logic to fallback to settings with the new name).
```

There are several references to blocklist in the core dashboards repo. One customer facing example is for the Graphite blocklist feature. To make consistency, we should replaced `blocklist` to `denylist`, including something related, for example `graphiteBlockedIPs`. 

This should not break anything. It is just for code consistency purpose.

**Comment by tmarkley** [comment]
Is this a duplicate of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1319?

**Comment by joshuarrrr** [comment]
I think the intent is that `blocklist` terminology should also be updated to `denylist`, in addition to the `blacklist` -> `denylist` change covered by #1319

**Comment by tmarkley** [comment]
@joshuarrrr ahhh right, my brain was glossing over that when I first read it 😄

**Comment by kavilla** [comment]
Removing `2.1` label due to code cutoff being today.
