### ISSUE TITLE
[Initiative] Remove AngularJS as dependency

### ISSUE THREAD

**Issue by tmarkley** [opensearch-project/OpenSearch-Dashboards#1560]
We need to track the work required to remove AngularJS from the project. As of January 2022 it is EOL: https://blog.angular.io/discontinued-long-term-support-for-angularjs-cc066b82e65a

#1558 is the first CVE that has been identified, and there is no other option to resolve it (or any other CVEs that are found) other than removing the dependency.

**Comment by boktorbb-amzn** [comment]
### Angular in Dashboards:

### Overall App
- Will need to remove actual angular dependency from package.json
- Will need to update all docs with angular mentions
- Will need to update markdown files 
- Will likely need to update fonts and bootstrap code

### Discover

- [Discover angular directory](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/discover/public/application/angular)
- Doc Table needs to be reworked
- Data Grid needs to be reworked 
- Need to migrate to React Router
- [Doc Views](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/discover/public/application/doc_views)
- Discover controller will need to be reworked
- Discover Context view 

### Timeline

- [Timeline](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/timeline/public/application.ts) is written in angular and will need to be rewritten 

### Visualizations
- [vis_type_vislib](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/vis_type_vislib/public/vislib/lib/binder.ts) will need to be reworked
- [vis_type_table](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/vis_type_table/public/vis_controller.ts) will need to be reworked

### i18n Framework
- Will need to remove angular code from [i18n](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/packages/osd-i18n/src/angular)

### UI Shared Deps Package
- [osd-ui-shared-deps](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/packages/osd-ui-shared-deps/index.js) relies on angular and will need to be changed

### OpenSearch Dashboards Legacy
- [opensearch_dashboards_legacy](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/opensearch_dashboards_legacy/public/angular) plugin uses angular and will need to be reworked

**Comment by joshuarrrr** [comment]
How well do we understand or cover all the functionality of these components? Should part of this conversion process to add enough functional testing to make sure we maintain feature parity, or are there other ways we might be able to validate the conversions?

**Comment by tmarkley** [comment]
> How well do we understand or cover all the functionality of these components? Should part of this conversion process to add enough functional testing to make sure we maintain feature parity, or are there other ways we might be able to validate the conversions?

@joshuarrrr great point. I know we have some functional tests for [Discover](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/test/functional/apps/discover), the [Discover Context view](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/test/functional/apps/context), etc. but I'm not confident that the coverage is great. I think investing in functional tests ahead of the migration React is a great step, and we can take that opportunity to write them in Cypress as well (à la #754).

**Comment by tmarkley** [comment]
What's the status of this initiative and how much work is left?

**Comment by joshuarrrr** [comment]
@tmarkley - @ananzh is the dev lead of the overall de-angularization initiative. The first phase of work has been a re-write of the `vis_type_table` plugin: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2139

That work is targeting the `2.5.0` release. You can track the progress of the related tasks via the https://github.com/opensearch-project/OpenSearch-Dashboards/labels/tableVis label. Discover will be the largest remaining project, but we may also tackle the timeline vis and/or dashboards plugin in parallel. Frankly, there's a lot of remaining effort left, and we'd welcome community assistance in this effort.

**Comment by ananzh** [comment]
Hey @tmarkley, sorry I just notice this message. There are three main blocks for de-angular: visualzations, discover, dashboards.

* Currently we are working on cleaning visualizations. The two main parts are table and timeline.
* Discover re-write/replace is in progress. We are trying to make an alignment by collecting more customer usages and feedbacks. Then we will decide what features from Discover we want to keep and what we would like to add. This evaluation work is done by @ahopp .
* Dashboards: there are some work left here but not a lot.

After these three blocks, we will clean packages and make a final cleaning. I think we still have a lot of work to do. Currently, there is no one working on timeline and dashboards.

**Comment by ashwin-pc** [comment]
Current status:

| Plugin                       | Depends on | Status      | Tracking issue |
| ---------------------------- | ---------- | ----------- | -------------- |
| Discover                     | -          | In progress | #4216          |
| Dashboards                   | -          | In progress | #3365          |
| Timeline                     | -          | Completed   | #3366          |
| Visualizations               | -          | Completed   | #2137, #2187   |
| i18n Framework               | Discover   | In progress | #4018          |
| UI Shared Deps Package       | TODO       | In progress | TODO           |
| OpenSearch Dashboards Legacy | Discover   | In progress | #4020          |
| Tile Map & Region Map        | TODO       | In progress | TODO           |
| Data plugin                  | TODO       | In progress | TODO           |
| Clean css files              | TODO       | In progress | TODO           |
