### ISSUE TITLE
[D&D] Bar Chart

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#1616]
Requirements:
* Bar Chart is within D-n-D
  * ~~TODO: List of functional requirements for bar charts @ahopp @ashwin-pc~~
  * Does not need to be future parity 
* Testing
* Switching visualization (and potentially persisting configurations, if not possible then create a follow up issue)

Blocked by: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2073

**Comment by kavilla** [comment]
@CPTNB will hand off work with this.
