### ISSUE TITLE
API Status redaction

### ISSUE THREAD

**Issue by zhyuanqi** [opensearch-project/OpenSearch-Dashboards#1642]
OSD status API exposes service internal information.

Dashboards team need to investigate on solutions on OpenSearch Dashboards side. Possible options could be:

- Remove service internal information from status API

- Implement redaction within OSD as a plugin
      
- Enable authentication for status API

**Comment by kavilla** [comment]
Hello @zhyuanqi,

Thanks for opening. I have modified this to indicate just for OpenSearch Dashboards, this repo is forked from the legacy application but should be considered different. So we wouldn't be able to backport changes to legacy versions from within this this repo.

For the solution, I do believe this can be configured in most versions via the Security Dashboards plugin. For version 2.0.0, they [defaulted to ensure authentication](https://github.com/opensearch-project/security-dashboards-plugin/commit/d9cdb82f1653ccfbcc69ad68595d0df6db4f835b) but we should be able to configure `opensearch_dashboards.yml` to set `opensearch_security.basicauth.unauthenticated_routes: []` and `opensearch_security.auth.unauthenticated_routes: []`. Basically setting to empty to ensure they have to authenticate it.

If that resolves the issue I think we can move it to the security plugin repo.

**Comment by zhyuanqi** [comment]
Got it. Did not know this feature in security Dashbords plugin earlier. Thank you for the explanation here.

**Comment by ananzh** [comment]
@kavilla Since 2.0, if security plugin is installed, status api is authenticated by default. To disable it, you need to specifically do `opensearch_security.auth.unauthenticated_routes: ['/api/reporting/stats', '/api/status']` in opensearch_dashboards.yml. So we don't need to set `opensearch_security.basicauth.unauthenticated_routes: []` and `opensearch_security.auth.unauthenticated_routes: []`, right?

**Comment by kavilla** [comment]
Closing for now.

@seraphjiang, would you be able to provide more insight on the closure.

cc: @zengyan-amazon

**Comment by seraphjiang** [comment]
The metric information may contains some os, cpu information, which should be controlled by sever admin whether need to expose or not.

e.g. 
os.cpu.cpuacct
os.distroRelease

<img width="607" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/550437/7fd130c5-f9a1-438e-bd09-e7b46574a783">

**Comment by seraphjiang** [comment]
@wbeckler @dblock

**Comment by zhyuanqi** [comment]
Closing for it as after OSD 2.0,  status api is authenticated by default with security plugin.
