### ISSUE TITLE
Release version 1.3.3

### ISSUE THREAD

**Issue by tmarkley** [opensearch-project/OpenSearch-Dashboards#1680]
Coming from https://github.com/opensearch-project/opensearch-build/issues/2101

- [x] Release notes - https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1693
- [x] All Issues and PRs labeled with `v1.3.3` are closed: https://github.com/opensearch-project/OpenSearch-Dashboards/labels/v1.3.3
- [x] Publish a release: https://github.com/opensearch-project/OpenSearch-Dashboards/releases/tag/1.3.3

**Comment by kavilla** [comment]
@tmarkley, one thing to note, tag creation happens automatically post-release by a pipeline under the Jenkins job `release-tag-creation` but we still need to publish the release with that created tag.

**Comment by kavilla** [comment]
Release made from cut tag.
