### ISSUE TITLE
Failed to build OpenSearch-Dashboard [BUG]

### ISSUE THREAD

**Issue by Simbafa** [opensearch-project/OpenSearch-Dashboards#1681]
**Describe the bug**

**To Reproduce**
1. git checkout main
2. "nvm install 14.19.1" OK
3. "npm i -g yarn" OK
4. "yarn osd bootstrap" OK
5. "yarn build --docker" Failed

**OpenSearch Version**
2.0
**Dashboards Version**
2.0 and main are tried.

**Plugins**
Not changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/37646009/172362516-bfc27553-743d-494e-b729-2cfe7e8c1df8.png)

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser and version [e.g. 22]

**Additional context**

**Comment by Simbafa** [comment]
It's network issue.

**Comment by joshuarrrr** [comment]
@Simbafa Were you able to successfully build after the network issue was resolved?

**Comment by seanneumann** [comment]
Please re-open if you are still having issues. Thanks!
