### ISSUE TITLE
[Deprecation] Deprecate `master` nodes and replace with `cluster_manager` nodes

### ISSUE THREAD

**Issue by tmarkley** [opensearch-project/OpenSearch-Dashboards#1688]
Parent: #1318 

### Instances of `master` nodes

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/plugins/console/public/lib/osd/osd.js#L104

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/plugins/console/server/lib/spec_definitions/json/generated/cluster.state.json#L31

**Comment by joshuarrrr** [comment]
closed via https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1761
