### ISSUE TITLE
[Deprecation] Deprecate `setupMaster` in favor of `setupClusterManager`

### ISSUE THREAD

**Issue by tmarkley** [opensearch-project/OpenSearch-Dashboards#1689]
Parent: #1318 

### Instances of `setupMaster`

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/cli/cluster/cluster_manager.ts#L138

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/cli/cluster/cluster.mock.ts#L81

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/cli/cluster/worker.ts#L47

**Comment by joshuarrrr** [comment]
closed by #1752
