### ISSUE TITLE
[Non-Inclusive Lanuage] Replace references to `master` branch with `main`

### ISSUE THREAD

**Issue by tmarkley** [opensearch-project/OpenSearch-Dashboards#1691]
Parent: #1318 

### Instances of incorrect `master` branch references

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/bfetch_explorer/public/plugin.tsx#L78

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/developer_examples/README.md?plain=1#L17

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/embeddable_explorer/public/plugin.tsx#L89

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/routing_example/public/app.tsx#L70-L93

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/routing_example/public/plugin.tsx#L64-L79

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/search_examples/README.md#L9

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/state_containers_examples/public/plugin.ts#L83-L137

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/ui_actions_explorer/public/plugin.tsx#L137

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/url_generators_explorer/public/plugin.tsx#L73

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/opensearch-eslint-config-opensearch-dashboards/typescript.js#L100

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-config/src/config_service.test.ts#L45

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-config/src/env.test.ts#L39

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-eslint-import-resolver-opensearch-dashboards/import_resolver_opensearch_dashboards.js#L124

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-eslint-import-resolver-opensearch-dashboards/package.json#L13

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-eslint-import-resolver-opensearch-dashboards/README.md#L63

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-i18n/README.md#L125-L149

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-i18n/src/core/i18n.ts#L147

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-plugin-generator/README.md#L15-L44

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-plugin-generator/template/README.md.ejs#L10

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-pm/src/utils/projects.ts#L109

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-spec-to-console/README.md#L1-L16

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-spec-to-console/lib/convert.js#L40

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-test/src/failed_tests_reporter/add_messages_to_report.test.ts#L105-L251

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-test/src/failed_tests_reporter/get_failures.test.ts#L44-L115

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-test/src/failed_tests_reporter/run_failed_tests_reporter_cli.ts#L68-L70

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-test/src/failed_tests_reporter/__fixtures__/ftr_report.xml#L15-L31

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-test/src/failed_tests_reporter/__fixtures__/jest_report.xml#L3-L9

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-test/src/failed_tests_reporter/__fixtures__/mocha_report.xml#L18

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/release-notes/opensearch-dashboards.release-notes-1.1.0.md#L201

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/core/server/core_app/assets/legacy_dark_theme.css#L15

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/core/server/core_app/assets/legacy_light_theme.css#L15

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/core/server/http/http_config.ts#L44

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/core/server/plugins/discovery/plugin_manifest_parser.test.ts#L43

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/core/server/plugins/discovery/plugins_discovery.test.ts#L79

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/dev/ci_setup/checkout_sibling_opensearch.sh#L48

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/dev/ci_setup/get_percy_env.js#L66

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/legacy/server/config/schema.js#L64

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/plugins/embeddable/README.md#L11-L19

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/plugins/opensearch_dashboards_overview/README.md#L9

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/plugins/opensearch_dashboards_utils/common/state_containers/create_state_container_react_helpers.ts#L90

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/plugins/opensearch_dashboards_utils/common/state_containers/index.ts#L34

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/plugins/opensearch_dashboards_utils/common/state_containers/README.md#L2

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/plugins/opensearch_dashboards_utils/public/state_sync/index.ts#L35-L47

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/plugins/opensearch_dashboards_utils/public/state_sync/README.md#L3

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/plugins/opensearch_dashboards_utils/public/state_sync/state_sync.ts#L67

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/plugins/opensearch_dashboards_utils/public/state_sync/state_sync_state_storage/create_osd_url_state_storage.ts#L53

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/plugins/opensearch_dashboards_utils/public/state_sync/state_sync_state_storage/create_session_storage_state_storage.ts#L36-L47

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/test_utils/public/testbed/types.ts#L184-L186

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/tasks/docker_docs/Dockerfile#L18

**Comment by kaddy645** [comment]
@tmarkley I was validating the links and noticed many of the files does not exist! let me know whats the plans for these links!

1. [https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/foo/README.md](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/foo/README.md) Here we don't have **foo folder**, I am assuming it was just testing folder ?

2. We do not have **docs folder** at the moment! Some of the links (around 6 )are pointing to docs folder ! I found [this PR ](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/201) where we are removing docs folder! 
e.g 
[Link - 1](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/docs/development/core/server/opensearch-dashboards-plugin-core-server.irouter.md)

3. Some of the links are external so main/master not required ?
[https://github.com/yahoo/intl-messageformat/blob/master/src/core.js#L62](https://github.com/yahoo/intl-messageformat/blob/master/src/core.js#L62)

4. Are we also suppose make changes in xml files ? e.g

[mocha_report.xml](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-test/src/failed_tests_reporter/__fixtures__/mocha_report.xml#L18)

[jest_report.xml](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-test/src/failed_tests_reporter/__fixtures__/jest_report.xml#L3-L9)

**Comment by tmarkley** [comment]
> 1. https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/foo/README.md Here we don't have **foo folder**, I am assuming it was just testing folder ?

Yes this is just an example. We can still change `master` to `main`.

> 2. We do not have **docs folder** at the moment! Some of the links (around 6 )are pointing to docs folder ! I found [this PR ](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/201) where we are removing docs folder!

Correct, the docs folder does not exist anymore.

> 3. Some of the links are external so main/master not required ?
>        https://github.com/yahoo/intl-messageformat/blob/master/src/core.js#L62

Yeah, for some of these I think the branches did changes from master to main, but if not then we can leave them alone. For that link in particular it looks like the file name was changed: https://github.com/formatjs/intl-messageformat/blob/master/src/core.ts
 
>     4. Are we also suppose make changes in xml files ? e.g
> 
> 
> [mocha_report.xml](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-test/src/failed_tests_reporter/__fixtures__/mocha_report.xml#L18)
> 
> [jest_report.xml](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-test/src/failed_tests_reporter/__fixtures__/jest_report.xml#L3-L9)

I actually don't think we need these files anymore because they seem to be related to x-pack: 

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/89d3872f314aedf9c4f281ea73f784a5802e0175/packages/osd-test/src/failed_tests_reporter/add_messages_to_report.test.ts#L213-L218

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/89d3872f314aedf9c4f281ea73f784a5802e0175/packages/osd-test/src/failed_tests_reporter/add_messages_to_report.test.ts#L165-L171

Those can be handled in a separate issue/PR.
