### ISSUE TITLE
[D&D] Replace wizard naming convention

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#1706]
Renaming "Wizard" to "Visualization Builder"

Tasks:

In code reference of 'wizard' string: 
- [x] Rename `wizard` in code to `visBuilder` in function name, type name and class name
- [x] Replace class name prefixes `wiz` with `vb`
- [x] Replace file name and paths of 'wizard' to 'vis_builder'
- [x] Rename 'wizard' saved object type

UI/UX reference of 'wizard' string: https://github.com/opensearch-project/ux/issues/49
- [x] wizard editing page
- [x] dashboard page
- [x] visualization page
- [x] saved object page

**Comment by joshuarrrr** [comment]
It seems like there's consensus on "Vis Bulider": https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1157

**Comment by ashwin-pc** [comment]
@kgcreative @btzeng do we need to update the VisBuilder Logo since the old one was created to reflect the name "Drag and Drop"?

**Comment by kgcreative** [comment]
Probably not a bad idea tbh

**Comment by abbyhu2000** [comment]
I documented all the string reference of 'wizard' in the current dashboard UI: https://quip-amazon.com/tN23Aq10MmHz/References-of-wizard-string-in-dashboards

**Comment by kgcreative** [comment]
UX Issue for Icon: https://github.com/opensearch-project/ux/issues/45

**Comment by abbyhu2000** [comment]
Finish replacing wizard to VisBuilder for both UI and in-code reference for 2.4. There will be more discussions on some of the UI strings in the future.
