### ISSUE TITLE
[D&D] Add support for release as beta/preview feature

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#1708]
Core Requirement:
- [x] #1877

Other exit criteria (Needs to be finalized):
- [x] #1892
- [x] #1893
- [ ] #1962

**Comment by ashwin-pc** [comment]
@ahopp Do these requirements make sense?

**Comment by joshuarrrr** [comment]
The existing code makes distinctions between `beta` and `experimental` features, which mostly affect the language used:

### Beta

Message:
> This visualization is in beta and is subject to change. The design and code is less mature than official GA features and is being provided as-is with no warranties. Beta features are not subject to the support SLA of official GA features

via
- [new visualization selector](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/53e98a66a81cf986894962b5f17e4190baebf57f/src/plugins/visualizations/public/wizard/type_selection/type_selection.tsx#L240-L250)
- [visualization listing](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/6dfe116e3a478a1bf4df736485a24cd8372f09fc/src/plugins/visualize/public/application/utils/get_table_columns.tsx#L49-L54)

### Experimental

New visualization message:

> This visualization is experimental. The design and implementation are less mature than stable visualizations and might be subject to change.

via:
- [new visualization selector](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/53e98a66a81cf986894962b5f17e4190baebf57f/src/plugins/visualizations/public/wizard/type_selection/type_selection.tsx#L235-L238)

New visualization tooltip: 

> This visualization might be changed or removed in a future release and is not subject to the support SLA.

via:
- [new visualization selector](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/53e98a66a81cf986894962b5f17e4190baebf57f/src/plugins/visualizations/public/wizard/type_selection/type_selection.tsx#L230-L233)
- [visualization listing](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/6dfe116e3a478a1bf4df736485a24cd8372f09fc/src/plugins/visualize/public/application/utils/get_table_columns.tsx#L65-L68)

Banner message:

> This visualization is experimental and is not subject to the support SLA of official GA features.
>   For feedback, please create an issue in {githubLink}."

via:
- [`ExperimentalVisInfo`](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/6dfe116e3a478a1bf4df736485a24cd8372f09fc/src/plugins/visualize/public/application/components/experimental_vis_info.tsx#L40-L50)

@ahopp @kgcreative Can we get some updates for this language, both for general purpose use and for the `experimental` case we're using for D&D?
