### ISSUE TITLE
[BUG] Can't print strings that have more 256 characters in a datatable

### ISSUE THREAD

**Issue by NikolaiBirolini** [opensearch-project/OpenSearch-Dashboards#1713]
Hello everyone !

**Describe the bug**
I want to print a string from a redmine custom field in a datatable. But I can't print strings that have more than 256 characters.

**To Reproduce**
1. Transmit a string to the dashboard
2. Create a datatable
3. Select the index
4. Select terms and the corresponding field
5. Update

**Expected behavior**
This string : "Hello" will be print in the datatable
But a string that have more than 256 characters will be see as "Missing" in the datatable.

**Host/Environment (please complete the following information):**
 - OS: debian 9
 - Browser : firefox 91.10.0esr

**Additional context**
I inject my data with a Python code.

Thank you for your help,

**Comment by seanneumann** [comment]
Please re-open if you're still having issues. Thanks!
