### ISSUE TITLE
[DeAngularize] [Discover] clean doc_views component

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#1717]
This is a research issue for de-angular doc_views. 
There are couple of things done for doc_views:
1.deangular doc_view component
2.deangular doc view table component

What is left:
clean out registries and rest angular in doc_views
tests doc_views react component in discover

Requirements:
* Doc views is no longer in Angular
* Draft public documentation about component and usage

Related Issue:
This is part of our [De-angular project](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1560)

**Comment by ananzh** [comment]
Will research:
how to break one angular (directive+template/view+controller) 
how to make react work in an angular app

**Comment by kavilla** [comment]
Update: Collecting the work for executing this and breaking down.

**Comment by ananzh** [comment]
This is done. doc_views is completely react in Discover 2.0. Close this issue.
