### ISSUE TITLE
[MD]Credential management in stack management

### ISSUE THREAD

**Issue by seraphjiang** [opensearch-project/OpenSearch-Dashboards#1733]
be able to CRUD credential to support multiple datasource

![image](https://user-images.githubusercontent.com/550437/173461437-c69b9b08-dcdd-46ca-a6bd-e60e63863201.png)

Temporal tasks break down table with rough estimation. Will update the dates afterwards with more contexts.

- [x] #1804
- [x] #1839
  - [x] #1742 
  - [x] #1810
- [x] Credential Saved Object on Data Source Plugin
  - [x] #2081
    - [x] #1813
    - [x] #1828
    - [x] #1938
  - [x] #1850
  - [x] #1926
  - [x] #2023
  - [x] #2124
  - [x] #2207
- [ ] Credential Management pages on CM Plugin
  - [x] Create UX mock pages
  - [x] Add Save credential frontend page
  - [x] Add Credential editing frontend page
  - [x] Add Credential management frontend page
  - [x] #1977
    - [x] #2144
    - [x] #1902
    - [x] #2047
    - [x] #2048
    - [x] #2049
    - [x] #2050
    - [x] #2051
    - [x] #2055
    - [x] #2060
    - [x] #2184
  - [x] #1973
  - [x] #1876 
  - [x] #1968
  - [x] #1978
  - [x] #2025
  - [x] #2024
  - [x] #2027
- [x] #1904
- [ ] MISC
  - [ ] [MD] Remove runtime generated ts.map file
  - [x] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2150/
  - [x] #2158
- [ ] Security Review
  - [x] Threat modeling 
  - [x] Pen test preparation
- [ ] Unit test
  - [x] Add unit test for crypto module
  - [x] #2068
  - [x] #2033
  - [x] #2169
- [ ] Integration test 
  - [x] #2206
  - [ ] Add integration test for decryption

### Documentation Tasks

- [x] #2199

### Optional Tasks

1. #1976
2. #1872
3. #1945
4.  [MD] Support Keyring rotation and update encrypted field of all credentials (Optional)
5. #2046
6. #2110
7. #2035 
8. [MD] Support multiple Keyrings

**Comment by zhongnansu** [comment]
closing. Since all required tasks are marked as done
