### ISSUE TITLE
Creating sample packages

### ISSUE THREAD

**Issue by BT-93** [opensearch-project/OpenSearch-Dashboards#1747]
**Is your feature request related to a problem? Please describe.**

Just like the sample packages that come with OSD, I'd like to create my own sample package.

**Describe the solution you'd like**

A way to implement a sample package with sample data, where timestamp fields are replenished with current times.

**Describe alternatives you've considered**

¯\_(ツ)_/¯

I use a script atm but would be great for demo purposes to have this inbuilt.

**Additional context**

![image](https://user-images.githubusercontent.com/94328741/173719643-25566b28-a27e-46de-9204-6631ed38617e.png)

**Comment by ashwin-pc** [comment]
@BT-93 I'm not entirely sure i understand the ask here. Are you referring to `plugins` here? If thats the case we already have a package [`osd-plugin-generator`](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/packages/osd-plugin-generator) to do this. It can scaffold 3 types of plugins:

- An Example plugin that resides within `/examples`
- A Core plugin that resides within `/src/plugins`
- Or an external plugin that isnt committed into the codebase and resides within `/plugins`. I assume this is what you want to do.

Loading a plugin dynamically from the Dashboard is not a feature we have today but is being discussed in #287. 

As for loading sample data, even the existing sample data feature simple performs a bulk upload to upload sample data. This feature can be mimicked easily using the existing data plugin once your sample plugin is scaffolded.  The example plugins are a good way to see how to build such a plugin.

**Comment by BT-93** [comment]
@ahopp I too am in favour of the latter you mentioned. I don't have a solution locally I've been digging around to try and work out how the samples are created currently. My script just sends random data with relative timestamps between dates to OS. 

@ashwin-pc 
I see, thanks for the info. I'm just interested in loading sample data. I haven't had much time to dig around to see how the sample data feature fully works. I'll have a look at the sample plugins. I did notice there was a script that replenishes timestamps in there.

My request was a bit vague. I'm interested in how it currently works so I can mimic something in the meantime. I'm also interested in community sample packages.

**Comment by ashwin-pc** [comment]
@BT-93 Thanks for the clarification. We can go many different ways to achieve what you are looking for. From a project perspective the most useful feature here would be as @joshuarrrr mentioned a plugin that can import static data. This wont address your concern for timestamps but it should make loading data a lot easier for testing purposes.

for your specific issue here, I can reccomend two approaches. 

1. use logstash to generate periodic data and upload to opensearch.
2. create a `sample data generator` plugin that can take in some parameters and generate periodic data.

Installing sample data is handled in https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/home/server/services/sample_data/routes/install.ts#L0-L1 which you can reference for your use case if you decide to go with the second approach.

**Comment by BT-93** [comment]
@ahopp Yes it does, thanks! All good. Thanks all for the info.

**Comment by seraphjiang** [comment]
@Flyingliuhub this might align with what playground and create generic way to support ingestion example for user e.g. demo for plugin.
