### ISSUE TITLE
[MD] Research on encryption / decryption strategies

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/OpenSearch-Dashboards#1756]
This is the sub issue for https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1720

# Research outline

1. Research on NodeJs Cryptography package 
    1. Bcrypt VS native crypto - Recommend  native crypto
    2. appendix - bcrypt vs bcryptjs
2. Research on Encryption / Decryption Algorithms
    1. Hash? - No Hash
    2. symmetric VS asymmetric - symmetric
    3. which symmetric algorithm - AES-GCM
    4. Recommendation / Best practices

### Bcrypt VS native crypto - Recommend  native crypto

bcrypt (https://www.npmjs.com/package/bcrypt) is a npm repository that provides robust **hashing functions** for password encryption that is also computationally expensive and irreversible. Examples of usage include:

```
const bcrypt = require('bcrypt');
const saltRounds = 10;
const myPlaintextPassword = 's0/\/\P4$$w0rD';
const someOtherPlaintextPassword = 'not_bacon';
```

Crypto (https://nodejs.org/api/crypto.html) is a native NodeJS library that provides hashing as well as encryption and decryption. From a security standpoint, using an external module from npm opens the door for malicious code to be injected, defeating the original security goal. *As a result, we recommend using the native crypto library.* Examples of usage include as documented on :

```
const {
  scrypt,
  randomFill,
  createCipheriv
} = await import('node:crypto');

const algorithm = 'aes-192-cbc';
const password = 'Password used to generate key';

// First, we'll generate the key. The key length is dependent on the algorithm.
// In this case for aes192, it is 24 bytes (192 bits).
scrypt(password, 'salt', 24, (err, key) => {
  if (err) throw err;
  // Then, we'll generate a random initialization vector
  randomFill(new Uint8Array(16), (err, iv) => {
    if (err) throw err;

    // Once we have the key and iv, we can create and use the cipher...
    const cipher = createCipheriv(algorithm, key, iv);

    let encrypted = '';
    cipher.setEncoding('hex');

    cipher.on('data', (chunk) => encrypted += chunk);
    cipher.on('end', () => console.log(encrypted));

    cipher.write('some clear text data');
    cipher.end();
  });
});
```

### Hash?  - No Hash

The use case for our credential encryption: on OpenSearch Dashboard, the data is encrypted using a standard encryption algorithm that ensures data integrity, and the key must be decrypted and passed to OpenSearch for further authentication. As a result, we cannot use irreversible hashing functions.

### Symmetric VS Asymmetric? - Symmetric

The use case of our credential encryption (as mentioned above) is categorized as **encryption of data at rest.**

Symmetric encryption, which employs a single key, is preferable for *data-at-rest*. Data stored in databases must be encrypted to prevent it from being compromised or stolen. Because this data only needs to be safe until it needs to be accessed in the future, it does not require two keys, only the one provided by symmetric encryption.

Asymmetric encryption, on the other hand, has typical use case such as data sent to other people via email. If only symmetric encryption was used on data in emails, an attacker could steal or compromise the data by obtaining the key used for encryption and decryption. Because their public key was used to encrypt the data, the sender and recipient ensure that only the recipient can decrypt the data using asymmetric encryption. Both types of encryption are used in conjunction with other processes, such as digital signing or compression, to provide additional data security.

### Which symmetric Algorithm?

AES-GCM, as recommended by NIST (National Institute of Standards and Technology) - Ref https://csrc.nist.gov/publications/detail/sp/800-38d/final

### Other Recommendation / Best practices

* It is recommended that **symmetric** keys be generated from the text to be encrypted rather than provided by the API caller, which the later adds risks to data security. Ref - key derivation function https://en.wikipedia.org/wiki/Key_derivation_function
* Good to have - For the implementation, define a key-management or lifecycle that includes secure key generation or establishment, key storage, key destruction, and key rotation.
* Use an AES key in preference order of 256 or 128 bits.
* Use a mac_tag size of 128 bits.
* Never encrypt more than 236 – 32 bytes, or protect more than 261 – 1 bytes of additional data in a single invocation (a call to the AES_GCM_Encrypt( ) primitive).
* Do not use decrypted plaintext if message authenticity fails.

**Comment by seraphjiang** [comment]
Thanks for research and recommendation about encryption strategy for multiple data source key.

I have a question from user's view
As a user, I need a symmetric-key string or file to configure my dashboards site to enable multiple-datasource feature. Is there a keygen tool I could use to generate a strong key satisfied all requirement/recommendation.

**Comment by noCharger** [comment]
> Thanks for research and recommendation about encryption strategy for multiple data source key.
> 
> I have a question from user's view As a user, I need a symmetric-key string or file to configure my dashboards site to enable multiple-datasource feature. Is there a keygen tool I could use to generate a strong key satisfied all requirement/recommendation.

That's a good question.

Based on security best practices, symmetric keys are generated from the encrypted text(https://en.wikipedia.org/wiki/Key derivation function). However, from my understanding so far, it's a question of user experience design: do we want to provide an experience that allows administrators to provide / configure symmetric keys?

If yes, we can implement this functionality and make design decisions on implementation details, such as the keystore interface for key management mentioned in the **Other Recommendation / Best Practices** section.

Related issues are:

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1743
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1759

**Comment by seraphjiang** [comment]
> do we want to provide an experience that allows administrators to provide / configure symmetric keys

it is must-have, site-admin should be able to choose their own key, hardcode key in code is not secure. 
also, we don't/shouldn't provide any UI management feature to configure this key. the key must be in dashboards.yml file

**Comment by seraphjiang** [comment]
> we can implement this functionality and make design decisions on implementation details, such as the keystore

What functionality we plan to implement. could we come up proposal use case before research?

**Comment by noCharger** [comment]
> it is must-have, site-admin should be able to choose their own key, hardcode key in code is not secure.
> also, we don't/shouldn't provide any UI management feature to configure this key. the key must be in dashboards.yml file

Thanks for clarification. According to my previous response, only site-admin should have access to the key, and there should be no UI to configure the key. However, the key is not hardcoded and is either provided by site-admin or generated by 'crypto.scryptSync' - a password-based key derivation function that is designed to be expensive computationally and memory-wise in order to make brute-force attacks unrewarding (https://nodejs.org/api/crypto.html#cryptoscryptsyncpassword-salt-keylen-options).

The detailed context and story on symmetric key will be updated on this issue as the next step. https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1743

**Comment by noCharger** [comment]
> > we can implement this functionality and make design decisions on implementation details, such as the keystore
> 
> What functionality we plan to implement. could we come up proposal use case before research?

Yes, as stated in my previous response, the functionality is to provide an interface for site-admin to provide keys from either (a file directory / a remote keystore / a cloud service such as KMS).

**Comment by Flyingliuhub** [comment]
I'm assuming that Amazon Web Services already have similar implementation, do you have any chance to take a look the existing SDK, like as [aws-encryption-sdk-java](https://github.com/aws/aws-encryption-sdk-java). Thanks

**Comment by seraphjiang** [comment]
> 

Definitely it could be option if there is open source lib. I'd like to call out one tenet, AWS itself should not get additional weight to the decision making.

**Comment by noCharger** [comment]
> I'm assuming that Amazon Web Services already have similar implementation, do you have any chance to take a look the existing SDK, like as [aws-encryption-sdk-java](https://github.com/aws/aws-encryption-sdk-java). Thanks

> > 
> 
> Definitely it could be option if there is open source lib. I'd like to call out one tenet, AWS itself should not get additional weight to the decision making.

Excellent points! The AWS Encryption SDK, like OSD, is distributed for free under the Apache 2.0 license. I'll look into it and report back on the results.

**Comment by AMoo-Miki** [comment]
I am not convinced that we needed an AWS package to do a simple AES encryption which is built into Node.

**Comment by noCharger** [comment]
> I am not convinced that we needed an AWS package to do a simple AES encryption which is built into Node.

Hi @AMoo-Miki, updated the issue with more context. Please review~

**Comment by AMoo-Miki** [comment]
@noCharger, I found the updated text very informative and helpful in my understanding of the reasoning behind the choice. Thanks a ton for your research and the update.
