### ISSUE TITLE
Reinvent Discover Plugin

### ISSUE THREAD

**Issue by seanneumann** [opensearch-project/OpenSearch-Dashboards#1792]
**Is your feature request related to a problem? Please describe.**

The existing Discover plugin contains a large amount of AngularJS 1.8 code which needs to be replaced with React. This is required for security and code base consistency. Instead of refactoring the existing codebase, this may be a good opportunity to create a new modern plugin. 

Let's use this issue to start discussing what that new experience can be.

**Comment by ananzh** [comment]
* Understand Discover which includes setup & start discover and core functions  https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3112
* Rewrite Evaluation: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3104

**Comment by ashwin-pc** [comment]
Closing in favour of #4165
