### ISSUE TITLE
Error: no handler found for uri [/_plugins/_security/authinfo] and method [GET]

### ISSUE THREAD

**Issue by davidvossw** [opensearch-project/OpenSearch-Dashboards#1812]
Hello
I can not login to the Dashboard. I have configured admin / admin in opensearch_dashboards.yml.

I get error: "Invalid username or password" and in dashboard Log:
[error][plugins][securityDashboards] Failed authentication: Error: no handler found for uri [/_plugins/_security/authinfo] and method [GET]

Any idea what to do to solve this?

I run opensearch 2.0.1 and dashboard on same cent os 8 stream.

thanks

**Comment by CPTNB** [comment]
Hi, this is an issue with the [security plugin](https://github.com/opensearch-project/security).  Please make sure it's properly installed and if your issue persists you can reopen against that repository.

**Comment by bob4inski** [comment]
How to check that plugin is installed?
