### ISSUE TITLE
[BUG][Tests] `should show Percentile Ranks` test failure

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#1821]
**Describe the bug**

`should show Percentile Ranks` is currently failing because it is expecting `2.036%` but the value being returned is from OpenSearch is:  `2.029%` for this [test](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/test/functional/apps/visualize/_metric_chart.js#L177).

**To Reproduce**
1. Run `node scripts/functional_tests.js --config test/functional/config.js --include ciGroup10`

**Expected behavior**
The value returned from OpenSearch should be `2.036%`.

**OpenSearch Version**
3.0 (NOTE: this test passes on 2.x and started failing on 3.x within the pass couple days)

**Dashboards Version**
3.0

**Plugins**
none

**Screenshots**
n/a

**Host/Environment (please complete the following information):**
All environments

**Additional context**
Link to example failure: https://github.com/opensearch-project/OpenSearch-Dashboards/runs/7119441424?check_suite_focus=true

**Comment by dblock** [comment]
This is caused by upgrading t-digest to 3.3 in https://github.com/opensearch-project/OpenSearch/pull/3634. Version 3.2 was interpolating results, therefore the old number is wrong, while the new number is right.
