### ISSUE TITLE
[BUG] Incomplete welcome readme

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#1847]
**Describe the bug**

The welcome section in the main Readme does not make sense. It currently reads 

> OpenSearch Dashboards is an open source search and analytics visualization.

**To Reproduce**
1. Go to [`./Readme.md`](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/README.md?plain=1#L11)
4. See text

**Expected behavior**
Expect the welcome text to be clearer about what the project is/does

**Comment by kavilla** [comment]
[Triage]: @joshuarrrr please reach out to doc team about getting something formalized.

@kavilla: do we need to gather and formalize what this project is and then ask for formalization.

**Comment by vagimeli** [comment]
@ashwin-pc I'll handle. Thanks :)

**Comment by vagimeli** [comment]
@joshuarrrr and @kavilla Here's my rewrite of the Welcome section. Do we have a link to add to the sentence "take a look at what the community has been doing"? It'd be helpful to direct the user to that information.  

_OpenSearch Dashboards is an open-source visualization tool designed to work with OpenSearch. OpenSearch Dashboards gives you data visualization tools to improve and automate the visual communication process. By using visual elements like charts, graphs, or maps to represent data, you can advance business intelligence and support data-driven decision-making and strategic planning. 

We aim to be an exceptional community-driven platform and to foster open participation and collective contribution with all contributors. Please take a look at what the community has been doing and then take a look at the [Project Board](https://github.com/opensearch-project/OpenSearch-Dashboards/projects) to track release targets, [open issues](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/new/choose), [set up your development environment](DEVELOPER_GUIDE.md#getting-started), or [contribute to the project](CONTRIBUTING.md)._

**Comment by joshuarrrr** [comment]
>  Do we have a link to add to the sentence "take a look at what the community has been doing"? It'd be helpful to direct the user to that information. 

I'm not sure what the original intent of that sentence was, but I suspect it was implying "take a look at what the community has been doing by reviewing recent [issues](https://github.com/opensearch-project/OpenSearch-Dashboards/issues) and [pull requests](https://github.com/opensearch-project/OpenSearch-Dashboards/pulls)."

**Comment by joshuarrrr** [comment]
> Should the Project board link be updated to https://github.com/orgs/opensearch-project/projects/63/views/5?filterQuery=?

I don't think so - I suggest cutting that until we have a better org-wide milestone tracker.

> Should the link to the development environment be updated to https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md?

Should be https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md#getting-started-guide
