### ISSUE TITLE
[UX] Restyle global breadcrumbs

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#1858]
As a follow-on to #1583 and a supporting feature for #1248, we'd like to enhance the breadcrumb component in the global header to be more useful and integrated into the overall look and feel.

**Comment by kavilla** [comment]
Adding @kaddy645 as they will develop this.

**Comment by KrooshalUX** [comment]
Here are the proposed look & feel updates to breadcrumbs:

**Current Design:**
<img width="1014" alt="Screen Shot 2022-07-19 at 8 19 22 PM" src="https://user-images.githubusercontent.com/105819041/179889144-c00d3ca9-df34-4bdd-9e2b-4cb11b8e0490.png">

**Proposed Design:**
<img width="1005" alt="Screen Shot 2022-07-19 at 8 19 30 PM" src="https://user-images.githubusercontent.com/105819041/179889170-5159550c-ea35-46be-b075-de65c01ab615.png">

**Details:**
What to retain:
- Retain current truncation rules for breadcrumb titles
- Retain current breadcrumb step truncation logic
- Retain typography treatment

What to update:
- Remove auto generated “/” characters between breadcrumb steps
- Introduce background shapes with the following details: 
      - Colors:
            - Active / Current Breadcrumb Step : #b9d9eb
            - Inactive / Previous Step: #d9e1e2
      - Shape:
            - Global:
                  - Corner Radius: 2px
                  - Spacing: Steps within breadcrumb appear to have a gap and never intersect
                        - <img width="237" alt="Screen Shot 2022-07-19 at 6 35 49 PM" src="https://user-images.githubusercontent.com/105819041/179889708-9a043323-d099-49f0-ac1a-392ec894fbda.png">
                  - Single Breadcrumb and/or First Breadcrumb Step: Left rectangular end scalable to fit using current truncation rules, right angle end
                        - <img width="528" alt="Screen Shot 2022-07-19 at 5 19 24 PM" src="https://user-images.githubusercontent.com/105819041/179890008-7146eb94-8801-458b-929e-afcfbe9b5655.png">

                  - Second and all following breadcrumb steps: Left angle end, rectangular center scalable to fit using current text truncation rules, right angle end.
                        -  <img width="755" alt="Screen Shot 2022-07-19 at 5 19 32 PM" src="https://user-images.githubusercontent.com/105819041/179890027-aa130b43-9dff-4ced-95f1-1953b280ad8d.png">
                        - Previous step retains background treatment, but color changes from Active/Current step to Inactive/Previous Step 
                              - <img width="690" alt="Screen Shot 2022-07-19 at 5 25 15 PM" src="https://user-images.githubusercontent.com/105819041/179890129-950b984a-34b3-42f6-ba7a-16745579bfea.png">
                  - Truncated Step: Updated alignment, padding and color (#003b5c)
                        -  <img width="297" alt="Screen Shot 2022-07-19 at 6 51 08 PM" src="https://user-images.githubusercontent.com/105819041/179890209-691c4aa7-6015-46fa-b0de-bb458bf4802a.png">
                        - <img width="298" alt="Screen Shot 2022-07-19 at 6 54 53 PM" src="https://user-images.githubusercontent.com/105819041/179890211-8a723265-94c4-4cdf-ba45-266b5cda1eb9.png">
