### ISSUE TITLE
[MD]Best practice for credential import (Optional)

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/OpenSearch-Dashboards#1872]
Users must currently type credentials manually as part of the credential management story. 
![image](https://user-images.githubusercontent.com/44716267/178130654-769214ee-6c3f-4da7-90f5-19250c47782d.png)

Credentials can also be imported / uploaded via a browser page. The purpose of this issue is to discuss best practices for credential import.

Example:
![image](https://user-images.githubusercontent.com/44716267/178130632-f8da5956-2a6d-4470-b7a8-49bfd0c3818c.png)

Priority = P2

**Comment by seraphjiang** [comment]
could we add more detail and context so others could know?

**Comment by noCharger** [comment]
Close these optional issues for now, will reopen based on priority
