### ISSUE TITLE
[BUG] TSVB y-axis missing

### ISSUE THREAD

**Issue by Artain** [opensearch-project/OpenSearch-Dashboards#1873]
**Describe the bug**

All y-axis in the TSVB visualizations are missing.

**To Reproduce**
1. Update to version 2.0.1 or 2.1.0 
2. Create a TSVB

**Expected behavior**
Y-axis should be visible as it was before

**OpenSearch Version**
2.0.1; 2.1.0

**Dashboards Version**
2.0.1; 2.1.0

**Plugins**

Default

**Comment by kavilla** [comment]
Thanks for opening this @Artain! Sorry about that and I am seeing issues as well.

@ananzh I see you assigned yourself to it. Do you have any insight on this? I was wondering if the [SASS lint update](https://github.com/opensearch-project/OpenSearch-Dashboards/commit/6c13abeac3e3f9ac4567a9f01e1af910eaad26f4) or [rendering expressions update](https://github.com/opensearch-project/OpenSearch-Dashboards/commit/1ad1a8bbba3645478d021b541d9f3c3321b2c1cc) had something to do with it but I reverting both and still not seeing it as well (albeit I didn't completely dump my node_modules).

Perhaps this was introduced in the EUI bump and we neglected to update something.

**Comment by jimkaba** [comment]
I can further add an observation that this bug existed prior to version 2.x.x.
I observed it after upgrading from v1.2.3 (where Yaxis labels were rendered correctly) to v1.3.2 (where Yaxis labels were no longer displayed.)  So the bug was likely introduced somewhere between those versions.  The problem persisted with upgrades to v2.0.1 and 2.1.0.

**Comment by jimkaba** [comment]
I'll also add that a temporary work-around for some people is to set "separate axis" to "yes" under options tab settings under the data tab.  HOWEVER, doing so exposes what may be another bug -- namely, if the Axis Scale was selected as "Log" under the Panel Options tab settings, this selection will be overridden (and forced to "Normal") when "separate axis" is set to yes.

**Comment by kavilla** [comment]
> @kavilla @AbhishekReddy1127 I can further add an observation that this bug existed prior to version 2.x.x. I observed that it appeared after upgrading from v1.2.3 (where Yaxis labels were rendered correctly) to v1.3.2 (where Yaxis labels were no longer displayed.) So the bug was likely introduced somewhere between those versions. The problem persisted with upgrades to v2.0.1 and 2.1.0.

This is great insight thank you @jimkaba

**Comment by AMoo-Miki** [comment]
Just to sum up, OSD v1.3.4 shows the y-axis on TSVB but v2.0.0 doesn't. My thought is that the bump in `eui-charts` has caused this but I can't be sure.

**Comment by ananzh** [comment]
> 



> Just to sum up, OSD v1.3.4 shows the y-axis on TSVB but v2.0.0 doesn't. My thought is that the bump in `eui-charts` has caused this but I can't be sure.

Found this error in console log 
```
react_devtools_backend.js:4026 [@elastic/charts] Cannot compute scale for axis spec yaxis_763acdb0-12b1-11ed-a7c9-057fc4ef8dd4_main. Axis will not be displayed.
```
<img width="980" alt="Screen Shot 2022-08-02 at 15 28 21" src="https://user-images.githubusercontent.com/79961084/182484800-51ed0066-06c3-4e91-af3e-99035a2c7cda.png">

**Comment by ananzh** [comment]
Meanwhile compare props of XYChart from v1.3.4 and v2.0.0
v1.3.4
<img width="636" alt="Screen Shot 2022-08-02 at 15 49 24" src="https://user-images.githubusercontent.com/79961084/182486712-b273d422-e2a2-4bf7-a8b4-577503dd4bc6.png">

v2.0.0
<img width="482" alt="Screen Shot 2022-08-02 at 15 48 53" src="https://user-images.githubusercontent.com/79961084/182486758-892b73cc-825d-4153-9644-3f4deccc5d5f.png">

axesTicksDimensions which has the y axis percentage values and axesTicksPosition are missing
<img width="636" alt="Screen Shot 2022-08-02 at 15 53 38" src="https://user-images.githubusercontent.com/79961084/182487109-839e824c-6f10-4659-9def-51bcecc600b1.png">
