### ISSUE TITLE
[OfficeHour] Understand De-Angularization work

### ISSUE THREAD

**Issue by pjfitzgibbons** [opensearch-project/OpenSearch-Dashboards#1874]
I need to hear further details about work to convert legacy Angular modules into React.

**Comment by kavilla** [comment]
Hello @pjfitzgibbons, I think we can close this as we are using https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1560 to track the work. If that is okay with you?

**Comment by kavilla** [comment]
There were questions about state management which here is some more details: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/opensearch_dashboards_utils/docs/state_containers/README.md. We are working on indexing this information and making publicly accessible. 

But plugins have opted to their own state management. Drag and Drop is currently using redux.

Please follow up on #1560 if you would like to take on converting, current priority 0 is move over the Discover Plugin. Please re-open this issue if this doesn't satisfy your questions.
