### ISSUE TITLE
[Vis Builder] Add validation steps between serialization/deserialization and state sync

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#1881]
As a follow-up to #1870

- [ ] Make sure states are valid [before serializing](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/8c50d0f87d4036e5bdb7bb18a09a3f52f214e6b3/src/plugins/wizard/public/application/utils/get_top_nav_config.tsx#L94-L95), [handle errors](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1880)
- [x] Clean/remove unsupported properties [before dispatching state updates](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/8c50d0f87d4036e5bdb7bb18a09a3f52f214e6b3/src/plugins/wizard/public/application/utils/use/use_saved_wizard_vis.ts#L47-L48)

**Comment by kavilla** [comment]
@ashwin-pc  are you picking this one up?

**Comment by kavilla** [comment]
Follow-up: Can the work applied here be applied in other places?

**Comment by kavilla** [comment]
Assigning to @ashwin-pc

**Comment by kavilla** [comment]
[Planning]:

Needs verification if this completed.

**Comment by joshuarrrr** [comment]
@abbyhu2000 Is this complete?

**Comment by abbyhu2000** [comment]
> @abbyhu2000 Is this complete?

I think @ashwin-pc said he will confirm on this one. @joshuarrrr

**Comment by joshuarrrr** [comment]
@ashwin-pc Can we close?

**Comment by ashwin-pc** [comment]
Still haven't found the time to do this.
