### ISSUE TITLE
[D&D] Functional: validate export/import of saved objects

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#1885]

**Comment by ashwin-pc** [comment]
@joshuarrrr What exactly do we need to test for this flow? I have as a part of the functional test flow steps to seed saved object data for Vis Builder. Would that cover the import section of this test? 

Also does this need to be a part of the vis builder functional test suite or Dashboards in general?

**Comment by joshuarrrr** [comment]
After looking at this again, I'm not sure it's in scope? It's more about testing whether we correctly integrated with the saved object management plugin, so that some of its standard flows (such as importing/exporting via UI) work as expected. 

But given the open issues around import/export, such as https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1526 and https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1723, I wonder if that work would be better done in a more comprehensive look at the saved object management behavior in general.

So I think I'd recommend just closing this issue, especially if we've manually validated that import/export through the UI works as expected.

**Comment by ashwin-pc** [comment]
Closing this as per @joshuarrrr recommendation. Will need a comprehensive "saved object management" test flow thats separate from VisBuilder

**Comment by ashwin-pc** [comment]
Closing this as per @joshuarrrr recommendation. Will need a comprehensive "saved object management" test flow thats separate from VisBuilder
