### ISSUE TITLE
[BUG] Some core plugin API documentations are missing

### ISSUE THREAD

**Issue by bandinib-amzn** [opensearch-project/OpenSearch-Dashboards#1895]
**Describe the bug**

Some core plugin API documentations are missing

**To Reproduce**
1. Go to https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/core
2. Click on Core Public API, Core Server API, OpenSearch Dashboards Platform Plugin API
3. See ```Page not found``` error

**Expected behavior**
It should redirect to valid documentation. 

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by ashwin-pc** [comment]
Looks like these used to point to developer docs which we no longer have. But it might be worthwhile to point them to the [public](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/public/public.api.md#L0-L1) and [server](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/server/server.api.md#L0-L1) API report files in the meantime. They are not as easy to read as dedicated docsite links but will still be useful in the meantime while we get that up and running

**Comment by manasvinibs** [comment]
@ashwin-pc For OpenSearch Dashboards Platform Plugin API, do you think this is a good link to point to for now -https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/PRINCIPLES.md ?
