### ISSUE TITLE
[FTR] Remove upstream deps downloads from Kibana dev / test env.

### ISSUE THREAD

**Issue by mihirsoni** [opensearch-project/OpenSearch-Dashboards#19]
Currently codebase rely on upstream snapshots and bundles for running ES, remove it and update it with BFS elasticsearch

https://github.com/opendistro-for-elasticsearch/search

**Comment by kavilla** [comment]
Is this accurate anymore? Like it's removed but we don't have the replacement with the correct snapshot url when we have one.
