### ISSUE TITLE
[D&D] Fix support for query, filter and timerange

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#1903]
Currently query, filter and timerange settings applied in the top nav do not affect the visualization. Fix this to correctly aggregate the data based on these filters. 

- [x] Add support for updating the expression context based on query, filter and timerange
- [x] Updating the ranges should automatically update the viz

**Comment by joshuarrrr** [comment]
Closed via #1905
