### ISSUE TITLE
[Vis Builder] Persist the global query parameters including global filters, time range and time filters

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#1913]
Problem: In the top navigation bar, if user made modification to the global filters, time range, and time refresh intervals, the values will not get saved when they refresh the page, or when they navigate away to another app. 

Expected behaviors: Those values should persist when they refresh the page, or when they navigate to visualize, discover, timeline and dashboards app.

Requirements:
* Figure out how to do this with how plugins do this and then update this issue with the approach
* Document the findings for how plugins do this
* Implement
* Tests (if we have something custom was implemented)

**Comment by kavilla** [comment]
Note: first understand how this is being done today (is this related to URL followed by filters), if this is the current behavior then keep it that way. But we need to do the research here.

**Comment by abbyhu2000** [comment]
Research on how current plugins achieve data persistence: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2876
