### ISSUE TITLE
[BUG] [D&D] Editing saved viz after switching index pattern broken

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#1917]
**Describe the bug**

when editing a saved Vis who's index pattern is not the default index pattern, it causes the D&D editor to crash.

**To Reproduce**
1. Go to Wizard
2. Change the default index pattern
3. Drop a field to aggregate
4. Save the Vis
5. Reload the page
6. Page crashes because the agg service cannot find the field in the default index pattern. It should be looking in the saved index pattern

**Expected behavior**
The editor should open again with the correct state

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by joshuarrrr** [comment]
closed via #1949
