### ISSUE TITLE
[BUG] [D&D] Bad error message for Saving a Vis with an existing title

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#1918]
**Describe the bug**

Saving a Vis with a title that already exists causes the editor to throw an error that does not make sense to the user. The user should be told that a Vis with that title already exists. 

It also mentions that the Vis was saved but loading the saved Vis again uses the original saved object. This means that the message "Saved but no id returned" is also incorrect. 

![image](https://user-images.githubusercontent.com/20453492/179963231-dc154f11-24aa-44d7-82b4-c4244b5af700.png)

**To Reproduce**
1. Go to Wizard
2. Create a Vis
3. Save the vis with a title that already exists for another D&D Vis

**Expected behavior**
A clear error message highlighting what the issue is should be displayed. Ideally in the save modal itself.

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by joshuarrrr** [comment]
closed via #1950
