### ISSUE TITLE
[BUG] Enabling separate axis for a TSVB Time Series graph overrides Axis Scale setting in Panel Options

### ISSUE THREAD

**Issue by jimkaba** [opensearch-project/OpenSearch-Dashboards#1929]
**Describe the bug**
In a TSVB Time Series graph, if "separate axis" is set to "yes" in the Data :: Series :: Options tab control settings, the Y-axis scale will be forced to "Normal" even if the Panel Options :: Style "Axis Scale" control menu specifies "Log".

This effectively means that only Normal (linear) Y-Axis scaling can be used on the graph.  The Log scaling is not inherited, it is ignored and overridden.  There is no mechanism to specify Log scaling within the Data :: Series "" Options tab. 

**To Reproduce**
1. Create a simple TSVB Time Series graph of a data series that has a wide range of Y-axis values (e.g. between zero and millions)
2. Under the Panel Options tab, select "Log" for the "Axis Scale" setting.  This should force the Y-axis to use a log scale.
3. Under the Data tab, for a series being graphed, select the "Options" tab and set "Separate Axis" to "Yes"
5. The Y-axis scale of the graph will change from Log to Normal.

**Expected behavior**
The graph's Y-axis scale setting should keep whatever value is set by the Panel Options "Axis Scale" control parameter.  Simply enabling a separate graph axis should not override the global setting set under Panel Options.

**OpenSearch Version**
2.0.1; 2.1.0

**Dashboards Version**
2.0.1; 2.1.0

**Plugins**
Default

**Screenshots**
Log Axis Scaling working when "separate axis"=No
(Note -- Y-axis values are not being displayed due to an unrelated bug.)
![image](https://user-images.githubusercontent.com/109618264/180263108-e64787be-147d-4c2b-8fa4-ea96ec20e488.png)

Axis Scaling overridden (changed from Log to Normal) when "separate axis"=Yes
![image](https://user-images.githubusercontent.com/109618264/180263454-a9a0838d-09c6-448b-8b21-c3a3606f3c2e.png)

**Comment by joshuarrrr** [comment]
Thanks for the reproduction steps, I was able to confirm the bug.

**Comment by AMoo-Miki** [comment]
In my opinion, when choosing to display data on a separate axis, it would be beneficial to have the ability to customize the scale, similar to how we can adjust the minimum, maximum, and position of the axis.
