### ISSUE TITLE
[D&D] Provide link to experimental feature feedback forum/poll/issue

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#1962]
The experimental banner on Wizard currently links to a blank GitHub issue, but we could create a new GH template for experimental feature feedback.

Alternatively, because this is a user-facing link, it may be better to collect feedback in the forums or another tool that's more comfortable for non-technical users.

**Comment by joshuarrrr** [comment]
@kgcreative, it sounds like we first need to decide how and where we want to collect the feedback, and then we can update the link/copy/CTA. Will UX be providing, or should we ping someone else to provide?

**Comment by kavilla** [comment]
Closing, will re-visit for 2.3.
