### ISSUE TITLE
[MD] Support conditional rendering with global config

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/OpenSearch-Dashboards#1978]

**Comment by seraphjiang** [comment]
@noCharger

what's the proposed config item name, please provide this, so other component owner could mock in their code before feature is implemented?

**Comment by noCharger** [comment]
> @noCharger
> 
> 
> 
> what's the proposed config item name, please provide this, so other component owner could mock in their code before feature is implemented?

data_source.enabled

**Comment by seraphjiang** [comment]
we should have very simple switcher
e.g. 

datasource.enabled: false


1. this config should be readable from public plugin code at browser
```
  constructor(private readonly initializerContext: PluginInitializerContext) {
    this.config = this.initializerContext.config.get<ConfigType>();
  }
```

2. this config should be accessible from  Server plugin code

3. this config could be configure and set when dashboards launch
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2d6eef9679dcc225757873d50d40dccc8abeceea/test/common/config.js

4. this config should be configure via yml config file

**Comment by seraphjiang** [comment]
> data_source.enabled

@zengyan-amazon @zhongnansu @kristenTian @mpabba3003 @yibow98  @KrooshalUX @kgcreative 

here is the feature flag to enable/disable data source feature, would please review and comment if different opinion, otherwise we will go with it.

**Comment by noCharger** [comment]
>  we should have very simple switcher
> 
> e.g. 
> 
> 
> 
> datasource.enabled: false
> 
> 
> 
> 
> 
> 1. this config should be readable from public plugin code at browser
> 
> ```
> 
>   constructor(private readonly initializerContext: PluginInitializerContext) {
> 
>     this.config = this.initializerContext.config.get<ConfigType>();
> 
>   }
> 
> ```
> 
> 
> 
> 2. this config should be accessible from  Server plugin code
> 
> 
> 
> 3. this config could be configure and set when dashboards launch
> 
> https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2d6eef9679dcc225757873d50d40dccc8abeceea/test/common/config.js
> 
> 
> 
> 4. this config should be configure via yml config file
> 
> 
> 
> 

Aligned with all but the code block under 1 will not apply in our case since PluginConfigDescriptor interface and `exposeToBrowser` only supported for configs of same plugin

**Comment by seraphjiang** [comment]
> 



> > we should have very simple switcher
> > e.g.
> > datasource.enabled: false
> > 
> > 1. this config should be readable from public plugin code at browser
> > 
> > ```
> > 
> >   constructor(private readonly initializerContext: PluginInitializerContext) {
> > 
> >     this.config = this.initializerContext.config.get<ConfigType>();
> > 
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. this config should be accessible from  Server plugin code
> > 3. this config could be configure and set when dashboards launch
> > 
> > https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2d6eef9679dcc225757873d50d40dccc8abeceea/test/common/config.js
> > 
> > 4. this config should be configure via yml config file
> 
> Aligned with all but the code block under 1 will not apply in our case since PluginConfigDescriptor interface and `exposeToBrowser` only supported for configs of same plugin


good to know. let's cut feature request issue to track for long term solution

to unblock this, what's proposal?

have we consider introduce plugin level flag?

```
data_source.cm.ui.enabled: false
```

**Comment by zhongnansu** [comment]
There're 2 places we need conditional rendering.

1.  `Cred management plugin` and `DS management plugin`
2. `Index Pattern management` plugin, to conditionally render the "attach datasource" configuration step

I agree to have only 1 switch in the data source plugin, and have `Cred management plugin` and `DS management plugin` to depend on that.

```
{
  "id": "dataSourceManagement",
  "version": "opensearchDashboards",
  "server": false,
  "ui": true,
  "requiredPlugins": ["management", "dataSource"],
  "optionalPlugins": [],
  "requiredBundles": ["opensearchDashboardsReact"]
}

```

As for how to access the global switch value. There can be 2 ways.
1. A straightforward way is just to load the datasource plugin flag in yml, from `Cred management plugin` and `DS management plugin` setup stage. Haven't tried it yet, but I assume it should work
```
 this.initializerContext.config
      .create<DataSourceConfigType>()
      .pipe(first())
      .toPromise()
```
2. Another way is to expose the flag from `DataSourcePluginStart`, as a function. Caller plugin can just access it during plugin setup stage. Similar to how `indexManagementPlugin` depennds 
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/4dd7f142ad4c8845bc2dd40a3947f8eb6752e891/src/plugins/index_pattern_management/public/plugin.ts#L48-L50

**Comment by noCharger** [comment]
> There're 2 places we need conditional rendering.
> 
> 1. `Cred management plugin` and `DS management plugin`
> 2. `Index Pattern management` plugin, to conditionally render the "attach datasource" configuration step
> 
> I agree to have only 1 switch in the data source plugin, and have `Cred management plugin` and `DS management plugin` to depend on that.
> 
> ```
> {
>   "id": "dataSourceManagement",
>   "version": "opensearchDashboards",
>   "server": false,
>   "ui": true,
>   "requiredPlugins": ["management", "dataSource"],
>   "optionalPlugins": [],
>   "requiredBundles": ["opensearchDashboardsReact"]
> }
> ```
> 
> As for how to access the global switch value. There can be 2 ways.
> 
> 1. A straightforward way is just to load the datasource plugin flag in yml, from `Cred management plugin` and `DS management plugin` setup stage. Haven't tried it yet, but I assume it should work
> 
> ```
>  this.initializerContext.config
>       .create<DataSourceConfigType>()
>       .pipe(first())
>       .toPromise()
> ```
> 
> 2. Another way is to expose the flag from `DataSourcePluginStart`, as a function. Caller plugin can just access it during plugin setup stage. Similar to how `indexManagementPlugin` depends on data plugin
>    https://github.com/opensearch-project/OpenSearch-Dashboards/blob/4dd7f142ad4c8845bc2dd40a3947f8eb6752e891/src/plugins/index_pattern_management/public/plugin.ts#L48-L50
> 
> cc @seraphjiang @zengyan-amazon @noCharger

Thanks Zhongnan, there are some difference in detail, feel free to check my PR :P
