### ISSUE TITLE
Onboard non index-pattern based visualization types to multiple datasource

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/OpenSearch-Dashboards#1990]
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2004
- [ ]  #2153
  - [ ] Legacy call support
  - [ ] new client support 
- [ ] Onboard timeline visuzaliton to multi data source
- [ ] Onboard Vega visuzaliton to multi data source
- [ ] Onboard [Gantt chart](https://github.com/opensearch-project/dashboards-visualizations) to multi data source
  - [ ] Research https://github.com/opensearch-project/dashboards-visualizations/issues/119

related to https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2455

**Comment by seraphjiang** [comment]
this should be lower priority, target for 2.5 or 3.0

**Comment by kristenTian** [comment]
Yes, for 2.5 we are targeting more plugin integrations with multiple data source. Including TSVB and dev console(https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2699) -- This requires UX update on existing experience, users now should be able to navigate between data sources before perform existing supported operations. For example, for dev console, UX should specify which data source for user to invoke the API requests to.

**Comment by seraphjiang** [comment]
close as tracked in other campaign 

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5870 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6009
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6005
