### ISSUE TITLE
[D&D] Placeholder visualization selection menu

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#2011]
We didn't yet complete https://github.com/opensearch-project/OpenSearch-Dashboards/issues/954, because we only have one visualization type (metric) ready for the 2.2 experimental release. Instead, we should implement the selector as mocked there, but with other visualization types as inactive and some sort of "coming soon" message.

**Comment by joshuarrrr** [comment]
@btzeng can you provide updated guidance on the look and behavior of the selector for initial release?

**Comment by btzeng** [comment]
@joshuarrrr Thanks for reaching out. the design team is currently figuring out the goal of the test for the experimental release. If the strategy is to communicate there will be more "prioritized" chart types coming, I'll provide additional message and design mocks.

**Comment by kavilla** [comment]
@btzeng could we get a decision on this by today?
