### ISSUE TITLE
[MD] Optimize text content and layout with UX inputs

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/OpenSearch-Dashboards#2024]
- [ ] 1. the content for delete button confirmation box

Use case 1 - This is the screenshot of delete button confirmation box in editing credential page: 
<img width="800" alt="Screen Shot 2022-08-11 at 1 24 46 PM" src="https://user-images.githubusercontent.com/109543558/184236017-f45960b9-83b5-4285-a852-22fb6b04b2d8.png">

Use case 2 - This is the screenshot of listing page delete button from Saved Object section, just want to confirm the design for credential listing page delete button confirmation box. 
<img width="799" alt="Screen Shot 2022-08-11 at 1 30 03 PM" src="https://user-images.githubusercontent.com/109543558/184237051-2310ebc3-3d61-46bc-ab9b-0c16b7529af3.png">

- [x] 2. list page columns to expose, and respective column names [Done]
![image](https://user-images.githubusercontent.com/44716267/184237279-4a63d665-3998-47b3-a56f-a5a4ee19cb7c.png)
- [ ] 3. toast message for success and error

Questions:
1. Do we need a toast for create/edit succesfully? What's the text content for the toast?
2. Do we need a toast for create/edit failed? What's the context for the toast? Shall we expose item ID?

Context - Index pattern management page
![Screen Shot 2022-08-10 at 8 21 48 PM](https://user-images.githubusercontent.com/44716267/184235096-00aa9ea5-ec41-4a79-9631-4959510a0d3b.png)
Context - Inside Saved object management page
![Screen Shot 2022-08-10 at 8 21 52 PM](https://user-images.githubusercontent.com/44716267/184235144-bef0f2d3-186a-49e4-bd56-290e4dce3f1d.png)

- [ ] 4. Context of header 
See screen shots 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2051

- [ ] 5. Edit credential page

**Comment by kristenTian** [comment]
What is the error case for 3, and 4?
