### ISSUE TITLE
[BUG] Unable to install plugin on platform that is NOT LINUX

### ISSUE THREAD

**Issue by seraphjiang** [opensearch-project/OpenSearch-Dashboards#2026]
**Describe the bug**

Try to install plugin on my Mac environment, but got error

```
huanji@ea-osd % node scripts/opensearch_dashboards_plugin.js install kibana-ga-v0.1.0.tar.gz                                                                      
Plugins are only available for Linux
```

**Expected behavior**
Be able to install plugin on non-linux OS, MacOS, Windows 

**Dashboards Version**
2.x

**Plugins**
https://github.com/jmcarp/kibana-ga

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: MacOS

**Comment by joshuarrrr** [comment]
This is a feature request, not a bug - that appears to be the intended behavior of the script as per https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1316/files

**Comment by seraphjiang** [comment]
Thanks @joshuarrrr 
Could we know what's the motivation to introduce the constrains in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1316

**Comment by peterzhuamazon** [comment]
This is a hard blocker for windows as well.
https://github.com/kavilla/OpenSearch-Dashboards-1/blob/main/src/cli_plugin/install/settings.js#L48

**Comment by seraphjiang** [comment]
> This is a hard blocker for windows as well.
> https://github.com/kavilla/OpenSearch-Dashboards-1/blob/main/src/cli_plugin/install/settings.js#L48

@kavilla  do we any concern to remove the linux specific check to unblock windows distribution (also other OS)

**Comment by ruanyl** [comment]
I have the same issue on OSX, I was trying to trace the commit history and the original unit tests. But couldn't find a particular reason for why having the `platform` restriction on the plugin installation. 

I can see that `osd-opensearch` has a restriction on OpenSearch snapshot installation for a particular platform(Linux) which makes sense if OpenSearch snapshot artifacts are only available for Linux for now.

My question: should the same restriction be applied to dashboard plugins? or do plugins actually have different binaries for different platforms?

**Comment by peterzhuamazon** [comment]
@AMoo-Miki is working on fixing this as part of the windows support.
