### ISSUE TITLE
[BUG] Region Map Plug JS code

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#2039]
**Describe the bug**

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1718/files extending some functionality but the code was added in JS instead of TypeScript.

It new ups a legacy client, also, doesn't follow the casing format defined in the repo for example, `Opensearch` should be `OpenSearch`. Functions are not explicit too.

**To Reproduce**
Navigate to plugin, notice linter issues.

**Expected behavior**
Refactor to TypeScript and type it with current expectations of the repo for example: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/visualize/server/plugin.ts

**Comment by Flyingliuhub** [comment]
@kavilla discussed offline with @junqiu-lei , the owner of this change is @Shivamdhar.

**Comment by Flyingliuhub** [comment]
@Shivamdhar, Could you please take a look this issue and provides the fixes? Thanks

**Comment by Shivamdhar** [comment]
@Flyingliuhub sure. I'll take a look into it.
