### ISSUE TITLE
[Bug] Header component error on index pattern management page

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/OpenSearch-Dashboards#2048]
<img width="1788" alt="Screen Shot 2022-08-31 at 11 01 05 AM" src="https://user-images.githubusercontent.com/44716267/187749293-2fab20c4-3e4f-4f08-bb50-b19d3716940b.png">

Reproduce steps:

1. pull code from main branch
2. start OSD instance
3. click 'stack management' -> 'Index Patterns'
4. check inspect and the error pops up in console

**Comment by joshuarrrr** [comment]
@noCharger Thanks so much for opening this issue - I had also noticed it, and it is definitely an annoyance!
