### ISSUE TITLE
[MD] Fix breadcrumb

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/OpenSearch-Dashboards#2060]
![Screen Shot 2022-08-03 at 10 49 52 AM](https://user-images.githubusercontent.com/44716267/182675478-b873a8fa-4758-48cb-9671-4d14ec16caaf.png)

**Comment by seraphjiang** [comment]
screenshot show Saved Objects, should it be `Credentials`?

**Comment by noCharger** [comment]
> screenshot show Saved Objects, should it be `Credentials`?

Yes that what already been fixed #2069
