### ISSUE TITLE
[MD][IP] Add config data source step

### ISSUE THREAD

**Issue by kristenTian** [opensearch-project/OpenSearch-Dashboards#2064]

**Comment by kristenTian** [comment]
![image](https://user-images.githubusercontent.com/105667444/183158159-310321b6-691f-4cf4-97a8-e313ef050bf0.png)

**Comment by kristenTian** [comment]
Hi Kroosh, one more thing to consider in this part is that, we could also allow user to use local cluster as a data source. -- Right now the flow ask the user to use other clusters as data sources only.

**Comment by KrooshalUX** [comment]
@kristenTian  are you referring to the Figma mockup?

**Comment by KrooshalUX** [comment]
@kristenTian  Got it. To inform the designs, do we currently allow users to assign a name to the local cluster?

**Comment by kristenTian** [comment]
DataSource could be used as follows:

- Real default cluster -- just allow user to update name, not anything else.
- Use default OS as a data source, but with different credential (different OSD users when using security plugin) -- use as a datasource
