### ISSUE TITLE
[BUG] Docker image building fails

### ISSUE THREAD

**Issue by AMoo-Miki** [opensearch-project/OpenSearch-Dashboards#2093]
**Describe the bug**

The base OS image used for generating Docker images is [CentOS 8](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/d7004dc5b0392477fdd54ac66b29d231975a173b/src/dev/build/tasks/os_packages/docker_generator/run.ts#L54). CentOS 8 was [EOLed](https://www.centos.org/centos-linux-eol/) at the end of 2021 and the official mirrors were wiped. As a result, building docker images fails.

**To Reproduce**
1. Run `yarn build-platform --docker`
2. Notice failure message of `info Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist`

**Expected behavior**
Docker image to be successfully generated.

**Dashboards Version**
All

**Add any other context about the problem here.**
One workaround is to use vaulted packages by amending the [Dockerfile](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/8c11eff94240169a87288710d0c3acaea6fd24fc/src/dev/build/tasks/os_packages/docker_generator/templates/Dockerfile#L52) using
```
RUN cd /etc/yum.repos.d/
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
```

**Comment by peterzhuamazon** [comment]
In build repo we already swap any build related image that requires a RHEL 8 to RockyLinux 8.
There is also another flavor in Almalinux 8. Both are good alternatives to the CentOS8.

We as infra does not use this dashboards core docker image building file in any of our builds, as we have our own scripts in our repo to handle that.

**Comment by ashwin-pc** [comment]
@kavilla do you think this is a candidate for the `good-first-issue` label?

**Comment by kavilla** [comment]
I believe we can close this as a duplicate for this https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1601

**Comment by aoguan1990** [comment]
Close this Issue due to duplication.
