### ISSUE TITLE
[Proposal][DeAngular][table] table visualization re-write to get rid of angular

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#2139]
# Statement
Currently, table visualization is written in Angular. Angular is [not supported since 12/2021](https://blog.angular.io/discontinued-long-term-support-for-angularjs-cc066b82e65a) and cause [high severity CVE issues](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1558). Since we decided to remove angular from current code base, table visualization needs to be refactored ore re-written in ReAct. Meanwhile, our current table visualization is old and we see [new requests](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/705) from users to get it updated.

In this issue, I would like to first introduce the core features of the current table visualization. Then make some high-level proposals for the new table visualization. We will leave the implementation details in another [design issue](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2187).

# Current Table Visualization 

The table visualization is used to show data in a table format. It is bootstrapped when a table is rendered. 

### create a table visualization
* on home page, click the side bar menu and click `visualize`
* on the top right of the visualizations list, click `Create visualization`
* choose `Data Table` as the visualization type and then choose the index pattern
* a table visualization will be rendered based on the default settings
<img width="621" alt="Screen Shot 2022-08-23 at 11 12 59" src="https://user-images.githubusercontent.com/79961084/186267404-a2cf39c2-cb1c-4be5-b351-c9c67418f62d.png">

### access an existing table visualization
There are three ways to access the saved visualizations.
* the visualizations list
<img width="731" alt="Screen Shot 2022-08-23 at 14 19 28" src="https://user-images.githubusercontent.com/79961084/186268332-80559358-d0b8-49bb-b741-93d448684131.png">

* the saved object (`Stack Management` --> `Saved objects`)
<img width="895" alt="Screen Shot 2022-08-23 at 14 11 22" src="https://user-images.githubusercontent.com/79961084/186268403-19f35419-6a44-40f3-9295-fb07c785ef40.png">

* if the table vis is saved in a dashboard, you could also access it from there
<img width="1757" alt="Screen Shot 2022-08-23 at 14 13 01" src="https://user-images.githubusercontent.com/79961084/186268678-7705ccc9-8e8e-478d-b5e4-12a543ae7a71.png">

### sort the column (asc, desc)
Currently, there are only two ways to sort: asc and desc (see below image)
* click the black up-pointing triangle to do asc sort
* click the black down-pointing triangle to do desc sort

### pagination
* table has the pagination depending on how many data to show (see below image)
<img width="919" alt="Screen Shot 2022-08-14 at 18 54 15" src="https://user-images.githubusercontent.com/79961084/184735218-51844ed1-75bc-4918-9ebc-29b2294d2100.png">

### export table as csv
There are two options, `Raw` and `Formatted`
<img width="632" alt="Screen Shot 2022-08-15 at 16 00 25" src="https://user-images.githubusercontent.com/79961084/186254946-f404aaac-c0cf-4d52-8b7e-f073d2d619d9.png">

* click `Raw` to export the data table in csv
* click `Formatted` to export the data table in csv
* There is one column missing which is chosen from `options` --> `percentage column`. 

<img width="1552" alt="Screen Shot 2022-08-23 at 11 31 46" src="https://user-images.githubusercontent.com/79961084/186254869-5bd1a7f3-41c0-405d-b3d3-8e10e51ae5e2.png">

### split table in columns and rows

* table can be split. there are two options.
<img width="295" alt="Screen Shot 2022-08-14 at 18 55 06" src="https://user-images.githubusercontent.com/79961084/184734716-7da5f01e-8957-4d69-9125-ee0ad7c3b103.png">

* split table in `Rows`
<img width="1384" alt="Screen Shot 2022-08-14 at 18 56 18" src="https://user-images.githubusercontent.com/79961084/184734752-d4c59731-ddeb-4a7c-a811-746b816dd800.png">

* split table in `Columns`
<img width="1382" alt="Screen Shot 2022-08-14 at 18 55 58" src="https://user-images.githubusercontent.com/79961084/184734723-e0b3c99d-f8cd-43cc-8d67-cda1993f64cc.png">

### show total 
* click `options` --> `show total`. Then you will be able to select different metrics. 
<img width="531" alt="Screen Shot 2022-08-23 at 14 25 53" src="https://user-images.githubusercontent.com/79961084/186269345-b66b0feb-4200-4a95-9fb1-e54d558b9458.png">
see there is a calculated total at the bottom:
<img width="1697" alt="Screen Shot 2022-08-23 at 13 47 27" src="https://user-images.githubusercontent.com/79961084/186269668-e4fa8224-07bb-487d-8a3f-655df3852347.png">

### show partial rows
* click `options` --> `show partial rows`. This option will allow table visualization to show partial rows if there are many columns.

### show metrics for every bucket/level
<img width="1610" alt="Screen Shot 2022-08-23 at 13 59 12" src="https://user-images.githubusercontent.com/79961084/186264517-9e6fe1cd-a894-4d2d-aff7-c8e5127acb10.png">

### show percentage column
* click `options` -->  choose `Percentage column` and the metrics
* the default is `Don't show`
<img width="1580" alt="Screen Shot 2022-08-23 at 13 48 01" src="https://user-images.githubusercontent.com/79961084/186270715-0856351a-ffeb-4598-a0a5-f364024ff7c4.png">

# Proposal
The purpose to create a new table visualization is to remove Angular code and upgrade our table visualization. It should be easy to use with minimum learning curve. Therefore, I would like to propose minimal changes from usage perspective:

* use the same creation method
* keep all the three access ways
* keep all the current core features
* some improvements to consider:

(a) the black up-pointing/down-pointing triangle is not clear to me
<img width="1096" alt="Screen Shot 2022-08-23 at 14 44 26" src="https://user-images.githubusercontent.com/79961084/186272265-c031482e-4cf9-4222-83fc-4f20cf12c7e4.png">

(b) the column width is not adjustable. when there are a lot of columns, users don't have the choice to adjust the column.
<img width="1229" alt="Screen Shot 2022-08-23 at 14 52 55" src="https://user-images.githubusercontent.com/79961084/186273324-8e785cd4-4afd-4f6f-9fbc-8b05b8a96eef.png">

* [optional][new feature] pivot table: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/705

# Providing feedback
The purpose of this proposal is to introduce our current table visualization and our thoughts to enhance the usability. We would like to collect feedback from the community. This proposal is meant to cover the high-level proposal and functionality but does not go into implementation details and architecture. Once we get feedback from the community we will publish a more detailed design doc.

For any feedback on the problem statement, the proposal, or any open questions please leave your comments on this issue. Looking forward to your input!

**Comment by joshuarrrr** [comment]
@ananzh I bumped this to target the 2.5.0 release.

**Comment by ananzh** [comment]
Close it due to new table vis been merged into main.
