### ISSUE TITLE
[Plugin as Extension] Research in packages/osd-pm

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#2160]
[@osd/pm](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/packages/osd-pm) gets build and used by the build to set up the dependencies for the project.

Besides the README, there is not much insight underneath the hood for this package.

Requirements:
* Research and dive into the package and understanding it with the goal of how this package can be transformed to allow an extension to be built without being within the OpenSearch Dashboards project.
* Dev docs

**Comment by manasvinibs** [comment]
PR to developer doc site - https://github.com/CPTNB/opensearch-dashboards-dev-docs/pull/9
