### ISSUE TITLE
[Plugin as Extension] Research in packages/osd-optimizer

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#2161]
[@osd/optimizer](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/packages/osd-optimizer) optimizes the project when building.

Besides the README, there is not much insight underneath the hood for this package.

Requirements:
* Research and dive into the package and understanding it with the goal of how this package can be transformed to allow an extension to be built without being within the OpenSearch Dashboards project.
* Dev docs

**Comment by seanneumann** [comment]
Closing as we don't need it.
