### ISSUE TITLE
[BUG] [MD] Update credentials that attached to datasource doesn't give the correct client.

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/OpenSearch-Dashboards#2182]
**Describe the bug**

Update credentials that attached to datasource doesn't give the correct client.

**To Reproduce**
1. create 2 credentials. `cred-1`(right username/password) and `cred-2`(in-correct username/password)
2. create a data source `ds-1` attached to `cred-1`
3. create index-pattern `ip-1` that attached to `ds-1`
4. Use `Discover` to search on `ip-1`
5. Able to see data from the `ds-1`
6. update `ds-1` to use `cred-2`, and save
7. Use `Discover` to search on `ip-1`
8. Still seeing data from `ds-1`, which is not supposed to happen, because `cred-2` is not even a correct crendential for `ds-1`

**Expected behavior**

**Comment by zhongnansu** [comment]
Originally I was thinking this is because the way we implement data source pooling(the LRU cache), but after double check, there's nothing wrong with that. We are only caching the root client, which is always a Client with no-auth. And for each time it needs a client, we always retrieve credential and create a child client to return, and we don't cache this child client.
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/160664ab56d7f414fbc8ca4aac8dbdb913376b21/src/plugins/data_source/server/client/configure_client.ts#L128

After further looking into the issue. I found the issue is caused by the way we spawn child client with `auth` option. After first time we spawn a child of a root client with auth, it will be "locked". Afterwards, any `getBasicAuthClient` of the same endpoint won't overwrite the auth info of it.
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/160664ab56d7f414fbc8ca4aac8dbdb913376b21/src/plugins/data_source/server/client/configure_client.ts#L134-L143

**Comment by zengyan-amazon** [comment]
thanks for the investigation, let's implement the fix

**Comment by zhongnansu** [comment]
PR merged, resolving
