### ISSUE TITLE
Busy icon/progress bar on click of Refresh/Update button indicating the search operation in progress is missing on Kibana UI.

### ISSUE THREAD

**Issue by rakhinarveka1** [opensearch-project/OpenSearch-Dashboards#2183]
Description:
when user tries to search data on 'Discover' menu using search string and click on 'Refresh'/ 'Update' button, if data is not available in iframe then busy icon/progress bar is appearing. 
If data is already present of previous search, then busy icon is not displaying. however ideally if search is in progress, then it should show busy icon/progress bar  on every search if we are changing timeframe or search string.

**To Reproduce**
1. Go to Kibana UI Discover Menu
2. Click on 'Update/Refresh' button
3. while Search is in progress in background , busy icon is missing if Iframe already has the data of previous search.

**Expected behavior**
Busy icon/progress bar  should appear when search is in progress in background.

**Dashboards Version**
1.X

**Screenshots**

![image](https://user-images.githubusercontent.com/111862494/186124440-f8966c9f-1150-4678-ad2d-605888230aca.png)
![image](https://user-images.githubusercontent.com/111862494/186124487-712db2ac-9541-46f5-9ec6-eee9709b2cbd.png)
![image](https://user-images.githubusercontent.com/111862494/186124527-cbe74afe-7762-4674-80ee-4a56f6bdc932.png)
![image](https://user-images.githubusercontent.com/111862494/186124578-154d80e6-3f58-483e-b185-551ada403803.png)

From above 2 screens it shown that number of hits are changing but busy icon is missing while second search is awaiting or in progress.

**Host/Environment (please complete the following information):**
 - OS: Windows 10
 - browser: Google chrome, Version 104.0.5112.102 (Official Build) (64-bit)

**Comment by zhongnansu** [comment]
@rakhinarveka1 could you check if this is still the issue with Opensearch Dashboards? Thx

**Comment by joshuarrrr** [comment]
@rakhinarveka1 I believe this has been fixed - see recording below, which was made using [the OpenSearch Dashboards playground](https://playground.opensearch.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d,to:now))&_a=(columns:!(_index,currency,category),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ff959d40-b880-11e8-a6d9-e546fe2bba5f,key:category.keyword,negate:!f,params:(query:'Men!'s%20Clothing'),type:phrase),query:(match_phrase:(category.keyword:'Men!'s%20Clothing')))),index:ff959d40-b880-11e8-a6d9-e546fe2bba5f,interval:auto,query:(language:kuery,query:''),sort:!())).

Note that on any action the OpenSearch logo in the top left of the navigation bar is replaced with a loading icon.

https://user-images.githubusercontent.com/1679762/222577554-89149d81-da01-4037-93e7-80ce14e45e6f.mov

I believe that this loading indicator was improved and added in version 2.1.0, via https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1586.

If I've misunderstood the bug or request, feel free to re-open with more details.
