### ISSUE TITLE
[Proposal] Automate versioning, releasing and changelog generating with Changesets

### ISSUE THREAD

**Issue by ruanyl** [opensearch-project/OpenSearch-Dashboards#2189]
Seeing people been discussing **automated release** in different contexts, I'd like to propose a possible solution.

Related issues https://github.com/opensearch-project/OpenSearch-Dashboards/issues/591 https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1741 https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1801

## What's Changesets?
> Changesets is a tool to manage versioning and changelogs with a focus on multi-package repositories

More details about Changesets can be found here: [link to Changesets](https://github.com/changesets/changesets)

## Why Changesets?

1. Fully automated version bump in `package.json` for packages, no manual work needed, version get bump based on SemVer
2. Release with automatic tagging and `changelogs` generating. By following Changesets workflow, all PRs need to be properly "documented" which ensures all changes are recorded in the changelogs when making a new release.
3. Changesets PR workflow will bring a better community engagement experience with Changesets [github bot](https://github.com/changesets/bot).
4. **Changesets encourage PR author to put details of the changes for each PR**
> The best time to capture this information is when submitting a PR (when it is fresh in your mind), not when you eventually go to batch and release these changes.

I noticed people are also discussing 4 digit version in dashboard plugin projects while Changesets works with SemVer, but still, I'd love to raise the topic for discussion 😃 (I might miss some key points as I lack a full picture of the project)

**Comment by prudhvigodithi** [comment]
Hey @ruanyl thanks for starting the discussion.

For dashboard plugins I see we have version increment done for more than one file (not only just the package.json files), example https://github.com/opensearch-project/security-dashboards-plugin/pull/1005/files, as part of the version increment process we should be able to handle them.
Also we have an extra digit along with SemVer example [2.0.0.0](https://github.com/prudhvigodithi/dashboards-visualizations/blob/main/gantt-chart/opensearch_dashboards.json#L3-L4), (more discussion to add extra number to semVer https://github.com/semver/semver/issues/340), I will do some more reading about Changeset if it can handle the version increment with this extra number.

@bbarani @dblock @seanneumann @kavilla

**Comment by ruanyl** [comment]
Thanks @prudhvigodithi for the comment! Yes, I noticed the usage of 4 digit version, this could be challenge with Changeset as it expects SemVer, I'm not sure how easy to customize it via plugin, need to double check that.

Unlike release process which can be pretty much standardized, the version increment in other files can be different in different projects, a generic release automation tool probably should not handle this, I feel these can be done via scripts/templates as part of the release.

**Comment by dblock** [comment]
Are there any concerns of introducing this set of tools into a non-JS toolset like in OpenSearch? Will developers have to do anything more?

**Comment by joshuarrrr** [comment]
@ruanyl Thanks for all the suggestions about Changesets. Many of those ideas have been incorporated into the adopted proposal: https://github.com/opensearch-project/.github/issues/156
