### ISSUE TITLE
[BUG] Tenant keeps switching to Global

### ISSUE THREAD

**Issue by sshock** [opensearch-project/OpenSearch-Dashboards#2200]
**Describe the bug**

Throughout the day, maybe once an hour, while using OpenSearch Dashboards it will randomly switch me from the custom tenant I am on to the Global tenant.

**To Reproduce**
1. Switch to a custom tenant.
2. Click around to view different dashboards, maybe do refresh, or simply leave your browser open to a dashboard with auto-refresh enabled.

**Expected behavior**
It should stay on the tenant I have selected.

**Actual behavior**
It switches back to the Global tenant after a while.

**OpenSearch Version**
1.3.2

**Dashboards Version**
1.3.2

**Host/Environment:**
 - OS: macOS
 - Browser and version: Chrome 104.0.5112.101

**Additional context**

My suspicion is that the session is expiring and I am getting logged out.  I am told that sessions last 1 hour and I am being auto logged out and back in.

Even if that is what is happening, I expect it to be able to remember which tenant I am on.

**Comment by joshuarrrr** [comment]
@sshock Thanks for filing the bug - re-routing to the security plugin repo.

**Comment by joshuarrrr** [comment]
Issue moved to [opensearch-project/security-dashboards-plugin #1084](https://github.com/opensearch-project/security-dashboards-plugin/issues/1084) via [**ZenHub**](https://www.zenhub.com/)
