### ISSUE TITLE
[D&D] Research on how plugins create and store reference objects

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#2205]
Requirements: 
* Research on how other plugins are creating reference object and how are they being stored
* What are the relationships among KibanaSavedObject, search source and reference object
* For https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1878, explore the option to skip the steps and create reference object directly
* Document findings here

**Comment by joshuarrrr** [comment]
Great list! While we can start by documenting the findings here, we'll also want to make sure they're saved somewhere under version control (as a README or other tutorial) so they're discoverable.
