### ISSUE TITLE
[BUG] Maps show error

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#221]
**Describe the bug**
Calls to get map data errors out. While navigating to any page that makes a call to get map data it sends a request to a non-existent service. This is because the original URL for the service was replaced while the fork was undergoing renaming. This was expected bug to occur but will need to be fixed.

**To Reproduce**
1. Load sample data
2. Go to dashboards
3. Go to a map widget

**Expected behavior**
Successful response to an existing service and it shows map data.

**OpenSearch Version**
`n/a`

**Dashboards Version**
`1.x` `main`

**Plugins**
`n/a`

**Screenshots**

![Screen Shot 2021-03-23 at 9 47 44 AM](https://user-images.githubusercontent.com/12060704/112185675-b2379900-8bbd-11eb-9f53-b7f3c21e95c0.png)

**Host/Environment (please complete the following information):**
 - OS: Ubuntu
 - Browser and version [e.g. 22]; Firefox 78.7.0esr 

**Additional context**

Need to discuss with the community about what map service to use.

**Comment by mihirsoni** [comment]
In order to solve this problem, there are multiple approach :
* We provide guide to host user's own mapping server 
* Work with Amazon internal to see if OpenSource Dashboards can leverage the existing Tiles / Maps service.

CC: @nknize

**Comment by kavilla** [comment]
Currently, if you pull `main`, it will fail out of the box. But you can get the app to work if you add the following to the [config/opensearch_dashboards.yml](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/config/opensearch_dashboards.yml):

```
map.tilemap.url: "https://tiles.maps.search-services.aws.a2z.com/tiles/{z}/{x}/{y}.png"
map.includeOpenSearchMapsService: false
```

**Comment by kavilla** [comment]
Will be sending a PR to make a new maps client that extends the current map client.
