### ISSUE TITLE
Add a table vis for the sample data

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#2211]
Currently, we don't have any table vis for any sample data. 
<img width="779" alt="Screen Shot 2022-08-26 at 14 38 28" src="https://user-images.githubusercontent.com/79961084/186994405-de526053-2983-4e42-9848-788c39930ab0.png">

To reproduce:
1) add sample data 
2) go to `Visualization` from the side menu
3) search `Data Table` to verify

Since we will start to build [a new table vis](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2187), it would be nice to have a table vis for the sample data to compare.

**Comment by joshuarrrr** [comment]
Completed via https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4581 - the Visual Consistency Dashboard contains at least one example of every supported visualization type.
