### ISSUE TITLE
[BUG] Auto-complete menu of Dev Tools is missing `_index_template` and perhaps others

### ISSUE THREAD

**Issue by AMoo-Miki** [opensearch-project/OpenSearch-Dashboards#2219]
Just like `_cat`, `_template` and many others appear when keying in, `_index_template` should appear in the list as well.

**To Reproduce**
1. Go to Dev Tools
2. Key in `_template`
4. Notice that `_index_template` isn't in the auto-complete list

**Expected behavior**
`_index_template` in the list

**OpenSearch Version**
1.3

**Dashboards Version**
1.3

**Additional context**

It is possible that other specs are missing as well.

**Comment by kristenTian** [comment]
https://cptnb.github.io/opensearch-dashboards-dev-docs/source/readmes/packages/osd-spec-to-console/
https://cptnb.github.io/opensearch-dashboards-dev-docs/source/readmes/src/plugins/data/#autocomplete

yarn spec_to_console
yarn run v1.22.19
$ node scripts/spec_to_console
Expected input
error Command failed with exit code 1.

**Comment by joshuarrrr** [comment]
Resolved via #2226
