### ISSUE TITLE
[BUG] OSD Optimizer understanding and update limits

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#2224]
`node scripts/build_opensearch_dashboards_platform_plugins.js --update-limits`

generates a lot of changes in the [limits.yml](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/packages/osd-optimizer/limits.yml), why and what is this doing?

**Comment by kristenTian** [comment]
checking how pageLoadAssetSize is been used, the command will even change for the existing folders.

**Comment by kristenTian** [comment]
--update-limits  will run a build and rewrite the limits file to include the current bundle sizes +5kb

Base on updateBundleLimits, it will compare the pageLoadAssetSize in the limit.yaml file vs the metrics file size. If the configured size is less than the real size, it will increase the pageLoadAssetSize by 15000.

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/4c3f2229efb7bde806b31da64b89906fc71befc2/packages/osd-optimizer/src/limits.ts#L93

The metric size mentioned above to be compared with is got by getting the file size of the directory of `target/public` . Note that, this only apply to the UI plugin.

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/d7004dc5b0392477fdd54ac66b29d231975a173b/packages/osd-optimizer/src/optimizer/get_plugin_bundles.ts#L52

OpenSearch Dashboards Platform plugins with `"ui": true` in their `opensearch_dashboards.json` file will have their `public/index.ts` file (and all of its dependencies) bundled into the `target/public` directory of the plugin. The build output does not need to be updated when other plugins are updated and is included in the distributable without requiring that we ship `@osd/optimizer`

**Comment by kristenTian** [comment]
Closing the issue after synced up with Abby offline, feel free to reopen it if there are new action items.
