### ISSUE TITLE
[Plugins] Get Anomaly Detection plugin working with OpenSearch Dashboards

### ISSUE THREAD

**Issue by boktorbb-amzn** [opensearch-project/OpenSearch-Dashboards#224]
- [x] Get the Anomaly detection plugin building and working with OpenSearch Dashboards
- [ ] Write documentation of process for use by external plugin teams

**Comment by mihirsoni** [comment]
@ananzh Is this issue still WIP or we can mark it as closed ?

**Comment by ananzh** [comment]
Issues solved. All plugins can be built and run on Dashboards.
