### ISSUE TITLE
[Feature Proposal] Across-tenant Saved Object Aggregation View

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/OpenSearch-Dashboards#2249]
**Is your feature request related to a problem? Please describe.**

Today, in OpenSearch-Dashboards with Multi-tenancy enabled, user can only see the saved objects that are created in the selected tenant. When user wants to see a list of saved object across all tenants that they have permissions to, there is no way for that. 
![Screen Shot 2022-08-29 at 3 54 46 PM](https://user-images.githubusercontent.com/16925774/187312832-64ba4314-8f81-4459-bfe4-1f87ea1be3a5.png)

**Describe the solution you'd like**

- The view shows all saved objects across tenants that the user has permissions to 
- The new column(`Tenant`) shows in which tenant the saved object is created

![Screen Shot 2022-08-31 at 11 13 02 PM](https://user-images.githubusercontent.com/16925774/187844362-fb0e2c54-0fac-4ada-ae0d-d08e7ffda2a8.png)

**Additional context**

This is the first milestone of [the new Dashboard object sharing experience](https://github.com/opensearch-project/security/issues/1869). More interesting features/milestones are coming to make the new sharing experience happen.

**Comment by joshuarrrr** [comment]
@cliu123 Is there a reason you're proposing this here, rather than in https://github.com/opensearch-project/security?

**Comment by aoguan1990** [comment]
@cliu123 This is an awesome feature to improve user experience. But I am very curious about the following design details: which tenant is associated with aggregation view? As we need to call tenant api to capture the current Tenant, if user want to check the aggregation view, which tenant should users switch to? Do we by default populate the tenant that owns the aggregation view?

**Comment by kavilla** [comment]
@cliu123 is this in 2.4? should we migrate this to security dashboards repo?

**Comment by cliu123** [comment]
@kavilla @joshuarrrr good call!
@opensearch-project/transfer-request Please transfer this to security-dashboards-plugin. Thanks!
