### ISSUE TITLE
Unable to start opensearch-dashboards service

### ISSUE THREAD

**Issue by zakirpcs** [opensearch-project/OpenSearch-Dashboards#2254]
I build customized rpm of opensearch & opensearch-dashboads now i am facing to start opensearch-dashboard service using systemd script.

I am getting below error message during service startup.

opensearch-dashboards[533384]:     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
opensearch-dashboards[533384]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
opensearch-dashboards[533384]:     at internal/main/run_main_module.js:17:47 {
opensearch-dashboards[533384]:   code: 'MODULE_NOT_FOUND',
opensearch-dashboards[533384]:   requireStack: []
opensearch-dashboards[533384]: }
systemd[1]: opensearch-dashboards.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: opensearch-dashboards.service: Failed with result 'exit-code'.
-- Subject: Unit failed

How can i resolved this issue. Can anyone help me on this or is it possible to share spec file with me so that i can customized the rpm as per my requirements.

Regards,
Zakir

**Comment by kavilla** [comment]
Hello @zakirpcs!

Thanks for opening, do you mind telling me how you are running the build? So you forked OpenSearch Dashboards and then run the build script and attempting to run the artifact outputted? Or did you download the official release?

Also, which plugins are you running and what operating system are you running on?

Thank you!

**Comment by zakirpcs** [comment]
Hello @kavilla  

Thanks for your reply.


I build the rpm using official tarball file. And I am trying to run this rpm on AlmaLinux 8.4 environment which is clone of Red Hat 8. 

No special plugin I am using.  I just try to run  the service by using default plugins.

Thank You.

**Comment by joshuarrrr** [comment]
This may be a documentation issue - @AMoo-Miki will investigate.

**Comment by joshuarrrr** [comment]
@zakirpcs Can you provide the commands you ran?

**Comment by zakirpcs** [comment]
@joshuarrrr 

I am using below command to run the service.

systemctl status opensearch-dashboards


cat /usr/lib/systemd/system/opensearch-dashboards.service
```
# SPDX-License-Identifier: Apache-2.0
#
# The OpenSearch Contributors require contributions made to
# this file be licensed under the Apache-2.0 license or a
# compatible open source license.

# Description:
# Default opensearch-dashboards.service file

[Unit]
Description="OpenSearch Dashboards"

[Service]
Type=simple
User=opensearch-dashboards
Group=opensearch-dashboards
# Load env vars from /etc/default/ and /etc/sysconfig/ if they exist.
# Prefixing the path with '-' makes it try to load, but if the file doesn't
# exist, it continues onward.
EnvironmentFile=-/etc/default/opensearch-dashboards
EnvironmentFile=-/etc/sysconfig/opensearch-dashboards
ExecStart=/usr/share/opensearch-dashboards/bin/opensearch-dashboards
Restart=always
WorkingDirectory=/usr/share/opensearch-dashboards

[Install]
WantedBy=multi-user.target
```

**Comment by zakirpcs** [comment]
If I change opensearch-dashboards.service file as follows then service run without any issue.

[Unit]
Description="OpenSearch Dashboards"

```
[Service]
Type=simple
User=root
Group=root

EnvironmentFile=-/etc/default/opensearch-dashboards
EnvironmentFile=-/etc/sysconfig/opensearch-dashboards
ExecStart=/usr/share/opensearch-dashboards/bin/opensearch-dashboards "-c /etc/opensearch-dashboards/opensearch_dashboards.yml" --allow-root
Restart=always
WorkingDirectory=/usr/share/opensearch-dashboards

[Install]
WantedBy=multi-user.target
```

So its look like chroot mode issue to me.

**Comment by AMoo-Miki** [comment]
I have a feeling that your `opensearch-dashboards` user does not have access to read the node modules or it really cannot find them. Below is my entire process of running OpenSearch Dashboards as a service; you might find it helpful in resolving your issue.

To setup the env for OpenSearch Dashboards:
* I create the user:
  ```
  sudo adduser --system --shell /bin/bash -U --no-create-home opensearch
  ```
* create some folders
  ```
  mkdir -p /opensearch-dashboards/2.4.0 /opt/nvm
  ```
* fetch https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/2.4.0/opensearch-dashboards-2.4.0-linux-x64.tar.gz and unzip into `/opensearch-dashboards/2.4.0`
* set permissions
  ```
  sudo chown -R opensearch:opensearch /opensearch-dashboards
  sudo chmod -R g+w /opensearch-dashboards
  ```
* install nvm, node, and yarn
  ```
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | NVM_DIR="/opt/nvm" bash
  nvm install 14.20.0
  npm i -g yarn
  sudo chown -R opensearch:opensearch /opt/nvm
  ```
* give Node.js some privileges:
  ```
  sudo setcap cap_net_bind_service=+ep /opt/nvm/versions/node/v14.20.0/bin/node
  ```

This the service file I use:
```
[Unit]
Description=OpenSearch-Dashboards-2.4.0
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
RuntimeDirectory=opensearch-dashboards

WorkingDirectory=/opensearch-dashboards/2.4.0
ExecStart=/opensearch-dashboards/2.4.0/bin/opensearch-dashboards
Restart=always

User=opensearch
Group=opensearch
StandardOutput=journal

[Install]
WantedBy=multi-user.target
```

My service picks the config file from its default location, `/opensearch-dashboards/2.4.0/config`.
