### ISSUE TITLE
[BUG] 'admin' can't see Security tab in GUI

### ISSUE THREAD

**Issue by pragmatic3** [opensearch-project/OpenSearch-Dashboards#2275]
**Describe the bug**

The 'admin' user cannot see the security plugin listed under the 'OpenSearch Plugins' list in the GUI.

**To Reproduce**
1. Go to 'triple bar drop down menu'
2. Look under 'OpenSearch Plugins'
3. Note that Security is not listed

**Expected behavior**
Expected to see Security listed to be able to manage user, roles, etc.

**OpenSearch Version**
Please list the version of OpenSearch being used.
opensearch-2.2.1-1.x86_64

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.
opensearch-dashboards-2.2.1-1.x86_64

**Plugins**
Please list all plugins currently enabled.
alertingDashboards@2.2.1.0
anomalyDetectionDashboards@2.2.1.0
customImportMapDashboards@2.2.1.0
ganttChartDashboards@2.2.1.0
indexManagementDashboards@2.2.1.0
notificationsDashboards@2.2.1.0
observabilityDashboards@2.2.1.0
queryWorkbenchDashboards@2.2.1.0
reportsDashboards@2.2.1.0
securityDashboards@2.2.1.0

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: RHEL 8.6
 - Browser and version [e.g. 22]  Chrome 105.0.5195.102 on Win 10

**Additional context**

**Comment by joshuarrrr** [comment]
Issue moved to [opensearch-project/security-dashboards-plugin #1092](https://github.com/opensearch-project/security-dashboards-plugin/issues/1092) via [**Zenhub**](https://www.zenhub.com/)

**Comment by peternied** [comment]
@pragmatic3 Please create a request in the support forums to get help with this issue, https://discuss.opendistrocommunity.dev/
