### ISSUE TITLE
Create build artifacts

### ISSUE THREAD

**Issue by boktorbb-amzn** [opensearch-project/OpenSearch-Dashboards#230]
As of now There are no tested build artifacts, this issue ensures we have all the artifacts and cleaned build pipeline.

- [x] Use official NodeJS website for downloading the artifacts
- [x] Remove `-no-oss` flag from the build tool
- [x] Remove `-oss` flag from the build tool
- [x] Ensure we produce only oss distribution
- [x] Tar
  - [x] windows
  - [x] OSX
  - [x] Linux
- [x] Docker
- [x] OS Distribution
  - [x] Deb
  - [x] RPM

**Comment by mihirsoni** [comment]
This has been partially generated locally, I'll keep this issue open until we have automated process to generate all the artifacts.

**Comment by galangel** [comment]
Hi, Any update on the Docker part?

**Comment by kavilla** [comment]
Hi @galangel, we got a little busy. Will bring this up in our sync up to see if have more details.

**Comment by kavilla** [comment]
The code base can generate all these items, and we are in discussions just to have the code generate the artifacts but the ownership of the automation still needs to be resolved.

**Comment by kavilla** [comment]
There is a CI for building the artifacts, but should be improved upon. Will keep this issue open and target 1.1.0 for improvements related to automation.

**Comment by tmarkley** [comment]
The original issue here is resolved. Follow-ups for automation are in the build repo: https://github.com/opensearch-project/opensearch-build/issues
