### ISSUE TITLE
Add this repo to the manifest for the next developer iteration

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/OpenSearch-Dashboards#2308]

**Comment by kavilla** [comment]
You can close this one. The issue that open is created across the project but for OpenSearch and OpenSearch Dashboards there is a cron job that automatically does this for us.

**Comment by noCharger** [comment]
> You can close this one. The issue that open is created across the project but for OpenSearch and OpenSearch Dashboards there is a cron job that automatically does this for us.

Sure. Will update that auto PR to the main issue after its done.
