### ISSUE TITLE
Breaking changes and migration 

### ISSUE THREAD

**Issue by boktorbb-amzn** [opensearch-project/OpenSearch-Dashboards#231]
This issue is to track all the breaking changes after rename exercise.

**Comment by kavilla** [comment]
Most, if not all, saved objects had the property `kibanaSavedObjectMeta` within the rename we changed this to `opensearchDashboardsSavedObjectMeta`. Which has prevented objects from being imported.

**Comment by kavilla** [comment]
The default index changed from `.kibana` to `.opensearch_dashboards`

**Comment by mihirsoni** [comment]
Url redirections from `/kibana` to `opensearch_dashboards`

**Comment by kavilla** [comment]
Will close this one and will address the issue in this issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/334
