### ISSUE TITLE
Write unit tests for restricted endpoints and upstream communication

### ISSUE THREAD

**Issue by boktorbb** [opensearch-project/OpenSearch-Dashboards#232]
We need unit tests that make sure that no PRs or code is trying to hit the elastic telemetry endpoints such as `/api/ui_metric/report` or other telemetry endpoints

We also need unit tests that fail if `opensearch_dashboards.json` manifest files exist for plugins we have disabled such as Newsfeed and Telemetry Management Section

**Comment by ananzh** [comment]
I think we can ignore the unit test for now. Currently the response to fetch elastic telemetry endpoints such as `/api/ui_metric/report` are disabled. 

```
const response = await fetch.post('/api/ui_metric/report', {
        body: JSON.stringify({ report }),
      });
```

**Comment by tmarkley** [comment]
@boktorbb-amzn can you add more info to this Issue?

**Comment by ananzh** [comment]
@boktorbb-amzn My bad. You are right. There is no unit test. I think what I mean here is that we don't need write unit test now and can close this issue this the functions are currently disabled. Or we could save the issue to remind us to add unit test later.

**Comment by wbeckler** [comment]
given we've lived for 2 years without this in place and there have been no implications, I propose we close this.
