### ISSUE TITLE
[Remote Store] Feature Feedback

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch-Dashboards#2337]
A meta issue to consolidate all the feedback for the new experimental feature - Remote Store option for improved durability.

Documentation - https://opensearch.org/docs/latest/opensearch/remote/
Feature Proposal - https://github.com/opensearch-project/OpenSearch/issues/1968
Design Proposal - https://github.com/opensearch-project/OpenSearch/issues/2700
Tasks that are part of 2.3 release - https://github.com/opensearch-project/OpenSearch/issues/3974
Backlog - https://github.com/opensearch-project/OpenSearch/issues/2992

**Comment by kavilla** [comment]
Hello @sachinpkale, do you have some insight for this? I don't have much information for this experimental feature.

**Comment by sachinpkale** [comment]
Hi @kavilla , adding some resource information in the description of the issue.

**Comment by joshuarrrr** [comment]
It appears this issue would make more sense in the https://github.com/opensearch-project/OpenSearch repo, as it doesn't seem to be a dashboards feature.

**Comment by sachinpkale** [comment]
Yes, this should be in `OpenSearch` repo. Thanks @joshuarrrr . Created an issue here: https://github.com/opensearch-project/OpenSearch/issues/4576
Closing this one.
