### ISSUE TITLE
[BUG] package contains legacy information

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/OpenSearch-Dashboards#234]
**Describe the bug**

`package.json` contains legacy information.

 -  `"homepage": "https://www.opensearch.co/products/kibana",` - this URL will not exist. 
 - `build` points to a number and sha hash that are probably not valid any longer.

It's questionable to have the `author` field still pointing to someone not involved with the fork - I'll leave this call to someone else.

**Comment by mihirsoni** [comment]
@stockholmux I've updated both information #238
