### ISSUE TITLE
[Table Visualization] Table viz to export table as CSV and split table

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#2379]
* split table vis under row and col directions (PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2578)
* format column data to show date and percentage (PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2562)
* export table vis as raw and formatted csv
* restore showTotal feature (PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2562)
* restore percentage column feature (PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2562)

**Comment by ananzh** [comment]
all the sub-issues have targeted PRs in review
close this issue
