### ISSUE TITLE
[VizBuilder] Increase test coverage

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#2380]
Parent task to fill in the gaps from the low initial coverage that the VisBuilder has.

## Sub tasks:

- [x] Add unit tests to functional code where it makes sense
- [x] Investigate and document functional testing flow to see if they can be made easier to write and debug
- [x] Add missing functional test workflows
- [x] Add Vis Builder FTR tests to OpenSearch Dashboards Repo (set the appropriate env flag)

## Missing unit tests

- [x] `src/plugins/wizard/public/application/utils/get_top_nav_config.tsx`
- [x] `src/plugins/wizard/public/application/utils/validate_schema_state.ts`
- [x] `src/plugins/wizard/public/application/components/data_tab/utils/get_available_fields.ts`

## Missing functional tests

- [ ] Save workflow
- [x] View on dashboards
- [x] Edit from dashboards
- [x] Create from dashboards: 
- [x] Edit from Visualization listing
- [x] Metric tests
- [x] Bar chart tests
- [x] Line chart tests
- [x] Area Chart tests
- [x] Drag and Drop test
- [x] Change datasource

**Comment by kavilla** [comment]
[Follow-up]: Negative code coverage? Maybe we should have a rule if negative code coverage point to new functional tests.

[Follow-up 2]: Is there another way to calculate coverage accurately from a functional tests view point.

**Comment by joshuarrrr** [comment]
See also:
- https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1884
- https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1885

**Comment by ashwin-pc** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2458 
         https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2460

**Comment by ashwin-pc** [comment]
Save workflow is blocked by https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2627#issuecomment-1292841626. Will track adding a test workflow as a part of that separately. Closing this issue in the meantime.
