### ISSUE TITLE
[Feedback] Multiple Datasources

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#2400]
OpenSearch Dashboards provides tools to help you visualize and explore your data. Multiple datasources project allows for the connection to an OpenSearch cluster endpoint

**Comment by kavilla** [comment]
Data sources page reference legacy application

**Comment by abbyhu2000** [comment]
maybe consider adding a readme doc to explain how to use the multiple datasource plugin and its functionalities?

**Comment by kavilla** [comment]
Unsure of the verification behind adding a data source connection. Still verifying. I am able to add a duplicate datasource will see the impact of this.

**Comment by kavilla** [comment]
`This will delete data source connections(s) and all Index Patterns using this credential will be invalid for access.`

` connections(s) `

**Comment by kavilla** [comment]
![Screen Shot 2022-09-21 at 3 15 05 PM](https://user-images.githubusercontent.com/12060704/191620042-db0a61c1-8183-440a-8067-01a7308fce6d.png)

I believe this not the standard from OpenSearch's for modal that can delete something. @KrooshalUX

**Comment by kavilla** [comment]
Sample data is able to add duplicate index patterns, should there be an indication on the index pattern page which source the index pattern is from?

**Comment by kavilla** [comment]
Information how my plugin can extend this functionality

**Comment by kavilla** [comment]
⚠️ for validation again, it does not do any validation on the version of the data source. currently we are coupled tightly with the version of OpenSearch. But it could get data from a data source that is really old or really new version with document's or APIs changes that we have yet to implement in the current version.

**Comment by kavilla** [comment]
⚠️ If MD is enabled, how did we want to handle if any outage on the other data sources? What is the experience? It seems like it will start since it will just check the default data source but visualizations associated to that index pattern from the data source should fail to load. Do we indicate that the data source is experiencing an outage?

**Comment by kavilla** [comment]
Batching concurrent requests fails

**Comment by ananzh** [comment]
> Maybe consider adding a readme doc to explain how to use the multiple datasource plugin and its functionalities?

Yes, I agree with @abbyhu2000. I have trouble to set it up as a developer. A developer guide / readme would be better with 1) setup in opensearch_dashboards.yml 2) instructions and example to create a data source 3) provide some sample endpoint_url

<img width="462" alt="Screen Shot 2022-09-21 at 15 57 42" src="https://user-images.githubusercontent.com/79961084/191624755-5ba6990e-5a3f-424c-8f84-4b0713563e18.png">

**Comment by ananzh** [comment]
I see the column sorting can do the sort on the lowercase named data source correctly. But if there is capital letter named data source or symbol started named data source, it is not working properly. Is there any restrictions on how to name the data source? is this some expected behavior?

<img width="1000" alt="Screen Shot 2022-09-21 at 15 53 23" src="https://user-images.githubusercontent.com/79961084/191624997-a41a58df-78fa-4328-84c6-dd12fc281acf.png">
<img width="988" alt="Screen Shot 2022-09-21 at 15 53 32" src="https://user-images.githubusercontent.com/79961084/191625003-9d634cae-fd9f-4961-a2df-75ab5983ca6a.png">

**Comment by ananzh** [comment]
Same with description sorting. not sure whether this is expected. seems if cx doesn't pay attention to lowercase/uppercase, then cx might not be able to find the correct data source immediately. If this is expected, we need to notice cx in the user guide.

<img width="984" alt="Screen Shot 2022-09-21 at 16 04 25" src="https://user-images.githubusercontent.com/79961084/191625485-8b67f076-8390-44af-b985-1a8cfc574c67.png">
<img width="948" alt="Screen Shot 2022-09-21 at 16 04 36" src="https://user-images.githubusercontent.com/79961084/191625487-4d698c19-583c-4092-bf84-7bf1d418a29d.png">

**Comment by zhongnansu** [comment]
> Maybe consider adding a readme doc to explain how to use the multiple datasource plugin and its functionalities?

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2199

**Comment by ananzh** [comment]
I am reading this test:

```
    * Using the search bar, type the search criteria to find something that matches only 1 items in the table (search for title)
    * Validate that table displays only one row
    * Using the search bar, type the search criteria to find something that matches only 1 items in the table (search by description)
    * Validate that table displays only one row
```

but it seems we are allowing same data source (title, description, endpoint url and Authentication method) to be created
<img width="902" alt="Screen Shot 2022-09-21 at 16 11 17" src="https://user-images.githubusercontent.com/79961084/191626299-0d9222b3-2697-4870-8d06-e09ad25bbffe.png">

is this expected? from the test description, it seems not.

**Comment by zhongnansu** [comment]
> Batching concurrent requests fails

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2174

**Comment by abbyhu2000** [comment]
When i try to update password, there is no indication on if i successfully updated the password or not. 

1. If i provide a wrong password for `Old password`, there is no error shown and it still allows me to click the `update `button. (I think it's helpful to have some messages like "Please provide a correct old password", and `update` button should not be allowed)
2. If i provide a correct password for `Old password`, there is no message to indicate that I successfully updated the password. And it seems like the password is not actually updated(when i try to switch to a password with shorter length, but the number of * shown on the UI does not change)

**Comment by ananzh** [comment]
When I try to create an index pattern with system index. It is not showing properly. 

1) search `.kiban` --> can see all the indices
<img width="1205" alt="Screen Shot 2022-09-21 at 16 36 15" src="https://user-images.githubusercontent.com/79961084/191628262-3a4f1a2d-8990-4cf5-949a-c3ae4e548418.png">

**2) search `.kibana` --> show only one. should this match all indices starting with `.kibana`?**
<img width="1208" alt="Screen Shot 2022-09-21 at 16 36 24" src="https://user-images.githubusercontent.com/79961084/191628354-83149af8-c937-4f91-ba64-7db1aa08e665.png">

then if you add `_` it starts to show again
<img width="1193" alt="Screen Shot 2022-09-21 at 16 36 33" src="https://user-images.githubusercontent.com/79961084/191628442-fe67f3e2-7b88-4e9f-a4e6-4ae96b0db55b.png">

**Comment by ananzh** [comment]
should me remove alias?
<img width="1198" alt="Screen Shot 2022-09-21 at 16 46 44" src="https://user-images.githubusercontent.com/79961084/191629400-6a71cf86-84e8-4278-8a38-df7a31483490.png">

**Comment by noCharger** [comment]
> Maybe consider adding a readme doc to explain how to use the multiple datasource plugin and its functionalities?



> > Maybe consider adding a readme doc to explain how to use the multiple datasource plugin and its functionalities?
> 
> #2199

Will prioritize this

**Comment by abbyhu2000** [comment]
After I created a new index pattern from an external data source, the `View single document` is broken. 

![Screen Shot 2022-09-22 at 9 11 02 AM](https://user-images.githubusercontent.com/43937633/191798220-5f91c953-b665-4272-91e4-f0800b4bb474.png)
![Screen Shot 2022-09-22 at 9 11 14 AM](https://user-images.githubusercontent.com/43937633/191798261-5efd7ffa-5565-44c7-b086-e09e47ffc741.png)

`View single document` should work as below(this is the index pattern using the default data source)
![Screen Shot 2022-09-22 at 9 12 38 AM](https://user-images.githubusercontent.com/43937633/191798553-21349bac-317d-4863-874d-6424572d0e9c.png)

**Comment by kavilla** [comment]
Explicit message indicating that this is an experimental feature for example like the visualization builder:

![Screen Shot 2022-09-23 at 12 05 19 PM](https://user-images.githubusercontent.com/12060704/192039540-0b5a259c-4ed6-42ed-b220-edacfea4a38f.png)

**Comment by KrooshalUX** [comment]
Moving a conversation from Slack into GitHub: There are still pending UX changes and copy edits to be made. I will work with @kristenTian, @mpabba3003 and others to help address those feedback items.

**Comment by bjo004** [comment]
> > Maybe consider adding a readme doc to explain how to use the multiple datasource plugin and its functionalities?
> 
> Yes, I agree with @abbyhu2000. I have trouble to set it up as a developer. A developer guide / readme would be better with 1) setup in opensearch_dashboards.yml 2) instructions and example to create a data source 3) provide some sample endpoint_url
> 
> <img alt="Screen Shot 2022-09-21 at 15 57 42" width="462" src="https://user-images.githubusercontent.com/79961084/191624755-5ba6990e-5a3f-424c-8f84-4b0713563e18.png">

Hi @ananzh , 

Should I assume it's the opensearch URL that will look like this https://<OPENSEARCH_URL>.com:9200 

Kind regards,

Bankole.

**Comment by zhongnansu** [comment]
> ⚠️ for validation again, it does not do any validation on the version of the data source. currently we are coupled tightly with the version of OpenSearch. But it could get data from a data source that is really old or really new version with document's or APIs changes that we have yet to implement in the current version.

Team decides it's not a release blocking issue, added to the roadmap of 2.5, #2435

**Comment by mpabba3003** [comment]
> I see the column sorting can do the sort on the lowercase named data source correctly. But if there is capital letter named data source or symbol started named data source, it is not working properly. Is there any restrictions on how to name the data source? is this some expected behavior?
> 
> <img alt="Screen Shot 2022-09-21 at 15 53 23" width="1000" src="https://user-images.githubusercontent.com/79961084/191624997-a41a58df-78fa-4328-84c6-dd12fc281acf.png">
> 
> <img alt="Screen Shot 2022-09-21 at 15 53 32" width="988" src="https://user-images.githubusercontent.com/79961084/191625003-9d634cae-fd9f-4961-a2df-75ab5983ca6a.png">

This is default sorting by EUI library InMemoryTable.

**Comment by zhongnansu** [comment]
> Data sources page reference legacy application

I didn't get this one, do you have a screenshot? Is it about documentation links on the page? @kavilla

**Comment by zhongnansu** [comment]
> Information how my plugin can extend this functionality, ie would be cool to add this feature to the console plugin.


> 

#2437 #2436

**Comment by mpabba3003** [comment]
> When i try to update password, there is no indication on if i successfully updated the password or not.
> 
> 1. If i provide a wrong password for `Old password`, there is no error shown and it still allows me to click the `update `button. The pop up is then closed and return to the previous page. It gives an illusion that the password is successfully updated with a wrong `Old Password`. (I think it's helpful to have some messages like "Please provide a correct old password", and `update` button should not be allowed)
> 2. If i provide a correct password for `Old password`, there is no message to indicate that I successfully updated the password.
>    ![Screen Shot 2022-09-21 at 4 36 33 PM](https://user-images.githubusercontent.com/43937633/191628165-188f98b8-7dfc-46d7-859e-340e06ad8a53.png)

This is still under work. As of now nothing happens when user tries to update password

**Comment by zhongnansu** [comment]
> 

#2411

**Comment by zhongnansu** [comment]
> Unsure of the verification behind adding a data source connection. Still verifying. I am able to add a duplicate datasource will see the impact of this.
> 
> EDIT: By adding a duplicate data source it doesn't impact the viz's for the original data source. Experience is on par with deleting index pattern (all associated viz and dashboards remain but fail to work because they can't find index pattern)


#2411

**Comment by zhongnansu** [comment]
> Information how my plugin can extend this functionality, ie would be cool to add this feature to the console plugin.

It's on the roadmap. To support Legacy client in ds is paving the road for external plugin integration. I'll create an issue for tracking

**Comment by zhongnansu** [comment]
> Batching concurrent requests fails

#2174 tracking here

**Comment by zhongnansu** [comment]
> When I try to create an index pattern with system index. It is not showing properly.
> 
> 1. search `.kiban` --> can see all the indices
> 
> <img alt="Screen Shot 2022-09-21 at 16 36 15" width="1205" src="https://user-images.githubusercontent.com/79961084/191628262-3a4f1a2d-8990-4cf5-949a-c3ae4e548418.png">
> 
> **2) search `.kibana` --> show only one. should this match all indices starting with `.kibana`?** <img alt="Screen Shot 2022-09-21 at 16 36 24" width="1208" src="https://user-images.githubusercontent.com/79961084/191628354-83149af8-c937-4f91-ba64-7db1aa08e665.png">
> 
> then if you add `_` it starts to show again <img alt="Screen Shot 2022-09-21 at 16 36 33" width="1193" src="https://user-images.githubusercontent.com/79961084/191628442-fe67f3e2-7b88-4e9f-a4e6-4ae96b0db55b.png">

@ananzh this issue has nothing to do with data source. It's the default index pattern behaviour. Please submit as a separate issue in repo to get more discussion

**Comment by zhongnansu** [comment]
> After I created a new index pattern from an external data source, the `View single document` is broken.
> 
> ![Screen Shot 2022-09-22 at 9 11 02 AM](https://user-images.githubusercontent.com/43937633/191798220-5f91c953-b665-4272-91e4-f0800b4bb474.png) ![Screen Shot 2022-09-22 at 9 11 14 AM](https://user-images.githubusercontent.com/43937633/191798261-5efd7ffa-5565-44c7-b086-e09e47ffc741.png)
> 
> `View single document` should work as below(this is the index pattern using the default data source): ![Screen Shot 2022-09-22 at 9 12 38 AM](https://user-images.githubusercontent.com/43937633/191798553-21349bac-317d-4863-874d-6424572d0e9c.png)

fixed in #https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2431

**Comment by zhongnansu** [comment]
> should me remove alias? <img alt="Screen Shot 2022-09-21 at 16 46 44" width="1198" src="https://user-images.githubusercontent.com/79961084/191629400-6a71cf86-84e8-4278-8a38-df7a31483490.png">

same thing, it's not related to our code change. Default index pattern behavior

**Comment by zhongnansu** [comment]
@abbyhu2000 we have #2489 to track the password issue
