### ISSUE TITLE
Enabling the drag&drop wizard breaks OS dash[BUG]

### ISSUE THREAD

**Issue by SbJornS** [opensearch-project/OpenSearch-Dashboards#2406]
**Describe the bug**

When enabling the wizard in the yaml pr https://opensearch.org/docs/latest/dashboards/drag-drop-wizard/, OS dash fails to load with the following error message:
````
Something went wrong

Try refreshing the page. If that doesn't work, go back to the previous page or clear your session data.
Definition of plugin "wizard" not found and may have failed to load.

Version: 2.3.0
Build: 4104
Error: Definition of plugin "wizard" not found and may have failed to load.
read@https://site.tld/4104/bundles/core/core.entry.js:15:639824
_callee3$@https://site.tld/4104/bundles/core/core.entry.js:15:644536
tryCatch@https://site.tld/4104/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:2:2179
wrap/generator._invoke</<@https://site.tld/4104/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:2:1810
defineIteratorMethods/</<@https://site.tld/4104/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:2:2954
plugin_asyncGeneratorStep@https://site.tld/4104/bundles/core/core.entry.js:15:640279
_next@https://site.tld/4104/bundles/core/core.entry.js:15:640621
plugin_asyncToGenerator/</<@https://site.tld/4104/bundles/core/core.entry.js:15:640765
plugin_asyncToGenerator/<@https://site.tld/4104/bundles/core/core.entry.js:15:640508
createPluginInstance@https://site.tld/4104/bundles/core/core.entry.js:15:645102
_callee$@https://site.tld/4104/bundles/core/core.entry.js:15:642907
tryCatch@https://site.tld/4104/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:2:2179
wrap/generator._invoke</<@https://site.tld/4104/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:2:1810
defineIteratorMethods/</<@https://site.tld/4104/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:2:2954
plugin_asyncGeneratorStep@https://site.tld/4104/bundles/core/core.entry.js:15:640279
_next@https://site.tld/4104/bundles/core/core.entry.js:15:640621
plugin_asyncToGenerator/</<@https://site.tld/4104/bundles/core/core.entry.js:15:640765
plugin_asyncToGenerator/<@https://site.tld/4104/bundles/core/core.entry.js:15:640508
setup@https://site.tld/4104/bundles/core/core.entry.js:15:643183
_callee$@https://site.tld/4104/bundles/core/core.entry.js:15:654028
l@https://site.tld/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:389:405043
u/o._invoke</<@https://site.tld/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:389:404797
b/</<@https://site.tld/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:389:405406
plugins_service_asyncGeneratorStep@https://site.tld/4104/bundles/core/core.entry.js:15:648025
_next@https://site.tld/4104/bundles/core/core.entry.js:15:648385
````

**To Reproduce**
1. Add "wizard.enabled: true" to opensearch_dashboards.yml
2. restart service
3. refresh website

**Expected behavior**
Site should reload and give me the wizard

**OpenSearch Version**
2.3

**Dashboards Version**
2.3

**Plugins**
opensearch-alerting
opensearch-anomaly-detection
opensearch-asynchronous-search
opensearch-cross-cluster-replication
opensearch-geospatial
opensearch-index-management
opensearch-job-scheduler
opensearch-knn
opensearch-ml
opensearch-notifications
opensearch-notifications-core
opensearch-observability
opensearch-performance-analyzer
opensearch-reports-scheduler
opensearch-security
opensearch-sql

**Screenshots**
![image](https://user-images.githubusercontent.com/114183317/191825797-9c6b9f85-3c6c-4514-bb09-6b180b9bf19e.png)

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS
 - Browser and version Firefox 105, Chrome 105.0.5195.52 (Official Build) (64-bit)

**Additional context**
Just upgraded from 2.1 and wanted to enable drag&drop visualizations

**Comment by kavilla** [comment]
Hey @SbJornS,

Thanks for opening, can you press the `Clear your session` button and see if this resolves your issue? Or did you select that already.

**Comment by SbJornS** [comment]
This is very strange: I did (re)try that several times in multiple browsers last night to no avail. My colleague couldn't get logged in with wizard enabled or disabled with the attached error message. 
![image](https://user-images.githubusercontent.com/114183317/191915496-88fd26a9-1657-4e18-a6c4-2f463d745981.png)

My colleague was able of getting the rest api to work with curl: "if I take a valid CF_Authorization cookie (allowing me to get through the CF firewall) and create a GET request using standard auth with my username and password, then I can access https://some.tld/api/v1/restapiinfo via cURL".

When I re-enabled the wizard this morning to verify the issue before reporting back, it worked without issue (???). I suspect this might be related to these two issues reported in elastic, but it's hard to say for sure as it's already resolved itself. Per my colleagues info about bypassing CF proxy, the issue might be with it caching static resources and them not getting updated with new versions?
https://github.com/elastic/kibana/issues/130226
https://github.com/elastic/kibana/issues/132535

**Comment by kavilla** [comment]
@SbJornS,

Thanks for getting back! Yeah, I have experienced this a couple times with the caching busting mechanism not working as expected. Perhaps, we could repurpose this issue to take the time to revisit that.
