### ISSUE TITLE
Missing API Compatibility with Beats

### ISSUE THREAD

**Issue by anubisg1** [opensearch-project/OpenSearch-Dashboards#2417]
When using external tools (like beats) to import dashboards into OpenSearch Dashboards, import fail because the API returns the actual dashboards version

```
2022-09-26T16:06:50.034Z        ERROR   instance/beat.go:971    Exiting: Error importing Kibana dashboards: Kibana API is not available in Kibana version 2.3.0
Exiting: Error importing Kibana dashboards: Kibana API is not available in Kibana version 2.3.0
```

OpenSearch itself provides a compatibility mode with

```
PUT _cluster/settings
{
  "persistent": {
    "compatibility": {
      "override_main_response_version": true
    }
  }
}
```

there isn't (or i haven't found any documentation about it) a comparable feature for OpenSearch Dashboards

**Comment by zhongnansu** [comment]
This is a duplicate issue with #656, we have provided workaround [here](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/656#issuecomment-898575767)
