### ISSUE TITLE
[MD] Identify the source for duplicate index patterns

### ISSUE THREAD

**Issue by mpabba3003** [opensearch-project/OpenSearch-Dashboards#2442]
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2400#issuecomment-1254289458

**Comment by zhongnansu** [comment]
https://github.com/opensearch-project/ux/issues/38

**Comment by noCharger** [comment]
@mpabba3003  is this done since https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2521 merged?

**Comment by kristenTian** [comment]
Create a new index pattarn, then install the sample data to defualt.
