### ISSUE TITLE
[VisBuilder] [BUG] Empty workspace animation does not work in firefox

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#2443]
**Describe the bug**

The visbuilder animation in firefox does not work. 

**To Reproduce**
1. Go to [Visualization Builder](https://playground.opensearch.org/app/wizard) on firefox
4. See no animation

<img width="1904" alt="Screen Shot 2022-09-28 at 2 34 56 PM" src="https://user-images.githubusercontent.com/20453492/192893024-c27066ed-0209-4f83-9a1e-64332aacdff0.png">

**Expected behavior**
There should be an animated hand

**OpenSearch Version**
2.3

**Dashboards Version**
2.3

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by lashewi** [comment]
Hi @ashwin-pc , can I work on this?

**Comment by ashwin-pc** [comment]
Sure! Let me know if you need any help with this

**Comment by ashwin-pc** [comment]
Hey @lashewi! Just checking in to see how you are doing with the issue.

**Comment by raintygao** [comment]
If this issue has not been dealt with, I will try to have a look on it
