### ISSUE TITLE
[MD] Onboard other plugins to multiple data source feature

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/OpenSearch-Dashboards#2455]
Not planned for 2.4 releases

Since we have support both legacy clients new clients, that paved the road to onboard both other plugins and external plugins (such as Alerting, AD, reporting, etc)
For example dev tools, ghant chart(external plugin)

- [x] research on dev tools, ghant chart as example
~~- [ ] provide documentation~~
- [ ] #2699

**Comment by joshuarrrr** [comment]
@zhongnansu I know #2699 is in scope for 2.7.0 GA. What about the rest of this issue (docs)?

**Comment by zhongnansu** [comment]
> @zhongnansu I know #2699 is in scope for 2.7.0 GA. What about the rest of this issue (docs)?

I'll remove it. We can ignore doc for now. It's just me putting random ideas. As plugin can be implemented in different way. Hard to have a plan that works for everyone. MD only provides one API for callers to get client, and it's documented already in the first launch.
