### ISSUE TITLE
[VisBuilder] Functional: create wizard directly on dashboard, save and return to the dashboard

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#2458]
Write function tests for these scenarios:
1. select a dashboard, and create a new wizard
2. make sure `Add To Dashboard after saving` toggle is on
3. type a title and select `Save and return` button 
4. should automatically navigate to the dashboard page, and the created wizard should be shown on the dashboard
5. click `save` on the dashboard 

<img width="1048" alt="Screen Shot 2022-09-29 at 3 52 02 PM" src="https://user-images.githubusercontent.com/43937633/193155985-0f1adb1e-2c07-468d-812c-01cf9494b3f0.png">

**Comment by ashwin-pc** [comment]
https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/340
