### ISSUE TITLE
[Docs] Update functional testing instructions 

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#2462]
[opensearch-dashboards-functional-test](https://github.com/opensearch-project/opensearch-dashboards-functional-test) is the official home for  OpenSearch Dashboards Functional tests. Since the migration of all the tasks is non trivial, the decision was to incrementally target the migration. To communicate this openly we should update the [TESTING.md](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/TESTING.md) readme with clear instructions on migration plan and steps to write the new tests.

Migration plan:
- New functional tests will be written in [opensearch-dashboards-functional-test](https://github.com/opensearch-project/opensearch-dashboards-functional-test)
- If any change that affects the existing test in any meaningful way, the test will be migrated to the functional test repo
- All other tests will be ...

**Comment by tianleh** [comment]
For "All other tests will be", currently there is no concrete plan for it. The team could gradually build the development velocity by migrating a few tests first. We also welcome the community to help.

We have some high level proposal to automate test generation https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/205 which could extend to automate migration test cases from Selenium to Cypress. This may require some research.

cc @kavilla @seraphjiang @seanneumann

**Comment by ashwin-pc** [comment]
Created #2491 to collect feedback and track the migration plan.
