### ISSUE TITLE
[BUG]: Visualization height panel issue for all charts

### ISSUE THREAD

**Issue by Koustubh5585** [opensearch-project/OpenSearch-Dashboards#2493]
**Describe the bug**

Height of the chart panel and height of the chart is mismatched. Chart is taking full height of page instead of chart panel height with vertical scroll bar. (attached screenshot for more clarity)

**To Reproduce**
1. Go to visualization of any chart
2. Observe the height of the chart panel (grey color) and height of the chart 
3. Scroll down to see full chart
4. Open inspect window and resize the chart
5. Observe chart gets resized as per chart panel 

**Expected behavior**
Chart to be displayed in chart panel all the time and there should not be scroll bar

**Screenshots**
Observed:
![image](https://user-images.githubusercontent.com/42600229/193841568-b0cc5a05-7f91-4c57-8ca7-3f6fcd22f74d.png)

Expected
![image](https://user-images.githubusercontent.com/42600229/193842039-92037e5d-ed04-4bdd-9b8b-bea5a2fff381.png)

**Comment by CPTNB** [comment]
I see this is in the Observability plugin--are you experiencing this in any other plugins?  Also, what viewport size are you using to get that vertical scrollbar?  I'm noticing lots of the elements on such a small viewport don't render ideally.

**Comment by Koustubh5585** [comment]
@CPTNB This issue only observed in Observability plugin. We have a solution of this issue .
- Thank you

**Comment by Koustubh5585** [comment]
Closing this issue as fix for this issue is merged
