### ISSUE TITLE
[MD] Support Refresh for data source

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/OpenSearch-Dashboards#2494]
The data source management portal could include a refresh button, similar to the one for saved objects.

![Screen Shot 2022-10-04 at 10 26 04 AM](https://user-images.githubusercontent.com/44716267/193885993-95cc6cf4-905f-4dc9-873a-8aa16136c8a1.png)

![Screen Shot 2022-10-04 at 10 25 51 AM](https://user-images.githubusercontent.com/44716267/193885957-95ed3159-b762-4f2e-b8dc-1adf4d7597e2.png)

**Comment by zhongnansu** [comment]
This request doesn't make sense to me. Data source listing page shouldn't be align with saved object listing page. Saved objects includes, index pattern, visualizations, dashboards. If you checked the existing UI/UX for all of those. Data source is aligned with them. Re-open the issue if needed.
@noCharger 
cc: @KrooshalUX
