### ISSUE TITLE
[CHORE] Leftover X Pack references

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#2517]
**Description**

There are still some x-pack references in the code that need to be removed. 

- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data/README.md?plain=1#L114
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/packages/osd-pm/src/utils/validate_dependencies.ts#L178
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/server/saved_objects/migrations/core/index_migrator.test.ts#L145
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/server/saved_objects/migrations/core/index_migrator.test.ts#L168
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/server/saved_objects/migrations/core/opensearch_index.ts#L314
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/dev/notice/cli.js#L83
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/apm_oss/server/tutorial/instructions/apm_server_instructions.ts#L39

Credits: @AMoo-Miki 

**To Reproduce**
1. Go to the link
2. See the X Pack reference

**Expected behavior**
We should not have any X Pack references in the code

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by vimalMK** [comment]
Can I do the clean up?

**Comment by kavilla** [comment]
@vimalMK feel free to work on it! Let us know if you need any help on it!

**Comment by vimalMK** [comment]
@kavilla Thank you! I have a question before PR. In the last link(file)

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/apm_oss/server/tutorial/instructions/apm_server_instructions.ts#L39

Shall I remove the whole default message and keep in empty or do you want to add something else.

**Comment by vimalMK** [comment]
Please find the PR #2638
