### ISSUE TITLE
[BUG] Suggestion list cutoff

### ISSUE THREAD

**Issue by xonvanetta** [opensearch-project/OpenSearch-Dashboards#2555]
**Describe the bug**
Suggestion list in discovery is cutoff after 250px width

**To Reproduce**
1. Search some log text i.e `message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis, libero nec dictum scelerisque, ligula tortor tempus turpis, eget semper erat ante eget dolor. Nullam."` 
2. Suggestion box wont show the full text

**Expected behavior**
Should show about the width of the bar in some way

**OpenSearch Version**
1.3.5

**Dashboards Version**
1.3.6

**Plugins**
```
opensearch-alerting
opensearch-anomaly-detection
opensearch-asynchronous-search
opensearch-cross-cluster-replication
opensearch-index-management
opensearch-job-scheduler
opensearch-knn
opensearch-ml
opensearch-observability
opensearch-performance-analyzer
opensearch-reports-scheduler
opensearch-security
opensearch-sql
```
**Screenshots**

![image](https://user-images.githubusercontent.com/11271952/195291136-bf9246ab-e64f-402e-bdf3-e9d40e580902.png)

**Host/Environment (please complete the following information):**
 - Opensearch is containerized using `opensearchproject/opensearch-dashboards:1.3.6`
 - My host. Arch `Linux Hostname 5.15.72-1-lts #1 SMP Wed, 05 Oct 2022 12:15:15 +0000 x86_64 GNU/Linux`
 - Chrome Version 106.0.5249.103 (Official Build) (64-bit) And Firefox 105.0.2 (64-bit)
 
 **Additional context**
Unmarking [this](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/6c13abeac3e3f9ac4567a9f01e1af910eaad26f4/src/plugins/data/public/ui/typeahead/_suggestion.scss#L147) in the console makes the suggestion list full length but i don't think this is the solution

**Comment by ananzh** [comment]
We could provide a short-term fix for the bug. But for the suggestion list cutoff behavior, we definitely need more feedbacks from the community.
