### ISSUE TITLE
Enabling livereload or hotload feature in opensearch-dashboard project

### ISSUE THREAD

**Issue by JoeAtOpenSearch** [opensearch-project/OpenSearch-Dashboards#2564]
**Is your feature request related to a problem? Please describe.**
No

I’m working on ISM plugin and find it annoying to reload page while making some changes to FE code. Can we add a new option when start the webpack server to enable the livereload and hotload feature, which will help to improve the efficiency alot

**Describe the solution you'd like**
Use yarn start --hotload --live-reload to enable both features.

Dashboard and other plugins will leverage the dev-friendly feature.

**Describe alternatives you've considered**

**Additional context**

**Comment by ananzh** [comment]
I think we need to understand what we want to implement here: hotload or live-reload or both.
what are the benefits and what are the implement plans.
need some community help.

**Comment by ashwin-pc** [comment]
The difference is outlined well here: https://stackoverflow.com/a/41429055

This is also a duplicate of #679. Marking it as such and adding these details to the original issue

**Comment by ashwin-pc** [comment]
The difference is outlined well here: https://stackoverflow.com/a/41429055

This is also a duplicate of #679. Marking it as such and adding these details to the original issue
