### ISSUE TITLE
[MD] Allow create index patterns for indices with same name but from different datasources.

### ISSUE THREAD

**Issue by kristenTian** [opensearch-project/OpenSearch-Dashboards#2597]
I cannot create an index pattern with an existing name (I should be able to do so, since the data source should be part of the unique ID to disambiguate)

**Comment by kristenTian** [comment]
Pending tasks:
- The UI validation needs update
- Save Object listing page
- Visualization creation /Discover page

Done:
-  index pattern DS column support

**Comment by kristenTian** [comment]
Need to append data source in front of index pattern, pending UX input on:

- Save Object listing page support
- Visualization creation
- Discover page support

**Comment by zhongnansu** [comment]
@kristenTian is this still on track for 2.5

**Comment by kristenTian** [comment]
UX is still pending for this task. we can work on it if there is bandwidth.

**Comment by zhongnansu** [comment]
> Still pending confirming on the UX look for this task. we can work on it if there is bandwidth.
> 
> Base on Kevin and Kroosh, should just be simply pre-append the data source in front of data source everywhere.

I am working on this task to allow index-pattern created with same name but different datasources, and there will be some UX/UI changes needed across OSD components where they interact with index patterns. We propose prepending `datasource name` to `index pattern name` to distinguish them from UI. E.g. we could display 2 index pattern as `datasource-1.index-pattern-name-1` and `datasource-2.index-pattern-name-1`. See screenshots below for details.

Based on the previous comment. I'd like to confirm with @kgcreative @KrooshalUX, that we are align on this before I start implementation. 


References
1. saved Object listing page: 
![image](https://user-images.githubusercontent.com/32652829/222013761-58fe68c5-f812-488a-85dd-cd31cb8fc613.png)
2. visualization creation page: 
![image](https://user-images.githubusercontent.com/32652829/222013866-40bcb6e3-5288-481b-b024-98683f1a0d4e.png)
3. Discover Page: 
![image](https://user-images.githubusercontent.com/32652829/222014107-674690d0-fdc2-4bdb-b907-58cb5f5f4b52.png)

cc: @zengyan-amazon @seraphjiang @kristenTian

**Comment by zhongnansu** [comment]
> @zhongnansu Will this be resolved by #3604?

@joshuarrrr yes
