### ISSUE TITLE
Prepend `<datasource-name>.` to index pattern name to differentiate across data sources

### ISSUE THREAD

**Issue by kristenTian** [opensearch-project/OpenSearch-Dashboards#2599]
In Discover, Prepend datasource. to the index pattern name to help users differentiate between data sources

**Comment by zhongnansu** [comment]
does it mean when we create a index pattern with data source ,and we want to name is "ds-1". After creation, what actually saved in the index is with name field `datasource.ds-1`?

**Comment by kristenTian** [comment]
I don't think so, it should be a UI tweak in Discover app, after the UX review meeting, let's decide which phase this feature is needed.

**Comment by ashwin-pc** [comment]
@kristenTian Is MD not transparent to the applications? Will each plugin need to be modified to support MD?

**Comment by kristenTian** [comment]
Synced offline. In short, for plugin leveraging data plugin search client will be transparent.

**Comment by zhongnansu** [comment]
@kristenTian is this still on track for 2.5?

**Comment by kavilla** [comment]
Will this be enough? Or did we want to maybe to try some A/B testing to verify if this will help our users differentiate?

**Comment by kristenTian** [comment]
This is the related task: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2597#issuecomment-1306306976. 

Basically the following components are involved:
- Save Object listing page support
- Visualization creation
- Discover page support

This can definitely be helpful to users when there are duplicated index pattern names.

**Comment by joshuarrrr** [comment]
@kristenTian Assigning to you, as it appears you have the parent task assigned.

**Comment by joshuarrrr** [comment]
bumped release target to `2.6.0`.

**Comment by zhongnansu** [comment]
closing this to avoid confusion, as there's another issue #3604 opened to track the same issue
