### ISSUE TITLE
[Documentation] release process

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#2604]
How as a community member release a feature. If I want to target a specific date. How do I get this reviewed and accepted? How do I know if it's safe? How do I know if my feature experimental? What about feature branching? Can I demo my stuff ahead of time?

**Comment by joshuarrrr** [comment]
Triage: we can list out what are the expected release-able tasks (including test coverage scope, test-automation, feature review, code-review window). Feature-releases should be somewhat separate from a library release. Can also provide guidelines for semver/backport.

**Comment by seanneumann** [comment]
Do we need to update the release md for this?

**Comment by seanneumann** [comment]
Let's get https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2533 reviewed this sprint and updated if necessary. @noCharger
