### ISSUE TITLE
[BUG] Be able to use OUI and EUI

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#2605]
We currently alias OUI components to EUI to be non-breaking for developers. But new dev should be implemented in OUI if possible.  However the project fails to work when using OUI namespacing.

We should be able to use OUI and EUI within OpenSearch Dashboards.

**Comment by joshuarrrr** [comment]
The PR that aliases it https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2080

other aliasing links:
https://github.com/opensearch-project/oui/commit/9abf87e5c5ffcf970d0b45c5fa7db0ea8f7c18df

https://github.com/opensearch-project/oui/commit/2504b430a853b0f93bdc5ce42621fbf3dce176a3

**Comment by manasvinibs** [comment]
@AMoo-Miki @kaddy645 @kavilla  Discussion notes: This is not a bug. OUI will be used exclusively in 3.x and we should not be using it along with EUI in 2.x as it will break backporting and plugins compatibility.

**Comment by AMoo-Miki** [comment]
We should NOT be using or be able to use the OUI namespacing in OSD 2.x.
