### ISSUE TITLE
[MD] Datasource listing page delete button refactor

### ISSUE THREAD

**Issue by yibow98** [opensearch-project/OpenSearch-Dashboards#2616]
Need to change delete button to danger state (Red), refer to Save Objects delete modal.

**Comment by KrooshalUX** [comment]
Clarification: delete button should be "danger" state, which is red. Warning state is more of an orange.

**Comment by yibow98** [comment]
> Clarification: delete button should be "danger" state, which is red. Warning state is orange, and would not apply here.

I have modified the description. Thanks @KrooshalUX  for clarification!
