### ISSUE TITLE
[MD] Meta issues from UX sign-off meeting

### ISSUE THREAD

**Issue by yibow98** [opensearch-project/OpenSearch-Dashboards#2623]
#### Experimental callout 
- [x] #2614 

#### Datasource listing page
- [x] #2615 
- [x] #2616 
- [x] #2617 
- [x] #2626 

#### Datasource create page
- [x] #2618 
- [x] #2619
- [x] #2620 

#### Datasource update page
- [x] #2621 
- [x] #2622

**Comment by KrooshalUX** [comment]
Commented on issue #2616  for clarity, all others look accurate. Thanks @yibow98 !
