### ISSUE TITLE
[BUG] [MD] Visbuilder

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#2631]
**Describe the bug**

In the dev playground instance, when i open visbuilder `/app/wizard` I see the following error popup

<img width="788" alt="Screen Shot 2022-10-19 at 6 22 11 PM" src="https://user-images.githubusercontent.com/20453492/196834044-d90bb43a-5835-4dcb-9ad6-34f09543cc79.png">

Visbuilder is using the following flow to fetch the available index patterns

```
const ids = await data.indexPatterns.getIds(true);
const patterns = await Promise.all(ids.map((id) => data.indexPatterns.get(id)));
```

**To Reproduce**
1. Go to dev playground instance
2. Go to visbuilder (`/app/wizard`)

**Expected behavior**
Should not see the error since the data plugin api's should not return index patterns that the current user does not have access to.

**OpenSearch Version**
2.x

**Dashboards Version**
2.x playground 

**Plugins**

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by zengyan-amazon** [comment]
@ashwin-pc It seems due to one of the data source (cf594c00-4e66-11ed-85b2-dfe7b949e559) password was incorrect, which caused that error. Update password to the correct one fixed that error. 

However, I see visBuilder keeps attempting to load the problematic index pattern and generating a lot of error toast, do we have a retry logic there until we load all index patterns in vizBuilder

**Comment by ashwin-pc** [comment]
Got it! No, its not retry but a react state update that retriggers the request. The client should already be caching this value so this should not be an issue if everything is correct, but as we've seen here, if there is an error with the index, we have too many errors. I've created an issue for Vis Builder to track that in #2643 

Closing this as the error was actually expected.
