### ISSUE TITLE
Input fields that can accept sensitive data should have `spellcheck='false'` 

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch-Dashboards#2657]
_I'm not sure if this should belong in the Dashboards or OUI repro, please move this issue it if is more appropriate somewhere else._

Spell checking systems can send user sensitive data to 3rd parties, the best want to be sure this does not happen is to add `spellcheck=false` onto html elements that should be protected such as user password fields.

If there are any 'masked' fields in OpenSearch they should have this setting applied to them and plugins should be able to turn this on if they are creating custom `EuiFieldText` based input fields.

More information about this data disclosure [1], and link to conversation where it was unclear how this could be added in Dashboards [2] in a feature that is targeting the v2.4.0 release.

[1] https://www.otto-js.com/news/article/chrome-and-edge-enhanced-spellcheck-features-expose-pii-even-your-passwords
[2] https://github.com/opensearch-project/security-dashboards-plugin/pull/1110/files#r986322939

**Comment by joshuarrrr** [comment]
@peternied Is this issue for the entire project (including security-dashboards plugin), or is this specific for fields in core dashboards?

Also, why is this tagged `2.4.0`?

**Comment by peternied** [comment]
This issue impacts the entire OpenSearch project.

The security-dashboards plugin has 2.4.0 components that are adding new fields that should have this property enabled on them, wanted to make sure we had this discussion and potential resolution before those features shipped.

**Comment by kavilla** [comment]
@kristenTian do you know if we should add this to the password field to MD?

**Comment by seanneumann** [comment]
Long term solution is to make this change in OUI. @KrooshalUX to create an issue in that repo. 

Short term solution is to update any masked fields in sec plugin and MD. @kristenTian to look.

**Comment by KrooshalUX** [comment]
I would like to discuss what other fields besides password are potentially sensitive data so we can provide additional guidance/guardrails at a Design System level (OUI components). Endpoint URLs come to mind as potentially another field that we might consider sensitive.

**Comment by kristenTian** [comment]
In MD, the related changes are:

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/115105a3c945dae4c2218caaeacaa854b2789afa/src/plugins/data_source_management/public/components/edit_data_source/components/update_password_modal/update_password_modal.tsx#L116-L154 

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/8d5e504041ce808c0c897a32485de5f8eed30d2a/src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx#L267-L281

And none of these changes have `spellcheck` specified, so they are default to `undefined`.  Therefore we are good.

**Comment by seanneumann** [comment]
@rednaksi91 I think this one goes under Vis. Can you follow-up?

**Comment by seanneumann** [comment]
Thanks for closing Miki.
