### ISSUE TITLE
[VisBuilder] Icons and strings implementation

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#2659]
Parent ux issue: https://github.com/opensearch-project/ux/issues/49

This issue for the implementation side of things.

**Comment by ashwin-pc** [comment]
@abbyhu2000 Doesn't #2645 resolve this?

**Comment by abbyhu2000** [comment]
Yes, close this one as #2645 is resolved. @ashwin-pc
