### ISSUE TITLE
[Bug] Path comparison issues causing plugin not able to build on Windows

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/OpenSearch-Dashboards#2669]
Coming from https://github.com/opensearch-project/dashboards-reports/issues/191#issuecomment-1291166886.

The issue being that Windows treat `Administrator` dir and `ADMINI~1` dir as the same on Windows.
But the code here in dashboards core is using `===` to compare:
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/d7004dc5b0392477fdd54ac66b29d231975a173b/packages/osd-plugin-helpers/src/load_opensearch_dashboards_platform_plugin.ts#L47
```
  const isRootPlugin = parentDir === Path.resolve(REPO_ROOT, 'plugins');
```

This cause a diff in comparison between these two paths in .ts, while on windows they point to the same location:
```
C:\Users\Administrator\AppData\Local\Temp\2\tmpndbrtuhg\OpenSearch-Dashboards\plugins
C:\Users\ADMINI~1\AppData\Local\Temp\2\tmpndbrtuhg\OpenSearch-Dashboards\plugins
```

This then cause the failure when building dashboards plugin:
```
+ yarn plugin_helpers build --opensearch-dashboards-version=2.4.0
yarn run v1.22.19
$ node ../../scripts/plugin_helpers build --opensearch-dashboards-version=2.4.0
ERROR Plugin located at [C:\Users\Administrator\AppData\Local\Temp\2\tmpzgwnkv7a\OpenSearch-Dashboards\plugins\dashboards-reports] must be moved to the plugins directory at the root of the OpenSearch Dashboards repo
error Command failed with exit code 1.
```

Thanks.

**Comment by seanneumann** [comment]
@manasvinibs can you prioritize this issue?

**Comment by peterzhuamazon** [comment]
More resources:
* https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#short_vs._long_names

Seems like we can try to disable this behavior on windows agent:
* https://learn.microsoft.com/en-US/troubleshoot/windows-server/performance/stop-error-code-0x00000019

**Comment by peterzhuamazon** [comment]
I would say the best solution is to find a way to resolve this on typescript side, without pushing windows agent to disable short names.

Since there will be community members using this code to build themselves.

Thanks.

**Comment by peterzhuamazon** [comment]
More details:
https://manjusullad.wordpress.com/2016/01/06/how-can-i-find-create-short-path-for-windows-folders-directories/

**Comment by bbarani** [comment]
@AMoo-Miki Any update on this issue?

**Comment by AMoo-Miki** [comment]
Rolled out with 2.4.0.
