### ISSUE TITLE
[BUG] Add integration and Add Sample data do the same thing

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#2684]
**Describe the bug**

On the page shown in the screenshot below, both "Add Integration" and "Add Sample Data" both take the user to the add sample data page.

**To Reproduce**
1. Create a fresh instance of OS and OSD
2. Go to the homepage
3. Click on either button
4. See the same result

**Expected behavior**

Either we should remove the "Add integration" button or replace it with something more useful

**OpenSearch Version**
3.0
**Dashboards Version**
3.0
**Plugins**

Please list all plugins currently enabled.

**Screenshots**
<img width="780" alt="Screen Shot 2022-10-27 at 5 15 09 PM" src="https://user-images.githubusercontent.com/20453492/198420593-b0a43468-5d9f-4212-b2d3-f2b5dbd7538c.png">

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by bandinib-amzn** [comment]
`Add integration` should allow user to add data from a variety of sources (e.g. apps, services etc). It should not lead to sample data set.

We will first provide short term fix which is removing `Add integration` button and just keep `Add sample data' button as both the buttons are taking user to sample data page.

For long term fix, @kavilla will create issue and work with UX team to decide workflow for `Add integration`.
