### ISSUE TITLE
[BUG] version missing match in packages.json

### ISSUE THREAD

**Issue by seraphjiang** [opensearch-project/OpenSearch-Dashboards#269]
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/package.json#L15

should packages.json version match with OpenSearch version 7.10.3?

what above branch? should it be 1.x?

```
  "version": "7.10.2",
  "branch": "7.10",
```

**Comment by mihirsoni** [comment]
This issue has been taken care with #292
