### ISSUE TITLE
[MD]Multi data source integration with Dev tool

### ISSUE THREAD

**Issue by kristenTian** [opensearch-project/OpenSearch-Dashboards#2699]

**Comment by zhongnansu** [comment]
TODO
- [ ] backend impl to be able to connect to datasources
- [ ] UI/UX, need to build a good user experience for user to select a datasource, and be able to know the datassource session. Notes for self: It doesn't necessarily to be a UI component, given the cli nature of dev tool console. We could add a field in the request uri for datasource

**Comment by zhongnansu** [comment]
@KrooshalUX fyi for some updates above

**Comment by KrooshalUX** [comment]
Here are some thoughts expressed in wires (not yet approved, will be reviewing with @kgcreative)

**Option 1 - Most likely a long term solution**
Here is what I believe to be the most correct update for Dev Tools, but given the release timeline I am not sure this is practical. This solution introduces [`OuiControlBar`](https://oui.opensearch.org/1.0/#/navigation/control-bar) as the "home" for functions like "Show/Hide history", "Settings" and "Help". It also corrects the page title from a tab to a proper H1/Title. 

In the example of control bar found [here](https://oui.opensearch.org/1.0/#/navigation/control-bar) and using references for how sources are changed in other features within OpenSearch Dashboards, it appears the best case for changing the data source would be to use an `OuiButton` (Empty) to reveal `OuiPopover` containing `OuiSelectable` with the searchable prop and singleSelection props set to `true`. 

Show history reveals the near-identical UI as present today (minus the close button). I am not sure if the space to the left of the history is there on purpose - if not, the history would span the width of the window including proper padding. 
![image](https://user-images.githubusercontent.com/105819041/225202135-4d7d875d-0d0a-4ddb-9786-c0d2bef66bb1.png)
![image](https://user-images.githubusercontent.com/105819041/225202151-63c19a6c-ce70-4115-9f9b-0a078a1fb6b7.png)
![image](https://user-images.githubusercontent.com/105819041/225202166-dd592dc6-7b00-4989-836d-0dfd15c764a4.png)

**Option 2 - Most practical for next release timing**
In the short term I imagine we are only able to execute something like this using `OuiComboBox` with the compressed & prepend props set to `true`. The prepend prop allows for a string value, in this case "data source" or "index pattern" (if its limited to working with index patterns as many of our features are) or something similar might work well to show what source the Dev Tool is interacting with. 

![image](https://user-images.githubusercontent.com/105819041/225199884-93c3bdc6-4521-4d20-a016-9283abe7fb45.png)

@zhongnansu  Please let me know your thoughts on these approaches - I can provide a more detailed hand-off once we choose a direction.

**Comment by zhongnansu** [comment]
@KrooshalUX Thanks Kroosh for the design. Option 2 with datasource dropdown list looks good to me, and the implementation seems straightforward as well. In the additional notes, you mentioned adding tabs to dev tool console, and OuiTabs seems insufficient and it's not interactive. I need to evaluate the effort for implementing such tab component.

cc: @zengyan-amazon @kgcreative @seraphjiang

**Comment by zhongnansu** [comment]
@KrooshalUX given the time and resources, we are not able to complete the "added engineering scope" of adding tabs. Are you OK with we stick with the original scope for 2.7 to only add data source selector on the top right? We can work on tabs in 2.8 release. 
cc: @kgcreative

**Comment by KrooshalUX** [comment]
@zhongnansu  Yes, that aligns to our expectation. To clarify, that was just ideation, our preference is to move forward with Option 2 from the first comment.
