### ISSUE TITLE
[Table Visualization] Add a more detailed Readme for table vis

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#2731]
Add a more detailed Readme if possible. 
* What is Table Vis
* How to use Table Vis
* How it interacts with the rest of the application

**Comment by joshuarrrr** [comment]
@ananzh Relabeling for `2.6.0`, as this is unassigned.

**Comment by ananzh** [comment]
Consider it done as https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/vis_type_table/README.md been merged.

If there is anything required to add up, pls open a new issue.
