### ISSUE TITLE
[Vis builder] Persist data when switching visualization types

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#2763]
Currently the field values are cleared when the user switches between vis types. VisBuilder should be able to persist values across compatible types and ideally between incompatible types too to whatever degree possible.

Tasks:

- [x] Investigate potential persistence solutions
- [x] Investigate how the solutions will scale with varying visualization types (May tie into Visualization Abstractions)
- [x] Implement persistence
- [ ] Functional tests

**Comment by abbyhu2000** [comment]
Split into sub tasks.

**Comment by abbyhu2000** [comment]
The first two subtasks are finished in these two issues: #2900 and #3482

**Comment by abbyhu2000** [comment]
Close this issue as the aggregation persistence has been implemented in this PR: #3495
