### ISSUE TITLE
[BUG] opensearch-dashboards-data-source-audit.log do not have line separator on cygwin/msys/mingw

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/OpenSearch-Dashboards#2764]
Hi,

https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/3383848918/jobs/5620140524#step:9:35

This will not happen on powershell but will happen on any mingw related emulated shell on windows.

bash: line 1: D:tmpopensearch-dashboards-data-source-audit.log: command not found

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/890a4b649c0a4169a8683a7ca72c0fda55e886d0/src/plugins/data_source/audit_config.ts#L39

The path separator is removed in the process resulted in the log not able to be accessed.

Thanks.

**Comment by peterzhuamazon** [comment]
After taking a look it is a non-issue, closing now.

**Comment by peterzhuamazon** [comment]
This is actually an issue that needs to be resolved by dashboards.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/3415811911/jobs/5685325875#step:10:90

**Comment by peterzhuamazon** [comment]
Seems like fixed in this PR just not being pulled in the latest artifact.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2793

**Comment by kavilla** [comment]
@kristenTian can we confirm?

**Comment by kristenTian** [comment]
Yes, https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2793 was merged in.

**Comment by peterzhuamazon** [comment]
I already confirmed this change is working in function test repo bundle e2e test.
Thanks.
