### ISSUE TITLE
[i18n] ru, ru-RU locale support

### ISSUE THREAD

**Issue by dmitry-by-step-logic** [opensearch-project/OpenSearch-Dashboards#2816]
**Is your feature request related to a problem? Please describe.**

Plugins translations using `@osd/i18n/react` component `FormattedMessage` not work as expected with `ru`, `ru-RU` locales.
Register this locales in `packages/osd-i18n/src/core/locales.js`, ref [#1582](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1582).

**Comment by kavilla** [comment]
Closed by https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2817
