### ISSUE TITLE
[BUG] Errors building docker container

### ISSUE THREAD

**Issue by jgough** [opensearch-project/OpenSearch-Dashboards#285]
I am trying to build a docker container with OpenSearch-Dashboards, but this fails with the following error:
```
   │      Step 23/31 : COPY --chown=1000:0 config/kibana.yml /usr/share/kibana/config/kibana.yml
   │          at makeError (/mnt/build/OpenSearch-Dashboards/node_modules/execa/lib/error.js:59:11)
   │          at handlePromise (/mnt/build/OpenSearch-Dashboards/node_modules/execa/index.js:114:26)
   │          at process._tickCallback (internal/process/next_tick.js:68:7)

error Command failed with exit code 1.
```

The Dockerfile that I think is generated by src/dev/build/tasks/os_packages/docker_generator/templates/Dockerfile seems to reference kibana many times so guessing needs to be updated?

**To Reproduce**
Run the following commands
```
yarn osd bootstrap --force-install --allow-root
yarn build --docker
```

**Expected behavior**
A docker container is built

**Comment by jgough** [comment]
I replaced kibana with opensearch-dashboards (and opensearch_dashboards for the config file) throughout this file and it successfully built.  Need to think about image names though as his creates then creates the image docker.opensearch.co/opensearch-dashboards/opensearch-dashboards, which is the wrong host.

Running a container built in this manner results in the following:
```
docker run -it --rm docker.opensearch.co/opensearch-dashboards/opensearch-dashboards:7.10.2-SNAPSHOT
  log   [23:17:44.331] [info][plugins-service] Plugin "visTypeXy" is disabled.
  log   [23:17:44.365] [fatal][root] { Error: Unknown configuration key(s): "monitoring.ui.container.opensearch.enabled". Check for spelling errors and ensure that expected plugins are installed.
    at ensureValidConfiguration (/usr/share/opensearch-dashboards/src/core/server/legacy/config/ensure_valid_configuration.js:55:11) code: 'InvalidConfig', processExitCode: 64, cause: undefined }

 FATAL  Error: Unknown configuration key(s): "monitoring.ui.container.opensearch.enabled". Check for spelling errors and ensure that expected plugins are installed.
```

**Comment by jgough** [comment]
Removing the line
```  ${!imageFlavor ? 'monitoring.ui.container.opensearch.enabled: true' : ''}```
from src/dev/build/tasks/os_packages/docker_generator/templates/opensearch_dashboards_yml.template.ts

Seems to fix this and makes the docker container run.  Would you like me to submit a pull request with these changes?

**Comment by mihirsoni** [comment]
@jgough Thank you for reporting this issue. Would you be awesome if you can create PR for the same.
