### ISSUE TITLE
[Table Visualization][Test] Add unit tests

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#2856]
Should add unit tests using react test library.

**Comment by joshuarrrr** [comment]
@ananzh Will this issue be resolved by https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3397 ?

**Comment by ananzh** [comment]
unit tests are added. close this issue.

**Comment by joshuarrrr** [comment]
completed via #3397
