### ISSUE TITLE
[Docs] Update EUI doc site links to point to OUI doc site

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#2862]
All links to `elastic.github.io/eui*` and anchor text should be updated to reference the OUI doc site instead: https://oui.opensearch.org

Found in the following files:
1. `DEVELOPER_GUIDE.md`
2. `src/plugins/home/server/services/tutorials/lib/tutorial_schema.ts`
3. `src/plugins/home/server/services/tutorials/lib/tutorials_registry_types.ts`
4. `src/plugins/opensearch_dashboards_legacy/public/notify/toasts/TOAST_NOTIFICATIONS.md`

**Comment by KrooshalUX** [comment]
Are there any places that reference EUI.elastic.co in addition to the GitHub link you found ?

**Comment by joshuarrrr** [comment]
> Are there any places that reference EUI.elastic.co in addition to the GitHub link you found ?

Nope, at least not in this codebase.

**Comment by joshuarrrr** [comment]
Absolutely!

**Comment by ss-vijayvavdiya** [comment]
@joshuarrrr
I'd like to take a look at this, in case the issue is still open.

**Comment by vvavdiya** [comment]
@joshuarrrr
I'd like to take a look at this, in case the issue is still open.

**Comment by vvavdiya** [comment]
@joshuarrrr do we need to tag this issue with `#OSCI` label?

**Comment by joshuarrrr** [comment]
> @joshuarrrr do we need to tag this issue with `#OSCI` label?

No, we're tracking the PRs.
