### ISSUE TITLE
[Research] Data persistence in current dashboard plugins

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#2876]
### Data persistence
There are four plugins that currently have data persistence ability in opensearch dashboard: dashboard, discover, timeline, and visualize. They are using the following services and mechanisms from opensearch_dashboard_utils plugin to achieve data persistence.

State syncing utils are a set of helpers to sync application state with URL or browser storage(when turning state: storeInSessionStore on in advanced setting, in case of overflowed URL):
1. syncState(): subscribe to state changes and push them to state storage; subscribe to state storage and push them to state container
2. storages that are compatible with syncState()
* OsdUrlStateStorage: serialize state and persist it to URL's query param in rison format; listen for state change in URL and update them back to state
* SessionStorageStateStorage: serialize state and persist it to URL's query param in session storage
3. state containers: redux-store like objects to help manage states and provide a central place to store state

### Two type of persistence
There are two parts for data persistence: 
1. app state (example from visualization plugin)
    1. app state storage key: '_a'
    2. app state is persistent only within the specific app, values will persist when we refresh the page, values will not be persist when we navigate away from the app
    3. for visualize app, the params are:
       1. query
       <img width="257" alt="Screen Shot 2022-11-15 at 1 20 34 AM" src="https://user-images.githubusercontent.com/43937633/201880618-51ded552-f3cd-4146-b8ff-fba088eeedba.png">

       2. filters 
       <img width="513" alt="Screen Shot 2022-11-15 at 1 19 14 AM" src="https://user-images.githubusercontent.com/43937633/201880353-df1bcfeb-9f77-4e1e-b689-e8894f9430e2.png">
       
       3. vis
       4. ui state
2. global query state 
    1. global state storage key: '_g'
    2. global query state is persistent across the entire application, values will persist when we refresh the page, or when we navigate across visualize, discover, timeline or dashboard page. For example, if we set time range to last 24 hours, and refresh intervals to every 30 min, the same time range and refresh intervals will be applied if we navigate to any of the other pages.
    3. params:
       1. filters
       2. refresh intervals
       <img width="465" alt="Screen Shot 2022-11-15 at 1 22 48 AM" src="https://user-images.githubusercontent.com/43937633/201881096-2f3422f5-264b-42ff-9af1-c6f7950720be.png">

       3. time range
       <img width="465" alt="Screen Shot 2022-11-15 at 1 22 13 AM" src="https://user-images.githubusercontent.com/43937633/201881002-033265f9-33fe-47f5-9329-b8d8c23e6428.png">

### URL breakdown & example
![Screen Shot 2022-11-15 at 1 55 39 AM](https://user-images.githubusercontent.com/43937633/201889038-23b1912d-847a-4fa2-824e-9406a50cfc6f.png)

### Global state persistence
1. In plugin.ts, during plugin setup, call createOsdUrlTracker(), listen to history changes and global state changes, then update the nav link URL. This also returns function such as onMountApp(), onUnmountedApp()
     ```
    const {
      appMounted,
      appUnMounted,
      ...
    } = createOsdUrlTracker({
      baseUrl: core.http.basePath.prepend('/app/visualize'),
      defaultSubUrl: '#/',
      storageKey: `lastUrl:${core.http.basePath.get()}:visualize`,
      navLinkUpdater$: this.appStateUpdater,
      stateParams: [
        {
          osdUrlKey: '_g',
          stateUpdate$: data.query.state$.pipe(
            filter(
              ({ changes }) => !!(changes.globalFilters || changes.time || changes.refreshInterval)
            ),
            map(({ state }) => ({
              ...state,
              filters: state.filters?.filter(opensearchFilters.isFilterPinned),
            }))
          ),
        },
      ],
   ....
   ```
    * when we enter the app and app is mounted, it initialize nav link by getting previously stored URL from storage instance: `const storedUrl = storageInstance.getItem(storageKey)`. (Storage instance is a browser wide session storage instance.) Then it unsubscribes to global state$ and subscribes to URL$. The current app actively listens to history location changes. If there are changes, set the updated URL as the active URL
     ```
       function onMountApp() {
           unsubscribe();
           ...
           // track current hash when within app
                 unsubscribeURLHistory = historyInstance.listen((location) => {
                       ...
                       setActiveUrl(location.hash.substr(1));
                    }
                 });
              }
     ```
    * when we are leaving the app and app is unmounted, unsubscribe URL$ and subscribe to global state$. If the global states are changed in another app, the global state listener will still get triggered in this app even though it is unmounted, it will set the updated URL in storage instance, so next time when we enter the app, it gets the URL from the storage instance thus the global state will persist. 
       ```
            function onUnmountApp() {
                 unsubscribe();
                 // propagate state updates when in other apps
                      unsubscribeGlobalState = stateParams.map(({ stateUpdate$, osdUrlKey }) =>
                            stateUpdate$.subscribe((state) => {
                            ...
                            const updatedUrl = setStateToOsdUrl( ... );
                            ...
                           storageInstance.setItem(storageKey, activeUrl);
                   })
                 );
            }
       ```
   
   
3. In app.tsx, call syncQueryStateWithUrl(query, osdUrlStateStorage) to sync '_g' portion of url with global state params
    * when we first enter the app, there is no initial state in the URL, then we initialize and put the _g key into url
        ```
        if (!initialStateFromUrl) {
             osdUrlStateStorage.set<QueryState>(GLOBAL_STATE_STORAGE_KEY, initialState, {
             replace: true,
          });
        }
        ```

   * when we enter the app, if there is some initial state in the URL(the previous saved URL in storageInstance), then we retrieve global state from '_g' URL
```
   // retrieve current state from `_g` url
  const initialStateFromUrl = osdUrlStateStorage.get<QueryState>(GLOBAL_STATE_STORAGE_KEY);
  // remember whether there was info in the URL
  const hasInheritedQueryFromUrl = Boolean(
    initialStateFromUrl && Object.keys(initialStateFromUrl).length
  );
  // prepare initial state, whatever was in URL takes precedences over current state in services
  const initialState: QueryState = {
    ...defaultState,
    ...initialStateFromUrl,
  };
```
   * if we make some changes to the global state
        1. stateUpdate$ get triggered for all other unmounted app(if we made the change in visualize plugin, then the stateUpdate$ will get triggered for dashboard, discover, timeline), then it will call setStateToOsdUrl() to set updatedURL in storageInstance so global state get updated for all unmounted app
        2. updateStorage() get triggered for currentApp to update current URL state storage, then global query state container will also be in sync with URL state storage

  ```
 const { start, stop: stopSyncingWithUrl } = syncState({
    stateStorage: osdUrlStateStorage,
    stateContainer: {
      ...globalQueryStateContainer,
      set: (state) => {
        if (state) {
          // syncState utils requires to handle incoming "null" value
          globalQueryStateContainer.set(state);
        }
      },
    },
    storageKey: GLOBAL_STATE_STORAGE_KEY,
  });
  start();
 
```
  

### App state persistence
* we use useVisualizeAppState() hook to instantiate the visualize app state container, which is in sync with '_a' URL
```
const { stateContainer, stopStateSync } = createVisualizeAppState({
        stateDefaults,
        osdUrlStateStorage: services.osdUrlStateStorage,
        byValue,
      });
```
* when we first enter the app, there is no app state in the URL, so we set the default states into URL in createDefaultVisualizeAppState()
`osdUrlStateStorage.set(STATE_STORAGE_KEY, initialState, { replace: true });`
* when we make changes to the app state, the `dirtyStateChange` event emitter will get triggered, then osd state container will call updateStorage() to update the URL state storage, then state container(appState) will also be in sync with URL state storage
   ```
   const onDirtyStateChange = ({ isDirty }: { isDirty: boolean }) => {
        if (!isDirty) {
          // it is important to update vis state with fresh data
          stateContainer.transitions.updateVisState(visStateToEditorState(instance, services).vis);
        }
        setHasUnappliedChanges(isDirty);
      };
      eventEmitter.on('dirtyStateChange', onDirtyStateChange);
    ... 
    const { start, stop: stopSyncingWithUrl } = syncState({
              stateStorage: osdUrlStateStorage,
              stateContainer: {
                  ...globalQueryStateContainer,
                  set: (state) => {
                      if (state) {
                          globalQueryStateContainer.set(state);
                       }
                  },
            },
            storageKey: GLOBAL_STATE_STORAGE_KEY,
       });
       // start syncing the appState with the ('_a') url
        startStateSync();
    ```

* in useEditorUpdates(), we use the saved appState to load the visualize editor

### Refresh
When we refresh the page, both app state and global state should persist:
1. appMounted() gets triggered for the current app, so current app subscribe to URL$
2. syncQueryStateWithUrl() gets called within app.tsx for the current app, and we are getting the global states from URL '_g', and then connectToQueryState() gets called to sync global states and state container for the current app so the current app load the saved global states in top nav
4. stateUpdate$ will get triggered for every other unmounted app, so the global states are updated for their URL in storage instance as well by calling setStateOsdUrl()
5. when we load the visualize editor, createDefaultVisualizeAppState() gets called, and it gets app state from URL '_a', and it updates `appState` based on URL
6. in useEditorUpdates(), it uses the updated `appState` to load the visualization with previous saved states

### Navigate to another app
When we navigate to another app from the current app, global state should persist: 
 1. appUnmounted() triggered for the current app, unsubscribe to URLHistory$, and subscribe to stateUpdate$
 2. appMounted() triggered for the app that we navigated to, so it unsubscribe its stateUpdate$, and subscribe to URLHistory$
 4. syncQueryStateWithUrl is triggered, it then gets the saved global state from the osdurlstatestorage and set the top nav global states by using globalQueryStateContainer

### Diagram
1. When first navigate to the visualize app, initialize and sync state storage and state containers
<img width="1092" alt="Screen Shot 2022-11-18 at 3 44 38 PM" src="https://user-images.githubusercontent.com/43937633/202821200-c194d19a-5145-47d2-b458-308534c23b58.png">

2. When we navigate to another app, the browser wide storage instance stores the last active URL for each app and also updates the URL if there are any new global state values. This ensure global data persistence across different apps. For example, if we navigate from visualize app to discover app:
<img width="681" alt="Screen Shot 2022-11-15 at 12 59 54 PM" src="https://user-images.githubusercontent.com/43937633/202024258-bb3b0183-a996-4c93-b2a1-cc0feed70975.png">

Example storage instance: 
![Screen Shot 2022-11-15 at 12 06 54 PM](https://user-images.githubusercontent.com/43937633/202015197-0bfabadd-5c5a-41d3-a305-536b12ffbcb9.png)

3. When we made some changes to the global params, the global query state container will receive updates and push the updates to osd url state storage. Other unmounted app will update their last active URL in instance storage as well.
<img width="1002" alt="Screen Shot 2022-11-17 at 4 46 52 PM" src="https://user-images.githubusercontent.com/43937633/202590728-c8b1459c-cbc3-4930-903c-eb1abefba679.png">

4. When we made some changes to the app params, the app state container will receive updates and also push the updates to osd url state storage.
<img width="762" alt="Screen Shot 2022-11-15 at 12 59 02 PM" src="https://user-images.githubusercontent.com/43937633/202024116-f38f443b-5241-4a9a-94e6-8717c7b8aac5.png">

5. When we refresh the page, we parse the information from the URL(_g for global state, _a for app state). We use the saved information to create new state containers and set up synchronization between state containers and state storage.
<img width="984" alt="Screen Shot 2022-11-15 at 12 59 26 PM" src="https://user-images.githubusercontent.com/43937633/202024177-c097480e-0ed5-4736-b161-a65131c73f80.png">

**Comment by ashwin-pc** [comment]
@abbyhu2000 This is an amazing deep-dive! I can already think of a lot of good ways to put this system to use. 

@kroosh @kgcreative while this is a technical deep-dive, I just want to put this on your radar when you think about how we want make the experience across Dashboard's and its plugins to feel unified and when we want to persist information as the user navigates form one app to another.

**Comment by joshuarrrr** [comment]
@abbyhu2000 What's the plan for where we're going to add this info to make it discoverable by other devs?

**Comment by abbyhu2000** [comment]
> @abbyhu2000 What's the plan for where we're going to add this info to make it discoverable by other devs?

@joshuarrrr will raise a PR and put this into root level doc folder.

**Comment by abbyhu2000** [comment]
Since the readme on the current plugin persistence implementation is merged, will close this issue.
