### ISSUE TITLE
[Feature Anywhere] Enable plugins to augment visualizations with additional data and context

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/OpenSearch-Dashboards#2880]
Currently time series visualizations are limited in just showing raw results generated on-the-fly from configured metrics, and don't provide any additional insights about the data shown on the chart. There are several OpenSearch plugins that are tailored towards providing insights into time series data, including [Anomaly Detection](https://github.com/opensearch-project/anomaly-detection) and [Alerting](https://github.com/opensearch-project/alerting).

To provide an easy way for users to gain more insights with their existing visualizations, as well as help improve visibility and adoption of these additional plugins, we propose a generic framework to allow plugin resources (e.g., anomaly detectors, alerting monitors) to be associated with visualizations, either via automatic generation based on a visualization itself, or existing plugin resources. Additionally, we can support overlaying these additional results on top of the visualization charts.

At a high level, this can be achieved through the following steps:
1. Construct a framework allowing plugins to register an option on the visualization details panel, to let users maintain relationships between a visualization and their plugin resources
2. Introduce a generic `VisLayers` interface to support multiple ways of overlaying / augmenting data in a visualization chart
3. Migrate the line visualization's charting library from the in-house `vislib` library to `vega-lite`, to more easily process & render overlayed data onto the charts
4. Introduce a new `feature-anywhere` saved object type to persist relationships between a plugin resource and a visualization
5. Introduce a new `vis_layers` expression function type that can be used to process plugin data and convert into visualization overlay data
6. Intercept the visualization render flow to collect & process any produced `VisLayer`s to show on the chart canvas

All of these new components (Steps 2,4,5 from above) can be maintained and registered in a standalone `vis_augmenter` plugin - see #2958 for details.

Plugins can onboard to this framework by performing the following steps:
1. Register their plugin as an option in the visualization details panel
2. Register a `vis_layers` expression function to process their plugin data and convert into a `VisLayer`.
3. Develop UI components to maintain the relationships between a visualization and plugin resources. This may include auto-creation of resources based on a visualization's config, or linking existing plugin resources. It will require CRUD operations on `augment-vis` saved objects for persisting these relationships.

Anomaly Detection and Alerting are the first 2 plugins that will be onboarding. Details can be found in their respective meta issues:
- Anomaly Detection: https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/400
- Alerting: https://github.com/opensearch-project/alerting-dashboards-plugin/issues/457

All related issues should be labeled with https://github.com/opensearch-project/OpenSearch-Dashboards/labels/feature-anywhere

Progress tracker (core Dashboards)
- [x] #2882 ([PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3108))
- [x] #2717 ([PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3076))
- [x] #2893 ([PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3109))
- [x] #2894 ([PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3108))
- [x] #2958 ([PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3107))
- [x] #3373 ([PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3374))
- [x] #2915 ([PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3106))
- [x] #3122 ([PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3131))
- [x] #3130 ([PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3145))
- [x] #3317 ([PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3777))
- [x] #3268 ([PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3687))
- [x] #3267 ([PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3646))
- [x] #3580 ([PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3649))
- [x] #3155 ([PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3415))
- [x] #3361 ([PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3961))
- [x] #3485 
- [x] #3582 
- [x] #2916 
- [x] #3383 
- [ ] #3833 
- [x] #3836 ([PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4006))
- [x] #4044 ([PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4059))
- [x] #3649 

Current bug tracker (meta issue):
- [x] #3969 

Progress tracker (functional tests)
See https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues?q=is%3Aissue+is%3Aopen+%5BFeature+Anywhere%5D

Future enhancement tracker (not part of initial release):

- [ ] #3481 
- [ ] #3509 
- [ ] #3407 
- [ ] #3566 
- [ ] #3644 
- [ ] #4138
- [ ] #4180 

Below are some of the high-level designs describing this feature:
Fig 1: The visualization render workflow design (changes highlighted in red)
![render design](https://user-images.githubusercontent.com/62119629/202597311-dbffbeca-a60c-4b23-914c-33130fa34b4f.png)

Fig 2: The user workflow design (changes highlighted in red):
![workflow design](https://user-images.githubusercontent.com/62119629/202597325-83e947c9-f1c9-432c-b742-04d29b578aad.png)

Below are some of the proposed mockups, using the anomaly detection plugin as an example:

Fig 3: View overlayed data on a visualization chart
![Screen Shot 2022-11-15 at 3 41 28 PM](https://user-images.githubusercontent.com/62119629/202048213-62913768-2452-4135-9b91-88d64901146a.png)

Fig 4: View registered plugins in the visualization options panel
![Screen Shot 2022-11-15 at 3 41 45 PM](https://user-images.githubusercontent.com/62119629/202048244-3500c861-d258-4f04-825c-f0466603a0c6.png)

Fig 5: View details for the Anomaly Detection plugin
![Screen Shot 2022-11-15 at 3 41 58 PM](https://user-images.githubusercontent.com/62119629/202048307-b16ce31a-4ed6-449b-b8fc-8f6fe3d7b636.png)

Fig 6: View details for a particular associated anomaly detector
![Screen Shot 2022-11-15 at 3 42 31 PM](https://user-images.githubusercontent.com/62119629/202048325-05341cb9-d529-42b9-a5f3-c032607b1b09.png)

**Comment by lezzago** [comment]
Alerting Meta task issue: https://github.com/opensearch-project/alerting-dashboards-plugin/issues/457

**Comment by amitgalitz** [comment]
Anomaly Detection meta task issue: https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/400

**Comment by ohltyler** [comment]
Added both of those in description ^

**Comment by kavilla** [comment]
As called out: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3981

We will target this for v2.next for prioritization on Node upgrade.
