### ISSUE TITLE
[Bug] Issues with RegionMaps plugin

### ISSUE THREAD

**Issue by VladutZzZ** [opensearch-project/OpenSearch-Dashboards#2888]
Hello,

I think I found multiple issues with region maps after adding support for custom import map vector.

First, from debugging the current code, looks like if you chose default map you can't use Name as join Field and iso_3166_2 is default selected:
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/region_map/public/region_map_visualization.js#L159

And the second one is using custom vector map, when getting vector map, size is not set so only first 10 Features are returned.
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/region_map/server/routes/opensearch.ts#L67
I got all results by adding size in params:
`const params = { index, body: {} ,size: 30};`

Thank you

**Comment by AbhishekReddy1127** [comment]
Hi @VladutZzZ for the first, it is getting updated with Name. Could you provide any small snippet of what you were describing so that, we can have some clear picture about it..

https://user-images.githubusercontent.com/62020972/207927233-4839e10c-e5a7-4668-ab07-f8289d894f8f.mov

For the second, I am not sure if it’s a bug since the request number is using by default. Could you provide more detailed information , so that we could look into it.

**Comment by VladutZzZ** [comment]
Hi,
For the first bug, it's not an UI bug, you can change it on UI and will change, the problem is on backend and you could see if you have some data in that index with countries name and will not show any result, only warnings with "USA not found" and you could see in backend that ISO 3166-1-alpha-2 Code is used even if on UI you selected Name.

For the second one, why shouldn't be a bug if you can set that value?
For example you import your custom geojson with 50 countries and from that geojson will be retreived only the first 10 entries because default used and on UI you can't override that value in this case.

Thanks

**Comment by kavilla** [comment]
Issue moved to [opensearch-project/dashboards-maps #156](https://github.com/opensearch-project/dashboards-maps/issues/156) via [**Zenhub**](https://www.zenhub.com/)
