### ISSUE TITLE
Add Windows support to the future 1.x releases

### ISSUE THREAD

**Issue by AMoo-Miki** [opensearch-project/OpenSearch-Dashboards#2889]
Would involve manually backporting #2601, #2681, and #2703.

**Comment by joshuarrrr** [comment]
@AMoo-Miki Can we update the version label here? Given the timeline for `1.3.7`, we'd need a PR to review tomorrow, which seems unlikely.

**Comment by joshuarrrr** [comment]
Closed via #2601, #2681, #2703 (and the backported versions). Also required #2842, #2964, #2965 (including manual backporting)
