### ISSUE TITLE
[Table Visualization][Bug] URL value is not clickable if enabled

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#2905]
### Description
This is a bug I found when deep dive in our functional tests. If we set `clientip` as URL format in index pattern field, it is not shown properly in the new table visualization.
 
<img width="864" alt="Screen Shot 2022-11-21 at 09 42 40" src="https://user-images.githubusercontent.com/79961084/203124127-3e0576fc-fe61-42b1-9b8a-b7492b3978c0.png">

They should be clickable. Below is from old table vis:
<img width="835" alt="Screen Shot 2022-11-20 at 20 34 48" src="https://user-images.githubusercontent.com/79961084/203123972-94a5ff93-6ec2-41cb-80b4-49cb68d72248.png">

<img width="1178" alt="Screen Shot 2022-11-20 at 20 34 35" src="https://user-images.githubusercontent.com/79961084/203111179-776e89b8-b8ff-4c19-bedb-00a918b7bc07.png">

### Reproduce Steps
- go to stack management, click `Index Patterns` then click index pattern `opensearch_dashboards_sample_data_logs`
- search `clientip` and click edit button on its right
- in `format` field, choose URL

### Expectation
* Should show clickable URL in table visualization
1. after setting up the field in index pattern, go to visualize and create a table visualization 
2. choose opensearch_dashboards_sample_data_logs, split rows with terms and field is clientip
3. clientip value in the table vis should be clickable
4. save this table visualization 

* Should show clickable URL in dashboard
1. open saved table vis in the above test in the dashboard
2. the clientip in the table vis should be URL and clickable

**Comment by ananzh** [comment]
This bug is due to the following line of code in [this file](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/f12fa98da910bbaea50ca3b52f7b177c1531657b/src/plugins/vis_type_table_new/public/components/table_vis_component.tsx#L55)
```
const formattedContent = column.formatter.convert(rawContent, 'text');
```

currently, in the new table vis, we set the content formatter to convert raw content to text format. we should convert it to html format.

**Comment by ananzh** [comment]
By switching text to html below:
```
const formattedContent = column.formatter.convert(rawContent, 'text');
```

<img width="805" alt="Screen Shot 2022-11-22 at 12 23 20" src="https://user-images.githubusercontent.com/79961084/203414055-feba959f-7b0b-4505-8d4a-72a9abb8cece.png">

Now we could see HTML content of a DOM element. But react can not recognize the html content and it just treat it as string. We could use `dangerouslySetInnerHTML` to let react know this is html content.

* security: 
According to [here](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml), use `dangerouslySetInnerHTML` may expose to a [cross-site scripting (XSS)](https://en.wikipedia.org/wiki/Cross-site_scripting) attack. However, for our use case, I think it is safe. These text are not from inputs. They are customer's data. As long as data is not messed, we should be safe.

**Comment by kavilla** [comment]
> They are saved customer's data.

Historically for security issues I believe we still had to purify the content before setting even though it was saved data. But does other viz plugins handle sanitization of data, I believe there is some sanitizing within the repo.

**Comment by joshuarrrr** [comment]
> But does other viz plugins handle sanitization of data

The answer is "no", it appears, at least when using these field formatters.
