### ISSUE TITLE
Minimal migration of Visualization line charts to vega-lite

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#2915]

**Comment by joshuarrrr** [comment]
@lezzago Please update the description with the scope you have in mind for the minimal migration.

**Comment by lezzago** [comment]
The scope of the minimal migration is to render the line chart using vega-lite instead of vislib whenever there is a need to use specific vega lite features such as annotating the visualization.

**Comment by ohltyler** [comment]
Closing via #3106
