### ISSUE TITLE
[Feature Anywhere] Framework for plugin registration

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#2916]
Construct a framework allowing plugins to register an option on the visualization details panel, to let users maintain relationships between a visualization and their plugin resources

**Comment by jackiehanyang** [comment]
The registration workflow is done at the plugin level, with a change in Dashboards to improve context menu grouping method. 

The PR for improving context menu grouping method - https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3169

A screenshot of how the registration looks like on the visualization details panel
![Screen Shot 2023-01-25 at 11 08 05 AM](https://user-images.githubusercontent.com/41348518/214659955-0484a11f-40f2-4dea-a62b-eaa76c767dfd.png)

**Comment by jackiehanyang** [comment]
Will close the issue once the PR at Dashboards side has been merged. @joshuarrrr

**Comment by joshuarrrr** [comment]
@jackiehanyang @sikhote Is this closable now that we merged https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3924?
