### ISSUE TITLE
[BUG] Table vis allows fields that can cause the app to crash

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#2923]
**Describe the bug**

When a count field is added to the split rowss dropbox and then clicked to edit the agg type, the whole app crashes

**To Reproduce**
1. Go to VisBuilder
2. Drag and Drop count to "Split Rows"
3. Click on the "filters" field (The dropped field)
4. See app crash

**Expected behavior**
- [ ] This field should not be allowed in the split rows dropbox.
- [ ] The app should gracefully error in such a scenario

**OpenSearch Version**
3.0

**Dashboards Version**
3.0

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by ashwin-pc** [comment]
The root cause here can be fixed quite easily by adding `!filters` to the agg filter for the table vis type. The bigger challenge is to make sure that issues like this does not takedown the whole application.

**Comment by joshuarrrr** [comment]
@ashwin-pc Is this still in scope for `2.5.0`?

**Comment by ashwin-pc** [comment]
yep, I'll have the PR out by tomorrow

**Comment by joshuarrrr** [comment]
@ashwin-pc Can we close now?
