### ISSUE TITLE
Visualizations "Controls"

### ISSUE THREAD

**Issue by serena-martino** [opensearch-project/OpenSearch-Dashboards#2931]
Hello,
i need to get value for specific Field and using it to filter data in my dashboard.
I select controls visualization but probabily there are more data in the fied and this is the message:

_"Terms list might be incomplete  because the request is taking too  long. Adjust the autocomplete  settings in  opensearch_dashboards.yml for  complete results "_ 

I can't adjust the autocomplete settings in opensearch_dashboards.yml .

I tried to disable Dynamic option but that doesn't help me.
I tried to crete small index patterns and  to reduce the time taken however i see that the visualization is experimental.

*Opensearch version is 1.2

![Controls](https://user-images.githubusercontent.com/118269868/204313859-b9481f48-d27a-40ae-8f31-4c516119d548.JPG)

Do you have any suggestions? I know that this visualization is experimental, is there any news ?

**Comment by joshuarrrr** [comment]
@serena-martino That message indicates that there are at least partial results for the autocomplete, but that it might not have every term that may be present. I believe the filter would still allow you to select a field value even if it doesn't appear on the list. 

As an alternative, you may not need a controls visualization - can you create the necessary filter with the global filter controls instead? If so, you can save those as part of your dashboard or saved search.

**Comment by BSFishy** [comment]
@serena-martino can you provide an update on the previous question?

**Comment by serena-martino** [comment]
Ok, thanks
