### ISSUE TITLE
Snapshots are only available for Linux and Windows, Any alternate option for Mac OS

### ISSUE THREAD

**Issue by ShubhamBhardwaj218** [opensearch-project/OpenSearch-Dashboards#2944]
I'm new this technology, I have Mac OS, and I was trying to learn Opensearch Dashboard and to do some code level modification in Opensearch Dashboard. I was following the [Developer Guide](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md) to get the boiler plate code in my system,
When I run the  following command.

`$ yarn opensearch snapshot `

I got an error saying `Snapshots are only available for Linux and Windows`
I have attached the log below.

(base) user_name@users-MacBook-Pro OpenSearch-Dashboards % yarn opensearch snapshot
yarn run v1.22.19
$ node scripts/opensearch snapshot
 info Installing from snapshot
   │ info version: 3.0.0
   │ info install path: /Users/user_name/OpenSearch-Dashboards/.opensearch/3.0.0
   │ info license: oss
   │ERROR Snapshots are only available for Linux and Windows
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Please provide some alternate options for MacOS.

Thank you.

**Comment by peterzhuamazon** [comment]
Hi @joshuarrrr we currently only have mac snapshot for OpenSearch, not Dashboards.

Thanks.

**Comment by abbyhu2000** [comment]
As @peterzhuamazon  mentioned, we do not currently support MacOS for OpenSearch Dashboards. This is currently blocked by a build repo issue: https://github.com/opensearch-project/opensearch-build/issues/38. 

We also have a similar issue to track support for MacOS in our repo, https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2087, and it is about running functional tests on MacOS.
