### ISSUE TITLE
Cut an initial GitHub release

### ISSUE THREAD

**Issue by philoserf** [opensearch-project/OpenSearch-Dashboards#295]
As a OpenSearch Dashboard user
In order to use the source
I need a release target

**Comment by mihirsoni** [comment]
@philoserf  Thank you for reporting this issues, as initially mentioned on  launch day -- we are still working on getting the artifacts out. This should happen in coming weeks. 

I'll be closing this issue and will track the project milestone Beta which will ensure we'll have artifacts which can be deployed. 

Feel free to re-open the issue if more question.
