### ISSUE TITLE
Maintainer Areas of Responsibility

### ISSUE THREAD

**Issue by geekygirldawn** [opensearch-project/OpenSearch-Dashboards#296]
It would be great if we could also add people's areas of responsibilities to the new [MAINTAINERS file](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/MAINTAINERS.md). This helps people understand which of these maintainers is responsible for a particular area. We could add this as a new column to the existing table or as a separate section of the file. I'm happy to do if someone wanted to let me know which people are responsible for what.

Here's an [example](https://github.com/goharbor/community/blob/master/MAINTAINERS.md).

The motivation for my suggestion is to help the rest of us outside of Amazon better understand the maintainers and what they are likely to be working on. The key here is likely and not exclusively. Having a bit more info helps the rest of us:
* understand who to talk to if we need to escalate a PR if it gets neglected for a long time or if something urgent comes up.
* learn about potential gaps that we could fill - maybe no one from Amazon is focused in a particular area that one of us has expertise in.
* we're all individuals interacting with each other, and if we all know a bit more about the people in leadership positions, it can help the rest of us understand where you're coming from.

**Comment by boktorbb-amzn** [comment]
I think that this topic was adequately covered in this issue over in the OpenSearch repo:

`https://github.com/opensearch-project/OpenSearch/issues/537`

On the dashboards side, we also haven't had the chance to particularly specialize into any roles and as alpha/beta releases keep moving forward we want to maintain an open process to allow for any available person to tackle what needs to be done at any given time.

We are currently working on a process that will help address some of the issues you bring up, such as PR escalation.
