### ISSUE TITLE
[BUG]Readme OpenSearch Github Repo Link

### ISSUE THREAD

**Issue by TheAlgo** [opensearch-project/OpenSearch-Dashboards#297]
**Describe the bug**

The READMe says to clone OpenSearch as a pre-requisite to run OpenSearch Dashboards but the link for OpenSearch Engine is of OpenSearch Dashboards. Can we rectify the README?

**Comment by kavilla** [comment]
Good catch! Thanks for making the change.

**Comment by TheAlgo** [comment]
No problem !
