### ISSUE TITLE
Backport Windows support to 1.x branch

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/OpenSearch-Dashboards#3015]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/181, backport Windows support to 1.x branch.

- [ ] Passing CI for 1.x branch on Windows
- [ ] Documentation

If you are already have an issue tracking backport Windows CI to 1.x branch, please link here.

**Comment by kavilla** [comment]
Hi @rishabh6788 we dont have specific issue to track backporting as a core repo. But we have backported the windows changes. 

I see OpenSearch did not have an issue can we just close this issue as this is not a plugin repo?

cc: @AMoo-Miki
