### ISSUE TITLE
change console plugin to use core.http to replace jQuery.ajax

### ISSUE THREAD

**Issue by zengyan-amazon** [opensearch-project/OpenSearch-Dashboards#3044]
**Is your feature request related to a problem? Please describe.**
OSD DevTool console browser side plugin uses `jQuery.ajax` to call NodeJS API instead of using `core.http` which is inconsistent with all other use cases, all settings on browser side `core.http`, like request interceptors don't apply to the devtool console calls. related code: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/console/public/lib/opensearch/opensearch.ts#L61

**Describe the solution you'd like**
refactor console plugin to use `core.http` to call OSD server, get rid of 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by seanneumann** [comment]
Thanks @zengyan-amazon. This seems like a generally good change. Looking forward to seeing the PR.

**Comment by joshuarrrr** [comment]
That definitely sounds like a legacy oversight. Is it just tech debt, or is there any user impact of using the ajax approach?
