### ISSUE TITLE
[FEATURE] Add red dot to the embeddable component

### ISSUE THREAD

**Issue by jovancacvetkovic** [opensearch-project/OpenSearch-Dashboards#3057]
**Is your feature request related to a problem? Please describe.**
Implement a red dot indicator to the embeddable component to support #3046 

**Describe the solution you'd like**
The embeddable component update handler will set a new boolean attribute called `indicateActionToTake` and if the attribute is set to `true` then render the red dot indicator.

**Comment by ashwin-pc** [comment]
@jovancacvetkovic whats the differecne between this issue and #3046?

**Comment by jovancacvetkovic** [comment]
I thought the previous ticket was just investigation ticket and we need ticket where we say the exact thing we are implementing. If you think this is just overthinking we can close this as a duplicate?

**Comment by ashwin-pc** [comment]
Yeah, the other one should suffice since it limits the conversation thread and whatever the decision is on that issue can be used to raise a PR against it :)
