### ISSUE TITLE
[MD] Feature test connection follow up

### ISSUE THREAD

**Issue by kristenTian** [opensearch-project/OpenSearch-Dashboards#3060]
Given the author is not able to continue follow up on the original code in #2973, and the team still prefer to pick this up, creating sub issues to work incrementally and track the feature & backport.

- [ ] Discuss and address the comments.
- [ ] Update UT(UT that previous skipped to unblock PR merge).
- [ ] Handling 403 error case.
- [ ] replace empty datasource id with undefined
- [ ] improve error handling (not return 500 in this edit case)

**Comment by zhongnansu** [comment]
- UI bug
<img width="1626" alt="image" src="https://user-images.githubusercontent.com/32652829/207204483-52cec881-3428-453d-8637-7ca04859a82b.png">

**Comment by kristenTian** [comment]
Is there no error message toast to user in edit data source page?
