### ISSUE TITLE
[BUG] Flakey link for datasource plugin tests

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#3075]
**Describe the bug**

We have 2 instances of `http://datasource.com` that points to a misconfigured url. When our lychee link checker runs during CI/CD, the check fails when this link is not reachable

**To Reproduce**
The issue is intermittent so here is a reference failure

https://github.com/opensearch-project/OpenSearch-Dashboards/actions/runs/3653727844/jobs/6173497842

**Expected behavior**
The link should point to one of the excluded urls e.g. example.com or this domain should be added to the excluded domains. I propose the former since we already have an exhaustive list of excluded URLs ant these 2 use cases dont seem to justify the need for another one.

**OpenSearch Version**
3.0

**Dashboards Version**
3.0

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

-

**Comment by zhongnansu** [comment]
Found lychee exclude list from https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/TESTING.md#additional-checks

Thanks for submitting the issue. I wasn't aware of this during development tho, maybe like you said, it's flaky. Anyway, we'll fix it following best practice
@ashwin-pc

**Comment by ashwin-pc** [comment]
No worries. Created the issue for tracking purposes since I saw that a lot of tests were having to be rerun because of it. That website will also be getting a lot of traffic from our CI workflows lol.

**Comment by ashwin-pc** [comment]
@zhongnansu can we close this issue now that those links are fixed?
