### ISSUE TITLE
[BUG] OpenSearch license text should be removed

### ISSUE THREAD

**Issue by arunx2** [opensearch-project/OpenSearch-Dashboards#3083]
**Describe the bug**
When importing a lens visualization, it is reporting to upgrade with appropriate license. I think it is a residue of kibana fork with xpack license.

**To Reproduce**
1. Export the attached visualization ndjson
2. When loading the dashboards, it shows error.

**Expected behavior**
Instead of showing the message to upgrade to an appropriate license, it can be as simple as `{type} can't be loaded. The plugin/visualization is not supported.` 
**OpenSearch Version**
Please list the version of OpenSearch being used.
2.3

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.
2.3
**Plugins**

Please list all plugins currently enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/844111/207731481-49edf48c-21d6-4952-9854-3344971ad356.png)

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

[export _copy.ndjson.zip](https://github.com/opensearch-project/OpenSearch-Dashboards/files/10232244/export._copy.ndjson.zip)

**Comment by joshuarrrr** [comment]
Hi @arunx2 - OpenSearch Dashboards doesn't support (and will likely never support) importing and viewing visualizations created in Kibana Lens, or other visualizations created in Kibana after the license change and fork.

However, you're right that we should update the language of that error message: 

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/911b969b22224ed55c43148e4b1e3abcae884516/src/plugins/embeddable/public/lib/errors.ts#L52

**Comment by joshuarrrr** [comment]
@kgcreative Can you provide guidance on the language for this error message? The context of the error is when an embeddable panel in the dashboard is of an unknown embeddable type. One initial thought:

> `OpenSearch Dashboards can't load "{type}" embeddables, because there's no compatible loader.`

It's a little tricky because I can think of several circumstances where a user might encounter this error. In addition to the case mentioned in the issue, another is if a user had a visualization built in a plugin that they no longer have installed.

**Comment by kgcreative** [comment]
@natebower can you review language here? My recommendataion:

`OpenSearch Dashboards can't load "{type}" visualizations. Check for a missing plugin or an incompatible visualization type.`

**Comment by natebower** [comment]
I agree with @kgcreative, though I would question whether we need the first instance of "type". Would it be sufficient just to say "{type} visualizations"? Otherwise, we'd need to hyphenated it as "{type}-type visualizations." Also, "plugin" should be one word with no hyphen.

**Comment by kgcreative** [comment]
@natebower I added "type" because one of the visualization types *is* `visualization`, so I was trying to avoid `... can't load "visualization" visualizations". I'm ok with removing `-type` if that's not a concern on your end.

**Comment by natebower** [comment]
In that particular case, I think "visualization-type visualizations" would still be awkward. I'm not sure that there's a great way to avoid the repetitiveness there. I'm fine either way, as long as `-type` is hyphenated if we use it.

**Comment by kgcreative** [comment]
I'm ok getting rid of `-type`, then. It feels redundant. 

Final copy: `OpenSearch Dashboards can't load "{type}" visualizations. Check for a missing plug-in or an incompatible visualization type.`

cc: @natebower , @joshuarrrr

**Comment by natebower** [comment]
> I'm ok getting rid of `-type`, then. It feels redundant.
> 
> Final copy: `OpenSearch Dashboards can't load "{type}" visualizations. Check for a missing plug-in or an incompatible visualization type.`
> 
> cc: @natebower , @joshuarrrr

"plugin" (one word, no hyphen)

**Comment by kgcreative** [comment]
Edited. Thanks for catching that!

**Comment by joshuarrrr** [comment]
> While "embeddables" is the technically correct term, it won't necessarily help end-users, and in Dashboard we have this Visualize -> Dashboard paradigm, so i'm using visualizations as a generic term for what goes into these panels

Yeah, to add a bit more context here, this error message is in the `embeddables` plugin, and embeddables aren't limited to visualizations, nor are they limited to the most common case, where the embeddables are visualizations and the dashboard app is where they're embedded. In our end user docs, we already tend to refer to anything embedded into a dashboard as a "visualization", even though that's actually quite confusing for markdown content, filter controls, etc. I'm still fine for this wording, but it will definitely be confusing in the edge case where some plugin is just using an embeddable to render basic HTML content and the embeddable factory is missing.

**Comment by kgcreative** [comment]
@joshuarrrr  - Would it make sense to say `object` instead of `visualization` or `embeddable`?

**Comment by joshuarrrr** [comment]
Yeah, I think that would be more accurate, although slightly less clear 😂

**Comment by tmarkley** [comment]
Related: #1479
