### ISSUE TITLE
[Vis Builder] Persist app filter and query without using state container

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#3089]
Current plugins persist the app filter and query use two source of truths: they create state container to be in sync with the URL(osdUrlStateStorage), and then the state container also needs to be sync with the state managers for filter and query from the data plugin. 

For vis builder, research to see if we can just directly hook state mangers for app filter and query from the data plugin with the URL for persistence.

**Comment by joshuarrrr** [comment]
closed via #3100
