### ISSUE TITLE
[BUG] Unable to build plugins using main branch

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/OpenSearch-Dashboards#309]
**Describe the bug**
main branch is on version `1.0.0`, but there is a version check expecting `7.9` when building plugins
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/packages/osd-plugin-helpers/src/cli.ts#L97-L102

And `yarn build` would fail with `These tools are not designed to work with version before 7.9, please checkout an earlier version of OpenSearch Dashboards to build your plugin`

**To Reproduce**
see workflow for steps: https://github.com/opensearch-project/sql/actions/runs/775063356/workflow#L50
error: https://github.com/opensearch-project/sql/pull/17/checks?check_run_id=2412679186#step:8:12

**Expected behavior**
Should be able to build plugin artifacts

**OpenSearch Version**
latest main, 1.0.0

**Dashboards Version**
latest main branch

**Plugins**
query workbench

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by mihirsoni** [comment]
Thanks for reporting the issue @joshuali925  @ananzh  Can you take a look at this ?

**Comment by ananzh** [comment]
Open an [PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/312)

**Comment by ananzh** [comment]
Fix it. Solve by PR [#312](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/312)
