### ISSUE TITLE
[BUG][Vis Builder] Pipeline aggregations break the app

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#3096]
**Describe the bug**

When using pipeline aggregations, the agg config created results in a 400 error. The cause is an incorrect parameter value for `min_doc_count` is sent.

**To Reproduce**
1. Go to VisBuilder
2. Add a pipeline agg to the Y axis
3. Add a timestamp field to the X axis
4. See error in network tab

**Expected behavior**

- [ ] The `min_doc_count` of 0 needs to be set for the `histogram` and `date_histogram` agg if it is the last bucket agg and is followed by a pipeline agg.
- [ ] If the last bucket agg is not a `histogram` or `date_histogram` agg given a parent pipeline agg, display a human readable error calling this out via a toast.

**OpenSearch Version**
3.0
**Dashboards Version**
3.0
**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by joshuarrrr** [comment]
@ashwin-pc Should this be targeted for `2.6.0` instead? PR is in draft.

**Comment by ashwin-pc** [comment]
I had marked it as draft since i wasnt sure if there was an overlap with your PR for pie chart, should be good to mark it as ready for review now.

**Comment by joshuarrrr** [comment]
Complete via #3137
