### ISSUE TITLE
[VisBuilder] Persist visualization internal state

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#3124]
VisBuilder Visualizations have internal state that they would like to persist when changed. Currently we do not persist this data. 

Note: We may want to hold off on implementing this until the migration to vega-lite is complete. f we cant wait for that, we need to investigate the impact of the migration on the saved object data since the uistate after migration may be drastically different from that of the legacy library.

**Comment by BSFishy** [comment]
@ashwin-pc Can we have more information about what you mean by "internal state"?

**Comment by ashwin-pc** [comment]
@BSFishy, today a user can interact with a visualization that lets them set values in the visualization, e.g.  The color for a line chart or the sort order for the table visualization. This value is not saved with the visualization and then the user reloads the visualization, this information is lost. The goal of this issue os to allow for those values to persist.
