### ISSUE TITLE
Add json worker and language implementation in @osd/monaco

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/OpenSearch-Dashboards#3132]
**Is your feature request related to a problem? Please describe.**

We are developing index state management and using `monaco-editor` to edit JSON content, however I find the monaco instance does not support json language.
<img width="931" alt="image" src="https://user-images.githubusercontent.com/13493605/209253802-fdc64031-c666-4bd1-b5b1-f54f0f9d6c3b.png">

Our product want to enhance the json editor with the capability to validate the properties of json in different case, e.g. Validate the index settings and give a hint on line if the property is not supported.
![image](https://user-images.githubusercontent.com/13493605/209254069-99048964-21d2-442b-b6bb-be8c237f70b7.png)

**Describe the solution you'd like**

Add the support of the language of json and add `monaco.languages.json` object to enable plugins to add [DiagnosticsOptions](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.json.DiagnosticsOptions.html).

**Additional context**

You can find the JSON validation playground [here](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults)

**Comment by SuZhou-Joe** [comment]
#3133

**Comment by joshuarrrr** [comment]
@SuZhou-Joe Thanks! I'm surprised we didn't already have JSON language support in there, but this will be a welcome addition.

**Comment by joshuarrrr** [comment]
This issue is a prerequisite for https://github.com/opensearch-project/index-management-dashboards-plugin/issues/545, which is currently targeted for `2.6.0`. We may also need to complete https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3097 to unblock this issue.
