### ISSUE TITLE
[BUG] Link copy fails in Visualisations > Share

### ISSUE THREAD

**Issue by lucafrost** [opensearch-project/OpenSearch-Dashboards#3147]
**Describe the bug**

When in Visualisations > My_Example_Viz, there is an issue when attempting to share the current visualisation as the link generated is *not* copied to the clipboard (Safari v16.1 macOS Ventura). See the below screenshot of the modal box that _should_ allow the user to copy the sharing link to the clipboard.

![](https://i.imgur.com/ZvWnkCv.png)

**To Reproduce**
1. Go to Visualisations
2. Select a Visualisation
3. Select Share > Permalink or Embed Code
4. Click 'Copy Link'

**Expected behavior**
The generated link should be copied to the clipboard.

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
2.3.0

**Host/Environment (please complete the following information):**
 - OS: AWS-managed OpenSearch Service
 - Browser and version: Safari 16.1 on macOS Ventura 13.0.1

**Additional context**

👋 This is my first OS/OSD bug report, apologies if I have overlooked anything!!

**Comment by joshuarrrr** [comment]
@lucafrost Thanks for opening! I believe this is a duplicate of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1716, which already has a fair amount of discussion.

**Comment by lucafrost** [comment]
@joshuarrrr my bad, apologies!
