### ISSUE TITLE
Allow grouping context menus with only 2 children

### ISSUE THREAD

**Issue by sikhote** [opensearch-project/OpenSearch-Dashboards#3171]
**Is your feature request related to a problem? Please describe.**

We are looking to create nested items with only 2 options within. Currently, 4 options are required, otherwise the options will not be grouped.

**Describe the solution you'd like**

I would like to change the requirements from 4 to 2, if possible.

**Describe alternatives you've considered**

N/A

**Additional context**

This is supporting some additions to the alerting plugin, which will be integrating into the main dashboard's context menus. We are adding a context menu for some visualizations. See screenshot below of what we wish to accomplish, but with only 2 options inside the Alerting menu.

<img width="430" alt="Screen Shot 2023-01-02 at 2 43 07 PM" src="https://user-images.githubusercontent.com/24573542/210282687-38c0f661-ce4f-43d8-8aa7-90f6cfc11217.png">

<img width="338" alt="Screen Shot 2023-01-02 at 2 45 16 PM" src="https://user-images.githubusercontent.com/24573542/210282775-e7086ecb-48f0-44b3-8e01-4d3a875557d8.png">

**Comment by seanneumann** [comment]
Is this related to https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2880 ??

**Comment by sikhote** [comment]
@seanneumann I think it's related, but I will refer to @ashwin-pc to answer.

**Comment by joshuarrrr** [comment]
Interesting. I can see solid reasons for the previous requirement, but also how it would be useful to leverage grouping more explicitly. Reducing the minimum to 2 seems reasonable, but we'll need to make sure existing dev guidance (both docs and example plugins) are updated as part of the change.

**Comment by joshuarrrr** [comment]
@sikhote After chatting with other maintainers, this seems like a fine change, and makes sense in the context of the anywhere feature. Feel free to proceed with the draft PR.
