### ISSUE TITLE
[BUG] Time display behaves weird

### ISSUE THREAD

**Issue by kaninaba94** [opensearch-project/OpenSearch-Dashboards#3187]
https://stackoverflow.com/questions/75021947/wrong-timestamp-displayed-in-opensearch-dashboards

**Comment by AMoo-Miki** [comment]
Looks like this was the issue of bad format being defined in the mapping. The problematic format,`YYYY-MM-DD HH:mm:ss.SSS`, was replaced with `yyyy-MM-dd HH:mm:ss.SSS` and the question owner marked that as an accepted answer.
