### ISSUE TITLE
Proposal: Rename artifact from opensearch-dashboards-1.0.0-linux.x64.tar.gz to something else

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch-Dashboards#319]
**Is your feature request related to a problem? Please describe.**

We are naming the bundle that contains OpenSearch Dashboards and plugins as opensearch-dashboards-1.0.0-beta1-linux.x64.tar.gz, which is the same name as what is produced out of this repository. Let's find a new name, maybe -min?

**Describe the solution you'd like**

A name consistent with how we do this in https://github.com/opensearch-project/OpenSearch/issues/632. 

**Describe alternatives you've considered**

We considered naming OpenSearch Dashboards+plugins a bundle, but decided that for users we want a single downloadable OpenSearch Dashboards product that contains everything they want to run, so we wanted that to be called "opensearch".

We also know that the name may be confusing because it does not contain OpenSearch itself, but c'est la vie, the product is called "OpenSearch Dashboards".

**Additional context**

https://github.com/opensearch-project/OpenSearch/issues/632

**Comment by ananzh** [comment]
I will check this and update artifact name to include "beta1".

**Comment by ananzh** [comment]
Peter already created [artifact](https://github.com/opensearch-project/OpenSearch-Dashboards/releases/tag/1.0.0-beta1)  following the naming convention as OpenSearch.  We don't need to do anything for artifacts. To manually build artifact, just change version in package.json from 1.0.0 to 1.0.0-beta1.
