### ISSUE TITLE
[Tech Debt] Clean up `docs_link_service` organization so that strings are in the right categories

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#3208]
**Is your feature request related to a problem? Please describe.**

In https://github.com/opensearch-project/OpenSearch-Dashboards/blob/68d503d110862d55baaf90a190ab17990e9e0f08/src/core/public/doc_links/doc_links_service.ts#L54

We organize links to documentation in 3 categories:

1. `opensearch` - these should be documentation links at https://opensearch.org/docs/latest/opensearch
2. `opensearchDashboards` - these should be documentation links at https://opensearch.org/docs/latest/dashboards
3. `noDocumentation` - these should only be documentation link placeholders where no valid documentation exists

**Describe the solution you'd like**

As far as I can tell, existing links in `opensearch` and `opensearchDashboards` are all correctly categorized and formatted.

But for links defined under `noDocumentation`:

1. If an actual documentation link is defined (more than just the documentation homepage)
  1. Replace any hard-coded path with `${OPENSEARCH_DASHBOARDS_VERSIONED_DOCS}` or `${OPENSEARCH_VERSIONED_DOCS}` as appropriate
  2. If there's no comment with the absolute URL to the doc link, add a comment above the property
  3. Move the property to `opensearch` or `opensearchDashboards` property as appropriate
  4. Update the `DocLinksStart` interface
  5. Update any references in code from `.noDocumentation.` to the appropriate property 
2. Some links that appear to be valid are not. For example https://opensearch.org/docs/latest/downloads/beats/auditbeat redirects to the documentation homepage. These links should be corrected if actual documentation pages exist, or updated to be `${OPENSEARCH_WEBSITE_DOCS}`, which will make it more clear that the documentation is really missing

**Comment by sayuree** [comment]
I have some questions regarding this issue:
`Move the property to opensearch or opensearchDashboards property as appropriate`
1. So we need to create `noDocumentation` on both `opensearch` and `opensearchDashboards`, dividing  URLs starting from https://opensearch.org/docs/latest/opensearch/ and https://opensearch.org/docs/latest/dashboards respectively. Is it right?
2. ` These links should be corrected if actual documentation pages exist, or updated to be ${OPENSEARCH_WEBSITE_DOCS}, which will make it more clear that the documentation is really missing`
How can we find links to documentation pages? For example, currently, the links below automatically redirect to the docs homepage: 
https://opensearch.org/docs/latest/downloads/beats/auditbeat
https://opensearch.org/docs/latest/downloads/beats/filebeat
https://opensearch.org/docs/latest/downloads/beats/metricbeat
https://opensearch.org/docs/latest/downloads/beats/heartbeat
In the documentation, I found only Tools page, containing links to the download page of these items, e.g. 
https://www.elastic.co/downloads/past-releases/auditbeat-oss-7-12-1 for Auditbeat

Can you also please assign this issue to me?
