### ISSUE TITLE
Monaco editor: Using the worker.js instead of embedding the worker inside the main ui process. 

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/OpenSearch-Dashboards#3215]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/13493605/211271726-46b997a8-f388-4dec-9c0a-01ec9cf1aba9.png)

The monaco editor dashboard holds give warnings every time it launches, and the root reason is that dashboard loads the worker by loading the bundle code instead of loading an external js.

**Describe the solution you'd like**

Enable the capability of loading external worker.

**Describe alternatives you've considered**
N/A

**Additional context**
No.

**Comment by ashwin-pc** [comment]
I'm not able to reproduce this issue in the monaco editor instanced used in core dashboards (Vega and timeline visualization editors). @SuZhou-Joe we are using the Monaco editor in the timeline visualize app too (`/app/visualize#/create?type=timelion`) do you see this error there? Or is it limited to just the Index management app?

**Comment by SuZhou-Joe** [comment]
Hi @ashwin-pc you are right. I tried that and found out that the root cause is the MonacoDiffEditor. 
![image](https://user-images.githubusercontent.com/13493605/211774610-c087ad2f-70ac-4342-9969-ed5ae0c01651.png)

I changed the editor to DiffEditor and the warning appears.

**Comment by ashwin-pc** [comment]
Okay that makes sense. We dont use the diff editor in core OSD. Does the warning cause any issue in the app?
