### ISSUE TITLE
Increment the version on the parent branch (2.x) to the next development iteration (2.5)

### ISSUE THREAD

**Issue by manasvinibs** [opensearch-project/OpenSearch-Dashboards#3228]
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3174

**Comment by joshuarrrr** [comment]
@manasvinibs Can we close?

**Comment by manasvinibs** [comment]
Yes this is merged! https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3229
