### ISSUE TITLE
[BUG] yarn osd bootstrap failed for downloaded tar file

### ISSUE THREAD

**Issue by yilintao-amzn** [opensearch-project/OpenSearch-Dashboards#324]
**Describe the bug**

Run command `yarn osd bootstrap` failed for downloaded tar file for 1.0.0-beta1 and 1.0.0-alpha2

**To Reproduce**
1. Go to OpenSearch-Dashboards release: https://github.com/opensearch-project/OpenSearch-Dashboards/releases
2. Download 1.0.0-beta1 source code
3. Unzip the downloaded file
4. Enter `cd OpenSearch-Dashboards-1.0.0-beta1`
5. Run `yarn osd bootstrap`
6. See error
```
ERROR [bootstrap] failed:
ERROR Error: Command failed with exit code 128: git ls-files -dmto --exclude-standard ...
...
fatal: Not a git repository (or any of the parent directories): .git
```

**Expected behavior**
Expected behavior is no error shows up and the bootstrap can complete successfully.

**OpenSearch Version**
N/A

**Dashboards Version**
It happens to 1.0.0-beta1 and 1.0.0-alpha2

**Plugins**
N/A

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser and version N/A

**Additional context**

**Comment by ananzh** [comment]
This is because we don’t have .git file.  I find our artifact is not a binary code. Please correct me: my understanding is that for developers they can run `git clone` to get our repo. The purpose of artifacts is for people who just want to try dashboards. Artifacts allow people download quickly and people can run directly using `./bin/opensearch-dashboards` without build . Why we need an artifact still request .git and build which is same as development mode?

**Comment by mihirsoni** [comment]
@yilintao-amzn the tag artifact download doesn't give you git meta data IMO, you would need to clone the repo and either checkout the tag / branch and try it out.

Let us know if that doesn't work. 

Closing the issue as of now, feel free to re-open.

**Comment by AMoo-Miki** [comment]
While cloning the repo is one way to use the latest code, it is not the only way to acquire the latest code. We should make sure that users investing time in fetching the zip archive can use the dashboards too.

**Comment by ananzh** [comment]
@AMoo-Miki  would you like to open a new issue for your concern?

**Comment by abdulazizAl-Jabi** [comment]
ERROR [bootstrap] failed:
ERROR Error: Command failed with exit code 1: C:\Users\Eng-Abdulaziz Aljabi\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js run osd:bootstrap
      C:\Users\WazuhDashborad\wazuh-dashboard\node_modules\typescript\lib\tsc.js:84772
how to fix this problem
