### ISSUE TITLE
[BUG] Having connection issues when running Dashboards

### ISSUE THREAD

**Issue by sreekarjami** [opensearch-project/OpenSearch-Dashboards#326]
**Describe the bug**
After running Dashboards, it fails to connect with the OpenSearch with "socket hang up" error. 

Error:
  log   [16:27:35.170] [info][savedobjects-service] Waiting until all OpenSearch nodes are compatible with OpenSearch Dashboards before starting saved objects migrations...
  log   [16:27:35.260] [error][data][opensearch] [ConnectionError]: socket hang up
  log   [16:27:35.274] [error][savedobjects-service] Unable to retrieve version information from OpenSearch nodes.
  log   [16:27:37.690] [error][data][opensearch] [ConnectionError]: socket hang up
  log   [16:27:40.193] [error][data][opensearch] [ConnectionError]: socket hang up

**To Reproduce**

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by ananzh** [comment]
Sync up. Error msg is due to opensearch connection. not dashboards issue.

**Comment by Singathiramanan** [comment]
I am also facing same issue. How to fix this error
