### ISSUE TITLE
[BUG][VisBuilder] Error when validate schema in vis builder

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#3276]
**Describe the bug**

Found the following error when run vis-builder app.

<img width="748" alt="Screen Shot 2023-01-13 at 10 16 24" src="https://user-images.githubusercontent.com/79961084/212410611-b4095da2-19fd-42ad-a7a4-bd5d8b0ae736.png">

**To Reproduce**
Start vis-builder and navigate to any chart type.

**Expected behavior**
No error.

**Comment by curq** [comment]
Hi @joshuarrrr @abbyhu2000 @ananzh,

I want to work on this issue, can you please assign it to me?

**Comment by ashwin-pc** [comment]
While not the same, I will be fixing this as a part of #2643
