### ISSUE TITLE
[BUG] Fetch calls pass custom headers for every 302 request causing CORS 

### ISSUE THREAD

**Issue by anijain-Amazon** [opensearch-project/OpenSearch-Dashboards#3277]
**Describe the bug**

In some scenarios where a 302 redirect request is received by OpenSearch Dashboards, it makes a fetch call to the redirected url using custom headers like `osd-version` [here](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/public/http/fetch.ts#L147). If the redirected URL doesn't belong to OpenSearch Dashboards and is meant for an external authentication system, such custom headers can cause the browser to treat the request as eligible for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests). 

This causes the browser to first send a preflight request to the redirected endpoint to check whether custom headers are allowed.  An example is `Access-Control-Request-Headers: osd-version`

**To Reproduce**
Not providing the exact steps to reproduce as this involves the use of external authentication systems and associated plugins present in OS core written to intercept and authenticate requests which are proprietary. 

- User tries to access dashboards with an expired session. 
- Request to OpenSearch Dashboards `GET capabilities API` is intercepted by proprietary plugin and it sees that token in cookie is expired.
- Proprietary plugin redirects the user to external authentication system.
- Redirected URL is loaded by OSD using `fetch.ts` and custom header of `osd-version` is passed. 
- Browser makes a Pre-flight `OPTIONS` request to external authentication system due to the presence of custom header.
- Pre-flight request to the external authentication system fails and user is not redirected to login page of external authentication system.  

**Expected behavior**

Since, the custom header `osd-version` is only understood by OSD, we should avoid sending it if the redirected URL doesn't belong to Dashboards.  

**OpenSearch Version**
1.3

**Dashboards Version**
1.3

**Plugins**
- alertingDashboards
- anomalyDetectionDashboards
- cognitoLogout
- ganttChartDashboards
- indexManagementDashboards
- observabilityDashboards
- queryWorkbenchDashboards
- reportsDashboards
- securityDashboards
- storage

**Host/Environment (please complete the following information):**
 - iOS
 - Chrome version 106

**Additional context**

OpenSearch Dashboards supports multiple ways of authentication for a user like Basic Auth, SAML, OpenID; etc. Most of these are natively supported by the security-dashboards-plugin and security-plugin. 

To enable other forms of external authentication methods that are not currently supported in open-source, installations can make use of plugins in Opensearch to intercept and authenticate requests. Such external authentication systems can perform redirection to external login endpoint if the credentials of the user is expired. 

Such redirections currently fail to succeed, due to the presence of custom headers like `osd-version` in the redirected request added by OSD core.

**Comment by manasvinibs** [comment]
[Triage]: Platform team will research on this to determine if the header `osd-version` is even required and can it be eliminated from the request?

**Comment by seanneumann** [comment]
We'll add this to the top of the triage agenda.

**Comment by varun-lodaya** [comment]
@seanneumann any update?

**Comment by seanneumann** [comment]
@kavilla - Can you provide your thoughts here?

**Comment by varun-lodaya** [comment]
Guys, any update here? This has been affecting us for some time now.

**Comment by kavilla** [comment]
After taking sometime to look the `osd-version` is added with OpenSearch Dashboards requests to prevent XSRF attacks. Without it OpenSearch Dashboards will prevent responses from loading.

I might need to understand more of the current blockage but would it not be configurable on the server side to allow for `osd-version`.

If it's within core then adding:
```
http.cors.allow-headers: osd-version
```

Let me know!

**Comment by ramanavenky22** [comment]
I am facing this issue in OSD 2.15. I am making a 302 redirect and both osd-xsrf and osd-version headers are added to the fetch call for the redirected Url.
