### ISSUE TITLE
Reuse of IndexPatternsService in Opensearch Dashboards plugins

### ISSUE THREAD

**Issue by djindjic** [opensearch-project/OpenSearch-Dashboards#3280]
**Is your feature request related to a problem? Please describe.**

As part of one new feature in [Security Analytics](https://github.com/opensearch-project/security-analytics-dashboards-plugin) plugin, we would need to reuse [IndexPatternsService](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data/common/index_patterns/index_patterns/index_patterns.ts#L78). Does it make sense to share it via [CoreStart](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/public/index.ts#L265) in the same way as you share [notifications](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/public/index.ts#L279) service and we can access it in straightforward way via [plugin setup method](https://github.com/opensearch-project/security-analytics-dashboards-plugin/blob/main/public/plugin.ts#L35)?

cc: @amsiglan @AWSHurneyt

**Comment by manasvinibs** [comment]
Yes, that seems to be the preferred way to do that. If you have more questions while developing it, please post here and reach out the team.

**Comment by manasvinibs** [comment]
https://opensearch.org/blog/dashboards-plugins-intro/

**Comment by djindjic** [comment]
@manasvinibs thanks a lot on you points.

We have just done it as it's defined in docs. Just as a final confirmation I have proposed docs improvement that I realized while wanted to improve some typings on our side.  Please check if it make sense: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3302
