### ISSUE TITLE
Proposal: Clean out elastic packages: elastic-datemath, elastic-eslint-config-kibana and elastic-safer-lodash-set

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#329]
**Is your feature request related to a problem? Please describe.**
Packages elastic-datemath, elastic-eslint-config-kibana and elastic-safer-lodash-set are elastic's NPM. When we have time we can think about rename these packages and publish under opensearch npm org. 

**Describe the solution you'd like**

 When we have time we can think about rename these packages and publish under opensearch npm org. Packages are not big.

**Comment by JacobBrandt** [comment]
You left out @elastic/eui which is a huge part of the baseline.  What's wrong with using these packages?

**Comment by kavilla** [comment]
@JacobBrandt, great point!

 I think for this one @ananzh was referencing that within the package folder we have these packages:
* https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/packages/opensearch-datemath
* https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/packages/opensearch-eslint-config-opensearch-dashboards
* https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/packages/opensearch-safer-lodash-set

The package exists locally but we still uses @elastic/datemath everywhere.

**Comment by ahopp** [comment]
@ananzh @kavilla What's the next steps with this issue?

**Comment by joshuarrrr** [comment]
@ananzh It looks like this is complete for `elastic-datemath`, via
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/254
