### ISSUE TITLE
[BUG] Text is not visible in discover data rows

### ISSUE THREAD

**Issue by mengweieric** [opensearch-project/OpenSearch-Dashboards#3292]
**Describe the bug**

Text is not visible in discover data rows when hovering on it.

**To Reproduce**

1. Go to stack management
2. Click Advanced Settings.
3. On the General panel, scroll to the Dark mode setting and click the toggle switch to On.
4. Click Save.
5. Reload the page for the changes to take effect.
6. Go to discover and load some data
7. Hover over a data row

**Expected behavior**
The text should be visible on hover

**OpenSearch Version**
Latest version 2.5

**Dashboards Version**
Latest version 2.5

**Plugins**

Reporting,
Observability

**Screenshots**

<img width="1332" alt="Screen Shot 2023-01-19 at 11 57 00 AM" src="https://user-images.githubusercontent.com/80358241/213547312-1e039e7d-b2b1-4c2c-834f-cf7d75960d7a.png">

**Comment by joshuarrrr** [comment]
Thanks @mengweieric for reporting. We have an initiative planned for a large-scale refactor of discover https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1792. But I'd love to see this fixed sooner if possible.

**Comment by Nicksqain** [comment]
I understand you have fixed the visual bug.
You can close the issue :)

![изображение](https://user-images.githubusercontent.com/67852536/222482754-4a10ddf4-8428-4779-9bf0-3e4acce8e7df.png)

**Comment by joshuali925** [comment]
fixed by https://github.com/opensearch-project/dashboards-observability/pull/329 (event analytics added a global style that affected discover), this issue can be closed

**Comment by joshuarrrr** [comment]
oh, wow, thanks @joshuali925! didn't realize this was a case of style conflicts.
