### ISSUE TITLE
[Feature Anywhere] Support clicking & custom tooltip functionality from vega charts

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/OpenSearch-Dashboards#3317]
Coming from #2880 

As part of the project design, we need to add custom functionality in the vega line charts such that:
- clicking on an annotation datapoint opens a 'View events' flyout
- rendering custom tooltips based on the type of datatpoint (regular or annotation) that is being hovered on
 
**Custom clicking:**
This is needed to open the View Events flyout when an annotation datapoint is clicked on. This can be done by adding an event listener in the Vega View to process click events within the chart canvas. Adding filtering on "event"/"annotation" datapoints (datapoints coming from `VisLayer`s) will need to be done, including logic for determining what is/isn't this type. Additionally, will need to be able to toggle clicking on/off, such that it is turned off in the view events flyout. Otherwise this would allow infinite opening of the flyout.

**Custom tooltips:**
Current mocks have custom data shown when hovering over a particular datapoint, including listing an aggregate view of the events that exist within the particular time bucket. Refer to the mocks in the meta issue for details: #2880. Note that custom tooltips will also require filtering on "event"/"annotation" datapoints.

Based on the current Vega View architecture in Dashboards, there is a single vega base view, which is where the tooltip handler and click handlers can be defined. These maybe can move into a new vega view that overrides functionality to include the custom functionality we want.

For an example on the entry points for enabling the custom functionality - see draft PR #3369

**Comment by ohltyler** [comment]
Custom clicking functionality can be done by adding a special event listener on the vega view.

Custom tooltip functionality can be done by defining a custom tooltip handler, and having logic to determine if a datapoint is an "annotation" datapoint or not.

**Comment by joshuarrrr** [comment]
@ohltyler Is this draft still needed, or is it superseded by #3777?

**Comment by joshuarrrr** [comment]
@ohltyler is this completed via #3777, or does the tooltip/hover interactions still needed to be added.

**Comment by ohltyler** [comment]
Tooltip still needs to be addressed, so leaving open for now.

**Comment by ohltyler** [comment]
Closed via #4120
