### ISSUE TITLE
[BUG] TSVB fails to load in "edit" mode after upgrading from Opensearch 1.2 to 1.3

### ISSUE THREAD

**Issue by varunrao** [opensearch-project/OpenSearch-Dashboards#3327]
**Describe the bug**
We are using AWS Opensearch service. The initial upgrade was from Elasticsearch 7.10 to 1.2. The worked without any issues. We then upgraded to 1.3 and since then the TSVB visuals are failing to load in the "EDIT" mode. They work fine in the "display" mode.

Browser console shows the following error. I am using SerialDiff and custom script in my TSVB visual.

osd-ui-shared-deps.js:438 TypeError: Cannot read properties of undefined (reading 'links')
    at SerialDiffAgg (visTypeTimeseries.chunk.2.js:1:240120)
    at ua (osd-ui-shared-deps.js:438:59332)
    at Ms (osd-ui-shared-deps.js:438:104414)
    at gl (osd-ui-shared-deps.js:438:90018)
    at fl (osd-ui-shared-deps.js:438:89943)
    at ol (osd-ui-shared-deps.js:438:87291)
    at osd-ui-shared-deps.js:438:45733
    at t.unstable_runWithPriority (osd-ui-shared-deps.js:446:3462)
    at Hi (osd-ui-shared-deps.js:438:45442)
    at Gi (osd-ui-shared-deps.js:438:45678)

**Expected behavior**
The "Edit" mode should show up without any errors. 

**Plugins**
All default plugins that come with OpenSearch.

**Screenshots**

<img width="566" alt="image" src="https://user-images.githubusercontent.com/1559391/214502922-52a86da4-7dc1-4025-8bd3-add8e0db323d.png">

**Host/Environment (please complete the following information):**
 - OS: MacOS
 - Version [e.g. 12.5]
 - Google Chrome: Version 109.0.5414.87

**Comment by varunrao** [comment]
I am able to consistently reproduce this. It happens even when creating a new TSVB visual. The error occurs as soon as i select SerialDiff Aggregation (**docLinks.services is undefined**).
Any chance this was fixed in 2.X? 
![image](https://user-images.githubusercontent.com/1559391/214785910-a4305d33-5fa0-4957-9d02-533b5f5cba26.png)

**Comment by joshuarrrr** [comment]
I can repro this failure in the [playground](https://playground.opensearch.org/app/visualize#/create?type=metrics&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d,to:now))&_a=(filters:!(),linked:!f,query:(language:kuery,query:''),uiState:(),vis:(aggs:!(),params:(axis_formatter:number,axis_position:left,axis_scale:normal,default_index_pattern:opensearch_dashboards_sample_data_ecommerce,default_timefield:order_date,id:'61ca57f0-469d-11e7-af02-69e470af7417',index_pattern:'',interval:'',isModelInvalid:!f,series:!((axis_position:right,chart_type:line,color:%2368BC00,fill:0.5,formatter:number,id:'61ca57f1-469d-11e7-af02-69e470af7417',label:'',line_width:1,metrics:!((field:products.price,id:'61ca57f2-469d-11e7-af02-69e470af7417',type:sum),(alpha:0.3,beta:0.1,field:'61ca57f2-469d-11e7-af02-69e470af7417',gamma:0.3,id:'73849590-a665-11ed-93b9-97d62154a4cd',model_type:simple,multiplicative:!t,period:1,type:cumulative_sum,unit:'',window:5)),point_size:1,separate_axis:0,split_color_mode:opensearchDashboards,split_mode:everything,stacked:none,type:timeseries)),show_grid:1,show_legend:1,time_field:'',tooltip_mode:show_all,type:timeseries),title:'',type:metrics))) - from that example link, if you change "Cumulative Sum" to "Serial Difference" you'll see the reported error. From some quick spot-checking it appears to only be an issue with Serial Difference - other parent pipeline aggregations seem to work fine.

**Comment by joshuarrrr** [comment]
Added some additional context of the root cause in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3392
