### ISSUE TITLE
Design and Features Review For Observability Integration Framework

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/OpenSearch-Dashboards#3334]
## *Background*
Observability is the ability to measure a system’s current state based on the data it generates, such as logs, metrics, and traces. Observability relies on telemetry derived from instrumentation that comes from the endpoints and services.

Observability telemetry signals (logs, metrics & traces) arriving from the system would contain all the necessary information needed to observe and monitor.  Application today can have a complicated distributed architecture that combines cloud native and microservices layers. Each layer produces telemetry signals that may have different structure and information.

Observability telemetry schema defines the following components - logs, traces, metrics and notifications.
Log files provide comprehensive system details, such as a fault, and the specific time when the fault occurred. By analyzing the logs, one can troubleshoot code and identify where and why the error occurred. 
Traces represents the entire journey of a request or action as it moves through all the layers of a distributed system. Traces allow you to profile and observe systems, especially containerized applications, serverless architectures, or microservices architecture. Metrics are a numerical representation of data that can be used to determine a service or component’s overall behaviour  over time. Notifications and alerts that are raised in response to some condition being met. The condition is generally defined on the actual Observability ingested data.

In many occasions, correlate between the logs, traces and metrics is mandatory to be able to monitor and understand how the system is behaving. In addition the distributed nature of the application produces multiple formats of telemetry signals arriving from different components ( network router, web server, database)

For such correlate to be possible the industry has formulated a common structure for communicating these signals - the Observability schema.

### *Problem definition*
Today in OpenSearch, Observability and its dashboards are only partially aware (traces only) of the schematic structure of these 4 types. In addition the actual schema index mapping is not present internally in the Observability plugin and has to be imported externally.

Integrating different data producers and correlating different signals is practically unavailable most of the time due to missing schema definition and correlated field names.

Integration of a new Observability data source (such as NginX / Tomacat) includes complicated configuration of both the ingestion process and the actual index store, manually discovery of the specific format of the new datasource and the crafting of the dedicated dashboards for its proprietary fields.

### *Proposal* 
Our goal is creating a consolidated Observability solution which allows customers to ingest any type of telemetry data from any type of provider and have the capability of displaying and analysis of this data in a common and unified way.
Customers using Observability are expecting our solution allow simple and out of the box integration and configuration.

Using a unified schema that models all the Observability components, and allowing customers to easily add integrations that would simplify their daily monitoring and incidents investigations using pre-build dashboards and pre-defined correlation and notifications.

**Comment by joshuarrrr** [comment]
@YANG-DB I think the problem definition and background are clear, but the proposal could use quite a bit more detail - some examples would make it clearer and let us consider the pros and cons of particular technical implementations.

From what I've read so far, it also seems like an issue better suited to the https://github.com/opensearch-project/dashboards-observability repository (@opensearch-project/transfer-request please review).

**Comment by ahopp** [comment]
@YANG-DB Thanks for opening! 

In general, I 100% agree that a consolidated observability solution (which allows customers to ingest any type of telemetry data) with the ability to perform analysis in a common and unified way is an awesome vision. In fact, I think we should consider anyway we can to reduce the complexity and effort of identifying specific actionable information across multiple use cases including broader monitoring and observability use cases...tracing and telemetry are a few of many examples. Additionally, in generally, we are hoping to create a solution that allows simple and out of the box integration and configuration as best possible. 

But I'd love to understand a bit more about what you're hoping in this framework/solution, specifically some examples around how you see unified schema that models all the Observability components working. And what you specifically mean by integrations?

**Comment by YANG-DB** [comment]
see RFC for the Integrations design https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3412

**Comment by kavilla** [comment]
@dagneyb @seanneumann @rednaksi91 

Refreshing for comment.
