### ISSUE TITLE
[BUG] Replace documents with prod urls

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#335]
This issue has been repurposed to handle the replacing of the documents with prod urls because we replaced the dead links with the best of our ability but didn't have the best replacements so we replaced to the root document. Even with that there are gaps and even more so they are beta docs so the links aren't final.
----
**Describe the bug**

Any hyperlink that sends users to docs fails.

For example:
Flagging link for DQL information doesn't work. e.g. https://www.opensearch.org/guide/en/kibana/main/kuery-query.html navigates to a 404.

**To Reproduce**
1. Go to OpenSearch Dashboards
2. Click on Discover
3. Click on DQL
4. Click on link about DQL
5. See error
![Screen Shot 2021-05-07 at 12 42 30 PM](https://user-images.githubusercontent.com/12060704/117500940-32c61500-af32-11eb-928b-ee3c8a8347d0.png)

**Expected behavior**

**OpenSearch Version**
1.0.0

**Dashboards Version**
1.0.0

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**
Most of the issues we have could be solved by updating this: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/public/doc_links/doc_links_service.ts

**Comment by kavilla** [comment]
For this issue, we don't have a replacement document website. We have https://docs-beta.opensearch.org/docs/opensearch-dashboards but it isn't versioned and there is missing documents there. 

We did the best we can with some replacements that we have. Once we have a permanent replacement then we can complete this issue.

**Comment by kavilla** [comment]
Will need a replacement for Mappings API documentation.

**Comment by tmarkley** [comment]
Confirmed with the owners of https://github.com/opensearch-project/documentation-website that the beta site will remain up for the 1.0 GA launch and we can do a follow-up to change the links to point to the production website.

**Comment by kavilla** [comment]
Duplicate issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/645

**Comment by kavilla** [comment]
A production site for documentation exist at https://opensearch.org/docs/, so we should replace all instances related to https://docs-beta.opensearch.org/.

Warning, there are multiple locations where docs-beta was inserted. For example (but not limited to):
* https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/public/doc_links/doc_links_service.ts
* https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/vis_type_vega/public/components/vega_help_menu.tsx#L59

Another thing to mention is that the existing production URLs are *not* versioned. In the future they will need to be.

Associated engine issue: https://github.com/opensearch-project/OpenSearch/issues/956
Associated engine PR: https://github.com/opensearch-project/OpenSearch/pull/957

**Comment by kavilla** [comment]
Referenced in #645 

> Please get link-checker in! It would have immediately flagged these.

Sounds good, created an issue here: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/646

**Comment by kavilla** [comment]
Will keep this issue alive but will replace beta with prod url but keeping the references to this issue because we don't have actual replacements for certain links. we just direct users to a default page.

**Comment by kavilla** [comment]
Doc site is now version.

**Comment by tmarkley** [comment]
Addressed with #905 and #938. Will open a separate issue to track gaps in documentation.
