### ISSUE TITLE
[RELEASE] Release version 1.3.8

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#3352]
This is a component issue for __1.3.8__.
Coming from [opensearch-build#3012](https://github.com/opensearch-project/opensearch-build/issues/3012). Please follow the following checklist.
__Please refer to the DATES in that post__.

<details><summary>How to use this issue</summary>
<p>

## This Component Release Issue

This issue captures the state of the OpenSearch release, on component/plugin level; its assignee is responsible for driving the release. Please contact them or @mention them on this issue for help. 
Any release related work can be linked to this issue or added as comments to create visibility into the release status.

## Release Steps

There are several steps to the release process; these steps are completed as the whole component release and components that are behind present risk to the release. The component owner resolves the tasks in this issue and communicate with the overall release owner to make sure each component are moving along as expected.

Steps have completion dates for coordinating efforts between the components of a release; components can start as soon as they are ready far in advance of a future release. The most current set of dates is on the overall release issue linked at the top of this issue.

## The Overall Release Issue

Linked at the top of this issue, the overall release issue captures the state of the entire OpenSearch release including references to this issue, the release owner which is the assignee is responsible for communicating the release status broadly.  Please contact them or @mention them on that issue for help.

## What should I do if my plugin isn't making any changes?

If including changes in this release, increment the version on __1.x__ branch to __1.3.8__ for Min/Core, and __1.3.8.0__ for components. Otherwise, keep the version number unchanged for both.

</p>
</details>

### Preparation [Done] 

- [x] Assign this issue to a release owner
- [x] All the tasks in this issue have been reviewed by the release owner.
- [x] Create, update, triage and label all features and issues targeted for this release with `v1.3.8`.
- [x] All code changes for `1.3.8` are complete.

### Pre-Release
- [x] Update to the 1.3 release branch in the distribution manifest. (Updated by opensearch-build team: https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.8/opensearch-dashboards-1.3.8.yml)
- [x] Confirm that all changes for `1.3.8` have been merged.

### During Release Testing

- [x] Review any PRs in this repo during the release.

### Release

- [ ]  Complete release note.
- [x] Complete [documentation] if there's any changes (https://github.com/opensearch-project/documentation-website).
- [x] Verify all issued labeled for this release are closed or labelled for the next release.

### Post Release
- [ ] Add this repo to the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/) for the next developer iteration. (1.3.9) 
- [ ] Add this repo to the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/) of the next eventual security patch version. (1.3.9)
- [ ] Prepare for an eventual security fix development iteration by incrementing the version on the release branch to the next eventual patch version.
- [ ] [Suggest improvements](https://github.com/opensearch-project/opensearch-build/issues/new) to [this template](https://github.com/opensearch-project/opensearch-build/blob/main/meta/templates/releases/release_template.md).
- [ ] Conduct a retrospective, and publish its results.
- [ ] Update CHANGELOG.md. (Put everything released in a new section and titled with the release version. Create a new empty section for unreleased changes.)

**Comment by joshuarrrr** [comment]
@ananzh We should update this template with the post release changelog actions - everything in the release gets a new header that indicates the release and we create a new empty section for unreleased changes.

**Comment by ananzh** [comment]
> @ananzh We should update this template with the post release changelog actions - everything in the release gets a new header that indicates the release and we create a new empty section for unreleased changes.

@joshuarrrr I updated the release template with 1) add a release note in release stage and 2) update changelog in the post-release stage
