### ISSUE TITLE
[Feature Anywhere] Advanced settings to soft limit on number of anywhere saved objects on a single visualization

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/OpenSearch-Dashboards#3361]
**Is your feature request related to a problem? Please describe.**
Main issue: #2880 

When associating plugin resources to a visualization, we need to ensure we can limit the number of plugin resources to associate in order to prevent users from creating too many plugin resources and making the visualization too noisy without the user understanding the impact of doing this.

**Describe the solution you'd like**

Add new advanced settings to add a limit to this

**Comment by joshuarrrr** [comment]
What do you mean by a soft limit? Are we planning to warn with a toast but still allow more associations? We probably need some UX mocks to help illustrate what the experience will be link when a user hits or exceeds the limit.

**Comment by ohltyler** [comment]
Regarding implementing the limit on the UI side:

the saved object API calls can intercept CRUD operations for saved objects of `augment_vis` type. From there we can check the limit and accept/reject the request based on that. If at the limit, can return a user-friendly response.

Can use this response to update UI via potentially some callout in the menu and/or creation flows of the plugin resources

**Comment by ohltyler** [comment]
Added to the meta issue list

**Comment by ohltyler** [comment]
Will need to have the setting to globally turn the feature on/off as well.

**Comment by ohltyler** [comment]
Closing via #3961
