### ISSUE TITLE
[De-Angular] Dashboards over-all tracking issue

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#3365]
## Research Stage

As part of the De-Angular project, we aim to replace all the remaining angular code within the dashboard plugin. The goal of this task can be divided into three parts:

### Goal
* Understand the main usage of the dashboards plugin
* Investigate the remaining angular code that is left in the dashboards plugin
* Divide angular code replacing work into sub-tasks and smaller action items

### De-Angular Design
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4317

### Research

- [x] #3417 
- [x] #3903
- [x] #3904
- [x] #3905
- [x] #3982
- [x] #3907

## Implementation Stage 
- [x] #3999 
- [x] #4000 
- [x] #4002 
- [x] #4003 
- [x] #4004 
- [x] #4433
- [x] #4356
- [x] Make sure all tests are passing
   - [x] https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/733
 
## Enhancement
- [x] #4051 
- [ ] #4052 
- [ ] #4193
- [ ] #4349
- [ ] #4596
- [ ] #4603
- [ ] #4597
- [ ] #4604
- [ ] #4605
- [x] #4574
- [ ] #4606

**Comment by abbyhu2000** [comment]
> @ananzh @abbyhu2000 Note from oncall: Could you provide more context to this issue, as submitter or assignee?

Added more context to the issue description, will continue updating the issue after investigating.

**Comment by kavilla** [comment]
TODO:

Look into the duplicity check in panels: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4504#discussion_r1256272381

Look into the spreading in the diff check: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4504#discussion_r1256277407

Look into the panel being null: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4504#discussion_r1256282000

These questions were asked but need to be revisited. The embeddable plugin is built out very specifically and the state mgmt within the container embeddable (dashboards plugin) is doing extra work that was ported over. Best to not touch it as previous attempts to clean up certain parts of the code caused failure in edge feature tests.

**Comment by kavilla** [comment]
Re-opening to track fast follows.
