### ISSUE TITLE
[BUG] Not able to see the predefined-role in Opensearch Dashboard role list "opensearch_dashboards_read_only" and "opensearch_dashboards_user"

### ISSUE THREAD

**Issue by sooryaprakash99** [opensearch-project/OpenSearch-Dashboards#3391]
**Describe the bug**

I have installed the docker-compose file containing both OpenSearch and OpenSearch dashboard. I am able to login using the "admin" user. I have created the new custom tenant and create internal user. Now I want to map "opensearch_dashboards_user" and "opensearch_dashboards_read_only" rolt to that user, so that the user will not be able to edit the dashboard.

But In the roles list, I am not able to see these two roles

**To Reproduce**
1. Go to security/roles
2. search for the roles "opensearch_dashboards_user" and "opensearch_dashboards_read_only"
3. The roles not avaiable in the list

**Expected behavior**
Expected to be displayed in the roles list if it is a pre-defined role.

**OpenSearch Version**
v2.5.0

**Dashboards Version**
v2.5.0

**Plugins**

alertingDashboards@2.4.1.0
anomalyDetectionDashboards@2.4.1.0
customImportMapDashboards@2.4.1.0
ganttChartDashboards@2.4.1.0
indexManagementDashboards@2.4.1.0
notificationsDashboards@2.4.1.0
observabilityDashboards@2.4.1.0
queryWorkbenchDashboards@2.4.1.0
reportsDashboards@2.4.1.0
searchRelevanceDashboards@2.4.1.0
securityAnalyticsDashboards@2.4.1.0
securityDashboards@2.4.1.0

**Screenshots**
<img width="1727" alt="Screenshot 2023-02-06 at 11 25 59 AM" src="https://user-images.githubusercontent.com/14161939/217021527-7f55e222-2afa-48ff-9d0b-80b77bb06a9e.png">

**Host/Environment (please complete the following information):**
 - OS: Mac
 - Browser and version [e.g. 22]

**Additional context**

**Comment by zhongnansu** [comment]
Note from oncall: the roles mentioned are default roles, as indicated in our public [doc](https://opensearch.org/docs/2.0/security/access-control/users-roles/). And it's expected to be seen by admin in the role management page. Transferring to security-dashboards repo

**Comment by joshuarrrr** [comment]
I don't have permissions either. For these cases, we have to request a transfer from @opensearch-project/transfer-request 

@opensearch-project/transfer-request please transfer to https://github.com/opensearch-project/security-dashboards-plugin

**Comment by sooryaprakash99** [comment]
Could you please tell me if this is the issue and needs to be fixed in v2.5.0? Will this be tracked as part of this thread itself?

**Comment by zhongnansu** [comment]
@sooryaprakash99 
While waiting for the issue to be transferred. I think this might not be an issue. I assume you are following our documentation of the[ predefined roles](https://opensearch.org/docs/2.4/security/access-control/users-roles/#predefined-roles) and found the `opensearch_dashboards_read_only` role. But actually from the security plugin [codebase](https://github.com/opensearch-project/security/blob/75b6c3055f99ed8df0fdbeb10756a865cf3e6c76/config/roles.yml#L6), you can see it's named `kibana_read_only`. Similar with `opensearch_dashboards_user` --> `kibana_user`

So I believe there's a mistake in our documentation. Please use `kibana_user` and `kibana_read_only` to see if that helps.

**Comment by sooryaprakash99** [comment]
@zhongnansu I tried using the kibana_user and kibana_read_only role. I am able to see the dashboard and also edit button. On clicking the "Save" after modification, I am getting "Forbidden Error". But is there a way to hide the "Edit" button in the first place?

**Comment by zhongnansu** [comment]
> @zhongnansu I tried using the kibana_user and kibana_read_only role. I am able to see the dashboard and also edit button. On clicking the "Save" after modification, I am getting "Forbidden Error". But is there a way to hide the "Edit" button in the first place?

As far as I know, the edit button is consistent and not aware of the actual permission behind until the request being triggered. Tagging ui/ux to the issue for visibility.

**Comment by zhongnansu** [comment]
https://github.com/opensearch-project/documentation-website/pull/3426 fix is merged
