### ISSUE TITLE
[Multiple Datasource] Integrate SigV4 auth with test connection feature

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/OpenSearch-Dashboards#3418]
- [x] Refactor existing test connection code logic to improve code re-use. https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3058#discussion_r1107557476
- [x]  Integrate SigV4 auth with test connection feature

**Comment by joshuarrrr** [comment]
@zhongnansu can this be closed via #3058, or are there still tasks remaining?

**Comment by zhongnansu** [comment]
#3456 merged. Closing

**Comment by seraphjiang** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5936
