### ISSUE TITLE
AWS OpenSearch Dashboard

### ISSUE THREAD

**Issue by itzmesalim** [opensearch-project/OpenSearch-Dashboards#3425]
Dear All,

I'm new to AWS Opensearch Service.

While using Opensearch dashboard, unable to get proper result while searching for specific word, varchar, boolean values.

Any help in this would be appreciable.

**Comment by ananzh** [comment]
Hey @itzmesalim, could you be more specific? like could you paste some error msgs or screenshot? Meanwhile, do you have issues with the sample data?

**Comment by kavilla** [comment]
Please re-open if you are still experiencing issues. Thank you!
