### ISSUE TITLE
[BUG] Can't get index-pattern fields at dashboard filter for vis-builder

### ISSUE THREAD

**Issue by junqiu-lei** [opensearch-project/OpenSearch-Dashboards#3429]
**Describe the bug**

When a vis-builder visualization is added to dashboard, and user want to add some filter at dashboard top bar, the filter bar can’t get the fields from the index-patterns which the vis-builder used.

**To Reproduce**
1. Add all sample index-patterns at OSD
2. Create a new dashboard
3. Create new vis-builder from dashboard
4. In vis-builder creation page, select `opensearch_dashboards_sample_data_logs` index pattern and create a vis-builder vis
5. Saved and return back to dashboard
6. Add filter on dashboard top, select field
7. We can't see the fields options from `opensearch_dashboards_sample_data_logs`

**Expected behavior**
Get fields options at the filter bar for vis-builder index pattern source

**OpenSearch Version**
2.5.0 (OpenSearch playground env)
3.0.0 (Local dev env)

**Dashboards Version**
2.5.0 (OpenSearch playground env)
3.0.0 (Local dev env)

**Comment by ashwin-pc** [comment]
@junqiu-lei I am not able to reproduce the error that you are seeing. Am i missing something? I created a viz just like you mentioned and after adding it to the dashboard, i can see all the fields when i try adding a filter. See the screenshot below.

![Screenshot 2023-03-13 at 2 03 53 PM](https://user-images.githubusercontent.com/20453492/224831821-f387e69a-4ad7-4a69-b4fc-8335e1fcebd6.png)

**Comment by junqiu-lei** [comment]
Hi @ashwin-pc , I think the above screenshot filter's index pattern(opensearch_dashboards_sample_data_ecommerce) is OSD default index pattern whenever you create any dashboard you will have this one. You could try to use opensearch_dashboards_sample_data_flights or opensearch_dashboards_sample_data_logs to reproduce.

The below one is using index pattern from opensearch_dashboards_sample_data_logs, but at the top UI filter, it only show filter from opensearch_dashboards_sample_data_ecommerce(default)
![image](https://user-images.githubusercontent.com/90288540/224835133-b951cb34-baa0-412d-b073-ffdc138ed5a5.png)

**Comment by ashwin-pc** [comment]
Ah! thanks @junqiu-lei. The PR link was really useful :)
