### ISSUE TITLE
Discover plugin as embeddable

### ISSUE THREAD

**Issue by asteriscos** [opensearch-project/OpenSearch-Dashboards#3474]
Hi team,
the OpenSearch plugins we are developing would be greatly enhanced if we could use the **Discover** plugin view as an **embeddable**. 

The goal is to reuse the Discover plugin in other plugin's app views by defining the Discover plugin as a dependency and using the exposed methods in the **start** life cycle function:
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/discover/public/plugin.ts#L424

It would be very helpful to be able to set a **new filterManager instance** or have the possibility to set the Discover embeddable filters state by, for example, props.

![image](https://user-images.githubusercontent.com/9343732/220419846-71c616bf-4310-4135-abf0-a9d160c11319.png)

**Comment by ashwin-pc** [comment]
@asteriscos Thanks for opening the issue, can you give me a little more context about the problem your plugin is trying to solve?

**Comment by asteriscos** [comment]
Hi @ashwin-pc, thanks a lot for the quick response. It's very appreciated.

We are currently using our own implementation of the "Discover" view in our app. The main goal is to allow the user to drill down information using the same filters applied in the Dashboard view without redirecting the browser tab/window to the **OpenSearch Discover** plugin url.

### Here's how it's implemented:

![Peek 2023-02-27 12-48](https://user-images.githubusercontent.com/9343732/221557896-77a05a36-fa29-4060-824d-c15dbee558e7.gif)

We are enhancing the fields rendering with some custom call to actions, like opening a flyout with some more details. 

As you can imagine, we currently duplicating lots of code to achieve this. We think our use case ( _embedding the Discover plugin in our own views using a pre-set of filters_ ) can be used as an example to enhance the Discover plugin and expose methods to reuse the component in other plugins. 
We believe that this feature no only will be of great help to us, but to the whole community as well.

**Comment by ashwin-pc** [comment]
Thanks for the additional context @asteriscos. There are a few good ways for you to go about this with some of the existing abstractions. Here are some of my thoughts, but feel free to correct me if any of my assumptions of what your version of discover. To use the same fiters applied in the dashboard view you can use the `TopNavMenu` component exposed by the navigation service. Any value set by this component updates the filter manager state that can be accessed using the data plugins query service e.g. https://github.com/opensearch-project/OpenSearch-Dashboards/blob/f5ee06d99c7f3dcc9110468125b8e94e0daf6cc1/src/plugins/vis_builder/public/application/components/top_nav.tsx#L38. The query service also provides hooks and utility functions to manage the query and filter state in your own custom way. This way you can implement your feature right away without needing to allow discover to be exposed as an embeddable. Let me know if this helps solve your problem?

**Comment by asteriscos** [comment]
Thanks for the suggestions @ashwin-pc. 
We already managed to apply the same filters from our Dashboard to our implementation of Discover (the _Events_ tab in the GIF I shared).

What we intend to do, is to deprecate our Discover (_Events_ tab) duplicated code and start using the already existing Discover plugin because it has "98%" of the features we need to implement. 

**This issue has been created to propose creating an interface (eg. embeddable) for the Discover plugin**, so other plugins can make use of it by inserting it on other plugins views.

If you need further details o clarifications please don't hesitate to ask.

**Comment by ashwin-pc** [comment]
I see. So the dilemma I'm facing with this issue is that the discover codebase is mostly written in angular and we plan on deprecating angular from the codebase. How this will affect Discover is still undecided so adding this feature now to discover will involve a lot of sunk cost if discover changes significantly. I'd love to hear thoughts from some of the other maintainers on this issue though. @kavilla @joshuarrrr @AMoo-Miki, what are your thoughts about this?

**Comment by asteriscos** [comment]
Thanks a lot for your answer @ashwin-pc. 
Exposing the components used by the **_Discover_** plugin would be a great solution. That way we can not only implement them in our own **_"Discover"_**, but also embed some of them in other views. 
I believe this would also benefit deprecating angularJS progressively and make the features provided by Discover more flexible.

**Comment by ashwin-pc** [comment]
@asteriscos not sure if you are still tracking this but Discover is now a part of the data explorer framework. so what you want to do should be a lot simpler now since discover is essentially a view in the data explorer app. This means that anywhere else that you want to render discover, it should be possible if it can also render views like data explorer. Closing this in the meantime since this is something that we will likely not do given the new architecture. Feel free to reopen though if you still think this is a feature we need to add.
