### ISSUE TITLE
[UX] Receive and review events on time series visualizations

### ISSUE THREAD

**Issue by xeniatup** [opensearch-project/OpenSearch-Dashboards#3478]
**Is your feature request related to a problem? Please describe.**
This is a part of augmenting dashboard visualizations with plugin data.  

UX Meta issue: https://github.com/opensearch-project/ux/issues/66

### Describe the solution you'd like 

To provide an easy way for users to gain more insights with their existing visualizations, as well as help improve visibility and adoption of additional plugins, we propose to allow plugin resources (e.g., anomaly detectors, alerting monitors) to be associated with visualizations. Additionally, we propose to support overlaying the additional results (alerts triggered, anomalies occured) on top of the time series visualization charts to allow for their consumption within the context of the dashboards.

**User Stories:**

**Alerting**

- As  a user who has set up an alerting monitor on a visualization, I  want to be informed when alerts are triggered, so I can feel  confident in the system/service I’m supporting.
- As a user who is looking at an alert view on a given visualization time range, I want to be able to get a summary of what are the alerts are about, so I can decide if I want to dive deeper into what caused them in a detailed view

**Anomaly Detection**
- As a user who set up anomaly detection on a time series visualization, I want to be informed when an anomaly occurred, so I can investigate it using the context of a dashboard.
-  As a user who is looking at an anomaly view on a given visualization time range, I want to be able to get a summary of what anomalies fired, so I can decide if I want to dive deeper into what caused the anomalies in a detailed view

<img width="1155" alt="Screenshot 2023-02-21 at 10 25 06 AM" src="https://user-images.githubusercontent.com/105245012/220428508-969a7c63-d163-4a78-a381-5498a632faf4.png">

#### Review alerts

https://user-images.githubusercontent.com/105245012/224822816-288b75f9-65c1-4310-a4e1-c9be1c0c903c.mp4

#### Review anomalies

https://user-images.githubusercontent.com/105245012/224822834-a32071b6-6113-4a88-835b-757fd0d652b6.mp4

**Screen 1a.** User selects a visualization that has alerting monitors/anomaly detectors associated with it. Events, generated by the additional plugins are overlayed on the visualization and aligned with its timeline. On mouse over user gets a summary of the events.
<img width="1340" alt="Screenshot 2023-04-04 at 1 12 09 PM" src="https://user-images.githubusercontent.com/105245012/229909440-16cd3658-1262-4920-af73-1022cb36ac1a.png">

**Screen 2a:** User selects an events marker which opens a flyout `OuiFlyout` with more detailed breakdown of the _alerts_ for the visualization time range. To further investigate the alerts user selects a specific monitor.

<img width="1433" alt="Screenshot 2023-04-04 at 1 13 15 PM" src="https://user-images.githubusercontent.com/105245012/229909821-4c8856b7-4bbb-4aaa-aeae-15768fae4a8d.png">

**Screen 2b:** User selects an events marker which opens a flyout `OuiFlyout` with more detailed breakdown of the _anomalies_ for the visualization time range. To further investigate the anomalies user selects a specific detector. 

<img width="1433" alt="Screenshot 2023-04-04 at 1 13 30 PM" src="https://user-images.githubusercontent.com/105245012/229909858-baf07794-9796-4eb4-883f-88a20f9b9445.png">

**Screen 3.** Alternatively the flyout can be accessed from the visualization by selecting  "View events" from the context menu `OuiContextMenu`: 

<img width="1436" alt="Screenshot 2023-02-21 at 10 31 48 AM" src="https://user-images.githubusercontent.com/105245012/220431070-553c4757-3236-4a05-901f-68a526bc4c19.png">

### Error, warning, empty states:

**Screen 1b:** Some of the plugin resources failed to load (e.g. timeout, API fails) on the dashboard 
- Each visualization on the dashboard generates error message
- The toasts messages are stacked on the dashboard

<img width="1433" alt="Screenshot 2023-04-04 at 1 16 39 PM" src="https://user-images.githubusercontent.com/105245012/229910383-d8e8da10-2b14-453b-8df5-6e7e20724e8e.png">

**Screen 1c:** Selecting "See full error" opens a modal dialog with the full description of the errors. 

<img width="1433" alt="Screenshot 2023-04-04 at 1 15 59 PM" src="https://user-images.githubusercontent.com/105245012/229910233-1a182908-cff8-4a73-b652-19d54bac668f.png">

**Screen 1d:** User doesn't have permissions to read monitors/detectors associated with the visualizations by another user in the same tenant. Multiple toast messages (for multiple visualizations) are aggregated by plugin. 

<img width="1435" alt="Screenshot 2023-02-28 at 10 39 09 AM" src="https://user-images.githubusercontent.com/105245012/224941746-4b4b882a-635e-4165-89a7-780ba701c2c4.png">

**Screen 2c:**  Events flyout empty state. No alerting monitor or anomaly detectors are associated with a visualization.

<img width="1438" alt="Screenshot 2023-02-27 at 1 19 08 PM" src="https://user-images.githubusercontent.com/105245012/224825829-616b94fc-d2ec-492e-aa8f-476d0b85a44f.png">

**Screen 2d:** Plugin resources not loaded. Errors accessing the monitors/detectors/alerts due to no read access. 

<img width="1438" alt="Screenshot 2023-03-07 at 9 48 27 AM" src="https://user-images.githubusercontent.com/105245012/224826278-92b08f39-020d-4990-b4e1-0b829f1a3c6f.png">

**Comment by ahopp** [comment]
Thanks for opening @xeniatup - taking a look!

**Comment by xeniatup** [comment]
Done:
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/400
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2880
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/457

**Comment by xeniatup** [comment]
Done:
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/400
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2880
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/457
