### ISSUE TITLE
[BUG] unable to create "serial difference" in TSVB visualization

### ISSUE THREAD

**Issue by arunx2** [opensearch-project/OpenSearch-Dashboards#3498]
**Describe the bug**
I'm unable to create a pipeline aggregation with "SerialDiff" in TSVB visualization (Tried with both "timeseries" and "Table" mode). Due to a JS error, it leads to a blank screen.   

**To Reproduce**
1. Go to 'visualization'
2. Click on 'create new', select TSVB.
3. I use the sample ecommerce data. Choose "group by" terms and select "category.keyword"
4. Click on "Add Metric" and select "Serial difference"
6. See error as getting white page.

**Expected behavior**
It should allow me to select the parent aggregation with an option to select "lag"

**OpenSearch Version**
Please list the version of OpenSearch being used.
2.3
**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.
2.3
**Plugins**

Please list all plugins currently enabled.

**Screenshots**

https://user-images.githubusercontent.com/844111/221317717-8b1b575f-a526-40c1-a712-df4c5163963e.mp4

**Host/Environment (please complete the following information):**
 - OS: [e.g. iOS] Amazon OpenSearch Service
 - Browser and version [e.g. 22] Firefox 102.8.0esr (64-bit)

**Additional context**

Browser console output
`TypeError: docLinks.services is undefined
    SerialDiffAgg https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/plugin/visTypeTimeseries/visTypeTimeseries.chunk.2.js:1
    Go https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    ms https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    lu https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    su https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    Qs https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    Yi https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    unstable_runWithPriority https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:451
    $i https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    Yi https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    qi https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    R https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    Xt https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
[osd-ui-shared-deps.js:443:82386](https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js)
TypeError: docLinks.services is undefined
    SerialDiffAgg https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/plugin/visTypeTimeseries/visTypeTimeseries.chunk.2.js:1
    Go https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    ms https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    lu https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    su https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    Qs https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    Yi https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    unstable_runWithPriority https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:451
    $i https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    Yi https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    qi https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    R https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    Xt https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
[osd-ui-shared-deps.js:443:82386](https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js)
Uncaught TypeError: docLinks.services is undefined
    SerialDiffAgg https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/plugin/visTypeTimeseries/visTypeTimeseries.chunk.2.js:1
    Go https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    ms https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    lu https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    su https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    Qs https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    Yi https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    unstable_runWithPriority https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:451
    $i https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    Yi https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    qi https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    R https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443
    Xt https://search-playground-2ftaid4l2gqnvk2pbirluxblkq.us-east-1.es.amazonaws.com/_dashboards/4104/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:443`

**Comment by Joshsmith10013** [comment]
Still seeing this issue as of today

**Comment by joshuarrrr** [comment]
@Joshsmith10013 Can you provide more details, such as the version of OpenSearch and OpenSearch Dashboards you're using?

**Comment by Joshsmith10013** [comment]
OpensearchDashboards-1.3.2 with OpenSearch-1.3

**Comment by Joshsmith10013** [comment]
@joshuarrrr ack, thanks!!
