### ISSUE TITLE
[BUG] The order of the options loaded from `config/node.options` and `NODE_OPTIONS` differs between Windows and non-Windows

### ISSUE THREAD

**Issue by AMoo-Miki** [opensearch-project/OpenSearch-Dashboards#3502]
**Describe the bug**

_On Windows_
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/5af9a43b19c0438f647dfbbc387543d915b488a7/src/dev/build/tasks/bin/scripts/opensearch-dashboards.bat#L22-L33
On Windows, when `opensearch-dashboards.bat` is called, the options read in from `config/node.options` are appended to any `NODE_OPTIONS` that might have existed.

_On others_
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/5af9a43b19c0438f647dfbbc387543d915b488a7/src/dev/build/tasks/bin/scripts/opensearch-dashboards#L42-L46
When `opensearch-dashboards` is called, the options read in from `config/node.options` are passed in and then `NODE_OPTIONS` is appended.

The difference is that on Windows, `config/node.options` override `NODE_OPTIONS`.

**Comment by kavilla** [comment]
Removing untriaged label as by definition since it is opened by a maintainer.
