### ISSUE TITLE
Unable to change Timezone for date formatting

### ISSUE THREAD

**Issue by akschatu** [opensearch-project/OpenSearch-Dashboards#3513]
**Describe the bug**

Unable to update UI setting

Request failed with status code: 403

**To Reproduce**
1. Go to 'Stack Management'
2. Click on 'dateFormat.tz in Timezone for date formatting'
3. Select any other timezone other than 'UTC'

**Expected behavior**
Timezone should change
**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

<img width="712" alt="ss" src="https://user-images.githubusercontent.com/85286453/222632246-e2b6be0e-e805-44e3-a939-c652fbf80802.png">

**Host/Environment (please complete the following information):**
 - OS: Mac OSX
 - Browser and version Chrome 110 & Safari 16.3

**Additional context**
Response from api/opensearch-dashboards/settings:
```
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

**Comment by AMoo-Miki** [comment]
@akschatu in order to be able to reproduce and solve your problem, we would need all of the fields in the template to be filled. Without details, it would be nearly impossible to know where to look.

**Comment by akschatu** [comment]
Added

**Comment by kavilla** [comment]
Do you have the security plugin installed? If so which tenant are you trying to update and do you have the permissions to update the settings on that tenant. Settings requires write permissions to the `.kibana` system index.

**Comment by akschatu** [comment]
Hello,
I didn't realise that advanced settings affect all users in an org. Since, I'm not an admin, I was seeing 403 unauthorised.
I really wish there were custom settings for each user in an org, I'm currently in GMT+4 timezone and viewing logs in UTC is cumbersome.
Thanks for the quick response!
