### ISSUE TITLE
[BUG] Dev tool console autocomplete suggestion doesn't suggest index name

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/OpenSearch-Dashboards#3515]
**Describe the bug**

Auto-complete/suggest in dev_tool console has some issues. It doesn't pop up with suggestions for index name, field names, and there's no error message. Note that the endpoint suggestion does work, for example when you type in `_s`, it pops out candidates such as `_search`. But any suggestion requires dynamically querying OpenSearch is not working, for example index names suggestion.

- Related code and file:
  https://github.com/opensearch-project/OpenSearch-Dashboards/blob/e871aead83b42ffc19e1e25687e36bc2dcbc7562/src/plugins/console/public/lib/mappings/mappings.js#L238

**To Reproduce**
Go to https://playground.opensearch.org/app/dev_tools#/console and try

**Expected behavior**
![image](https://user-images.githubusercontent.com/32652829/222305599-cf650aaa-83fa-4973-98e0-fd789fdc8422.png)

**OpenSearch Version**
2.6

**Dashboards Version**
2.6

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by AMoo-Miki** [comment]
I just tried in on playground using Firefox 110 on macOS and it worked. Which browser and OS combo did you use?

**Comment by zhongnansu** [comment]
> I just tried in on playground using Firefox 110 on macOS and it worked. Which browser and OS combo did you use?

@AMoo-Miki Mac OS + Chrome. I updated the issue description. It's not that all suggestion failed. Only those require querying OpenSearch is not working.

**Comment by kavilla** [comment]
Removing `untriaged` since maintainer opened issue.

**Comment by AMoo-Miki** [comment]
With #3080, the `opensearch.send` changed and it simply doesn't get any `arguments` when called. As a result, `retrieveAutoCompleteInfo` -> `retrieveSettings` fails to get the settings.

**Comment by zhongnansu** [comment]
@joshuarrrr literally this is not related to multiple datasource, removing the tag

**Comment by joshuarrrr** [comment]
@zhongnansu I included it because it's on the checklist for #3577. Are you saying it isn't part of the GA scope? If so, let's remove it from that checklist. Should we also remove the `2.7.0` label here?

**Comment by zhongnansu** [comment]
@joshuarrrr Not part of GA, but it's good to have. Because t's a bug with current dev tool console, not related to any change I made. I am still trying to fix it for 2.7. Added to the meta issue for tracking purpose, but this should have lowest priority.

**Comment by zhongnansu** [comment]
@zengyan-amazon posted PR #3775 to address the issue

**Comment by jonkerw85** [comment]
I also encounter this issue after upgrading our test cluster from 2.3 to 2.5. And have had contact with AWS support about this issue. We run OS as a manage service on AWS.

I have to discuss this internally but this issue might block us from upgrading the other cluster's to 2.5. Our developers expect the auto suggestion to be working, otherwise they might think the indices might not exist.

**Comment by joshuarrrr** [comment]
@jonkerw85 The linked PR has the fix, which is targeted for the 2.7.0 release.

**Comment by zhongnansu** [comment]
fixed by #3775, closing
