### ISSUE TITLE
[Proposal] Remove timeline application plugin

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#3519]
# Background
The timeline application (not timeline visualization) was deprecated in ODFE 7.0 and OSD 1.0. Since then it is only achievable if add a config in `opensearch_dashboards.yml` to enable it. Currently, timeline application is still using angular framework, which has severe security concerns. Therefore, based on the research, we propose to remove timeline application.

# Proposal  
Below are the sub tasks.
### Functional tests 
* Understand timeline application functional tests. https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3584
* Re-write/modify the tests to allow the functional checks to work with timeline visualization. https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3593
### Clean out
*  clean legacy pipelines 
*  remove any advanced settings that are related to timeline application
*  clean timeline sheets saved object related contents
*  clean docs

**Comment by joshuarrrr** [comment]
The migration path already existed from `timeline` to `vis_type_timeline` at the time of the fork, and `timeline` is hidden from the navigation from default. What will be hard deprecated is the idea of timeline "sheets" because dashboards were chosen as a more cohesive experience (and I agree with that choice).

**Comment by seanneumann** [comment]
I'm very supportive of removing this deprecated plugin. I'm also ok with us releasing this in a minor version since it's been long deprecated.

**Comment by joshuarrrr** [comment]
OK, this proposal has been adopted, and we'll move forward with #3971
