### ISSUE TITLE
 opensearch Indexing operations stopped after deleting system indices

### ISSUE THREAD

**Issue by mAbdelfatah11** [opensearch-project/OpenSearch-Dashboards#3527]
accidentally i have deleted one of opensearch system indices which is ".kibana", that led to losing access to all indices logs in the "Discover" tab in kibana, and in order to recover such index, i have just upgraded opensearch domain to the latest version, in order to force the cluster nodes replacement.

therefore, i have recovered all system indices successfully and i could access other application indices through "Discover" tab But, unfortunately my applications became no longer able to log any new data in opensearch, and the indexing operations stopped with just the old data before the upgrade operation.

i have checked the indexing rate graph in aws console and noticed the drop of indexing rate to zero after the upgrade.

can anyone help me address the issue ?

![image](https://user-images.githubusercontent.com/89046475/222990490-4431a915-c9ae-495e-8166-6e7caff17dc1.png)

**Comment by kavilla** [comment]
Hello @mAbdelfatah11,

Sorry about that. Do you have index patterns re-set up? Upgrading will recreate the system indices for you but any existing information like index patterns, visualizations, and dashboards would be lost. Also, based on if you are upgrading from a legacy application to OpenSearch, this metric might be looking for a legacy metric but now utilizes a new metric.

However, I'd recommend contacting your cloud provider to recover your cluster and having them investigating further.

**Comment by mAbdelfatah11** [comment]
@kavilla thanks for your reply but the upgrade should at least retain access of our applications to the opensearch url.
after the last upgrade, none of our apps were able to add any logs, however i can reach kibana dashboard and the applications was working fine before
i can not reach my cloud provider in such technical issue as i have basic support plan.
