### ISSUE TITLE
[BUG] Dev tools show nothing.

### ISSUE THREAD

**Issue by MohamedEHJ** [opensearch-project/OpenSearch-Dashboards#3556]
**Describe the bug**

The page `Dev tools` does not show anything on Mozilla Firefox. It works well on Chrome.
![image](https://user-images.githubusercontent.com/46054862/223735783-189be5c3-01df-42a4-96fa-899bbd0daac9.png)

Firefox dev console return this:
![image](https://user-images.githubusercontent.com/46054862/223737217-feec8dd5-cade-4662-8325-313ada34debe.png)

I've tried to clear cache, restart browser, clean reinstall, switch tenant and.

**To Reproduce**
Go to dev tools on Firefox.

**Expected behavior**
Page should display a prompt and an output.

**OpenSearch Version**
OpenSearch 2.5.0

**Dashboards Version**
 2.5.0

**Host/Environment (please complete the following information):**
 - OS: WSL2 - Debian GNU/Linux 11 (bullseye) - Windows 10 21H2
 - Firefox 110.0.1

**Comment by kavilla** [comment]
Hello! Could provide your extensions on your browser as well?

**Comment by MohamedEHJ** [comment]
Hello Kavilla, 

I feel like it's working today so i'm going to close the issue.

However here is the list of installed extensions if someone face the same problem:
- uBlock
- copyfish ocr
- Dark reader
- Simple translate

Thanks!
