### ISSUE TITLE
[BUG] React Developer Tools doesn't work in Mozila Firefox browser

### ISSUE THREAD

**Issue by DaniilShest** [opensearch-project/OpenSearch-Dashboards#3572]
A plugin "React Developer Tools" doesn't work in Mozila Firefox browser.

OpenSearch Dashboards 2.6.0

![IMG_20230309_231320_174.png](https://user-images.githubusercontent.com/98505252/224104498-8f50e9fe-6744-4920-b14d-b1eaec567a82.png)

 - OS: Windows 11
 - Browser and version: Mozila Firefox Developer Edition 111.0b8

**Comment by joshuarrrr** [comment]
@DaniilShest The React Developer Tools work in Firefox on my Mac, and I don't see any reason that it shouldn't work on Windows:

https://user-images.githubusercontent.com/1679762/225168261-33e9f926-265f-4b98-9013-343f6f46c34b.mov

I can confirm that the `/home#` route can be debugged/profiled via React Developer Tools, so you may want to look into your browser extension settings or reinstall, as it's more likely an issue with your browser and extensions than the OpenSearch Dashboards development server.
