### ISSUE TITLE
Ability to access the timepicker values in a script

### ISSUE THREAD

**Issue by brianreinhold** [opensearch-project/OpenSearch-Dashboards#3574]
**Is your feature request related to a problem? Please describe.**
It is to solve a problem or perform a task that cannot otherwise be done.

Unable to access the user-entered time picker values to perform calculations like 'percent of time a gateway lost cellular connectivity'
**Describe the solution you'd like**
An option to obtain the start and end range times of the timepicker.

I want to be able to calculate the percent of time a gateway was down, lost connectivity, etc. during the user selected period. It might be the case no event was received during the user selected period in which case the answer would be 0%.

**Describe alternatives you've considered**
There are none that could work unless I send events at a very regular frequency just to simulate time ticks. Very expensive and wasteful as there is no other reason to send such events

Could not think of any because the result depends upon user entered information which is impossible to know.

**Additional context**
None.

**Comment by abbyhu2000** [comment]
Thanks for opening!

Could you elaborate more on what problem you are trying to solve? If possible, could you add some screenshots? 

And according to the description above, are you asking to get the user entered information of the time picker from the UI?

**Comment by brianreinhold** [comment]
After a few days of power/connectivity issues and digging out from the storm, the problem I am trying to solve is pretty straight forward.
The data documents record how long a gateway in the field lost cellular connectivity. The user wants to know the percentage of time the gateway lost connectivity in January. So he enters the desired period in the time picker. I want to create a visualization of all the gateways in the field showing the percentage of time each was down during that user-selected period. I cannot do this without knowing the range of time specified by the user in the time picker.

**Comment by abbyhu2000** [comment]
@brianreinhold Thank you for the info! Close this issue since this is a duplicate, will track this issue in #3631.
