### ISSUE TITLE
[Multiple Datasource]Remove experiment feature banner. 

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/OpenSearch-Dashboards#3579]
- [ ] Remove experiment feature banner
![image](https://user-images.githubusercontent.com/32652829/225088882-83d1171c-0f04-4cd1-b097-96852443e7c6.png)

- [x] ~~Currently to enable the feature, user needs to set `data_source.enabled: false` to `data_source.enabled: true` and save the `opensearch-dashboards.yml` -> restart opensearch dashboards. [ reference](https://opensearch.org/docs/2.6/dashboards/discover/multi-data-sources/#modifying-the-multiple-data-sources-settings)] Wonder if in GA, we should turn it on by default @ahopp @zengyan-amazon @seraphjiang~~

**Comment by kavilla** [comment]
Tagging @dagneyb as well.

**Comment by zhongnansu** [comment]
cc @ahopp

**Comment by ahopp** [comment]
I'm aligned with this change - I say ship it.

**Comment by seraphjiang** [comment]
> we should turn it on by default

after GA, it should still disable by default. we don't want to impact existing customer behavior in setup/upgrade.

we might consider enable by default after 3.0
