### ISSUE TITLE
[BUG] link to DQL help page is broken from discover page

### ISSUE THREAD

**Issue by anirudha** [opensearch-project/OpenSearch-Dashboards#358]
**Describe the bug**

Link to DQL help is broken from discover page. 
it currently links out to 

https://www.opensearch.org/guide/en/kibana/main/kuery-query.html
<img width="950" alt="Screen Shot 2021-05-14 at 12 03 38 PM" src="https://user-images.githubusercontent.com/19362/118317170-927d6c80-b4ac-11eb-980c-6c80444cfc1d.png">

**Comment by kavilla** [comment]
Looks like a duplicate of: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/335

**Comment by kavilla** [comment]
Will close, because this will be handled in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/335
