### ISSUE TITLE
[BUG] Unable to edit existing Anomality Detectors after changing Authentication to SAML

### ISSUE THREAD

**Issue by lehmat** [opensearch-project/OpenSearch-Dashboards#3586]
**Describe the bug**
Changing authentication from internal users to SAML authentication causes existing (created with internal user, that is now deleted) anomality detectors to be not editable with administrator access.

Details:

PUT /_dashboards/api/alerting/monitors/id-of-detector?ifSeqNo=1&ifPrimaryTerm=59
-> Response status code 200
-> Response content: {"ok":false,"resp":"[alerting_exception] User has no available detectors"}
 

**To Reproduce**
1. Change authentication method to SAML (Azure in this case), Log in with new user with pre-existing anomality detectors
2. Click on Anomaly detection on sidebar
3. Click on Detectors
4. Click on one of Detectors created
5. Anomality overview click on Edit alert settings
6. Click on Edit
7. Do not make any changes and click on Update at the bottom

**Expected behavior**
Should be able to successfully edit

**Plugins**
SAML Authentication from Opensearch AWS console enabled

**Host/Environment (please complete the following information):**
 - OS: Windows 11, Edge
 - Version 2.3 (Latest on AWS)

**Comment by kavilla** [comment]
Issue moved to [opensearch-project/security-dashboards-plugin #1377](https://github.com/opensearch-project/security-dashboards-plugin/issues/1377) via [**Zenhub**](https://www.zenhub.com/)
