### ISSUE TITLE
[BUG] Maps includes broken links to Kibana

### ISSUE THREAD

**Issue by asfoorial** [opensearch-project/OpenSearch-Dashboards#359]
As shown in the screenshot. When creating a Visualization, it mentions "To get Maps, upgrade to the default distribution of OpenSearch"  with a link pointing to https://opensearch.org/downloads/kibana

Also, zooming levels is still limited.

![20210518_144203](https://user-images.githubusercontent.com/5801922/118678661-e0c0a180-b805-11eb-9d8f-27513f1507c5.jpg)

**Comment by kavilla** [comment]
Hello @asfoorial,

> As shown in the screenshot. When creating a Visualization, it mentions "To get Maps, upgrade to the default distribution of OpenSearch" with a link pointing to https://opensearch.org/downloads/kibana

Great catch! We will be removing the migration box in whole since that shouldn't be there. 

> Also, zooming levels is still limited.

For this, could you create another issue using the BUG template with the recreation steps and expected outcome?

Appreciate it!

**Comment by ahopp** [comment]
@kavilla It looks like there is also a reference to 8.0 that isn't relevant to our versioning.
