### ISSUE TITLE
Launch OpenSearch Dashboards 1.0

### ISSUE THREAD

**Issue by seanneumann** [opensearch-project/OpenSearch-Dashboards#360]
Launch OpenSearch Dashboard 1.0, a community-driven, open source fork of Kibana 7.10.2. OpenSearch is built to ensure customers continue to have a secure, high-quality, fully open source search and analytics suite with a rich roadmap of new and innovative functionality.

**Comment by tmarkley** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/releases/tag/1.0.0
