### ISSUE TITLE
[BUG] Limited zoom levels in Maps

### ISSUE THREAD

**Issue by asfoorial** [opensearch-project/OpenSearch-Dashboards#361]
**Describe the bug**

Maps zoom level is limited. It stops at certain level and asks for upgrading to unlock deeper zoom levels.

**Expected behavior**
1. Deepest zoom level should be equivalent to that of OpenStreetMaps. Space Needle can be a test case here.
2. No upgrade message should show up.

**OpenSearch Version**
1.0.0 beta-1.

**Dashboards Version**
1.0.0 beta-1

**Comment by JacobBrandt** [comment]
@asfoorial Wait this OpenSearch Dashboard repo asks for upgrading to unlock deeper zoom levels?  Upgrade to what Kibana?  

Ew, I went to look into this a little deeper and AWS is being hardcoded into the baseline.  WTH?
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/fb2f79308ff13a8e647ab073fd991d5954ba30b5/src/plugins/maps_legacy/public/map/opensearch_dashboards_map.js#L614

**Comment by kavilla** [comment]
> No upgrade message should show up.

Great catch, the toast should not being showing and there is no up-sell, just left over messages before the fork.

> Deepest zoom level should be equivalent to that of OpenStreetMaps. Space Needle can be a test case here.

Will look into this and verify that this isn't a limitation on the service.

**Comment by kavilla** [comment]
Still haven't been able to reach someone about the service we are using. A brief message was the limitation is zoom level 8 from the service, if that is the case I will see about timelines when we can have parity of OpenStreetMaps.

**Comment by kavilla** [comment]
Sorry about the delay in response there is a limitation in zoom. This is being deferred to the team working on the mapping service we are using.

**Comment by w0otness** [comment]
Is there any movement of this issue?

**Comment by kavilla** [comment]
@junqiu-lei, would you be able to provide some insight on this?

**Comment by junqiu-lei** [comment]
Hi there, from OpenSearch maps tiles server side https://tiles.maps.opensearch.org/tiles/{z}/{x}/{y}.png, currently we are supporting zoom 0 to zoom 10, we have also created a feature issue for [supporting for more zoom levels](https://github.com/opensearch-project/maps/issues/4) on maps repository. Thanks!
