### ISSUE TITLE
[BUG] OpenSearch Dashboards GUI shows "503 service unavailable"

### ISSUE THREAD

**Issue by talkraghu** [opensearch-project/OpenSearch-Dashboards#3611]
**Describe the bug**
OpenSearch Dashboards GUI shows "503 service unavailable"

The  opensearch-dashboards container logs show the below logs. The logs indicate problem with successful creation of .kibana_1.

The workaround would be to exec'ing to opensearch container and deleting the  .kibana_1 indice and restarting the opensearch-dashboards pod.  This workaround is not good to apply all the time as customers would not like any manual workarounds.
This problem happens often even with opensearch and opensearch-dashboard version 2.6.0

Are there any extra configs that needs to be applied to overcome the issue ?

```

{"type":"log","@timestamp":"2023-03-14T17:39:38Z","tags":["info","savedobjects-service"],"pid":1,"message":"Waiting until all OpenSearch nodes are compatible with OpenSearch Dashboards before starting saved objects migrations..."}
{"type":"log","@timestamp":"2023-03-14T17:39:38Z","tags":["info","savedobjects-service"],"pid":1,"message":"Starting saved objects migrations"}
{"type":"log","@timestamp":"2023-03-14T17:39:38Z","tags":["info","savedobjects-service"],"pid":1,"message":"Creating index .kibana_1."}
{"type":"log","@timestamp":"2023-03-14T17:40:08Z","tags":["error","opensearch","data"],"pid":1,"message":"[TimeoutError]: Request timed out"}
{"type":"log","@timestamp":"2023-03-14T17:40:08Z","tags":["warning","savedobjects-service"],"pid":1,"message":"Unable to connect to OpenSearch. Error: Request timed out"}
{"type":"log","@timestamp":"2023-03-14T17:40:11Z","tags":["error","opensearch","data"],"pid":1,"message":"[resource_already_exists_exception]: index [.kibana_1/CP2kXCCWTauw_mMdlb9nXg] already exists"}
{"type":"log","@timestamp":"2023-03-14T17:40:11Z","tags":["warning","savedobjects-service"],"pid":1,"message":"Unable to connect to OpenSearch. Error: resource_already_exists_exception: [resource_already_exists_exception] Reason: index [.kibana_1/CP2kXCCWTauw_mMdlb9nXg] already exists"}
{"type":"log","@timestamp":"2023-03-14T17:40:11Z","tags":["warning","savedobjects-service"],"pid":1,"message":"Another OpenSearch Dashboards instance appears to be migrating the index. Waiting for that migration to complete. If no other OpenSearch Dashboards instance is attempting migrations, you can get past this message by deleting index .kibana_1 and restarting OpenSearchDashboards."}

```

**To Reproduce**
Install opensearch and opensearch-dashboards with version 2.6.0 using public helm charts.

**Expected behavior**
The opensearch-dashboard to start well without errors

**OpenSearch Version**
2.6.0

**Dashboards Version**
2.6.0

**Comment by kavilla** [comment]
Hello @talkraghu,

OpenSearch Dashboards tries to create the system index on start up. It looks for anything of the format `.kibana_*` and attempts to migrate it. The `/` before `CP2kXCCWTauw_mMdlb9nXg` does not prevent the code from not finding that index and then OpenSearch Dashboards thinks it found another `.kibana_1`. I'm not aware where the `/CP2kXCCWTauw_mMdlb9nXg` is coming from. Is that a potential tenant? Will migrate to helm charts to see if they are adding this.

**Comment by kavilla** [comment]
Issue moved to [opensearch-project/helm-charts #404](https://github.com/opensearch-project/helm-charts/issues/404) via [**Zenhub**](https://www.zenhub.com/)

**Comment by talkraghu** [comment]
We don't have multitenancy feature enabled at our deployment

```
    opensearch_security.multitenancy.enabled: false
    opensearch_security.readonly_mode.roles: ["kibana_read_only"]
    opensearch_security.cookie.secure: true
```
