### ISSUE TITLE
[Dashboards List Integration] Create button now requires 2 clicks to create dashboard

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#3621]
Origin:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3090/

When creating a dashboard with the new integration defaults to making the create button a drop down list. This makes creating a dashboard a 2 click process.

### Enhancement

* There should be a one click workflow for dashboards incase there is any workflow attached with the previous existing functionality.

**Comment by pjfitzgibbons** [comment]
Ack

**Comment by pjfitzgibbons** [comment]
@kavilla If I understand correctly, the actual concern is whether the changed HTML will break customer-written browser-automation scrips.   Dashboard-Create is a low-activity interaction, so making it 2-click when there are integrations is not a super important affect IMO.

**Comment by anirudha** [comment]
may be we add something like [this](https://th.bing.com/th/id/R.c0f31c803551a7183c817f4e00d35d34?rik=o0Ze6LmaEcG81A&riu=http%3a%2f%2fwebuikits.com%2fwp-content%2fuploads%2f2012%2f10%2fMultipurpose-Dropdown-Button.jpg&ehk=uoa5ciQl4Zd%2f6vjzXyzKJRsQR0CrlPWn%2bBKv%2bq4Fx0Y%3d&risl=&pid=ImgRaw&r=0)

**Comment by pjfitzgibbons** [comment]
@kgcreative @dagneyb I like @anirudha suggestion.   It preserves the "default" create (Dashboard/Dashboard), and offers a drop-arrow for additional options?
![ButtonDropArrow](https://user-images.githubusercontent.com/11318/225986612-ddb04668-a705-4985-a0ad-2ac709f7e427.jpeg)

**Comment by kgcreative** [comment]
Tagging @KrooshalUX. Let's talk introducing a "split button" component to OUI for this behavior.  Another example is the github "Close with comment" button that's right below the comment box.

<img width="330" alt="Screen Shot 2023-03-17 at 12 15 41 PM" src="https://user-images.githubusercontent.com/3443142/225998922-b43333ee-cf81-4ab9-8d74-34aab5e47ad2.png">

**Comment by KrooshalUX** [comment]
@kgcreative Thanks for tagging me in. I would prefer to go with the boxesVertical icon treatment as its used commonly in tables and on dashboard visualizations to trigger a "menu"

**Comment by KrooshalUX** [comment]
@kgcreative  Thanks for tagging me in. 

A sort of brain-dump which may not be quite directional yet... 

- I don't quite see an issue with it being 2 clicks, here is why: given all of the cool functionality that is coming to dashboards core via our plug-ins/extensions/integrations (appologies I dont have a single word to refer to all of the things existing outside of OSD), I think the notion of "default" might be ... outdated. We have an increasing discoverability challenge for when a plugin/extension/integration gives Dashboards Core new functionality. I am not _yet_ aligned to providing a button that gives you an OSD Dashboard and a separate way to access the plugin/extensions/integrations contributed dashboards. With this split button suggestion, it reflects more of our organizational divide more than what a user may expect (one button that gives me a menu to show me all my options). 

- Additionally - I think the current OUI split button pattern is very confusing - I have no idea what to press - and this does need to get a new treatment in OUI. I think we can prioritize a change, but I will need to meet with the team to strategize further. 

- Currently the majority of menus are triggered by the `boxesVertical` - so for alignment to trigger `OuiContextMenu` we should be using that, though I am also partial to `arrowDown` when its in combination with a button, so I am a bit more aligned to the solution @pjfitzgibbons made in his original issue. 

I would like to hear more thoughts on where I am going with the discoverability issue, primarily.

**Comment by kgcreative** [comment]
@pjfitzgibbons & @kavilla -- please let us know what makes sense to you guys, and then we can make a final determination

**Comment by canascar** [comment]
We have begun working on designing the split button component.

Definition: A split button is a button with two components: a label and an arrow; clicking on the label selects a default action, and clicking on the arrow opens up a list of other possible actions. ([Reference](https://www.nngroup.com/articles/split-buttons/))

**There are some open questions related to functionality:**
1. Navigation on selection of option without button click, or single click as opposed to 2 click function. (Possibly not recommended unless action can be cancelled or delayed.)
2. Using only an icon for the action button (Possibly not recommended or used sparingly unless icon clearly defines the action.)
3. Popover v Dropdown container - most examples opt for a dropdown container as opposed to a popover container.

![splitbutton](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/111922174/95f5dd3e-7946-4b6b-b210-ba35e32055fb)

More design updates coming soon.

**Comment by canascar** [comment]
I discussed with @pjfitzgibbons about some design issues. We both agreed that a dropdown works best than a popover on click of the expanding secondary (split options) button. This is also consistent throughout most split button/dropdown patterns I've observed - Cloudscape, Adobe, Zendesk, Github - and it will allow us to reuse the existing component SuperSelect which we'd like to use for the selection mechanism.

We also think that the dropdown can be either left/right aligned and defined as a prop. We can also consider making this dependent on where the button and the dropdown appear in regards to the browser window.

<img width="464" alt="Screenshot 2023-12-14 at 1 28 39 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/111922174/ce356727-317e-4142-a639-7834658b7edb">
<img width="459" alt="Screenshot 2023-12-14 at 1 28 23 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/111922174/2cf95601-cabe-48c5-a551-c61bdfef2838">
<img width="515" alt="Screenshot 2023-12-14 at 1 28 13 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/111922174/1ebaa9fc-7626-4a2c-bf05-46dd77c1ce96">

Reference:
https://oui.opensearch.org/1.3/#/forms/super-select

**Anatomy**
A split button consists of:
1. A primary action button containing a label and an optional left icon
2. A secondary action button that expands a dropdown with options to select from that will impact or modify the primary action to be taken.
3. These buttons are sep

<img width="906" alt="Screenshot 2023-12-14 at 2 11 58 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/111922174/37cdf437-d5d9-43da-a409-f6e83e0cc970">
arated by a 1 pixel border

Primary action button width will be determined by the label (and icon and/or combination) consistent with our existing button pattern. Secondary button width should be proportional and use only an icon to denote action of dropdown expansion (in most cases, a down arrow icon but we can allow customizing if necessary.)

We can have split buttons for all our button states and types:
- Filled
- Outline
- Filled small
- Outline small

<img width="823" alt="Screenshot 2023-12-14 at 2 12 26 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/111922174/a61be12c-851c-42c3-adbc-0baa0d4d40fe">

**As far as things to consider for UX**
1. Use of Icon only for primary action button - we can have this capability but should write guidelines and warnings around using only an icon for an action. We can also set constraints for when it may be appropriate to use only an icon for such cases.
2. Number of options in the dropdown - we should have a limit for number of items in a split button so it does not become overwhelming. If there is a need for many options, perhaps a component like a dropdown select field is more appropriate in these cases.
3. Option Selection can **A.** Change the label and contents of the primary action button (ex. Another action is selected and swapped as the primary action.) **B.** Label and contents remain static but the type of action is modified depending on what is selected (ex. An execution of an action but executed with varying parameters.)
4. Action is triggered by clicking on the primary action button. 

**Prototype**
https://www.figma.com/proto/m3JvQ6e0pQztyywt8xdJdc/Split-button?page-id=41%3A2795&type=design&node-id=41-2796&viewport=386%2C464%2C0.29&t=b7xU3TuGlmyPR2nR-1&scaling=min-zoom&mode=design

@kgcreative, @shanilpa for visibility

**Comment by kgcreative** [comment]
> reuse the existing component SuperSelect which we'd like to use for the selection mechanism.

Also consider popover attached inside an input element(reference: https://oui.opensearch.org/1.3/#/layout/popover%23popover-attached-to-input-element) - which super select may be using under the hood

**Comment by canascar** [comment]
We are considering Super Select to be able to use the more complex option that allows for title/description parameters, but yes will look at all reusable options currently available.
https://oui.opensearch.org/1.3/#/forms/super-select#more-complex

**Comment by pjfitzgibbons** [comment]
> Also consider popover attached inside an input element

@canascar and I discussed popover vs select.  Our feeling was that the connect-arrow of popover feels like it interrupts the graphical continuity of a drop-down.

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/11318/c38e13d6-512a-41da-b204-05b041d30069)

If we must consider this as an option, it will add a possilby considerable amount to the code, since the useage of pop-up is different from the plain super-select.   Maybe we can plan for this option for a next phase?

@kgcreative

**Comment by kgcreative** [comment]
So what i'm calling out is that [Popover attached to input](https://oui.opensearch.org/1.3/#/layout/popover%23popover-attached-to-input-element) is what super select uses under the hood (https://github.com/opensearch-project/oui/blob/main/src/components/form/super_select/super_select.tsx#L321C15-L321C15) to render the context menu attached to the control

**Comment by pjfitzgibbons** [comment]
I see now.  I'll keep that in mind and list it in the alternatives
