### ISSUE TITLE
[BUG] SQL and PPL Documentation Links Not Correct

### ISSUE THREAD

**Issue by ahopp** [opensearch-project/OpenSearch-Dashboards#364]
**Describe the bug**
In Query Workbench the SQL and PPL docs links are still pointed to ODFE docs. Specifically, they are pointed to;

https://opendistro.github.io/for-elasticsearch-docs/docs/sql/ rather than https://docs-beta.opensearch.org/docs/sql/
https://opendistro.github.io/for-elasticsearch-docs/docs/ppl/ rather than https://docs-beta.opensearch.org/docs/ppl/

**To Reproduce**
1. Go to 'Query Workbench'
2. Click on 'SQL documentation' or 'PPL documentation'

**Expected behavior**
Expect to land on https://docs-beta.opensearch.org/docs/sql/ or https://docs-beta.opensearch.org/docs/ppl/

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/9532728/119103035-90953b00-b9cf-11eb-8847-2c833c3ab557.png)

**Additional context**
None.

**Comment by tmarkley** [comment]
Related to #335

**Comment by kavilla** [comment]
This was SQL/PPL Workbench plugin issue, looking at their repo looks to have been fixed https://github.com/opensearch-project/sql/commit/e4692ba75889800dd055680c4c0f2bb35268be17
