### ISSUE TITLE
[BUG] custom error not display correctly after dev tool console refactoring

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#3645]
**Describe the bug**
The error is caused by #3544 

**To Reproduce**
If search for an index pattern that does not exist, the console shows a 502 bad gateway error:
<img width="862" alt="Screen Shot 2023-03-21 at 1 18 18 PM" src="https://user-images.githubusercontent.com/43937633/226735588-610e7e9f-9c35-4943-a295-1743da26ffc0.png">

It should show a 404 not found custom error:
<img width="862" alt="Screen Shot 2023-03-21 at 1 18 57 PM" src="https://user-images.githubusercontent.com/43937633/226735551-b0795940-399f-40ec-8cf6-a1ec58251a4d.png">

**Comment by joshuarrrr** [comment]
It sounds like this is a blocker for the feature in 2.7.0

**Comment by AMoo-Miki** [comment]
> @abbyhu2000 The issue is with a typo. it's supposed to be `headers` not `header`. This is leading `isResponseErrorFlag` to always be false, and not forwarding the error message to response. I'll fix it in next PR
> 
> https://github.com/opensearch-project/OpenSearch-Dashboards/blob/de0634495ebace79453b50421e8d147104a7b562/src/plugins/console/server/routes/api/console/proxy/create_handler.ts#L140

Why do we care if the response has any headers?

**Comment by zhongnansu** [comment]
> > @abbyhu2000 The issue is with a typo. it's supposed to be `headers` not `header`. This is leading `isResponseErrorFlag` to always be false, and not forwarding the error message to response. I'll fix it in next PR
> > https://github.com/opensearch-project/OpenSearch-Dashboards/blob/de0634495ebace79453b50421e8d147104a7b562/src/plugins/console/server/routes/api/console/proxy/create_handler.ts#L140
> 
> Why do we care if the response has any headers?

to validate the error is a response error

**Comment by zhongnansu** [comment]
I've posted PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3652 to fix the problem. Please take a look
@abbyhu2000 @joshuarrrr @AMoo-Miki
