### ISSUE TITLE
[Tech Debt] Remove dependency on 'TinyMath'

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#3655]
Tinymath is a lightweight and fast JavaScript library for performing mathematical operations in JavaScript. It provides a range of mathematical functions for working with numbers, such as addition, subtraction, multiplication, division, and more. 

However, we should replace tinymath since it is abandoned 4 years ago and it contributes to the CSP-related vulnerability of OSD. 

Current dependency: `"tinymath": "1.2.1"`

Subtasks:
- [ ] #3656
- [ ] #3657

**Comment by ananzh** [comment]
Could add another sub task:
 

- [ ] Clean out other Tinymath usage
* clean out in packages/osd-optimizer/src/worker/webpack.config.ts
* clean out yarn.lock and package.json. check on documents and comments

**Comment by abbyhu2000** [comment]
@ltwmori Thank you for the reply! We have created a research sub task of this meta issue, and the research sub-task asks to research the usage of TinyMath library in the repo and then propose the best option for its replacement based on the usage. Do you want to pick up that task and document your research there? Here is the link #3656 Thanks!
