### ISSUE TITLE
[BUG] .gitignore update

### ISSUE THREAD

**Issue by Aigerim-ai** [opensearch-project/OpenSearch-Dashboards#3667]
**Describe the bug**
adding opensearch-dashboards-docker-dev  into .gitignore
I find it inconvenient to delete opensearch-dashboards-docker-dev( for docker users ) every time I want to make PRI
believe we need to add the path to opensearch-dashboards-docker-dev into our .gitignore file, which is created during our  app installation?

**Host/Environment (please complete the following information):**
 - OS: [e.g. iOS] MacOS

**Comment by curq** [comment]
Hi, I got a question about this issue,

Why not just have it in a separate directory outside of the main one? I'm also on MacOS and it is how I do it. Or is there any specific reason why we should have it within the same directory?

**Comment by joshuarrrr** [comment]
@Aigerim-ai I agree this was something we missed when we added the docker-dev instructions. Will you make a PR to update the `.gitignore`?

**Comment by joshuarrrr** [comment]
cc @abbyhu2000

**Comment by Aigerim-ai** [comment]
Okay I will do it
