### ISSUE TITLE
[Vis Builder] New visualization icon doesn't look consistent in dark mode

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#3691]
<img width="903" alt="Screen Shot 2023-03-24 at 5 10 07 PM" src="https://user-images.githubusercontent.com/1679762/227665691-a8ff5524-bbf2-408e-bc59-d61611bde9ee.png">

**Comment by joshuarrrr** [comment]
CC @ashwin-pc @KrooshalUX

**Comment by frost017** [comment]
Hi!
I think I can take a look at this. Where is this file located?

**Comment by ashwin-pc** [comment]
Thanks for offering @frost017 but this is dependent on https://github.com/opensearch-project/oui/issues/613 and tied to something i'm already working. There are plenty of other good issues in the repository though. dont hesitate to pick any other the others marked with the `good first issue` or `needs help` label 😄

**Comment by frost017** [comment]
Hi!
Oh ok, excuse me, I didn't know about it. Thanks for advice!

**Comment by KrooshalUX** [comment]
a few things here :
- it looks like the SVG was exported with a white fill
- Either the SVG was not cleaned and/or because the icon isnt being served up via OUI, I dont think the color utilities are swapping out the color properties correctly. 

When we provide a new icon and serve it up with OUI, this issue should be resolved ;)

**Comment by joshuarrrr** [comment]
Yep - one other small detail that's hard to see from this particular screenshot - all the other visualization icons seem to have a uniform line width.

**Comment by KrooshalUX** [comment]
We are starting over from scratch, so that factor will also be eliminated in this new version.

**Comment by joshuarrrr** [comment]
Oh, perfect!

**Comment by joshuarrrr** [comment]
This change didn't make it in OUI 1.1, so it won't be part of OpenSearch Dashboards 2.7

**Comment by joshuarrrr** [comment]
@KrooshalUX Just reviving this discussion, since it's definitely something we'll want for 2.10

**Comment by KrooshalUX** [comment]
@joshuarrrr this was corrected in 1.1 and the visBuilder icon was placed into the OUI Icon Library 
![Screen Shot 2023-06-29 at 11 55 43 AM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105819041/7b23e2f9-e8a8-449b-ab11-ed4b1f727b9f)
