### ISSUE TITLE
Update OpenSearch logos site-wide with new branding

### ISSUE THREAD

**Issue by tmarkley** [opensearch-project/OpenSearch-Dashboards#370]
**Is your feature request related to a problem? Please describe.**

OpenSearch Dashboards currently uses placeholder logos (e.g. "heatmap") that were set in the initial forking/renaming project: #37

**Describe the solution you'd like**

New icons/logos have been created for the public OpenSearch branding: https://opensearch.org/brand.html

All of the previous changes using the "heatmap" icon for OpenSearch and OpenSearch Dashboards need to be replaced with the updated logos.

**Describe alternatives you've considered**

N/A

**Additional context**

Commit to change logos for forking/renaming project: https://github.com/opensearch-project/OpenSearch-Dashboards/commit/905ccbe698ce88b3309c6b1f528e9b3a106f5d26

Below are examples of the new marks/logos:

#### Default Mark
![opensearch_mark_default](https://user-images.githubusercontent.com/5437176/119411732-7d74ba80-bcb0-11eb-9f43-7c57d10e9dd1.png)

#### OpenSearch Dashboards Logo (Dark Mode)
![opensearch_dashboards_logo_darkmode](https://user-images.githubusercontent.com/5437176/119411592-44d4e100-bcb0-11eb-86cd-3af9c2673603.png)

**Comment by mihirsoni** [comment]
@tmarkley Would you be able to ensure you attach your PR to this issue ?

**Comment by tmarkley** [comment]
> @tmarkley Would you be able to ensure you attach your PR to this issue ?

@mihirsoni Yep, I'm working on a draft now.
