### ISSUE TITLE
[Discuss] Achievement badges

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#3708]
## Background

Wanted to open a discussion about adding Achievement badges for pull requests to the repo. e.g. https://github.com/opensearch-project/opensearch-build/pull/3305 using [github-merit-badger](https://github.com/aws-github-ops/github-merit-badger). 

## Questions
1. Do we even want such a workflow for the repo?
2. Do we want to be consistent with OpenSearch and Build repo? or have different scaling and label names?

**Comment by seanneumann** [comment]
I love this idea. Let's do it for OUI repo too.

**Comment by Aigerim-ai** [comment]
1. Yes! I love this idea!
2. Let's be consistent
