### ISSUE TITLE
[BUG] Beta-1 has opensearch_security enabled by default

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/OpenSearch-Dashboards#371]
**Describe the bug**

Download "Beta-1" from https://opensearch.org/downloads.html and the opensearch_security params are in the YML by default.

**To Reproduce**
1. Go to https://opensearch.org/downloads.html
2. Click on 'Download OpenSearch Dashboards'
3. Unzip the downloaded file
4. Open "config/opensearch_dashboards.yml" and "opensearch_security" params are set

**Expected behavior**
opensearch_security shall not be there by default

**OpenSearch Version**
Beta-1

**Dashboards Version**
Beta-1

**Plugins**

No

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by peterzhuamazon** [comment]
Is this opensearch or dashboards, if it is the latter one, then the configs are suggested by Dashboards team.

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/opensearch-build/blob/main/config/opensearch_dashboards.yml

**Comment by peterzhuamazon** [comment]
This seems like an issue related to Dashboards, and Infra does not change anything until packing the bundle. Please help @mihirsoni @ananzh @kavilla Thanks.

**Comment by mihirsoni** [comment]
@tianleh what is an issue if you could disable it in via configuration as well right ?

**Comment by mihirsoni** [comment]
@tianleh  I think since Dashboards ships by default security enabled, i would recommend to disable if you wouldn't not prefer security to be enabled in infrastructure.

Closing the issue. Feel free to re-open if required.
