### ISSUE TITLE
[Docs] [Console] Fix/update documentation links in Dev Tools console

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#3714]
In the Dev Tools console, one the actions available when clicking the wrench icon next to a query is to "Open documentation". This is a very helpful contextual dual to directly link API endpoints discoverable via autocomplete to their user docs. The problem is that many of these links are broken.

https://user-images.githubusercontent.com/1679762/228101881-5a88cfc7-8be1-4e60-8126-8871e604cb5c.mov

For example: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/53047b6636934df1b0fa4f22eeaf4f755cf78e75/src/plugins/console/server/lib/spec_definitions/json/generated/ingest.put_pipeline.json#L13

Should point to https://opensearch.org/docs/latest/api-reference/ingest-apis/create-update-ingest/

The task is to audit the documentation values in the JSON files in https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/console/server/lib/spec_definitions/json/generated

and either

1. Update the link if a corresponding documentation page exists on https://opensearch.org
2. OR Open a single issue on https://github.com/opensearch-project/documentation-website that lists all the missing docs. In these cases update the link to just `https://opensearch.org/docs/`

Additionally, links in comments should be fixed or updated in  https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/console/server/lib/spec_definitions/js/ingest.ts

**Exit criteria:**

There should be no more strings matching`/guide/en/elasticsearch` in the https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/console plugin directory.

**Comment by curq** [comment]
Hi @joshuarrrr, can I take this issue?

**Comment by kavilla** [comment]
@curq I don't see why not! Go for it!

**Comment by joshuarrrr** [comment]
@curq  See also https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3685, which may help identify some of the missing links.
