### ISSUE TITLE
[Branding] OpenSearch Dashboards Branding

### ISSUE THREAD

**Issue by tmarkley** [opensearch-project/OpenSearch-Dashboards#372]
The following branding changes are required for the 1.0.0 release: https://opensearch.org/brand.html

- [x] favicons #368 
- [x] logos/icons #370 
  * Any current "heatmap" icons that were changed in this commit: https://github.com/opensearch-project/OpenSearch-Dashboards/commit/905ccbe698ce88b3309c6b1f528e9b3a106f5d26
- [x] OpenSearch mark loading spinner
- [x] Change color on Primary "OpenSearch Dashboards" card in the main home landing page

~Logic to display darkmode/default logos based on the theme~ https://github.com/opensearch-project/OpenSearch-Dashboards/issues/709

**Comment by kgcreative** [comment]
for the loading spinner, you can reference this: https://codepen.io/kgcreative/pen/gOmxrXX

**Comment by kavilla** [comment]
Is branding configurable?

**Comment by kgcreative** [comment]
I don't think it's configurable out of the box - @tmarkley, i know you've been looking under the hood at some of this

**Comment by tmarkley** [comment]
It's not currently configurable, we'd have to add that as a feature. I think Rocky was asking whether it _should_ be configurable.

**Comment by kgcreative** [comment]
I think it *should* be, particularly if we want to make it easier to whitelabel

**Comment by seanneumann** [comment]
@kgcreative let's create an issue soon to track configuration options/branding options. This is out of scope for 1.0.

**Comment by kgcreative** [comment]
Im going to take on:
[ ]  OpenSearch mark loading spinner
[ ] Change color on Primary "OpenSearch Dashboards" card in the main home landing page

PRs coming soon

**Comment by kavilla** [comment]
For branding, do we have a replacement for this K that turned into an "in and out" door.

In Home and Overview (maybe more):

![Screen Shot 2021-05-30 at 1 06 15 AM](https://user-images.githubusercontent.com/12060704/120097175-f2e2ef80-c0e3-11eb-9968-27cd9ccbf565.png)
![Screen Shot 2021-05-30 at 1 06 42 AM](https://user-images.githubusercontent.com/12060704/120097176-f37b8600-c0e3-11eb-97b9-d1e0cf8fd818.png)

**Comment by kgcreative** [comment]
> For branding, do we have a replacement for this K that turned into an "in and out" door.
> 
> 
> 
> In Home and Overview (maybe more):
> 
> 
> 
> ![Screen Shot 2021-05-30 at 1 06 15 AM](https://user-images.githubusercontent.com/12060704/120097175-f2e2ef80-c0e3-11eb-9968-27cd9ccbf565.png)
> 
> ![Screen Shot 2021-05-30 at 1 06 42 AM](https://user-images.githubusercontent.com/12060704/120097176-f37b8600-c0e3-11eb-97b9-d1e0cf8fd818.png)
> 
> 

We don't currently, but we should. Let me look into this.

**Comment by tmarkley** [comment]
1.0 branding was completed. Further branding changes can be tracked in separate issues.
