### ISSUE TITLE
[Feedback] update docker setup instructions

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#3731]
**Feedback needed**

A lot of first time contributors seemed to have run into the issue where the docker setup instructions have not worked as expected resulting in them finding alternative ways to setup the dev environment and contribute those changes to the repository. I too have personally run into this issue so I'm opening up this issue to identify some of the common issues faced by the developers and identify the underlying issue so that we can correctly identify the problem and update the documentation to fix this. Feel free to comment on this issue to outline in as much detail as possible the steps you followed and what went wrong. Also mention the output of some of the debugging steps mentioned here:

Steps to debug the issue:
1. Curl the opensearch endpoint
    `curl http://localhost:9200`
    You should see a response like this

```
{
  "name" : "ip-xxx-xx-xx-xxx",
  "cluster_name" : "opensearch",
  "cluster_uuid" : "abcd",
  "version" : {
    "distribution" : "opensearch",
    "number" : "3.0.0-SNAPSHOT",
    "build_type" : "tar",
    "build_hash" : "abcd",
    "build_date" : "2023-03-28T01:10:43.877444434Z",
    "build_snapshot" : true,
    "lucene_version" : "9.5.0",
    "minimum_wire_compatibility_version" : "2.7.0",
    "minimum_index_compatibility_version" : "2.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```
2. Run `docker ps` again to see if the containers are still up (One container is your dev environment and the other is opensearch, both have to be up for opensearch dashboards to work

Here is what happened to me and the output of some debugging steps.

How i ran into the problem:

1. I cloned the repository
3. installed yarn
4. opened the repository on VS code
5. tried to bootstrap but failed
6. Opened the [alternative docker method](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/docs/docker-dev/docker-dev-setup-manual.md) doc
7. Followed steps 1 - 7. Both containers were running.
8. Fllowed steps 7-10.
9. Opensearch Dashboards started but was unable to connect to OpenSearch

Debugging steps:
1. Curl the opensearch instance: Was not able to connect to the opensearch instance
2. Run docker ps again: only one of the containers was still up, looks like one of them went down after i checked its status

**Comment by curq** [comment]
> Run docker ps again: only one of the containers was still up, looks like one of them went down after i checked its status

I had similar issue, it is possibly caused by the lack of RAM. One container periodically went down. After I bumped RAM allocated to docker to 4.5 GB the issue was resolved.

**Comment by ashwin-pc** [comment]
Closing this issue since its been open for a while now.
