### ISSUE TITLE
[BUG] Percentiles aggregation is not working in monitor query

### ISSUE THREAD

**Issue by Jessie725** [opensearch-project/OpenSearch-Dashboards#3761]
**Describe the bug**

 Percentiles aggregation is not working in monitor query

**To Reproduce**
1. Go to OpenSearch
2. Click on Alerting -> monitors -> create monitor
3. Set the query of the monitor with percentiles aggregation
4. Click Run
5. See error: nothing comes out as result. Other aggregation does not have this issue

**Expected behavior**
The percentiles aggregation should show up

**OpenSearch Version**
Version of OpenSearch being used is 7.10.2

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: 12.6.1
 - Browser and version: Chrome 111.0.5563.110 

**Additional context**

**Comment by kavilla** [comment]
Issue moved to [opensearch-project/alerting-dashboards-plugin #512](https://github.com/opensearch-project/alerting-dashboards-plugin/issues/512) via [**Zenhub**](https://www.zenhub.com/)
