### ISSUE TITLE
Drag & Drop visualization creation

### ISSUE THREAD

**Issue by JacobBrandt** [opensearch-project/OpenSearch-Dashboards#379]
**Is your feature request related to a problem? Please describe.**

Metric, bucket, aggregation are all foreign terms to new users.  Right now the UI presents the users with a way to create visualizations but it's not intuitive and expects the users to know terminology about the technology behind the search.  This often becomes a burden for the user that just wants to see their data.

**Describe the solution you'd like**
An interface that allows users to drag and drop fields to create their visualizations (like Splunk, Tableau, etc.) would be a great improvement.

**Comment by kavilla** [comment]
This one seems very customer focus and empowering users. @ahopp would this be something that can build into the roadmap?

**Comment by ahopp** [comment]
Yes @kavilla @JacobBrandt, this would absolutely be great for users - and something I've been putting some thought into. We have some really phenomenal products to learn from (e.g. Splunk, Tableau, etc.) that have set strong precedence for this type of interface. Not only would an interface like this be a great step toward a more intuitive UI but I think there is a opportunity to enable a more exploratory experience in general. 

I think the next steps are building out a more detailed proposal/RFC around the UI that we'd want to see and sharing with the community. I'll be working on a RFC to share with the community and from there we can work together to get it on the feature roadmap. 

@JacobBrandt do you have specific elements you'd like to see?

**Comment by JacobBrandt** [comment]
@ahopp I'd love to see what you've been thinking.  I've drawn out some rough diagrams of what I've been thinking for a new visualization editing experience that goes beyond just a drag & drop interface.

Here is a list of some things I would like to see from a new visualization editor which hopefully helps with a roadmap.

- Drag and Drop functionality.
- Ability to change index pattern/saved search.
- Ability to change chart type (including installed plugins).
- Use pre-defined metric, bucket aggregation for dragged fields which depends on #378.
Advanced Features:
- Ability to use all pipeline and bucket aggregations.
- Ability to place metric aggregations anywhere in the nested aggregation hierarchy.
- Ability to apply custom calculations/formulas from aggregated results and display them.
- Ability to edit request payload (Useful for when an OpenSearch aggregation feature is possible but there is no UI for it).

**Comment by ahopp** [comment]
@JacobBrandt still working on the deep dive for feature with the team - just wanted to let you know this is still on my radar.

**Comment by ahopp** [comment]
@JacobBrandt created a proposal https://github.com/opensearch-project/OpenSearch-Dashboards/issues/883 to capture some of this high-level. Would love your thoughts! 

Once the community has time to review the proposal we'll share a design doc, but I also think we should start thinking through the features above in terms of feature priority. Would love you thought there as well!
