### ISSUE TITLE
[Console] Convert all lib/mappings files to typescript

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/OpenSearch-Dashboards#3800]
Coming from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3775#discussion_r1160144552, move to ts will make code more readable and maintainable.

Files:

```
find ./src/plugins/console/public/lib/mappings -name "*.js"
./src/plugins/console/public/lib/mappings/__tests__/mapping.test.js
./src/plugins/console/public/lib/mappings/mappings.js
```

**Comment by Seitakhmetv** [comment]
✌️Hello! 
Based on the issue, to **increase readability and maintainability** in those files, I'd like to suggest following

### Suggestions:

- Add typings for the parameters, variables, and return values
- Update function signatures with TS types based on the typings above
-  Replace typeof and Array.isArray with TS type guards
- Use TS utility types, such as Record and Partial
- Update the entire "lodash" import to individual functions import
- Add TS interfaces to provide type safety

Could you, please, assign this issue to me?

Feel free to comment or add more suggestions

**Comment by zhongnansu** [comment]
@Seitakhmetv The suggestions look great! Let me assign this to you, looking forward to your pull requests!

**Comment by joshuarrrr** [comment]
@Seitakhmetv In case you hadn't found these docs:

1. https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/TYPESCRIPT.md
2. https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main

**Comment by Seitakhmetv** [comment]
> @Seitakhmetv In case you hadn't found these docs

Thank you!
Those are really useful for me and, yes, indeed I haven't seen them.
Today I'll finish typescripting files above.

**Comment by curq** [comment]
Hi @Seitakhmetv, I hope you're doing well. I was wondering about the progress on this issue you've been working on. I'm looking forward to using the types from the mapping, as without them I can't complete my related Typescript conversion issue. Could you please provide an update on the status or an estimated time for completion? Thank you!

**Comment by curq** [comment]
Hello, @Seitakhmetv @joshuarrrr Can I make a PR for this issue? My two other issues need types from this one to finish, so I'm currently blocked because of it.

**Comment by joshuarrrr** [comment]
@curq Yes, go ahead if you're ready to unblock the related work.

**Comment by curq** [comment]
@joshuarrrr I made a PR, could you check it please?
