### ISSUE TITLE
[BUG] DevTools not working when the url have a query parameter

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/OpenSearch-Dashboards#3812]
**Describe the bug**

When run a command in DevTool, if the command don't have query parameter, it works fine. But when the command have a query parameter, it will got rejected with `contains unrecognized parameter: [v?pretty]`

**To Reproduce**
1. Go to 'Devtools'
2. input command `GET _cat/tasks?v`
3. click play icon

**Expected behavior**
It's a valid command and should be execute it without any error

**OpenSearch Version**
3.0.0

**Dashboards Version**
3.0.0

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

<img width="1703" alt="image" src="https://user-images.githubusercontent.com/113890546/230843751-af827da7-e66b-4b95-9b6d-0a09a040b40b.png">

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by aoguan1990** [comment]
@joshuarrrr please help look into this bug and  let me know if you have any concerns.

**Comment by joshuarrrr** [comment]
Thanks @Hailong-am for the issue and PR!
