### ISSUE TITLE
[BUG] [Console] Requests with query strings return errors

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#3815]
**Describe the bug**

From @Hailong-am https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3544#discussion_r1161408620

> when i run command GET _cat/tasks?v in DevTools, it reports error like below, i guess it may caused this change.
> 
> ```
>     {
>     "error": {
>     "root_cause": [
>     {
>     "type": "illegal_argument_exception",
>     "reason": "request [/_cat/tasks] contains unrecognized parameter: [v?pretty] -> did you mean [pretty]?"
>     }
>     ],
>     "type": "illegal_argument_exception",
>     "reason": "request [/_cat/tasks] contains unrecognized parameter: [v?pretty] -> did you mean [pretty]?"
>     },
>     "status": 400
>     }
> ```

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by joshuarrrr** [comment]
@zhongnansu I'm assigning you to take the first look

**Comment by zhongnansu** [comment]
@joshuarrrr Thanks for creating issue. I commented on the PR
