### ISSUE TITLE
Remove KUI usage in `maps_legacy`

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#3829]
The `maps_legacy` plugin uses a single `.kui*` namespaced class. See https://github.com/search?q=repo%3Aopensearch-project%2FOpenSearch-Dashboards+kui+NOT+trackUI+path%3A%2F%5Esrc%5C%2Fplugins%5C%2Fmaps_legacy%2F&type=code

## To resolve

Investigate and inspect the applied CSS of that class and the rendered component. If necessary:

1. Document CSS rules provided by these classes
2. Replace these components with OUI components

Note that `maps_legacy` is a plugin dependency of the `tile_map` and `vis_type_vega` plugins, so this change should be tested in both of those cases.

**Comment by curq** [comment]
@joshuarrrr Can you please assign this issue to me?

**Comment by miamia1999** [comment]
Could you, also, assign this issue to me?
