### ISSUE TITLE
[BUG] Blank Page when Editing Monitor with SNS Integration

### ISSUE THREAD

**Issue by michaelact** [opensearch-project/OpenSearch-Dashboards#3840]
**Describe the bug**
Blank Page when Editing Monitor with SNS Integration

**To Reproduce**
1. Go to Alerting > Monitor > Create Monitor > Add Trigger
2. Click on 'Select channel to notify' dropdown
3. Choose one of SNS channel
4. Blank page and see error in console.

**Expected behavior**
Should be able to edit the monitor.

**OpenSearch Version**
2.6.0

**Dashboards Version**
2.6.0

**Plugins**
Opensearch Dashboard:
```
$ ls plugins/
alertingDashboards/          mlCommonsDashboards/         searchRelevanceDashboards/
anomalyDetectionDashboards/  notificationsDashboards/     securityAnalyticsDashboards/
customImportMapDashboards/   observabilityDashboards/     securityDashboards/
ganttChartDashboards/        queryWorkbenchDashboards/
indexManagementDashboards/   reportsDashboards/
```

Opensearch Cluster:
```
$ ls plugins/
opensearch-alerting                   opensearch-neural-search
opensearch-anomaly-detection          opensearch-notifications
opensearch-asynchronous-search        opensearch-notifications-core
opensearch-cross-cluster-replication  opensearch-observability
opensearch-geospatial                 opensearch-performance-analyzer
opensearch-index-management           opensearch-reports-scheduler
opensearch-job-scheduler              opensearch-security
opensearch-knn                        opensearch-security-analytics
opensearch-ml                         opensearch-sql
```

**Screenshots**

<img width="920" alt="image" src="https://user-images.githubusercontent.com/86778470/231703339-939d4649-efe2-4ecb-937c-70ede94ab5bd.png">

**Host/Environment (please complete the following information):**
 - OS: Windows 11
 - Browser and version: Microsoft Edge 112

**Comment by joshuarrrr** [comment]
@opensearch-project/triage Please transfer to https://github.com/opensearch-project/alerting-dashboards-plugin

**Comment by michaelact** [comment]
> @opensearch-project/triage Please transfer to https://github.com/opensearch-project/alerting-dashboards-plugin

How?

**Comment by joshuarrrr** [comment]
@opensearch-project/triage is a group of admins with permissions to transfer issues between Opensearch project repositories. I don't have the permissions to transfer it myself.

**Comment by kavilla** [comment]
Issue moved to [opensearch-project/alerting-dashboards-plugin #529](https://github.com/opensearch-project/alerting-dashboards-plugin/issues/529) via [**Zenhub**](https://www.zenhub.com/)
