### ISSUE TITLE
Issues related to Reporting plugin in Opensearch Dashboard 2.6.0 [BUG]

### ISSUE THREAD

**Issue by singhankit62000** [opensearch-project/OpenSearch-Dashboards#3841]
**Describe the bug**
Installed Opensearch dashboard 2.6.0 with reporting plugin.
Created visualizations of various types and tried to generate reports for those visualizations in pdf and png format.
The visualizations are visible in the reports but the scale is not coming in the generated reports.

**To Reproduce**
1. Go to Visualisation, Save a visualisation
2. Click on Reporting -> Download PNG/ Download PDF
3. Check the downloaded report and compare it with the actual Visualisation

**Expected behavior**
A clear report of the whole visualisation/ dashboard along with the scale of the data as well.

**OpenSearch Version**
2.6.0

**Dashboards Version**
2.6.0

**Plugins**
* reportsDashboards
* opensearch-reports-scheduler
* opensearch-job-scheduler

**Screenshots**
![doc-1](https://user-images.githubusercontent.com/60176330/231711119-8db44550-d4d6-48dc-abc2-248af976069f.png)

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by joshuarrrr** [comment]
@opensearch-project/triage Please transfer to https://github.com/opensearch-project/dashboards-reporting

**Comment by singhankit62000** [comment]
Hi @joshuarrrr is there something I need to do for this issue to be transferred?

**Comment by kavilla** [comment]
Issue moved to [opensearch-project/dashboards-reporting #93](https://github.com/opensearch-project/dashboards-reporting/issues/93) via [**Zenhub**](https://www.zenhub.com/)
