### ISSUE TITLE
[BUG][MD] Cypress tests for multiple datasource are failing

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#3843]
**Describe the bug**
Currently the cypress tests for multiple datasource are failing. 
![Screenshot 2023-04-13 at 1 17 41 PM](https://user-images.githubusercontent.com/43937633/231873932-866b329d-7f29-4836-bdb4-422264de3fc3.png)

I think the default schema config value for multiple datasource is false, so MD is not enabled when cypress tests are trying to run. https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data_source/config.ts#L15

**Comment by zhongnansu** [comment]
@abbyhu2000 we need to enable from cypress workflow file, not from osd.yml. I have a PR opened. Let's see if cypress passes there

**Comment by joshuarrrr** [comment]
I think we do something similar for visbuilder? It's experimental, so disabled by default in OSD, but it should always be enabled in the test server for the purpose of testing.

**Comment by zhongnansu** [comment]
@joshuarrrr visbuilder is actually enabled by default in its `config.ts`.

**Comment by zhongnansu** [comment]
@joshuarrrr As my option 3 explains, test server in OSD cypress flow doesn't seem to provide option to enable/disable a osd setting, correct me if I'm wrong

**Comment by zhongnansu** [comment]
PR opened in function test repo https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/613

**Comment by zhongnansu** [comment]
cypress passes now https://github.com/opensearch-project/OpenSearch-Dashboards/actions/runs/4694010639/jobs/8339937917
