### ISSUE TITLE
[BUG] Unused URL failed the Link checker

### ISSUE THREAD

**Issue by aoguan1990** [opensearch-project/OpenSearch-Dashboards#3846]
**Describe the bug**

URL: http://roubenmeschian.com/rubo/?p=51 is not reachable by the link checker, which causes the link checker failure. We observed that this url is commented out in the following two files. Clean up is needed to fix the link checker failure.
- src/plugins/discover/public/application/angular/doc_table/create_doc_table_react.tsx
- src/plugins/discover/public/application/doc_views/doc_views_helpers.tsx

**Comment by joshuarrrr** [comment]
Resolved via #3847
