### ISSUE TITLE
Reporting : Add possibility to delete reports

### ISSUE THREAD

**Issue by 51CGO** [opensearch-project/OpenSearch-Dashboards#3856]
**Is your feature request related to a problem? Please describe.**

In the _reporting_ page, _reporting definitions_ can be deleted but _reportings_ can't.

**Describe the solution you'd like**

The _report details_ page should display a button to delete the report

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by zhongnansu** [comment]
@opensearch-project/triage please transfer this issue to reporting repo

**Comment by kavilla** [comment]
Issue moved to [opensearch-project/dashboards-reporting #92](https://github.com/opensearch-project/dashboards-reporting/issues/92) via [**Zenhub**](https://www.zenhub.com/)
