### ISSUE TITLE
[BUG] Play/Wrench Button Regression in Dev Tools

### ISSUE THREAD

**Issue by macohen** [opensearch-project/OpenSearch-Dashboards#3916]
**Describe the bug**

The Play/Wrench buttons do not move as focus is changed from one command to another in dev tools.

**To Reproduce**
1. Go to the Dev Tools on the 2.7 RC OpenSearch Dashboards
2. Enter a request into the textarea box on the left (e.g. GET /_cat)
3. Click the "Play" Button
4. Enter another request below the first request (e.g. GET /_cat/segments).
5. The "Play" Button and Wrench do not show up on the second request.

**Expected behavior**
I expect that the request with focus (where the cursor is) should have the Play button and wrench. 

**OpenSearch Version**
Docker Image: opensearchstaging/opensearch:2.7.0.7747

**Dashboards Version**
Docker image: opensearchstaging/opensearch-dashboards:2.7.0.6090

**Plugins**
opensearch-alerting                  2.7.0.0
opensearch-anomaly-detection         2.7.0.0
opensearch-asynchronous-search       2.7.0.0
opensearch-cross-cluster-replication 2.7.0.0
opensearch-geospatial                2.7.0.0
opensearch-index-management          2.7.0.0
opensearch-job-scheduler             2.7.0.0
opensearch-knn                       2.7.0.0
opensearch-ml                        2.7.0.0
opensearch-neural-search             2.7.0.0
opensearch-notifications             2.7.0.0
opensearch-notifications-core        2.7.0.0
opensearch-observability             2.7.0.0
opensearch-performance-analyzer      2.7.0.0
opensearch-reports-scheduler         2.7.0.0
opensearch-security                  2.7.0.0
opensearch-security-analytics        2.7.0.0
opensearch-sql                       2.7.0.0

**Screenshots**

<img width="748" alt="Screenshot 2023-04-21 at 11 11 00 AM" src="https://user-images.githubusercontent.com/254449/233673034-e0f011b1-a6cb-4f9e-80f6-bf684d9fb30c.png">

**Host/Environment (please complete the following information):**
 - OS: macOS Ventura 
 - Browser and version: Google Chrome Version 112.0.5615.121 (Official Build) (x86_64)

**Additional context**

**Comment by manasvinibs** [comment]
Removing untriaged label as we have a [PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3920) open linked to this issue. PR is still work in progress.

**Comment by joshuarrrr** [comment]
Fixed by reverting https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3929
