### ISSUE TITLE
[BUG] Impossible to list or create repository when repository validation fails (snapshot management + repository-S3 plugin)

### ISSUE THREAD

**Issue by djadeau** [opensearch-project/OpenSearch-Dashboards#3925]
**Describe the bug**

This bug has been noticed on Opensearch 2.6.0 with the repository-s3 plugin installed.
The problem comes from the repository validation in the snapshot management.
When there is a repository that cannot be validated, then the repositories are not listed and it is impossible to create a new one.
The only way to solve it in that case, is to delete the repository using the Opensearch API.

**To Reproduce**
1. In Opensearch Dashboard go to Snapshot management
2. Go to Repositories
3. Create a S3 repository (custom configuration) with a wrong parameter (in order to make the validation fails)
4. Try to display the repository list or to create a new repository

**Expected behavior**
The behavior should be similar to the Opensearch API. Then the repository validation should not block the listing and the creation of a new repository. It should only display a status.

**OpenSearch Version**
Version 2.6.0 + repository-s3 plugin

**Dashboards Version**
2.6.0.

**Plugins**

Repository-s3

**Host/Environment (please complete the following information):**
 - OS: Official Opensearch Helm chart applied on Openshift
 - Firefox 91, Chromium 110

**Additional context**

S3 environment based on Minio

**Comment by kavilla** [comment]
Issue moved to [opensearch-project/index-management-dashboards-plugin #714](https://github.com/opensearch-project/index-management-dashboards-plugin/issues/714) via [**Zenhub**](https://www.zenhub.com/)
