### ISSUE TITLE
How to use network-attachment-definitions in opensearch helm charts.

### ISSUE THREAD

**Issue by ganilmca** [opensearch-project/OpenSearch-Dashboards#3927]
Hi Team,

We want to deploy  OpenSearch-cluster with network-attachment-definitions.
Can any one please help us to deploy the cluster with network-attachment-definitions.
What changes are required from our side.

Thanks & Regards,
Anil

**Comment by manasvinibs** [comment]
@opensearch-project/triage transfer this to the helm-charts team https://github.com/opensearch-project/helm-charts

**Comment by kgcreative** [comment]
Issue moved to [opensearch-project/helm-charts #419](https://github.com/opensearch-project/helm-charts/issues/419) via [**Zenhub**](https://www.zenhub.com/)
