### ISSUE TITLE
[Feature Anywhere] Meta Issue tracker

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/OpenSearch-Dashboards#3969]
This is a meta issue tracker for #2880 to track the current progress of the project.

Create issues in the respective repository for any issues (UX or technical) regarding `Feature Anywhere` and link them to this issue, so this will be the central location to track and manage all the issues.

**Comment by ohltyler** [comment]
All bugs have been fixed and merged in several different PRs, with no associated list of bug fix issues. Resolving.
