### ISSUE TITLE
[BUG] "Select you tenant" is displayed when multitenancy is disabled

### ISSUE THREAD

**Issue by 51CGO** [opensearch-project/OpenSearch-Dashboards#3973]
**Describe the bug**

Just after login, Dashboards displays a pop-up "Select your tenant" even if multi tenancy is disabled.

If I select "Global", I get an error message, so I must click on "Cancel".

In the menu Security -> Tenants,
- The Manage tab says "You have not enabled multi tenancy"
- The Configure tab says Multi-tenancy : Enabled

**To Reproduce**
1. Connect to Opensearch Dashboards
2. Log in
3. A pop-up appears for selecting a tenant

**Expected behavior**
No pop-up

**OpenSearch Version**
2.7.0

**Dashboards Version**
2.7.0

**Plugins**
Standard delivery. No plugin added or removed.

**Screenshots**

![01 Select your tenant](https://user-images.githubusercontent.com/12408378/235882578-e115045c-1c5b-48bf-8c50-9e4c7d758806.png)
![02 Failed to switch tenant](https://user-images.githubusercontent.com/12408378/235882581-e9de0a60-2d9a-4620-b569-06e197e7e228.png)
![03 Multitenancy not enabled](https://user-images.githubusercontent.com/12408378/235882582-50ad182f-289f-4668-87f1-b2a61fd047d6.png)
![04 Multitenancy enabled](https://user-images.githubusercontent.com/12408378/235882584-5a1a0eec-7248-4d5b-b101-4b4cd774bc2b.png)

**Host/Environment (please complete the following information):**
 - OS: RHEL 8.4
 - Firefox 102.8.0esr (64 bits)

**Additional context**

N/A

**Comment by zhongnansu** [comment]
@opensearch-project/triage Please transfer the issue to security-dashboards-plugin https://github.com/opensearch-project/security-dashboards-plugin/issues

**Comment by kavilla** [comment]
@51CGO, yes good catch. There is an [existing issue](https://github.com/opensearch-project/security-dashboards-plugin/issues/1412) in the security dashboards repo. To get around this, please disable multitenancy on OpenSearch as well.

**Comment by kavilla** [comment]
Issue moved to [opensearch-project/security-dashboards-plugin #1422](https://github.com/opensearch-project/security-dashboards-plugin/issues/1422) via [**Zenhub**](https://www.zenhub.com/)
