### ISSUE TITLE
[BUG] Exporting via reporting on dark mode broke

### ISSUE THREAD

**Issue by BT-93** [opensearch-project/OpenSearch-Dashboards#3979]
When dark mode is set and you export to either PNG or PDF the background of the exports is white.
This was not an issue prior to version 2.6 (I think).

**To Reproduce**
1. Go to Advanced Settings
2. Search for Dark Mode
3. Set the slider to Dark Mode
4. Go to a dashboard
5. Select Reporting
6. Go either PNG or PDF
7. Exported doco background is white

**Expected behavior**
The background to be color #141519

**OpenSearch Version**
2.6 & 2.7

**Dashboards Version**
2.6 & 2.7

**Plugins**
The default ones

**Screenshots**
![image](https://user-images.githubusercontent.com/94328741/236122444-27957bf3-783c-47aa-bead-a4896fd659da.png)

**Host/Environment (please complete the following information):**
 - OS: Windows 10
 - Browser and version: Chrome Version 113.0.5672.64 (Official Build) (64-bit)

**Additional context**
:)

**Comment by zhongnansu** [comment]
@opensearch-project/triage Please transfer this issue to reporting repo https://github.com/opensearch-project/dashboards-reporting

**Comment by kavilla** [comment]
Issue moved to [opensearch-project/dashboards-reporting #111](https://github.com/opensearch-project/dashboards-reporting/issues/111) via [**Zenhub**](https://www.zenhub.com/)
