### ISSUE TITLE
2.8.0 Platform Upgrades for Plugins (Feature Anywhere, Point in time, Node 18,+)

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#3981]
For all [issues labeled 2.8.0](https://github.com/opensearch-project/OpenSearch-Dashboards/issues?q=is%3Aopen+is%3Aissue+label%3Av2.8.0), PRs must be opened by 2023-04-16 to be considered on track.

In general, the time to first review SLA for OpenSearch Dashboards is 7 days. Each PR will be assigned to a maintainer as the primary point of contact.

### GA feature launches

1. https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2880

### Dashboards plugin blockers

1. 

### Features and fixes

1. https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3957
2. https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1560 (Partial)

### Known PRs

https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is%3Aopen+is%3Apr+label%3Av2.8.0
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3957
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3961
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3777
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3687
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3415
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3971
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3908
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3608
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3116

### Feature launches

1. We will be pushing the feature anywhere PRs to 2.next for the sake of the Node bump upgrade since the impact of the changes is large in scope but is required as Node 14 has been EOL since the previous 2.x release.

**Comment by zhongnansu** [comment]
Add 1 more PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4126

**Comment by kavilla** [comment]
Feature anywhere stuff pushed to 2.9. Node bump made. Closing as no more upgrades for stabilization.
