### ISSUE TITLE
[BUG] unable to add data filter to an alerting monitor 

### ISSUE THREAD

**Issue by ArminRadmueller** [opensearch-project/OpenSearch-Dashboards#3983]
**Describe the bug**

It is not possible to add a data filter (e.g. EventId IS 1234). The UI displays the input window, it is possible to enter the filter, but it is not possible to save it because the Save/Close buttons are not present.

**To Reproduce**
1. fresh installation of OpenSearch 2.7.0
2. Alerting -> "Create monitor"
3. Select "Per query monitor" and "Visual editor", Index and Time field
4. Data filter -> "Add filter"
5. Enter the filter settings and try it to save

**Expected behavior**
as with other input window (e.g. add group by) the Save/Close buttons should be displayed

**OpenSearch Version**
2.7.0

**Dashboards Version**
2.7.0

**Plugins**

![image](https://user-images.githubusercontent.com/12393757/236396644-d7c3911b-b746-4f72-8e2b-78538e4c83c6.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/12393757/236396575-321f5ea1-45f4-418c-a8ae-8b49232d7495.png)

**Host/Environment (please complete the following information):**
 - OS: Win10
 - Browser and version: newest Edge

**Additional context**

**Comment by kavilla** [comment]
Issue moved to [opensearch-project/alerting-dashboards-plugin #545](https://github.com/opensearch-project/alerting-dashboards-plugin/issues/545) via [**Zenhub**](https://www.zenhub.com/)
