### ISSUE TITLE
[BUG] Edit Policy, Snapshot schedule "start time" field always set at 20h, then don't display the configured value

### ISSUE THREAD

**Issue by agaldemas-eridanis** [opensearch-project/OpenSearch-Dashboards#3984]
**Describe the bug**

when you edit a policy:
the Snapshot schedule "start time" field appears always set at 20h, then does not display the configured value
**To Reproduce**
1. create a policy ( through Snapshot Management/snapshot Policies interface) with a start time different than 20h (1h for exampke), save it
2. go back in the list, you see the policy, with 1h OK
3. edit the the just created policy
4. See the Snapshot schedule "start time" field always set at 20h, and if you update, 20h is saved...

**Expected behavior**
read value should be displayed, then it should not change it to 20h...

**OpenSearch Version**
2.7.0
**Dashboards Version**
2.7.0
**Plugins**

Please list all plugins currently enabled.

**Screenshots**

<img width="604" alt="Capture d’écran 2023-05-05 à 12 19 52" src="https://user-images.githubusercontent.com/82389794/236436153-dfab66a6-0700-46bc-a087-f9a8fe33232b.png">

### As you can see above field is set to 20h, instead of 1h !

**Host/Environment:**
 - OS: macos
 - chrome Version 112.0.5615.137 (Build officiel) (x86_64)

**Comment by kavilla** [comment]
Issue moved to [opensearch-project/index-management-dashboards-plugin #726](https://github.com/opensearch-project/index-management-dashboards-plugin/issues/726) via [**Zenhub**](https://www.zenhub.com/)
