### ISSUE TITLE
[PURIFY] Fix broken / transient unit test cases

### ISSUE THREAD

**Issue by mihirsoni** [opensearch-project/OpenSearch-Dashboards#4]
- [ ] With existing fixture, test `verify consistency of modes of files` inside zip.test.js fails. Need to fix it

**Comment by ananzh** [comment]
Include all skipped unit test and issues in a summary issue [#483](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/483). Close this issue since it is duplicate.
