### ISSUE TITLE
[BUG] Certain Dashboards only show in the Dashboard list after searching

### ISSUE THREAD

**Issue by ha-luke** [opensearch-project/OpenSearch-Dashboards#4017]
**Describe the bug**
After an upgrade from 2.6 to 2.7 when browsing the list of available dashboards, not all dashboards are shown. It is only when I enter a search string in the search box on the same page that the dashboards I am looking for show up. The default unfiltered dashboard page still shows a lot of my created dashboards, but a good 25% of them are not shown until searching for them. Confirmed reproducible after clearing cookies/cache. This affects all newly created dashboards as well.

**To Reproduce**
1. Go to 'Dashboard' in the hamburger menu under the 'OpenSearch Dashboards' section.
2. Observe the list of dashboards shown
3. Search for a dashboard that is not shown
4. Observe the dashboard that is shown only when searching

**Expected behavior**
The expectation is that all available dashboards are shown on the initial Dashboard page. Searching should not be required. 

**OpenSearch Version**
2.7.0

**Dashboards Version**
2.7.0

**Plugins**
Any included with the Docker image opensearchproject/opensearch-dashboards:2.7.0

**Screenshots**
Default Dashboard page showing exactly 20 dashboards:
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/110492633/61146563-431f-4a29-9396-a4a0f028af95)

And the results after typing "a" in the search box: (We found the dashboards I was looking for initially!)
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/110492633/a761f5c1-8e3f-4f39-b1c9-a12a2174f645)

**Host/Environment (please complete the following information):**
All clients are running Windows 10/11 with a mixed bag of browsers.
- Google Chrome Version 113.0.5672.93 (Official Build) (64-bit)
- Firefox Version 113.0 (64-bit)

**Additional context**
The common denominator: These dashboards that I can't see without searching were both created in May of this year. Although they were both created before the upgrade from 2.6 to 2.7, they are both fairly recent.

**Comment by seanneumann** [comment]
@pjfitzgibbons @kavilla Can you take a look at this?

**Comment by kavilla** [comment]
Hello @ha-luke,

Thanks for calling out. It wouldn't be anything related to dashboards previously created as it is related to a new feature within OpenSearch Dashbards. It is likely related to this line here:
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/dashboard/public/application/legacy_app.js#L154

It's only mapping the default limit to one page regardless if there is more than one page of saved objects.

Temporarily, can you confirm updating the `Objects per page` in your Advanced Settings to a number that matches the amount of dashboards and sees if everything shows.

![Screenshot 2023-05-12 at 9 50 18 AM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/12060704/a5a29d0c-a0f3-4cae-b45f-72ae50712f63)

**Comment by ha-luke** [comment]
Hi @kavilla! Thanks for the response!

Updating `Objects per page` resolved the issue. I can now see the new dashboards. Appreciate you looking into this!

Luke

**Comment by kavilla** [comment]
> Hi @kavilla! Thanks for the response!
> 
> Updating `Objects per page` resolved the issue. I can now see the new dashboards. Appreciate you looking into this!
> 
> Luke

No thank you!

It's actually related to previously the page size was set to to the listing limit which is by default `1000` but with the updates it is using the saved objects per page. Will make sure to make the fix!

Thanks again!
