### ISSUE TITLE
[Enhancement] Usability with switching tenants

### ISSUE THREAD

**Issue by arunx2** [opensearch-project/OpenSearch-Dashboards#4056]
**Is your feature request related to a problem? Please describe.**

The tenant information is visible anywhere on the home screen of the Dashboards. To know the tenant, I need to click on my profile icon in the top-right corner. And to switch tenants, multiple clicks required, there is no search for tenants, and select the tenant from the list of tenants.

**Describe the solution you'd like**

A tenant indication icon just besides a home screen or anywhere in the top banner. I should be able to search and select the available tenant by clicking the indication icon.

**Describe alternatives you've considered**

**Additional context**
<img width="208" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/844111/68a33b37-e741-4768-a239-4d214a00828c">

**Comment by kavilla** [comment]
Issue moved to [opensearch-project/security-dashboards-plugin #1431](https://github.com/opensearch-project/security-dashboards-plugin/issues/1431) via [**Zenhub**](https://www.zenhub.com/)
