### ISSUE TITLE
[BUG] API calls don't display any report definitions nor instances

### ISSUE THREAD

**Issue by 51CGO** [opensearch-project/OpenSearch-Dashboards#4125]
**Describe the bug**

When calling API .opendistro-reports-instances/_search or .opendistro-reports-definitions/_search, no hit is found.

**To Reproduce**
1. Create some reports definitions using Reporting -> Report definitions -> Create
2. Verify that the definitions exists and that some reports have been created 
3. Go to Dev tools
4. Try the following calls:
GET .opendistro-reports-instances/_search
GET .opendistro-reports-definitions/_search
=> no hit displayed

**Expected behavior**
These calls should display the definitions and the instances

**OpenSearch Version**
2.6.0

**Dashboards Version**
2.6.0

**Plugins**
Standard installation without adding nor removing any plugin.

**Screenshots**
![2023-05-24 10_51_35-Window](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/12408378/67fcebae-e508-4732-a661-738e73ef29b9)
![2023-05-24 10_52_12-Window](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/12408378/296d9fbc-6b26-4245-958a-a6b2dc3f2860)
![2023-05-24 10_52_34-Window](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/12408378/07942f78-7a89-4b38-985f-af1c1d86617a)

**Host/Environment (please complete the following information):**
 - OS: RHEL 8
 - Browser and version : Firefox 102

**Comment by zhongnansu** [comment]
@opensearch-project/triage please help moving to reporting repo

**Comment by joshuarrrr** [comment]
Thanks @51CGO - we'll get this moved to the reporting repo: https://github.com/opensearch-project/dashboards-reporting

**Comment by kavilla** [comment]
Issue moved to [opensearch-project/dashboards-reporting #119](https://github.com/opensearch-project/dashboards-reporting/issues/119) via [**Zenhub**](https://www.zenhub.com/)
