### ISSUE TITLE
[BUG] Acknowledging an alert leaves the checkbox checked and disabled

### ISSUE THREAD

**Issue by Jon-AtAWS** [opensearch-project/OpenSearch-Dashboards#4127]
**Describe the bug**

I am using the Alerting UI "Alerts by Triggers" panel to acknowledge alerts. I select the check box for one of the monitors, then click Acknowledge, then select the alert and Acknowledge. I return to the "Alerts by Triggers" page and the checkbox is checked and disabled.

From this point, I am not able to uncheck the box, or check a different box (the first box remains checked for a total of 2 checked boxes), and acknowledge alerts there.

**To Reproduce**
See above

**Expected behavior**
When I return to the "Alerts by Triggers" page, the box should be unchecked and disabled if I have no more alerts to acknowledge, or it should be enabled and not checked if there are more alerts to acknowledge.

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

OpenSearch 1.1, hosted in the AWS service

**Plugins**

Just the ones that come preloaded for the service

**Screenshots**

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/48454554/16982663-a888-4b64-b023-d92bc43cd6a1)

**Host/Environment (please complete the following information):**
 - OS: MacOS 12.6.5
 - Browser and version Firefox 113.0

**Comment by joshuarrrr** [comment]
@opensearch-project/triage Please transfer issue to https://github.com/opensearch-project/alerting-dashboards-plugin

**Comment by kavilla** [comment]
Issue moved to [opensearch-project/alerting-dashboards-plugin #559](https://github.com/opensearch-project/alerting-dashboards-plugin/issues/559) via [**Zenhub**](https://www.zenhub.com/)

**Comment by bbarani** [comment]
Going forward, I would recommend to transfer the issue rather than creating a new one to better track the history and owner of the issue.
