### ISSUE TITLE
Stack management to Dashboard Management

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/OpenSearch-Dashboards#4132]
- [ ] Rename Stack management to Dashboard Management
- [ ] Add overview page
- [ ] Replace Stack management with Management overview in app category page

### Before
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113890546/0564d8be-7eb9-4c97-9f7d-110ef62badb0)

### After
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113890546/7e82639f-4032-4bb6-9809-fc04fb69d72d)

### Overview page
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113890546/b24bec05-66c2-4d8c-96c2-98e60f80b041)

**Comment by KrooshalUX** [comment]
@manasvinibs thanks for the ping. This work belongs to @kamingleung  - however I have UX feedback that I will work with him on directly.
