### ISSUE TITLE
[BUG] “Remember my selection next time I log in from this device.” doesn’t work

### ISSUE THREAD

**Issue by Mosarvit** [opensearch-project/OpenSearch-Dashboards#416]
Hello!

“Remember my selection next time I log in from this device.” doesn’t seem to be working as it is intended. We have a multi-tenant ELK setup and when a user set a tenant and click on the remember preference checkbox it still takes back the user to global tenant each time they login or refresh the session(page reload on session expiry).

**To Reproduce**

1. Create more than one tenant
2. Enable multitenancy on Kibana
3. Login to Kibana (in our case, using SSO)
4. Select any tenant other than Global
5. Select “Remember my selection next time I log in from this device.”
6. Confirm
7. Wait until session expires
8. Reload the page

**Actual behavior**
Global tenant is selected

**Expected behavior**
The previously selected tenant should be still selected

**OpenSearch Version**
 OpenDistro 1.13.2

**Comment by kavilla** [comment]
Hey @Mosarvit, this seems like an issue related to the [security plugin](https://github.com/opensearch-project/security-dashboards-plugin) it should be raised in that repo.

**Comment by Mosarvit** [comment]
Thank you, @kavilla , will do!
