### ISSUE TITLE
[Table Visualization] [CCI] Remove custom styling for ```text-align:center``` in favor of OUI utility class ```oui-textCenter```

### ISSUE THREAD

**Issue by curq** [opensearch-project/OpenSearch-Dashboards#4163]
**Is your feature request related to a problem? Please describe.**

As part of the OUI compliance [audit](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4162), it was discovered that instead of OUI utility class, custom styling was used.
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/bd7d70731eb56372aa2a360e85207a1e6396091f/src/plugins/vis_type_table/public/components/table_vis_app.scss#L20-L23

**Describe the solution you'd like**

Use ```oui-textCenter``` instead.

**Describe alternatives you've considered**

Keep the custom styling, but it is not ideal.

**Additional context**

Audit from where the suggestions comes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4162.

**Comment by joshuarrrr** [comment]
completed via #4164
