### ISSUE TITLE
Troubleshooting Orphan Processes after Upgrading OpenSearch Dashboard to 2.7.0

### ISSUE THREAD

**Issue by nik06** [opensearch-project/OpenSearch-Dashboards#4198]
**Behavior prior to OSD 2.7.0** : 

Launching OSD created a single process that can be easily managed. 

**Behavior in OSD 2.7.0** : 

Launching OSD creates 3 processes : 
P1. opensearch-dashboards/bin/opensearch-dashboards
P2. opensearch-dashboards/bin/use_node
P3. opensearch-dashboards/node/bin/node

All these 3 processes get launched with --config flag. Parent process is P1, parent of P2 is P1 and parent of P3 is P2.
Killing P1 doesn't terminate child processes P2 and P3.

**Comment by kavilla** [comment]
@nik06 confirmed with @AMoo-Miki this has been addressed in 2.8 (which is currently pending release). Will you be willing to upgrade to 2.8 once it comes out?

Unfortunately, there isn't a 2.7.1 release planned: https://opensearch.org/releases.html.

If you are not able to, please re-open this issue and we can talk about next steps.

**Comment by nik06** [comment]
Hi @kavilla @AMoo-Miki , thanks for the update. Given that 2.8 release is scheduled for next week, I'll wait for the new version.
