### ISSUE TITLE
[Data Explorer] Build switching functionality between 'discover' and 'discover_legacy'

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#4223]

**Comment by wbeckler** [comment]
If this never gets built, what are the consequences?

**Comment by ashwin-pc** [comment]
Closing. Duplicate of #4219. 

@wbeckler the consequence is that customers wont be able to revert back to the old experience during the transition period of 2.10 and 2.11
