### ISSUE TITLE
[Data Explorer] Build basic doc table

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#4224]
### Setup and start workflow

- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4419
          PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4432

### Implement Table using Data Grid
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4442
          PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4458

### Clean out Table related angular context
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4459
          PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4468

### De-Angular leaf components and polish the logic
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4470

### Data Fetch and subscribe
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4396
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4397

**Comment by ananzh** [comment]
Done. Close the issue.
