### ISSUE TITLE
[Data Explorer] Implement Embeddable

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#4233]

**Comment by ananzh** [comment]
### Overall Functioning

- [ ] Dashboard could load a saved search
- [ ] saved search should display data grid table
- [ ] view single document link is clickable and should see a single doc with two formats (JSON and table)
- [ ] view surrounding document link is clickable and should see surrounding documents

### Top Nav
- [ ] should display time range of first added saved search 
- [ ] change time range can update all saved searches
- [ ] filter can update all saved searches
- [ ] search query can search all saved searches

### Data grid table
- [ ] `filter for value` button in Table should work
- [ ] `filter out value` button in Table should work
- [ ] should sort
- [ ] should be able to move column, except `time` and `_source`
- [ ] should be able to remove column. If all columns (except `time`) are removed, should display default `_source`.
- [ ] pagination should work

### Context view
- [ ] when expand doc, `filter for value` should work
- [ ] when expand doc, `filter out value` should work
- [ ] when expand doc, toggle column should work
- [ ] when expand doc, exist button should work

### Panel Options
- [ ] should be able to edit search
- [ ] should be able to clone panel
- [ ] should be able to edit panel title
- [ ] should be able to remove a panel

**Comment by ananzh** [comment]
done with above PR. close this issue.
