### ISSUE TITLE
[MD] Install sample data to a data source

### ISSUE THREAD

**Issue by zengyan-amazon** [opensearch-project/OpenSearch-Dashboards#4240]
**Is your feature request related to a problem? Please describe.**
When multi-datasource feature is enabled, we want to allow users to install sample data to a data source.

**Describe the solution you'd like**
when installing sample data, we offer users an option to select a data source, and then install the sample data to that data source. 

**Additional context**
With https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4149 , the local data source in multi-datasource will no longer valid, thus we will need this feature to allow users to install sample data to a user defined data source

**Comment by kristenTian** [comment]
Went through the current flows and noted down couple pages will requires update when no sample data installed:



- Home page when no sample data installed:
http://localhost:5601/app/home#/

<img width="743" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105667444/3acda808-0e3d-48a3-9baf-eefbcc8d2084">

After click explore on my own or add sample data:
http://localhost:5601/app/home#/tutorial_directory
<img width="1602" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105667444/c21fe0bd-5bef-4942-aa7b-8d166bfe955a">

- Overview page 
http://localhost:5601/app/opensearch_dashboards_overview#/
<img width="1620" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105667444/e95c82ca-aa92-484b-9e61-99a3fedf1531">

- When trying to create index patterns:

**Comment by kristenTian** [comment]
Adding data source selection in add sample data page:

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105667444/6797b1e2-86ef-468b-bc25-8bbe79c79aa0)

**Comment by zhongnansu** [comment]
close as PR was merged
