### ISSUE TITLE
Post-release chore: Update CHANGELOG with new 2.8.0 sections

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#4263]
For `2.x` branch: 
- [ ] Update CHANGELOG in 2.x so that there's a `2.8.0` section that matches the `2.8.0` release notes. 
- [ ] Add 2.8.0 release date
- [ ] For any PRs released in 2.8.0, remove from the "Unreleased" section
- [ ] Validate that "Unreleased" section is accurate

For `main`  branch:
- [x] Validate that  `2.8.0` section matches the `2.8.0` release notes. 
- [x] Validate 2.8.0 release date
- [x] For any PRs released in 2.8.0, remove from the "Unreleased" section
- [x] Validate that "Unreleased" section is accurate

**Comment by zhongnansu** [comment]
@manasvinibs handing off the remaining work of this issue to current oncall

**Comment by joshuarrrr** [comment]
completed via #4283
