### ISSUE TITLE
[BUG] How to use `core.http.registerRouteHandlerContext` without breaking types?

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/OpenSearch-Dashboards#4274]
**Describe the bug**

I can't figure out how to register router handler context using server http without breaking type checks:

```typescript
  // Argument of type '"observability_plugin"' is not assignable to parameter of type '"core"'.
  core.http.registerRouteHandlerContext('observability_plugin', (context, request) => {});
```

Looking into signature of `registerRouteHandlerContext`,

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/55b293a2e52399c5c4101f5b3e643519c4531809/src/core/server/http/types.ts#L279-L282

`keyof RequestHandlerContext` is `'core'`, `T extends 'core'` restricts `T` to `'core'`, and `contextName: T` restricts contextName to be `'core'`. How would this work exactly? e.g. how to I allow `observability_plugin` to be a `contextName`?

**To Reproduce**

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by ashwin-pc** [comment]
@joshuali925 you need to extend the type for the `RequestHandlerContext`. e.g. 

```ts
declare module 'src/core/server' {
  interface RequestHandlerContext {
    dataSource: DataSourcePluginRequestContext;
  }
}
```

https://github.com/ashwin-pc/OpenSearch-Dashboards/blob/66139a6dbbbcb339387872b530801b3b0a1982c6/src/plugins/data_source/server/types.ts#L48-L52

**Comment by joshuali925** [comment]
just a note that `declare module` works in independent `plugins/` but won't work well in core `src/plugins/`, since doing this would modify `RequestHandlerContext` for every core plugin
