### ISSUE TITLE
Query Workbench Header says "OpenSearchDashboards"

### ISSUE THREAD

**Issue by seanneumann** [opensearch-project/OpenSearch-Dashboards#429]
The header for Query Workbench pages says "OpenSearchDashboards" (no space). It should say "Query Workbench".

![image](https://user-images.githubusercontent.com/1413295/120711529-58cccf80-c474-11eb-8654-82af6045503e.png)

**Comment by kavilla** [comment]
Fixed in https://github.com/opensearch-project/sql/issues/111.
