### ISSUE TITLE
[BUG] Dashboard/Dashboards naming convention in navigation pane & UI

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/OpenSearch-Dashboards#4296]
**Describe the bug**

What is the bug?
Inconsistent naming convention in the navigation pane versus UI

**How can one reproduce the bug?**
Open OpenSearch Dashboards, view main menu, select Dashboard, and then view UI.

**What is the expected behavior?**
Naming convention should be consistent.

**What is your host/environment?**
OpenSearch Dashboards v 2.8.0

**Additional context**
See comments in [UX issue #68](https://github.com/opensearch-project/ux/issues/68)

<img width="1553" alt="Screenshot 2023-06-15 at 4 49 04 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105296784/e07dcc9e-db4d-44d0-bf71-36442aa9efea">

**Comment by joshuarrrr** [comment]
From https://github.com/opensearch-project/ux/issues/68, the preferred term is Dashboards not Dashboard
