### ISSUE TITLE
[Feature Anywhere] Fix legacy tests

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/OpenSearch-Dashboards#4310]
Goal is to get feature branch have all consistent passing CI workflows. This is a requirement for merging into `main`/`2.x`.

Broken tests on `feature/feature-anywhere` branch as of 6/19 ([ref](https://github.com/opensearch-project/OpenSearch-Dashboards/actions/runs/5315191200/jobs/9623273627))

- [x] group 2 (linux + windows) (2 failing on `main`)
- [x] group 3 (linux + windows)
- [x] group 6 (linux + windows) (6 failing on `main`)
- [x] group 7 (linux + windows)
- [x] group 9 (linux + windows) (1 failing on `main`)
- [x] group 10 (linux + windows) (18 failing on `main`) (13 when re-running, probably flaky and some succeeded in my run)
- [x] group 11 (linux + windows) (8 failing on `main`)
- [x] group 12 (linux + windows) (14 failing on `main`)

Failures in main based off of [this run on 6/20](https://github.com/opensearch-project/OpenSearch-Dashboards/actions/runs/5273048338/jobs/9538940419) from #4268

**Comment by ohltyler** [comment]
After initial fixes in #4477: Still seeing failures for:
- [ ] CI 6 (9 failures vs. 6 on main)
- [ ] CI 7 (4 failures vs. 0 on main)
- [ ] CI 12 (15 failures vs. 14 on main)

Ref run: https://github.com/opensearch-project/OpenSearch-Dashboards/actions/runs/5328885666/jobs/9653998014

I will run all of these on my local to see which are flaky or which are actual failures

**Comment by ohltyler** [comment]
Able to reproduce CI 7 failures locally - looking into it

**Comment by ohltyler** [comment]
After latest commit in PR above ^ only same errors seen as on `main` are left.

**Comment by joshuarrrr** [comment]
@ohltyler Can this be closed via #4327 ?

**Comment by ohltyler** [comment]
Yes
