### ISSUE TITLE
[Vis colors] Replace heatmap color schemas with palettes generated with `colorPalette` and OUI color variables

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#4325]
Several OpenSearch Dashboards visualizations (VisLib Gauge, VisLib Goal, VisLib Heatmap, Metric) use color schemas from [getHeatmapColors()](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/charts/public/static/color_maps/heatmap_color.ts#LL69C13-L69C1).

see https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/charts/public/static/color_maps/color_maps.ts

and https://github.com/opensearch-project/oui/pull/601/ for visual examples and defaults.

Instead, we should use OUI's `colorPalette` service to generate similar palettes with OUI color variables as the source. We can also reduce the number of color stops to 20, and simplify much of the mapping.

**Comment by manasvinibs** [comment]
This [PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4293) addressed updating the maps color palette source to OUI. There are still utility functions, which does interpolate color maps in the charts plugin but it will be addressed as part of this issue https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2830. 
Resolving this one!
