### ISSUE TITLE
Visualization filter on OpenSearch Dashboard

### ISSUE THREAD

**Issue by asc0691** [opensearch-project/OpenSearch-Dashboards#4359]
I have created an OpenSearch dashboard with multiple visualizations and now i am facing an issue.
Whenever i click on any of the visualization it will filter out whole dashboard according to that visualization and there is not option to return from that filter.

Example :  I have a bar visualization showing three state, Open, Closed and WIP so if i will click on Open bar, this will apply filter to whole dashboard and there is no option to revert it apart from using back option.

I need help with below queries.
1. How can i disable these filters, so that clicking on any visualization won't filter whole dashboard
2. How can i revert the filter applied if i will use this feature.

OpenSearch dashboard version 2.6.0

**Comment by ashwin-pc** [comment]
@asc0691 simply going back in the browser should take you back to the dashboard before the filter was applied. I dont think there is an option to disable the filters today though. Feel free to reopen the issue if that does not work for you
