### ISSUE TITLE
[BUG] Breadcrumb behavior on dashboard is broken

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#4367]
**Describe the bug**

When we enter Edit mode in the dashboard page, the breadcrumb text should say `Editing dashboard_name`; only if we made some changes, then the breadcrumb text will append a `(unsaved)` string to the end thus change to `Editing dashboard_name(unsaved)`. 

This behavior was correct a while ago; however now on both main branch and 2.8 branch, the breadcrumb text always say `Editing dashboard_name(unsaved)` as soon as we enter edit mode, even with no changes being made.

Correct behavior according to this function, we get different breadcrumb texts based on if there are changes being made or not:
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/333e2b33e421f529a3f2c49c129f58d34640351f/src/plugins/dashboard/public/application/dashboard_strings.ts#L41 

```
export function getDashboardTitle(
  title: string,
  viewMode: ViewMode,
  isDirty: boolean,
  isNew: boolean
): string {
  const isEditMode = viewMode === ViewMode.EDIT;
  let displayTitle: string;
  const newDashboardTitle = i18n.translate('dashboard.savedDashboard.newDashboardTitle', {
    defaultMessage: 'New Dashboard',
  });
  const dashboardTitle = isNew ? newDashboardTitle : title;

  if (isEditMode && isDirty) {
    displayTitle = i18n.translate('dashboard.strings.dashboardUnsavedEditTitle', {
      defaultMessage: 'Editing {title} (unsaved)',
      values: { title: dashboardTitle },
    });
  } else if (isEditMode) {
    displayTitle = i18n.translate('dashboard.strings.dashboardEditTitle', {
      defaultMessage: 'Editing {title}',
      values: { title: dashboardTitle },
    });
  } else {
    displayTitle = dashboardTitle;
  }

  return displayTitle;
}

```

Wrong behavior: after enter edit mode, breadcrumb text always say `Editing dashboard_name(unsaved)`no matter if we made changes or not.

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/7c461213-c869-4d95-9ce4-ca3079fcf3d6

**Comment by joshuarrrr** [comment]
@kgcreative @KrooshalUX I know you have some eventual changes in mind for edit mode - but is this behavior something we need to fix as part of the current Dashboard refactoring?

**Comment by kgcreative** [comment]
We should definitely fix this in the short term. `(Unsaved)` should only be appended if changes have been made. An additional enhancement would be to also disable the "save" button until changes have been made as well, but that's an incremental "nice-to-have"

**Comment by abbyhu2000** [comment]
This is solved as part of the dashboard de-angular effort. The breadcrumb behavior works as expected now.
