### ISSUE TITLE
[RELEASE] Release version 2.9.0

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/OpenSearch-Dashboards#4486]
This is a component issue for 2.9.0.
Coming from https://github.com/opensearch-project/opensearch-build/issues/3616. Please follow the following checklist.
__Please refer to the DATES in that post__.

<details><summary>How to use this issue</summary>
<p>

## This Component Release Issue

This issue captures the state of the OpenSearch release, on component/plugin level; its assignee is responsible for driving the release. Please contact them or @mention them on this issue for help.
Any release related work can be linked to this issue or added as comments to create visiblity into the release status.

## Release Steps

There are several steps to the release process; these steps are completed as the whole component release and components that are behind present risk to the release. The component owner resolves the tasks in this issue and communicate with the overall release owner to make sure each component are moving along as expected.

Steps have completion dates for coordinating efforts between the components of a release; components can start as soon as they are ready far in advance of a future release. The most current set of dates is on the overall release issue linked at the top of this issue.

## The Overall Release Issue

Linked at the top of this issue, the overall release issue captures the state of the entire OpenSearch release including references to this issue, the release owner which is the assignee is responsible for communicating the release status broadly.  Please contact them or @mention them on that issue for help.

## What should I do if my plugin isn't making any changes?

If including changes in this release, increment the version on `2.x` branch to `2.9.0` for Min/Core, and `2.9.0.0` for components. Otherwise, keep the version number unchanged for both.

</p>
</details>

### Preparation

- [x] Assign this issue to a release owner.
- [x] Finalize scope and feature set and update [the Public Roadmap](https://github.com/orgs/opensearch-project/projects/1).
- [x] All the tasks in this issue have been reviewed by the release owner.
- [x] Create, update, triage and label all features and issues targeted for this release with `v2.9.0`.

### CI/CD

- [x] All code changes for `2.9` are complete.
- [x] Ensure working and passing CI.
- [x] Check that this repo is included in the [distribution manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/__REPLACE_MAJOR_MINOR_PATCH__).

### Pre-Release

- [x] Update to the `2.9.0` release branch in the [distribution manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.9.0).
- [x] Increment the version on the parent branch to the next development iteration.
- [x] Gather, review and publish release notes following the [rules](https://github.com/opensearch-project/opensearch-plugins/blob/main/RELEASE_NOTES.md) and back port it to the release branch.[git-release-notes](https://github.com/ariatemplates/git-release-notes) may be used to generate release notes from your commit history.
- [x] Confirm that all changes for `2.9.0` have been merged.
- [ ] Add this repo to the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/) for the next developer iteration.

### Release Testing

- [ ] Find/fix bugs using latest tarball and docker image provided in parent release issue and update the release notes if necessary.
- [ ] Code Complete: Test within the distribution, ensuring integration, backwards compatibility, and performance tests pass.
- [x] Sanity Testing: Sanity testing *and* fixing of critical issues found.
- [ ] File issues for all intermittent test failures.

### Release

- [ ] Complete [documentation](https://github.com/opensearch-project/documentation-website).
- [ ] Verify all issued labeled for this release are closed or labelled for the next release.
- [ ] Verify the release date mentioned in release notes is correct and matches actual release date.

### Post Release

- [ ] Prepare for an eventual security fix development iteration by incrementing the version on the release branch to the next eventual patch version.
- [ ] Add this repo to the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/) of the next eventual security patch version.
- [ ] [Suggest improvements](https://github.com/opensearch-project/opensearch-build/issues/new) to [this template](https://github.com/opensearch-project/opensearch-build/blob/main/.github/ISSUE_TEMPLATE/component_release_template.md).
- [ ] Conduct a retrospective, and publish its results.

**Comment by manasvinibs** [comment]
with security
```
curl -X GET https://localhost:9200 -u 'admin:admin' --insecure
{
  "name" : "ip-172-31-62-57",
  "cluster_name" : "opensearch",
  "cluster_uuid" : "LOnshKtjTl6Xf64Y0STiVw",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.9.0",
    "build_type" : "tar",
    "build_hash" : "cb6d891de16a34704a6513769c2e2c44df9ba1d0",
    "build_date" : "2023-07-14T18:15:43.508806642Z",
    "build_snapshot" : false,
    "lucene_version" : "9.7.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

```
curl -X GET https://localhost:9200/_cat/plugins?v -u 'admin:admin' --insecure
name            component                            version
ip-172-31-62-57 opensearch-alerting                  2.9.0.0
ip-172-31-62-57 opensearch-anomaly-detection         2.9.0.0
ip-172-31-62-57 opensearch-asynchronous-search       2.9.0.0
ip-172-31-62-57 opensearch-cross-cluster-replication 2.9.0.0
ip-172-31-62-57 opensearch-geospatial                2.9.0.0
ip-172-31-62-57 opensearch-index-management          2.9.0.0
ip-172-31-62-57 opensearch-job-scheduler             2.9.0.0
ip-172-31-62-57 opensearch-knn                       2.9.0.0
ip-172-31-62-57 opensearch-ml                        2.9.0.0
ip-172-31-62-57 opensearch-neural-search             2.9.0.0
ip-172-31-62-57 opensearch-notifications             2.9.0.0
ip-172-31-62-57 opensearch-notifications-core        2.9.0.0
ip-172-31-62-57 opensearch-observability             2.9.0.0
ip-172-31-62-57 opensearch-performance-analyzer      2.9.0.0
ip-172-31-62-57 opensearch-reports-scheduler         2.9.0.0
ip-172-31-62-57 opensearch-security                  2.9.0.0
ip-172-31-62-57 opensearch-security-analytics        2.9.0.0
ip-172-31-62-57 opensearch-sql                       2.9.0.0
```
without security
```
curl -X GET http://localhost:9200
{
  "name" : "ip-172-31-62-57",
  "cluster_name" : "opensearch",
  "cluster_uuid" : "LOnshKtjTl6Xf64Y0STiVw",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.9.0",
    "build_type" : "tar",
    "build_hash" : "cb6d891de16a34704a6513769c2e2c44df9ba1d0",
    "build_date" : "2023-07-14T18:15:43.508806642Z",
    "build_snapshot" : false,
    "lucene_version" : "9.7.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```
```
curl -X GET http://localhost:9200/_cat/plugins?v
name            component                            version
ip-172-31-62-57 opensearch-alerting                  2.9.0.0
ip-172-31-62-57 opensearch-anomaly-detection         2.9.0.0
ip-172-31-62-57 opensearch-asynchronous-search       2.9.0.0
ip-172-31-62-57 opensearch-cross-cluster-replication 2.9.0.0
ip-172-31-62-57 opensearch-geospatial                2.9.0.0
ip-172-31-62-57 opensearch-index-management          2.9.0.0
ip-172-31-62-57 opensearch-job-scheduler             2.9.0.0
ip-172-31-62-57 opensearch-knn                       2.9.0.0
ip-172-31-62-57 opensearch-ml                        2.9.0.0
ip-172-31-62-57 opensearch-neural-search             2.9.0.0
ip-172-31-62-57 opensearch-notifications             2.9.0.0
ip-172-31-62-57 opensearch-notifications-core        2.9.0.0
ip-172-31-62-57 opensearch-observability             2.9.0.0
ip-172-31-62-57 opensearch-performance-analyzer      2.9.0.0
ip-172-31-62-57 opensearch-reports-scheduler         2.9.0.0
ip-172-31-62-57 opensearch-security                  2.9.0.0
ip-172-31-62-57 opensearch-security-analytics        2.9.0.0
ip-172-31-62-57 opensearch-sql   
```

**Comment by manasvinibs** [comment]
![Screenshot 2023-07-14 at 3 57 13 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105884062/e9a5e400-d73e-40ea-8587-cc99288f56f8)
![Screenshot 2023-07-14 at 3 57 26 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105884062/8038bace-2182-41e9-a8cd-5bc08d293c58)

**Comment by manasvinibs** [comment]
```
curl -X GET https://localhost:9200 -u 'admin:admin' --insecure
{
  "name" : "ip-172-31-62-57",
  "cluster_name" : "opensearch",
  "cluster_uuid" : "8rfLvQupRVa5lUToQGRb0Q",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.9.0",
    "build_type" : "tar",
    "build_hash" : "1164221ee2b8ba3560f0ff492309867beea28433",
    "build_date" : "2023-07-18T21:23:29.367080729Z",
    "build_snapshot" : false,
    "lucene_version" : "9.7.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

**Comment by manasvinibs** [comment]
```
curl -X GET https://localhost:9200/_cat/plugins?v -u 'admin:admin' --insecure
name            component                            version
ip-172-31-62-57 opensearch-alerting                  2.9.0.0
ip-172-31-62-57 opensearch-anomaly-detection         2.9.0.0
ip-172-31-62-57 opensearch-asynchronous-search       2.9.0.0
ip-172-31-62-57 opensearch-cross-cluster-replication 2.9.0.0
ip-172-31-62-57 opensearch-geospatial                2.9.0.0
ip-172-31-62-57 opensearch-index-management          2.9.0.0
ip-172-31-62-57 opensearch-job-scheduler             2.9.0.0
ip-172-31-62-57 opensearch-knn                       2.9.0.0
ip-172-31-62-57 opensearch-ml                        2.9.0.0
ip-172-31-62-57 opensearch-neural-search             2.9.0.0
ip-172-31-62-57 opensearch-notifications             2.9.0.0
ip-172-31-62-57 opensearch-notifications-core        2.9.0.0
ip-172-31-62-57 opensearch-observability             2.9.0.0
ip-172-31-62-57 opensearch-performance-analyzer      2.9.0.0
ip-172-31-62-57 opensearch-reports-scheduler         2.9.0.0
ip-172-31-62-57 opensearch-security                  2.9.0.0
ip-172-31-62-57 opensearch-security-analytics        2.9.0.0
ip-172-31-62-57 opensearch-sql
```

**Comment by manasvinibs** [comment]
![Screenshot 1](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105884062/b7ee2eff-aada-4dbe-b056-e8fd50e28f4d)

![Screenshot 2](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105884062/b57251fc-e031-4a42-8cd9-05342d4b76c7)

![Screenshot 3](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105884062/dad06144-6e00-4d82-a576-a36524b88d6a)
