### ISSUE TITLE
[BUG] Re2 Requires wrong NODE_MODULE_VERSION

### ISSUE THREAD

**Issue by sdbruder** [opensearch-project/OpenSearch-Dashboards#4518]
**Describe the bug**

regular expressions using re2 module fail. re2 was built with NODE_MODULE_VERSION 83 while opensearch dashboards 2.8.0 was built with NODE_MODULE_VERSION 93.

**To Reproduce**
1. On opensearch-dashboards 2.8.0 (from the published container), create a dashboard
2. Add a timeline with a regular expression
3. See error

**Expected behavior**
actual executable and correct regular expressions,

**OpenSearch Version**
Opensearch 2.8.0 from container `opensearchproject/opensearch:2.8.0`.

**Dashboards Version**
Opensearch Dashboards 2.8.0 from container `opensearchproject/opensearch-dashboards:2.8.0`

**Host/Environment (please complete the following information):**
- Actual official containers, so server OS is Amazon Linux release 2 (Karoo).
- Browser here does not matter, it's a server side issue (but reproduced with both Chrome and Firefox).

**Additional context**

The actual error message:

```
[timeline_vis] > Timeline request error: undefined Error: in cell #1: The module 
‘/usr/share/opensearch-dashboards/node_modules/re2/build/Release/re2.node’ 
was compiled against a different Node.js version using NODE_MODULE_VERSION 83. 
This version of Node.js requires NODE_MODULE_VERSION 93. Please try re-compiling 
or re-installing the module (for instance, using npm rebuild or npm install).
```

**Comment by AMoo-Miki** [comment]
`re2` was to be removed from the 2.8.0 release but looking at https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4208, it didn't make it to the release.

Based on the error message, Node.js v16 is used at runtime but Node.js v14 was used to build the dependencies which is odd. I will investigate this.

**Comment by smortex** [comment]
Sample timeline expression that reproduce the error:

```
.opensearch().label(regex="(.*)")
```

**Comment by AMoo-Miki** [comment]
@ananzh, am i right to say 2.9.0 was released without re2 and that this issue can be closed now?

**Comment by smortex** [comment]
> @ananzh, am i right to say 2.9.0 was released without re2 and that this issue can be closed now?

@AMoo-Miki I confirm it is fixed and can be closed, thanks.

**Comment by AMoo-Miki** [comment]
Thanks @smortex
