### ISSUE TITLE
[MD] Issue connecting to data source cluster with self-signed certificates

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/OpenSearch-Dashboards#4524]
I had problems creating a data source connection to an OpenSearch with HTTPS protocol (created with a self-signed certificate). I received this problem:

<img src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/94870017/968e886e-185f-4583-ba0c-a3f1778b3ec4" alt="drawing" width="350"/>

Response:

```json
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Data Source Error: unable to verify the first certificate",
    "attributes": {
        "error": "Data Source Error: unable to verify the first certificate"
    }
}
```

> **observation**: 
> I tested the communication in the `opensearch-dashboard` terminal. 
> I executed `$ curl -k https://opensearch-b:9200` and worked it.

---

When I configure a new data source connection to an OpenSearch with HTTPS protocol with a valid certificate, it works as expected. It also works when I configure OpenSearch with HTTP protocol.

<img src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/94870017/6ae56e4a-cb64-40ea-9845-ef4f6ca5b338" alt="drawing" width="350"/>

---

Do you have some tips or suggestions? Is it a requirement that the data source connection with HTTPS must have a valid certificate? I did not find this information in the [documentation](https://opensearch.org/docs/latest/dashboards/discover/multi-data-sources/).

> - OpenSearch: 2.8.0
> - OpenSearch-Dashboards: 2.8.0
> - _Tests made on docker-compose_

_Originally posted by @carlos-neto-trustly in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2829#issuecomment-1611585079_

**Comment by zhongnansu** [comment]
Even with `opensearch.ssl.certificateAuthorities: ['path/to/root-ca.pem']` configured in `opensearch-dashboards.yml`. It will still fail. The issues are, 
1. Datasource clients is configured to always validate certificate.
2. The ssl config in yml is not being passed to data source client

Those issues can also be part of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2009, that we should have a way to support configuration of datasource clients, including SSL configuration

**Comment by augustoliks** [comment]
Hello! @zhongnansu 

I created a docker-compose lab to reproduce the Issue description.

- https://github.com/augustoliks/lab-opensearch/tree/main/multi-data-source-bug

> FYI: I'm @carlos-neto-trustly.

**Comment by Martin-Kemp** [comment]
I have the same issue. The setting `opensearch.ssl.verificationMode: none` is clearly not being used for datasources.

**Comment by Martin-Kemp** [comment]
Workaround as described by [carlos-neto-trustly](https://github.com/carlos-neto-trustly) [here](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2829):

Set and environment variable `NODE_EXTRA_CA_CERTS=/path/to/CAs` when starting your container.

Node docs: https://nodejs.org/api/cli.html#node_extra_ca_certsfile

This worked for me.

**Comment by uzhinskiy** [comment]
Hi. 
We are using 2 similar opensearch-clusters v2.10 - 'clusterA' and 'clusterB'. The 'clusterB' runs with enabled option ````plugins.security.ssl.http.clientauth_mode: REQUIRE````.
When we try to create a data source in opensearchdashboardA we get an error:

````Data Source Error: C0475B41D77F0000:error:0A000412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1605:SSL alert number 42````

Settings for opensearch_dashboards.yml in the "clusterA":
````
    opensearch.ssl.verificationMode: none
    opensearch.ssl.alwaysPresentCertificate: true
    opensearch.ssl.certificateAuthorities: [ "/usr/share/opensearch-dashboards/config/elk-root-ca.pem", "/usr/share/opensearch-dashboards/config/remote-root.pem" ]
    data_source.enabled: true
````
We also tried setting env for opensearch-dashboards in clusterA, but without success:
````
NODE_TLS_REJECT_UNAUTHORIZED=0
NODE_EXTRA_CA_CERTS=/usr/share/opensearch-dashboards/config/remote-root.pem
````

The remote-root.pem contains chain of  certificate for clusterB's opensearch.

However, adding the datasource works correctly with ````plugins.security.ssl.http.clientauth_mode: clientauth_mode: OPTIONAL```` in clusterB and set NODE_EXTRA_CA_CERTS variable .

Is it possible to set up 'datasource' when a remote cluster using ````plugins.security.ssl.http.clientauth_mode: REQUIRE````?

**Comment by cwperks** [comment]
I ran into this issue while looking into setting up multiple datasources when the security-dashboards-plugin is installed. I left a comment on the issue in the security-dashboards-plugin repo that has a zip containing a docker setup with 2 clusters that demonstrates the issue. https://github.com/opensearch-project/security-dashboards-plugin/issues/1782#issuecomment-1960352348

**Comment by derek-ho** [comment]
+1 if we can prioritize a fix that would be awesome! I think ideally the client should be using the same settings as the connection to the local cluster specified in the dashboards configuration.

**Comment by derek-ho** [comment]
> This is due to ssl config for rejectUnauthorized is hardcoded as true for now in data source client config, tested that changing this to false will not validate the certificate. Thus to solve this, we can expose a property `data_source.ssl.rejectUnauthorized` which will pass over to ssl configuration so that this behavior can be configured. The `opensearch.ssl.verificationMode:none` is the same as configuring ssl.rejectUnauthorized as false, see ref
> 
> https://github.com/opensearch-project/OpenSearch-Dashboards/blob/735424bcaabfc752453c4d514ddd5d4b4f1b6d6d/src/core/server/opensearch/client/client_config.ts#L137
> 
> The reason I think a new config is better is because opensearch.ssl.verificationMode is for local cluster setting, while we are actually configure for connected data sources here. But open to other suggestions, @derek-ho @cwperks

Thanks. That should work, and I agree that we may want different values for different datasource that is not the backing one. However, this begs this question - would this apply to all datasources? If that is the case and not specific to a datasource, I think we should call it out in the documentation that we are assuming all datasources are compatible with the ssl setting. I know that @cwperks had the same question for TLS settings - are we assuing/calling it out that a built in assumption is that the config works for all datasources?

**Comment by cwperks** [comment]
@BionIT For ultimate flexibility, TLS would need to be configured on a per data-source basis. Would `data_source.ssl.rejectUnauthorized: false` disable SSL verification for all connected data-sources? 

I am thinking about TLS configuration in 2 ways:

1. TLS configuration is common across all configured data-sources so it only needs to be configured once
2. If flexibility is needed per-datasource then there would also need to be a way to configure TLS per data-source.

**Comment by cwperks** [comment]
When configuring TLS for Dashboards, there are 2 separate traffic flows that need to be secured:

1. From the user's browser to OpenSearch Dashboards
2. From Dashboards to the backend data-source

For 2, ultimate flexibility would mean configuring this per data-source, but there could be a common configuration for multiple data-sources.

The settings to configure 2) are:

**SSL Verification Mode**: This setting allows you to specify how OpenSearch Dashboards verifies the certificates from OpenSearch nodes.

```
opensearch.ssl.verificationMode: full
```

_full_: (Default) Verifies that the provided certificate is signed by a trusted authority (CA), that the certificate is not expired, and that the common name (CN) or subject alternative name (SAN) matches the requested hostname.
_certificate_: Verifies that the provided certificate is signed by a trusted authority (CA), but does not perform hostname verification.
_none_: Does not perform any verification.

**SSL Certificate Authorities**: If you're using self-signed certificates or certificates signed by your organization's CA, you need to specify the path to the CA certificate(s) used to sign the certificates for OpenSearch nodes.

```
opensearch.ssl.certificateAuthorities: ["/path/to/your/ca.pem"]
```

-----

This next one is only required is [clientcert auth](https://opensearch.org/docs/latest/security/authentication-backends/client-auth/) is set to REQUIRED. 

**Client Certificate and Key**: Specify the paths to the certificate and key files that OpenSearch Dashboards will use to authenticate itself to the OpenSearch cluster.

```
opensearch.ssl.certificate: "/path/to/your/client.crt"
opensearch.ssl.key: "/path/to/your/client.key"
```

**Comment by seraphjiang** [comment]
close as per https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6171
