### ISSUE TITLE
[BUG] `yarn opensearch snapshot` fails on Mac Os

### ISSUE THREAD

**Issue by devardee** [opensearch-project/OpenSearch-Dashboards#4533]
**Describe the bug**

`yarn opensearch snapshot` fails on (Darwin) Mac Os

**To Reproduce**
run the below command on Mac
```
>yarn opensearch snapshot
yarn run v1.22.19
$ node scripts/opensearch snapshot
 info Installing from snapshot
   │ info version: 2.5.0
   │ info install path: /Users/devardee/IdeaProjects/OpenSearch-Dashboards/.opensearch/2.5.0
   │ info license: oss
   │ERROR Snapshots are only available for Linux and Windows
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


```

**Expected behavior**
[Developer guide](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md#run-opensearch) suggest the cmd should run fine even on Mac

**Dashboards Version**
`2.5.0`

**Host/Environment (please complete the following information):**
 - OS: [iOS]

**Comment by gulderov** [comment]
`yarn opensearch snapshot` would work only if you have Intel version

**Comment by devardee** [comment]
> `yarn opensearch snapshot` would work only if you have Intel version
I am using the intel version

**Comment by ananzh** [comment]
Hey @devardee thank you for reaching out. We start to support macOS from 2.6. In 2.5, you will see a cli error 
```
if (!SUPPORTED_PLATFORMS.includes(platform)) {
    throw createCliError(`Snapshots are only available for Linux, Windows, and Darwin`);
  }
```

The developer guide you linked is from main which includes all the latest progress. If you change version to 2.5, then you could see macOS is not in the support system. The minimal version if you need to run OSD on mac is 2.6. I just give a try and it works well. Let us know if you have other questions. 😄

**Comment by devardee** [comment]
oh I see, makes sense, closing the issue. Thanks @ananzh  !!
