### ISSUE TITLE
[Dashboard De-Angular] Remove angular bootstrap line when Discover is completely de-angularized

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#4597]
Remove `initAngularBootstrap()`  in the plugin.tsx after Discover is completely de-angularized. This is needed to render the saved search visualization(created from Discover) correctly on the dashboard. 

```
    // TODO: delete this when discover de-angular is completed
    initAngularBootstrap();
```

**Comment by ashwin-pc** [comment]
Fixed in #4982
