### ISSUE TITLE
(OUI Next Theme) Application Loading State

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/OpenSearch-Dashboards#4634]
_This issue to be transferred to corresponding repository_

I am working on launching new light and dark mode themes provided by [OUI component library](https://oui.opensearch.org/1.2/#/) for a target launch within 2.10. These changes support the vision expressed in [Future Vision for Dashboards](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4298.)

I have identified the following front end related issues that prevent the theme from appearing complete and potential solutions within this feature:

- [ ] While in dark mode the OpenSearch logo should display the dark mode variant
<img width="653" alt="Screen Shot 2023-07-25 at 3 26 33 PM" src="https://github.com/opensearch-project/oui/assets/105819041/3fc398be-33b0-4bf3-ae75-925717d20b37">

**Comment by joshuarrrr** [comment]
Fixed by https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4702
