### ISSUE TITLE
[BUG]cannot  remove securityDashboards  in opensearch-dashboards:1.0.0-rc1 

### ISSUE THREAD

**Issue by DavidSche** [opensearch-project/OpenSearch-Dashboards#465]
**Describe the bug**

I cannot  remove securityDashboards  in opensearch-dashboards:1.0.0-rc1 , it's ok in  opensearch-dashboards:1.0.0-beta1 

I uses this Dockerfile 

```
FROM opensearchproject/opensearch-dashboards:1.0.0-rc1
RUN /usr/share/opensearch-dashboards/bin/opensearch-dashboards-plugin remove securityDashboards
COPY --chown=opensearch-dashboards:opensearch-dashboards opensearch_dashboards.yml /usr/share/opensearch-dashboards/config/
``` 
the opensearch_dashboards.yml  

```
server.name: opensearch-dashboards
server.host: "0"
```

**To Reproduce**

when I run opensearch-dashboards-plugin  list  command , the securityDashboards plugin is in list ;but cannot remove 
``` shell
[opensearch-dashboards@90784366e4db bin]$ ./opensearch-dashboards-plugin list                      
alertingDashboards@1.0.0.0-rc1
anomalyDetectionDashboards@1.0.0.0-rc1
ganttChartDashboards@1.0.0.0-rc1
indexManagementDashboards@1.0.0.0-rc1
notebooksDashboards@1.0.0.0-rc1
queryWorkbenchDashboards@1.0.0.0-rc1
reportsDashboards@1.0.0.0-rc1
securityDashboards@1.0.0.0-rc1
traceAnalyticsDashboards@1.0.0.0-rc1

[opensearch-dashboards@90784366e4db bin]$ ./opensearch-dashboards-plugin remove securityDashboards 
Unable to remove plugin because of error: "Plugin [securityDashboards] is not installed"
[opensearch-dashboards@90784366e4db bin]$ 

```

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by kavilla** [comment]
Hey David,

Thanks for opening this up. I definitely see the confusion. The value listed in the plugins cli does not match the actual plugin.

As you can see in this PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/357 we converted to kebab case based on github.com/opensearch-project/OpenSearch-Dashboards/issues/322.

This is technically a duplicate of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/366.

The solution is to have your Dockerfile like the following:
```
FROM opensearchproject/opensearch-dashboards:1.0.0-rc1
RUN /usr/share/opensearch-dashboards/bin/opensearch-dashboards-plugin list
RUN /usr/share/opensearch-dashboards/bin/opensearch-dashboards-plugin remove security-dashboards
RUN /usr/share/opensearch-dashboards/bin/opensearch-dashboards-plugin list
COPY --chown=opensearch-dashboards:opensearch-dashboards opensearch_dashboards.yml /usr/share/opensearch-dashboards/config/
```

Will need to bring it up github.com/opensearch-project/OpenSearch-Dashboards/issues/322 about the confusing output versus the actual value.

**Comment by kavilla** [comment]
Let me know if it is acceptable if I close this issue using this [issue](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/322#issuecomment-859919937) to track it.

**Comment by DavidSche** [comment]
thanks @kavilla ,  your Dockerfile is ok !  thanks !

**Comment by kavilla** [comment]
No problem! Thanks for bringing this up. 

Will close this issue and will use https://github.com/opensearch-project/OpenSearch-Dashboards/issues/322 to track it, if you could please keep track of the outcomes there or comment your opinion please do!

Otherwise, if you still run into issues and not sure where to comment please feel free to re-open this issue.
