### ISSUE TITLE
[De angular] Remove the angular dependency

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#4664]
This issue is to remove the final angular dependency from the package.json

**Comment by nitin-pandita** [comment]
I am up for it please assign this to me

**Comment by ashwin-pc** [comment]
@nitin-pandita This is the final task in a list of tasks that are related to the deangularizing the repository. Before this step we need to make sure that all the angular components within the codebase are migrated. You can see the list of tasks in https://github.com/orgs/opensearch-project/projects/119. 

If you are interested in helping with the effort can you take a look at [[Deangular] Tile map and region map](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4665)?

**Comment by nitin-pandita** [comment]
> e need to

@ashwin-pc thank you for your reply, I will look into it
