### ISSUE TITLE
[Deangular] Tile map and region map

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#4665]
## Work left

- [ ] Remove angular-sanitize from tile_map plugin
- [ ] Clean out opensearch_dashboards_legacy usages in tile map and region map

**Comment by ananzh** [comment]
I created an issue in our map team https://github.com/opensearch-project/dashboards-maps/issues/459 since I see a TODO in tile map code.
```
// TODO: Determine why visualizations don't populate without this
import 'angular-sanitize';
```
We should notify map team and let them investigate how this would break them.
