### ISSUE TITLE
Inform users of theme "Next" preview 

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/OpenSearch-Dashboards#4676]
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105819041/af613e66-69a9-4c9e-9521-82741284e69b)

- At first time user experience, present user with modal that describes the theme "Next" preview, including images of light and dark modes 
- Include messaging that instructs users on how to revert to v7 theme (current them)
- Include link feedback mechanism about the theme and theme modes 
- Include link to related documentation 
- In the absence of a user object, store the dismissal of the modal locally. Users will see the modal again if local data is cleared or a new device is used to access their instance of OpenSearch Dashboards

**Comment by wbeckler** [comment]
If the plan for 2.11 is to default to dark mode, it might help to ask people to try it out and give feedback on the [dark mode issue](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4454).

**Comment by KrooshalUX** [comment]
@wbeckler Sure, I can work on copy edits to call out dark mode more explicitly. 

As for driving to feedback, I have proposed a feedback link in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4330 (both the long and short term implementation options). We discussed that GitHub is often a barrier to entry for feedback and recommend using the forums instead (this lines up with the same strategy established for Experimental Features). 

Are you OK if we link to the Dark Mode GitHub issue in the forum post?

**Comment by wbeckler** [comment]
Definitely

**Comment by joshuarrrr** [comment]
Some initial thoughts about how I plan to implement:

1. This modal will be added to the `home` plugin and only appear on the home page. This will prevent getting in users way when they're trying to directly navigate to a deep link in the app.
2. It's not a blocker for the initial tech work, but we'll need to define both new links (documentation - see https://github.com/opensearch-project/documentation-website/issues/4728, feedback forum link - see https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4330)
3. I assume the close button in the top right and the "Dismiss" button should have the same effect. Is this correct?
