### ISSUE TITLE
Switch default theme to "Next" from "V7"

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/OpenSearch-Dashboards#4677]
- In version release 2.10, users should see "Next" theme as provided by OUI theme system as default theme 
- Users who have previous installations of OpenSearch Dashboards should have their previously chosen Dark or Light mode theme preferences retained

**Comment by mustafaazad03** [comment]
Hi,
I understand the issue, I would like to solve this issue.

**Comment by wbeckler** [comment]
@mustafaazad03, what approach were you thinking?

**Comment by wbeckler** [comment]
@mustafaazad03, what approach were you thinking?

**Comment by joshuarrrr** [comment]
@mustafaazad03 Thanks for volunteering! We'll need this on a relatively short deadline. Do you think you'll be able to complete it this week? I'll go ahead and assign it for now, but we may have someone else grab it if the timeline doesn't work for you.

**Comment by mustafaazad03** [comment]
> @mustafaazad03, what approach were you thinking?

I am thinking that what changes were made earlier so that this issue happened and accordingly I make some changes so that this issue will resolve without affecting any new update.

**Comment by joshuarrrr** [comment]
I went ahead and created the PR.
