### ISSUE TITLE
[BUG] no menu on Dashboard View / saved search at Table

### ISSUE THREAD

**Issue by MSchlick** [opensearch-project/OpenSearch-Dashboards#4688]
**Describe the bug**

When I added a Table-View to the dashboard, no menu get shown.
Function was given at previous version.

**To Reproduce**
1. Save Table at Discover
2. Add it to a Dashboard
3. Click at ... at the table in dashboard-view
4. See error in Web-Console

**Error**
```
embeddable.plugin.js:6 TypeError: Cannot read properties of undefined (reading 'data')
    at isEligibleForVisLayers (alertingDashboards.plugin.js:44:359259)
    at _callee$ (alertingDashboards.plugin.js:6:868034)
    at tryCatch (queryWorkbenchDashboards.plugin.js:2:2179)
    at Generator._invoke (queryWorkbenchDashboards.plugin.js:2:1802)
    at Generator.next (queryWorkbenchDashboards.plugin.js:2:2954)
    at asyncGeneratorStep (alertingDashboards.plugin.js:6:866337)
    at _next (alertingDashboards.plugin.js:6:866648)
    at alertingDashboards.plugin.js:6:866798
    at new Promise (<anonymous>)
    at Object.<anonymous> (alertingDashboards.plugin.js:6:866560)
```

**Expected behavior**
Open menu with inspection an maximize panel

**OpenSearch Version**
2.9.0

**Dashboards Version**
2.9.0

**Host/Environment (please complete the following information):**
 - OS: Rhel
 - Browser and version chrome, edge, firefox

**Additional context**

Same error on every three installations.  2x new installations, 1x update from 2.8 .
Function at 2.8 was okay.

**Comment by joshuarrrr** [comment]
@ohltyler Can you take a look at this and/or assign to someone who worked on the anywhere feature? This appears to be a regression.

**Comment by juergen-walter** [comment]
I can confirm this regression after update to 2.9.0 (independent of @MSchlick) 

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4694 affects the same js file, also after update 2.9.0. You might want to look a them together.

**Comment by ohltyler** [comment]
@lezzago can you help take a look? Looks like an NPE in alerting plugin.

**Comment by lezzago** [comment]
@MSchlick I have pushed out a fix from the above PR. 
I have provided the updated 2.9 alerting dahsboards artifact [here](https://github.com/opensearch-project/alerting-dashboards-plugin/pull/684#issuecomment-1674937659), for you to update the cluster with the new plugin. This should resolve the issue you are having. 

Additionally, you may use the source code for the [2.9 branch](https://github.com/opensearch-project/alerting-dashboards-plugin/tree/2.9) to build the artifact and reinstall it on your 2.9 cluster.

**Comment by MSchlick** [comment]
Fix from @lezzago is working
