### ISSUE TITLE
`Overview` units tests are insufficient

### ISSUE THREAD

**Issue by AMoo-Miki** [opensearch-project/OpenSearch-Dashboards#4693]
[`Overview`](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/opensearch_dashboards_overview/public/components/overview/overview.tsx) is pretty complicated and the [unit tests](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/opensearch_dashboards_overview/public/components/overview/overview.test.tsx) don't deal with any of the complications.

#### Requirements
* Add more unit tests to handle the features within overview

**Comment by thanhinhchtom** [comment]
Can I try this?
