### ISSUE TITLE
[BUG] [Data Explore] scope history on legacy discover plugin is broken

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#4698]
**Describe the bug**

The save window on legacy discover plugin is not the same as previous one, the current one does not allow save as new toggle, and is causing some function tests to fail. Therefore, we can never edit and save an existing saved search, it always ends up saving a new saved search.

Current one: 
![Screenshot 2023-08-08 at 4 32 19 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/6ae33ab1-af7a-43d0-9cce-936845341377)

Expected one/previous one: 

![Screenshot 2023-08-08 at 4 30 56 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/240b7e1f-6e5b-4fdd-9fe9-17d826f04c05)

**Comment by ashwin-pc** [comment]
I'm not able to repro this either. Here are my steps, let me know if i need to change it:
1. Ensure that you are on legacy discover
2. Save a search
3. After its saved, click on save again
4. See the screen below

![Screenshot 2023-08-09 at 2 48 17 AM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/20453492/b7ca3c23-c337-401f-b1ac-ab51d4985920)

**Comment by abbyhu2000** [comment]
Pulled down the latest change from the feature branch, now the save search window works as expected.

**Comment by abbyhu2000** [comment]
However, i thought there is another bug related to this: in one functional test, it saved a saved search first on discover, then navigate to dashboard page to add that saved search to the dashboard, and save the dashboard. Then go back to discover page by clicking the discover tab in the side menu. It should directly go back to that saved search page, so then when we make modifications, the save window will show the save as new toggle. However, now in the legacy discover, the scope history seem to be lost, and clicking the discover tab in the side menu wont take us to the saved search page anymore, it will only take us to the general discover page. Thus now when we click save, the save window will not show save as new toggle, cuz it thinks this is a new saved search. 

In previous discover:

Uploading Screen Recording 2023-08-09 at 10.37.19 PM.mov…



In the current legacy discover:

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/3e20d3d8-72c6-4381-9183-9fd0222a0ca5

**Comment by ashwin-pc** [comment]
Since legacy discover will be removed in 2.11, this issue wont be fixed.
