### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Julien-athstat** [opensearch-project/OpenSearch-Dashboards#4705]
**Describe the bug**

I am using the TSVB markdown visualisation to link to a 3rd party (partner) website, which has white-listed our domains to open their tool where there are some of our customers data (videos).
When I set the TSBV to Open in a new tab, my 3rd party session is denied. I tested with my 3rd party partner and this is because there no referral passed through.
Inspecting the elements create by these links, there are settings which block this.
For the moment, I have to use the link NOT opening in a new tab, but this should be a work around and not the solution.
The issue is: rel= noreferrer

**To Reproduce**
In Visualize:
- click create visualization
- select TSVB
- select Markdown
- in the Markdown text box create a link: [Link NO new tab](https://www.xxxxxx)
- go to Panel options and set Open in new tab set to NO
- create another TVSB Markdown: [Link WITH new tab](https://www.xxxxxx)
- go to Panel options and set Open in new tab set to YES

Looking at these through a webbrowser dev tool, you will see:
<a href="https://www.xxxxxx=">Link NO new tab</a>
<a href="https://www.xxxxxx" target="_blank" rel="noopener noreferrer">Link WITH new tab</a>

**Expected behavior**
The Link opening in a new tab option should not have the rel="noreferrer" as it is used by partners 3rd parties whitelisting our domain

**OpenSearch Version**
v 1.2.0
**Dashboards Version**
v 1.2.0

**Host/Environment (please complete the following information):**
 - OS: MacOS
 - Browser and version: Chrome Version 114.0.5735.248 (Official Build) (x86_64)

**Comment by AMoo-Miki** [comment]
`rel="noreferrer"` is combo of privacy and security measures. I don't see it being removed or being made configurable. However, if you feel strongly about being able to disabe the privacy via a switch that would satisfy security with `rel="noopener"`, you are more than welcome to raise a PR.
