### ISSUE TITLE
[Data Explorer] `filter for value` and `filter out value` options are not visible in the discover table

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#4775]
For the `filter for value` and `filter out value`, I see if we expand the document, then we can add the two filters there in the document details fly-out. 

However, previously the legacy discover can have the `filter for value` and `filter out value` on each document cell from the table itself without needing to expand the document. I guess this is a UX decision to see if we still want to have the options to add those two filters on each table cell. 

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/f8ad67b4-768b-421a-ab18-7f1bdd0c0ad2

**Comment by ananzh** [comment]
PR is merged. Resolve this issue.
