### ISSUE TITLE
[Data Explorer] Sorting ascend and descend do not work in the discover table

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#4776]
It seems like sorting ascend and descend action do not actually change the order in the discover table.

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/a0f9bfa5-bfc0-4eaa-9e53-ed9121f13485

**Comment by ananzh** [comment]
PR is merged. Resolve this issue.
