### ISSUE TITLE
[Data Explorer] Left side bar can not be expanded and collapsed

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#4780]
Previously, the legacy discover have the left side bar expanded by default, and it also provides option to collapse the side bar.

Discover 2.0 does not have the expanding and collapsing functionalities anymore.

**Comment by joshuarrrr** [comment]
Because there's no PR open, relabeling for 2.12.

**Comment by ashwin-pc** [comment]
As Kevin mentioned in his comment here: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5260#issuecomment-1761428753, lets use the resizeable and collapsible component from OUI to implement this. This should happen in the data explorer plugin's layout between the canvas and the sidebar.

This is similar to the VisBuilder's implementation of the same care has to be taken to memoize the child components since resizing constantly rerenders the children unless memoized.

**Comment by LHozzan** [comment]
This function is missing for me too or anybody with small screen.
Have you please some estimation to provide fix?

**Comment by joshuarrrr** [comment]
@wbeckler This is labeled for 2.12, but do we need to actually get an assignee?

**Comment by Ganesh0107** [comment]
@joshuarrrr @ashwin-pc I have a solution ready for this problem and would be happy to contribute. Could someone guide me on the next steps or whether you would like me to submit a pull request?

**Comment by ashwin-pc** [comment]
@Ganesh0107 Thanks! yes any contributions here would be appreciated. The goal was to use OUI's resizeable containers to do this https://oui.opensearch.org/1.3/#/layout/resizable-container%23collapsible-resizable-panels. The change is needed in the Data Explorer component. You can raise a PR for the change and I can help you with any issues that you might face while implementing it :) Thanks for volunteering to help with this

**Comment by CMDWillYang** [comment]
thanks @ananzh and @ashwin-pc for suggesting this project for me, I would love to work on it! 

@Ganesh0107 if you are still interested in tackling this lmk. would love to collaborate :)

**Comment by ananzh** [comment]
@CMDWillYang I have assigned this to you.
@Ganesh0107, would like to hear your solution and have ur contribution. We have tag it to 2.13. Feel free to contact me or @CMDWillYang to cooperate.

**Comment by Ganesh0107** [comment]
@CMDWillYang @ananzh I am about to raise PR in Couple of hours

**Comment by Ganesh0107** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5635

**Comment by ananzh** [comment]
@Ganesh0107 thanks for opening the PR. I will remove @CMDWillYang and will start reviewing the PR.

**Comment by ananzh** [comment]
Close it as resolved
