### ISSUE TITLE
[BUG] Dashboard URLs from Markdown visualizations are not loaded correctly

### ISSUE THREAD

**Issue by thmsbp** [opensearch-project/OpenSearch-Dashboards#4819]
**Describe the bug**

Dashboard URLs defined in Markdown Visualizations are not loaded correctly.
Note: URL to external websites work.

**To Reproduce**
1. From Opensearch Dashboard 2.9
2. Edit a dashboard
3. Create a Markdown visualization with links to dashboards (relative URL, absolute, with params... issue happens with all formats)
4. Save everything
5. On Chrome or Firefox, click on a link from the markdown visualization
6. The current page is reloaded with blank content. User must refresh the webpage to get the dashboard from the link (ex: F5)

Example of markdown:
\[Test1](#/view/dashboardA?_g=())
\[Test2](#/view/dashboardB?_g=())

**Expected behavior**
As with OpenSearch 2.8 (and before), a link should load the dashboard directly (without F5)

**OpenSearch Version**
Opensearch 2.9

**Dashboards Version**
OpenSearch Dashboards 2.9

**Plugins**

From app/status:

core:opensearch@2.9.0
core:savedObjects@2.9.0
plugin:notificationsDashboards@2.9.0
plugin:enhancedTable@2.9.0
plugin:bfetch@2.9.0
plugin:charts@2.9.0
plugin:advancedSettings@2.9.0
plugin:devTools@2.9.0
plugin:embeddable@2.9.0
plugin:discover@2.9.0
plugin:expressions@2.9.0
plugin:indexPatternManagement@2.9.0
plugin:inspector@2.9.0
plugin:legacyExport@2.9.0
plugin:management@2.9.0
plugin:navigation@2.9.0
plugin:managementOverview@2.9.0
plugin:opensearchDashboardsReact@2.9.0
plugin:opensearchDashboardsOverview@2.9.0
plugin:opensearchDashboardsUsageCollection@2.9.0
plugin:opensearchUiShared@2.9.0
plugin:opensearchDashboardsUtils@2.9.0
plugin:savedObjectsManagement@2.9.0
plugin:savedObjects@2.9.0
plugin:share@2.9.0
plugin:uiActions@2.9.0
plugin:visDefaultEditor@2.9.0
plugin:visualize@2.9.0
plugin:visualizations@2.9.0
plugin:urlForwarding@2.9.0
plugin:customImportMapDashboards@2.9.0
plugin:alertingDashboards@2.9.0
plugin:indexManagementDashboards@2.9.0
plugin:mlCommonsDashboards@2.9.0
plugin:securityDashboards@2.9.0
plugin:dashboard@2.9.0
plugin:data@2.9.0
plugin:apmOss@2.9.0
plugin:console@2.9.0
plugin:home@2.9.0
plugin:inputControlVis@2.9.0
plugin:mapsLegacy@2.9.0
plugin:opensearchDashboardsLegacy@2.9.0
plugin:regionMap@2.9.0
plugin:visAugmenter@2.9.0
plugin:visBuilder@2.9.0
plugin:usageCollection@2.9.0
plugin:visTypeMarkdown@2.9.0
plugin:visTypeMetric@2.9.0
plugin:visTypeTable@2.9.0
plugin:visTypeTagcloud@2.9.0
plugin:visTypeTimeline@2.9.0
plugin:visTypeTimeseries@2.9.0
plugin:tileMap@2.9.0
plugin:visTypeVislib@2.9.0
plugin:visTypeVega@2.9.0

**Screenshots**

**Host/Environment (please complete the following information):**
 - Windows 10 Pro
 - Firefox 116.0.3
 - Chrome 115.0.5790.170
Opensearch + OpensearchDashboard in Docker on Redhat 8.6

**Additional context**

none

**Comment by ashwin-pc** [comment]
@thmsbp can you provide a sample URL that does not work? I have a strong suspicion that you are using the URL from the browser directly which does not work well with markdown formatting since the URL is also used to store the state of the application. Can you also try using the URL from the share menu in the application and see if you face the issue?

**Comment by thmsbp** [comment]
@ashwin-pc 
This is the exact link we use and was working before OpenSearch 2.9:
\[Home](#/view/v202-bk-system-overview?_g=())

When I click on the link from another dashboard (other than "v202-bk-system-overview"
I get this URL in the address bar:

https://ip:port/app/dashboards#/view/v202-bk-system-overview?_g=()&_a=(description:'Overview%20of%20system%20metrics',filters:!(),fullScreenMode:!f,options:(darkTheme:!t,hidePanelTitles:!f,useMargins:!t),query:(language:lucene,query:''),timeRestore:!f,title:'%5Bv2.0.2%5D%5Bsystem%5D%20Overview',viewMode:view)

It doesn't load the "v202-bk-system-overview" dashboard, the current dashboard remains but views are empty.
I press F5 and get the Opensearch loading page, and then "v202-bk-system-overview" is correctly displayed.
Just in case, the URL in the address bar remains the same as in previous step:

https://ip:port/app/dashboards#/view/v202-bk-system-overview?_g=()&_a=(description:'Overview%20of%20system%20metrics',filters:!(),fullScreenMode:!f,options:(darkTheme:!t,hidePanelTitles:!f,useMargins:!t),query:(language:lucene,query:''),timeRestore:!f,title:'%5Bv2.0.2%5D%5Bsystem%5D%20Overview',viewMode:view)

I'm going to test the URL from the "share menu" (next message)

**Comment by thmsbp** [comment]
@ashwin-pc 
We have the same issue using the URL from the "Share" menu.
I made a test with this markdown:

\[Test](https://ip:port/app/dashboards?security_tenant=company_tenant#/view/v202-bk-system-overview?_g=()&_a=(description:'Overview%20of%20system%20metrics',filters:!(),fullScreenMode:!f,options:(darkTheme:!t,hidePanelTitles:!f,useMargins:!t),query:(language:lucene,query:''),timeRestore:!f,title:'%5Bv2.0.2%5D%5Bsystem%5D%20Overview',viewMode:view))

**Comment by kavilla** [comment]
Thanks @thmsbp.

I believe this is related to this: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4694#issuecomment-1702271190.

Still looking into fix.
