### ISSUE TITLE
[BUG] Broken link

### ISSUE THREAD

**Issue by taf2** [opensearch-project/OpenSearch-Dashboards#482]
Just installed opensearch dashboard and started testing found the following broken link while adding an index as a source.

<img width="1305" alt="Screen Shot 2021-06-14 at 9 35 40 AM" src="https://user-images.githubusercontent.com/1568/121900912-f2f20a80-ccf3-11eb-8a2c-5f03afbc4d24.png">

broken link is http://www.opensearch.org/guide/en/elasticsearch/reference/current/mapping.html

my current local revision is 6e34d855ef09964ac718b62a6066897fddcbee9e

**Comment by tmarkley** [comment]
For tracking purposes: sub-issue of #335
