### ISSUE TITLE
[BUG] buildPointSeriesData unit test fails due to hard-coded expected value that is not timezone friendly

### ISSUE THREAD

**Issue by evankielley** [opensearch-project/OpenSearch-Dashboards#4865]
**Describe the bug**
The unit test buildPointSeriesData fails due to trying to match a hard-coded UTC datetime with a datetime generated in accordance with my machine's timezone. A simple fix would be to change the expected values to be `moment('2023-01-01')` and `moment('2023-01-01')` instead of `'2023-01-01T00:00:00+00:00'` and `'2023-01-02T00:00:00+00:00'`.

**To Reproduce**
1. Run `yarn test:jest src/plugins/discover/public/application/components/chart/utils/point_series.test.ts`

**Expected behavior**
The unit test should pass.

**OpenSearch Version**
N/A

**Dashboards Version**
N/A

**Plugins**
N/A

**Screenshots**
<img width="924" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/19230025/1c748cf0-cb18-4f09-abaf-d57a62574ed7">

**Host/Environment (please complete the following information):**
 - OS: macOS 13.5.1
 - Browser and version: N/A

**Additional context**
yarn version: 1.22.19
node version: v18.16.0

**Comment by ananzh** [comment]
@evankielley Thank you for catching this test bug for us and you are absolutely right. I also reproduced and saw the unit test for `buildPointSeriesData` fails when comparing expected datetime strings. The discrepancy arises from the behavior of the moment library regarding time zones. Specifically, when creating a moment object like moment('2023-01-01'), it uses the local timezone of the machine executing the code. As a result, on a machine set to the -08:00 timezone, the formatted string from the moment object will also carry that -08:00 offset, causing a mismatch with the hard-coded UTC string '2023-01-01T00:00:00+00:00'.

As @evankielley suggested, to ensure consistency across different environments, the date-time strings used within the test should be explicitly defined in UTC. By using a format like `moment('2023-01-01T00:00:00Z')`, the moment object is set in UTC regardless of the system's local timezone. Thus, when this moment object is formatted, it should consistently produce a UTC timestamp, avoiding discrepancies in different environments.

I will raise a PR to fix it.
