### ISSUE TITLE
[Theme: Next] Left menu background doesn't stretch all the way to the bottom

### ISSUE THREAD

**Issue by AMoo-Miki** [opensearch-project/OpenSearch-Dashboards#4878]
The bottom part of the left menu uses a different color; it is white.
<img width="388" alt="Screenshot 2023-08-31 at 10 35 25 AM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/3527403/ee07a616-3e8b-4452-8a31-4d58084fa963">

**Comment by joshuarrrr** [comment]
I believe the incorrect background color is the correct background for `OuiFlyout` in other contexts. So it's probably best to fix this on the OSD side.

**Comment by kavilla** [comment]
@AMoo-Miki to hand off here
