### ISSUE TITLE
[Workspace][Feature] Setup workspace skeleton and implement basic CRUD API

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/OpenSearch-Dashboards#4945]
**Feature includes**
- [x] Add feature flag on workspace plugin.
- [x] Setup workspace plugin skeleton.
- [x] Define data structure on `workspace`.
- [x] Implementation on CRUD operations on `workspace`.

**Additional context**

#4615

**Comment by SuZhou-Joe** [comment]
#4944

**Comment by ananzh** [comment]
@SuZhou-Joe I think this issue is well triaged. I will remove the `untriage` tag for now. If not, feel free to ping me.

**Comment by SuZhou-Joe** [comment]
Thanks @ananzh .
