### ISSUE TITLE
[Look and Feel] New Home Page Experience

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#4966]
The homepage needs to be redesigned to provide useful links, including favorites, recents, and AI-based smart suggestions for visualizations wrapped up with a modernized visual aesthetic that includes an attractive dark mode that users now prefer.

## High-level requirements

- “Home” workspace will be a public (everyone can write/edit) workspace.
  - By default, all users can read/write to the workspace,
  - Only Admins should be able to edit the workspace settings/configure the homepage.
  - Admins can also configure feature visibility in the Home workspace.
- Every user will have a “Personal” workspace.
  - This workspace will be fully customizable.
  - Users can pick whether they land on “home”, their personal workspace, or some other workspace.
  - Users will have the option of importing their private tenant objects to their personal workspace.
- For adding sample data, post P0 we would like to add sample workspaces, instead of adding sample data to the current workspace. This will allow those sample workspaces to customize their “overview” pages.
- “Home workspace” will have a page called “Home”; Personal and Custom workspaces will have “Overview” pages. Both of these pages will be the same type of page, and all the content embeddables we create for Home will be available as content that can be added to “Overview”, as well as any dashboards.

## UX vision

<img width="1103" alt="Screen Shot 2023-09-07 at 9 54 14 AM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/1679762/ef74d279-81c5-40c2-9cd9-41d527228c0f">

Proposal created on behalf of @mnkugler and @wbeckler

**Comment by BSFishy** [comment]
Some questions/observations I have:
 - For section component
    - Do we have the requirements for that?
    - How are props specified?
       - I see the categories within the section are similar to card props. Are those cards? Should a list of card props be provided?
    - The last section is one unified category instead of 3 distinct one, is there some sort of differentiation there?
    - The top section is clearly a different type of section than the rest. Should sections have a "type" or should that be a separate component?
 - I can see the mock uses a Trinity style UI, where there isn't a top bar. That's usually where the breadcrumbs are, so how does that work with the current style?
 - What does `Customize homepage` do?
 - I understand embeddables are meant to be utilized somehow
    - Are sections themselves embeddables, so eg. Observability could register its own homepage section?
       - Is this a requirement for the initial new homepage release?
       - Are individual categories embeddables too?
          - For example, could we have a "What's new" section, where different plugins could register what they added in the most recent release?
    - I believe visualizations are meant to be embeddable on the homepage through a recent visualizations section or something of the sort?
 - How are links handled?
    - For example, for the "Learning more about workspaces" category, I presume those links are to documentation. Are those links customizable somehow? If so, how?
 - How is section layout stored?
    - Is it in a saved object? Does it require the concept of a user in Dashboards to build off of? Could it be stored in local storage?
    - What is stored? Is it only the order of sections?
 - Are there admin-configurable sections?
    - For example, I could see an admin wanting a section with categories similar to the "Learning more about workspaces" category with links to documentation or maybe even other plugins
 - How is the video handled?
    - Is it hosted on YouTube or Vimeo? We don't want to ship a video binary with Dashboards
    - Could admins configure it to show something else?
