### ISSUE TITLE
[De-Anagular] Clean/Modify documents

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#5017]
Some docs still have angular context. This is an overall tracking issue for cleaning up documents & comments. Some important ones are:

- [ ] packages/osd-i18n/GUIDELINE.md
- [ ] packages/osd-i18n/README.md
- [ ] src/dev/i18n/README.md
- [ ] DEVELOPER_GUIDE.md

Could create sub-issues if anyone picks up. Feel free to link other missing document related cleaning to this meta issue.

**Comment by ShatilKhan** [comment]
Hey @ananzh , I have been assigned this repo to work on as part of OSCI. Just wanted to hop in & try out fixing something to understand the project better. 
Would you mind if I take a look at this issue?
Also would be great to get some more context/info on what needs to be done exactly.
Hopefully I'll learn more on tomorrow's Weekly call!

**Comment by ashwin-pc** [comment]
Fixed in #5080
