### ISSUE TITLE
[De-Angular] More angular test cleaning

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#5020]
- [ ] Remove/Replace `test/plugin_functional/plugins/doc_views_plugin/public/plugin.tsx` 
- [ ] Remove/Replace `test/plugin_functional/test_suites/doc_views/doc_views.ts`.

**Comment by joshuarrrr** [comment]
@ananzh Should this be relabeled for 2.12?

**Comment by ananzh** [comment]
I will see if I have time to work on it tmrw. Otherwise, I will re-label it.
