### ISSUE TITLE
[BUG] Dashboards RC 2.10.0.6565 filter button in discover app doesn't work

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/OpenSearch-Dashboards#5027]
**Describe the bug**

Filter button in facetted search doesn't work. Confirmed on the latest releases of Brave and Firefox, see video. 

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/2643715/906cdba6-93a0-435b-ab2b-be7a1da578cf

**Expected behavior**
when clicking the + icon the filter is applied

**OpenSearch Version**
2.10.0.8459 Docker container

**Dashboards Version**
Dashboards RC 2.10.0.6565 Docker container

**Plugins**

Defaults + S3 repository plugin

**Screenshots**

**Host/Environment (please complete the following information):**
Macos Ventura

**Additional context**
N/A

**Comment by ict-one-nl** [comment]
Found something related. When opening a previously saved search, in the old version the filters are applied as expected.  In the new version the filter are not applied. See video:

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/2643715/7e584703-5092-404d-bf3b-0880fba7822b

This is recorded in Brave v1.58.124

If you want to close the add filter window, you need to click cancel. Clicking in another part of the window doesn't close the filter window. This somewhat confused me as you can see in the video.

**Comment by ict-one-nl** [comment]
As discussed on Slack:

Another small UI thing: clicking the close button closes the notice as expected, but if you refresh the screen it’s there again. Would have expected that it stayed away after closing it the first time.

<img width="1357" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/2643715/88b262c0-9925-4b12-a198-8d187390cd8b">

**Comment by ict-one-nl** [comment]
Another small thing:

<img width="398" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/2643715/ab1fb32c-ded1-417c-8ecf-7fa327dd3e19">

In the selected fields part, fields can be ordered. The hand cursor is intuitive there. In the available fields part fields can't be reordered, but the cursor suggests it could be. Maybe a good compromise would be that a single click opens the pane (like the 
<img width="28" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/2643715/6276c14c-3421-4210-aee5-7f0c3d96d18d"> button) and holding/dragging it reorders where it can be done.

**Comment by ict-one-nl** [comment]
Sorry, another one, this is a bug: opening a saved filter reloads the dashboards app


https://github.com/opensearch-project/OpenSearch-Dashboards/assets/2643715/7a0107ad-34ed-4191-aa22-4b6748dd45d3

**Comment by ashwin-pc** [comment]
@ict-one-nl thanks for catching these issues. Given that we still have the legacy app available and that the 2.10 release is today, I will fix as many of these as possible before the release, but the rest may only be fixed in the next release. For the ones that arent addressed rigth away, I will move them into a separate issue for 2.11 :)

**Comment by ict-one-nl** [comment]
Great thanks. Let me emphasize I appreciate the new look and all the work that has gone in it. Seems more responsive.

If I can help test some more let me know.

**Comment by ashwin-pc** [comment]
@ict-one-nl much appreciated :) Please feel free to open any other issue you see in the new Discover app. 

Also 

> Another small thing, more of a inconsistency:
> 
> <img alt="image" width="398" src="https://user-images.githubusercontent.com/2643715/268118849-ab1fb32c-ded1-417c-8ecf-7fa327dd3e19.png">
> In the selected fields part, fields can be ordered. The hand cursor is intuitive there. In the available fields part fields can't be reordered, but the cursor suggests it could be. Maybe a good compromise would be that a single click opens the pane (like the <img alt="image" width="28" src="https://user-images.githubusercontent.com/2643715/268121583-6276c14c-3421-4210-aee5-7f0c3d96d18d.png"> button) and holding/dragging it reorders where it can be done.

The reason for the hand icon in the available fields is because those fields can be dragged from the list onto the selected fields in addition to the + icon. See the attached video:

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/20453492/0fc5bdd6-a6f1-4a36-af69-dcf20102dad5

**Comment by ashwin-pc** [comment]
> Sorry, another one, this is a bug: opening a saved filter reloads the dashboards app
> 
>  Screen.Recording.2023-09-15.at.00.05.48.mov

Are you sure you consider this a bug? I intentionally implemented it this way to ensure that there is only one way to open saved searches. To do so without reloading the page would mean that i'd have two similar code paths to load a saved search, which if not careful can result in a drift between experiences as more changes are introduced. There are more updates that are coming to Discover soon so I wanted to make sure that we have less code paths to worry about.

**Comment by ict-one-nl** [comment]
Hm I think I understand your implementation. From a users perspective: this screen normally only shows when first using Dashboards. So when this pops up it gave me pause: is everything okay? I understand the ultimate solution is ditching the old code path, maybe in the mean time make more explicit why this loading screen is served at the loading screen itself.

**Comment by ict-one-nl** [comment]
Fixes for the filtering and notice not disappearing permanently: confirmed! :)

**Comment by ict-one-nl** [comment]
@ashwin-pc Got another one on Brave:

<img width="213" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/2643715/bcfedb1e-1c48-4c31-96b2-a5d044c5165d">

Sorting doesn't do anything it seems. This is a saved filter that I just opened
