### ISSUE TITLE
[BUG] [Data Explorer] Data Explorer does not respect global time filter anymore

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#5056]
**Describe the bug**
When we save a new saved search and reload that saved search, the global time filter is lost and always reset back to default. 

When we click `reset` button on a loaded saved search, the time filter does not persist and always goes back to the default as well.

**Expected behavior**
Time filter should be persisted globally.

Current behavior:

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/43672d2d-742a-45ab-899e-635434fda611

Expected behavior: 

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/3e2cb7ed-39a6-4a60-94ea-0cd20c251f73

**Comment by joshuali925** [comment]
this also affects reporting since it assumes that the time filter value is in the URL https://github.com/opensearch-project/dashboards-reporting/pull/190

**Comment by abbyhu2000** [comment]
@ashwin-pc I don't think this is resolved. The bug still persists: when i load the saved search, time filter still resets back to the default.

**Comment by abbyhu2000** [comment]
Verified it is working, close the issue.
