### ISSUE TITLE
[BUG][Data Explorer] `SearchOnPageLoad` does not work

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#5057]
**Describe the bug**
If `SearchOnPageLoad` is turned on, the discover page should not show search result immediately, but show a page saying `Start searching`. 
<img width="1726" alt="Screenshot 2023-09-18 at 2 56 39 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/a1cd5675-a2a7-47ed-bcc4-174674f5676a">

Currently, the behavior is the same whether `SearchOnPageLoad` is turned on or off, it always loads the result immediately on page load: 

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/d93ec2d5-8f33-4663-a5f4-7283a474b45e

Expected:

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/535e50e9-4ed5-49d9-a509-94d6c5513bd8

**Comment by ananzh** [comment]
This is a missing! Great catch!
