### ISSUE TITLE
[BUG] [Data Explorer] `data-shared-item` attribute is missing on the discover table

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#5058]
**Describe the bug**
One of the functional test for legacy discover is testing whether the attribute `data-shared-item` exists on the discover table when we open a saved search.

The test:
```
describe('data-shared-item', function () {
      it('should have correct data-shared-item title and description', async () => {
        const expected = {
          title: 'A Saved Search',
          description: 'A Saved Search Description',
        };

        await retry.try(async () => {
          await PageObjects.discover.loadSavedSearch(expected.title);
          const {
            title,
            description,
          } = await PageObjects.common.getSharedItemTitleAndDescription();
          expect(title).to.eql(expected.title);
          expect(description).to.eql(expected.description);
        });
      });
    });
```

HTML example: 
<img width="578" alt="Screenshot 2023-09-18 at 3 03 35 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/5518bc26-e925-4705-b25c-30785e6d3b87">

This attribute is missing when we load saved search using the data explorer.

**Comment by ananzh** [comment]
I think this is not a bug. We don't have this legacy implementation of a "Discover DocTable" and we shift it to the new implementation using the EuiDataGrid component from the OUI library. 

I think functionality wise, we just need to ensure that the functions this legacy test uses or calls still exist and behave the same way. So something like:

```
describe('data-grid-table', function () {
    it('should have correct data-grid-table title and description', async () => {
        const expected = {
            title: 'A Saved Search',
            description: 'A Saved Search Description',
        };
...
```

If functionality wise changed, we might need to rewrite portions of the test.

**Comment by abbyhu2000** [comment]
I do think it is beneficial to add the `data-shared-item` since it is not just a legacy concept of discover. The concept is also used in visualization and dashboard plugin.

-  For example, the `data-shared-item` tag is added to the visualization embeddable by 
`div.setAttribute('data-shared-item', '')` in src/plugins/visualizations/public/embeddable/visualize_embeddable.ts, 

- Dashboard also has the tag added to the dashboard container.
```
<div
        data-shared-items-count={Object.values(panels).length}
        data-shared-items-container
        data-title={title}
        data-description={description}
        className={useMargins ? 'dshDashboardViewport-withMargins' : 'dshDashboardViewport'}
      >
```

Both visualization plugin and dashboard plugin has dedicated functional tests to test on the `data-shared-items` tag being successfully added too. Thus i think it is good to add the `data-shared-item` with `data-title` and `data-description` tags to the discover table. @ananzh @ashwin-pc

**Comment by ananzh** [comment]
What exactly does this `data-shared-item` tag is used for ? I think `vis_type_table` doesn't have these tags and I don't see any issues. I am just thinking it is not a required tag.

**Comment by abbyhu2000** [comment]
> What exactly does this `data-shared-item` tag is used for ? I think `vis_type_table` doesn't have these tags and I don't see any issues. I am just thinking it is not a required tag.

have not dived into the specific usage in these tags, but i think it is related to embeddables? since they only add these tags on dashboard container embeddable, visualization embeddable, and save search embeddable.

**Comment by ananzh** [comment]
if adding it is easier to fix the tests, then go ahead. we could investigate this later.

**Comment by abbyhu2000** [comment]
The `data-shared-item` tag is used in this functional test `test/functional/apps/dashboard/data_shared_attributes.js` where dashboard uses these tags to see if all the embeddables are loaded and rendered correctly with their title and descriptions.
