### ISSUE TITLE
[BUG] Nothing is loading

### ISSUE THREAD

**Issue by dstoes00** [opensearch-project/OpenSearch-Dashboards#5063]
Hello - when logging into the site, nothing is loading.  Cannot see Dashboards, Visualizations, etc.  Are you able to help?

**Comment by kavilla** [comment]
Hello @dstoes00,

Sorry about that. Would you mind providing more details?

How are you accessing the site? Locally, cloud provider? Which version of the application you are running?

**Comment by dstoes00** [comment]
Hi @kavilla , it seems this is a known issue for CH2 that's been going on for a week.  I'm with Comcast...I believe it's being worked on but the problem hasn't been resolved yet

**Comment by wbeckler** [comment]
Hi @dstoes00 if there's no objection, I'm going to close this issue under the assumption that the details are being discussed elsewhere.

**Comment by dstoes00** [comment]
Hello – that’s fine.  It’s being taken care of.

Thanks,

Dave Stoessel
TPX Connect TES
Downingtown, PA
M: 215-978-7764
***@***.***
