### ISSUE TITLE
[BUG][Data Explorer] Saved queries does not persist after browser refresh

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#5071]
**Describe the bug**
Saved queries does not persist after browser refresh. (The saved queries is no longer being selected as shown in the saved quer ies window)

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/3e9f9ca4-d24d-4e9c-a047-070fd01da099

**Expected behavior**
Saved queries should persist across refresh, and it is still shown as selected in the save queries window.

**Comment by joshuarrrr** [comment]
@abbyhu2000 Is the fix for this expected to be ready for 2.11, or should we relabel?

**Comment by AMoo-Miki** [comment]
This was resolved with #5206.
