### ISSUE TITLE
[BUG][Data Explorer] View single/surrounding document open a new tab

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#5097]
**Describe the bug**
View single/surrounding document open a new tab, which makes the below functional test fail. The functional test is testing backward navigation after clicking surrounding document, so the new tab makes the backward navigation fail.

`test/functional/apps/context/_context_navigation.js`

**To Reproduce**

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/ea96d750-fcaf-495f-ae72-42f444ffb93c

**Expected behavior**

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/f4be0aac-bcab-4750-bfd1-253501964fb5

**Comment by ananzh** [comment]
currently, due to design of data explorer, we decide to make view single and surrounding doc open in a new tab and won't support backward nav.
