### ISSUE TITLE
[BUG][Data Explorer][Discover] When there is only one index pattern, discover is not able to load it

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#5128]
## Reproduce steps
* Don't add/load default sample data, just create one index pattern in OSD, which will be set as default.
<img width="1095" alt="Screenshot 2023-09-29 at 10 48 53" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/600ab1ff-77e3-4de9-b4e6-1f9994ee0f3e">

* Go to discover page. See it is not automatically loading the default index pattern.
<img width="1775" alt="Screenshot 2023-09-29 at 10 48 12" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/460cad1a-61c5-4d16-b979-2c0d32fba365">

* You will need to upload the index pattern manually.
<img width="1772" alt="Screenshot 2023-09-29 at 10 48 24" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/487f5173-7658-4f7d-a63c-224a4ea4433d">

**Comment by ashwin-pc** [comment]
@ananzh can you add some more context here. This should work, so I'm assuming you have a more specific use case that does not work. Can you add a screenshot and repro steps to the issue?
