### ISSUE TITLE
I am not able to see dashboards or any content on any page

### ISSUE THREAD

**Issue by ranu-toshniwal-jpmc** [opensearch-project/OpenSearch-Dashboards#5135]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ashwin-pc** [comment]
@ranu-toshniwal-jpmc can you fill out the description of the issue based on the template? Also attach any screenshots or error messages that you see that will help us debug the issue.

**Comment by kavilla** [comment]
Likely related to this? https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4694#issuecomment-1702271190

**Comment by wbeckler** [comment]
Please reopen if you have more info
