### ISSUE TITLE
[Discover] Documents view is too small in Dashboards 2.10

### ISSUE THREAD

**Issue by kaszanka1234** [opensearch-project/OpenSearch-Dashboards#5137]
**Is your feature request related to a problem? Please describe.**

Documents view has smaller effective area in 2.10 compared to previous versions

**Describe the solution you'd like**

Add option to hide the time histogram graph
OR
Make time histogram graph scroll with the documents like it used to

**Describe alternatives you've considered**

none

**Additional context**

In dashboards 2.10 time histogram graph is static on the page meaning the documents view (outlined in green) is effectively smaller than previous versions where the graph scrolled along with document list
![dashboards2 10](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/42652623/31d9e7a2-4b9e-4913-8c4d-3f487a850446)

Hiding the graph with custom css makes the document view (outlined in green) larger, allowing more documents to fit on a screen when the histogram is not relevant
![dashboards2 10a](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/42652623/48328559-75c7-446d-8e26-3634032028cf)

**Comment by seanneumann** [comment]
Thanks @ kaszanka1234! We'll take a look. Please report any other issues you are seeing with the new Discover. We really appreciate it!

Sean.

**Comment by ashwin-pc** [comment]
Thanks for pointing out the issue @kaszanka1234. We've changed the layout for discover in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5114 to be similar to the old one so that the page scrolls. This should resolve your issue.

**Comment by kaszanka1234** [comment]
Thank you for the reply, I believe these changes will ship in 2.11? If so i'm waiting for the update to retest :)

**Comment by rlevytskyi** [comment]
Upvote the issue.
It doesn't seems like "5114" resolves the issue.

**Comment by AMoo-Miki** [comment]
@rlevytskyi haven't hear back from you; please feel free to reopen if you have more data to provide.
