### ISSUE TITLE
[Workspace]Add a configuration to disable ACL(access control) on saved object

### ISSUE THREAD

**Issue by xluo-aws** [opensearch-project/OpenSearch-Dashboards#5144]
**Is your feature request related to a problem? Please describe.**

Workspace feature https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4944 introduce a new access control service on saved objects. We want to provide an option for admin to disable it in case it causes some unexpected problems or user don't want to apply access control for saved object.

**Describe the solution you'd like**

It can be configured in opensearch_dashboard.yml or a UI configuration that can be turned on or off dynamically.

**Describe alternatives you've considered**

Don't support disable ACL, there is security concern on whether we should allow user to disable ACL because it means every user has full access to all saved object.

**Additional context**

**Comment by xluo-aws** [comment]
Please assign this ticket to me.

**Comment by ruanyl** [comment]
This is implemented in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5084
