### ISSUE TITLE
[BUG][Discover] Panel header says `Open search`

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#5145]
**Describe the bug**
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/discover/public/application/components/top_nav/open_search_panel.tsx#L70

**To Reproduce**
Navigate to Discover page, click on `Open`. Notice the header says `Open search`

**Expected behavior**
I believe it should say `OpenSearch` but even still I'm not quite that makes sense.

**Dashboards Version**
All

**Comment by bibaswan7** [comment]
Please assign it to me

**Comment by bibaswan7** [comment]
@kavilla sorry for the mess. #5152 is the final PR where the issue has been fixed and also the snapshots are updated

**Comment by ss-vijayvavdiya** [comment]
If this issue still open, I'd like to take a look at this

**Comment by bibaswan7** [comment]
I have already been assigned
