### ISSUE TITLE
[BUG] Use different currency symbol than $

### ISSUE THREAD

**Issue by dgrigorov** [opensearch-project/OpenSearch-Dashboards#5153]
**Describe the bug**
I’m working on a metric visualization where I have to display the total revenue for a specified month with a currency symbol in front of the total amount but I got stuck. I’ve imported the sample e-commerce data and was able to see how was done there so I’ve managed to create a sum of the order_total field in my case but I got stuck with the currency symbol. It seems like OpenSearch allows to display of only the $ symbol and not any others. Is that true? There could be 5 different websites for which I have to show the total revenue in the respective site's currency.

Here are the settings of the scripted field I've made: https://i.imgur.com/HwPeceH.png

Even if I change the dollar sign to a euro sign for example it shows no currency symbol in the visualization.

**OpenSearch Version**
2.9.0

**Dashboards Version**
2.9.0

**Screenshots**
https://global.discourse-cdn.com/business5/uploads/mauve_hedgehog/original/2X/f/f5ad57f6b28c7b3f64593add533775431165d7c0.png

https://global.discourse-cdn.com/business5/uploads/mauve_hedgehog/original/2X/7/702b86872dd2888d69feb96b49c8cb8d0d1ff2ea.png

**Comment by joshuarrrr** [comment]
@dgrigorov OpenSearch Dashboards field formats are a way to specify how numerical fields are converted to strings for the the purpose of displaying in visualizations, discover, or other apps. The field format pattern you see in the first screenshot is implemented by the Numeral.js library (http://numeraljs.com/#format), and the `$` is just a placeholder for the currency symbol. The default format pattern can be adjusted via the `format:currency:defaultPattern` advanced setting.

But the actual currency symbol displayed is determined by the `locale`, set via the `format:number:defaultLocale` advanced setting. By changing this from "English" to "French", you should see the currency symbol update on your visualization from a dollar sign to a Euro symbol. These settings affect your entire OpenSearch Dashboard cluster (or tenant if using multitenancy).

This also assumes that fields have already been normalized during ingestion (whether via DataPrepper or some other tool). This limitation actually makes sense once you start doing aggregations - there's no universal way to sum a field with varying units.

**Comment by wbeckler** [comment]
@dgrigorov if there is something you might need to move forward please reopen the issue.
