### ISSUE TITLE
[BUG] Point series unit test failure

### ISSUE THREAD

**Issue by thanhinhchtom** [opensearch-project/OpenSearch-Dashboards#5165]
**Describe the bug**

There is a wrong test case happening with time conversion.

**To Reproduce**
1. Run the command `yarn test:jest src/plugins/discover/public/application/components/chart/utils/point_series.test.ts`

**Expected behavior**
It should run through this test

**OpenSearch Version**
Snapshot 3.0.0

**Dashboards Version**
3.0.0

**Plugins**

Please list all plugins currently enabled.

**Screenshots**
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/88635563/5501cc17-a55d-4400-83a8-7c9b73113b9a)

**Host/Environment (please complete the following information):**
 - OS: macOS Ventura 13.4.1 arm64
 - Browser and version: Google Chrome version 117.0.5938.92

**Additional context**

**Comment by joshuarrrr** [comment]
It appears that the unit test output may be sensitive to system timezone - the fix would be to make sure the test is consistent regardless of any local timezone settings.

**Comment by thanhinhchtom** [comment]
[OSCI] Can I do this? @joshuarrrr

**Comment by joshuarrrr** [comment]
Sure! Assigned to @thanhinhchtom

**Comment by thanhinhchtom** [comment]
@joshuarrrr I already create a pull request to fix this problem [#5174 ](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5174). Can you review it for me?
