### ISSUE TITLE
[BUG] Refresh button in Discover not working in new 2.10 version

### ISSUE THREAD

**Issue by tallyoh** [opensearch-project/OpenSearch-Dashboards#5186]
While in a discover screen with data displayed - I click the refresh button and nothing changes on the screen. But If I click the browser refresh button, I can see new data in the top graph. 

It seems like the time period is not updated. For example with "last 15 min" selected, clicking the refresh button does not update the search results. But if I manually change the time to last 30 min, 24 hrs, etc - then the display does update. Clicking a full browser refresh also updates the display.

I should note that by reverting to the older discover page  the refresh button seems to work fine.

1. Go to Discover
2. Click on an available index pattern
3. Wait a minute for more data to be indexed- then click the refresh button
4. The page doesn't update.

I would expect that with a range of say "last 15 min" chosen, then clicking refresh would re-calculate what the last 15 min are, and update the top graph and search results below accordingly. 

OpenSearch and Dashboards 2.10 is currently installed

Only default install plugins are installed and enabled

 - OS: Oracle Linux 8.8, 7 node cluster - all fresh install with 2.10
 - Browser:  Edge and Chrome browsers both exhibit behavior on Windows 10/11

**Additional context**

It seems like refresh is just not re-calculating relative times and triggering the actual refresh. i.e. what is the last 15 minutes? But If I manually change the relative interval, then the screen does refresh.

**Comment by ashwin-pc** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5160 fixes this issue. @tallyoh if you still see any issues with this, feel free to reopen the issue.
