### ISSUE TITLE
[BUG] Dashboards 2.9 is sending request with extra & for request

### ISSUE THREAD

**Issue by seraphjiang** [opensearch-project/OpenSearch-Dashboards#5187]
Dashboards 2.9 is sending request with extra & for this request, e.g.  

GET /_dashboards/api/saved_objects/_find?default_search_operator=AND&&has_reference=%7B%22type%22%3A%22visualization%22%2C%22id%22%3A%22334084f0-52fd-11e8-a160-89cc2ad9e8e2%22%7D&page=1&per_page=100```&&t```ype=augment-vis

this will break functionality of downstream service rely on standard query string pattern, which single question mark is used as a separator

https://en.wikipedia.org/wiki/Query_string

**Comment by seanneumann** [comment]
Assigning to @ashwin-pc as he has some context.
