### ISSUE TITLE
[Datasources] Address Remaining Items in Datasource Selector

### ISSUE THREAD

**Issue by mengweieric** [opensearch-project/OpenSearch-Dashboards#5211]
**Is your feature request related to a problem? Please describe.**

Due to time constraints, some review comments have not been addressed. This issue is for tracking those remaining tasks need to be addressed in the PR #5167 .

**Describe the solution you'd like**

Addressing all reviews after the merge, including: 
<s> - add / improve interfaces and types </s>
<s>- code movement of datasource registration from discover to data plugin </s>
- Adjustments for datasource API definitions
  - removing multiple selectable API
  - add type to datasource and remove hardcoding type name mapping
<s>  - using i18n for user facing text </s>
- Unit / E2E test coverage

**Comment by anirudha** [comment]
lets target this at 2.12 or sooner

**Comment by anirudha** [comment]
In the next release we should move this to the view-switcher asap

**Comment by mengweieric** [comment]
Spoke with @ashwin-pc on this issue that we will:

- Remove this issue from 2.12 release
- Add tests to datasource code lines that still need coverages
- Make change to datasource interface addressing item 'Adjustments for datasource API definitions' after 2.12 when we'd settled new datasource interface designs
