### ISSUE TITLE
[BUG] slide drawer navigation item 'Discover' doesn't have active background when selected

### ISSUE THREAD

**Issue by Abilashinamdar** [opensearch-project/OpenSearch-Dashboards#5226]
**Describe the bug**

When we open the drawer and select Discover it is not highlighted with an active background color like other items.

**To Reproduce**
1. Click the hamburger icon at the top left.
2. Click on the Discover item in the OpenSearch Dashboards collapsible section.
3. The Discover page will be rendered now.
4. Again repeat step 1.
5. See the Discover item doesn't have an active background color.
6. Other items will have active color if we click and go. 

**Expected behavior**
It should be highlighted with an active background color like other items. 

**Dashboards Version**
v 2.10.0

**Screenshots**
![Screenshot from 2023-10-05 17-22-54](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/7028723/9327ef47-92e2-4db4-aaa9-2d7392fb3e48)

![Screenshot from 2023-10-05 17-22-37](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/7028723/263b54f8-b4f0-4b5b-8e3c-c29c26151856)

![Screenshot from 2023-10-05 17-22-02](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/7028723/39e881de-bc31-41df-91cd-702c93df89c9)

**Comment by Willie-The-Lord** [comment]
Hi @ananzh, I would like to work on this issue. Thanks!

**Comment by Willie-The-Lord** [comment]
## Overview
While investigating this problem, I discovered that two distinct plugins, `discover` and `data-explorer`, are triggered when tapping on the `discover` tab, leading to the `isActive` render issue.

## Problem
- In the code, it appears that these are two different instances of `core.application` (`discover` and `data-explorer`). What is the correlation between them?
- Why are they both triggered multiple times in a single tap on the Discover side bar button?

## Screenshot
 ![Screenshot 2023-10-18 at 11 16 29 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/65143821/7ae3f893-8e60-44c1-bf8e-29a840832956)

## Reference
### The code that leads to two AppId
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/336dce65664cd1f541db33325e5787722443d9c6/src/plugins/discover/public/plugin.ts#L276C1-L281C10

### The logic that check whether it is active or not
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/336dce65664cd1f541db33325e5787722443d9c6/src/core/public/chrome/ui/header/nav_link.tsx#L85C1-L85C28

@joshuarrrr @ashwin-pc @ananzh @mattsb42-aws any guidance would be really appreciate!

**Comment by wbeckler** [comment]
Can you change the logic so it is more resilient and works for either app id?

**Comment by Willie-The-Lord** [comment]
Hi @wbeckler no problem! I am preparing my midterm exam at the moment, but I plan to submit a pull request within the next week or two.
