### ISSUE TITLE
[BUG] Discover - 'truncate:maxHeight' no longer working 2.10.0

### ISSUE THREAD

**Issue by stevesimpson418** [opensearch-project/OpenSearch-Dashboards#5227]
**Discover - Maximum table cell height setting no longer working**

In OpenSearch Dashboards 2.10.0 the new UI is no longer respecting the `truncate:maxHeight` Advanced Setting.

**To Reproduce**
1. Index a document with a long string / or long log line. EG
```
PUT my-test-index/_doc/1
{
  "long_field": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mattis, nisl vitae blandit congue, nisl est aliquet sem, vel porttitor libero purus eu lectus. Morbi consequat euismod tortor vel eleifend. Phasellus sit amet vehicula metus. Vestibulum blandit velit euismod, cursus elit nec, cursus nisl. Etiam vitae est orci. Morbi tincidunt vitae nunc sed cursus. Donec scelerisque risus lorem, placerat maximus purus eleifend in. Cras porta quam libero, quis tincidunt neque venenatis ut. Nam in augue urna. Aenean ornare condimentum leo, et bibendum leo bibendum eget. Nulla faucibus diam ut sem posuere, id fringilla erat pulvinar. Fusce a enim quis augue bibendum molestie. Ut vitae auctor purus. Suspendisse et euismod enim. Nullam at ultricies risus, sed dignissim leo. In sollicitudin, tellus tincidunt rhoncus sollicitudin, metus ligula condimentum lacus, id aliquam arcu urna eu nisl. Vestibulum id nulla id sem ultrices gravida. In id mauris ultrices, sollicitudin ex luctus, congue magna. Nullam nec mauris est leo."
}
```
2. Create the Index Pattern, `my-test-index`
3. Set `truncate:maxHeight: 0` in `Dashboards Management>Advanced Settings`.
4. Attempt to visualise the data in the Discover app, you will see that the cells are truncated, ignoring the `truncate:maxHeight` setting.

**Expected behavior**
As with previous versions I would expect the cells to be truncated to the correct height as specified in the `truncate:maxHeight` setting, particularly if truncation is set to 0 and turned off. This is essential when debugging longer log lines.

**OpenSearch Version**
2.10.0
Docker image: opensearchproject/opensearch:2.10.0
**Dashboards Version**
2.10.0
Docker image: opensearchproject/opensearch-dashboards:2.10.0

**Plugins**

Only plugins loaded when running the official docker images, nothing extra

**Screenshots**
<img width="1714" alt="Screenshot 2023-10-05 at 14 02 11" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/15142417/c12e73b8-947b-4895-a78a-87f5b1c70cf5">
<img width="1201" alt="Screenshot 2023-10-05 at 14 02 30" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/15142417/834fa535-c50b-4acd-86a5-d90891dd6041">

**Host/Environment (please complete the following information):**
 - OS: MacOS Ventura 13.6 | Official Docker OpenSearch Images from Docker Hub
 - Browser and version: Google Chrome 117

**Additional context**

This would work with previous versions of OpenSearch Discover and is vital when needing to debug several loglines at once that may stretch beyond the default truncation

**Comment by m-kratochvil** [comment]
I see exactly the same issue in 2.11.0. This is unfortunate, and a fix would be much appreciated, I depend on the full log message during troubleshooting issues..

**Comment by ashwin-pc** [comment]
Given how Data Tables work i dont think this should work the same way in future. That being said, since the requirement here is to prevent the automatic truncation of the cell data, something like that can be achieved if the datatable can support auto row sizing. This unfortunately will require an update to the OUI Data Table component that needs to support dynamic row sizing. Once we have that we can fix this issue. 

Ive opened an issue in OUI to track this: https://github.com/opensearch-project/oui/issues/1172

In the meantime i think adding a control on top of the table that allows the user to select the number of lines they want to see should mitigate some of the pain here until we have the ideal fix.

**Comment by ananzh** [comment]
For 2.12, we restored legacy table where `truncate:maxHeight` work to adjust row height. For datagrid discover, we added a row height controller. Here is details:


https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/5e6ddd96-56f0-419f-9da2-28d10ae6788d

@stevesimpson418 do you think we could close this bug?

**Comment by sean-codevasp** [comment]
@ananzh video looks good. i am using managed opensearch in aws. hope this gets release asap with managed service as well. when do u expect that enduser of aws could get this?
