### ISSUE TITLE
[BUG] UI Glitch when mouseover Discover document

### ISSUE THREAD

**Issue by seanneumann** [opensearch-project/OpenSearch-Dashboards#5230]
**Describe the bug**

<img width="1077" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/1413295/cf28c5fa-72e8-432a-820f-d98efcafccac">

When you go to the Discover and mouseover a document, the text shifts when the expand button appears.

<img width="306" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/1413295/03fe6901-4ddd-466f-8833-47eb70d8302c">

**To Reproduce**
1. Go to Discover
2. Make sure there are multiple documents listed
3. Hover mouse over a document
4. Notice the text shift when the expand button appears.

**Expected behavior**
The button should exist on a higher z-index and not manipulate the document space. The text should not shift. 

**Dashboards Version**
2.11 early build

**Comment by ShatilKhan** [comment]
I'd like to take a look at this

**Comment by kgcreative** [comment]
This may be an implementation bug with the [OUI Data Grid component](https://oui.opensearch.org/1.3/#/tabular-content/data-grid), and how truncation + the hover overlay interacts with each other

**Comment by joshuarrrr** [comment]
Yeah, I'm also pretty sure this will first need a fix at the OUI component level.

**Comment by ShatilKhan** [comment]
Can I get some guidance on what kind of changes should be made on OUI component level @joshuarrrr 
Maybe I can open an Issue & work on it in OUI?

**Comment by kgcreative** [comment]
So looking at OUI it seems like data grid will float those items by default (there is no text jank in the demo website) -- this leads me to believe there may be some overrides or props that aren't set correctly in the implementation. I would start there

**Comment by ShatilKhan** [comment]
All right I'll look into OUI & try to understand it

**Comment by joshuarrrr** [comment]
@kgcreative Do you know if the demo site have any cells with multiline text (i.e., where the text needs to be wrapped within the cell)? I think that's the failure case we're seeing here.

**Comment by kgcreative** [comment]
> @kgcreative Do you know if the demo site have any cells with multiline text (i.e., where the text needs to be wrapped within the cell)? I think that's the failure case we're seeing here. 

Honestly this seems like an opportunity to expand the examples in the documentation page for data grid, particularly if we plan to use it in more cases. Should we track that in a separate issue?

**Comment by ananzh** [comment]
Can‘t reproduce it any more in data grid table. Legacy table has no such issue. Close it.
