### ISSUE TITLE
[BUG] Unit test failure in Config.test.ts at M2 Mac mini

### ISSUE THREAD

**Issue by MadaniKK** [opensearch-project/OpenSearch-Dashboards#5232]
**Describe the bug**
Failing 3 Tests in 1 Test Suite in Config.test.ts when using Mac mini with M2 chip

**To Reproduce**
Run the command 
`yarn test:jest src/dev/build/lib/config.test.ts`
**Expected behavior**
The test should have passed

**OpenSearch Version**
Snapshot 3.0.0

**Dashboards Version**
3.0.0

**Plugins**

None

**Screenshots**

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/71857976/55ab152f-a50e-4882-b613-934712ac0b7d)

**Host/Environment (please complete the following information):**
 - OS: macOS Ventura 13.4.1 M2 chip
 - Browser and version: Chrome Version 117.0.5938.88

**Comment by ananzh** [comment]
If you search the code using the error msg `Error(`Unable to find platform ...`, you could see an `ALL_PLATFORMS` array.  Based on the provided array, we do not currently have an entry for the "darwin arm64" platform (M1, M2). This means getPlatform won't find a matching platform for "darwin arm64" and will throw the error you mentioned.

**Comment by ananzh** [comment]
This could be a good first issue.

**Comment by Willie-The-Lord** [comment]
Hi @ananzh I would like to work on this issue. Thanks!
