### ISSUE TITLE
[BUG] Dark Mode in Console hard to read

### ISSUE THREAD

**Issue by seanneumann** [opensearch-project/OpenSearch-Dashboards#5233]
<img width="191" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/1413295/390aeb9e-0d74-4fd7-b8f3-77c1cd902446">

<img width="382" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/1413295/7cda008a-4eff-4671-b989-d4287e8d800e">

In 2.11 (early build) dark mode, go to Dev Tools > Console. Start typing and notice the autocomplete options are dark on dark. Very hard to read. See screen cap. e.g. type "GET _cat"

**Comment by ananzh** [comment]
@kgcreative pls help ~

**Comment by kgcreative** [comment]
@ananzh -- is there a console theme that we can pull that will do the right thing for colors?

**Comment by kgcreative** [comment]
cc: @joshuarrrr -- Josh, i think you've done a minor deep dive into this?

**Comment by joshuarrrr** [comment]
@kgcreative The way pretty much all text editor components work is that they're wrappers around the Ace editor. Within OpenSearch Dashboards, we have this `_ace_overrides` SCSS file that alters the `textmate` ace theme to use OUI themed vars. It's just missing some additional style overrides for `.ace_editor.ace_autocomplete .ace_completion-highlight`, `.ace_rightAlignedText`, `.ace_editor.ace_autocomplete .ace_line-hover`.

**Comment by kgcreative** [comment]
Ok, for dark mode, let's start with:

`.ace_editor.ace_autocomplete .ace_completion-highlight`, let's use the same style as `.ace_url`
`.ace_rightAlignedText`, let's match the `.ace_variable` style
`.ace_editor.ace_autocomplete .ace_line-hover`, let's use the same color as `.ace_active-line

Let's start with that and see how that feels?
