### ISSUE TITLE
[BUG] Disappeared logo files in default_branding 

### ISSUE THREAD

**Issue by sipopo** [opensearch-project/OpenSearch-Dashboards#5237]
Doesn't show default logo

**To Reproduce**
Just open the main page

**OpenSearch Version**
OpenSearch 2.10.0

**Dashboards Version**
OpenSearch Dashboard 2.10.0

**Screenshots**

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/16489000/79f4f5ac-2e3a-41a9-a931-8f7c927c5296)

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/16489000/3b7f3f75-8745-4593-8281-8a91cc6cad68)

**Comment by abbyhu2000** [comment]
Hi @sipopo, that file path is an old file path, and the file is already deleted. The new file paths for the default branding logos are: 
```
src/core/server/core_app/assets/default_branding
```
It might be a caching issue, could you try to clear the cache and hard reload the page?
