### ISSUE TITLE
[Data Explorer][Discover 2.0] New discover ignores "Default columns" setting

### ISSUE THREAD

**Issue by karel-m** [opensearch-project/OpenSearch-Dashboards#5246]
**Describe the bug**

The new discover interface seems to ignore "Default columns" settings

**To Reproduce**

1. Go to - Dashboards Management >> Advanced settings
2. Find section - Discover
3. Change "Default columns" to an explicit list of columns
4. Go to - OpenSearch Dashboards >> Discover

**Expected behavior**

Showing columns according to the "Default columns" setting.

Unfortunately it shows just `@timestamp` + `_source` columns like this:

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/1918753/c75f70a1-019a-4e14-9c5d-9e834d2c79c0)

**OpenSearch Version**

v2.10.0 (installed from RPM opensearch-2.10.0-1.x86_64)

**Dashboards Version**

v2.10.0 (installed from RPM opensearch-dashboards-2.10.0-1.x86_64)

**Host/Environment**
 - Server - Oracle Linux 8
 - Desktop - Browser and version: Chrome 117.0.5938.149 (Windows 10)

**Comment by ananzh** [comment]
@karel-m thanks for helping us find this bug. We will work on it.
