### ISSUE TITLE
[BUG] Current Node version (20.8.0) is incompatible with the current module when running command yarn osd bootstrap

### ISSUE THREAD

**Issue by tranngocsongtruc** [opensearch-project/OpenSearch-Dashboards#5247]
**Describe the bug**

This bug happens when running the command line `yarn osd bootstrap` in the [Development Guide file](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md#prerequisites) in [OpenSearch-Dashboards](hhttps://github.com/opensearch-project/OpenSearch-Dashboards). It appears that the current bootstrap version is incompatible with the 20.8.0 Node version 

**To Reproduce**
1. Go to [Bootstrap OpenSearch Dashboards](https://github.com/tranngocsongtruc/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md#bootstrap-opensearch-dashboards) section in the [DEVELOPMENT_GUIDE](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md#prerequisites) file
2. Run command line `yarn osd bootstrap`
3. See error:
`tructran@Trucs-MacBook-Air OpenSearch-Dashboards % yarn osd bootstrap`
`yarn run v1.22.19`
`error opensearch-dashboards@3.0.0: The engine "node" is incompatible with this module. Expected version ">=14.20.1 <19". Got "20.8.0"`
`error Commands cannot run with an incompatible environment.`
`info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Expected behavior**
bootstrap completed

**OpenSearch Version**
3.0.0-SNAPSHOT

**Dashboards Version**
3.0.0

**Plugins**

Please list all plugins currently enabled.

**Screenshots**
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/60404203/1f52be4b-e76d-4761-b488-bc5350e47f20)

**Host/Environment (please complete the following information):**
 - OS: MacOS Ventura 13.3

**Comment by ananzh** [comment]
Hey @tranngocsongtruc, Node 20 is the latest node version. We just bump node from 14 to 18 (https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3601). Currently we don't support Node 20. As you see from the error msg `Expected version ">=14.20.1 <19"`, the latest version we support is Node 18.

You could install diff node version locally by running `nvm install <some version>` and then `nvm use <installed version`. If you still see issues running OSD or you want to do more investigation on bumping Node to 20, pls re-open the issue.
