### ISSUE TITLE
[BUG] [Dashboard 2.10] - plugins.dataExplorer is undefined

### ISSUE THREAD

**Issue by sipopo** [opensearch-project/OpenSearch-Dashboards#5249]
**Coudn't authorize in web interface**

After login in to the web you get error "plugins.dataExplorer is undefined"

**To Reproduce**
Clear your cookies and open the main page.

**OpenSearch Version**
OpenSearch version 2.10

**Dashboards Version**
OpenSearch Dashboard version 2.10

**Plugins**

alertingDashboards
anomalyDetectionDashboards
customImportMapDashboards
ganttChartDashboards
indexManagementDashboards
mlCommonsDashboards
notificationsDashboards
observabilityDashboards
queryWorkbenchDashboards
reportsDashboards
searchRelevanceDashboards
securityAnalyticsDashboards
securityDashboards

**Screenshots**

![Screenshot from 2023-10-09 14-08-19](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/16489000/98d52452-5b5c-468e-a2e4-6e2d6218ed18)

**Host/Environment (please complete the following information):**
 - OS: FreeBSD 13.2
 -  Firefox 117.0.1

**Comment by ananzh** [comment]
Seems cache issue to me. I see from the log that you are using OSD 2.9 but you mentioned in the issue `OpenSearch Dashboard version 2.10`. Browsers not only cache cookies but also cache assets. If you want to switch from 2.10 to 2.9, tryp clear the browser's cache (not just cookies). If issue persists or if this is urgent, feel free to ping me directly in public slack.

**Comment by sipopo** [comment]
You were right, it was cache issue in an nginx. Thank you.
