### ISSUE TITLE
[BUG] - re-login not working after logout. 

### ISSUE THREAD

**Issue by 0asp0** [opensearch-project/OpenSearch-Dashboards#526]
**Describe the bug**

**To Reproduce**
1. login to opendashboards with default credentials admin/admin -> login is successful
2. logout
3. try tp relogin with the same credentials
4. nothing happens. Login page appears again. In Dev Console (F12) I can see http 401.

**Expected behavior**
re-login is possible

**OpenSearch Version**
1.0.0-rc.1

**Dashboards Version**
1.0.0-rc.1

**Plugins**
all plugins activated  by default

**Screenshots**
![image](https://user-images.githubusercontent.com/25737721/122926051-c0858480-d367-11eb-814f-7c72d0fdc5ee.png)

**Host/Environment (please complete the following information):**
 - OS: Windows 10
 - Browser and version: Vivaldi 4.0.2312.25 (Stable channel) (64-Bit)

**Additional context**

Reload Loginpage with just https://<servername>:<port>/ and you can login again with identical credentials.
The urls are looking slightly different:
not working (get this after logout):  https://opendashboards.k8s-dev.local/app/login?nextUrl=
working: https://opendashboards.k8s-dev.local/app/login?nextUrl=%2F

**Comment by kavilla** [comment]
hey @0asp0 thanks for logging this. Could you update the title to be a little bit more descriptive? Can look into this but will most likely will need to be reassigned to the OpenSearch security plugin.

**Comment by 0asp0** [comment]
sorry, just missed the tile line ;-). Topic is renamed.

**Comment by kavilla** [comment]
hey @0asp0, it's looking like `security_authentication` is getting wiped out and can't return even after logging in until you restore the params in the url and refresh the application. Might be from the API side when we log out of Dashboards. 

But it's related to the security plugin, although I believe it is the engine's plugin that is failing I think it's worth creating in the Dashboard's plugin just in case. 

I would transfer this issue but for some reason I don't have access to do so.  I'm really sorry but do you mind closing this issue and creating a new issue [here](https://github.com/opensearch-project/security-dashboards-plugin/issues/new?assignees=&labels=bug%2C+untriaged%2C+Beta&template=bug_template.md&title=%5BBUG%5D) and copying over the content? I can do so for you if you like, just let me know! 

Thanks!

**Comment by kavilla** [comment]
Hello @0asp0, I've gone ahead and opened the issue in the security plugin repo. 

Please track updates here: https://github.com/opensearch-project/security-dashboards-plugin/issues/790

Thank you!
