### ISSUE TITLE
[BUG] [Data Explorer] Modify columns on switch

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#5268]
**Describe the bug**
Advanced setting `discover:modifyColumnsOnSwitch` does not work for the new data explorer. 

**To Reproduce**

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/0435d696-2a09-4a6a-aefa-e79b3e68e5fb

**Expected behavior**
When the setting `discover:modifyColumnsOnSwitch` is turned off, the columns from the previous index pattern should not be automatically cleared.

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/f03a3139-e066-442d-9fe0-52285a67720c

**Comment by wbeckler** [comment]
What is the purpose of this switch?

**Comment by MadaniKK** [comment]
May I work on this issue? Ty.

**Comment by MadaniKK** [comment]
The workflow of how the selected fields are updated in the left side nav:
in the use effect, when a new indexPattern is selected,  fields will get updated
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/7def75cce9df1a151690b606405296c0995e2de7/src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx#L104-L107

then the selectedfields got updated after the groupFields() function

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/7def75cce9df1a151690b606405296c0995e2de7/src/plugins/discover/public/application/components/sidebar/discover_sidebar.tsx#L125-L135

I am thinking maybe we can add in some logic based on `config.get(DEFAULT_COLUMNS_SETTING)`

**Comment by ananzh** [comment]
> What is the purpose of this switch?

One user story I could think about is that user has some similar index pattern, with most fields same but 1-2 key fields diff. When they nav from one index pattern to another one, they would like to keep all fields even though some of them will be grey. So they could know what index pattern they are using without distinguishing the index pattern name.

**Comment by ananzh** [comment]
@MadaniKK since we have go through the workflow today, could you help us add a clear summary on 
* how index pattern is changed in Discover
* how does `discover.state.columns` update/refresh when index pattern is change 

Thanks~ ❤️

**Comment by MadaniKK** [comment]
Updated the workflow

**Comment by ananzh** [comment]
closed it as it is resolved in #5508
