### ISSUE TITLE
[FEATURE] Discover plugin support PPL 

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/OpenSearch-Dashboards#5277]
**Is your feature request related to a problem? Please describe.**

In the discover tab you can use DQL, but PPL can also be very handy but it's hard to use now.

**Describe the solution you'd like**

Add PPL support to the discover page, but maybe some options need to be disabled when in PPL mode (filtering and such).

**Describe alternatives you've considered**

Workbench, but it's somewhat limited (see the other two tickets)

**Additional context**

None

**Comment by kavilla** [comment]
@ashwin-pc is this sort of the plan with data explorer?

**Comment by ashwin-pc** [comment]
@ict-one-nl Thanks for opening this issue. Yes we have some lofty plans here with https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4165. Discover 2.0 is the first step to achieving this. Keep an eye out for Data explorer.

This being said, Log explorer (part of the observability suite) has support for PPL. Given that they have very similar features, I'm curious to know why you would like to see PPL in Discover as well.

**Comment by ict-one-nl** [comment]
Ah that's on me, never really used the log explorer. Looks pretty much like what I need. Sorry for the inconvenience!
