### ISSUE TITLE
HSTS Missing from Opensearch-Dashboard server

### ISSUE THREAD

**Issue by RickkCedoof** [opensearch-project/OpenSearch-Dashboards#5307]
**Is your feature request related to a problem? Please describe.**

The Opensearch-Dashboards HTTPS server is not enforcing HTTP Strict Transport Security (HSTS).
The responses from the server therefore do not have "Strict-Transport-Security" header.

**Describe the solution you'd like**

A solution to this issue would be to add a parameter in *opensearch-dashboard.yml* with the purpose to add "Strict-Transport-Security" header in all the HTTP responses.

**Comment by asiminiceanu** [comment]
@RickkCedoof you can do it with custom headers also

`
server.customResponseHeaders:
  Strict-Transport-Security: "max-age=31536000; includeSubDomains"
`

**Comment by RickkCedoof** [comment]
Thank you @asiminiceanu,
This effectively adds the header to the HTTP responses.

**Comment by Mohit24012** [comment]
@RickkCedoof, is there any plan for OpenSearch to provide native HSTS header support in a future release?
