### ISSUE TITLE
[BUG] impossible to edit table dashboard with Date Historgram bucket

### ISSUE THREAD

**Issue by flechter** [opensearch-project/OpenSearch-Dashboards#5313]
When i define a data table, if i try to add a bucket with a Date Histogram, if i save it, i can't edit this table anymore.
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17095257/a339e120-e8c5-4d37-8dde-19cde3c8495d)

**To Reproduce**
1. Add a data table to a dashboard
2. Add a bucket "split table"
3. Choose "Date Histogram"
4. Save the widget
5. Try to edit the widget with the toothed wheel and the menu didn't apear

**Expected behavior**
to edit the widget

**OpenSearch Version**
2.10

**Dashboards Version**
2.10

**Plugins**

**Screenshots**
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17095257/215f87cf-edb1-4b99-ace5-07fcde166daa)

**Host/Environment (please complete the following information):**
 - OS: Linux redhat 7
 - Browser and version : firefox or chrome

**Comment by AMoo-Miki** [comment]
I wonder if this could be related to vis-augmenter which was fixed with https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5190. Can you plz check if this is solved for you in 2.11?

**Comment by flechter** [comment]
Hello,
I have installed the 2.11 and yes it solve our problem, thank you for the update !
Regards
Stephane Didierjean
