### ISSUE TITLE
[CI] `set-output` is deprecated 

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#5322]
**Describe the bug**

Our github action is complaining the following:

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

We use `set-output` to set environment variables; maybe we can upgrade to using environment files as suggested above here: https://github.com/opensearch-project/OpenSearch-Dashboards/tree/466d298d673bf3d46acecf39a04ed6501d9ac960/.github/workflows

**To Reproduce**

Here is one example github action run:
https://github.com/opensearch-project/OpenSearch-Dashboards/actions/runs/6540904090?pr=5300

**Comment by shawnkchan** [comment]
Hi, I'd like to be assigned to this issue!

**Comment by kavilla** [comment]
@vvavdiya can you comment on this issue so I can have it assigned for you.
