### ISSUE TITLE
Removal of non-inclusive term "whitelist" with neutral language

### ISSUE THREAD

**Issue by mrudrego** [opensearch-project/OpenSearch-Dashboards#533]
**Is your feature request related to a problem? Please describe.**

OpenSearch-Dashboards(Kibana) has a configuration property elasticsearch.requestHeadersWhitelist.
There are concerns raised on usage of this non-inclusive terminology. Linux team has approved on replacing these non-inclusive terminologies. There are many other tech companies and open-source projects that have removed references to racially-charged jargon from their code for more neutral and inclusive language. 

**Describe the solution you'd like**

This request is to replace the term Whitelist used in one of the OpenSearch-Dashboards(kibana) configuration with a neutral word say allowlist or passlist

**Additional context**

Reference: https://www.zdnet.com/article/linux-team-approves-new-terminology-bans-terms-like-blacklist-and-slave/

**Comment by dblock** [comment]
Thanks for highlighting this. A similar issue was discussed in https://github.com/opensearch-project/OpenSearch/issues/472, specifically https://github.com/opensearch-project/OpenSearch/issues/472#issuecomment-822506656. We want to fix this, please do consider contributing a backwards-compatible change.

**Comment by kavilla** [comment]
For code, it should be straight forward. But configs, I recommend we initially start with update name and deprecating the previous config key instead of out right removing them. If we end up removing them then the application won't start if the user does not modify their config which would go against our backwards-compatible change. But for 2.x we can remove them completely.

**Comment by kavilla** [comment]
Hello we will track this here: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1319. We will work on deprecating this configurations then for `3.x` we will remove them as this will be a breaking change.
