### ISSUE TITLE
[BUG] Discover event count does not go above 10,000

### ISSUE THREAD

**Issue by mobiusmalware** [opensearch-project/OpenSearch-Dashboards#5359]
**Describe the bug**
For any of my indices, if I choose a time frame that exceeds 10,000 records/events, it will max out at that point. Notice in the screenshot that my count tops 400,000 for the given time frame. I have deleted and recreated index patterns and visualizations in an attempt to fix the issue to no avail.

**To Reproduce**
1. Go to 'Discover'
2. Click on time frame picker
3. Set to any period of time that includes more than 10k events
4. Click 'Update'

**Expected behavior**
There should be a total number of records for the time frame chosen.

**OpenSearch Version**
2.11

**Dashboards Version**
2.11

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

![10kbug_opensearch](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/18300032/d622b3f6-5b0e-4212-91ed-1fcfa5e3c623)

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser and version: Firefox 118.0

**Comment by zhongnansu** [comment]
we have an open issue in OpenSearch repo with regard to this limitation. https://github.com/opensearch-project/OpenSearch/issues/2093
