### ISSUE TITLE
Playground - OpenSearch Demo Site

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/OpenSearch-Dashboards#538]
Do you have plan to add a demo page for Dashboards? 
Similar to Kibana: https://demo.elastic.co/app/dashboards#/view/welcome_dashboard?

**Comment by kavilla** [comment]
Hey @zhongnansu! 

Speaking for myself I definitely believe we wanted one and I believe the @opensearch-project/opensearch-dashboards-maintainers agreed. In terms of timelines I believe we wanted to have a stable release version but will need to get resources and allocation for this.

@ahopp what do you think?

**Comment by elfisher** [comment]
If we do this, can we break the logic of generating the data set out into a plugin or something? I think it would be really powerful if there was a way to easily configure a generator for sample data sets :)

**Comment by ahopp** [comment]
Thanks @kavilla! I agree that this would be great to add - after GA I think this would be a great addition to the roadmap. 

RE: breaking out the logic of generating the data set into a plugin, this sounds like a separate feature but one we should also add to the backlog for prioritization.

**Comment by tmarkley** [comment]
Adding 2.0 for now since it would be great to showcase the changes from 1.x. We'll re-prioritize as needed.

**Comment by ahopp** [comment]
@stockholmux I think you where thinking about a demo experience previously. Before we propose some Dashboards work, can you share what you were thinking?

**Comment by kavilla** [comment]
Missed the mark here again, but I think with the current CI/CD being finalized I think we can begin thinking about exposing doing a nightly run of the executable built.

**Comment by seraphjiang** [comment]
The demo/playground project will be track at https://github.com/opensearch-project/dashboards-anywhere/issues/8

**Comment by Flyingliuhub** [comment]
Yes. we can close this one, it will go out via 2.3 releaase

**Comment by noCharger** [comment]
Closed after syncup with @Flyingliuhub
