### ISSUE TITLE
[BUG]Discover: Some Fields Aren't Displayed in the Left Navigation Bar

### ISSUE THREAD

**Issue by MadaniKK** [opensearch-project/OpenSearch-Dashboards#5400]
**Describe the bug**
In Discover some fields are not being displayed in the left Field Nav              
              
**To Reproduce**
* step 1: go to dev tools. create an index and add nested field.
```
PUT test-2/_doc/1
{
  "products": [
    {
      "base_price": 28.99,
      "discount_percentage": 0,
      "quantity": 1,
      "manufacturer": "Tigress Enterprises"
    },
    {
      "base_price": 32.99,
      "discount_percentage": 0,
      "quantity": 1,
      "manufacturer": "Oceanavigations"
    }
  ]
}

PUT test-2/_doc/2
{
  "products": [
    {
      "base_price": 31.14,
      "discount_percentage": 5,
      "quantity": 1,
      "manufacturer": "Virora"
    },
    {
      "base_price": 35.69,
      "discount_percentage": 10,
      "quantity": 3,
      "manufacturer": "Oceanavigations"
    }
  ]
}

```
* step 2: go to `Dashboards management` --> `Index patterns` --> `create index pattern`
<img width="1612" alt="Screenshot 2023-10-25 at 12 49 21" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/f50862e1-5ee1-4935-a4cb-7d246cf21c8c">

* step 3: enter `test*` to match `test-2`
*  go back to discover. in the index pattern selector (on top of left nav), choose `test*`.

So in new Discover (2.11), if you check the left field nav, you could see we miss the nested field`products`. but the flyout and display are fine. It is just that there is no way customer could select nested field. 

<img width="1788" alt="Screenshot 2023-10-25 at 12 37 29" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/83b9775d-3eb4-4e0e-bb85-047951f00d85">

But if we do the above steps in 2.9 OSD with legacy discover, we could see `products` in left nav and once click `+` button to select it, you could see multiple lines in each row as customer shown.

<img width="1779" alt="Screenshot 2023-10-25 at 12 13 16" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/31624488-c4f8-4059-b0cd-b7df75a898a4">
<img width="1042" alt="Screenshot 2023-10-25 at 12 44 11" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/9fec8cde-7dd8-4dcf-8e87-f6d66a94a6d5">

<img width="1674" alt="Screenshot 2023-10-25 at 12 45 34" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/13083206-d204-444a-8e10-176b81205262">

I think we need to first solve the nested field not picked up by left nav then verify if we see multiline issue after select the nested field.

_Originally posted by @ananzh in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5208#issuecomment-1779957586_

**Expected behavior**
The Left field nav should display all these fields
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/71857976/7f35fc74-dfd3-47fd-b47b-ebc40f03c5eb)
 
**OpenSearch Version**
3.0.0

**Dashboards Version**
Discover 2.11

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by MadaniKK** [comment]
Here is what @ananzh and I found after some digging:
the fields are rendered based on some conditions, which involve mostly two objects `indexPattern` and `fieldCounts`. What is causing the subfields of `Product` not to be displayed is the construction of `fieldCounts`.  All the subfields exist in the object `indexPattern` but not in `fieldCounts`

We found that the `flattenHit(row)` function here never unnest the subfields inside `Product`, causing all the subfields missing in 'fieldCounts` https://github.com/opensearch-project/OpenSearch-Dashboards/blob/eeb325163a65c750405714ea6674ce26607608d5/src/plugins/discover/public/application/view_components/utils/use_search.ts#L164-L175

**Comment by MadaniKK** [comment]
I am also confused about the purpose of fieldCounts. We will do more research on this later.
And I wonder, when constructing the field counts, why can't we just use whatever existing keys in 'IndexPattern'. Because `indexPattern` must have gone through unnesting successfully every time we create/update a new fields.
Thus I thought `const fields = Object.keys(indexPattern.flattenHit(row));` can be changed into `const fields = indexPattern.fields.getAll().map((field) => field.displayName);`
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/eeb325163a65c750405714ea6674ce26607608d5/src/plugins/discover/public/application/view_components/utils/use_search.ts#L164-L175
But Still right now we are still going to preserve the old codes and just fix the `flattenHit()` function

**Comment by MadaniKK** [comment]
We just discovered that if we don't construct the fields through the original way `const fields = Object.keys(indexPattern.flattenHit(row));` , it would cause a new bug: cannot display nested object properly in Discover table
new bug:
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/71857976/cbd2e9da-e00c-4c96-9298-d9bbc160021d)
expected:
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/71857976/31752daa-8be3-4c79-8770-8d706dfea483)
So the best way to resolve this issue is still using flattenHitWrapper functions

**Comment by Willie-The-Lord** [comment]
@MadaniKK Thank you for sharing the findings.

**Comment by ananzh** [comment]
resolved by https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5429
