### ISSUE TITLE
[BUG] No line wrapping when displaying fields (dashboard v 2.11)

### ISSUE THREAD

**Issue by uranru** [opensearch-project/OpenSearch-Dashboards#5404]
**Describe the bug**
The functionality of the Discover section has deteriorated after updating Opensearch-dashboard to version 2.11.
No line wrapping when displaying fields.
It is very inconvenient to work with long text fields.

**To Reproduce**
Go to the Discover section.
Select multiple long fields

**Expected behavior**
Fields are displayed in several lines

**OpenSearch Version**
2.11

**Dashboards Version**
2.11

**Plugins**

**Screenshots**
Top screenshot version 2.9
Bottom screenshot version 2.11

![os-dash](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/44777964/ca40cbb8-63cc-418d-af59-299e35f1f934)

**Host/Environment (please complete the following information):**
 - OS: Windows 10
 - Browser and version: Firefox119.0  

**Additional context**

**Comment by wbeckler** [comment]
This looks same as https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5208
Closing as duplicate, but feel free to reopen if there's a difference.

**Comment by ashwin-pc** [comment]
Closing this as it is similar to #4859. Lets use that as the single thread for this issue.

**Comment by seraphjiang** [comment]
re-open this issue as it is line-wrap issue on result grid message, path columns, it is not duplicated to #4859



2.9

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/550437/0afe0242-368d-4627-9b7c-27942db722ed)

2.11

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/550437/be60477c-9498-46a6-9a33-cabc228fbc97)

**Comment by abbyhu2000** [comment]
We are tracking to resolve both this issue and #4859 for 2.12 release. @seraphjiang @ashwin-pc @uranru

**Comment by seraphjiang** [comment]
Thanks @abbyhu2000 , I assume you mean backport to 2.11 branch not conduct a 2.11 patch release right?

> We are tracking to resolve both this issue and #4859 for 2.12 release. @seraphjiang @ashwin-pc @uranru
> 
> And the fix will also be backported to 2.11 release.

**Comment by ananzh** [comment]
In 2.12 we provided two ways for users to adjust row height to avoid wrapping. We restored legacy table where `truncate:maxHeight` can work to adjust row height. For datagrid discover (2.11 table), we added a row height controller. Pls see the details:

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/5e6ddd96-56f0-419f-9da2-28d10ae6788d

@uranru do you think these fixes resolve your issue? could we close this? thx
