### ISSUE TITLE
[BUG]`match_all` query filters applied despite courier:ignoreFilterIfFieldNotInIndex setting enabled

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#5423]
**Describe the bug**
The `match_all` query filter is applied and included in the OpenSearch request when `courier:ignoreFilterIfFieldNotInIndex` is enabled. This setting is used to skip filters that apply to fields that don’t exist in the index for a visualization. However, we see filter applied even if the field the filter applies to does not exist in the index pattern of the visualization, which contradicts the expected behavior as per the setting's definition.

<img width="1695" alt="Screenshot 2023-11-03 at 10 56 38" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/2c71d0c5-1e2a-40ec-a0de-70b8d483d0ed">

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/d58f433d-8c92-406b-be15-739aa301863e

**To Reproduce**
* Navigate to `Stack Management` > `Advanced Settings` > `courier:ignoreFilterIfFieldNotInIndex`.
* Enable the setting `courier:ignoreFilterIfFieldNotInIndex` and save the changes.
* Create a visualization of type DataTable and choose an index pattern.
* In Buckets, split rows, choose aggregation as "Terms", select a field of type string, and click Update.
* Add a normal filter (match_all query) that targets a non-existent field in the chosen index pattern.
* Click `Inspect` -> `View: Requests` -> Click `request`:  Here the custom query DSL that we created is still sent in the request. 

**Expected behavior**
**with courier:ignoreFilterIfFieldNotInIndex Enabled**
Filters that target fields not present in the index pattern should be skipped, and not included in the request. Both `prefix` query and `match_all` query should not send the request for non-existent fields.

**OpenSearch Version**
any

**Dashboards Version**
any

**Plugins**

na

**Comment by ananzh** [comment]
https://github.com/opensearch-project/dashboards-visualizations/issues/281

**Comment by anand3493** [comment]
@ananzh  I believe you misunderstood my issue raised in the bug https://github.com/opensearch-project/dashboards-visualizations/issues/281

Re-explaining:
courier:ignoreFilterIfFieldNotInIndex is enabled now

Irrespective of the type of filter (either custom query DSL or normal filter), the filter should be applied if the field is present in the chosen index.

The filter should not be applied only when the field is not present on the index pattern

My issue is I have enabled the ignoreFilterIfFieldNotInIndex option and I create a visualization for a index pattern and I create a custom query DSL filter **for a field which is present on the chosen index**.
Expected Outcome: Fitler should be applied.
Current misbehavior: Filter is not sent in the request.
