### ISSUE TITLE
[BUG] HeaderNavControl missing border at right

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/OpenSearch-Dashboards#5449]
**Describe the bug**

When register more than one navControl on header, the border is missing between them.

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113890546/6bfe546c-ae0d-4f18-bbe0-401eab34519f)

**To Reproduce**

**Expected behavior**

Border should displayed 
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113890546/e0ffdd0d-e0ce-4a87-9b44-eb740ef9ea3d)

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by AMoo-Miki** [comment]
@kgcreative can you please comment on this?

**Comment by kgcreative** [comment]
Yes please -- there needs to be an option for having multiple dividers between items.
