### ISSUE TITLE
Easily view nested structured data in Discover

### ISSUE THREAD

**Issue by michaelruigrok** [opensearch-project/OpenSearch-Dashboards#5459]
Essentially I want the column JSON drop-downs of Discover 1.0 back.

Let's say I have a nested object that I want to compare between records.  If a record has a lot of data, the values you might not be able to see a field in the in-line list view, meaning you have to use the source pop-out view. This makes quickly comparing values between rows in the output very painful.

I propose having a column option that lets you toggle a column to display a full multi-line pretty JSON version of a field. This would let you quickly compare each record's value for a nested object without needing to click each row to open an alternative view.

Another benefit of the JSON view is making it easy to display arrays of objects. If you have `object.array.obj.obj.value`, and a column for `object.obj.obj.value`, the column could simply map the `object.array` accordingly and display the result as a JSON array . The current solution of not allowing list data at all in columns is rather a sad state of affairs, in my opinion.

If there's another recommended way to achieve this, I would love to hear it. Thank you very much!

**Comment by AMoo-Miki** [comment]
The JSON view is still available on the new Discover experience. Have you tried the button next to each row to see if that fulfills your needs?

<img src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/3527403/13c77c8a-eb1c-4d1d-861c-a688d5e72306" width=450px />

**Comment by AMoo-Miki** [comment]
There is also a PR to enhance the fields that are available on the left-menu: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5429.

**Comment by AMoo-Miki** [comment]
If neither of those options are what you were looking for, please add some details of your vision and reopen this issue.

**Comment by michaelruigrok** [comment]
@AMoo-Miki I have clarified the description of this issue. I am aware of the existing JSON view present in new Discover, I believe this is insufficient for the kind of quick structural comparison it needs to support. My request is to display specific JSON in each row to quickly compare dozens of rows without having to click open the full JSON view. Please let me know if my description is not clear enough.

Could you please re-open this issue? it appears I lack the permissions.

**Comment by rahul-sophos** [comment]
For my use case, I found a workaround for a better view in the Discover tab by defining a scripted field as:

if (params._source.containsKey('key_at_level1') && params._source['key_at_level1'].containsKey('key_at_level2') && params._source['key_at_level1']['key_at_level2'].containsKey('key_at_level3')) { return params._source['key_at_level1']['key_at_level2']['key_at_level3']; }
