### ISSUE TITLE
[BUG] Cannot open in a new tab link to visualization

### ISSUE THREAD

**Issue by remyleone** [opensearch-project/OpenSearch-Dashboards#5460]
**Describe the bug**

I cannot open in a new tab a visualization when I look for one.

**To Reproduce**
1. Go to Visualize tab https://opslog.internal.scaleway.com/app/visualize#/
2. Try to Right click on a link to open it in a new tab
3. It doesn't show up that

**Expected behavior**

I expect when I see a link to be able to open it in a new tab

**OpenSearch Version**

v 1.3.1-SNAPSHOT

**Plugins**

Reporting
Index Management 

**Screenshots**
<img width="419" alt="Capture d’écran 2023-11-10 à 10 40 13" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/300834/59efb5b0-9e25-42f5-a2ff-1698498b6898">

**Host/Environment (please complete the following information):**
 - OS: macos 14.1.1
 - Browser and version Chrome 118

**Comment by joshuarrrr** [comment]
@remyleone This was fixed in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2395 and released in versions `1.3.7` and `2.4.0`. I'd recommend at least upgrading from 1.3.1 to `1.3.7` for a number of security and bug fixes.
