### ISSUE TITLE
[BUG] Discover - "Field" pane not collapsible

### ISSUE THREAD

**Issue by toby181** [opensearch-project/OpenSearch-Dashboards#5472]
**Describe the bug**

In OpenSearch Dashboards 2.9 the "fields" (Selected fields / Available fields) pane was collapsible which saved some space for the view of the logs, which especially nice to have for saved queries that have no need to show available or selected fields.

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/91274455/4196b126-e4d8-4712-bdfb-83d203e5420c)
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/91274455/956b587a-752b-416c-bce1-09d4f3de2628)

In OpenSearch Dashboards 2.11 this option is no longer available. The pane got even bigger, compared to version 2.9.
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/91274455/5b7fd0a5-0a5c-4aab-be19-3543b94a8c77)

**Expected behavior**
"Fields" pane is collapsible.

**OpenSearch Version**
2.11

**Dashboards Version**
2.11

**Additional context**

**Comment by AMoo-Miki** [comment]
Thanks @toby181. We are tracking this at https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4780. Please feel free to add any comments or suggestions to that issue.
