### ISSUE TITLE
Drilldown feature in dashboards 

### ISSUE THREAD

**Issue by romarito90** [opensearch-project/OpenSearch-Dashboards#5478]
Recently we install Opensearch in our servers, so we are going to migrate from Elasticsearch to Opensearch 

We'll try to build dashboards with drilldowns but this feature is not found in the graphics or visualizations 

We need to install something else or a license or this feature is not integrated with Opensearch like Elasticsearch in Kibana?

Any suggestion will be excellent for us to add drilldowns in dashboards in Opensearch 

![imagen](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/114606380/e56cab17-c694-452f-92c1-fb0a3c6e8115)

![imagen](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/114606380/4f65bd11-72a9-445d-ba17-d2a61118c231)

**Comment by Willie-The-Lord** [comment]
Hi @romarito90, it looks like issue #1308 matches your needs, but the feature is still under development. I'm actively working on the customizable drilldown plugin to address this!

**Comment by wbeckler** [comment]
Yup, closed as dupe
