### ISSUE TITLE
[BUG] Can't filter index patterns in the "Discover" page

### ISSUE THREAD

**Issue by renkai95** [opensearch-project/OpenSearch-Dashboards#5499]
**Describe the bug**

In the previous versions of the discover page, you could filter index patterns when typing to change the selected index pattern. This is no longer possible in 2.11, as all index patterns remain when trying to filter them out. This poses a problem for large projects with many index patterns, as you have to scroll far to find what you need.

**To Reproduce**
1. Go to the "Discover" page under Opensearch Dashboards
2. Click "Select a Datasource" and type in the name of an index pattern

**Expected behavior**

Non-relavant index patterns should be filtered out when typing

**OpenSearch Version**
2.11

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.
(Unknown, using the latest 2.11 version of Opensearch AWS provides, with OpenSearch_2_11_R20231113 this service version)

**Plugins**

none

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Amazon hosted Opensearch
 - Chrome 

**Additional context**

none

**Comment by kavilla** [comment]
Hello @renkai95,

Thank you for opening, looks like we have a current draft PR to resolve:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5484

cc: @mengweieric
