### ISSUE TITLE
[BUG] Log table rows in the "New Discover" UI flicker after scrolling to the bottom

### ISSUE THREAD

**Issue by gjd6640** [opensearch-project/OpenSearch-Dashboards#5512]
**Describe the bug**

Log table rows in the "New Discover" UI flicker after scrolling to the bottom.

**To Reproduce**
1. Go to the Discover dashboard (leave the "New Discover" theme enabled)
2. Adjust the search criteria and refresh such that multiple pages of logs are found
3. Scroll down to the bottom of the list of log entries
4. Observe:  There should be links to multiple pages of results in the bottom right
5. Observe:  The log entries data in the table all now flicker between log data and blank

**Expected behavior**
Log lines in the table should not flicker. This makes them unusable.

**OpenSearch Version**

Unknown - I think as just a user I lack permission to get to this info

**Dashboards Version**

v2.10.0 (found this value in the '?' menu)

**Plugins**

Google Docs Offline
Symantec Extension
Axiad Portal Extension

**Screenshots**

![rlr2](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/3105435/ba72290c-f064-4bd8-a5c2-05f179b7c8c4)

**Host/Environment (please complete the following information):**
 - OS: Windows 10 enterprise 10.0.19045 Build 19045
 - Chrome: 119.0.6045.124 (Official Build) (64-bit)

**Comment by ananzh** [comment]
Hey @gjd6640 thanks for opening this issue. I would like to reproduce it first in 2.10. Have 2 questions
1) For `Adjust the search criteria and refresh such that multiple pages of logs are found`, what do you mean by `adjust the search criteria`? Is it add some search field in the side nav? add a query in the top nav?
2) For `Observe: There should be links to multiple pages of results in the bottom right`, what are the links to multiple pages? you mean pagination? 

Is there a way that you could help us add a screen recording and add it in the issue? and a clear screen shot for the expected links to multiple pages. This would help us quickly understand and resolve the issue. Thanks a lot for testing new Discover for the community!!!

**Comment by gjd6640** [comment]
Here's the filter criteria. I'm not really filtering for this example other than using the dev environment index. Note that while capturing this I noticed that depending on which columns I include in my results and what order I put them in the flicker problem sometimes goes away.

![OpenSearchUI](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/3105435/69d88b1f-4f43-40e2-911d-7f44491df9b1)

Here's a video showing the flicker:

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/3105435/1ce124ba-ddb7-435c-9be4-457f4b553658

Here's some performance data captured by the browser showing that a scroll event seems to be firing repeatedly:

![OpenSearchUI_performanceAnalysis](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/3105435/b455ad52-06ea-4990-ab36-bfcf0c4b46c1)

**Comment by mz118** [comment]
I saw similar behaviour in 2.11.0.

**Comment by ananzh** [comment]
Performance is resolved in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6599
Close it for now. Let us if there is any other issues.
