### ISSUE TITLE
[BUG][Disocver] Timefield of an indexPattern would get added to selected field in the side nav when removing a column from the canvas

### ISSUE THREAD

**Issue by MadaniKK** [opensearch-project/OpenSearch-Dashboards#5527]
**Describe the bug**
Everytime we remove a column from the canvas, the timefield of the indexpattern get added to the selected field in the side nav.

**To Reproduce**
1. Go to Discover, selected some columns
2. Click on 'remove column'
3. Look at the selected fields in left side bar
4. See the timestamp/order date column got added to the selected field
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/71857976/f4755f8d-b298-47f8-8bfe-2ce82b5bd1f5)
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/71857976/c9569ea2-5dc8-4826-98fb-c7cf1cb5333b)
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/71857976/fe28c55a-8de6-4f43-aaaf-86ca8529b8df)

**Expected behavior**
The time field shouldn't get added to the selected field automatically.

**OpenSearch Version**
Please list the version of OpenSearch being used.
3.0.0

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by ananzh** [comment]
@MadaniKK Thanks for opening. I have assigned it to you.

**Comment by MadaniKK** [comment]
I suggest keeping the time column in the side nav bar because it exists in the legacy cover, and when the hide time column is off, we can still add the time column to the selected field and use drag-drop to arrange column order.

**Comment by ananzh** [comment]
Close it as it is resolve in #5538
