### ISSUE TITLE
[BUG] Default index in Advanced settings is never saved

### ISSUE THREAD

**Issue by Kluk** [opensearch-project/OpenSearch-Dashboards#5529]
The "Default index" setting in the "Advanced settings" is not correctly saved.
For some reason, OpenSearch chose a random index and used it as the default index. I tried to reset this setting to default, which is 'null', I saved the settings but the change is not applied. If I go back to Advanced settings, the previous index is still configured. I also tried to set another index but the behaviour is the same.

**To Reproduce**
1. Go to Dashboards Management -> Advanced settings.
2. Modify the setting 'Default index' and save the configuration.
3. Go to another page and then go back to Dashboards Management -> Advanced settings.
4. 'Default index' still contains the old value, not the one set up in step 2.

**Expected behavior**
'Default index' value must be correctly saved.

**OpenSearch Version**
OpenSearch 2.11 on AWS

**Dashboards Version**
OpenSearch Dashboards 2.11 on AWS

**Plugins**

None

**Screenshots**

None

**Host/Environment (please complete the following information):**
 - OS: Windows 10 22H2
 - Mozilla Firefox 119.0.1 (64-bit)

**Additional context**

This issue appeared after upgrading from version 2.9 to version 2.11.

**Comment by abbyhu2000** [comment]
Verified this bug and it seems like it exists in version 2.9 to 2.11 as well as 1.3. 

It seems like when there are index patterns, one of the index pattern will always be automatically set as the default. And we are unable to set and save the default index as null.

If there are no index patterns, the default index will always be null. 

Do we want to do anything with this? or is this an expected behavior? @ashwin-pc @kavilla @joshuarrrr

**Comment by ashwin-pc** [comment]
This is where the logic that handle's default index takes place. As you can see, if there isnt an index pattern for the default index, then the default index value is cleared and set to the default index ID for the first index pattern. @Kluk could this be the issue that you are facing?

**Comment by ashwin-pc** [comment]
@Kluk can you share a screen recording of the bug? One where the index exists?

**Comment by Kluk** [comment]
> @Kluk can you share a screen recording of the bug? One where the index exists?

I'm sorry, I don't understand what I'm supposed to take a screenshot of. Could you be more specific?

**Comment by ashwin-pc** [comment]
Sure, what im asking for is a screen recording where you reproduce the bug using the steps you mentioned. I tried the steps like you mentioned and cant see this issue, so i'm wondering if there is a difference between what you are doing and me.
