### ISSUE TITLE
[BUG] Index Pattern Filtering when searching in Dashboards

### ISSUE THREAD

**Issue by edha84564** [opensearch-project/OpenSearch-Dashboards#5533]
**Describe the bug**

In OpenSearch v2.9, when searching for an index pattern under Discover, the search results will filter down to only the relevant matches whilst highlighting the text in bold. In OpenSearch v2.11 the search result does not filter down at all. It simply highlights the text in bold. This is cumbersome for users that have many index patterns.

**To Reproduce**
1. Go to OpenSearch Dashboard
2. Click on "Discover"
3. In the top left, search for an index pattern
4. Observe how the search results are filtered
5. Compare this for v2.9 and v2.11

**Expected behavior**
In v2.9 search results are filtered showing only the relevant matches. This is the expected behavior. Not the case in v2.11

**OpenSearch Version**
Opensearch v2.9
Opensearch v2.11

https://docs.aws.amazon.com/opensearch-service/latest/developerguide/what-is.html#choosing-version

**Dashboards Version**
Dashboard v 2.9.0
Dashboard v 2.11.0

**Plugins**

Query Workbench
Reporting
Anomaly Detection
Maps
Security Analytics
Search Relevance
Machine Learning

These plugins are part of Amazon OpenSearch Service

**Screenshots**

![2 9](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/134039433/057eae29-a5cc-49e7-b893-6d5c2aa8dc0f)
![2 11](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/134039433/c09f0b5d-07eb-485a-9974-a68a56bc914c)

**Host/Environment (please complete the following information):**
Amazon OpenSearch Service. Default cluster settings.

**Comment by kavilla** [comment]
cc: @mengweieric
