### ISSUE TITLE
[BUG][Feedback] Content is cut off in the Discover view

### ISSUE THREAD

**Issue by albgus** [opensearch-project/OpenSearch-Dashboards#5556]
**Describe the bug**

Since the modernization of the Dashboards was introduced content is being cut off in the discover view if the field is too long. In the previous versions the content would be word wrapped if the string was too long to fit.

**To Reproduce**
1. Go to https://playground.opensearch.org/app/data-explorer/discover#?_a=(discover:(columns:!(order_date,manufacturer,products),isDirty:!f,sort:!()),metadata:(indexPattern:ff959d40-b880-11e8-a6d9-e546fe2bba5f,view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d,to:now))&_q=(filters:!(),query:(language:kuery,query:''))
2. Resize the fields or add more fields.
3. Note that long values will be cut off.

**Expected behavior**
I would expect the content of the fields to wrap in the column, at least to some extent. I can understand that it would be problematic to show very large messages but the current implementation makes it quite difficult to deal with logs that include any kind of generic text as it's quite often hard to fit in the column. It also requires a lot more fiddling with the field sized to properly display the data then the previous version.

**OpenSearch Version**
2.11.0

**Dashboards Version**
2.11.0

**Plugins**

* repository-s3

**Screenshots**

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/4476818/860e8d0e-f39c-401d-a3f6-54b2211ac8e9)

**Host/Environment (please complete the following information):**
 - OS: macOS 14.1.1
 - Browser and version Chrome 119.0.6045.159

**Comment by mruzicka** [comment]
Having to hover and open each entry makes quick scanning through the entries impossible.
Could you perhaps reintroduce the original behavior as a configurable option?

**Comment by Brightside56** [comment]
For the sake of god, make possibility to view full entries
