### ISSUE TITLE
[BUG] Searching for index patterns does not filter the list

### ISSUE THREAD

**Issue by albgus** [opensearch-project/OpenSearch-Dashboards#5558]
**Describe the bug**

When searching for index patterns in the OpenSearch dashboard non-matching patterns are not excluded. The only thing that happens is that the matching texts is displayed in bold, which is frankly not that visible, especially if you have to scroll through a longer list of patterns.

This is made _much_ worse by the list no longer being ordered, making it very annoying to try and find the right index when you have 10s of them in the list.

**To Reproduce**
1. Go to https://playground.opensearch.org/app/data-explorer/discover and search for an index pattern

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/4476818/955b54b1-6db3-47ca-8c14-4e845eef1b23)

**Expected behavior**
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/4476818/7c7d4b26-d080-4854-bdfc-a2fbbb1182c4)

**OpenSearch Version**
2.11.0

**Dashboards Version**
2.11.0

**Plugins**
* repository-s3

**Host/Environment (please complete the following information):**
- OS: macOS 14.1.1
- Browser and version Chrome 119.0.6045.159

**Comment by lyradc** [comment]
We are still seeing this issue on 2.11.0. Is there an estimated time this will be released?

**Comment by brian-grabau** [comment]
Looks like this is going to be fixed in 2.12.x scheduled around 3rd week in Feb. This is almost crippling our deployment as we have a large list of index patterns. Is there any way we could get a 2.11.2 release to resolve this one issue sooner?

**Comment by peternied** [comment]
Thanks for the context @brian-grabau - I'd recommend following up in the OpenSearch slack channel for [#dashboards](https://opensearch.slack.com/archives/C01QENNTGUD) to make sure this gets more active consideration.  Good luck and thanks for bring in up during todays triage meeting.
