### ISSUE TITLE
[BUG] Dev tools console autocomplete doesn't work well with aliases

### ISSUE THREAD

**Issue by BSFishy** [opensearch-project/OpenSearch-Dashboards#5567]
**Describe the bug**

The console autocomplete doesn't work well with aliases. For example, if I have an alias called `alias` to a index called `index`, if I try to type in requests related to the `alias` alias, I won't get very much autocomplete. For example, if I start typing in `GET alias`, I won't get auto-completion on `alias`. Further, if I try creating a search request on that alias, I won't get auto-completion on field names.

**To Reproduce**
1. Create an index and populate it with data
2. Create an alias pointing to the index
3. Go to dev tools console
4. Type in `GET [alias name]/_search` and notice you don't get auto-completion on the alias name
5. Start writing in a search query. I used:
   
   ```json
   {
     "query": {
       "term": {
         "": {
           "value": "VALUE"
         }
       }
     }
   }
   ```
   
   Notice in the empty string you don't get auto-completion on field names.
6. Now try steps 4-5 with the index instead of the alias and notice auto-completion works as expected.

**Expected behavior**

I would expect autocomplete to work the same as if I were using an index rather than alias.

**OpenSearch Version**

2.8.0

**Dashboards Version**

Main

**Plugins**

OSD:
 - Security

OS: Everything included with the tarball distribution

**Screenshots**

![Screenshot (189)](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/6763209/15297a18-f1ba-4ad3-84aa-1ce059ca0984)
(I should be getting an autocomplete prompt for the field name)

**Host/Environment (please complete the following information):**
 - OS: Windows 10
 - Browser and version: Firefox 115.4

**Additional context**

This seems to have worked in a previous release, although I haven't done extensive testing to figure out where.

**Comment by joshuarrrr** [comment]
@kishor82 Thanks for the quick fix! I'll take a look at the PR in the next couple days.

**Comment by kishor82** [comment]
sure @joshuarrrr
