### ISSUE TITLE
[Features] Configurable rows per page in the discover view

### ISSUE THREAD

**Issue by albgus** [opensearch-project/OpenSearch-Dashboards#5569]
**Is your feature request related to a problem? Please describe.**

The new discover view splits search results into pages instead of automatically loading new pages as you scroll downwards. Looking through large search results were much easier when not having to navigate through pages and having 100 results per page isn't very much when dealing with large log files. It also restricts quick searching back with Ctrl+F in the browser if things are no longer on the same page.

**Describe the solution you'd like**

I'd like to be able to be able to either switch back to the old behaviour, or at least be able to configure the number of results per page as an advanced setting to increase the results shown at the same time.

**Additional context**

Inspecting the Network page of the browser DevTools it seems that all results are fetched in one request, so I'm not even sure what purpose the pages serve if everything is returned at the same time anyway?

**Comment by joshuarrrr** [comment]
I think making the page size configurable is a good solution. @ananzh and @ashwin-pc what do you think?

**Comment by kishor82** [comment]
Related to #5601

**Comment by ashwin-pc** [comment]
@albgus Does the solution proposed in #5610 address your problem?
