### ISSUE TITLE
[BUG] Copying data from columns in discover includes extra data

### ISSUE THREAD

**Issue by albgus** [opensearch-project/OpenSearch-Dashboards#5570]
**Describe the bug**

When trying to copy the value of a column in the discover view the string "Row" is appended to the copied value.

**To Reproduce**
1. Go to https://playground.opensearch.org/app/data-explorer
2. Select an index then expand the details view of an item and toggle the column in the results table.
4. Select the content of a column and copy it and paste it somewhere. For instance when copying the value `EUR` is pasted as `EURRow `

**Expected behavior**
Only the actual value of the column should be selected/copied. 

**OpenSearch Version**
2.11.0

**Dashboards Version**
2.11.0

**Host/Environment (please complete the following information):**
 - OS: macOS 14.1
 - Browser and version: Chrome 119.0.6045.199

**Comment by joshuarrrr** [comment]
I can partially confirm this bug. It is actually possible to select just the cell text, but the additional row and column info will be included when selecting an entire row or column. We probably want to take a look at the OUI component to improve its behavior - the row/column info is added for screen readers.

@kgcreative Can we have some UX assistance on how to better solve for copy/pasting from tables?

**Comment by kgcreative** [comment]
Thanks @joshuarrrr! My sense is we should copy/paste as either CSV or as a table -- let me think about this a bit more and see how different experiences copy/paste data back and forth. My sense is we'd want to make it easy to copy/paste as markdown/csv/html table

**Comment by abbyhu2000** [comment]
For the two problems that are addressed:

1. When copying and pasting the table, the extra text "Row # Column #" will be eliminated by this PR: https://github.com/opensearch-project/oui/pull/1198

2. However, for copying and pasting the data as a table format or CSV format, it requires OUI component `<OuiDataGrid>` to be entirely re-written and re-style as `<table>`; currently each table cells are `<div>` thus when copying and pasting, it does not format like a table, but format as a list of values.

I have created an issue in OUI for rewriting `<OuiDataGrid>` as table: https://github.com/opensearch-project/oui/issues/1199
