### ISSUE TITLE
Discover Page : Pagination vs scroll ( older way)

### ISSUE THREAD

**Issue by gupta-mayank** [opensearch-project/OpenSearch-Dashboards#5601]
**Problem Statement:**
The older version of Open search before new discover ( with Angular ) used to have scroll of 500 documents in the same page. Some of our users use that feature extensively for triaging issues. With pagination, the context is lost .

**Solution proposed**
1. Make this configuration based if scroll vs pagination.
2. Increase the pagination size to 200 or 300 than limiting to 100.

I understand it might be related to new UI working across.

**Alternatives**
No alternatives are considered for now. We have asked users to refine search better to have 100 records.

**Comment by kishor82** [comment]
Based on the configurable `Number of rows` (discover:sampleSize) setting, I believe pagination options should be set accordingly.
