### ISSUE TITLE
[BUG] Filtering index pattern in Discover page does not work

### ISSUE THREAD

**Issue by mz118** [opensearch-project/OpenSearch-Dashboards#5604]
**Describe the bug**

Searching/filtering index patterns in Discovery mode doesn't work

**To Reproduce**
1. Go to OpenSearch Dashboards -> Discover
2. Click on fild where you can choose index pattern
3. Start typing index pattern name and filter doesn't work, all index patterns are still visible and you have to scroll down to find and choose the one you want to

**Expected behavior**
After typing index pattern name on the Discover page, there should be working filtering

**OpenSearch Version**
2.11.0 and 2.11.1

**Dashboards Version**
2.11.0 and 2.11.1

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by kishor82** [comment]
@mz118  can you add screenshots?

**Comment by mz118** [comment]
See my screenshots below:

Searching index pattern in OpenSearch Dashboard v2.11.1 (I had to cover full index-patterns names):
![indexpatternsearch-2111](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/31475160/e2dbf702-189d-4ca0-a9e9-2e0e423db52b)

vs. 2.9.0:
![indexpatternsearch-290](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/31475160/59211969-852c-4b73-887a-e7d67213d981)

**Comment by ashwin-pc** [comment]
@mz118 I dont see this error on main but i do see this on playgrounds. I havent checked this on the 2.x line. The screen recording below is from main.

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/20453492/daa94776-1053-49b0-bfa7-ee67c2c2347e

**Comment by kishor82** [comment]
It's working as expected in main, issue seems to be in 2.11.*

**Comment by ashwin-pc** [comment]
They are on the same component but different issues. This on i believe is already fixed. @ananzh can you link the PR that fixes this here and close the issue if its been resolved?

**Comment by abbyhu2000** [comment]
Yea this is fixed in this PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5484 and it has been backported to 2.11. @ashwin-pc

**Comment by ashwin-pc** [comment]
@mz118 Yeah unfortunately this fix was merged after the 2.11.1 release was cut. So this will either come in 2.12 or 2.11.2 (If 2.11.2 is released, which at this stage is unlikely)
