### ISSUE TITLE
[BUG] Index patterns no longer alphabetized in the data source selector and filter causes CSP error

### ISSUE THREAD

**Issue by adamdepollo** [opensearch-project/OpenSearch-Dashboards#5609]
**Describe the bug**

After upgrading to OpenSearch 2.11, the index pattern selection dropdown on the Discover dashboard no longer alphabetizes index patterns. This makes finding index patterns quite difficult. 

Additionally, typing a pattern into the dropdown field does not seem to work correctly as a search function. I'm not sure what the expected functionality is here, but typing in a specific index pattern, for example, simplly changes the font display of that index pattern in the dropdown menu to bold. It does not actually search for that index or auto-select it from the list of dropdown options.

**To Reproduce**
1. Go to Discover
2. Open the index pattern dropdown
4. See patterns are not alphabetized

**Expected behavior**
Index patterns should be sorted alphabetically. Entering index pattern name in the dropdown text field should either auto-select the index pattern or filter the options in the dropdown to only those matching the query.

**OpenSearch Version**
2.11

**Dashboards Version**
2.11

**Plugins**

AWS managed OpenSearch. Using whatever the default plugins are.

**Screenshots**
<img width="461" alt="Screenshot 2023-12-13 at 5 02 58 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/55102313/a6f115a1-aec7-40d1-bd1e-66815037562b">

**Host/Environment (please complete the following information):**
 - OS: Windows
 -  Chrome Version 119.0.6045.200 (Official Build) (64-bit) and FireFox 120.0.1 64 bit

**Additional context**

**Comment by ashwin-pc** [comment]
@mengweieric Can you take a look at this issue? cc: @anirudha

**Comment by mengweieric** [comment]
@adamdepollo thanks for reporting this.

I checked out both 2.9 and 2.10, and the index patterns there are not sorted alphabetically started from 2.10 where new component was introduced: [combo box](https://oui.opensearch.org/1.3/#/forms/combo-box) where it does not sort options alphabetically by default but rather just render the list as it is.

2.9
<img width="463" alt="Screenshot 2023-12-15 at 11 18 32 AM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/80358241/36825396-1a4b-4ae7-88c4-0aa6479a5033">


Started from 2.10
<img width="446" alt="Screenshot 2023-12-15 at 10 23 12 AM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/80358241/279ea7cd-0ff2-46ed-9e5f-3d958b7139fd">

We will introduce the sorting functionality to current index selector as soon as possible. Will create an issue and link to this issue.

With respect to filtering, I did a test on 2.11 and was able to see filtering working as expected.

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/80358241/ef0f181c-57b5-463e-8fee-95c93296a84c

 This is the [PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5554) addressing this on 2.11 could you check if this commit is included correctly? thanks!

**Comment by AMoo-Miki** [comment]
@mengweieric I noticed that #5719 added a changelog referencing this issue:
1. Please raise a new PR to update the changelog to point to the original PR
2. If this issue is related to the PR in question, please link them and close this.

**Comment by AMoo-Miki** [comment]
@ashwin-pc the PR addressing this was merged in to 2.12. Is there anything left that warrants labeling this for 2.13?

**Comment by ananzh** [comment]
@adamdepollo Have confirmed that this issue is resolved. Pls feel free to reopen it if you see other issues after the fix.
