### ISSUE TITLE
[BUG][Data explorer] Index patterns are not sorted in alphabetically order in index pattern selector

### ISSUE THREAD

**Issue by mengweieric** [opensearch-project/OpenSearch-Dashboards#5622]
**Describe the bug**

Started from 2.10, index patterns are not ordered alphabetically in index selector of discover.

Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5609

**Expected behavior**
Index patterns should be ordered alphabetically in index selector of discover

**Dashboards Version**
2.10, 2.11

**Comment by ashwin-pc** [comment]
Closing as a duplicate of #5609.
