### ISSUE TITLE
[BUG] Copy Link button in Share does not actually copy the link on Safari

### ISSUE THREAD

**Issue by petewerner** [opensearch-project/OpenSearch-Dashboards#5629]
**Describe the bug**

The "Copy Link" button in "Share" does not actually copy the link on Safari

**To Reproduce**

1. Using Safari, go to Discover
2. Click Share in the top menu on the right
3. Click Copy Link
4. Try and paste the link and it the copy & paste buffer will be empty or still have what was previously there.

**Expected behavior**

It should copy the link

**OpenSearch Version**

2.11 via AWS

**Dashboards Version**

2.11 

**Plugins**

Nothing special/whatever comes with the AWS Opensearch Managed Service

**Screenshots**

n/a

**Host/Environment (please complete the following information):**
 - OS: MacOS Sonoma 14.1.1
 - Safari Version 17.1 (19616.2.9.11.7)

**Additional context**

Copy link works fine in Chrome
Selecting different options in the share popup (short url etc) still has the issue.

**Comment by manasvinibs** [comment]
Hi @petewerner 
I tried re-producing the issue in Safari v17.1 with Dashboards version 2.11. But I'm able to copy the link and paste it without any issues. 

<img width="1792" alt="2023-12-19" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105884062/ba4102e5-aaac-4bd0-a749-aea4b8210a27">

Can you screen record and share your experience? Also can you try clearing your session cookies and see if it helps.

**Comment by petewerner** [comment]
hey thanks for taking a look. 

I tried on a new safari profile and cleared out the cookies, recorded the video linked below.

I noticed it is playing an alert sound when I click copy. 

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/1332487/a3fd2d69-c79b-4bd2-96e8-48b44f8a34be

I also have a copy of the developer console, there are a few issues, but they all happen before i click copy. Nothing is printed to console when i access the menu items or click copy link

```
[Error] Fetch API cannot load https://xx/_dashboards/internal/search/opensearch due to access control checks.
	(anonymous function) (core.entry.js:15:180679)
	fetchResponse (core.entry.js:15:181534)
	(anonymous function) (core.entry.js:15:179136)
[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (discover, line 366)
[Log] ^ A single error about an inline script not firing due to content security policy is expected! (bootstrap.js, line 43)
[Log] Detected an unhandled Promise rejection. (core.entry.js, line 15)
TypeError: undefined is not an object (evaluating 'location.href.split("#")[1].split')
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'location.href.split("#")[1].split')
	(anonymous function) (reportsDashboards.plugin.js:24:109719)
	checkURLParams (reportsDashboards.plugin.js:24:110343)
	(anonymous function) (reportsDashboards.plugin.js:24:109615)
	u (osd-ui-shared-deps.js:411:26174)
	(anonymous function) (osd-ui-shared-deps.js:411:26472)
```

**Comment by ananzh** [comment]
No problem in Safari in 2.15. Close it for us. Let us know if there is any other issues.
