### ISSUE TITLE
Standardize the directory name to include version number

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/OpenSearch-Dashboards#564]
**Is your feature request related to a problem? Please describe.**
No

Unpacking the Opensearch TAR creates the directories with the version number but Opensearch-dashboards doesn’t. We would like to standardize the folder names hence we need to add the version number to the directory for the OpenSearch-Dashboards directory as well.

**Describe the solution you'd like**
Add the version number to the directory for the OpenSearch-Dashboards directory when unpacking the TAR.

Version number is added to the folder name

**Describe alternatives you've considered**
Manually renaming the folder name

**Additional context**

**Comment by kavilla** [comment]
When the tar files are built they include the version number for me. Do you have more context for this?

Like do you have an example of the the files and what you expect the files to look like?

**Comment by tmarkley** [comment]
@bbarani @peterzhuamazon can you answer the questions above?

**Comment by tmarkley** [comment]
@bbarani @peterzhuamazon checking in on this again.

**Comment by peterzhuamazon** [comment]
Not the tar file, after you untar the tarfile, it will show only opensearch-dashboards folder, where opensearch will show opensearch-1.0.0 folder.

**Comment by tmarkley** [comment]
@peterzhuamazon can you confirm the command you're using to unpack?

**Comment by peterzhuamazon** [comment]
Seems like this is fixed for now thanks:
```
opensearch-dashboards-1.1.0-linux-arm64/
opensearch-dashboards-min-1.1.0-linux-arm64.tar.gz
```
