### ISSUE TITLE
[BUG] Saved Search horizontal resizing not working

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/OpenSearch-Dashboards#5653]
**Describe the bug**

In a dashboard that has a saved search at the bottom, add another visualization, it stacks with the saved search. Additionally saved search doesn't resize

**To Reproduce**
1. Go to home page, add ecommerce sample data
2. Click on view data
3. Click on edit, add, add `[eCommerce] Sales by Category`
4. See it stacked on top of the table
5. Resize the saved search, it doesn't resize

**Expected behavior**
new visualization should be added at the bottom, and resize saved search should work like other visualizations

**OpenSearch Version**
2.11.0

**Dashboards Version**
2.11.0

**Plugins**

default distribution

**Screenshots**

<img width="755" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/28062824/ea740693-338d-4ac0-b85c-6b252aa366a4">
<img width="1500" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/28062824/135ae453-fca9-4839-898e-115e055a2607">

**Host/Environment (please complete the following information):**
 - OS: [e.g. iOS] linux x64
 - Browser and version [e.g. 22] 

**Additional context**

I tried in 2.11.1, seems the visualization stack issue is fixed. Which PR fixed it? is it https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5441? Also I still can't resize in 2.11.1

**Comment by ashwin-pc** [comment]
@joshuali925 Thanks for opening this issue. Yes it looks like #5441 did fix the overlap issue but not completely. What seems to be happening is that the underlying datagrid component is overflowing the parent embeddable (Resizeable component). You can see that the resize handle is still present and vertical resizing still works although horizontal resizing is still broken. Given that the stacking issue has been fixed, ill repurpose this issue to track the resizing issue instead. Let me know if see any reason not to do that :)

**Comment by ananzh** [comment]
Resolve this as it is done.
