### ISSUE TITLE
[BUG] Changing from a search with few results to a search with more results keeps the number of rows from the previous search

### ISSUE THREAD

**Issue by acb** [opensearch-project/OpenSearch-Dashboards#5659]
When you make subsequent searches it seems that the results table remembers the most restrictive number of rows from your searches and doesn't update. For example, I made a search that returned 6 results, then loosened my search query to one that returned 81 results. However, the table that shows the results was still limited to 6 rows. The correct number of results shows up in the bar graph at the top of the results, and refreshing the page loads the full results correctly.

**To Reproduce**
1. Make a search with a small number of results
2. Change search to one with more results than previous
3. Results table only shows the number of rows from search 1, truncating the results from search 2

**Expected behavior**
The results table should show the full results from all searches without refreshing the page.

**OpenSearch Version**
AWS hosted version, OpenSearch_2_11_R20231113-P2

**Dashboards Version**
2.11.0

**Plugins**

None.

**Screenshots**
**Search with 6 results**
![6-hits](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/4690898/6953e47d-4f7a-4fd0-9a43-f92b1673d1a9)
**Search with 81 results, only 6 show in the table**
![81-hits](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/4690898/55ba1d58-b587-4a4b-bddd-0b98cd1d62d7)

**Host/Environment (please complete the following information):**
Server host is AWS's hosted OpenSearch
Browser info: 
 - OS: Ubuntu 22.04.1 LTS
 - Browser: Vivaldi 6.5.3206.39 (Chromium browser, Chromium version 120.0.6099.121)

**Comment by ananzh** [comment]
Hi @acb we fixed this table size adjust issue in 2.12 and main. For example, if I change query from a name to `EUR`, you could see table is adjusted. You could check main or our upcoming 2.12 release:


https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/5cf1ba46-54e1-4268-a5df-474f0f178743

Do you think we could close this issue?
