### ISSUE TITLE
[BUG] Unable to load indexed patterns

### ISSUE THREAD

**Issue by sriv1211** [opensearch-project/OpenSearch-Dashboards#5664]
**Describe the bug**

**To Reproduce**
1. Go to `Index Patterns`
2. Click on `Create index pattern`
3. Reload the page

```
reportsDashboards.plugin.js:24 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
    at checkURLParams (reportsDashboards.plugin.js:24:109718)
    at HTMLDocument.<anonymous> (reportsDashboards.plugin.js:24:109600)
    at u (osd-ui-shared-deps.js:411:26168)
    at l (osd-ui-shared-deps.js:411:26470)
```

**Expected behavior**

**OpenSearch Version**
2.11.1 arm64

**Dashboards Version**
2.11.1 arm64

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/19315039/cd2eb166-fb84-4ce9-9f40-eb9449bf0eed

**Host/Environment (please complete the following information):**
 - OS: macOS Sonoma
 - Browser and version FF 121.0 and Chrome (`Version 120.0.6099.199 (Official Build) (arm64)`)

**Additional context**

**Comment by kavilla** [comment]
@AMoo-Miki checking with the reporting plugin is an existing issue or not.

**Comment by AMoo-Miki** [comment]
This is tied to https://github.com/opensearch-project/dashboards-reporting/issues/281.

**Comment by ananzh** [comment]
@AMoo-Miki what is the status of this issue? as https://github.com/opensearch-project/dashboards-reporting/issues/281 is closed

**Comment by ananzh** [comment]
Resolved as @AMoo-Miki verified the update.
