### ISSUE TITLE
[Improvement] noreferrer on doc links

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#567]
**Is your feature request related to a problem? Please describe.**
Stemming from this PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/565. Links inconsistently have `noreferrer` on the reference.

'Adding rel="noopener noreferrer" to links protects your site's users against having the site you've linked to potentially hijacking the browser'

**Describe the solution you'd like**
Apply noreferrer to most, if not all, links.

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by tmarkley** [comment]
Potential option: add a linting rule?
