### ISSUE TITLE
[BUG] Size is not adaptive after table condition filtering

### ISSUE THREAD

**Issue by luArye** [opensearch-project/OpenSearch-Dashboards#5678]
Version: v 2.11.1
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/143676625/de27bede-54f6-42d1-9978-b3121ae14802)

Bug description:
When the filtering condition is added, the table height becomes smaller, and the data becomes larger after the filtering condition is cleared. However, the table height does not adjust adaptively
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/143676625/f75b3098-526c-4f2c-9382-6b660ba25ea7)

**Comment by ananzh** [comment]
Hi @luArye we fixed this issue in [#5789](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5789). You could verify in 2.12 or main. Check this recording to see table size is adjusted after adding a filter.


https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/8207d9b9-8363-419b-8b28-80fdf5f80652


Do you think we could close the issue?

**Comment by abbyhu2000** [comment]
Tested against the 2.12 release and this issue has been resolved. 

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/12a1879a-9232-4b4a-a5fc-cd69ae2d77e2
