### ISSUE TITLE
Gg

### ISSUE THREAD

**Issue by Ebaome** [opensearch-project/OpenSearch-Dashboards#5687]
https://github.com/android/platform-samples/blob/main/samples%2Fuser-interface%2Fappwidgets%2Fsrc%2Fmain%2Fjava%2Fcom%2Fexample%2Fplatform%2Fui%2Fappwidgets%2FAppWidgets.kt

**Comment by kavilla** [comment]
Hello @Ebaome,

Do you mind populating this issue with more information and then re-open?

Thank you!
