### ISSUE TITLE
[Enhancement] Redesign global header

### ISSUE THREAD

**Issue by kgcreative** [opensearch-project/OpenSearch-Dashboards#569]
**Is your feature request related to a problem? Please describe.**
We've had some requests to remove the top bar, as well as making it easier to change the top logo. This is a meta issue that covers redesigning the global header.

See: https://discuss.opendistrocommunity.dev/t/change-top-left-elastic-logo-on-opendistro-kibana/5436

**Describe the solution you'd like**

The initial proposal is to collapse the current stacked header into a single one.

![Header](https://user-images.githubusercontent.com/3443142/123994669-73ff0200-d982-11eb-8f9c-3d18e9a1dc7a.png)

The UX team is exploring the responsive behavior in the top bar, and will add additional guidance here for how to handle the user menu, tenants, and cases where there are additional action menus (Such as the `Full screen | Share | Clone | Reporting | Edit` actions in the Dashboard plugin.)

Additionally, we'd like to explore uploading an SVG in advanced settings in order to make it easy to change the logo in the header.

**Additional context**
This issue was originally raised from the OpenSearch forum

Related forum posts:
* https://discuss.opendistrocommunity.dev/t/change-top-left-elastic-logo-on-opendistro-kibana/5436
* https://discuss.opendistrocommunity.dev/t/opensearch-dashboards-logo-feels-wrong/6510

**Comment by galangel** [comment]
Good idea,
IMO it could event be just the side bar,
User/Account info could also be there at the top, similar to other apps.

the only thing I'm not sure about is merging the contextual buttons and breadcrumbs, it would be too crowded there.

**Comment by kgcreative** [comment]
> the only thing I'm not sure about is merging the contextual buttons and breadcrumbs, it would be too crowded there.

This is a really good point, Gal. I think the interesting thing here is that there seems to be a lack of clarity regarding how the whole application chrome is architected. 

The top-most bar seems to be mostly global actions, and it's there mostly as an anchor for the side menu. The side menu went from being a partially revealed side-navigation to being completely removed when closed, and the second level bar now appears to be mostly for contextual information (breadcrumbs, contextual buttons). There seems to be some buggy behavior today when looking at that in mobile viewports as well, where some buttons collapse to a drop-down menu, and some buttons dissappear all together. (I tested it against the "dashboard" panel).

Perhaps there's an opportunity here to rethink the overall chrome, and be intentional about what information belongs where.

**Comment by robcowart** [comment]
@kgcreative I like the simple bar. This is closer to the earlier Kibana 7 styling before the screen real estate wasting top bar with useless search box was added (sorry... I am a bit opinionated on this). I would even go further and omit "Home" and simply let that be the action when clicking the logo.

**Comment by jgough** [comment]
I made [a comment in 2019](https://github.com/elastic/kibana/issues/40719) about how the Kibana header was getting more and more progressively complex with each successive release.  Elastic does not seem interested in changing things though.  Hoping things can be simplified here in Opensearch Dashboards.

**Comment by kgcreative** [comment]
Please see #1583 for the proposed 2.0 nav changes.
