### ISSUE TITLE
[BUG] Multiple Datasource should support timeline, vega and TSVB

### ISSUE THREAD

**Issue by Flyingliuhub** [opensearch-project/OpenSearch-Dashboards#5690]
**Describe the bug**
The multiple datasource didn't support timeline, vega and TSVB, we need to make sure that multiple datasource support timeline, vega and TSVB for multiple datasource 

**To Reproduce**
1. Go to 'Dashboard management'
2. Click on 'dataSources' and 'create datasource connection'
3. fill out the required information 
4. Choose VIS. 
5. Multiple datasource didn't support timeline, vega and TSVB.

**Expected behavior**
Multiple datasource should support timeline, vega and TSVB.

**OpenSearch Version**
2.11

**Dashboards Version**
2.11

**Plugins**

N/A

**Screenshots**

N/A

**Host/Environment (please complete the following information):**
 - OS: MacOS
 - Browser and version Firefox 115.5.0esr

**Additional context**

N/A

**Comment by seraphjiang** [comment]
close as @huyaboo is actively working on it
