### ISSUE TITLE
[BUG] Multiple datasource unable retrive datasource in the first time load dev tool

### ISSUE THREAD

**Issue by Flyingliuhub** [opensearch-project/OpenSearch-Dashboards#5698]
**Describe the bug**

Multiple datasource unable retrieve datasource in the first time load of dev tool, the first time open dev tool throw the error with multiple datasource enabled.

**To Reproduce**
1. Go to 'DataSource'
2. Click on 'Create Data source connection'
3. Fill out the required information and save
4. Click 'Dev Tools'
5. The 'Dev Tools' page throw error in the right bottom corner, "Unable to fetch existing data sources"

**Expected behavior**
It should successfully load 'Dev Tools' page.

**OpenSearch Version**
2.11

**Dashboards Version**
2.11

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

<img width="990" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/33105471/4d4f710f-8554-475d-9665-a5c74d9cc03c">

**Host/Environment (please complete the following information):**
 - OS: MacOS
 - Browser and version firefox 115.5.0esr

**Additional context**

The 'Dev Tools' should render correctly when first time after create datasource

**Comment by Flyingliuhub** [comment]
@xinruiba will work this issue

**Comment by xinruiba** [comment]
Sure, will take a look @Flyingliuhub

**Comment by xinruiba** [comment]
#5827

**Comment by xinruiba** [comment]
With #5827, this issue should not shows up again.
Closing issue.
