### ISSUE TITLE
[BUG] Multiple datasource UI fixes

### ISSUE THREAD

**Issue by Flyingliuhub** [opensearch-project/OpenSearch-Dashboards#5700]
**Describe the bug**

The current 'dev tools' is using text "Select a Data Source" which should be "Select a data source", and when user is using the feature flag to disable other authentication, the other authentication type should be disabled in the drop down list.

**To Reproduce**
1. Go to 'Dev Tools'
2. Navigate to right top corner, it is showing up "Select a Data Source" 

**Expected behavior**
It should be "Select a data source" 

**OpenSearch Version**
2.11

**Dashboards Version**
2.11

**Plugins**

N/A

**Screenshots**

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/33105471/c0f3c5c2-f8b6-428d-b480-98087e845738)

**Host/Environment (please complete the following information):**
 - OS: MacOS
 - Browser and version: firefox 115.5.0esr

**Additional context**

N/A

**Comment by bandinib-amzn** [comment]
It got fixed in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5475
