### ISSUE TITLE
[Feature] Support Multiple Data Source when Import saved objects from uploading files

### ISSUE THREAD

**Issue by yujin-emma** [opensearch-project/OpenSearch-Dashboards#5712]
**Is your feature request related to a problem? Please describe.**

When multiple data source enabled, user can add [sample data](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4412/files) and use the [dev tool](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3806) with one specified data source. Import saved objects accepts uploaded files, but the API does not know the data source. These objects cannot display since the it does not know where to fetch the data.

![Screenshot 2024-01-18 at 12 48 19](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/112784385/3538a0ee-f225-438d-93b8-dc60c806a56c)

We want to provide user the ability to import saved objects after selecting one data source. When user import saved object from  cluster where not enabled multiple data source feature, the imported saved objects will attach the dataSourceId with the objectId; while user import saved objects from some cluster with multiple data source feature enabled, then the objectId would already contains data source info, for this case, we want to replace the dataSourceId. The id schema are exactly same as when user add sample data and dev tools with multiple data source enabled. 

![Screenshot 2024-01-18 at 12 26 38](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/112784385/ed00a3d8-70ae-4832-b6b6-9ef21259538b)
![Screenshot 2024-01-18 at 12 27 48](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/112784385/2827a7cd-4541-4ecd-be89-a72e4e828680)

**Challenges**

There are two modes to import saved objects, one is create new copy, the other is check conflict and override. We need to support both modes and cannot break the existing behavior. 
Current Import API support create new copy by using the exact objectId to construct the importIdMap, support check conflict and override by checking if there is anything error and only push overrides to construct final import saved object request. 
For these two modes, we need to resolve carefully, below are the detailed approach to support multiple data source when import saved objects.

**Describe the solution you'd like**

***Mode - create new copy***

When choosing create new copy, after user select one data source, attach the dataSourceId to the saved objects. The `_`  is between dataSourceId and objectId. 
```
if (dataSourceId) {
      return acc.set(`${object.type}:${object.id}`, {
        id: `${dataSourceId}_${uuidv4()}`,
        omitOriginId: true,
      });
    }
    return acc.set(`${object.type}:${object.id}`, { id: uuidv4(), omitOriginId: true });

```
***Mode - check conflict and override***

Under this mode, if there is no conflict, import API would not add any object to importIdMap, while when multiple data source enabled and import saved objects, we need to first check if there is dataSourceId existing in the current objectId, we need to:

      1. attach if there is no dataSourceId in the objectId

``` 
// Sample code
if (noConflictError && dataSourceId) {
        importIdMap.set(`${type}:${id}`, { id: `${dataSourceId}_${object.id}`,id});
      } else {
        importIdMap.set(`${type}:${id}`, { id: uuidv4(),id });
      }
```
      2. replace the dataSourceId info when user specify one data source

```
// Sample code
if (dataSourceIdExited){
        const subId = id.split("_")[1];
        const newId = `${dataSourceId}_${subId}`;
        const newTypeArray = type.split("_");
        const newType = newTypeArray[newTypeArray.length - 1];
        importIdMap.set(`${newType}:${subId}`, { id: `${newId}`, omitOriginId });
 }

 // if conflict exist, replace the dataSourceId in the objectId and reconstruct the pendingOverwrites item
 const idArrayWithoutUnderscore = id.split("_");
 const newId = idArrayWithoutUnderscore.length >= 2? `${dataSourceId}_${idArrayWithoutUnderscore[idArrayWithoutUnderscore.length - 1]}` : id;
 const newTypeNoUnderScore = type.split("_");
 const newType = newTypeNoUnderScore.length >= 1 ? newTypeNoUnderScore[newTypeNoUnderScore.length - 1] : type; 
// extract the original type from the imported saved object
 pendingOverwrites.add(`${newType}:${newId}`); 

```

**Additional context**

```
"saved_objects": [
        {
            "id": "3ecd6420-ae62-11ee-a922-ffcd95c5e76a_37cc8650-b882-11e8-a6d9-e546fe2bba5f",
            "type": "visualization",
            "namespaces": [
                "default"
            ],
            "updated_at": "2024-01-09T01:51:16.078Z",
            "version": 14,
            "attributes": {
                "description": "",
                "uiStateJSON": "{}",
                "title": "[eCommerce] Sales by Category_emma-1-3",
                "version": 1,
                "kibanaSavedObjectMeta": {
                    "searchSourceJSON": "{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[],\"indexRefName\":\"searchSourceJSON.index\"}"
                },
            "references": [
                {
                    "name": "searchSourceJSON.index",
                    "type": "index-pattern",
                    "id": "3ecd6420-ae62-11ee-a922-ffcd95c5e76a_ff959d40-b880-11e8-a6d9-e546fe2bba5f"
                }
            ]
        },
```

**Comment by BionIT** [comment]
There are a few edges cases I can think of and make sure we handle them gracefully: 
1. What is the behavior if datasource id already present in the prefix of the objects, and it either match or do not match the selected datasource
2. Does the change affect the import API/UI if data source plugin is not enabled
3. If user export the objects from the dashboard that enabled data source plugin, all objects contain the datasource id in the prefix, but they are all different from each other, should user select or unselect data source, etc

**Comment by BionIT** [comment]
@kgcreative 
Thanks for going over the UX and walking through the scenario for import saved objects UI! I tried the flow again, and since the uploaded file is only loaded when the import button is clicked, thus there can be 2 options:
1. have the source of data picker before the import button is clicked, while local cluster is selected by default, when click on Remote data source, then there is a option to choose from the datasources. 
2. after import button is clicked, then the backend will check for the content of file and if any of them doesn't have datasource in the id, then show up error message and show the Source of data section.

Both are achievable, option 2 adds more complexity and only allow selecting data source after file is read, and by looking at index pattern management page when multiple data source is enabled, adding a new index pattern requires configure the data source first, thus wanted to hear your suggestion! The `Source of data` section only shows up when multiple data source plugin is enabled

The following are screenshots of the new section to pick data source, and it was made to match the style of the import options section, and want to hear your thoughts as well
- Local cluster is selected by default
![Screenshot 2024-01-26 at 10 50 15 AM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/cf9d0571-4c24-491d-8809-f2a8c8667f25)
- If `Remote data source` is selected, user can select connected data source
![Screenshot 2024-01-26 at 2 25 46 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/e3fe80f7-f87b-402b-8f94-4ee2e1ff188b)

**Comment by BionIT** [comment]
Hi @kgcreative, if no concern, we would go with this layout with option 1.

**Comment by BionIT** [comment]
This is the older version of the layout and benefit is we will reuse the existing picker component
![Screenshot 2024-01-30 at 13 22 55](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/8e4cfa0a-11f1-4b91-8b3a-2ed70c4972df)

**Comment by BionIT** [comment]
As discussed, this is the layout we will go with when multiple data source is enabled
![Screenshot 2024-01-30 at 10 41 26 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/605edd3b-43e7-4bb4-bbec-98fbcc9424b2)

**Comment by kgcreative** [comment]
LGTM -- if we can make the flyout a couple pixels wider so the last "IDs" text isn't all lonely in a second line, it would be ideal, but don't spend too much time on it.

**Comment by kgcreative** [comment]
LGTM, thank you!

Cc: @dagneyb
