### ISSUE TITLE
[MD] Data source picker should have same behavior in devtool, tutorial, etc where it is used

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/OpenSearch-Dashboards#5717]
**Is your feature request related to a problem? Please describe.**

I feel confused when seeing different behavior for the data source picker based on where it is located

**Describe the solution you'd like**

The datasource picker should be one component to ensure the behavior is the same. Then, if we need to change the behavior for the picker, we don't need to go through entire code base to find the duplicated code in order to make change. The component should be reusable by other plugins
To unify the behavior, the default option for the picker when first opening the page with the picker should be `Local cluster`. After removing the option, it should display `Select a data source`. Change the `DataSource` to `Data source`

**Describe alternatives you've considered**

Stay where we are and just change every places every time that a small text adjustment is needed for the picker. 

**Additional context**
When data source plugin is enabled, if we go to dev tool page or add sample data page, the behavior of the data source picker is different: 
- dev tools shows `Select a data source` and the prepend is `Data source`
![Screenshot 2024-01-19 at 2 41 45 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/8d764a79-8c7f-45bd-a0af-8fa8bda057c6)

- add sample data tutorial shows a default value and the prepend is `DataSource`
![Screenshot 2024-01-19 at 2 41 55 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/e131a3e8-17bd-4a89-a5fa-f4b10087e931)
after removing the default value it shows `Select a Data Source`
![Screenshot 2024-01-19 at 2 42 02 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/13c39fea-2349-4117-b41e-b25808e13c9a)

**Comment by BionIT** [comment]
Happy to work on it

**Comment by bandinib-amzn** [comment]
> After removing the option, it should display Select a data source. Change the Data source or DataSource to Destination

Does that mean all occurrences of `Select a data source` will change to `Select a destination`?

**Comment by bandinib-amzn** [comment]
Adding here one feedback I received from UX team while reviewing these pages:

Make first created data source as default data source and set default data source as default selected option on dev tool and sample data screens instead of `Select a data source`.

**Comment by BionIT** [comment]
> > After removing the option, it should display Select a data source. Change the Data source or DataSource to Destination
> 
> Does that mean all occurrences of `Select a data source` will change to `Select a destination`?

Yeah, you are right, it should be `Select a destination`

> Make first created data source as default data source and set default data source as default selected option on dev tool and sample data screens instead of Select a data source.

At of today, in my understanding, local cluster has to be present unless https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5696 is introduced

> On Dev Tool, Sample Data screens, use the new data source picker component. [Feature] Datasource selector of multiple datasources  #5167. We need to figure out if we can filter out index patterns and only show data sources.

I can consult UX about this component, my feeling is it is too busy to show a label inside the picker where we already know we are looking for datasource instead of any other objects.

> Ideally when no data source present on dev tool, sample data (and there is no local cluster), it should instruct user to create data source first. We need similar experience when we visit dashboards, visualization, discover and no index pattern has been created.
This behavior doesn't exist yet until local cluster can be removed, and agree that the behavior should be the same, and we can decide later if the behavior should be implemented in the picker
