### ISSUE TITLE
Search history is truncated 

### ISSUE THREAD

**Issue by ptandon91** [opensearch-project/OpenSearch-Dashboards#5729]
**We have a customer who reported that search history is getting truncated when viewing through the dashboard. It should have full query displayed but doesn't show up in the history**

**Expected behavior**
Please find the screenshot for reference. It should look like this -
![image-5](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/74795590/1e086a71-b61d-4dbc-bec5-8c3f0d473676)

**OpenSearch Version**
v2.3.0

**Dashboards Version**
v2.3.0

**Additional context**

**Comment by kavilla** [comment]
@ananzh was this addressed in a later version?

**Comment by AMoo-Miki** [comment]
@ptandon91 thanks for reporting the issue. This was fixed in 2.4.0 with https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2607.
