### ISSUE TITLE
[BUG] TSVB table showing wrong data

### ISSUE THREAD

**Issue by rafaelrangellima** [opensearch-project/OpenSearch-Dashboards#5732]
I have a TSVB table that monitors packet loss. However, even with packet loss at 100% (confirmed in the data entry in the index), at the time of the update it shows 0%.
Could it be a bug?

**Expected behavior**
Since the device is off the network, the ping test should always show 100% packet loss, but it shows 0%, and then updates to 100% intermittently.

**OpenSearch Version**
2.11

**Dashboards Version**
2.11

**Plugins**
TSVB

Please list all plugins currently enabled.

**Screenshots**

![2024-01-24 12_03_15-OpenSearch Dashboards](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/36416271/dfa992a8-ce00-4197-a421-b0abc9eab3a7)
![2024-01-24 12_02_02-OpenSearch Dashboards](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/36416271/1d0ee1a1-b2e4-46ee-a007-f6269d8bb681)

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]
 - Chrome last version

**Additional context**

**Comment by AMoo-Miki** [comment]
@rafaelrangellima I am afraid there isn't much information to help you here. Can you share the definition (metrics as well as options) for the offending column and the complete panel options? It would also help to know the mapping of the field you are working with.

**Comment by rafaelrangellima** [comment]
@AMoo-Miki thanks for the feedback.
I managed to solve this problem by changing my script to multi thread.
