### ISSUE TITLE
How to Move AWS open search Indexes to S3 Bucket

### ISSUE THREAD

**Issue by Msahu201989** [opensearch-project/OpenSearch-Dashboards#5740]
I am having AWS service Amazon OpenSearch Service enabled & have a domain . My requirement is to move old data to s3 bucket

Please note :  Fine grained access control is not enabled 

How to move old indexes from open search to s3 bucket if Fine grained access control is not enabled 
Also i want to access one of the node from cluster but unable view IP

**Comment by AMoo-Miki** [comment]
@Msahu201989 you would be best served by reaching out to AWS support or posting on [forum.opensearch.org](https://forum.opensearch.org/).
