### ISSUE TITLE
[BUG] Error Accessing Index Patterns Without Corresponding Indices in OpenSearch Dashboards

### ISSUE THREAD

**Issue by yoicomment** [opensearch-project/OpenSearch-Dashboards#5768]
# Describe the bug
When attempting to access an index pattern in OpenSearch Dashboards that does not have any corresponding indices, an error message is displayed: "Error: Could not locate that index-pattern-field (id: @timestamp)". This occurs in the OpenSearch Dashboards Discover Tab. After that error is thrown, the only way to fix it via refresh or clearing the cache. It can happen that there are no corresponding indices when e.g. index patterns are created via api calls/terraform or when the indices are deleted by index lifecycle management.

# Steps to reproduce the behavior:

1. Create an index pattern in OpenSearch Dashboards using Terraform, without having any existing indices that match this pattern.
2. Go to OpenSearch Dashboards.
3. Navigate to the Discover Tab.
4. Attempt to select the newly created index pattern.
5. Observe the error message: "Error: Could not locate that index-pattern-field (id: @timestamp)".

# Expected behavior
The expected behavior would be for OpenSearch Dashboards to either not display or disable the selection of index patterns that do not have any corresponding indices. This would prevent the error from occurring and improve user experience by guiding them away from selecting non-functional index patterns.

OpenSearch Version
2.11.1 docker images
Dashboards Version
2.11.1 docker images
Plugins
All plugins that are in bundled when using docker container images. 

Host/Environment (please complete the following information):

OS: Ubuntu 22.04
Browser and version: Firefox

**Comment by abbyhu2000** [comment]
@abbyhu2000 try to reproduce the issue.

**Comment by yoicomment** [comment]
@abbyhu2000 this issue was fixed in 2.12
