### ISSUE TITLE
[BUG] Discover routing without query params does not route correctly

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#5774]
**Describe the bug**

Wen visiting the single document or context pages, if the url does not contain query parameters, the routing breaks. e.g.

```sh
# Works
http://localhost:5601/app/discover#/context/90943e30-9a47-11e8-b64d-95841ca0b247/oyj5iIwBAXmWFklaNiuy?

# Does not work
http://localhost:5601/app/discover#/context/90943e30-9a47-11e8-b64d-95841ca0b247/oyj5iIwBAXmWFklaNiuy
```

The issue is with how discover maps the legacy URL's to the new data explorer route. The url parameters after the `?` are optional, but the regex currently requires the `?` to be present to route the URL correctly. 

**To Reproduce**

**Expected behavior**

Routes `http://localhost:5601/app/discover#/context/<doc-id>/<index-id>` correctly

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by ananzh** [comment]
close this since it is fixed in 2.12
