### ISSUE TITLE
Plugin that displays base64 as image

### ISSUE THREAD

**Issue by replacementAI** [opensearch-project/OpenSearch-Dashboards#5805]
I'm trying to code a plugin that is a custom visualization type, that will convert any matching base64 fields into images, but I am having trouble finding similar examples and documentation on how to code such a thing. Has anyone ever done this before, or can anyone offer some pointers? Thanks

**Comment by AMoo-Miki** [comment]
@replacementAI I don't know of a plugin that does that specifically but you would get a lot more eyes on this issue if you post about it on https://forum.opensearch.org.

**Comment by AMoo-Miki** [comment]
@replacementAI I am not sure if this will help you or not but if you will be having only one type of image encoded in base64, you can use them without a plugin. I will add an example in a few minutes.

**Comment by AMoo-Miki** [comment]
```
// Create an index
PUT /base64

// Set the mapping up to be keyword so I can use it in aggregations; text would work otherwise
PUT /base64/_mapping
{
  "properties": {
    "image": {
      "type": "keyword"
    }
  }
}

// Add some images
POST /base64/_doc 
{
  "image": "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNCAxNCIgaGVpZ2h0PSIxNCI+PHBhdGggZmlsbD0iI0M5MDAwMCIgZD0iTTEgNmgxMnYySDF6Ii8+PC9zdmc+"
}


POST /base64/_doc 
{
  "image": "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNCAxNCIgaGVpZ2h0PSIxNCI+PHBhdGggZmlsbD0iIzE4QjI0QiIgZD0iTTEzIDZIOFYxSDZ2NUgxdjJoNXY1aDJWOGg1eiIvPjwvc3ZnPg=="
}
```

The I created an index pattern for `base64` (my index). I edited the `image` field by:
1. setting "format" as `Url`
2. setting "type" as `Image`
3. setting "URL Template" to `data:image/svg+xml;base64,{{value}}`

My images are SVGs and the "URL Template" matches the data-URIs for SVG images.

I then created a Data Table visualization and the images showed fine. However, Area and Bar visualizations were adamant to use the text and I don't think they are hooked to interpret the format correctly.
