### ISSUE TITLE
[Feature] Implementation of saving in `Saved Queries` not only `query text` and `filters`, but also `index patters` and `Selected fields`

### ISSUE THREAD

**Issue by kinseii** [opensearch-project/OpenSearch-Dashboards#5812]
**Is your feature request related to a problem? Please describe.**

The Save Queries option does not save the index pattern and Selected fields. If you load a saved query, these fields are reset, which is very inconvenient because we use many different queries and we have to manually set the necessary patterns and fields.

**Describe the solution you'd like**

Implement the ability to save index pattern and Selected fields in the Save Queries.

**Versions:**
OpenSearch 2.11.1
OpenSearch Dashboards 2.11.1
AKS 1.27.7

**Comment by ananzh** [comment]
I believe index patterns and fields can be saved in saved objects. For example, in Discover, we implement saved search on top of saved object which can save idx and selected fields to the table. Same for visualization. Therefore, we could this to save and select the saved query. Do you think this could satisfy your needs? Is there any specific pain for using both of them?

**Comment by kinseii** [comment]
@ananzh 
I apologize, I'm not quite sure what you mean. If this is a suggestion for implementing such behavior, then I agree. We use `Discover` and `Saved Queries` in the `Search` field (3.5" floppy disk icon). If you mean that this is already implemented, when I load any Saved Query (to the left of `Search` the 3.5" floppy disk icon), the Index Templates and Selected Fields fields are reset.

**Comment by kinseii** [comment]
@abbyhu2000 
Guys, I may have misunderstood you. It seemed to me that you can implement this functionality. But if you have already done it, please send a link to PR. In the new version 2.12 the behavior of `Saved Queries` has not changed.

**Comment by kinseii** [comment]
@abbyhu2000 
@ananzh 
Please reopen this Issue. 

The thing is that saving `Index Pattern` and `Selected fields` to `Saved queries` does not work. I check both boxes to save the search, but only `Time filter` is saved.

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/74458264/0024d5b2-2013-42e4-b887-c7349059b164)
