### ISSUE TITLE
[BUG] At first time, Import saved objects with check existing objects and automatically override, when there is no conflict and create new objects, still display {number} objects overwritten 

### ISSUE THREAD

**Issue by yujin-emma** [opensearch-project/OpenSearch-Dashboards#5861]
**Describe the bug**

Tried to import saved objects from local file, chose an empty data source, choose Check existing objects and automatically override, since there is no conflict, objects are imported as new objects, but still display overwritten, which is not correct
**To Reproduce**
1. Enable data source feature
2. Go to dashboards managements -> saved objects
3. import
4. choose a local file to upload
5. At Data source picker, choose an empty data source
6. choose check existing object and automatically override conflict
7. can see {number} objects override, but the total number of objects increase by {number}

**Expected behavior**
 {number} objects new
**OpenSearch Version**
2.12
**Dashboards Version**
2.12
**Plugins**

**Screenshots**
![Screenshot 2024-02-09 at 15 50 18](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/112784385/771fec96-ad6e-4cde-81d0-b5db484e751e)

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by AMoo-Miki** [comment]
@yujin-emma noted that this is fixed with #5871
