### ISSUE TITLE
[FEATURE] Documentation For  Cell Dimensions

### ISSUE THREAD

**Issue by ahopp** [opensearch-project/OpenSearch-Dashboards#5865]
**Is your feature request related to a problem?**
When clicking the [explanation of cell dimensions](https://opensearch.org/docs/latest/dashboards/maptiles) link (see below) in the Advanced Settings (under Stack Management), I see a generic page about [maptiles](https://opensearch.org/docs/latest/dashboards/maptiles). On this page, there is no reference to cell dimensions.

![image](https://user-images.githubusercontent.com/9532728/158638014-326ad10e-c2cb-4aa5-82dd-1c5b5c544834.png)

**What solution would you like?**
If I click explanation of cell dimensions, I should be able to find some relevant information on cell dimensions. This would/might include information on cell dimensions (currently does not include cell dimensions at all).

**What alternatives have you considered?**
None.

**Do you have any additional context?**
None.

**Comment by wbeckler** [comment]
The link is here: https://github.com/opensearch-project/OpenSearch-Dashboards/blame/main/src/plugins/maps_legacy/server/ui_settings.ts

Transferred issue to OpenSearch-Dashboards from the Documentation repo.

We definitely need to update the link as it's nonsensical. It might be the case that there is no link where an explanation of the setting exists. It could also be that this setting doesn't do anything.

**Comment by kavilla** [comment]
@AMoo-Miki can you please comment

**Comment by AMoo-Miki** [comment]
I think we should include the below table for geohash precision on https://opensearch.org/docs/latest/aggregations/bucket/geohash-grid/ and link OSD's help-line to that page.

|Percision / Length<br>of Geohash|Latitude<br>Bits|Longitude<br>Bits|Latitude<br>Error|Longitude<br>Error|Cell<br>Height|Cell<br>Width|
|------------------|-------|-------|-------|-------|-------|-------|
|1|2|3|±23|±23|4992.6 km|5009.4 km|
|2|5|5|±2.8|±5.6|624.1 km|1252.3 km|
|3|7|8|±0.70|±0.70|156 km|156.5 km|
|4|10|10|±0.087|±0.18|19.5 km|39.1 km|
|5|12|13|±0.022|±0.022|4.9 km|4.9 km|
|6|15|15|±0.0027|±0.0055|609.4 m|1.2 km|
|7|17|18|±0.00068|±0.00068|152.5 m|152.9 m|
|8|20|20|±0.00086|±0.000172|19 m|38.2 m|
|9|22|23|±0.000021|±0.000021|4.8 m|4.8 m|
|10|25|25|±0.00000268|±0.00000536|59.5 cm|1.2 m|
|11|27|28|±0.00000067|±0.00000067|14.9 cm|14.9 cm|
|12|30|30|±0.00000008|±0.00000017|1.9 cm|3.7 cm|

Reference:
Liu, B., Zhang, C., & Xin, Y. (2023). GL-Tree: A Hierarchical Tree Structure for Efficient Retrieval of Massive Geographic Locations. In Sensors (Vol. 23, Issue 4, p. 2245). MDPI AG. https://doi.org/10.3390/s23042245

**Comment by AMoo-Miki** [comment]
The table is live on https://opensearch.org/docs/latest/aggregations/bucket/geohash-grid/. Will work on getting the link added to OSD.

**Comment by ahopp** [comment]
Dang, we merged right before this issues first birthday!
