### ISSUE TITLE
[Meta] [2.14] Security, bug fix and enhancemanet for dashboards anywhere

### ISSUE THREAD

**Issue by ZilongX** [opensearch-project/OpenSearch-Dashboards#5872]
This meta issue tracks the PR/Issues for security, bug fix and enhancement for dashboards anywhere for 2.14

### RFC
- [x] #5877 
- [x] #6341

### Feature
- [x] #6211 
- [x] #6129
- [x] #6125
- [x] #6268
- [x] #6082 
- [x] #6349
- [x] #6439
- [x] #6420
- [x] #6210
- [x] #6084
- [x] #6058
- [x] #6035
- [x] #6005
- [x] #6298
- [x] #6543

### Enhancement
- [x] #5868
- [x] #6175
- [x] #6438
- [x] #6113
- [x] #6302
- [x] #6257
- [x] #6256
- [x] #6564
- [x] #6429
- [x] #6274
- [x] #6594
- [x] #6393
- [x] #6324
- [x] #6276
- [x] #6271
- [x] #6239
- [x] #6229
- [x] #6174 
- [x] #6566
- [x] #6515
- [x] #6514
- [x] #6497 
- [x] #6400
- [x] #6372
- [x] #6358
- [x] #6333
- [x] #6565
- [x] #6559

### Bug
- [x] #6115 
- [x] #6185
- [x] #6291
- [x] #6548
- [x] #6535
- [x] #6533
- [x] #6434
- [x] #6433
- [x] #6368
- [x] #6498
- [x] #6496
- [x] #6546
- [x] #6450
- [x] #6430
- [x] #6336
- [x] #6281
- [x] #6465
- [x] #5690  
- [x] #6617
- [x] #6581
- [x] #6582
- [x] #6517

### Tech debt
- [x] #6204
- [x] #6142
- [x] #6287
- [x] #6500
- [x] #6437
- [x] #6416

### Dev Guide
- [x] #6449
- [x] #6448
- [x] #6275

### Documentation
- [x] [#7026](https://github.com/opensearch-project/documentation-website/pull/7026)

**Comment by tianleh** [comment]
One document PR to update the instructions to configure CSP rules. https://github.com/opensearch-project/documentation-website/pull/7026

**Comment by BionIT** [comment]
@tianleh Added

**Comment by ZilongX** [comment]
All listed tasks have been successfully merged in as part of 2.14.0 release
