### ISSUE TITLE
Login page customization

### ISSUE THREAD

**Issue by rafaelrangellima** [opensearch-project/OpenSearch-Dashboards#5884]
**Is your feature request related to a problem? Please describe.**

It´s not a problem.

**Describe the solution you'd like**
Put a background image on my login screen page

I would like to know if it is possible to place a background image on the Opensearch Dashboard login screen?

**Describe alternatives you've considered**

**Additional context**

**Comment by AMoo-Miki** [comment]
The login screen is provided by [security-dashboards-plugin](https://github.com/opensearch-project/security-dashboards-plugin) and the documentation for changing the imagery is provided in the documentation, specifically [here](https://opensearch.org/docs/latest/security/configuration/multi-auth/#basic-authentication-settings). You would get more accurate responses if you raise issues on their repo or reach out through the forum.
