### ISSUE TITLE
Loading a json using Vega

### ISSUE THREAD

**Issue by rafaelrangellima** [opensearch-project/OpenSearch-Dashboards#5885]
**Describe the bug**

I have a snippet of a script in Vega that calls a json file:

“data”: [
{
“name”: “node data”,
“url”: “data/diagram.json”,
“format”: {“type”: “json”, “property”: “us”}
},
{
“name”: “link data”,
“url”: “data/diagram.json”,
“format”: {“type”: “json”, “property”: “links”}
}
],

However it shows this error: Loading failed
data/diagram.json

**To Reproduce**

**Expected behavior**
I expected the json file data to be loaded and the topology to be shown.

**OpenSearch Version**
Please list the version of OpenSearch being used.
Opensearch: 2.11.0

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.
Opensearch Dashboard: 2.11.0

**Plugins**
Vega

Please list all plugins currently enabled.

**Screenshots**

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/36416271/fd93edd6-6d14-4d8c-aead-a9b2ff4464e2)

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]
 - Chrome

**Additional context**

Any json file I try, even the ones hosted on Github return the same error.

**Comment by ashwin-pc** [comment]
Hey @rafaelrangellima did this work in an older version of OSD? I dont think JSON is one of the datasources that the vega implementation supports. Its limited to opensearch indexes and raw data

**Comment by ashwin-pc** [comment]
Ah i see. Was it a CORS issue? Closing this since you mentioned that the issue was resolved. CORS is usually the culprit for cross domain requests failing like this. IF there is still an issue, feel free to reopen
