### ISSUE TITLE
[MD] Index pattern selector which was used in maps dashboard plugin and visualization should show data source name as prefix

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/OpenSearch-Dashboards#5900]
**Is your feature request related to a problem? Please describe.**

I feel confused when multiple data source is enabled, while using visualization and need to select an index pattern created from connected data sources, it is almost impossible to distinguish which data source the index pattern belongs to
![Screenshot 2024-02-19 at 3 47 33 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/109f6513-7eab-4cdb-9b09-8e200563035b)

**Describe the solution you'd like**

I would want to be able to have the data source connection name as a prefix to the index pattern name, similar to what we have in saved objects page and discover data picker
![Screenshot 2024-02-19 at 4 01 47 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/3c0105c4-de37-415a-9c28-f558c7214b77)

saved objects page
![Screenshot 2024-02-19 at 4 01 17 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/0cfef428-8d4f-4763-9f9e-264b1700b0f5)

**Describe alternatives you've considered**
There is no alternative other than guessing which data source the index pattern belongs to

**Additional context**

**Comment by BionIT** [comment]
Synced with @kgcreative , and please correct me if it is wrong, the prefix should be like `<connection_name>::<index_pattern_name>`

**Comment by BionIT** [comment]
Happy to work on this

**Comment by BionIT** [comment]
@kgcreative This is what I have for now and should be able to raise PR by end of day if this looks good
![Screenshot 2024-02-20 at 10 15 48 AM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/d0a4ff36-971d-420d-936d-402b5e338e4e)

**Comment by kgcreative** [comment]
Thank you @BionIT! This LGTM!

**Comment by BionIT** [comment]
Thanks @seraphjiang ! Updated the term in my comment
