### ISSUE TITLE
[BUG] when enable multiple data source, import saved objects of index pattern display UUID as prefix, what expected is using data source connection name

### ISSUE THREAD

**Issue by yujin-emma** [opensearch-project/OpenSearch-Dashboards#5901]
**Describe the bug**
Like the screenshot, when using multiple data source, index pattern has UUID as the prefix, what expecting is the data source connection name
![Screenshot 2024-02-19 at 3 46 59 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/112784385/c5b4f421-1be5-4896-a1ae-349e22bf0909)

**To Reproduce**
1. Enable multiple data source feature
2. import saved objects to a data source
3. Go to saved objects 
4. Filter index pattern objects, you can see some index pattern prefixed by UUID

**Expected behavior**
The prefix of the index pattern should be the data source connection name
**OpenSearch Version**
main
**Dashboards Version**
main
**Plugins**
N/A
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by seraphjiang** [comment]
Prefer to use datasource instead of data source connection. Will discuss more with @kgcreative no need any change for now, stay tuned 🥹

**Comment by kgcreative** [comment]
I think what the OP is referring is to displaying the name of the data source instead of a UUID in the cases where a saved object is imported

(A.k.a: `dataSourceName::indexPattern` instead of `UIID::indexPattern`

**Comment by yujin-emma** [comment]
This PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5907 fixed the issue mentioned here
![Screenshot 2024-03-13 at 09 17 48](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/112784385/bc6ba41a-993c-4d84-af98-050e1516c829)
