### ISSUE TITLE
[Proposal] Create a changelog to track releases over time

### ISSUE THREAD

**Issue by tmarkley** [opensearch-project/OpenSearch-Dashboards#591]
**Is your feature request related to a problem? Please describe.**

We currently (i.e. for v1.0.0) generate [release notes](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/release-notes) for each release, but changelogs are often easier to parse/search when dealing with version bumps/upgrades than individual release notes. Having a complete summary of breaking changes, new features, etc. between all previous versions is incredibly useful.

**Describe the solution you'd like**

We could use something like this to aid in the generation: https://github.com/github-changelog-generator/github-changelog-generator

**Describe alternatives you've considered**

Some potential alternatives:
* https://github.com/CookPete/auto-changelog
* https://github.com/git-chglog/git-chglog
* https://github.com/semantic-release/semantic-release
* https://github.com/conventional-changelog/standard-version

**Additional context**

A great example is mocha, where they include the version number, date, sections in each release, and emojis (a fun bonus feature): https://github.com/mochajs/mocha/blob/master/CHANGELOG.md

I also added a comment in the OpenSearch repo with this suggestion: https://github.com/opensearch-project/OpenSearch/issues/789#issuecomment-871675956

**Comment by galangel** [comment]
Good suggestion

**Comment by dblock** [comment]
+1, and I would want this to be in https://keepachangelog.com/en/1.0.0/ format

A stretch idea would be to both enforce the format and require changelog entries on PRs, thus not needing to do any work for releases notes before releases. I use https://github.com/dblock/danger-changelog for this.

**Comment by zhongnansu** [comment]
Change log makes auto backport PRs fail a lot, since all PRs now will touch the same file `CHANGELOG.md`, and the chance  of a conflict becomes higher.

**Comment by joshuarrrr** [comment]
closing this proposal, as most of the suggestions have been implemented, albeit at significant cost to developers and maintainers.
