### ISSUE TITLE
[BUG] Test Connection is not working for multi data source

### ISSUE THREAD

**Issue by bandinib-amzn** [opensearch-project/OpenSearch-Dashboards#5924]
**Describe the bug**

After introducing the change in PR #5895, Test connection is no longer working.

**To Reproduce**
1. Go to Create data source
2. Enter title, endpoint, credentials.
3. Click on 'Test connection'

**Expected behavior**
Test connection should be successful for correct credentials and endpoint.

**OpenSearch Version**
N/A

**Dashboards Version**
N/A

**Plugins**

N/A

**Screenshots**

<img width="1907" alt="Screenshot 2024-02-22 at 10 58 01 AM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/63824432/bd962e6f-63db-4fdc-b84f-14d384a8a14f">

**Comment by bandinib-amzn** [comment]
This is due to missing customApiSchemaRegistryPromise while calling dataSourceServiceSetup.getDataSourceClient in https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data_source/server/routes/test_connection.ts#L62-L72
```
Argument of type '{ savedObjects: SavedObjectsClientContract; cryptography: CryptographyServiceSetup; dataSourceId: string | undefined; testClientDataSourceAttr: DataSourceAttributes; request: OpenSearchDashboardsRequest<...>; authRegistry: IAuthenticationMethodRegistery; }' is not assignable to parameter of type 'DataSourceClientParams'.
  Property 'customApiSchemaRegistryPromise' is missing in type '{ savedObjects: SavedObjectsClientContract; cryptography: CryptographyServiceSetup; dataSourceId: string | undefined; testClientDataSourceAttr: DataSourceAttributes; request: OpenSearchDashboardsRequest<...>; authRegistry: IAuthenticationMethodRegistery; }' but required in type 'DataSourceClientParams'.
```

cc: @BionIT

**Comment by BionIT** [comment]
> This is due to missing customApiSchemaRegistryPromise while calling dataSourceServiceSetup.getDataSourceClient in https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data_source/server/routes/test_connection.ts#L62-L72
> 
> ```
> Argument of type '{ savedObjects: SavedObjectsClientContract; cryptography: CryptographyServiceSetup; dataSourceId: string | undefined; testClientDataSourceAttr: DataSourceAttributes; request: OpenSearchDashboardsRequest<...>; authRegistry: IAuthenticationMethodRegistery; }' is not assignable to parameter of type 'DataSourceClientParams'.
>   Property 'customApiSchemaRegistryPromise' is missing in type '{ savedObjects: SavedObjectsClientContract; cryptography: CryptographyServiceSetup; dataSourceId: string | undefined; testClientDataSourceAttr: DataSourceAttributes; request: OpenSearchDashboardsRequest<...>; authRegistry: IAuthenticationMethodRegistery; }' but required in type 'DataSourceClientParams'.
> ```
> 
> cc: @BionIT

@bandinib-amzn yeah, I had a PR to fix it - no one reviewed yet https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5944/files
