### ISSUE TITLE
[Test] Investigate and fix " [React Intl] Could not find required `intl` object" console error for unit tests

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#593]
**Describe the issue**

Currently, we observe the following console error when run unit tests. To make a clean unit test, we want to explore the reasons for these errors/warnings and decide whether we could fix or remove them. 

```
  console.error
    [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry. Using default message as fallback.

```

Here is a list of all the unit test suites which have the above issue:
* src/plugins/telemetry_management_section/public/components/telemetry_management_section.test.tsx
* src/plugins/index_pattern_management/public/components/field_editor/components/scripting_call_outs/warning_call_out.test.tsx
* src/plugins/index_pattern_management/public/components/create_index_pattern_wizard/components/header/header.test.tsx
* src/core/public/core_app/status/components/server_status.test.tsx
* src/core/public/application/ui/app_container.test.tsx
* src/plugins/vis_default_editor/public/components/controls/percentiles.test.tsx
* src/core/public/overlays/banners/user_banner_service.test.ts
* src/plugins/index_pattern_management/public/components/edit_index_pattern/scripted_fields_table/components/header/header.test.tsx

**To Reproduce**
Run:`yarn test:jest {path to the above test}` 

**Expected behavior**
    
explore each problem unit test cases and investigate each question:
   
- what causes the console error or issues?

- should this unit test log this error or warning message?

- if answer to the above question is no, then can we fix it?

The final output is expected to be a cleaned unit test with un-necessary error/warnings been removed. 

**OpenSearch Version**
OpenSearch 1.0.0

**Dashboards Version**
Dashboards 1.0.0

**Comment by kavilla** [comment]
Can be closed now right @ananzh ?
