### ISSUE TITLE
[BUG] Discover crashed when loading a saved search from saved object list in dashboards management

### ISSUE THREAD

**Issue by mengweieric** [opensearch-project/OpenSearch-Dashboards#5942]
**Describe the bug**

Discover crashed when loading a saved search from saved object list in dashboards management.

**To Reproduce**
1. in Discover page, do a query search (or even without any change)
2. Click on save icon beside query bar
3. click save current query
4. go to 'saved objects' of Dashboards management, search for the query saved above
5. click on it to load it in discover
6. Discover page crashed

**Expected behavior**
Discover should load the saved search correctly.

**OpenSearch Version**
2.11.0

**Dashboards Version**
2.11.0

**Plugins**

N/A

**Screenshots**

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/80358241/d8807fcb-d69b-4376-abf2-b7bf6761613d

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by ananzh** [comment]
Sorry. Didn't have time to work on this. Will do it in 2.16.
