### ISSUE TITLE
[BUG] Some saved searches are not showing up in 'Open' flyout of discover

### ISSUE THREAD

**Issue by mengweieric** [opensearch-project/OpenSearch-Dashboards#5945]
**Describe the bug**

If a search is saved through clicking 'saved icon', it is not showing up in 'Open' flyout of discover.

May related to https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5942

**To Reproduce**

1. in Discover page, do a query search (or even without any change)
2. Click on 'save icon' beside query bar
3. click save current query
4. Click 'open' in the top bar
5. Above saved search is not showing up in the list
6. The saved search is seen in saved objects of dashboard management

**Expected behavior**
It should show up in 'open' flyout.

**OpenSearch Version**
2.11

**Dashboards Version**
2.11

**Plugins**
N/A
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by ashwin-pc** [comment]
This is not a bug. What you are referring to is a saved query. They are a different saved object thats unrelated to saved searches although both of these saved objects open into the same discover window from the saved object management pane. These saved objects only show up on clicking the save icon for the saved query menu.
