### ISSUE TITLE
[BUG] Creating no auth data connection fails validaiton

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/OpenSearch-Dashboards#5987]
**Describe the bug**

Try to create a data connection to a cluster running without security:

You get the following error:
```

Request payload:
{"dataSourceAttr":{"endpoint":"http://localhost:9201","auth":{"type":"no_auth","credentials":{"username":"","password":"","service":"es"}}}}

Response:
{statusCode: 400, error: "Bad Request",…}
error
: 
"Bad Request"
message
: 
"[request body.dataSourceAttr.auth.credentials]: types that failed validation:\n- [request body.dataSourceAttr.auth.credentials.0.service]: definition for this key is missing\n- [request body.dataSourceAttr.auth.credentials.1.region]: expected value of type [string] but got [undefined]"
statusCode
: 
400
```

Even though the cluster is reachable:
```
➜  opensearch-3.0.0-SNAPSHOT curl http://localhost:9201
{
  "name" : "b0f1d89879ca",
  "cluster_name" : "opensearch",
  "cluster_uuid" : "jz2tgeuDTk6XgiDEerKtMw",
  "version" : {
    "distribution" : "opensearch",
    "number" : "3.0.0-SNAPSHOT",
    "build_type" : "tar",
    "build_hash" : "3125b948029609f354d3153f8ca6391638daefc7",
    "build_date" : "2024-02-29T01:10:41.128733293Z",
    "build_snapshot" : true,
    "lucene_version" : "9.11.0",
    "minimum_wire_compatibility_version" : "2.13.0",
    "minimum_index_compatibility_version" : "2.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

**To Reproduce**

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by BionIT** [comment]
I can reproduce this bug
before creating the data source, click `test connection` with no auth >> show error
after data source is created, then click `test connection` >> no error

**Comment by BionIT** [comment]
The error is due to schema validation for test connection, happy to work on it! We need to add tests for this validate endpoint
