### ISSUE TITLE
[MD] Expose properties to allow customization for picker provided by data source plugin

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/OpenSearch-Dashboards#5992]
**Is your feature request related to a problem? Please describe.**

In https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5717, we implemented a data source picker in order to unify the experience when selecting data source in devtools, tutorial, etc. While being used by plugins, this picker needs to be customized in order to satisfy the needs.

**Describe the solution you'd like**

We can expose the following properties for consumers
- placeholderText
- prepend
- defaultOption

In addition, we can expose a filter function property to allow consumers to define their filtering logic to hide incompatible/irrelevant data sources

**Describe alternatives you've considered**
Each consumer would need to write its own picker in order to customize things

**Additional context**

**Comment by seraphjiang** [comment]
looking forward to see some examples. It could be first party plugin like discover app
