### ISSUE TITLE
Update CHANGELOG.md

### ISSUE THREAD

**Issue by bandinib-amzn** [opensearch-project/OpenSearch-Dashboards#5998]
Looks like changes targeted for 2.13.0 getting added in [2.12.0 CHANGELOG](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/CHANGELOG.md#2120---2024-02-20).

We need to move them to unreleased until we release 2.13.0.

**Comment by bandinib-amzn** [comment]
@manasvinibs @kavilla Thoughts?

**Comment by BionIT** [comment]
Also, wonder if we cut release branch from 2.x, while backport 2.x PR skips changelog, see https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5971#discussion_r1505046062. Do we need to add changelog when submitting PR against main if it doesn't get into 2.x?
