### ISSUE TITLE
[Workspace] Support delete saved objects by workspace

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/OpenSearch-Dashboards#6016]
**Is your feature request related to a problem? Please describe.**

When deleting a workspace, we need to delete all saved objects associated to this workspace, otherwise those saved object will become to orphan objects and not able to clean up.

To support share functionality in future, saved objects may associated to multiple workspace,
if a saved object associated to 2 or more workspaces, the delete operation will detach it from the deleted workspace instead of hard delete the saved object itself.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

#4944 #6013

**Comment by SuZhou-Joe** [comment]
Closed as #6013 has been merged
