### ISSUE TITLE
[Proposal] - New, Open, Save, Share and Update Discover Searches and Queries

### ISSUE THREAD

**Issue by shanilpa** [opensearch-project/OpenSearch-Dashboards#6085]
## Overview
The following proposal aims to show what an improved query and discover search saving, opening and updating experience might look like.

### Current challenges
Currently in Discover there are several places where a user can trigger a save action. These options make it confusing and rely on a user knowing what each save option does and how to best use them. Additionally, updating and knowing what saved search you are in is confusing and not clearly indicated for users. The following proposal seeks to address these concerns by creating a simplified, transparent, and functional saving, opening and updating experience.

### Saving and Updating a Search or Query
Users are able to save both a query and a search via the same save option. For Searches they are also able to add a search directly to an existing Dashboard via the optional field. Users can also update searches and are given visibility into the state and name of their exploration.

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113368824/3bc2f6af-c2ff-44f6-9a62-ab7c6cd85f17

### Opening a Search or Query

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113368824/6c825799-b83b-4962-99ed-0dbd49acc896

### New and Share
The new option opens a new Discover Search (unsaved). If a user has an existing search we prompt them with a modal asking if they want to save or discard any unsaved searches.

The share option follows the existing save functionality but also contains reporting

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113368824/ab5e7689-d1d3-4504-a603-a7e44fc74f5c)

**Comment by kgcreative** [comment]
I think we need to disambiguate DQL from Saved Searches and Saved PPL Queries. To me, DQL is really search/filter. This should be saved filters, not saved queries. PPL Saved Queries are more akin to DQL Saved Searches, not "Search and filter" saved states. This becomes apparent in visualizations and dashboards, where you have queries that populate the individual visualizations, but you can still search and filter on them. We should disambiguate this clearly, and move to a "Saved filters" paradigm.

**Comment by kavilla** [comment]
We also have the filter bar which i believe you can save the query with filters and time filters.

![Screenshot 2024-05-13 at 3 58 08 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/12060704/069136ac-32c6-44e7-8fdb-caaf36cc1f7e)

Does this mean each query can be saved when stacking queries or is it a singular stacked saved query. does filters get applied to response or each individual query?

cc: @abbyhu2000 might have some relevance here.

**Comment by RyanL1997** [comment]
Hi folks, just trying to confirm it here: are we redesigning the above flows in this proposal, so that we can close this issue since the designs are out of date? (cc: @kgcreative @kavilla @ashwin-pc )

**Comment by kavilla** [comment]
@RyanL1997 

Yeah I agree. will close. The current mocks include the save query and saved search.

This is because in stacked queries, it gets confusing and it is better to associate saved queries with the query.
