### ISSUE TITLE
react-cytoscapejs installed. Application not able to find module

### ISSUE THREAD

**Issue by priyankamahajan369** [opensearch-project/OpenSearch-Dashboards#6138]
I have installed the react-cytoscapejs and its types. Added the module in types array of tsconfig.base.json

// adding global typings
    "types": [
      "node",
      "jest",
      "react",
      "flot",
      "@testing-library/jest-dom",
      "resize-observer-polyfill",
      "react-cytoscapejs"
    ]
npm install react-cytoscapejs
npm install --save @types/react-cytoscapejs

On bringing OSD up, where i am trying to use cytoscape along with data_grid_table, getting following error:

 ERROR in ./public/application/components/data_grid/data_grid_table.tsx
       │          Module not found: Error: Can't resolve 'react-cytoscapejs' in '/home/pmahajan/PriyankaProjects/OpenSearch-Dashboards2.11_original/OpenSearch-Dashboards/src/plugins/discover/public/application/components/data_grid'
       │          resolve 'react-cytoscapejs' in '/home/pmahajan/PriyankaProjects/OpenSearch-Dashboards2.11_original/OpenSearch-Dashboards/src/plugins/discover/public/application/components/data_grid'
       │            Parsed request is a module
       │            using description file: /home/pmahajan/PriyankaProjects/OpenSearch-Dashboards2.11_original/OpenSearch-Dashboards/package.json (relative path: ./src/plugins/discover/public/application/components/data_grid)
       │              Field 'browser' doesn't contain a valid alias configuration
       │              resolve as module

**Comment by AMoo-Miki** [comment]
OSD uses `yarn` for package management. To add a package, as opposed to installing it directly, please add it to the `package.json` file and do the normal `yarn osd bootstrap`.

Please reopen if you have any more questions.
