### ISSUE TITLE
[MDS]Typo in data_source_management plugin

### ISSUE THREAD

**Issue by xinruiba** [opensearch-project/OpenSearch-Dashboards#6142]
**Describe the bug**

We've identified a typo in our codebase, which is currently referenced in 31 places as of March 13, 2024.

Typo Link: [link](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/df6de4e23c89b99e07bc6faae4f1f67a81568e14/src/plugins/data_source_management/public/auth_registry/authentication_methods_registry.ts#L24) 

**To Reproduce**
N/A

**Expected behavior**
Should be `AuthenticationMethodRegistry` instead of `AuthenticationMethodRegistery`.

**OpenSearch Version**
2.12

**Comment by BionIT** [comment]
Thanks @xinruiba for reporting it! Do you want to fix it? Can you also backport to 2.12 if it gets affected?

**Comment by xinruiba** [comment]
> Thanks @xinruiba for reporting it! Do you want to fix it? Can you also backport to 2.12 if it gets affected?

Thanks for the follow up, we are targeting this issue fix on 2.14~
