### ISSUE TITLE
[Multi data Source] Data source and Data source management plugin auditing

### ISSUE THREAD

**Issue by bandinib-amzn** [opensearch-project/OpenSearch-Dashboards#6204]
### Issue Description

Perform a general audit of the data source and data source management plugin.

### Proposed Implementation

1. Ensure near 100% coverage of documentation. 
2. Ensure that there is documentation coverage of the backend and its functions.
3. Perform a static code analysis, and address issues that it finds.
3.1 Ensure that best practices are followed.
3.2 Fix typo errors.
3.3 Remove duplicate code
3.4 Naming of methods, parameters should be adherent to their functionality.
3.5 Correct TypeScript type errors
4. Ensure near 100% coverage of Unit testing
5. Add functional. integration tests
6. Search for security vulnerabilities.

### Tasks
 -  [x] #6142
 -  [x] #6287 
 - [ ] #6437

**Comment by seraphjiang** [comment]
Thanks @bandinib-amzn for taking the initiative to raise the bar for the quality.

**Comment by bandinib-amzn** [comment]
Data source plugin and data source management plugin both have data source attribute interface. 

Interface in data source plugin: 
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/476cffc2f793b424d68981aaaee9aa1f9fd958be/src/plugins/data_source/common/data_sources/types.ts#L8-L18

Interface in data source management plugin:
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/476cffc2f793b424d68981aaaee9aa1f9fd958be/src/plugins/data_source_management/public/types.ts#L139-L153

It creates confusion among the plugin owners and in general consumers of data source plugin. Therefore, we should maintain only one interface for data source attributes.

I propose to remove interface from `data_source_management`[https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data_source_management/]. 
- Move extra properties to interface in data_source plugin.
- change type of auth_type to be `AuthType | string` to allow custom auth type along with predefined.
- To reduce impact and efforts to change reference in files which are using data_source_management plugin interface, we will export the interface from the same file from where we removed duplicate interface.
