### ISSUE TITLE
[Workspace] Add update workspace page

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/OpenSearch-Dashboards#6269]
**Is your feature request related to a problem? Please describe.**

After users create a workspace, they may want to update the workspace name, description or the feature set when they need, so we should have an update page for workspace.

**Describe the solution you'd like**

Add a new page for users to update the workspace attributes, such as name, description, feature set, color etc.

**Additional context**

In terms of user experience, the update page should be consistent with the create workspace page: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6179.

**Comment by ruanyl** [comment]
Close this one as it's completed
