### ISSUE TITLE
[MDS] Support label rendering when only given ID

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/OpenSearch-Dashboards#6274]
To support a more seamless MDS experience, plugins may want to include the dataSourceId within the url somehow. Thus, links can be shared with the correct datasource context. However, today the datasource menu does not populate the label of the datasource based on the datasource. This can be confusing to users, who may not know what human-readable datasource they are looking at. 

We should support this for all types of components(read only, selectable, aggregate), when activeOption is provided.

Either an API call should be made to look up the datasource name, or it can be attempted to be found using the existing list that gets called by the menu component initially. 

For illegal data source id passed into the component, we should show a toast with user friendly message like `Data source <id> is not available`. 

- [x] readonly data source view: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6315
- [ ] single selectable

**Comment by BionIT** [comment]
Thanks @derek-ho! One discussion we had with @RamakrishnaChilaka as well was that if only the data source id is provided, then the component will make a call to get the name/title of the data source to save some network calls.

**Comment by yujin-emma** [comment]
I will work on this :)

**Comment by BionIT** [comment]
Thanks @yujin-emma

**Comment by BionIT** [comment]
PR has been merged, closing issue
