### ISSUE TITLE
[BUG] Add datasource with test connect failed

### ISSUE THREAD

**Issue by zhyuanqi** [opensearch-project/OpenSearch-Dashboards#6281]
**Describe the bug**

Connect failed to remote datasource. After change data_source.ssl.verificationMode: none  in config file, connection succeed

**To Reproduce**
1. Go to Datasource
2. Click on Create datasource connection
4. Add a datasource and test connection
5. Datasource connection failed. 
6. In the config/opensearch_dashboards.yml file, after change data_source.ssl.verificationMode: none. Connection would work

**Expected behavior**
Expect test connection to work

**Dashboards Version**
Main branch

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by BionIT** [comment]
The bug is introduced in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6171/files
The reason is because when passing the sslConfig object, ca field is set to empty array

**Comment by cwperks** [comment]
Looks like the default of empty list should be removed [here](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6171/files#diff-b08115fb7b3fe6a92ddc034122496543e8cdaf025fd8e4c9100a1b5bb8a9709dR59). 

This would match the behavior of the existing [opensearch_client_config](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/server/opensearch/legacy/opensearch_client_config.ts#L183)

**Comment by cwperks** [comment]
@zhyuanqi @BionIT Thank you for filing this issue. I opened a Draft PR to address the issue here: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6282

If the `datasource.ssl.certificateAuthorities` setting is not present in `opensearch_dashboards.yml` then the sslConfig portion of the client config should contain `undefined` instead of empty array.

**Comment by kavilla** [comment]
@cwperks , looks like this didn't get into 2.13 cut so I have added the label 2.14 and will resolve this issue. If this is incorrect please, update it as needed.

Thank you.

**Comment by cwperks** [comment]
This is good to be closed. The backport to 2.x was merged yesterday: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6296
