### ISSUE TITLE
[BUG][NewHomePage] Avoid Requiring Index Write Permission for the New Homepage Loading

### ISSUE THREAD

**Issue by Flyingliuhub** [opensearch-project/OpenSearch-Dashboards#6320]
**Describe the bug**

The new homepage was introduced in the 2.13 release, which required index write permission when loading. However, this should be avoided as dashboard users may not have index write permission. 

**To Reproduce**
1. Enable useNewHomePage in the advance setting 
2. Open the homepage with users who only have readonly permission users
3. The new homepage was broken with error message "There was an error loading the homepage."

Steps to reproduce the behavior in local cluster:
1. Run OS with security plugin `yarn opensearch snapshot --security`
2. Run osd `yarn start --no-base-path`
3. Login with osd with admin user and enable newhome feature from advanced setting for `Global tenant`
4. Copy the default role `readall` and add Global tenant read permission   
5. Create user `test` and map to the copied `readall_copy` role
6. Login with osd with `test` user which created in the step 5
7. Navigate to homepage

**Expected behavior**
The new home page loading should not required to index write permission

**Impact**
In case of admin enabled advance setting in the global tenant, all the readonly users under global tenant will impact when visit new home page. 

**OpenSearch Version**
8.13.0

**Dashboards Version**
2.13.0

**Plugins**

All the official release plugins

**Screenshots**

<img width="995" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/33105471/5bd5bcd5-73f0-49a6-a5c0-703191609e68">

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/33105471/072027e1-7cd8-4b8e-8d46-67fbd5148a8c

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

````
{
    "statusCode": 403,
    "error": "Forbidden",
    "message": "no permissions for [indices:data/write/index] and User [name=xxx, backend_roles=[xxx], requestedTenant=null]: security_exception: [security_exception] Reason: no permissions for [indices:data/write/index] and User [name=xxxx, backend_roles=[xxxx], requestedTenant=null]"
}

````

**Comment by seraphjiang** [comment]
Thanks @Flyingliuhub @ashwin-pc  

@bbarani  @wbeckler  do you think we should conduct a patch release to include fix for this?

cc: @kgcreative @elfisher

**Comment by bbarani** [comment]
Based on feedback from @ashwin-pc, this bug is in an opt-in feature and the new dashboard is not enabled by default so the  risk is low.

**Comment by seraphjiang** [comment]
> Based on feedback from @ashwin-pc, this bug is in an opt-in feature and the new dashboard is not enabled by default so the risk is low. Please let me know if you think otherwise.

not sure how we define the opt-in feature, compare the experimental feature , GA feature.

+ @kgcreative  @elfisher to assess the potential to custom impact

**Comment by ananzh** [comment]
@Flyingliuhub I am not able reproduce this. Here are my steps:

* Add opensearch_security.auth.anonymous_auth_enabled: true in opensearch_dashboards. also set http:
  anonymous_auth_enabled: true in opensearch
* I use global admin to set to use new home page
* log out
* remove login part from url and reload


https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/2ae244dc-6c27-46cc-bf70-5392b4387312

**Comment by Flyingliuhub** [comment]
> @Flyingliuhub I am not able reproduce this. Here are my steps:
> 
>     * Add opensearch_security.auth.anonymous_auth_enabled: true in opensearch_dashboards. also set http:
>       anonymous_auth_enabled: true in opensearch
> 
>     * I use global admin to set to use new home page
> 
>     * log out
> 
>     * remove login part from url and reload
> 
> 
> Here is the video, and start at 40s https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/2ae244dc-6c27-46cc-bf70-5392b4387312

You are visit default home, not newhome page, you need to visit the new home page for repro the issue

**Comment by ananzh** [comment]
@Flyingliuhub will revisit this in 2.15

**Comment by ananzh** [comment]
Issue is in src/plugins/home/public/services/section_type/section_type.ts 

```
if (heroes || sections) {
              homepage
                .save({})
                .then(() => error$.next(undefined))
                .catch((e) => error$.next(e));
            }
```

to 
```
if (heroes || sections) {
              homepage
                .save({})
            }
```

**Comment by Flyingliuhub** [comment]
@ananzh 2.15 is release soon. do you have a fix for this issue? we still saw this error in the future.playground with 2.15 build

**Comment by ananzh** [comment]
@ruanyl I think this bug is fixed in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7054. I don't quite remember why I reopen it on the same day when PR is merged. I think it might just be a mistake when I check all the 2.15 PRs. Feel free to verify this.

**Comment by ruanyl** [comment]
Introduced a new framework for dynamic content rendering https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7201, the issue no longer existing, closing this now.
