### ISSUE TITLE
[Multiple Datasource] Data source multi selectable component should return the selected data sources and return to the callback function after initial load

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/OpenSearch-Dashboards#6324]
**Is your feature request related to a problem? Please describe.**
Currently, search relevance plugin and query workbench plugin would use the multi selectable component as a filter, and by requirements, the multi selectable will select all data sources by default, however the selected data sources are not passed to callback function until there is a change event.

**Describe the solution you'd like**
Multi selectable component should pass selected data sources on the initial load to the call back function

**Describe alternatives you've considered**
Instead of select all options, do not select any options as the default state, then that means user need to always make a selection first

**Additional context**

**Comment by huyaboo** [comment]
Taking a look

**Comment by BionIT** [comment]
Thanks @huyaboo!
