### ISSUE TITLE
[BUG] TSVB offset causes canvas issues during daylight savings

### ISSUE THREAD

**Issue by dvas0004** [opensearch-project/OpenSearch-Dashboards#6326]
**Describe the bug**

Our TSVB charts went from this:

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/5849965/f502bfe0-70ed-4533-8c90-ecdfb9b8e85d)

To this:

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/5849965/1ab3b19f-8447-485c-902e-7d08fedeaf59)

Note how the bars became way too thin. The red bar series is the same as the green bar series with an offset of 7 days. 
If you look very closely you'll notice a slight gap that happened since April 01

![g6f8J0onzpexanH7](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/5849965/d63d1869-5322-4023-8edc-f0dc060d134e)

It just so happens that on March 31st we had a daylight savings switch and set our clocks forward by one hour. This seems to be causing the issue. If we instead select a time period when the timeseries and the offset timeseries are within the same daylight savings, the issue goes away

**To Reproduce**
1. Create a TSVB series
2. Ensure the series is in bar chart mode, with preferably a larger interval (e.g. 1 day)
3. Duplicate the series
4. Change the offset of the duplicated series to something like 7 days
5. Some part of the timeseries data must be in a different daylight savings

**Expected behavior**
Bar width in charts should not be affected by daylight savings and retain their original width

**OpenSearch Version**
2.9.0

**Dashboards Version**
2.9.0

**Plugins**

default

**Host/Environment (please complete the following information):**
 - Rocky Linux 8
 - Chrome Version 123.0.6312.86

**Additional context**

This seems to have been around for a while, as there seem to be references to "bars going thin" in Elasticsearch Kibana too, way back in 2020: https://discuss.elastic.co/t/create-side-by-side-bar-chart-for-business-data/235500/3

**Comment by dvas0004** [comment]
workaround: manually setting the timezone in the "Advanced settings" page (as opposed to leaving the default `browser`) resolves the issue

**Comment by dvas0004** [comment]
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/5849965/903186b5-171c-4ba3-b048-234b2f858ca9)

**Comment by AMoo-Miki** [comment]
The `timezone` setting is exactly for problems like this. I am glad you were able to find the solution. Please let us know if you face any other issues with DST.
