### ISSUE TITLE
[BUG] Hide local cluster should be set using yaml config

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/OpenSearch-Dashboards#6336]
**Describe the bug**
In https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5754, we introduced a new yaml config to allow hide local cluster from the data source component. This property is needed for the component to decide if local cluster should be shown as an option. 

Note that this property should be set from the yaml config, note that we can get the prop from the dataSource object https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data_source/public/types.ts#L8 and should set it in https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data_source_management/public/plugin.ts#L105

**Additional context**

**Comment by zhongnansu** [comment]
Hi Lu @BionIT,  I'd like to work on this issue

**Comment by BionIT** [comment]
Awesome, thanks @zhongnansu !
