### ISSUE TITLE
[Multiple Datasource] [Plugins Version Decoupling] Fetch and include Installed Plugin List in the data-source saved object when creating a new data source in MDS

### ISSUE THREAD

**Issue by ZilongX** [opensearch-project/OpenSearch-Dashboards#6349]
**Is your feature request related to a problem? Please describe.**

This feature is the second step per discussion and feedback collected from RFC https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5877. 

In order to decouple the plugin versions with OSD core, first step we're making is to fetch the installed plugin list when creating a new data source which would be consumed by plugins for supporting check

**Describe the solution you'd like**

When we create a new data source in MDS, an cat.plugin() api call would be fired towards the targeted data source to fetch the installed plugin list,  then this listr will be included as part of the data-soruce saved object.

**Additional context**

[Plugins Version Decoupling] Dev work is targeting completion by release `2.14.0`

**Comment by derek-ho** [comment]
In a version decoupled world, I am imagining situations where plugins can be installed/removed as needed, so why not do this at filter function time instead of storing the list statically?

**Comment by BionIT** [comment]
PR was merged, I think this issue can be closed
