### ISSUE TITLE
[MDS] Still showing local cluster option when set data_source.hideLocalCluster to true 

### ISSUE THREAD

**Issue by jackiehanyang** [opensearch-project/OpenSearch-Dashboards#6355]
**Describe the bug**

when setting `data_source.hideLocalCluster: true`, still can see local cluster option in data source picker (I'm using DataSourceSelectable component). When local cluster is selected in this scenario, it's return `""`

![Screenshot 2024-04-05 at 14 09 40](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/41348518/1787e181-e3e8-4fd0-8b17-4f0aef2fbbb6)

![Screenshot 2024-04-05 at 14 09 47](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/41348518/8c058133-b648-425f-90d7-de71e90c2e46)

**Comment by BionIT** [comment]
Thanks @jackiehanyang for reporting the bug! @huyaboo should be able to help!

**Comment by jackiehanyang** [comment]
Synced offline, this is not a bug. Instead, it's a feature that's still under implmentation
