### ISSUE TITLE
[BUG] `data_source.hideLocalCluster` setting and default datasource is not being honored when mounting data source menu via Top Nav Menu

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/OpenSearch-Dashboards#6368]
**Describe the bug**

Coming from discussion [here](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6361#discussion_r1555348383). Currently when mounting data source menu via Top Nav Menu, 
- it fails to use the `data_source.hideLocalCluster` setting in data source plugin config to decide if to hide/show local cluster. 
- It fails to render default label of options in any data source picker/selectors.

This is related to how `DataSourceMenu` is consumed in navigation plugin, it's currently imported directly, instead of using the data source management plugin API, `const DataSourceMenu = this.props.dataSourceManagement.ui.getDataSourceMenu<DataSourceMultiSelectableConfig>();`.
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/a0eaf8483cbc29daf95d559c4b98965ad168052d/src/plugins/navigation/public/top_nav_menu/top_nav_menu.tsx#L44

**To Reproduce**
0. enabled data source plugin and set `data_source.hideLocalCluster: true`
1. `yarn start --run-examples`
2. create a datasource,
3. go to Data Source List All Component Mounted Via TopNavMenu Example, from the data source picker on the top right, it doesn't show any default label of any options, and it still shows local cluster 
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/32652829/b65c419c-355e-4d03-a022-452d504c0501)

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by BionIT** [comment]
I think this is done
