### ISSUE TITLE
[Multiple Datasource] Refactor data source readonly view component 

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/OpenSearch-Dashboards#6393]
**Is your feature request related to a problem? Please describe.**
There are a few props we need to add for data source view component:
- optional data source filter, same as other data source components
- hide local cluster, same as other data source components
- onSelectedDataSources, same as other data source components, although this component doesn't allow selection, it needs to have a callback to tell plugins about the validity of the data source passed in

There are a few edge cases we need to address for the component and make sure we have tests that cover the following:
- When id is empty string while hide local cluster setting is true, this is invalid case, will show toasts saying the data source is not available
- When invalid data source id is passed in, the component should show toast saying the data source is not available in regardless of the hide local cluster setting
- When empty data source id is passed in and hide local cluster setting is set to false, the component should show local cluster on initial load
- When valid data source id is passed in, the data source component should show the data source

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhyuanqi** [comment]
Will take a look and work on it.

**Comment by BionIT** [comment]
Thanks a lot @zhyuanqi !
