### ISSUE TITLE
[BUG] CSV download has wrong MIME type

### ISSUE THREAD

**Issue by dpocock** [opensearch-project/OpenSearch-Dashboards#640]
**Describe the bug**

I tried to download a CSV

The server told me it was text/plain

The browser wanted to open it in a text editor

**To Reproduce**

**Expected behavior**

The MIME type should be ```text/csv```

The browser should offer to open the file in a spreadsheet, not a text editor.

**OpenSearch Version**
opensearch-1.0.0-rc1

**Dashboards Version**
"version": "1.0.0-rc1",

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by kavilla** [comment]
Hello @dpocock!

Would you be able to update the description to reproduce and environment details? Trying to recreate and I don't get the same behavior.

Thank you!

**Comment by dpocock** [comment]
Please try this:

- create a new dashboard
- choose Data Table
- in the Dashboard view, you see "Export: Raw Formatted"
- click either of the links, Raw or Formatted

It will offer you a CSV file (based on the filename extension) but it says the document is plain text.

**Comment by kavilla** [comment]
Ah yes I see it now. Will remove the untriaged label for now.

**Comment by kavilla** [comment]
Attached the `help wanted` label for now, since I am not able to get to this soon.
