### ISSUE TITLE
[BUG] Long data source name breaks data source edit page 

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/OpenSearch-Dashboards#6432]
**Describe the bug**
Long data source name breaks data source edit page, and the set default, delete, test connection options are gone
<img width="1562" alt="Screenshot 2024-04-12 at 11 24 54 AM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/d17f9c45-e7f0-4c3f-ac98-0aaa17ad92b8">

**To Reproduce**
1. Go to data source management portal
2. Click on 'data sources'
3. Click on 'create data source connection'
4. enter long name
5. go to edit page for this data source

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by zhongnansu** [comment]
I'll take this task

**Comment by BionIT** [comment]
We addressed this issue by limiting the number of characters, close as duplicate
