### ISSUE TITLE
[BUG] Data source name does not have a limitation on number of characters

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/OpenSearch-Dashboards#6433]
**Describe the bug**
Currently, we can create a data source with unlimited number of characters. We should restrict the number of characters
<img width="1562" alt="Screenshot 2024-04-12 at 11 24 54 AM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/d5bd910f-58a9-4905-918e-dec1d5fcf810">

**To Reproduce**
1. Go to data source management portal
2. Click on 'data sources'
3. Click on 'create data source connection'
4. enter long name with 1000 characters
5. click on create and is successful

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by zhongnansu** [comment]
I'll take this task

**Comment by BionIT** [comment]
Thanks @zhongnansu ! We can restrict to 32 characters.

**Comment by BionIT** [comment]
I believe this issue has fixed, closing next
