### ISSUE TITLE
Change docs-beta links to /docs

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#645]
A production site for documentation exist at https://opensearch.org/docs/, so we should replace all instances related to https://docs-beta.opensearch.org/.

Warning, there are multiple locations where docs-beta was inserted. For example (but not limited to):
* https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/public/doc_links/doc_links_service.ts
* https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/vis_type_vega/public/components/vega_help_menu.tsx#L59

Another thing to mention is that the existing production URLs are *not* versioned. In the future they will need to be.

Associated engine issue: https://github.com/opensearch-project/OpenSearch/issues/956
Associated engine PR: https://github.com/opensearch-project/OpenSearch/pull/957

**Comment by dblock** [comment]
Please get link-checker in! It would have immediately flagged these.

**Comment by kavilla** [comment]
> Please get link-checker in! It would have immediately flagged these.

Sounds good, created an issue here: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/646

**Comment by kavilla** [comment]
This is a duplicate issue will use the older issue but will copy the contents.
