### ISSUE TITLE
[BUG] When using the "View surrounding documents" function the main event is not highlighted

### ISSUE THREAD

**Issue by uranru** [opensearch-project/OpenSearch-Dashboards#6457]
**Describe the bug**
When using the "View surrounding documents" function the main event is not highlighted

**Expected behavior**
I would really like to see the implementation of version 2.9

**OpenSearch Version**
2.13

**Dashboards Version**
2.13

**Plugins**

Please list all plugins currently enabled.

**Screenshots**
In version 2.9 it was like this:
![old](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/44777964/81959b2c-fab5-4052-9add-05fbc7667bec)

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by ananzh** [comment]
Confirmed this regression bug.
