### ISSUE TITLE
Verify broken links automatically

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#646]
**Is your feature request related to a problem? Please describe.**

There were broken links that existing apart of the renaming exercise.

As we are dynamic and things are fluid, links to other repositories might become broken.
Developers find these problems when they use documentation, but we should have an automated way to check and notify broken links.

**Describe the solution you'd like**

Implement a github action to verify if there are any broken links

**Describe alternatives you've considered**

N/A

**Additional context**

Engines issue: https://github.com/opensearch-project/OpenSearch/issues/873
Engines PR: https://github.com/opensearch-project/OpenSearch/pull/877

**Comment by tmarkley** [comment]
Want to get to this ASAP, but it may not be ready for `v1.2`.
