### ISSUE TITLE
[BUG] Node-RE2 build missing for ARM

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#648]
**Describe the bug**
This bug existed pre-fork with the error message including: `node_modules/re2/build/Release/re2.node: cannot open shared object file: No such file or directory`. It turns out the application uses node-re2 so that it can safely use the regular expressions specified by end-users within Timeline, but [Node-RE2](https://github.com/uhop/node-re2) does not contain a hosted build for ARM. So it fails while hosted on machines with ARM architecture since it doesn't exist.

**Steps to reproduce**
* On an applicable platform for example something like graviton2 
* Logon to OpenSearch Dashboards and load sample web log data
* Go to visualize and create a Timeline visualization
* type in query .es(split=host.keyword:50, index=opensearch_dashboards_sample_data_logs).label("Host Name: $1", "^.:(.) >.*")

**Additional context**
The pre-fork repo issue number was: #83012

What the pre-fork did to solve this was build an ARM version and hosted on their own archives site then updated [patch_native_modules_task.ts](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/dev/build/tasks/patch_native_modules_task.ts#L50) to pull that hosted build (pre-fork repo PR #84163).

Since they own that site we probably don't want to just simply pull that build so we should find a replacement to be hosted or verify legally if that falls under the "magic category". The magic category meaning it is required to build and run so we can't change it right away, for example like the default index remaining the same. If we do find out we need to host it we need to figure out where it can be hosted for easy access. We could also verify if the dependency host builds for ARM now or if there exists a better dependency with full builds.

**Requirements to solve**
* Verify the error exists for OpenSearch Dashboards
* Verify if we can reuse the link provided by the pre-fork of the hosted build or if we need to host it
  * If we do need to host our own build we will need to build and then figure out where to host perhaps under: https://artifacts.opensearch.org
* Implement the solution

**Comment by tmarkley** [comment]
@ahopp how should we prioritize this?
