### ISSUE TITLE
[BUG][Workspace] Workspace name duplication check not work for name contains operators of simple query string

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/OpenSearch-Dashboards#6480]
**Describe the bug**

Workspace name suppose to be unique across the system, we have add a unique check https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/workspace/server/workspace_client.ts#L94-L103

```typescript
  const existingWorkspaceRes = await this.getScopedClientWithoutPermission(requestDetail)?.find(
    {
      type: WORKSPACE_TYPE,
      search: attributes.name,
      searchFields: ['name'],
    }
  );
  if (existingWorkspaceRes && existingWorkspaceRes.total > 0) {
    throw new Error(DUPLICATE_WORKSPACE_NAME_ERROR);
  }
``` 

under the hood, this search will use `simple_query_string` syntax to do query. If workspace name contains operators of `simple_query_string`, it will get parsed and not treat as literal value as workspace name.

An example, if we have workspace name `foo bar` that will parsed to workspace name is `foo` or workspace is `bar`, that will duplicate with existing workspace named `foo`.

To resolve this, we might need to support limit the operators as `NONE`, reference: https://opensearch.org/docs/latest/query-dsl/full-text/simple-query-string/#limit-operators

**To Reproduce**

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

#4944

**Comment by BionIT** [comment]
@Hailong-am Looks like a PR has been merged, can this issue be closed?

**Comment by Hailong-am** [comment]
> @Hailong-am Looks like a PR has been merged, can this issue be closed?

Yes, close now.
