### ISSUE TITLE
[BUG] [Workspace] applications are missing when updating a workspace

### ISSUE THREAD

**Issue by ruanyl** [opensearch-project/OpenSearch-Dashboards#6481]
**Describe the bug**

After creating a workspace with features(applications) selected, the features that were not selected is missing from workspace update page.

**To Reproduce**
1. Create a workspace with only `Dashboards` selected(suppose you can select from `Dashboards` `Visualize` `Discover`)
2. Enter the workspace
3. Go to workspace update page
4. Only `Dashboards` is displayed on the page as selected

**Expected behavior**
`Visualize` and `Discover` should also be displayed as unselected for user to select and update.

**OpenSearch Version**
main branch

**Dashboards Version**
main branch

**Plugins**

None

**Screenshots**

None

**Host/Environment (please complete the following information):**
unrelated

**Additional context**

No

**Comment by BionIT** [comment]
@ruanyl Looks like a PR has been merged, can this issue be closed?
