### ISSUE TITLE
[BUG] For Selectable, popover does not close after selection, Also remove group label in the panel

### ISSUE THREAD

**Issue by zhyuanqi** [opensearch-project/OpenSearch-Dashboards#6507]
**Describe the bug**

For selectable, component popover would not close after selection.  Also needs to remove group label in the panel and show options directly, 

**Current UI**
<img width="237" alt="Screenshot 2024-04-16 at 10 51 44 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/53279298/6451021a-b5ee-4a4e-be58-5877fe1012cc">

**Expected UI**
<img width="685" alt="Screenshot 2024-04-16 at 10 51 27 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/53279298/0748c77c-4a90-401e-a1b7-d71bd4086187">

**Comment by BionIT** [comment]
@zhyuanqi could you attach PR for this task?

**Comment by zhyuanqi** [comment]
Related PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6515 and close the issue
