### ISSUE TITLE
[BUG] JSON parse error

### ISSUE THREAD

**Issue by diegargon** [opensearch-project/OpenSearch-Dashboards#6513]
### Describe the bug

Got this error

JSON.parse: expected ',' or '}' after property value in object at line 1 column 13008 of the JSON data

HttpFetchError@http://172....:5601/7326/bundles/core/core.entry.js:15:184257
fetchResponse@http://172...:5601/7326/bundles/core/core.entry.js:

After split the indexer the error was related to logs about windows-secuirty-mitigation   (Windoes Event forward)

winlogbeat->logstash->opensearch

The rest works fine.

### Related component

Indexing

### To Reproduce

Loading
Discover->windows-security-mitigation logs

### Expected behavior

No error.

### Additional Details

Opensearch v 2.12.0

**Comment by kavilla** [comment]
@diegargon, we have added some fixes related to this in 2.13. Could you verify if you are still experiencing this issue?

**Comment by diegargon** [comment]
@kavilla Seems fixed (fast check), thanks.
