### ISSUE TITLE
Validation for Endpoint URL when creating a dataSource

### ISSUE THREAD

**Issue by riysaxen-amzn** [opensearch-project/OpenSearch-Dashboards#6517]
**DataSource Endpoint Validation**
Presently, there is no validation for the Endpoint URL during the creation of a dataSource in Dashboards Management. Consequently, it is possible to create a dataSource with an invalid Endpoint URL, as shown below.

![Image 4-17-24 at 3 16 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/69919272/fdcb64fa-56c6-4e82-8d98-406857a4ad11)

Despite repeated attempts to test the connection, error messages related to authentication issues persist, masking the actual problem associated with the Endpoint URL. Also, I was able to create a dataSource with an invalid Endpoint

![Image 4-17-24 at 3 33 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/69919272/26896190-01c4-4dc7-bd35-9b97a887f874)

**Describe the solution you'd like**

Implementing DataSource Endpoint Validation would significantly improve the user experience. By incorporating this validation, error messages can accurately reflect the cause of failure during dataSource creation, leading to more efficient issue resolution.

**Describe alternatives you've considered**

**Additional context**

**Comment by BionIT** [comment]
Thanks @riysaxen-amzn to report this issue! @zhongnansu could you help to work on this and this issue in functional test repo is somewhat related https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/1202

**Comment by zhongnansu** [comment]
> Thanks @riysaxen-amzn to report this issue! @zhongnansu could you help to work on this and this issue in functional test repo is somewhat related [opensearch-project/opensearch-dashboards-functional-test#1202](https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/1202)

Sure, I'll work on this. What I plan to do is to add the same logic of "test connection", to the create data source validation.
