### ISSUE TITLE
[BUG] Fix text alignment and change to normal cursor in data source aggregated view

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/OpenSearch-Dashboards#6533]
**Describe the bug**
When hover over the aggregated view, the cursor should be regular cursor
![cursor-read-only](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/3245f2a8-7184-4870-bf53-7f3474468ef3)

The text for the popover needs to be aligned
![Screenshot 2024-04-18 at 7 21 44 AM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/17714150/e3654d09-05a6-48e0-8abf-b0440e54966a)

**To Reproduce**
1. Go to future playground
2. Click on maps plugin
3. Go to create and open the popover
4. See the behavior

**Expected behavior**

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by huyaboo** [comment]
I can take this issue

**Comment by BionIT** [comment]
Thanks @huyaboo !

**Comment by BionIT** [comment]
I believe this is addressed in the PR attached, please reopen if not @huyaboo
