### ISSUE TITLE
[BUG] Data source selectable and readonly component are not consistent

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/OpenSearch-Dashboards#6535]
**Describe the bug**

- The height of the popover header should be consistent between the read-only and selectable
- The stroke around the header looks better in the read-only popover, the floating line between the search field and the header looks a bit weird. This might be a part of next item.
- It looks like additional padding is added to the selectable popover content

**To Reproduce**
1. Go to future playground
2. Go to security plugin or index management plugin
3. Go to main page vs details page
4. See problem

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by zhyuanqi** [comment]
Will work on it.

**Comment by BionIT** [comment]
Awesome, thanks @zhyuanqi

**Comment by BionIT** [comment]
I believe this is fixed, please reopen if not @zhyuanqi
