### ISSUE TITLE
[Multiple Datasource] Empty State - Please keep consistent font size and keep the footer button small

### ISSUE THREAD

**Issue by yujin-emma** [opensearch-project/OpenSearch-Dashboards#6548]
**Is your feature request related to a problem? Please describe.**

![Screenshot 2024-04-18 at 11 27 06 AM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/112784385/91211c82-db4e-4235-af23-320cc7d3225b)

**Describe the solution you'd like**

1. The text in the no data source not consistent with other text, please use 12 ( small ) as the text
2. The footer button should be in small size

**Describe alternatives you've considered**

N/A
**Additional context**

**Comment by BionIT** [comment]
I believe this is addressed in the PR, @yujin-emma please reopen if not
