### ISSUE TITLE
[Meta] [2.15] Security, bug fix and enhancemanet for dashboards anywhere

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/OpenSearch-Dashboards#6600]
This meta issue tracks the PR/Issues for security, bug fix and enhancement for dashboards anywhere for 2.15
### RFC
- [x] #6410

### Feature
- [x] #6607

### Bugs
- [x] #6771
- [x] #6822
- [x] #6879
- [x] #6857
- [x] #6835
- [x] #6738
- [x] #6878
- [x] #6850
- [x] #6940
- [x] #6948
- [x] #6928
- [x] #6908

### Enhancement
- [x] #6715
- [x] #6395
- [x] #6892
- [x] #6893
- [x] #6678
- [x] #6385
- [x] #6919
- [x] #6954
- [x] #6733
- [x] #6702
- [x] #6754
- [x] #6753
- [x] #6750
- [x] #6749
- [x] #6748
- [x] #6741
- [x] #6724
- [x] #6723
- [x] #6903

### Documentation
- [x] #6885
- [x] #6872
- [x] #6860
- [x] #6856
- [x] #6855
- [x] #6864
- [x] #6859
- [x] #6799

### Test coverage
- [x] #6755
- [x] #6752
- [x] #6742
- [x] #6729

**Comment by seraphjiang** [comment]
could we add this https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6607 to track list

**Comment by hdhalter** [comment]
Does this require documentation for 2.15? If so, please raise a doc PR by 6/10/24. Thanks.
