### ISSUE TITLE
Exported Timestamp field is shown as empty brackets with report generation to CSV

### ISSUE THREAD

**Issue by pantinor** [opensearch-project/OpenSearch-Dashboards#6615]
When generating a report from a saved search query that includes the @timestamp field, the results in the CSV are empty brackets instead of the formatted data time field as seen in the UI Discovery section of the same query. 

Is it as known issue?

Using 2.13.0 but was not present in earlier build.

**Comment by kavilla** [comment]
@opensearch-project/admin please re-route this to the reporting plugin repo.

**Comment by pantinor** [comment]
Noting that we tested with 2.9.0 and it works fine.

**Comment by pantinor** [comment]
@kavilla  I will open this in the  reporting-dashboards repo if this is incorrect.  And we can close this.
