### ISSUE TITLE
[BUG][MD] Failing to Install Sample Data to OpenSearch Serverless

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/OpenSearch-Dashboards#6632]
**Describe the bug**

**To Reproduce**
1. Create a data source connecting to OpenSearch Serverless
2. Install sample data
3. See the error
4. Cat indices show the indices but the doc number is 0

**Expected behavior**
Sample data gets installed and doc number is greater than 0

**Dashboards Version**
OSD 2.11 and 2.13

**Screenshots**
```
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "sample_data install errors while loading data. Error: Error: Data Source Error: [index_not_found_exception] no such index [_vtUEo8BMJDI9AagE9AU], with { index=\"_vtUEo8BMJDI9AagE9AU\" & index_uuid=\"_na_\" }"
}
```
<img width="1900" alt="Screenshot 2024-04-24 at 3 55 36 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/16925774/2fcfa954-5457-405d-94e9-e206a77b304c">
<img width="1907" alt="Screenshot 2024-04-24 at 4 08 35 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/16925774/953cf4a6-9883-4f62-96ab-91a8b8e83285">

<img width="1830" alt="Screenshot 2024-04-24 at 4 17 58 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/16925774/a6eac84d-c9a5-4529-87d5-5267e3c1f69f">

**Comment by BionIT** [comment]
@zhongnansu Is it due to serverless index service issue? Just assigned to you, and could you share findings? If no change needed for OSD side, we can close it.

**Comment by zhongnansu** [comment]
> @zhongnansu Is it due to serverless index service issue? Just assigned to you, and could you share findings? If no change needed for OSD side, we can close it.

Yes, we have created support ticket for Amazon OpenSearch Severless, and they are working on the fix. Nothing is needed in OSD side. Closing
