### ISSUE TITLE
[BUG] Developer guide does not have instructions on how to build Dashboards locally

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#666]
**Describe the bug**

There are no instructions on [DEVELOPER_GUIDE.md](https://github.com/ashwin-pc/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md) for how to build OpenSearch Dashboards locally. The [Developer Guide](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md) for OpenSearch core does include these instructions. I also could not find these instructions anywhere else.

**To Reproduce**
1. Go to https://github.com/ashwin-pc/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md
2. No instructions on how to build and run the OpenSearch Dashboards code

**Expected behavior**
Documentation similar to Open Search core on how to build and run OpenSearch Dashboards. Instruction on how to run the other scripts would also be useful here e.g. tests, storybook

**Comment by tmarkley** [comment]
Hi Ashwin, thanks for documenting this! We had some instructions in the README.md but recently edited that. I'll add them to the DEVELOPER_GUIDE and add a link in the README.

**Comment by MerwaneHAMADI** [comment]
For anyone having this kind of issue, you can change versions on github, and see if the install instructions are present.

I found them here https://github.com/opensearch-project/OpenSearch-Dashboards/tree/1.0.0-beta1

Granted, they might be different now, but it's better than nothing.
