### ISSUE TITLE
[BUG] Testing page not found

### ISSUE THREAD

**Issue by MerwaneHAMADI** [opensearch-project/OpenSearch-Dashboards#667]
**Describe the bug**
Testing page not found on main page

**To Reproduce**
1. Go to https://github.com/opensearch-project/OpenSearch-Dashboards
2. Click on Testing : https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/TESTING.md
3. page not found
![Screen Shot 2021-07-25 at 9 01 51 AM](https://user-images.githubusercontent.com/9652976/126905655-46427ed7-ab47-4ba5-9922-f5a1859a4a59.png)

No additional context needed, I think

**Comment by MerwaneHAMADI** [comment]
Also, I don't want to open an other issue for it, but the tutorial on how to get started disappeared.
There were nice instructions on which node version, yard osd bootstrap, etc, etc..
I think it should be really easy to access it from the main github page

**Comment by kavilla** [comment]
> Also, I don't want to open an other issue for it, but the tutorial on how to get started disappeared.
> There were nice instructions on which node version, yard osd bootstrap, etc, etc..
> I think it should be really easy to access it from the main github page

Will be handled in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/666

**Comment by kavilla** [comment]
Thanks for creating this issue will go about adding a TESTING doc.

**Comment by tmarkley** [comment]
Same is true for the `Admin Responsibilities` link because we don't have an ADMINS.md file either.

**Comment by kavilla** [comment]
Below is a draft of the contents, what do y'all think:
---
OpenSearch Dashboards uses [Jest](https://jestjs.io/) for unit and integration tests and [Selenium](https://www.selenium.dev/) for functional tests.

- [General information](#general-information)
- [Requirements](#requirements)
- [Running tests](#running-tests)
  - [Unit tests](#unit-tests)
  - [Integration tests](#integration-tests)
  - [Functional tests](#functional-tests)
- [Environment misc](#environment-misc) 

# General information
In general, we recommend three tiers of tests:
* Unit tests: small and modular utilizing mocks for external dependencies.
* Integration tests: higher-level tests that verify interactions between systems (eg. HTTP APIs, OpenSearch API calls, calling other plugin). 
* End-to-end tests (e2e): functional tests that uses behavior through the browser.

# Requirements
* Install the latest NodeJS, [NPM](https://www.npmjs.com/get-npm) and [Yarn](https://classic.yarnpkg.com/en/docs/install/#mac-stable)
    * `nvm install v10.24.1`
    * `npm install -g yarn`

# Running tests
The following is a cheatsheet of options for running the tests for OpenSearch Dashboards.

### Unit tests
To run all the unit tests:
`yarn test:jest`
To run specific unit tests, pass the path to the test:
`yarn test:jest [test path]`

### Integration tests
To run all the integration tests:
`yarn test:jest_integration`
To run specific integration tests, pass the path to the test:
`yarn test:jest_integration [test path]`

### Functional tests
To run all functional tests:
`yarn test:ftr`
To run specific functional tests, you can run by CI group:
`node scripts/functional_tests.js --include ciGroup1`

To debug functional tests:
Run the following command on your ubuntu instance for CI group 1:
`node --debug-brk --inspect scripts/functional_tests.js --config test/functional/config.js --include ciGroup1 --debug`

This will print of an address, to which you could open your chrome browser on your instance and navigate to `chrome://inspect/#devices` and inspect the functional test runner `scripts/functional_tests.js`.

# Environment misc
Selenium tests are run in headless mode on CI. Locally the same tests will be executed in a real browser. You can activate headless mode by setting the environment variable:
`export TEST_BROWSER_HEADLESS=1`

By default the version of OpenSearch Dashboards will pull the snapshot of the same version of OpenSearch if available while running a few integration tests and for running functional tests. However, if the version of OpenSearch Dashboards is not available, you can build OpenSearch locally and point the functional test runner to the executable with:
`export TEST_OPENSEARCH_FROM=[local directory of OpenSearch executable]`

**Comment by tmarkley** [comment]
@kavilla that looks pretty good! A few minor comments/suggestions:

* `OpenSearch Dashboards uses Jest for unit and integration tests and Selenium for functional tests.` - should this go under the `General Information` section?
* `Unit tests: small and modular utilizing mocks for external dependencies.` --> `Unit tests: small and modular tests that utilize mocks for external dependencies`
* `End-to-end tests (e2e): functional tests that uses behavior through the browser.` --> `End-to-end tests (e2e): functional tests that verify behavior in a web browser.`
* `Run the following command on your ubuntu instance for CI group 1` - Ubuntu shouldn't be required here, right?

Additional questions:
* Should we include instructions for running tests in Jenkins? Or at least mention that it's possible using the `Jenkinsfile`?
* There are some tests that are written in Mocha (documented in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/215), that might be worth mentioning to avoid confusion?
