### ISSUE TITLE
[BUG] link checker failed

### ISSUE THREAD

**Issue by yujin-emma** [opensearch-project/OpenSearch-Dashboards#6682]
**Describe the bug**

The lint checker failed 

**To Reproduce**
1. rebase the latest main code
2. make PR
3. PR lint checker failed due to the issue here: https://github.com/opensearch-project/OpenSearch-Dashboards/actions/runs/8886043901/job/24400402236?pr=6610

**Expected behavior**
Lint checker passed
**OpenSearch Version**
main
**Dashboards Version**
main
**Plugins**
data_source_management
**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by kavilla** [comment]
fixed with: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6688
