### ISSUE TITLE
[BUG] DataSourceMenu prop hideLocalCluster has no effect

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/OpenSearch-Dashboards#6747]
**Describe the bug**

The prop "hideLocalCluster" on DataSourceMenu has no effect. To replicate - set data_source.hideLocalCluster=true in dashboards config yml. Then, when rendering datasourcemenu, try to pass in hideLocalCluster = false. When it is rendered, it still hides the local cluster. 

**To Reproduce**

**Expected behavior**
When set false via prop, it should not hide local cluster. I think it should take precedence over the dashboards config setting. 
**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by BionIT** [comment]
@derek-ho This config should be set by using yaml config instead of each plugin to set it https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6336

**Comment by derek-ho** [comment]
@BionIT security dashboards plugin may need to disregard the yaml config since it needs to manage local cluster things as well, so can we change the prop to be able to take effect as well or override the yaml value?

**Comment by BionIT** [comment]
Synced offline, this prop is set via yaml config not be used by plugins, thus not a bug, will close next.
