### ISSUE TITLE
[Multiple Datasource Test] Add test for auth validation

### ISSUE THREAD

**Issue by yujin-emma** [opensearch-project/OpenSearch-Dashboards#6754]
**Is your feature request related to a problem? Please describe.**

 Add test for auth validation
**Describe the solution you'd like**

 Add test for auth validation
**Describe alternatives you've considered**

**Additional context**

**Comment by BionIT** [comment]
Hi @yujin-emma, is this issue for 2.15?

**Comment by yujin-emma** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6755 fixed this issue
