### ISSUE TITLE
Cannot Start Opensearch Dashboard

### ISSUE THREAD

**Issue by anh2001ht** [opensearch-project/OpenSearch-Dashboards#6762]
Hello, I am using docker compose to run Opensearch, and use source code Opensearch-Dashboard then yarn start to run dashboard (to use plugin i18n). I have a problem that I can not access to dashboard Url (port 5601) because of this error : 

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105328390/01a33c95-b510-4646-87e5-53cb2bc28669)
**Here is my docker-compose.yaml**

version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - compatibility.override_main_response_version=true
      - "OPENSEARCH_SECURITY_ENABLED=true"
      - "OPENSEARCH_SECURITY_AUDIT_ENABLED=true"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=mypasswordStrong123!"
     # - "DISABLE_INSTALL_DEMO_CONFIG=true"
     # - "DISABLE_SECURITY_PLUGIN=true"
    volumes:
      - ./data:/usr/share/opensearch/data
      - ./config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./certs/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
      - ./certs/node1.pem:/usr/share/opensearch/config/node1.pem
      - ./certs/node1-key.pem:/usr/share/opensearch/config/node1-key.pem
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net
networks:
  opensearch-net:
    driver: bridge

**file config opensearch.yml:**
`
network.host: 0.0.0.0
plugins.security.ssl.transport.pemcert_filepath: node1.pem
plugins.security.ssl.transport.pemkey_filepath: node1-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: true
plugins.security.ssl.http.enabled: false
plugins.security.ssl.http.pemcert_filepath: node1.pem
plugins.security.ssl.http.pemkey_filepath: node1-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: root-ca.pem
plugins.security.allow_unsafe_democertificates: false
plugins.security.allow_default_init_securityindex: true
plugins.security.nodes_dn:
  'CN=node1.dns.a-record,OU=UNIT,O=ORG,L=TORONTO,ST=ONTARIO,C=CA'

**file config opensearch_dashboards.yml**

server.host: "0.0.0.0"
opensearch.username: "admin"
opensearch.password: "admin"
opensearch.hosts: ["http://localhost:9200/"]
i18n.locale: "ja-JP"

Can someone help me please, I can run dashboard and opensearch with docker compose sucessfully but I run dashboard with yarn start and docker compose opensearch I can not work. this is the file docker compose that both opensearch and opensearch dashboard work : 

version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - compatibility.override_main_response_version=true
      - "OPENSEARCH_SECURITY_ENABLED=true"
      - "OPENSEARCH_SECURITY_AUDIT_ENABLED=true"
      # - "DISABLE_SECURITY_PLUGIN=true"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=mypasswordStrong123!"
    volumes:
      - ./data:/usr/share/opensearch/data
      - ./config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./certs/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
      - ./certs/node1.pem:/usr/share/opensearch/config/node1.pem
      - ./certs/node1-key.pem:/usr/share/opensearch/config/node1-key.pem
      - ./certs/admin.pem:/usr/share/opensearch/config/admin.pem
      - ./certs/admin-key.pem:/usr/share/opensearch/config/admin-key.pem
      - ./logs/log.log:/usr/share/opensearch/logs/opensearch.log
    ports:
      - 9200:9200
    networks:
      - opensearch-net
  kibana:
    image: opensearchproject/opensearch-dashboards:2.12.0
    container_name: kibana
    ports:
      - 5601:5601
      - 5603:5603
    stdin_open: true
    tty: true
    expose:
      - "5601"
      - "5603"
    environment:
      - 'OPENSEARCH_HOSTS=["http://localhost:9200/"]'
      - 'SERVER_HOST="0.0.0.0"'
      - "OPENSEARCH_USERNAME=admin"
      - "OPENSEARCH_PASSWORD=admin"
    networks:
      - opensearch-net
networks:
  opensearch-net:
    driver: bridge

**Comment by Hailong-am** [comment]
@anh2001ht  `"OPENSEARCH_PASSWORD=admin"` this password need to be same as `- "OPENSEARCH_INITIAL_ADMIN_PASSWORD=mypasswordStrong123!"`

**Comment by anh2001ht** [comment]
> @anh2001ht `"OPENSEARCH_PASSWORD=admin"` this password need to be same as `- "OPENSEARCH_INITIAL_ADMIN_PASSWORD=mypasswordStrong123!"`

Thanks for reply,  when I change OPENSEARCH_PASSWORD into mypasswordStrong123! I got this error 
`server    log   [07:53:33.272] [error][data][opensearch] [ResponseError]: Response Error
server    log   [07:53:33.287] [error][savedobjects-service] Unable to retrieve version information from OpenSearch nodes.
  log   [07:53:34.098] [error][data][opensearch] [ResponseError]: Response Error
server    log   [07:53:35.760] [error][data][opensearch] [ResponseError]: Response Error
  log   [07:53:36.615] [error][data][opensearch] [ResponseError]: Response Error
server    log   [07:53:38.252] [error][data][opensearch] [ResponseError]: Response Error`

**Comment by anh2001ht** [comment]
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105328390/38916293-bb15-4c41-acc0-7776de148c1e)
This is the screenshot when I curl to opensearch node: curl --insecure -u "admin:admin" -XGET https://localhost:9200/

**Comment by Hailong-am** [comment]
> ![image](https://private-user-images.githubusercontent.com/105328390/329969571-38916293-bb15-4c41-acc0-7776de148c1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODgwNTYsIm5iZiI6MTcxNTU4Nzc1NiwicGF0aCI6Ii8xMDUzMjgzOTAvMzI5OTY5NTcxLTM4OTE2MjkzLWJiMTUtNGM0MS1hY2MwLTc3NzZkZTE0OGMxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwODA5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmNkZmZkNGVlMDdmNjAyMDYwMDViY2Q4M2NkMGM3NzQ1ZTVhOTdhYzBjZTcyMTMxNGFmN2NkZmRhNzdjYzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-UXVy11pbbzcLowVRO2p0Ons2gzRhiEZWQeCuaO7U3o) This is the screenshot when I curl to opensearch node: curl --insecure -u "admin:admin" -XGET https://localhost:9200/

I see, do you have [security dashboard plugin](https://github.com/opensearch-project/security-dashboards-plugin) under plugins directory? it's used for log in since OpenSearch has security enabled.

**Comment by anh2001ht** [comment]
> > ![image](https://private-user-images.githubusercontent.com/105328390/329969571-38916293-bb15-4c41-acc0-7776de148c1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODgwNTYsIm5iZiI6MTcxNTU4Nzc1NiwicGF0aCI6Ii8xMDUzMjgzOTAvMzI5OTY5NTcxLTM4OTE2MjkzLWJiMTUtNGM0MS1hY2MwLTc3NzZkZTE0OGMxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwODA5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmNkZmZkNGVlMDdmNjAyMDYwMDViY2Q4M2NkMGM3NzQ1ZTVhOTdhYzBjZTcyMTMxNGFmN2NkZmRhNzdjYzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-UXVy11pbbzcLowVRO2p0Ons2gzRhiEZWQeCuaO7U3o) This is the screenshot when I curl to opensearch node: curl --insecure -u "admin:admin" -XGET https://localhost:9200/
> 
> I see, do you have [security dashboard plugin](https://github.com/opensearch-project/security-dashboards-plugin) under plugins directory? it's used for login since OpenSearch has security enabled.

yes, I have install dashboard plugin already , this is the file opensearch_dashboard.yml after I build security plugin 
`server.host: "0.0.0.0"
opensearch.hosts: ["https://localhost:9200"]
opensearch.ssl.verificationMode: none
opensearch.username: "admin"
opensearch.password: "admin"
i18n.locale: "ja-JP"
opensearch.requestHeadersWhitelist: [ authorization,securitytenant ]
opensearch_security.multitenancy.enabled: true
opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
opensearch_security.cookie.secure: false`

**Comment by kavilla** [comment]
@opensearch-project/admin can you re-route this to security dashboards plugin repo?
