### ISSUE TITLE
[BUG] Running `yarn uiFramework:start` fails to build osd-ui-framework

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#680]
**Describe the bug**

The package `osd-ui-framework` does not build on running `yarn uiFramework:start`. The biggest issue here seems to be that the dependencies were updated but the docsite build was not run since the update. `react-router` was updated from 3 to 4 which was a complete rewrite of the package causing a lot of breaking changes. There are a few other issue which make the build fail as well.

1. The `packages/osd-ui-framework/doc_site/webpack.config.js` file uses the post-css loader but that file now resides in `packages/osd-optimizer/postcss.config.js` (As a part of this migration: [Link](https://github.com/elastic/kibana/commit/827e91c4474e8790374417d30b433296f909b110)). Updating the rule should fix this. 

```js
// from 
{
  test: /\.scss$/,
  loaders: ['style-loader', 'css-loader', 'postcss-loader',  'sass-loader'],
  exclude: /node_modules/,
},
// to
{
  test: /\.scss$/,
  loaders: ['style-loader', 'css-loader', {
    loader: 'postcss-loader',
    options: {
      config: {
        path: require.resolve('@osd/optimizer/postcss.config.js')
      },
    }
  }, 'sass-loader'],
  exclude: /node_modules/,
},
```
2. There is the line referencing a missing elastic svg logo ([Code](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/packages/osd-ui-framework/doc_site/src/components/guide_nav/_guide_nav.scss#L85))

These are the 3 main issues i've identified but there may be more. Migrating the router is what held me off from just jumping in and fixing this.

**To Reproduce**
1. Run `yarn uiFramework:start`
2. The build fails and the server fails to start up

**Expected behavior**
Expected the server to start and load the components

**OpenSearch Version**
1.0.0

**Dashboards Version**
1.0.0

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

This package seems to host many UI components, but i cant seem to find any references to it within the actual application.

**Comment by tmarkley** [comment]
I confirmed that `yarn build`, `yarn build:types`, `yarn uiFramework:build`, and `yarn uiFramework:start` all fail with the latest changes in `main`.
