### ISSUE TITLE
Support query assist in discover

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/OpenSearch-Dashboards#6820]
**Is your feature request related to a problem? Please describe.**

In log explorer there's a feature to generate PPL queries through natural language. But in discover user has to manually write the queries, this feature does not exist there.

**Describe the solution you'd like**

Add query assist to discover.

**Describe alternatives you've considered**

**Additional context**

TBD

**Comment by BionIT** [comment]
Hi @joshuali925, are we targeting to get this done for 2.15 or 2.16?

**Comment by joshuali925** [comment]
currently targeting 2.16. closing as duplicate of #6077
