### ISSUE TITLE
[CI] Automatically run tests on Windows and macOs via github actions

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#683]
Currently we are focusing on automate all tests under ubuntu environment. GitHub Actions Virtual Environments have been extended to involve windows and macos. We could investigate and enable automation on diff environments. Below is the current support env:

<img width="863" alt="Screen Shot 2021-07-28 at 9 36 51 PM" src="https://user-images.githubusercontent.com/79961084/127432597-d7764254-8a48-4a23-90e6-8fff451f6201.png">

Image reference and more info: [here](https://github.com/actions/virtual-environments#github-actions-virtual-environments)

**Comment by joshuarrrr** [comment]
@AMoo-Miki Don't we already run GH Actions windows tests now? Should this be updated to just target macOS?
