### ISSUE TITLE
[BUG] Set default data source unstable issue

### ISSUE THREAD

**Issue by zhyuanqi** [opensearch-project/OpenSearch-Dashboards#6835]
**Describe the bug**
The first created datasource should be automatically set as the default datasource. However, this feature is unstable. Sometimes the first created datasource has not been selected as default datasource. It is flaky

**To Reproduce**
1. Go to management page
2. Click on Datasources ---> create datasource
3. Create datasource and save datasource
4. Datasource has been saved, but it has not been selected as default datasource

**Expected behavior**
The first created datasource should be automatically set as the default datasource. 

**OpenSearch Version**
OS_2.14

**Dashboards Version**
OSD_2.14

**Comment by BionIT** [comment]
@zhyuanqi @yujin-emma Is the tag correct? We are targeting to fix in 2.15, right?
