### ISSUE TITLE
[BUG] Dashboards does not properly process custom timestamp formats for index mappings

### ISSUE THREAD

**Issue by huyaboo** [opensearch-project/OpenSearch-Dashboards#6839]
**Describe the bug**
Timestamp index mappings seem to be case-sensitive. When a timestamp format `MMM dd, YYYY h:mm:ss a` is used for the index mapping, Dashboards does not properly parse the date. For example, a timestamp of `Apr 25, 2024 11:58:33 PM` will be processed as `2024-01-01T23:58:33.000Z` (`Jan 1st, 2024 11:58:33 PM`). However, if the timestamp format were `MMM dd, yyyy h:mm:ss a`, the issue is fixed.

**To Reproduce**
1. In `Dev Tools`, create an index with the following index mapping:
```
PUT /test-index
{
  "mappings": {
    "properties": {
      "timestamp": {
        "type": "date",
        "format": "MMM dd, yyyy h:mm:ss a"
      }
    }
  }
}
```
2. Add a document 
```
POST /test-index/_doc
{
  "timestamp": "Apr 25, 2024 11:58:33 PM"
}
```
3. Create the index pattern with `timestamp` as the timestamp field
4. Navigate to `Discover` (this index mapping should correctly parse the `timestamp` field)
5. Navigate back to `Dev Tools` and delete the index (or reindex) and create a new index with the following index mapping
```
DELETE /test-index

PUT /test-index
{
  "mappings": {
    "properties": {
      "timestamp": {
        "type": "date",
        "format": "MMM dd, YYYY h:mm:ss a"
      }
    }
  }
}
```
6. Insert an example document
```
POST /test-index/_doc
{
  "timestamp": "Apr 25, 2024 11:58:33 PM"
}
```
7. Navigate to `Discover` again and the document will show up in `Jan 1st` instead of `Apr 25`

**Expected behavior**
Timestamp index mappings should not be case-sensitive in Dashboards.

**OpenSearch Version**
OS 2.11.1

**Dashboards Version**
OSD 2.11.1

**Plugins**
Core plugins only

**Screenshots**

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/73027756/d0d00f56-31ae-4da4-9602-96419b23ba8a

**Host/Environment (please complete the following information):**
 - OS: MacOS: (Apple Silicon)
 - Browser and version: Firefox

**Comment by kavilla** [comment]
@huyaboo,

So when navigating to https://playground.opensearch.org/app/management/opensearch-dashboards/settings, you can search for format and get the following:

![Screenshot 2024-05-28 at 10 59 45 AM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/12060704/f78a60b4-ea52-4cce-9ebd-30abd7c42342).

Can we verify that this solves the issue? If so then, I think we should keep the casing very specific as it is configurable by end users.

**Comment by BionIT** [comment]
@huyaboo Does reply above help address the issue?
