### ISSUE TITLE
[BUG] Undocumented server.ssl.cipherSuites in opensearch_dashboards.yml

### ISSUE THREAD

**Issue by artur-borys** [opensearch-project/OpenSearch-Dashboards#6841]
**Describe the bug**

Hi! First of all - thanks for the great work that you're doing. It's an important project and I value your time and dedication.

I treat security very seriously and I've noticed that the default ciphersuites contain a lot of ciphers which are not considered to be secure anymore.

I've noticed that the example ``opensearch_dashboards.yml`` file doesn't contain any description for ``server.ssl.cipherSuites`` key.

I was able to limit the enabled ciphersuites to a secure list by setting:
``` yaml
server.ssl.cipherSuites:
  - TLS_AES_256_GCM_SHA384
  - TLS_CHACHA20_POLY1305_SHA256
  - TLS_AES_128_GCM_SHA256
  - ECDHE-ECDSA-AES256-GCM-SHA384
  - ECDHE-ECDSA-CHACHA20-POLY1305
  - ECDHE-ECDSA-AES128-GCM-SHA256
```

It would be nice if the parameter was mentioned in the example ``opensearch_dashboards.yml`` file, as I think it's an essential parameter when it comes to security.

**To Reproduce**
N/A

**Expected behavior**
``opensearch_dashboards.yml`` example linked in https://opensearch.org/docs/latest/install-and-configure/configuring-dashboards/ contains a description of ``server.ssl.cipherSuites`` key

**OpenSearch Version**
N/A

**Dashboards Version**
Probably all

**Plugins**
N/A

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
N/A

**Additional context**
Enabled ciphersuites are an essential part of security of the application, so users should be able to configure them. I had to take a look at the source code of opensearch-dashboards to see if this is configurable at all. At first I've tried configuring it via NODE_OPTIONS environment variables or node.options config file, but it didn't work.

The important detail is that I'm using Wazuh fork of opensearch-dashboards, the wazuh-dashboard, but the issue is related more to Opensearch documentation. It would be nice if the HTTP documentation contained a table with description of all the available parameters, instead of linking to an example ``opensearch_dashboards.yml``, but I understand that this is a difficult and mundane task to do and keep up to date. That's why I ask you to at least include a mention about ``server.ssl.cipherSuites`` in the example ``opensearch_dashboards.yml`` file. If there are no people available to do it, I can probably find a little bit of time to add it and ask for verification if my description is ok.

I've found the configuration parameter here: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/server/http/ssl_config.ts#L53

**Comment by kavilla** [comment]
Hello @artur-borys,

Thanks for opening! I understand and agree, with documentation concerns we have approached as adding as much as we can over time.

I see you are willing to take the task of adding the details. That would be great and would love your help, do you mind if assign this issue but feel free to ask any questions.
