### ISSUE TITLE
[BUG] Search Fails when query using Dashboard DQL search space. 

### ISSUE THREAD

**Issue by ksajan** [opensearch-project/OpenSearch-Dashboards#6842]
**Describe the bug**
I recently updated the default limit of the number of fields from 1000 to 1500, but after that change, I am receiving this error message for every search that I do on the dashboard

```
Error
    at fetch_Fetch.fetchResponse (https://<dashboard_url>/_dashboards/301202401/bundles/core/core.entry.js:15:180800)
    at async interceptResponse (https://<dashboard_url>/_dashboards/301202401/bundles/core/core.entry.js:15:176117)
    at async https://<dashboard_url>/_dashboards/301202401/bundles/core/core.entry.js:15:178597
```

Not able to search on the Dashboard 

**To Reproduce**
1. Go to devtools
2. Update the collection/index default field limit 
3. Search in that collection/index using dashboard searchable space

**Expected behavior**
It should just work and returns the expected output as it does when using filters

**OpenSearch Version**
Please list the version of OpenSearch being used.
v 2.14.0

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.
v 2.11.0

**Plugins**

Please list all plugins currently enabled.
None
**Screenshots**
<img width="1433" alt="Screenshot 2024-05-28 at 1 35 05 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/31013555/1b451033-0e73-473e-9b41-93ad49cec872">
<img width="933" alt="Screenshot 2024-05-28 at 1 40 13 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/31013555/94c27aed-57c7-4224-bc76-a5d0b8a293cd">

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]
Using as AWS manager service deployed on graviton server

**Additional context**

**Comment by yujin-emma** [comment]
Hi. @ksajan could you please provide more information about running OS on 2.14 while the OSD is 2.11

**Comment by manasvinibs** [comment]
@ksajan Closing this one for now. Please feel free to re-open if you need help.
