### ISSUE TITLE
[DataSource] Restrict data source creation/update/delete when manageableBy is none or dashboard_admin

### ISSUE THREAD

**Issue by yubonluo** [opensearch-project/OpenSearch-Dashboards#6889]
**Is your feature request related to a problem? Please describe.**

Adding an optional setting that controls the permissions of data source to create, update and delete.
data_source.editMode: "read_only|admin_only|none"
"all": The data source is readonly for all users.
"dashboard_admin": The data source can only be managed by dashboard admin.((https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6389) ).
"all": The data source can be managed by all users. Default to "all".

**Describe the solution you'd like**

Before editing a data source, data source permission client wrapper will verify the data source edit mode.

**Describe alternatives you've considered**

**Additional context**

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4944

**Comment by BionIT** [comment]
Hi @yubonluo, thanks for opening the issue! Are we targeting this in 2.16?

**Comment by yubonluo** [comment]
> Hi @yubonluo, thanks for opening the issue! Are we targeting this in 2.16?

Hi @BionIT , The PR regarding this issue will be submitted in the next two days, with releasing on 2.15.
