### ISSUE TITLE
[BUG] Bad format with nested objects

### ISSUE THREAD

**Issue by robertogg** [opensearch-project/OpenSearch-Dashboards#6922]
I am creating a simple object using nested objects:
`{
  "_index": "testindex1",
  "_id": "100",
  "_version": 1,
  "_score": 0,
  "_source": {
    "patients": [
      {
        "name": "John Doe",
        "age": 56,
        "smoker": true
      },
      {
        "name": "Mary Major",
        "age": 85,
        "smoker": false
      }
    ]
  }
}
`
Mapping:
`PUT testindex1
{
  "mappings" : {
    "properties": {
      "patients": { 
        "type" : "nested"
      }
    }
  }
}
`

Internally it works fine, so the search using nested object works perfectly but cheking the document in the Dashboard I can see this:

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/537683/89ea609d-4089-41d5-9e59-ecb3e4b2f88b)

Instead of seeing the info as an object it is split in data array:
So you cannot know which data belongs to which object only checking the possition. is there any way to use the previous visualization used in earlier versions ( before 2.12)
This is how I would expect to see it:
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/537683/85a4bab4-52c5-41fa-bac8-7185db28b0a9)

**OpenSearch Version**
Since version 2.12.

**Dashboards Version**
since version 2.12

**Comment by kmaity-9563** [comment]
I would to like to work on it,is it open?

**Comment by AMoo-Miki** [comment]
@robertogg, the Table view is supposed to show a flattened view of the data, even nested objects. The JSON view will however show you the nested object in a JSON format.

PS, the older Table views showing a mix of flattened and JSON was a bug which got fixed with 2.12.

If the JSON view doesn't provide you what you need please reopen with details.
