### ISSUE TITLE
[BUG] Sample TSVB visualization is not rendering data with data source 

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/OpenSearch-Dashboards#6936]
**Describe the bug**

This issue only happens when you add sample data to a data source , not local cluster.
- tsvb in flight sample data
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/32652829/713f8d18-293a-4393-9a0f-af3b69cde954)
- tsvb in web log sample data
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/32652829/29d736f7-4bea-41d6-889d-054806285a74)

- tsvb in ecommerce sample data
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/32652829/6782d9d2-43ee-45ba-b3ad-ace33c9d9e8a)

**To Reproduce**

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by BionIT** [comment]
Thanks @zhongnansu for capturing this!
