### ISSUE TITLE
[BUG] sample vis builder visualizations fail to render with data source

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/OpenSearch-Dashboards#6938]
**Describe the bug**

sample vis builder of fails to render with data source 

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/32652829/22bbebaa-f74b-4f41-bbeb-ddc1f6edc1a3)
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/32652829/1d6f25df-4cbc-4ae5-a07f-af0a4ba4387e)

**To Reproduce**
1. create data source
2. add web log sample data from UI
3. check the visual consistency dashboard which contains the sample vis builder visualiaztiuon.

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by BionIT** [comment]
@zhongnansu is this issue completed?

**Comment by zhongnansu** [comment]
> @zhongnansu is this issue completed?

yes, completed by PR #6948 , closing
