### ISSUE TITLE
[Discover-Next][UI] Date histogram can be collapsed

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#7042]
### Description

When query enhancements are enabled. Users default see the date histogram expanded (if available), but when users select the `arrowDown` icon it will collapsed
![Screenshot 2024-06-15 at 7 23 18 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/12060704/22e1f4cc-a361-4678-baf5-4e0020b7f789)

### Requirements
* UX Questions
   * Any keyboard actions?
* If there is an action item from https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7041, that keeps this section separate then make sure the expansion button (and the entire component) is not rendered for timestamp series
* We should toggle off the [existing Discover setting](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/discover/public/application/components/utils/local_storage.ts#L8)

**Comment by abbyhu2000** [comment]
Close as complete.
