### ISSUE TITLE
[Workspace] Add useCaseEnabled in advanced settings

### ISSUE THREAD

**Issue by wanglam** [opensearch-project/OpenSearch-Dashboards#7073]
**Is your feature request related to a problem? Please describe.**

There will be a new navigation links grouped method after #7061 added. User may not used to the new navigation, we need to provide a way to switch back to the original navigation in advanced settings page.

**Describe the solution you'd like**

Add a new `useCaseEnabled` flag in ui settings, expose the value in chrome service. Plugins can use this flag to determine to add specific logic when `useCaseEnabled` equal `true`.

**Describe alternatives you've considered**

N/A

**Additional context**

#4944

**Comment by SuZhou-Joe** [comment]
Close this issue as it has been complete by #7060
