### ISSUE TITLE
[BUG][Discover-Next] Invalid security token error when using query assist with MDS

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#7113]
**Describe the bug**
When testing MDS with discover: 

It is able to get the suggested questions using query assist. However, after pressing generate button, the query failed to generate due to 
```
{"error":{"reason":"System Error","details":"Error from remote service: 
{\"message\":\"The security token included in the request is invalid.\"}",
"type":"OpenSearchStatusException"},"status":403}`
```

**To Reproduce**
1. Installed `MDS DashboardsPlugin` and `queryEnhancements` in /plugins folder and bootstrap in `NeoDashboardsPlugin`
2. Modify corresponding config yml files values and start up a MDS dashboard
3. Created data source connection and index pattern
4. Turned on query enhancement toggle
5. Go to discover

**Screenshots**
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/980c9b6d-1adf-4dea-93b1-0fcdfe80f580)

**Comment by joshuali925** [comment]
1. what is `NeoDashboardsPlugin` and how does it make a difference for query assist?
2. `The security token included in the request is invalid` error message is kind of clear, how was the model setup and is the security token valid?
