### ISSUE TITLE
[Navigation-Next] prepend current nav group into breadcrumbs

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/OpenSearch-Dashboards#7132]
**Is your feature request related to a problem? Please describe.**

After #7027 Nav group introduced, we should set current nav group into breadcrumbs like below. `Observability` is the Nav group title
 
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113890546/3dce37fe-f801-40f7-89ac-6feedf5eb435)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

#7027

**Comment by SuZhou-Joe** [comment]
Should close as we have merge the PR.
