### ISSUE TITLE
[Bug]: No 2.15.0 "Release" for opensearch-dashboards

### ISSUE THREAD

**Issue by max-allan-cgr** [opensearch-project/OpenSearch-Dashboards#7169]
### Describe the bug

In the GitHub releases page for opensearch-dashboards, it shows 2.14.0 as "Latest".

But there is a 2.15.0 release. Right?

### To reproduce

Visit: https://github.com/opensearch-project/OpenSearch-Dashboards/releases

Look at the latest release.

### Expected behavior

2.15.0 release to be visible and "Latest"

### Screenshots

![image](https://github.com/opensearch-project/opensearch-build/assets/159389543/b9963c79-a87b-4716-8488-048d2970b82c)

**Comment by kavilla** [comment]
@max-allan-cgr thanks for catching this and sorry about that. I have created it and should be available.
