### ISSUE TITLE
[BUG] 404 Cannot fetch data sources

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/OpenSearch-Dashboards#7170]
**Describe the bug**

Navigate to "Datasources", under "Direct query connections" you will get a 404 and an error toast popup. I am currently the admin user so I shouldn't be missing any permissions.

![Screenshot 2024-07-03 at 1 57 46 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/26328171/d78a3046-7fe4-4a42-ae19-c0bfc2aba97c)

**Expected behavior**
No error toast, no 404
**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by RyanL1997** [comment]
Transferring the conversation with @derek-ho here:
> this 404 is caused by the absent of dashboards observability, since i'm waiting on the api migration, Right now i'm temporarily hooked the api to the dashboards observability still. And once we change that this should be gone.

According to the above we can close this for now.
