### ISSUE TITLE
[RFC] Data Source Tracking across Nav Changes

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/OpenSearch-Dashboards#7171]
**Is your feature request related to a problem? Please describe.**
With new changes coming in with how navigation works in OSD core (See: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7029), there is now an issue with tracking selected Data source globally (or even within the same sub-apps of a plugin). 

Video of this problem occurring after breaking down in-app navigation into separate apps registered by OSD core: 

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/26328171/f7ff90b4-fb47-49db-ae9d-4c9171313c6f

When navigating between plugins or applications within a plugin, the datasource context is maintained. 

Instead of URL tracking datasources, we can use cookies (which would be persisted across apps), or we can have some globally managed data source (may introduce complexities with data source compatibility across workspaces/plugins).

**Comment by derek-ho** [comment]
@SuZhou-Joe can you take a look/any thoughts on this? I am happy to help out with a solution

**Comment by derek-ho** [comment]
Can a datasource be tracked per nav group/category instead?

**Comment by SuZhou-Joe** [comment]
Hi @derek-ho I will take a look on this.

**Comment by SuZhou-Joe** [comment]
https://github.com/opensearch-project/security-dashboards-plugin/pull/2022

Tagging related PR here.

**Comment by SuZhou-Joe** [comment]
Should be fixed by PR: https://github.com/derek-ho/security-dashboards-plugin/pull/3

**Comment by derek-ho** [comment]
Thanks @SuZhou-Joe. @BionIT since this issue was brought up a while ago: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6534, what do you think of exposing a common URL (or even URL updater method) to standardize this behavior across all sub-applications and also different plugins within a nav category/group?

**Comment by ashwin-pc** [comment]
Why arent we using global state here/

**Comment by SuZhou-Joe** [comment]
We can continue discussing the common url key in #6534.
