### ISSUE TITLE
[BUG] Discover no longer shows new lines in a field

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/OpenSearch-Dashboards#7177]
**Describe the bug**

Discover no longer shows new lines in the selected field

**To Reproduce**
1. Go to devtools
2. run
```http
PUT /multi-line-index/_doc/1
{
  "message": "This \n is \n a \n test \n message"
}
```
4. create index pattern and search in discover
5. select `message` field in the left side bar
6. see `message` is displayed in one line

**Expected behavior**
old behavior as in 1.x, where `message` is correctly displayed with line breaks when selected

**OpenSearch Version**
main

**Dashboards Version**
main

**Plugins**

none

**Screenshots**

<img width="762" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/28062824/05ff6e52-5122-49ec-816a-835aed9ae331">

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by joshuali925** [comment]
the functionality came from 
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/4fc9c064768c2de92404963ddc5516c5f2aab9b3/src/plugins/discover/public/application/angular/doc_table/components/table_row/_cell.scss#L1-L3

but in newer versions, this class is no longer used or defined, and there are no similar classes. 

it was removed in #5086. @ashwin-pc do you know if it's intended to not use `white-space: pre-wrap;` on table cells anymore?

**Comment by stevesimpson418** [comment]
I would like to add this is an issue in 2.x also, tested and verified on version 2.3
