### ISSUE TITLE
[BUG] [Workspace] workspace name missing validation on blank input

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/OpenSearch-Dashboards#7280]
**Describe the bug**

when we create a new workspace, the validation rule for workspace name is to check it don't have special character and only allow `a-z, A-Z, 0-9, (), [], _ (underscore), - (hyphen) and (space)`.
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/d2e7b9d41cf1725b49eb5826c0673d2bb1609d24/src/plugins/workspace/public/components/workspace_form/utils.ts#L39-L46 

But for blank input as workspace name, it can pass the validation and created successfully.

workspace with blank name will be not clickable on workspace list page and hard to tell what it is in workspace switcher.

![image](https://github.com/user-attachments/assets/f1d30b41-a3b7-4e4a-a76a-b62c3f016f5a)

![image](https://github.com/user-attachments/assets/d04328f3-8808-45f0-901a-e2e77adea5cc)

**To Reproduce**

**Expected behavior**

workspace name with blank should be blocked for creation and updation

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by ananzh** [comment]
@Hailong-am I will remove the untriaged label for now.

**Comment by SuZhou-Joe** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7512
