### ISSUE TITLE
[BUG] UI doesn't show version of distribution

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/OpenSearch-Dashboards#731]
**Describe the bug**

The help menu displays `v1.0.0` - this is the version of OpenSearch Dashboards. In the upcoming distribution 1.0.1 release, only patch versions of the plugins will change and Dashboards is slated to not change. So, after upgrade Dashboards will still show 1.0.0, which will be confusing.

**To Reproduce**
1.  Open OpenSearch Dashboards
2. Click on the life preserver
3. (see screenshot)

**Expected behaviour**
This area should should the correct distribution **and** dashboards version. 

**OpenSearch Version**
1.0.0

**Dashboards Version**
1.0.0

**Plugins**
All OpenSearch

**Screenshots**

<img width="349" alt="Screen Shot 2021-08-19 at 2 26 10 PM" src="https://user-images.githubusercontent.com/1152927/130126347-6df47c0a-e723-4e61-91ba-25a36bd0b798.png">

**Comment by kavilla** [comment]
The help menu is linked to package.json version value [[here](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/package.json#L14)]. So we will need to make a change but for the bundle we should be able to mimic what we did for the rc1 version where we modified the package.json and bundled it.

**Comment by jcgraybill** [comment]
Hey, if we make a change to the UI here, let's be sure to use the right terminology: the collection of OpenSearch, OpenSearch Dashboards, and some number of plugins that are tested and distributed together is a "distribution".

**Comment by stockholmux** [comment]
@jcgraybill Edited to reflect the correct terminology.

**Comment by tmarkley** [comment]
@kavilla was this addressed?

**Comment by stockholmux** [comment]
@tmarkley So if there is a 1.1.1 with only a change in a plugin, will the correct version show?

**Comment by tmarkley** [comment]
> So if there is a 1.1.1 with only a change in a plugin, will the correct version show?

It will just as long as Dashboards bumps the [package version number](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1.1/package.json#L14).

**Comment by elfisher** [comment]
@ahopp let's take a look at this. I see an opportunity to be more explicit about the versions we report here. For example, this could be updated to show the Dashboards version and the OpenSearch version since they aren't always the same.

**Comment by tmarkley** [comment]
I'm going through some old issues to try to take care of some low hanging fruit. @ahopp @seanneumann @kgcreative  can we land on a path forward here? Should we show both the Dashboards version and the OpenSearch version? How should we label them in the help menu?

**Comment by seanneumann** [comment]
Since we now support multiple data sources and are working on decoupling Dashboards to run independently, I think we should only show the Dashboards version. And in the Stack Management / Data Sources we should list the endpoint versions.

https://playground.opensearch.org/app/management/opensearch-dashboards/dataSources

@seraphjiang Thoughts?

**Comment by seraphjiang** [comment]
> Since we now support multiple data sources and are working on decoupling Dashboards to run independently, I think we should only show the Dashboards version. And in the Stack Management / Data Sources we should list the endpoint versions.
> 
> https://playground.opensearch.org/app/management/opensearch-dashboards/dataSources
> 
> @seraphjiang Thoughts?

Agree only show dashboards version, not the distribution version of all product. 

btw, dashboards has status page to see all plugins versions

https://playground.opensearch.org/status

the information is retrieved from https://playground.opensearch.org/api/status

```
{
    "name": "dashboards-opensearch-dashboards-78fc478b4c-fmwh8",
    "uuid": "950cadef-8927-47a5-b9e7-d50112079f3a",
    "version": {
        "number": "2.4.0",
        "build_hash": "6e38e1c6f71e56b70f9b89a0452c19f3667995e8",
        "build_number": 4304,
        "build_snapshot": false
    },
    "status": {
        "overall": {
            "since": "2022-12-06T02:02:26.707Z",
            "state": "green",
            "title": "Green",
            "nickname": "Looking good",
            "icon": "success",
            "uiColor": "secondary"
        },
        "statuses": [
            {
                "id": "core:opensearch@2.4.0",
                "message": "OpenSearch is available",
                "since": "2022-12-06T02:02:26.707Z",
                "state": "green",
                "icon": "success",
                "uiColor": "secondary"
            },
            {
                "id": "core:savedObjects@2.4.0",
                "message": "SavedObjects service has completed migrations and is available",
                "since": "2022-12-06T02:02:26.707Z",
                "state": "green",
                "icon": "success",
                "uiColor": "secondary"
            },
            {
                "id": "plugin:advancedSettings@2.4.0",
                "message": "All dependencies are available",
                "since": "2022-12-06T02:02:26.707Z",
                "state": "green",
                "icon": "success",
                "uiColor": "secondary"
            },
```

show engine version of data source is a great idea if feasible.  It should be a runtime version instead of static, retrieve when connect to endpoint. that way if customer upgrade their domain to new version, it got reflect without update datasource.

**Comment by kgcreative** [comment]
Would it make sense to add a `Connection type` column? This would allow for additional information (e.g. `OpenSearch 1.2`, `Prometheus 1.2.3`, `Spark 1.2.1`, `S3`, etc

cc: @KrooshalUX

**Comment by kgcreative** [comment]
This also leads me to think we need `Source` and `Destination` columns to account for things like Federated data sources, where a data source might exist in a remote cluster.

**Comment by seraphjiang** [comment]
close per https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6178
