### ISSUE TITLE
[BUG] dev tools in app tabs styling issue

### ISSUE THREAD

**Issue by ruanyl** [opensearch-project/OpenSearch-Dashboards#7349]
**Describe the bug**
1. Data source selector moving from right to left
2. Unexpected extra space under tab title

Screenshot:
<img width="1684" alt="image" src="https://github.com/user-attachments/assets/794cc149-5232-485e-bf55-29c201c133c1">

**To Reproduce**
4. Click on '....'
5. Scroll down to '....'
6. See error

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by ananzh** [comment]
Close it as resolved
