### ISSUE TITLE
Support new recent icon in OUI and replace SVG code in OSD

### ISSUE THREAD

**Issue by raintygao** [opensearch-project/OpenSearch-Dashboards#7354]
**Is your feature request related to a problem? Please describe.**

In https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7257, we introduced a new icon. 
![image](https://github.com/user-attachments/assets/f4f406fa-d89d-4946-a0fd-b4fe3fdd9fea)
We should add this recent icon to OUI, because this involves the OUI release and the upgrade in the OSD, in order to catch 2.16 release before code freeze, we directly use SVG code in repo. 

**Describe the solution you'd like**

We should add this to OUI library and use this to replace SVG code in OSD.

**Comment by AMoo-Miki** [comment]
Fixed by https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7741

**Comment by raintygao** [comment]
Awesome, thanks Miki!
