### ISSUE TITLE
[Workspace]Hide create workspace button in workspace menu and workspace list

### ISSUE THREAD

**Issue by wanglam** [opensearch-project/OpenSearch-Dashboards#7358]
**Is your feature request related to a problem? Please describe.**

This is a feature request. Only dashboard admin can create workspace,  all the create workspace buttons should be hidden or show "contact to dashboard admin" to create workspace. The workspace menu and workspace list show create workspace for non dashboard admin. That is not as expected.

**Describe the solution you'd like**

Currently, the `isDashboardAdmin` will be stored in the capabilities service as `dashboards.isDashboardAdmin`. The front end page should read this flag to determine wether create workspace button should be displayed.

**Describe alternatives you've considered**

N/A

**Additional context**

#4944 
#6389

**Comment by SuZhou-Joe** [comment]
closed because of #7357
