### ISSUE TITLE
[Feature Request] Auto refresh index pattern

### ISSUE THREAD

**Issue by Nurielevi** [opensearch-project/OpenSearch-Dashboards#7364]
### Is your feature request related to a problem? Please describe

Lately i have been adding a lot of new fields to some logs that goes into opensearch and i had a problem with some dashboards that didn't work at all and i got an error the some fields are "problematic". After a research i found out about index pattern and after refreshing it all dashboards were fixed. 

### Describe the solution you'd like

I would like to know if there are versions that support this feature of auto refresh index patterns.

### Related component

Indexing

**Comment by ananzh** [comment]
I think the original design for not auto refreshing idx has some tradeoff concerns. For example the overhead for automatically checking and updating index patterns for every query and the unexpectedly change on visualization. We will discuss this with other maintainers.

**Comment by AMoo-Miki** [comment]
Thanks for your feature request. This is a popular feature and over the years, we have been looking for a safe and performant ways of achieving this.

We will post back if we arrive at a solution and plan the implementation.

**Comment by magicmicah** [comment]
Hi @Nurielevi @AMoo-Miki  - Is this still on the backlog? I see the issue is closed, but It would be a nice feature to have.
