### ISSUE TITLE
[BUG] Dataseries indexes cant be accessed in UI at all.

### ISSUE THREAD

**Issue by camAtGitHub** [opensearch-project/OpenSearch-Dashboards#737]
**Describe the bug**

Support 'data series' indexes in the UI.
I can't search DS indexes with 'discover'.  
index-patterns finds zero timestamps and or fields.  
SQL and PPL plugins error with `Ds-foo2: Bad Request, this query is not runnable. 

**To Reproduce**
Follow your [docs](https://opensearch.org/docs/opensearch/data-streams/#get-started-with-data-streams)
1. Create index template for DS index  
```
PUT /_index_template/test-ds-foo3
{
  "index_patterns": [ "ds-foo3" ],
  "data_stream": { "timestamp_field": { "name": "@timestamp" } }
}
```
2. Create DS index and post a document in a single, swift motion:
```
POST ds-foo3/_doc
{
  "@timestamp": "2021-08-23T16:02:15.000Z",
  "makethis": "work",
  "yousaid": "it works in the docs",
  "cluster_uuid": "fo345345322"
}
```
3. Try create index-pattern
4. Try visualize anything
5. Try search this index in 'discover'
6. Cry over the hours wasted....

**Expected behavior**
Show me logs / data / visualisations. 

**OpenSearch Version**
Docker based:  opensearch:1.0.0

**Dashboards Version**
Docker based:  opensearch-dashboards:1.0.0  

**Plugins**

As per opensearch-dashboards:1.0.0 and  opensearch:1.0.0  

**Host/Environment (please complete the following information):**
 - OS: opensearch on redhat 8 w podman.
 - Browser: firefox 91.0.1

**Comment by camAtGitHub** [comment]
Hi @kavilla, thanks but no.  
> Are you expecting the "index_patterns": [ "ds-foo4" ] to create an OpenSearch Dashboards index pattern once you insert a doc?  
 
As I mentioned above in step 3, I was creating an index pattern in 'stack management' in every attempt, after posting a few sample documents.  
When I created this ticket I was not able to use the 'UI/Discover' after attempting to create a datasource index after 7 attempts with various index template settings.  
The next day 3 out 7 are now displaying data via 'Discover'.  
As per this table ![Alt](https://raw.githubusercontent.com/camAtGitHub/data_stream_issues/main/DataSeries_verbose_info.png =300x300) [Link](https://raw.githubusercontent.com/camAtGitHub/data_stream_issues/main/DataSeries_verbose_info.png) I'm unable to make heads or tails of why some are working and some are not.  

A good example of confusion is 'ds-foo4' compared to 'ds-foo5', as they are near identical but only one works and the config that does differ works in a different example! The index [templates](https://github.com/camAtGitHub/data_stream_issues) and examples of the [data](https://github.com/camAtGitHub/data_stream_issues) in the indexes are [here](https://github.com/camAtGitHub/data_stream_issues).  
Any insight is appreciate. Thanks

**Comment by camAtGitHub** [comment]
Hi @boktorbb-amzn & @kavilla 
I have no idea whats going on but I have spent another 15 hours trying to get data streams to populate in the discover UI and not a single one worked today! (although I have had a small bit of non-repeatable success in the past...)
This is driving me crazy!!!  

[Here](https://github.com/camAtGitHub/data_stream_issues/blob/main/streams_that_dont_work/apple.txt) [are](https://github.com/camAtGitHub/data_stream_issues/blob/main/streams_that_dont_work/cabbage.txt) [plenty](https://github.com/camAtGitHub/data_stream_issues/blob/main/streams_that_dont_work/chips.txt) of [step](https://github.com/camAtGitHub/data_stream_issues/blob/main/streams_that_dont_work/france.txt) [by](https://github.com/camAtGitHub/data_stream_issues/blob/main/streams_that_dont_work/france.txt) step [examples](https://github.com/camAtGitHub/data_stream_issues/blob/main/streams_that_dont_work/parsnip.txt) [that](https://github.com/camAtGitHub/data_stream_issues/blob/main/streams_that_dont_work/rice.txt) I [did](https://github.com/camAtGitHub/data_stream_issues/blob/main/streams_that_dont_work/tomato.txt) today and [they](https://github.com/camAtGitHub/data_stream_issues/blob/main/streams_that_dont_work/toyota.txt) all [failed](https://github.com/camAtGitHub/data_stream_issues/tree/main/streams_that_dont_work)!  

Please note while trying various steps and stages, I have logged out and back in, refreshed browsers, used private mode while accessing stack management > index patterns and they say 'The indices which match this index pattern dont contain any time fields'  

SOS Please send help :-)

**Comment by camAtGitHub** [comment]
Solved. Cleaner bug report lodged: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/747

**Comment by kavilla** [comment]
Apologies @camAtGitHub and thanks for the detailed information. Will dive into the new issue tmrw.
