### ISSUE TITLE
[BUG] The hamburger icon will always pop up tooltip when switching app

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/OpenSearch-Dashboards#7483]
**Describe the bug**

**To Reproduce**
1. Go to home
2. Click on any of the menu on the left
3. You will see a `menu` pop up

**Expected behavior**
The tooltip should only pop up when hover.

**OpenSearch Version**
3.0.0

**Dashboards Version**
3.0.0
commit id: a9801a2c31858b84f77e51eab2381ee9744989d9

**Plugins**

None

**Screenshots**

https://github.com/user-attachments/assets/5dc72300-a304-4b46-81e9-21403d7521d2

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by virajsanghvi** [comment]
@SuZhou-Joe Can this be closed?

**Comment by SuZhou-Joe** [comment]
closed by #7493
