### ISSUE TITLE
Address Browser Warnings

### ISSUE THREAD

**Issue by Kapian1234** [opensearch-project/OpenSearch-Dashboards#7515]
**Describe the bug**
‘PageRender’, ‘setupHome’, and ‘HomeListCard’ are missing a `key` prop in list rendering.

In ‘use_case_footer.tsx’
Could not find required 'intl' object. <IntlProvider> needs to exist in the component ancestry.

Navlink of workspace_list has already been registered in group settingsAndSetup

**To Reproduce**
Open the console in homepage to see the warnings.

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4944

**Comment by wanglam** [comment]
@Kapian1234 Shall we link this issue with #4944 ?

**Comment by kavilla** [comment]
@ruanyl would you like to comment here. Thanks.

**Comment by ruanyl** [comment]
The PR resolved the issue: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7550
