### ISSUE TITLE
Add latest version of Cypress as a dependency

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/OpenSearch-Dashboards#754]
Currently, Dashboards doesn't support Cypress as a test framework. Many Dashboards plugins, however (Anomaly Detection, Index Management, etc.) are using it, but are maintaining individual versions of it. Because of this, there are occasional integration issues with different plugins, where mismatched versions are found and can cause warning or compilation errors. Trying to test all of the plugins together can also lead to failures, where running different major versions of Cypress can introduce breaking changes that cause some tests to unexpectedly fail.

Preferably, core Dashboards maintains Cypress versioning, and the downstream plugins can consume such versions. This would help maintain consistency and reliability in testing everything together. Additionally, I believe Dashboards should migrate to, and actively use, Cypress, for more consistency between core and the plugins.

**Comment by tmarkley** [comment]
@ohltyler To confirm, do we just need to take a dependency on the Cypress repo? Is there a particular version we should start with?

**Comment by ohltyler** [comment]
> @ohltyler To confirm, do we just need to take a dependency on the Cypress repo? Is there a particular version we should start with?

Yeah, I guess this could be split into multiple steps.
1. Pull in Cypress as a dependency via `yarn add cypress`. Using the [latest version available](https://yarnpkg.com/package/cypress) is probably fine.
2. Reach out to Dashboards plugin owners that plugin-specific versions of Cypress can be removed and consumed from core. This may require a bit of work from plugin teams to fix any broken tests that could be caused by breaking changes introduced in the newer version (e.g., AD Dashboards is using Cypress 5.x, latest is Cypress 8.x)
3. Actively use it as a test framework for core Dashboards itself (can be done at a later time)

Just my thoughts. Let me know what you think.

**Comment by tmarkley** [comment]
That sounds good to me! I think number 3 will indeed come at a later time but I think we can tackle 1 and 2.
