### ISSUE TITLE
[BUG] Version 2.11.1 doesn't support Alerts API

### ISSUE THREAD

**Issue by oshi36** [opensearch-project/OpenSearch-Dashboards#7568]
I am using opensearch v2.11.1 and trying to query opensearch API for getting alerts at this path according to the documentation.
```
GET _plugins/_alerting/monitors/alerts
```
This path is returning me null as a result. On going further I have found that there is not alert index as well under indices which I can query .

**Comment by Hailong-am** [comment]
> I am using opensearch v2.11.1 and trying to query opensearch API for getting alerts at this path according to the documentation.
> 
> ```
> GET _plugins/_alerting/monitors/alerts
> ```
> 
> This path is returning me null as a result. On going further I have found that there is not alert index as well under indices which I can query .

@oshi36 can you run `GET _cat/plugins` to check whether alerting plugin has been installed?

**Comment by oshi36** [comment]
> > I am using opensearch v2.11.1 and trying to query opensearch API for getting alerts at this path according to the documentation.
> > ```
> > GET _plugins/_alerting/monitors/alerts
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This path is returning me null as a result. On going further I have found that there is not alert index as well under indices which I can query .
> 
> @oshi36 can you run `GET _cat/plugins` to check whether alerting plugin has been installed?

yes @Hailong-am it is installed , `opensearch-alerting                  2.11.1.0`

**Comment by oshi36** [comment]
Also when listing monitors under data sources for each monitor I can see this
 ```
"data_sources": {
        "query_index": ".opensearch-alerting-queries",
        "findings_index": ".opensearch-alerting-finding-history-write",
        "findings_index_pattern": "<.opensearch-alerting-finding-history-{now/d}-1>",
        "alerts_index": ".opendistro-alerting-alerts",
        "alerts_history_index": ".opendistro-alerting-alert-history-write",
        "alerts_history_index_pattern": "<.opendistro-alerting-alert-history-{now/d}-1>",
        "query_index_mappings_by_type": {},
        "findings_enabled": false
      },
```

But I can't find any query_index or alerts_index in my indices

**Comment by Hailong-am** [comment]
> But I can't find any query_index or alerts_index in my indices

try `GET _cat/indices?expand_wildcards=all`, note they are system indices, you can query them directly. To query data you need interact with [API](https://opensearch.org/docs/latest/observing-your-data/alerting/api/)

**Comment by oshi36** [comment]
Found this on running the above command `/.opendistro-alerting-alerts` but how can I get alerts with this?

**Comment by kavilla** [comment]
@opensearch-project/admin could you please re-direct this to alerting dashboards repo.

**Comment by oshi36** [comment]
My issue resolved.I am closing this issue
thank you.
