### ISSUE TITLE
[BUG] Discover page hang forever when no index pattern

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/OpenSearch-Dashboards#7626]
**Describe the bug**

when there is no index pattern, the discover page hang for long time and can't render.

**To Reproduce**
1. setup a new OSD instance and don't import any sample data
2. Click on Discover on left navigation, the page URL will be `http://localhost:5601/app/data-explorer/discover#?_a=(discover:(columns:!(_source),isDirty:!f,sort:!()),metadata:(indexPattern:'',view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))`
3. Page start hang and no responding

**Expected behavior**

**OpenSearch Version**
main

**Dashboards Version**
main

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

https://github.com/user-attachments/assets/f726e90e-3538-424e-bdf5-b8e855e88819

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by ruanyl** [comment]
Sharing the screenshot:
![image](https://github.com/user-attachments/assets/d08f253d-1a49-4234-9caf-c2667c0b44c6)

**Comment by samegens** [comment]
I noticed this as well with the recommended docker-compose.yml from https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/. When I replaced the latest tag with 2.15.0 the Discover page works as expected. So it seems this is a bug introduced in 2.16.0.

**Comment by markgoddard** [comment]
Also seeing this using 2.16.0. Reverted to 2.15.0 and it worked.

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/andrross), [2](https://github.com/dblock), [3](https://github.com/AmiStrn), [4](https://github.com/reta), [5](https://github.com/finnegancarroll)]

**Comment by JordanBarnartt** [comment]
We're running into this on a fresh deploy of 2.16.0 as well.  I tried to roll back Dashboards to 2.15.0, but am getting the following error trying to start up Dashboards:
```
WreckHttpsOptions properties:
 | type=log @timestamp=2024-09-06T19:27:33Z tags=["info","plugins","securityDashboards"] pid=1

Error: Setup lifecycle of "securityDashboards" plugin wasn't completed in 30sec. Consider disabling the plugin and re-start.
    at Timeout._onTimeout (/usr/share/opensearch-dashboards/node_modules/@osd/std/target/node/promise.js:42:90)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7) | type=log @timestamp=2024-09-06T19:28:03Z tags=["fatal","root"] pid=1

Stopping all plugins. | type=log @timestamp=2024-09-06T19:28:03Z tags=["info","plugins-system"] pid=1

 FATAL  Error: Setup lifecycle of "securityDashboards" plugin wasn't completed in 30sec. Consider disabling the plugin and re-start.
```

If anyone has any suggestions, I'm all ears.  Right now, I'm thinking it's some issue with the Security index, and I'll need to do a full redeploy down to 2.15.0 on the Opensearch nodes as well.

**Comment by 10000-ki** [comment]
Can it be fixed in the next version?

**Comment by Hailong-am** [comment]
> Can it be fixed in the next version?

I have a PR to fix this https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8082, that will need @kavilla to help review
