### ISSUE TITLE
[BUG] autocomplete not working when defining a filter

### ISSUE THREAD

**Issue by jfwm2** [opensearch-project/OpenSearch-Dashboards#7631]
**What is the bug?**
The autocomplete is not working when defining a filter on OpenSearch Dashboards 2.14 (backend is OpenSearch 2.14)

**How can one reproduce the bug?**
1. Go to 'Discover'
2. Click on '+ Add filter'
3. In the  'EDIT FILTER' windows, select a field (“application” in the screenshot provided)
5. Still in the  'EDIT FILTER' windows, choose the operator “is”
6. Still whithin the  'EDIT FILTER' windows, in the “value” text-field, type a letter or more, but the autocomplete does not work
7. Some error 500 are shown in the “chrome debugger” network tab (see screenshot provided)

**What is the expected behavior?**

**What is your host/environment?**
 - OS: CentOS
 - Version: 8.8
 - Plugins:
   - alertingDashboards@2.14.0.0
   - anomalyDetectionDashboards@2.14.0.0
   - assistantDashboards@2.14.0.0
   - customImportMapDashboards@2.14.0.0
   - ganttChartDashboards@2.14.0.0
   - indexManagementDashboards@2.14.0.0
   - mlCommonsDashboards@2.14.0.0
   - notificationsDashboards@2.14.0.0
   - observabilityDashboards@2.14.0.0
   - queryWorkbenchDashboards@2.14.0.0
   - reportsDashboards@2.14.0.0
   - searchRelevanceDashboards@2.14.0.0
   - securityAnalyticsDashboards@2.14.0.0
   - securityDashboards@2.14.0.0

**Do you have any screenshots?**
![image-20240717-151021](https://github.com/user-attachments/assets/2cef6b3e-c86d-4d35-be0a-89c0586fdcad)
![image-20240725-142045](https://github.com/user-attachments/assets/09f99470-1946-4477-8962-bd58452309a5)

**Do you have any additional context?**
Add any other context about the problem.
This behavior was reproduced using various browser, OS

**Comment by pgoron** [comment]
Hi @jfwm2 , issue seems related to https://github.com/opensearch-project/OpenSearch/issues/14198, worth to check in 2.15.

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/andrross), [2](https://github.com/dblock), [3](https://github.com/AmiStrn), [4](https://github.com/reta), [5](https://github.com/finnegancarroll)]

**Comment by jfwm2** [comment]
Indeed upgrading to v2.15 seems to fix the issue. The autocomplete is still slowish but it does the job :+1: 
Thanks @pgoron!!
