### ISSUE TITLE
[BUG][Workspace]Dev server crashed after unassigning self from workspace owner

### ISSUE THREAD

**Issue by wanglam** [opensearch-project/OpenSearch-Dashboards#7639]
**Describe the bug**

Dev server crashes due to unhandled promise rejection when attempting to set default data source after the current workspace owner unassigns themselves, as they are removed from the workspace permission list before this operation.

**To Reproduce**

1.Clone main branch and run `yarn osd bootstrap`
2.Add below configs in `config/opensearch_dashboards.yml`
```
workspace.enabled: true
savedObjects.permission.enabled: true
data_source.enabled: true
uiSettings:
  overrides:
    'home:useNewHomePage': true
opensearchDashboards.dashboardAdmin.users: ['admin']
```
3.Run `yarn start --no-base-path`
4.Login with admin user and create a test user with `kibanauser` role
5.Create a workspace and set test user as a workspace owner
6.Login with test user and go to workspace detail page
7.Remove test user in `Collaborator` tab
8.Click `save` button and then the dev server will crashed

**Expected behavior**
Dev server should not be crashed, default data source should be set

**OpenSearch Version**
N/A

**Dashboards Version**
Latest main branch

**Plugins**
workspace

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
N/A

**Additional context**
#4944

**Comment by SuZhou-Joe** [comment]
closed because of #7636
