### ISSUE TITLE
[BUG] Discrepancy between generated NOTICE file and the file in the repository

### ISSUE THREAD

**Issue by tmarkley** [opensearch-project/OpenSearch-Dashboards#765]
**Describe the bug**

The [NOTICE](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1.0/NOTICE.txt) file that exists in the repository has been manually edited thus far, and it does not match the generated NOTICE file using the [notice generator](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1.0/src/dev/notice/generate_notice_from_source.ts).

**Expected behavior**
Use the notice generator to make changes to the NOTICE file instead of manual changes.

**Comment by joshuarrrr** [comment]
PR reverted over questions about year in notice. Once we discuss and resolve, we should be able to re-submit.

**Comment by tmarkley** [comment]
Dang, totally missed that. I'll fix it!

**Comment by ananzh** [comment]
@tmarkley may I assign you and remove untriaged label?

**Comment by tmarkley** [comment]
> @tmarkley I assigned you since you have started working on this issue. Should we remove the untriaged label?

@ananzh yes you can, I still don't have permissions to do that myself 😢

**Comment by ahopp** [comment]
@tmarkley still being a hero. 😉
