### ISSUE TITLE
[BUG] DQL Link in Syntax Options goes to unrelated query language

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/OpenSearch-Dashboards#769]
**Describe the bug**

Semi-related to #335 

In the Syntax Options popup in Discover, it provides a link to OpenSearch Dashboards Query Language. The current link goes to documentation for the Query DSL (through the `docs-beta` forward). Query DSL is unrelated to DQL. Currently there is no documentation on DQL and there is no active work being done on this at the moment. This would be very confusing for users who try to put Query DSL into the Discover page.

**To Reproduce**
1. Go to http://localhost:5601/app/discover#/
2. Click on DQL
3. Click on OpenSearch Dashboards Query Language
4. See wrong linked documentation

**Expected behavior**
Remove the link since the documentation doesn't exist.

**OpenSearch Version**
1.0.0

**Dashboards Version**
1.0.0

**Plugins**
All

**Additional context**

Seems to be sourced from here: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/06989dde6926cefd93ff8febbc2be7c3772dd45c/src/core/public/doc_links/doc_links_service.ts#L143 with the variable `kueryQuerySyntax`. There are a few other places where this is linked if you search the repo for `kueryQuerySyntax` - I think all of these links should be removed since there is no current work being done to document DQL. Additionally, references to 'kuery' in the code should be modernized.

**Comment by ahopp** [comment]
I agree with @stockholmux - I think we should remove the link for now but we need to open an issue in [doc site](https://github.com/opensearch-project/documentation-website/issues) so it's tracked somewhere long-term so we can continue to prioritize gaps or issues in documentation. 

@tmarkley @kavilla agree?
