### ISSUE TITLE
Visualizations should show the data in the dashboard having count greater than 1

### ISSUE THREAD

**Issue by Bhalaji21297** [opensearch-project/OpenSearch-Dashboards#7698]
In Opensearch dashboard, I want to create "data table" visualization. 

In that visualization, I am filtering 125 data. Out of 125 data, my goal is to show only data's having count > 1 in the dashboard. 

Following are the configs 
Metric --> Aggregation --> Count
Bucket --> Split Rows --> Filters

Can you help me with the steps required to achieve my goal?

**Comment by dblock** [comment]
[Weekly Catch All Triage - [1](https://github.com/dblock)]

@Bhalaji21297 This may not be the best place to ask questions, try the OpenSearch public Slack, https://opensearch.org/slack.html
