### ISSUE TITLE
[BUG] get_keystore test using absolute path

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#773]
**Describe the bug**
Get_keystone checks if the path contains the word 'config'. However, if we have a branch with a name including the word 'config', the get_keystone test will fail on Jenkins because it is taking the branch name to create a new folder and validate against the absolute path. We should not test against an absolute path because we should only care about what is within the opensearch dashboard application but not the path outside of opensearch dashboards.

**To Reproduce**
1. Create a branch and name it with the word 'config'
2. Go to Jenkins
3. Build
4. See error log under unit test: get_keystore test failed

**Screenshots**
<img width="834" alt="Screen Shot 2021-09-08 at 6 26 11 PM" src="https://user-images.githubusercontent.com/43937633/132606869-503f4d12-09a6-42d9-9968-303bde1c8a18.png">

**Comment by Aigerim-ai** [comment]
Hi can I take this issue?

**Comment by Aigerim-ai** [comment]
Hi @abbyhu2000, How can I "go to Jenkins"? Do I need specific repository to run?

**Comment by abbyhu2000** [comment]
Hi @Aigerim-ai, `Jenkins` is used to be the main automation tool for our CICD. It might be difficult for you to access our Jenkin pipeline. However, you can still finish this task without using Jenkin. 

The problematic unit tests are below in `src/cli_keystore/get_keystore.test.js`. If you read the function `getKeystore()` in `src/cli_keystore/get_keystore.js`, the rules are pretty simple. If there is a existing data keystore, we return data keystore path; if not, we return the config keystore path. However, the unit tests here are just using `toContain('config')` and `toContain('data')` to verify if the function is returning the correct path. It assumes that if the path contains the word 'config', then the function correctly returns the config keystore file path; and vise versa.

Instead of assuming this, could you rewrite the following two unit tests so they are actually checking the function `getKeystore()`  returns the correct file path of either data keystore or config keystore?

```
  it('uses the config directory if there is no pre-existing keystore', () => {
    sandbox.stub(fs, 'existsSync').returns(false);
    expect(getKeystore()).toContain('config');
    console.log(getKeystore())
    expect(getKeystore()).not.toContain('data');
  });

  it('uses the data directory if there is a pre-existing keystore in the data directory', () => {
    sandbox.stub(fs, 'existsSync').returns(true);
    expect(getKeystore()).toContain('data');
    console.log(getKeystore())
    expect(getKeystore()).not.toContain('config');
  });
```
