### ISSUE TITLE
[BUG] Mapping service is not accessible from India

### ISSUE THREAD

**Issue by jkowall** [opensearch-project/OpenSearch-Dashboards#777]
**Describe the bug**

The mapping service cannot be served from India. This is a restriction that AWS has put in place that needs to be fixed. 

**To Reproduce**
1. Go to India
2. Click on a dashboard which uses mapping
3. Map does not render

**Expected behavior**
Map should render in India

**OpenSearch Version**
1.0

**Dashboards Version**
1.0

**Screenshots**
![image](https://user-images.githubusercontent.com/1859948/132753176-ea837627-397c-4549-aa16-3e3902deb487.png)
![image](https://user-images.githubusercontent.com/1859948/132753207-95ede34e-379e-4f93-8999-e56a37fbf7b3.png)

See: https://discuss.opendistrocommunity.dev/t/status-of-kibana-maps/5106/35

**Comment by kavilla** [comment]
Thanks @jkowall , pinging someone with insight.

**Comment by jkowall** [comment]
The AWS team is involved in the troubleshooting already and they have a plan, it will just take some time to fix it per the forum discussion. Thanks.

**Comment by tusharrcrm** [comment]
I am still facing the same issue for AWS managed opensearch. I am from india region.

Error : The OpenSearch Maps Service is currently not available in your region

You can configure OpenSearch Dashboards to use a [custom map](https://opensearch.org/docs/latest/dashboards/visualize/maps/#adding-a-custom-map) server for dashboards maps.
