### ISSUE TITLE
Adding links to plugin documentation

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#778]
**Is your feature request related to a problem? Please describe.**

There exists some good readme's for plugin development within the OpenSearch Dashboards core Readme e.g. [/src/core/README.md](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/README.md). The only reason i found this was while debugging an issue. There was no mention of this in the [DEVELOPER_GUIDE.md](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md)or in the [Opensearch Dashboard's website](https://opensearch.org/docs/dashboards/index/)

**Describe the solution you'd like**

Add the following links to the developer guide:
- https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/core/README.md
- https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/packages/osd-plugin-generator

These were just the two that i could find, but i could have missed more that could be useful while we create better documentation for development and plugin development

**Describe alternatives you've considered**

Adding the links to the Dashboards website

**Additional context**

**Comment by kavilla** [comment]
Hey @ashwin-pc , I agree! Actually just created an issue https://github.com/opensearch-project/documentation-website/issues/171 today because of the same reasons!

Did we want to modify the issue I opened in the doc repo to include your recommendations as well or just move this issue over completely and reference the issue.

**Comment by ashwin-pc** [comment]
Modifying the issues sounds better to me. I'd prefer keeping them both open since having the links in both places is better for discoverability, and they are asking for changes in two separate places.

**Comment by sayuree** [comment]
Hi,  can you please assign this issue to me?
