### ISSUE TITLE
[BUG] query_enhancements "Get agent `os_query_assist_ppl` failed, reason: getting agent_id from undefined"

### ISSUE THREAD

**Issue by chishui** [opensearch-project/OpenSearch-Dashboards#7803]
**Describe the bug**
I'm testing query_enhancements's query assistant feature. When I input a natural language question, dashboard pops up error saying "Get agent 'os_query_assist_ppl'  failed, reason: configuration is undefined". 

It's because `configuration` is not in the response of getting agent API, it's `ml_configuration` now.

Sample response:
```
{
	"config_type": "os_query_assist_ppl_agent",
	"ml_configuration": {
		"agent_id": "nIy2MJEBu0iSk2-nBhti"
	}
}
```

**To Reproduce**

**Expected behavior**

**OpenSearch Version**
3.0.0

**Dashboards Version**
3.0.0

**Plugins**
query_enhancements

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by ruanyl** [comment]
closed by https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7804
