### ISSUE TITLE
[BUG][Workspace] Maximum call stack error in workspace detail page

### ISSUE THREAD

**Issue by wanglam** [opensearch-project/OpenSearch-Dashboards#7820]
**Describe the bug**

The workspace detail page show below error when enter workspace detail page
![image](https://github.com/user-attachments/assets/2a4b2083-4c6f-4a6d-8d10-12b99b830a8a)

**To Reproduce**
1. Go to 'workspace detail page'
2. Open devtools and check error logs

**Expected behavior**
Should not show maximum call stack error in the console

**OpenSearch Version**
N/A

**Dashboards Version**
Latest main

**Plugins**
N/A

**Screenshots**
See above.

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**
N/A

**Comment by ruanyl** [comment]
fixed in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7817
