### ISSUE TITLE
Bump EUI library to last AL2 release

### ISSUE THREAD

**Issue by dbbaughe** [opensearch-project/OpenSearch-Dashboards#787]
There are some bug fixes, improvements, etc. in the last AL2 release that the OpenSearch-Dashboards doesn't have.

I see there is ongoing effort for forking https://github.com/opensearch-project/OpenSearch-Dashboards/issues/653

If the effort is minimal it would be nice to also bump the current EUI dep to the last AL2 release. (If it would take a lot of effort, then can ignore wasted work and just focus on #653)

**Comment by kavilla** [comment]
Hey @dbbaughe, thanks for opening this up! I might not have the context provided for the bugs and improvements. Could you provide some examples?

**Comment by dbbaughe** [comment]
You can read the changelog
https://elastic.github.io/eui/#/package/changelog

We appear to be using version [29.3.2](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/package.json#L121)

The license change appears to have happened for version 35.0.0 which means we could technically bump up to 34.6.0 possibly?
So just take a look at all the changes from 29.3.2 up to 34.6.0 to see what has been fixed and added etc.

**Comment by tmarkley** [comment]
Hey Drew, thanks for calling this out! 

There are quite a few breaking changes between 29.3.2 and 34.6.0: https://github.com/elastic/eui/blob/v34.6.0/CHANGELOG.md

This means that we'd need to target a major version release to adhere to SemVer and not break plugins and plugin devs. I think this would make sense as a prerequisite to the forking/folding-in project (#695) to give us a good baseline to start from. @kgcreative what do you think?

**Comment by kgcreative** [comment]
I agree here. Short term, we should bump up to 29.5 to capture the most recent bug fixes and updates. After that, we should baseline to 34.6 as part of folding in. Beyond 34.6, we need to take control of the roadmap and audit EUI to see where it makes sense to evolve it.

**Comment by tmarkley** [comment]
@kgcreative definitely agree. We're going to target the upgrade to 34.6 as a part of the 2.0 release along with the Node.js upgrade.

**Comment by ahopp** [comment]
@AMoo-Miki did you see this? Wanted to validate given https://github.com/opensearch-project/OpenSearch-Dashboards/issues/695

**Comment by AMoo-Miki** [comment]
> @AMoo-Miki did you see this? Wanted to validate given #695

@ahopp, thanks for shoutout. As @tmarkley mentioned, a version bump will only be possible when the version of NodeJS required by Dashboards is bumped which is will occur with `v2.0.0`.

**Comment by tmarkley** [comment]
@AMoo-Miki we are on track to upgrade NodeJS to v14 for 2.0. Do you plan to upgrade EUI to 34.6 as part of the folding-in project? Will that work be ready for 2.0?

**Comment by AMoo-Miki** [comment]
@tmarkley, that is wonderful! This will enable us to fold in the last Apache-2.0 licensed EUI and Charts, targetting Dashboards v2.0.

**Comment by kavilla** [comment]
We will be bumping EUI and Charts first, and then folding in EUI to OpenSearch Dashboards.

**Comment by AMoo-Miki** [comment]
> We will be bumping EUI and Charts first, and then folding in EUI to OpenSearch Dashboards.

I, initially, wanted to combine them both and raised a PR for that but after discussions, we decided to do them bump and fold separately. #1252 will deal with the bump followed by a few PRs to fold in and deal with other issues.

**Comment by kavilla** [comment]
Closing issue since this was completed!
