### ISSUE TITLE
[Build] De-couple and support to build win32 x64

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#796]
**Is your feature request related to a problem? Please describe.**

When running `yarn build --skip-os-packages` it will build 4 tarballs for Dashboards (2x linux, 1x macOS, 1x windows) and takes 10+min to do so.

A previous PR #795 has de-coupled the build process for linux. However, de-couple windows is a bit different. The node_download_info task downloads nodejs from`https://nodejs.org/dist/v${version}/win-x64/node.exe` for windows which is not able to be executed in every platform (for example, linux). Windows doesn't have a tarball like linux. 

**Describe the solution you'd like**
The reason we need to download and unzip the tarball from `https://nodejs.org/dist/v${version}/win-x64/node.exe` is to get nodejs license info and then add it to our docs. This license info is the same for both windows and linux. An easy way is to also download and unzip linux-x64 tar for windows and use info from there. 

**Describe alternatives you've considered**

**Comment by AMoo-Miki** [comment]
This is solved with #2601.
