### ISSUE TITLE
[Feature Request] Embed Pipe Processing Language (PPL) to GUI

### ISSUE THREAD

**Issue by getkub** [opensearch-project/OpenSearch-Dashboards#806]
**Is your feature request related to a problem? Please describe.**
As mentioned by https://github.com/opendistro-for-elasticsearch/pipe-processing-language , it is great to have a single language for data analytics, alerting, aggregation etc.

**A clear and concise description of what the problem is. Ex. I'm always frustrated when**
Piped Processing Language (PPL),  users with exploration and discovery of, and finding search patterns in data stored in Elasticsearch, using a set of commands delimited by pipes (|). These are essentially read-only requests to process data and return results.

**Describe the solution you'd like**
Implementation of PPL as described in: https://github.com/opendistro-for-elasticsearch/pipe-processing-language

**Comment by ahopp** [comment]
Hey @getkub have you seen https://github.com/opensearch-project/piped-processing-language? I think this is what you're looking for but wanted to validate before closing. 

Documentation can be found [here](https://opensearch.org/docs/search-plugins/ppl/index/#piped-processing-language).

**Comment by getkub** [comment]
thanks @ahopp. Hopefully it will develop fast. You can resolve this request.
