### ISSUE TITLE
[BUG] Discover page stuck in an infinite loop

### ISSUE THREAD

**Issue by n9** [opensearch-project/OpenSearch-Dashboards#8159]
**Describe the bug**

Click on OpenSearch Dashboards > Discover opens page that seems stuck in an infinite loop.

**To Reproduce**
1. Click on Menu > OpenSearch Dashboards > Discover:
  ![image](https://github.com/user-attachments/assets/85dbcd82-0c0c-4984-bb18-9624ae54c526)
2. See "Searching": 
  ![image](https://github.com/user-attachments/assets/87ea08c1-7103-4b47-abb3-1e63cd92ba1a)
3. After a while Browser (Chrome) will "Page Unresponsive":
  ![image](https://github.com/user-attachments/assets/3d2fd4dd-a0f8-446a-90d9-98a5e387c2a2)
  Path in browser is: `/app/data-explorer/discover#?_a=(discover:(columns:!(_source),isDirty:!f,sort:!()),metadata:(indexPattern:'',view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_q=(filters:!(),query:(language:kuery,query:''))`

**Expected behavior**
Page will not stuck in an infinite loop.

**OpenSearch Version**
2.16.0

**Dashboards Version**
2.16.0

**Plugins**
![image](https://github.com/user-attachments/assets/a97044e6-eb6e-4998-884f-05ae784f4c0f)

**Screenshots**
See steps.

**Host/Environment (please complete the following information):**
 - OS: Windows
 - Browser and version: Chrome 128.0.6613.120

**Additional context**
- Stuck page eats CPU.
- Page does not react to clicks, back, reload.
- Seems like an infinite loop in JavaScript.

**Comment by Hailong-am** [comment]
> Maybe same as #7626?

yes, that will fixed in 2.17

**Comment by CCongWang** [comment]
Thanks @Hailong-am for the info, link PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8082
