### ISSUE TITLE
[BUG] Google Chrome v129 Discover screen - CSS class eui-xScrollWithShadows placing a big red layer over all the logs details

### ISSUE THREAD

**Issue by rcaferraz** [opensearch-project/OpenSearch-Dashboards#8250]
**Describe the bug**

After updating Google Chrome to the version 129.x I started to see a red layer over the log details in the discover screen.

**To Reproduce**
1. Open Google Chrome version 129.x
2. Go to Discover screen to show some log events
3. At the top of the screen, as usual, there will be shown the log events over a time line, and below that, the list of log events for you to expand and see the details.
4. Click at any one of those log events below the time line to expand the details.
5. See the error: there will be a big red layer over all the info that you would like to read, making the screen unusable.

**Expected behavior**
There shouldn't be any red layer over the details of the logs.

**OpenSearch Version**
Not sure

**Dashboards Version**
v2.11.0

**Plugins**
Not sure if we have any

**Screenshots**

![image](https://github.com/user-attachments/assets/feda3f60-9410-4e66-bdd1-2b18650481a8)
![image](https://github.com/user-attachments/assets/812a6a27-28ae-4e7f-aa5a-9715a6c08de1)

**Host/Environment (please complete the following information):**
 - OS: Microsoft Windows 11 Pro 23H2
 - Browser and version: Google Chrome v129.0.6668.59 64 bits

**Additional context**
The problem seems to be related to the CSS class eui-xScrollWithShadows as shown in the second image above.

**Comment by rcaferraz** [comment]
By the way, if you need a workaround for that, you can paste the code below on your `Chrome Dev Tools console`. The red layer will turn into a colorful transparent gradient (I didn't find a way to remove it entirely):

```
(function(){
    let style = `<style>
.eui-xScrollWithShadows{
        -webkit-mask-image: linear-gradient(to right, #f719636e, #7aff006b 100%)
    }
</style>`;

document.head.insertAdjacentHTML("beforeend", style);
})();
```

Before pasting the code above:
![image](https://github.com/user-attachments/assets/bed13c4a-4e23-42f5-87e2-fbd225ee5205)

After pasting the code above:
![image](https://github.com/user-attachments/assets/a84a0f73-514e-47de-b87d-e25ace43aacd)

**Comment by AMoo-Miki** [comment]
I reproduced this on OSD from `main` and Chrome 129.

**Comment by AMoo-Miki** [comment]
@rcaferraz thanks for the investigation you did. Chrome 129 and 130 have a problem with rendering of `mask-image` which seems to be tied to the `overflow`. If the `overflow` attributes are turned off on the parent, the mask renders correctly. I noticed other on the internet had other kinds of issues with this combination.

The cleanest solution I could come up with was to have Chrome contain the painting of the elements using mask images. This has the least impact on the browser and everything around it. Other tricks like `transform: translate?(0)`, or `transform-style: preserve-3d` add work to the browser but `contain: paint` reduces the workload of the browser by instructing it to not bother with how the element bleeds out.

A PR is on the way.

**Comment by ashwin-pc** [comment]
I've opened an issue on the chromium channel with reproduction steps: https://issues.chromium.org/issues/368562242

**Comment by AMoo-Miki** [comment]
After digging some more, the Chrome bug manifests with a combination of nested overflows, negative margin, border-radius, position absolute, and of course the mask-image.

**Comment by rcaferraz** [comment]
Thanks a lot, folks! I'm amazed on how quick this was fixed. If it isn't asking too much, can you please let me know in which version this fix will be available? Is it in `2.17.1` (according to the label this issue received)?

**Comment by ashwin-pc** [comment]
Yes that is correct. We are working with the release team to put out a patch for this asap

**Comment by stefansundin** [comment]
Here's my workaround:

```javascript
const s=document.createElement("style");
document.head.appendChild(s);
s.sheet.insertRule('.eui-xScrollWithShadows { mask-image: none !important; }');
```

You can create a ["bookmarklet"](https://en.wikipedia.org/wiki/Bookmarklet) with this URL for a simple one-click fix:

```
javascript:(function(){const s=document.createElement("style");document.head.appendChild(s);s.sheet.insertRule('.eui-xScrollWithShadows { mask-image: none !important; }');})();
```

**Comment by ashwin-pc** [comment]
Is anyone able to reproduce this issue with the legacy table?

<img width="709" alt="Screenshot 2024-09-25 at 11 48 01 AM" src="https://github.com/user-attachments/assets/8c8b1ecc-4422-4b11-818c-fb37e261cabd">

**Comment by rlevytskyi** [comment]
With legacy view, this issue exists too.

**Comment by kinseii** [comment]
On version 2.12.0, the problem persisted on both the new Discover and Legacy. I have consistently upgraded to 2.17 and the problem on the Legacy Discover is gone, it is only on the new Discover.
@ashwin-pc

**Comment by ashwin-pc** [comment]
2.17.1 that was ju7st released shoud fix it for both tables :)

**Comment by kinseii** [comment]
Yes! It works in 2.17.1! Thanx a lot!

**Comment by ssantichaivekin** [comment]
My company is using AWS OpenSearch Service and AWS told us they won't pick up this update until Oct 25.

We added the following to our Chrome extension and set it to run when we open any OpenSearch dashboard sites:
```javascript
(function () {
    setTimeout(() => {
        let style = `<style>
.eui-xScrollWithShadows{
        -webkit-mask-image: unset;
    }
</style>`;

        document.head.insertAdjacentHTML("beforeend", style);
    }, 3000); // wait 3 seconds before running
})();
```
Which fixed the issue.

Want to share this in case it's helpful to people using AWS OpenSearch Service. 😄

**Comment by Streethawk27** [comment]
@ssantichaivekin Could you explain please, how to add this to the extension? Is it the osearch extension?
Thanks.

**Comment by Streethawk27** [comment]
@ssantichaivekin i figured out how to add the code.Thanks

**Comment by oliveirahelder** [comment]
Hey, still happening on my end!

![Screenshot_104](https://github.com/user-attachments/assets/3c9e0914-c462-4158-8c57-6b181d42ee56)

**Comment by oliveirahelder** [comment]
Well, ther's a workaroud, and it worked for me!
![7RXHQTciYY](https://github.com/user-attachments/assets/e70e1274-2b73-480c-92c5-8f7f0309079f)

**Comment by ashwin-pc** [comment]
@oliveirahelder which version of OpenSearch Dashboards are you running and where?

**Comment by oliveirahelder** [comment]
v 2.11.0

**Comment by LunaticoCR** [comment]
> Here's my workaround:
> 
> ```js
> const s=document.createElement("style");
> document.head.appendChild(s);
> s.sheet.insertRule('.eui-xScrollWithShadows { mask-image: none !important; }');
> ```
> 
> You can create a ["bookmarklet"](https://en.wikipedia.org/wiki/Bookmarklet) with this URL for a simple one-click fix:
> 
> ```
> javascript:(function(){const s=document.createElement("style");document.head.appendChild(s);s.sheet.insertRule('.eui-xScrollWithShadows { mask-image: none !important; }');})();
> ```

This is gold! Thanks @stefansundin !

**Comment by gwharton** [comment]
Opensearch 2.18 Issue still present on Chrome Version 132.0.6834.160 (Official Build) (64-bit)

![Image](https://github.com/user-attachments/assets/fd2f3799-9db1-46af-b357-5d247bdfe8bf)
