### ISSUE TITLE
[BUG] Redirection issue for direct query datasource in dashboards management

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/OpenSearch-Dashboards#8256]
**Describe the bug**

When MDS is enabled, we are still having the card view in datasource detail page in here shows "query data in observability logs" and forwards user to log exploer page which should be disabled when MDS is enabled
Same redirecting action is also being applied for specific accelerations

**To Reproduce**
- enable MDS
- go to a direct query datasource's detail page
-  video

https://github.com/user-attachments/assets/f5f78804-d679-4a5c-8fbe-43d6262a5b72

**Expected behavior**
when MDS is enabled, it should be directed into Discover

**OpenSearch Version**
main

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

need dashboards observability plugin
**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by dblock** [comment]
[Catch All [Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta),  [3](https://github.com/krisfreedain),  [4](https://github.com/lukas-vlcek/)]

**Comment by RyanL1997** [comment]
Hi team, according to the recent gameday sanity testing, me and @ps48 observed that the current behavior of this re-direction is only handling the case for redirection to discover. The enhanced behavior should be:
- mds enabled: redirect to discover (https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8492 has handled that)
- mds disabled: keep the original redirection for log explorer 

According ot the above, I'm re-opening this issue, and I will update the description
