### ISSUE TITLE
Opensearch 1.0.0 incompatible with kibana 7.10.2

### ISSUE THREAD

**Issue by antonisnyc94** [opensearch-project/OpenSearch-Dashboards#830]
**Describe the bug**
Out of nowhere when I restarted my kibana instance, I get the message that the elasticsearch version is incompatible... even tho I clearly clicked on compatibility with 7.10.2 when upgrading Amazon elasticsearch

```
{"type":"log","@timestamp":"2021-09-23T17:04:31Z","tags":["info","savedobjects-service"],"pid":16,"message":"Waiting until all Elasticsearch nodes are compatible with Kibana before starting saved objects migrations..."}
{"type":"log","@timestamp":"2021-09-23T17:04:31Z","tags":["error","savedobjects-service"],"pid":16,"message":"This version of Kibana (v7.10.2) is incompatible with the following Elasticsearch nodes in your cluster: v1.0.0 @ undefined (undefined), v1.0.0 @ undefined (undefined), v1.0.0 @ undefined (undefined), v1.0.0 @ undefined (undefined), v1.0.0 @ undefined (undefined), v1.0.0 @ undefined (undefined), v1.0.0 @ undefined (undefined), v1.0.0 @ undefined (undefined)"}

```

**To Reproduce**
external kibana pod authenticated with basic auth to opensearch cluster in AWS

**Comment by CEHENKLE** [comment]
Transferring to Dashboards.  As you guys are looking at BWC, let's make sure we capture this case.

**Comment by kavilla** [comment]
OpenSearch Dashboards 1.x is compatible with ElasticSearch 7.10.2 and OpenSearch. But this is dealing with Kibana 7.x which we don't own.

**Comment by dblock** [comment]
@antonisnyc94 What version does `curl server:9200` report for your OpenSearch instance? It should be 7.10.2 in compatibility mode and I wouldn't expect Kibana to complain that it's talking to version 1.0.0.
