### ISSUE TITLE
[BUG] Filters persist when creating new searches or switching indices

### ISSUE THREAD

**Issue by msoler8785** [opensearch-project/OpenSearch-Dashboards#8338]
**Describe the bug**

When clicking "New" to create a new search any configured filters persist.  They are also persisted when changing indices.  This happens even though they are not pinned.

**To Reproduce**
1. Go to Discover
2. Create any filter
3. Click "New"
4. See filter persist.
5. Change Index
6. See filter persist.

**Expected behavior**
1. When a "New" search is created, all the unpinned filters are cleared.
2. When the selected index is changes, all unpinned filters are cleared.

**OpenSearch Version**
2.17

**Dashboards Version**
2.17

**Plugins**
[kibana-enhanced-table](https://github.com/fbaligand/kibana-enhanced-table)

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - OS: Windows 11
 - Microsoft Edge: 129.0.2792.52 (Official build) (64-bit) 
 - Firefox 130.0.1 (64-bit)
 - Chrome: 129.0.6668.70 (Official Build) (64-bit) (cohort: M129 Rollout) 

**Additional context**

**Comment by LDrago27** [comment]
Hi folks, The fix for this issue has been adressed in this PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8689 which has already been merged into main. Using
