### ISSUE TITLE
[BUG] Disabling Legacy Discover Display Red Overlay

### ISSUE THREAD

**Issue by msoler8785** [opensearch-project/OpenSearch-Dashboards#8357]
**Describe the bug**

Disabling the legacy overlay results in a red overlay that masks the table data.  This only happens in edge and chrome. Firefox does not exhibit this issue.  It occurs in incognito mode as well.

**To Reproduce**
1. Go to Discover
2. Click the settings gear
3. Disable legacy Discover Toggle
4. Observe the red overlay.

**Expected behavior**
The red banner is not overlaying the table

**OpenSearch Version**
2.17

**Dashboards Version**
2.17

**Plugins**
[kibana-enhanced-table](https://github.com/fbaligand/kibana-enhanced-table)

**Screenshots**
![image](https://github.com/user-attachments/assets/32b8a7d4-3d12-49b9-afac-cd8daab0af6a)

**Host/Environment (please complete the following information):**
 - OS: Windows 11
 - Microsoft Edge: 129.0.2792.52 (Official build) (64-bit) 
 - Chrome 129.0.6668.70 (Official Build) (64-bit) (cohort: M129 Rollout) 

**Additional context**
Doesn't appear to happen in Firefox

**Comment by msoler8785** [comment]
This appears to be a duplicate of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/8316

**Comment by dblock** [comment]
Closing as dup.
