### ISSUE TITLE
[BUG] Dashboards 2.13 is sending request with extra & in saved object api call

### ISSUE THREAD

**Issue by bandinib-amzn** [opensearch-project/OpenSearch-Dashboards#8379]
Dashboards 2.13 is sending request with extra `&` for below request, e.g.

`GET  _dashboards/api/saved_objects/_find?default_search_operator=AND&&has_reference=%7B%22type%22%3A%22visualization%22%2C%22id%22%3A%22a6a77010-241c-11ef-8df4-119560e0432f%22%7D&page=1&per_page=100&search_fields=title%5E3&search_fields=description&type=augment-vis`

this breaks the functionality of downstream service as they rely on standard query string pattern, which single question mark is used as a separator

**Comment by ashwin-pc** [comment]
@bandinib-amzn can you add any additional information here on how to reproduce the issue. Without reproduction steps it will be impossible to even vaidate the bug, much less fix it

**Comment by joshuali925** [comment]
The issue happens in the format call: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/64ed61bd9709b62d4fbc3de98656570e7e6bc782/src/core/public/http/fetch.ts#L151-L154

For testing I've changed the code to 
```ts
    const formatOptions = {
      pathname: shouldPrependBasePath ? this.params.basePath.prepend(options.path) : options.path,
      query: removedUndefined(query),
    };
    const url = format(formatOptions);
    console.log(JSON.stringify(formatOptions));
    console.log(url);
```

here is the response
```json5
{"pathname":"/api/saved_objects/_find","query":{"default_search_operator":"AND","fields":[],"has_reference":"{\"type\":\"visualization\",\"id\":\"b3e032c0-8b1a-11ef-a4c1-191794ea39d7\"}","page":1,"per_page":100,"search_fields":["title^3","description"],"type":"augment-vis"}}
/api/saved_objects/_find?default_search_operator=AND&&has_reference=%7B%22type%22%3A%22visualization%22%2C%22id%22%3A%22b3e032c0-8b1a-11ef-a4c1-191794ea39d7%22%7D&page=1&per_page=100&search_fields=title%5E3&search_fields=description&type=augment-vis
```

We can see the url has incorrect `&&`. But when running this on nodejs side, the formatted URL is correct
```sh
❯ node -e 'console.log(require("url").format({"pathname":"/api/saved_objects/_find","query":{"default_search_operator":"AND","fields":[],"has_reference":"{\"type\":\"visualization\",\"id\":\"b3e032c0-8b1a-11ef-a4c1-191794ea39d7\"}","page":1,"per_page":100,"search_fields":["title^3","description"],"type":"augment-vis"}}))'
/api/saved_objects/_find?default_search_operator=AND&has_reference=%7B%22type%22%3A%22visualization%22%2C%22id%22%3A%22b3e032c0-8b1a-11ef-a4c1-191794ea39d7%22%7D&page=1&per_page=100&search_fields=title%5E3&search_fields=description&type=augment-vis
```

Created upstream issue: https://github.com/defunctzombie/node-url/issues/72

**Comment by joshuali925** [comment]
#8611 should fix this, using that branch the url no longer contains `&&`
```
/api/saved_objects/_find?default_search_operator=AND&has_reference=%7B%22type%22%3A%22visualization%22%2C%22id%22%3A%22b3e032c0-8b1a-11ef-a4c1-191794ea39d7%22%7D&page=1&per_page=100&search_fields=title%5E3&search_fields=description&type=augment-vis
```
