### ISSUE TITLE
Support for tls v1.3 in opensearch-dashboards

### ISSUE THREAD

**Issue by aggarwalShivani** [opensearch-project/OpenSearch-Dashboards#838]
Description: 

(link to [original query]( https://discuss.opendistrocommunity.dev/t/support-for-tls-v1-3-in-opensearch-dashboards/6624/2))
Opensearch supports TLS v1.3 for both http and transport-layer communication. 
(Ref - https://github.com/opensearch-project/OpenSearch/blob/0ba0e7cc26060f964fcbf6ee45bae53b3a9941d0/libs/ssl-config/src/main/java/org/opensearch/common/ssl/SslConfiguration.java#L69)

However, **opensearch-dashboards also does not support tls 1.3 yet.** (Ref - https://github.com/opensearch-project/OpenSearch-Dashboards/blob/9a2d3e6918760c4bba8b44b9e8dfcd14e459a916/src/core/server/http/ssl_config.ts#L72)

Issue: As a result, if opensearch runs with tls 1.3 enabled for http communication, opensearch-dashboard would fail to connect to opensearch and wont start.
Note - In kibana, TLS 1.3 is supported only from 7.11.0 and not available in older versions i.e. 7.10 from which opensearch-dashboards is derived.

This feature is to request support for tls 1.3.

**Comment by aggarwalShivani** [comment]
Hi, 
Can you help us with the plan for supporting TLS 1.3 on Opensearch-dashboards? There is no update from last 1yr and we're really looking forward to move to TLS 1.3.

**Comment by scrawfor99** [comment]
@kajetan-nobel could you leave a comment so you can be assigned to this issue? Thank you :)

**Comment by kajetan-nobel** [comment]
@scrawfor99 Sorry, I didn't see that 😅. So - I'm on it :)

**Comment by davidlago** [comment]
Ready for review now.
