### ISSUE TITLE
[BUG] Discover add time range filtering using alias which is not supported in PPL 

### ISSUE THREAD

**Issue by xinyual** [opensearch-project/OpenSearch-Dashboards#8556]
**Describe the bug**

Now in query assistant, after generating PPL according to the natural language input, the discover UI will add time filtering if customer choose time interval like "in the last 15 minute" and run. And it will use time field of the target index. But we can set alias time field when config index and alias is not supported by PPL.

**To Reproduce**
1. Set an index with alias time field. For example, time2 is alias for time1
2. Create the index pattern and choose time2 as time field
3.  Go to discover page, generate a simple PPL like "how many docs inside the index", it will generate something like "source=<index pattern> | stats count"
4. choose time interval like last 15 minutes and click run
5. The networks shows error
<img width="1652" alt="image" src="https://github.com/user-attachments/assets/4921fc1d-87b6-4932-9bb6-e0b5d76fef4e">

**Expected behavior**
When appending time range, we should find the true field name for alias field.

**OpenSearch Version**
Latest 2.x

**Dashboards Version**
Latest 2.x

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by ashwin-pc** [comment]
Alias fields need to be supported in the SQL engine. They have noticed this and added an exception here https://github.com/opendistro-for-elasticsearch/sql/issues/941 and ive created a new issue to support alias fields in PPL here. https://github.com/opensearch-project/sql/issues/3069. Closing this as OSD should not be responsible to housing this logic.
