### ISSUE TITLE
[BUG] Discover Saved Search filters are not populated

### ISSUE THREAD

**Issue by atalakey4work** [opensearch-project/OpenSearch-Dashboards#8645]
**Describe the bug**

When we open a previously created saved search the filters are not populated.

**To Reproduce**
1. Go to 'Discover'
2. Select an index pattern.
3. Add a filter.
4. Save the search.
5. Go into 'Discover' again
6. Open the saved search created on step 4.

**Expected behavior**
Filters are present when a saved search is opened

**OpenSearch Version**
2.26.0

**Dashboards Version**
2.24.0

**Plugins**

opensearch-alerting 2.17.1.0
opensearch-anomaly-detection 2.17.1.0
opensearch-asynchronous-search 2.17.1.0
opensearch-cross-cluster-replication 2.17.1.0
opensearch-custom-codecs 2.17.1.0
opensearch-flow-framework 2.17.1.0
opensearch-geospatial 2.17.1.0
opensearch-index-management 2.17.1.0
opensearch-job-scheduler 2.17.1.0
opensearch-knn 2.17.1.0
opensearch-ml 2.17.1.0
opensearch-neural-search 2.17.1.0
opensearch-notifications 2.17.1.0
opensearch-notifications-core 2.17.1.0
opensearch-observability 2.17.1.0
opensearch-performance-analyzer 2.17.1.0
opensearch-reports-scheduler 2.17.1.0
opensearch-security 2.17.1.0
opensearch-security-analytics 2.17.1.0
opensearch-skills 2.17.1.0
opensearch-sql 2.17.1.0
opensearch-system-templates 2.17.1.0
query-insights 2.17.1.0

**Screenshots**

<img width="1440" alt="Screenshot 2024-10-18 at 9 14 44 AM" src="https://github.com/user-attachments/assets/1d1f2411-a31b-4970-97dd-9699c2ed12d6">
<img width="1122" alt="Screenshot 2024-10-18 at 9 15 13 AM" src="https://github.com/user-attachments/assets/e1c232c6-97ce-408e-b7dc-9a317d3802ea">

**Host/Environment (please complete the following information):**
 - OS: Container image (opensearchproject/opensearch, opensearchproject/opensearch-dashboards)
 - Browser and version: Chrome v129.0.6668.101

**Additional context**

Copy of kibanaSavedObjectMeta.searchSourceJSON

`{
  "query": {
    "query": "",
    "language": "kuery"
  },
  "highlightAll": true,
  "version": true,
  "aggs": {
    "2": {
      "date_histogram": {
        "field": "@timestamp",
        "fixed_interval": "30s",
        "time_zone": "Asia/Riyadh",
        "min_doc_count": 1
      }
    }
  },
  "filter": [
    {
      "meta": {
        "alias": null,
        "negate": false,
        "disabled": false,
        "type": "phrase",
        "key": "kubernetes.namespace_name",
        "params": {
          "query": "nginx-ingress"
        },
        "indexRefName": "kibanaSavedObjectMeta.searchSourceJSON.filter[0].meta.index"
      },
      "query": {
        "match_phrase": {
          "kubernetes.namespace_name": "nginx-ingress"
        }
      },
      "$state": {
        "store": "appState"
      }
    }
  ],
  "indexRefName": "kibanaSavedObjectMeta.searchSourceJSON.index"
}`

**Comment by coderjoe** [comment]
After upgrading opensearch and opensearch dashboards to 2.17.1 via helm chart versions 2.26.0 and 2.24.0 respectively we're experiencing something similar.

All existing saved searches do not load their filter criteria when opened in the user interface.
However exporting the saved searches still shows the criteria in the ndjson file.

Re-importing the search does not cause the filter criteria to show up.
Modifying the saved searches appears to cause all prior criteria to be lost.

This is causing a rather large user backlash so we're contemplating downgrading and restoring an old backup.

**Comment by pukarlamichhane** [comment]
what is the best or stable version to used for production of it

**Comment by zhyuanqi** [comment]
@abbyhu2000  Could you help?

**Comment by coderjoe** [comment]
Upon further review I believe my problem and possibly this bug is a duplicate of #8339

**Comment by atalakey4work** [comment]
Downgrading Dashboards to v2.16 with OpenSearch 2.17 resolve the issue as a work around. Still waiting for a permanent fix.

**Comment by atalakey4work** [comment]
Issue resolved in latest release
