### ISSUE TITLE
2.18-Release

### ISSUE THREAD

**Issue by SebastianThorn** [opensearch-project/OpenSearch-Dashboards#8982]
Why is not the dashboards-released at the same time as OpenSearch on GitHub?

https://github.com/opensearch-project/OpenSearch/releases/tag/2.18.0
https://opensearch.org/docs/latest/dashboards/

The container seems to be built at the same time?
https://hub.docker.com/r/opensearchproject/opensearch/tags?name=2.18
https://hub.docker.com/r/opensearchproject/opensearch-dashboards/tags?name=2.18

**Comment by dblock** [comment]
I think you're just missing a tag on GitHub?

**Comment by dblock** [comment]
@peterzhuamazon

**Comment by SebastianThorn** [comment]
Pinging people that have done releases in the past.
* @abbyhu2000 
* @zhyuanqi 
* @LDrago27

**Comment by LDrago27** [comment]
@SebastianThorn Added the dashboard-release tag corresponding to 2.18.0.  The release corresponding to 2.18.0 version was already done before, It is just the tag that was missing.

**Comment by SebastianThorn** [comment]
@LDrago27 Thanks!
The Dashboards-release some times lags behind the release of OpenSearch.
Is there some way this could be fixed or controlled so it does not occur in the future again?

Br Sebastian Thörn
