### ISSUE TITLE
[BUG] Navigating to Discover page from a visualization or dashboard with filters applied "persists" those filters to the Discover page

### ISSUE THREAD

**Issue by neodescis** [opensearch-project/OpenSearch-Dashboards#8985]
**Describe the bug**

If currently viewing a visualization or dashboard with filters applied, navigating to the Discover page will cause those filters to be there on the Discover page.

I do not know if it is relevant, but we do have storeInSessionStorage enabled.

**To Reproduce**
1. Go to a dashboard with saved filters, OR go to a visualization and add regular filters (not pinned/global)
2. Click on the hamburger menu, then click Discover
3. See filters from the dashboard or visualization applied to the Discover page

**Expected behavior**
Filters from the dashboard or visualization should *not* be there on the Discover page

**OpenSearch Version**
2.17.1

**Dashboards Version**
2.17.1

**Plugins**
Reporting, security

**Host/Environment (please complete the following information):**
 - Windows 11
 - Chrome 131.0.6778.86

**Additional context**

This appears to have been caused by [this pull request](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8168), as commenting out the change fixes this issue.

**Comment by Habeebah157** [comment]
Can I take this please

**Comment by AMoo-Miki** [comment]
@ashwin-pc @kavilla correct me if i am wrong but I believe this is the intended behavior.

We should maybe add an advanced setting to allow users to choose if they don't want context being carried over. This will also include Specific Dashboard -> other page -> Dashboards taking the user back to previous dashboard.

**Comment by neodescis** [comment]
> @ashwin-pc @kavilla correct me if i am wrong but I believe this is the intended behavior.
> 
> We should maybe add an advanced setting to allow users to choose if they don't want context being carried over. This will also include Specific Dashboard -> other page -> Dashboards taking the user back to previous dashboard.

I don't believe this is intended behavior. Generally, filters (unless pinned) do not carry over between Discover/Dashboards/Visualize.

However, as of 2.18.0, Discover no longer does this. As such, I'm going to close the issue.
