### ISSUE TITLE
Customize Dashboards UI

### ISSUE THREAD

**Issue by pietrogu** [opensearch-project/OpenSearch-Dashboards#902]
Hi,

I would like to have the possibility to customize the UI, for example:

- Using a custom logo
- Change main colors
- Having themes other than light and dark
- Pass a style CSS (something similar to what happens in MISP project

**Comment by kavilla** [comment]
Hey @pietrogu! For 1.2 or if you forked this project and pull from `main` or `1.x`, you can set the following:

> Using a custom logo
```
# opensearchDashboards.branding:
  # logo:
    # defaultUrl: ""
    # darkModeUrl: ""
  # mark:
    # defaultUrl: ""
    # darkModeUrl: ""
  # loadingLogo: 
    # defaultUrl: ""
    # darkModeUrl: ""
  # faviconUrl: ""
  # applicationTitle: ""
```

**Comment by pietrogu** [comment]
Hi, 

is there already a doc on how to correctly use this fields in the config file?

**Comment by ahopp** [comment]
@pietrogu we don't have it formalized in the docs yet, but we've opened [this ](https://github.com/opensearch-project/documentation-website/issues/241)issue to have it included. Might be a helpful place to start.

**Comment by pietrogu** [comment]
Thank you so much!
