### ISSUE TITLE
[BUG] OpenSearch Dashboards build script references env node version

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#908]
**Describe the bug**

[Here](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/dev/build/tasks/bin/scripts/opensearch-dashboards#L20) we reference `NODE="/usr/local/bin/node"` but first we check the node executable first `[ -x "${DIR}/node/bin/node" ]`.  If the executable exists we should be using it ie line 20 should say `NODE=${DIR}/node/bin/node`.

Issue on Darwin when running node 16 globally.

**Expected behavior**
If building for node 10.24.1, we should use the node executable if its available.

**OpenSearch Version**
`Unreleased 1.2`

**Dashboards Version**
`Unreleased 1.2`

**Plugins**

n/a

**Screenshots**

n/a

**Host/Environment (please complete the following information):**
Darwin

**Additional context**

Change came in for allowing FreeBSD, will seek guidance to make sure we do not just undo what we did for FreeBSD.

**Comment by smortex** [comment]
That looks like an error that slept through the multiple iterations of reworking the FreeBSD support Pull Request.

```diff
 if [ -x "${DIR}/node/bin/node" ]; then
-  NODE="/usr/local/bin/node"
+  NODE="${DIR}/node/bin/node"
 else
   NODE="$(which node)"
 fi
```
