### ISSUE TITLE
[BUG] "Experimental" banner when editing maps visualization

### ISSUE THREAD

**Issue by jcgraybill** [opensearch-project/OpenSearch-Dashboards#933]
**Describe the bug**

In OpenSearch Dashboards when editing a maps visualization, a banner appears that states: "Map layer is experimental and is not subject to the support SLA of official GA features. For feedback, please create an issue in GitHub." This seems to be residual from prior to the fork, since "support SLA" and "official GA features" aren't part of the OpenSearch project lifecycle. Nix this banner.

**Requirements**

* Remove the banner
* Fix any test failures if any
* Backport to 2.x
* Create issues for missing items for why this was still marked as experimental
* If it doesn't exist create it, but if there are more features marked as experimental create subsequent issues/story.

**Comment by jcgraybill** [comment]
Clarifying, this is a Vega maps visualization. https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/vis_type_vega/public/components/experimental_map_vis_info.tsx

**Comment by tmarkley** [comment]
Thanks for documenting this! The Controls visualization has the same message: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/800
