### ISSUE TITLE
[D&D] Add Field summary view

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#950]
Add a field summary view to the available fields in the side panel

![Screen Shot 2022-01-03 at 4 51 11 PM](https://user-images.githubusercontent.com/46726078/147995598-e13ff6c6-8071-4442-8a22-f27248ed77ff.png)

**Comment by ashwin-pc** [comment]
This is on hold for now since the field summary component from discover does not display an accurate summary of all the data and is in its current state kinda misleading. @joshuarrrr Can you comment on our plan for this?

**Comment by joshuarrrr** [comment]
Yeah, the plan for now is to port over as much of the existing Discover field summary functionality as makes sense, which will help with consistency and user familiarity. In the future, #1995 is where we'll iterate, refine, and improve on the user experience in both applications.

**Comment by joshuarrrr** [comment]
@btzeng I have a couple questions now that I have a working prototype implemented:

1. Do we want the "+" button on the field, like in Discover? In Discover, it's a quick action to add that field as a column. In VisBuilder, it would probably be something like a quick-add, and behave equivalently to dragging the field to the main canvas. But since we haven't yet implemented that, I suggest we skip for now.
2. What about the "Visualize" button below the value charts? I could similarly see this being useful as a type of quick-start action, but similarly suggest we skip for now.

**Comment by btzeng** [comment]
@joshuarrrr   The second one is a very nice feature.   @ahopp are these planed for any targeted release?
1. This one needs more work. For example when clicking on the "+" button, can the app figure out where the field should be added to- metric or bucket. Right now we have a solid flow that requires the user to drop directly to metric or bucket. Or click the + button directly in the field under metric or bucket to configure. 
2. Nice to have feature that takes the user directly to visualize to build a chart. *some fields have this visualize button, some don't. But I'd say for the fields that have the visualize button, we'll eventually add it in the summary view.

**Comment by btzeng** [comment]
> @btzeng I have a couple questions now that I have a working prototype implemented:
> 
> 1. Do we want the "+" button on the field, like in Discover? In Discover, it's a quick action to add that field as a column. In VisBuilder, it would probably be something like a quick-add, and behave equivalently to dragging the field to the main canvas. But since we haven't yet implemented that, I suggest we skip for now.

@joshuarrrr  We can skip the "+" button on the filed. For accessibility, we already have the "+" button in the data configuration panel where user can click to select field (works the same as dropping in a field).

> 2. What about the "Visualize" button below the value charts? I could similarly see this being useful as a type of quick-start action, but similarly suggest we skip for now.

Let's skip this for now. Long term we can think about what quick action we want to prioritize if needed.
