### ISSUE TITLE
[D&D] Visualization type selector

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#954]
Add a visualization type selector above the canvas on the workspace

![Screen Shot 2021-11-17 at 2 23 06 AM](https://user-images.githubusercontent.com/20453492/142182974-e204cba9-807d-4829-acb1-05154b78220d.png)

**Comment by kavilla** [comment]
@btzeng do we have a new mock for this.

**Comment by kavilla** [comment]
Not a release blocker for drag and drop.

**Comment by btzeng** [comment]
@kavilla  Yes, in the new mock the chart type select is moved to the right.
<img width="1702" alt="chart type" src="https://user-images.githubusercontent.com/93013804/179582005-54c8d8fb-c77a-4c51-b62a-5f266cd0e5be.png">

**Comment by joshuarrrr** [comment]
This will be on hold for now, with #2011 in its place.

**Comment by ashwin-pc** [comment]
The exit criteria here will be to 
- Move the Style panel from the Left hand side of the workspace to the right hand side
- Place the Visualization type picker into the right hand panel
- Make both the left and right hand side panels collapsible and resizable (With min and max constraints)

**Comment by ashwin-pc** [comment]
The type picker will be added in two stages. For the 2.x release we will use the SuperSelect component and in 3.0, we will use an updated component from OUI that matches the final style.

**Comment by ashwin-pc** [comment]
Followup issue created here: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2216
