### ISSUE TITLE
[D&D] Add to Dashboard directly from editor

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#960]
Add the ability to directly save and add the visualization to a new/existing Dashboard directly from this experience.

Blockers:
* Need UX mocks @btzeng (could be in meta issue)

Requirements:
* Implementation
* Tests

**Comment by abbyhu2000** [comment]
This issue addresses the user flow: 
1. Select a specific dashboard from the dashboard page
<img width="1188" alt="Screen Shot 2022-09-16 at 4 47 46 PM" src="https://user-images.githubusercontent.com/43937633/190831267-bac45ee9-da2d-463f-8ff7-681b26d826f2.png">

2. Create a new wizard or edit an existing wizard directly on that dashboard by clicking `Edit` on the top right corner of the dashboard
<img width="1713" alt="Screen Shot 2022-09-16 at 4 48 30 PM" src="https://user-images.githubusercontent.com/43937633/190831308-ab56752f-d081-431a-a1da-ce44b9433a38.png">

**Comment by ashwin-pc** [comment]
Closing this issue the core functionality has been implemented. The functional tests are tracked separately and cancel issue is not slated for 2.4.

**Comment by ashwin-pc** [comment]
Closing this issue the core functionality has been implemented. The functional tests are tracked separately and cancel issue is not slated for 2.4.
