### ISSUE TITLE
[Feature] custom links for clickable visualization elements

### ISSUE THREAD

**Issue by mmguero** [opensearch-project/OpenSearch-Dashboards#976]
**Describe the solution you'd like**

Enriching dashboards with on-the-fly lookups in other tools could be implemented by allowing the user to define custom URL templates for elements in visualizations (e.g., a value in a table or chart).

For example, a network traffic analysis tool could use this feature to configure an IP address or file hash field to provide a link to a VirusTotal IP lookup, port or protocol numbers to link to IANA, etc. I do something very similar to this in [Arkime by defining value actions](https://github.com/idaholab/Malcolm/blob/main/arkime/wise/source.zeeklogs.js#L1003-L1035).

It would open up another level of customization to allow custom links/URLs/contexts/whatever you want to call it for OpenSearch Dashboards visualizations.

**Describe alternatives you've considered**

This is possible in other (Elastic-based) products:

* [Inserting Links in Kibana Dashboards](https://thenewstack.io/inserting-links-kibana-dashboards/)
* elastic/kibana#12560
* [goodlabs-studio/kibana-plugin-drilldownmenu](https://github.com/goodlabs-studio/kibana-plugin-drilldownmenu)
* [Arkime's Value Actions](https://arkime.com/settings#right-click)

**Comment by ahopp** [comment]
@mmguero Did you want to take a look at this [issue ](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1248)(and associated [design](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1308)) and see if this meet you ask?

**Comment by mmguero** [comment]
@ahopp thanks for pointing me to those links! yes, i believe that feature (particularly the drill-down to external URLs, as mentioned [here](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1308#issuecomment-1059430323)) would take care of what I'm trying to do. The bit in that comment about ` Select variable (optional) ` may be a little bit limiting: for me, if we could allow the user to pass both a variable/field as well as the currently-selected time range (e.g., start/stop query time frame with UNIX seconds/milliseconds or ISO format or whatever) would be best. I'll close this issue and comment on that one.
