### ISSUE TITLE
dashboards startup error

### ISSUE THREAD

**Issue by linruoma** [opensearch-project/OpenSearch-Dashboards#979]
![image](https://user-images.githubusercontent.com/90311807/143230660-a89006eb-d47b-4eff-af65-69baf6a75583.png)
No special configuration is made, but an error is reported during startup

**Comment by kavilla** [comment]
Hello @linruoma! can you provide some of these details here:

* Plugins currently enabled
* Host/Environment

I see the security plugin is installed. Are you running from this repo, or are you running from a release?

**Comment by linruoma** [comment]
My installation method is Tarball, I changed version 1.1.0, this error disappeared, the previous version was 1.0.0, after installing opensearch and changing config, then I ran opensearch-tar-install.sh* under the opensearch directory , then started the opensearch service, then downloaded opensearch-dashboards, and started the opensea-dashboards service, then above error was reported, but the error disappeared after I changed the version. Another question is whether opensearch-tar-install.sh* must be run if no security plug-in is required

**Comment by kavilla** [comment]
Gotcha, if you are taking the tarball (like the release tarball), that comes bundled up with plugins installed. If you don't actively disable the security plugin on OpenSearch ([here](https://opensearch.org/docs/latest/security-plugin/configuration/disable)) and uninstall the security plugin for OpenSearch Dashboards ([here](https://opensearch.org/docs/latest/dashboards/install/plugins/#remove-plugins)) then you will still need to do the one time run of the opensearch-tar-install.sh. The shell script setups your environment to prepare for the security plugin but the security plugin will still try to work and would fail.

If you use docker, I believe the image there is already setup so you don't have to run the install script but for the tarball you'll have to do it yourself or uninstall the security plugins if you don't need it.
