### ISSUE TITLE
[Node.js upgrade] Fix failing unit tests

### ISSUE THREAD

**Issue by tmarkley** [opensearch-project/OpenSearch-Dashboards#990]
### Background

Jest config: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/dev/jest/config.js

Jest script: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/scripts/jest.js

Changes can be pulled from the draft PR (#982) or a [node-14 branch](https://github.com/tmarkley/OpenSearch-Dashboards/tree/node-14).

### Details

There are two unit tests (and a handful of integration tests) failing with the following error:

```
$ yarn test:jest
...

Summary of all failing tests
 FAIL  src/core/server/legacy/legacy_service.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/ubuntu/ws/OpenSearch-Dashboards/node_modules/weak-lru-cache/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { LRFUExpirer, EXPIRED_ENTRY } from './LRFUExpirer.js'
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1270:14)
      at Object.<anonymous> (node_modules/lmdb-store/caching.js:1:115)

 FAIL  src/cli/cluster/cluster_manager.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/ubuntu/ws/OpenSearch-Dashboards/node_modules/weak-lru-cache/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { LRFUExpirer, EXPIRED_ENTRY } from './LRFUExpirer.js'
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1270:14)
      at Object.<anonymous> (node_modules/lmdb-store/caching.js:1:115)


Test Suites: 2 failed, 1 skipped, 1434 passed, 1436 of 1437 total
Tests:       24 skipped, 9 todo, 10681 passed, 10714 total
Snapshots:   2448 passed, 2448 total
Time:        56.181 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Troubleshooting steps

* Checked that we are using the correct babel-preset env with ts-babel which is correct; that is what we’re using
* Per https://github.com/nrwl/nx/issues/812, added the `weak-lru-cache` package to the `transformIgnorePatterns` property in the jest config.
    * This did not fix the unit tests but added another failing ~30 unit tests because they can’t find module definitions
* Tried adding a custom transform for babel-jest but it also doesn’t fix the issue
* Converting the `.babelrc` to `babel.config.js` is a recommended possible solution but it causes cascading errors 
* Tried setting `"type": "module"` in `package.json` but this breaks the `yarn osd bootstrap` script
* Removed `jest-enviroinment-jsdom-thirteen` and replaced it with `jest-environment-jsdom` - didn’t fix the error but we can keep the change
* Adding new compiler option to allow JS to all tsconfigs has no effect on the unit tests
* Upgraded jest from v25 to v27 - didn’t resolve existing errors and introduced new failing tests
* Adding the `--experimental-vm-modules` flag has no effect
* Upgrading `lmdb-store` to `lmdb@2.0.2` has no effect - tests still fail
* Replacing babel-jest with ts-jest for TypeScript files has no effect - tests still fail

**Comment by ashwin-pc** [comment]
The issue appears to be that `babel-jest` tries to transform `weak-lru-cache` and the `ordered-binary` npm modules. they already have a cjs transformed version that jest does not pick up unless ignored using the `transformIgnorePatterns` property. 

changing it to this should resolve the unit test errors
```
transformIgnorePatterns: [
  '[/\\\\]node_modules(?![\\/\\\\](monaco-editor|weak-lru-cache|ordered-binary))[/\\\\].+\\.js$',
  ...
],
```

**Comment by boktorbb-amzn** [comment]
> 

Yup that fixes it. I had 
```
transformIgnorePatterns: [
  '[/\\\\]node_modules(?![\\/\\\\](monaco-editor|lmdb-store|weak-lru-cache|ordered-binary))[/\\\\].+\\.js$',
  ...
],
```
with the extra `lmdb-store` package and it was causing issues

**Comment by tmarkley** [comment]
Thanks so much @ashwin-pc! Not sure how we overlooked that 😅
